### ISSUE TITLE
[UPDATE] Adding file structure for challenge website codes and other questions

### ISSUE THREAD

**Issue by ashwanisng** [HarshCasper/NeoAlgo#1]
DSA Questions Like Remove duplicate elements from the array.

**Comment by mar-galho** [comment]
Hi, the idea is to have basic implementation for DS & Algos.

Perhaps we can think of a way of dealing with questions in another moment, but that is outside the initial scope of the project.

**Comment by mar-galho** [comment]
However, I'd like @HarshCasper and @born-2learn to give me their input on this

**Comment by HarshCasper** [comment]
I think we can have them in a separate folder as well. This will help contributors to get started with applying DS-Algo Skills for real-world problem-solving. We can have Hackerrank, Codechef and Codeforces Solutions as part of this.

**Comment by mar-galho** [comment]
True. @ashwanisng, would you be willing to help us with that?

**Comment by ashwanisng** [comment]
@HarshCasper awesome idea 💯

**Comment by ashwanisng** [comment]
@ricardoprins I love to part of the org and contribute in it 👍

**Comment by mar-galho** [comment]
If you could fork the repo and set up a basic structure for these challenges then - perhaps they can even have their own folder, apart from the Language ones. What do you guys think about this?
