### ISSUE TITLE
Unique paths in a matrix

### ISSUE THREAD

**Issue by ag278** [HarshCasper/NeoAlgo#1014]
## 🚀 Feature

Find the unique paths in a matrix starting from the upper left corner and ending in the bottom right corner.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this problem in O(min(m,n)) time complexity and O(1) space complexity(where m,n are rows and columns of matrix ) as a part of CH20

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by ag278** [comment]
I would like to solve this issue in c++ as a part of CH20. Please assign me this issue @SKAUL05 @iamrajiv @Abhijit2505 @atarax665

**Comment by SangeetaMishra** [comment]
I would like to take this in C

**Comment by ritvij14** [comment]
I would like to take this in Java

**Comment by narayan2111** [comment]
I would like to work on this issue in python
