### ISSUE TITLE
Count no. of BST's with n Nodes 

### ISSUE THREAD

**Issue by muddhit** [HarshCasper/NeoAlgo#1031]
## 💥 Proposal

Total number of possible Binary Search Trees with n keys

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by muddhit** [comment]
I want to solve it in Java

**Comment by muddhit** [comment]
Plz assign it to me

**Comment by yashaswibiyahut** [comment]
i would like to work on this issue in cpp kindly assign me @iamrajiv @SKAUL05 @HarshCasper

**Comment by rgrupesh** [comment]
I want do this in Python. Please, assign me. @Kajol-Kumari @atarax665 @plazzy99

**Comment by SangeetaMishra** [comment]
I would like to take this in C
