### ISSUE TITLE
Zig Zag Conversion

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#1043]
## 🚀 Feature

The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

P   A   H   N
APL S  I I  G
Y   I     R
And then read line by line: "PAHNAPLSIIGYIR"

Write the code that will take a string and make this conversion given a number of rows:  string convert(string s, int numRows);

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Adding a new algorithm and hence making the repo more extensive.

Plz assign me this issue in java and c++

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.

**Comment by rutujadhanawade** [comment]
I would like to do this in python

**Comment by AshKnight99** [comment]
I would like to do this in java

**Comment by SangeetaMishra** [comment]
I would like to take this in C
