### ISSUE TITLE
Subset

### ISSUE THREAD

**Issue by Kritika37** [HarshCasper/NeoAlgo#1049]
## 🚀 Feature
Given a set of distinct integers, nums, return all possible subsets (the power set).
Input: nums = [1,2,3]
Output:
[
  [3],
  [1],
  [2],
  [1,2,3],
  [1,3],
  [2,3],
  [1,2],
  []
]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this issue as a part of CH20. Also, it involves core concepts like backtracking and recursion which are really important.

## Pitch

One of the important questions for interviews.

**Comment by Kritika37** [comment]
@HarshCasper @Abhijit2505 @iamrajiv @atarax665  @SKAUL05. I would like to implement this in C++ as a part of CH20. Please assign me this issue. Thank You

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.

**Comment by SangeetaMishra** [comment]
I would like to take in C for CH20

**Comment by salonishah01** [comment]
I would like to take this in Python for CH20

**Comment by imPGupta** [comment]
I want to contribute to this issue. Assign me either in **C** or **C++**.
@atarax665

**Comment by Kritika37** [comment]
@iamrajiv @atarax665 please see to it once
