### ISSUE TITLE
Valid Stack sequence

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#1052]
## 🚀 Feature

Given two sequences, pushed and popped with distinct values. Return true if and only if this could have been the result of a sequence of push and pop operations on an initially empty stack.

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Adding a new algorithm and hence making the repo more extensive.

Plz assign me this issue in java and c++

**Comment by SangeetaMishra** [comment]
Please assign this to me in C/C++ for CH20

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.

**Comment by narayan2111** [comment]
I would like to work on this issue in python  @iamrajiv  @HarshCasper  as a part of  hacktoberfest

**Comment by narayan2111** [comment]
Kindly assign this issue and labels to it @iamrajiv @plazzy99 @Abhijit2505 @Kajol-Kumari @atarax665

**Comment by ritvij14** [comment]
@narayan2111 I cannot do that, I am not a mentor 😅
