### ISSUE TITLE
Add LeetCode Problem (#237 - Delete Node in a Linked List)

### ISSUE THREAD

**Issue by HarshKhilawala** [HarshCasper/NeoAlgo#1060]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes,

Problem Link: https://leetcode.com/problems/delete-node-in-a-linked-list/
Providing Solution in Different Programming Languages to given mentioned Problem.

Write a function to delete a node in a singly-linked list. You will not be given access to the head of the list, instead, you will be given access to the node to be deleted directly.

It is guaranteed that the node to be deleted is not a tail node in the list.

Input: head = [4,5,1,9], node = 5
Output: [4,1,9]
Explanation: You are given the second node with value 5, the linked list should become 4 -> 1 -> 9 after calling your function.

Assignees:

Java: @HarshKhilawala
Python: @bagladivyang03
C++: @HarshKhilawala
C: @shraddhavp

**Comment by Kajol-Kumari** [comment]
@HarshKhilawala please update the issue template.

**Comment by HarshKhilawala** [comment]
@Kajol-Kumari Maybe could work on Java /C++

**Comment by SangeetaMishra** [comment]
I would like to take this in C/C++ for CH20

**Comment by AshKnight99** [comment]
I would like to take this in Java for CH20

**Comment by HarshKhilawala** [comment]
@Kajol-Kumari Kindly take a look

**Comment by bagladivyang03** [comment]
@Kajol-Kumari I would like to work in python for this pls add relevant labels and assign to all of us :)

**Comment by Kajol-Kumari** [comment]
Hey @HarshKhilawala I can't assign it to anyone as I don't understand what your issue is exactly about! Please provide a clear description for the issue so that we can figure out how you issue is different from what we already have in our codebase like [this one](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/ds/LinkedList.cpp).

**Comment by HarshKhilawala** [comment]
@Kajol-Kumari Sorry for the late response, I have added some description and linked it to the Problem. Please take a look and assign me for Java language , after assigning everyone, I will update the issue and after getting pull request merged for the same, the issue will be closed.

**Comment by HarshKhilawala** [comment]
@HarshCasper Please take a look and assign us for different roles. Its been very long since I created the issue which is just for the Solution of Leetcode Problems

**Comment by shraddhavp** [comment]
@Kajol-Kumari  and @iamrajiv  would like to take this issue in C

**Comment by bagladivyang03** [comment]
@HarshCasper pls assign me this in python
