### ISSUE TITLE
Add LeetCode Problem (#53 - Maximum Subarray) 

### ISSUE THREAD

**Issue by HarshKhilawala** [HarshCasper/NeoAlgo#1061]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes,

Link : https://leetcode.com/problems/maximum-subarray/description/

Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.

Example 1:
Input: nums = [-2,1,-3,4,-1,2,1,-5,4]
Output: 6
Explanation: [4,-1,2,1] has the largest sum = 6.

Example 2:
Input: nums = [1]
Output: 1

Example 3:
Input: nums = [0]
Output: 0

Example 4:
Input: nums = [-1]
Output: -1

Example 5:
Input: nums = [-2147483647]
Output: -2147483647

**Comment by Kajol-Kumari** [comment]
@HarshKhilawala Please update the issue template.

**Comment by HarshKhilawala** [comment]
@Kajol-Kumari It is just a problem and I have already mentioned the Problem number of Leet-Code Problem. Maybe that's enough

**Comment by SangeetaMishra** [comment]
I would like to take this in C/C++ for CH20

**Comment by SangeetaMishra** [comment]
This is same as #555

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari It is just a problem and I have already mentioned the Problem number of Leet-Code Problem. Maybe that's enough

Hey @HarshKhilawala It's not possible for us to go to a particular site and then get to know what the issue is after searching for that! That's the reason we have `issue template` so you need to provide proper description of the issue here only so that anyone can see from here directly what you issue is! Also as mentioned by @SangeetaMishra I think it's a duplicate of #555 so feel free to close this one.

**Comment by HarshKhilawala** [comment]
@Kajol-Kumari Sure, I wouldn't mind closing this issue but though as there is already Leetcode Folder in the Miscellaneous directory , It would have been nice to keep track of this question in that folder as it would have been easy for users who can easily find that
