### ISSUE TITLE
Rat in a Maze

### ISSUE THREAD

**Issue by sheenxavi004** [HarshCasper/NeoAlgo#1064]
## Rat in a Maze

The program is aimed to use backtracking to find the way in which a rat is trapped in a maze where 1 in the maze matrix indicates an obstacle. The program will print out all possible solution of the maze.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

@SKAUL05 @hushee69 @mechiragjain @jivthesh @gat786 
Provide me the permission to implement the problem in C Plus Plus

**Comment by SangeetaMishra** [comment]
I would like to take this in C/C++ for CH20

**Comment by sheenxavi004** [comment]
Please assign me this in C++ @SKAUL05 @hushee69 @mechiragjain

**Comment by hushee69** [comment]
@sheenxavi004 and @SangeetaMishra

You can do it and then create a pull request..you don't have to be necessarily assigned to it to be able to contribute..the pull request will then be approved.

Good luck..

**Comment by ritvij14** [comment]
I would like to take this in Java and/or Javascript if it's up for CH20.

**Comment by rutujadhanawade** [comment]
I would like to do this in Python
