### ISSUE TITLE
Valid Triangle Number

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#1066]
## 🚀 Feature

Given an array consists of non-negative integers, your task is to count the number of triplets chosen from the array that can make triangles if we take them as side lengths of a triangle.

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Adding a new algorithm and hence making the repo more extensive.

Plz assign me this issue in java and c++

**Comment by ritvij14** [comment]
I would like to take this in Java and/or Javascript for CH20

**Comment by salonishah01** [comment]
I would like to take this in python

**Comment by rutujadhanawade** [comment]
I would like to do this in C
