### ISSUE TITLE
Painter Partition problem

### ISSUE THREAD

**Issue by NEEHITGOYAL** [HarshCasper/NeoAlgo#1068]
## 💥 Proposal
You have to paint N boards of length {A0, A1, A2, A3 … AN-1}. There are K painters available and you are also given how much time a painter takes to paint 1 unit of board. You have to get this job done as soon as possible under the constraints that any painter will only paint contiguous sections of board. Return the ans % 10000003

Input Format
First line contains three space seperated integers N,K and T ,where
N = Size of array,
K = No of painters available ,
T = Time taken to print each board by one painter
Next line contains N space seperated positive integers denoting size of N boards.

Constraints
1<=N<=100000
1<=K<=100000
1<=T<=1000000
1<=Li<=100000

Output Format
Return minimum time required to paint all boards % 10000003.

Sample Input
2 2 5
1 10
Sample Output
50
Explanation
The first painter can paint the first board in 5 units of time and the second painter will take 50 units of time to paint the second board. Since both can paint simultaneously , the total time required to paint both the boards is 50.

**It is a really hard and good problem was asked in google 
It really helps in understanding binary search **

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by NEEHITGOYAL** [comment]
i would like to work on this issue in cpp as part of hakin codes
kindly add ch20 tag and assign this issue to me@Kajol-Kumari @SKAUL05 @siddharth25pandey 
@plazzy99

**Comment by salonishah01** [comment]
I would like to take up this issue in python

**Comment by ritvij14** [comment]
I would like to take this in Java  for CH20

**Comment by rutujadhanawade** [comment]
I would like to do this in C

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ankitaggarwal23** [comment]
I would like to contribute in this issue in C++

**Comment by manasisaiba** [comment]
I would like to contribute in this issue in C++
