### ISSUE TITLE
Welcome Contributors 

### ISSUE THREAD

**Issue by anushkrishnav** [HarshCasper/NeoAlgo#1084]
Hello, Everyone ✨🙌

Thanks for showing your interest in being a part of this ever-growing community 💥

We are super delighted to have you on board for your Contributions on [NeoAlgo](https://github.com/TesseractCoding/NeoAlgo) 🙌

Project Maintainers:

| Name 📛                |                       Social Media #️⃣                       |                                 Github 🐱‍💻 |
| ---------------------- | :---------------------------------------------------------: | -------------------------------------------: |
| Aanisha Bhattacharyyai |                        [LinkedIn]()                         |         [Github](https://github.com/Aanisha) |
| Abhinav Anand          |                        [LinkedIn]()                         |       [Github](https://github.com/atarax665) |
| Ankit Aggarwal         |  [Linkedln](https://www.linkedin.com/in/aggarwalankit23/)   | [Github](https://github.com/ankitaggarwal23) |
| AnushKrishnav          |           [Website](https://anushkrishnav.rocks/)           |   [Github](https://github.com/anushkrishnav) |
| Harsh Bardhan Mishra   |          [Website](http://harshbardhanmishra.me/)           |     [Github](https://github.com/HarshCasper) |
| Rajiv Ranjan Singh     | [LinkedIn](https://www.linkedin.com/in/iamrajivranjansingh) |        [Github](https://github.com/iamrajiv) |
| Ricardo Prins          |            [Website](https://www.iamprins.com/)             |    [Github](https://github.com/ricardoprins) |
| Syed Farhan Ahmad      |                        [LinkedIn]()                         |     [Github](https://github.com/born-2learn) |
| Vijaya Gajanan Buddha  |                        [LinkedIn]()                         |      [Github](https://github.com/VijayaGB98) |

Events :

Here are some 12 Rules, you should be following while working on an Open-Source to have a great experience during the whole process:

- Be Nice, Be Respectful (BNBR)
- Check if the Issue you created, exists or not.
- Make proper commit messages and document your PR well.
- Always add Comments in your Code and explain it at points if possible add Doctest.
- Dynamic Input is always preferred over static Driver Code.
- Squash your commits before you push them.
- Always create a Pull Request from a Branch; Never from the Master.
- Follow proper Code conventions. Using I, j in Loops shows a poor understanding of Code Quality. Use proper Variable, Function Names.
- Issues would be served on a "First Come, First Serve" basis.
- Issues would be tagged as Easy, Medium, Hard. Scores would be assigned to the difficulty of the Issue you solve.
- Code would be reviewed by Maintainers before they are merged. Every PR requires 3 Reviews.
- No person can take up more than 2 Issues at a single point of time.

<b>Regards,</b>
<i>Team TesseractCoding</i> 🤗

**Comment by Tanmay2510** [comment]
Hey, I would like to contribute can you suggest me way to get started?
