### ISSUE TITLE
Knapsack Problem

### ISSUE THREAD

**Issue by Preetesh21** [HarshCasper/NeoAlgo#1093]
## 💥 Proposal

Program for the DP problem Knapsack

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

I would like to contribute in C and C++ language.

**Comment by ritvij14** [comment]
Possible duplicate of #423
