### ISSUE TITLE
Postfix Expression Evaluation

### ISSUE THREAD

**Issue by smv1999** [HarshCasper/NeoAlgo#1102]
## 🚀 Feature

Given a postfix expression (as a string), the program must print the result after evaluating the expression.
For example:
Input:
73426^*+*8+

Output:
1821

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This helps in better understanding of stacks

## Pitch

This problem helps to have a grip over stack operations
Happy Coding!

**Comment by smv1999** [comment]
@SKAUL05 @Abhijit2505 @HarshCasper @iamrajiv @siddharth25pandey @Kajol-Kumari  I would like to work on this issue in C . Please assign me this issue!

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20

**Comment by salonishah01** [comment]
I would like to take this in python

**Comment by Mohitkumar6122** [comment]
@SKAUL05 @Abhijit2505 @HarshCasper @siddharth25pandey I would like to work on this issue in C++.

**Comment by imPGupta** [comment]
I want to contribute to this. Assign me either in **C#** or **C++**.
@plazzy99

**Comment by smv1999** [comment]
@imPGupta I have already requested to work on this issue in C (Please find the comment thread above). Kindly request this to be assigned to you in some language other than the ones mentioned above.
