### ISSUE TITLE
DNF SORT

### ISSUE THREAD

**Issue by gayatri517** [HarshCasper/NeoAlgo#1108]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
 The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
(Write your answer here.)
Yes
I would like to add this in file in the C++ section, please assign it to me.

**Comment by salonishah01** [comment]
I would like to add to this in python

**Comment by ritvij14** [comment]
I would like to do this in Java for CH20

**Comment by mukuakhilesh** [comment]
I can do this in C++.

**Comment by rutujadhanawade** [comment]
I would like to do this in C

**Comment by atarax665** [comment]
@gayatri517 Can you be more descriptive about the problem? eg- Add few test cases to so that contributors can have better insight of the issue.

**Comment by gayatri517** [comment]
DESCPRIPTION:
For this problem, your goal is to sort an array of 0, 1 and 2's but you must do this in place, in linear time and without any extra space (such as creating an extra array).

Example 1:
Input: array = [2,0,2,1,1,0]
Output: [0,0,1,1,2,2]

Example 2:
Input: array = [2,0,1]
Output: [0,1,2]

Example 3:
Input: array= [0]
Output: [0]

@atarax665
