### ISSUE TITLE
PrintAllPossibleCode_Recursion

### ISSUE THREAD

**Issue by sukritidawar** [HarshCasper/NeoAlgo#1111]
## 🚀 Feature
Given a string s, and assuming that a=1, b=2, c=3, d=4, .... z=26, write a recursive function to print all the possible codes for the strings.
Example:
s = "1123"
Output:
aabc
aaw
alc
kbc
kw

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Helps in understanding recursion.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by sukritidawar** [comment]
I want to work on this issue in C++

**Comment by ritvij14** [comment]
I would like to work on this in Java for CH20

**Comment by narayan2111** [comment]
I would like to work on this issue in python

**Comment by rutujadhanawade** [comment]
I would like to do this in C

**Comment by ritvij14** [comment]
@Kajol-Kumari for this can we completely omit an input if any of the digits is 0?
