### ISSUE TITLE
A* Algorithm

### ISSUE THREAD

**Issue by amoghatsunil** [HarshCasper/NeoAlgo#1112]
A* algorithm is a Path finding algorithm that searches for the shortest path between the initial and the final state. 

@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper
Please assign me this issue, I Would like to implement this in Python

**Comment by ritvij14** [comment]
I would like to do this in Java for CH20

**Comment by rutujadhanawade** [comment]
I would like to do this in python

**Comment by UtkarshChaurasia** [comment]
I would like to implement this algorithm in C++ as a part of Hactoberfest 2020.
