### ISSUE TITLE
Rain Water Harvesting

### ISSUE THREAD

**Issue by NEEHITGOYAL** [HarshCasper/NeoAlgo#1116]
## 💥 Proposal

A ver popular problem asked in interviews medium difficulty
Apoorvaa has created an elevated roof. She wants to know how much water can she save during rain.

Given n non negative integers representing the elevation map where width of every bar is 1, Find the maximum water that she can save.

Explanation for the Sample input Testcase: 
![image](https://user-images.githubusercontent.com/44130067/94519631-84921880-0248-11eb-8515-416d81534168.png)
So the total units of water she can save is 5 units

**Input Format**
First line contains an integer n. Second line contains n space separated integers representing the elevation map.

**Constraints**
1 <= N <= 10^6

**Output Format**
Print a single integer containing the maximum unit of waters she can save.

**Sample Input**
10
0 2 1 3 0 1 2 1 2 1
**Sample Output**
5
**Explanation**
Refer to the image for explanation. Count the number of cells having water in them.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by NEEHITGOYAL** [comment]
i would like to work on this issue in c++ as part of hakin codes @plazzy99 @Kajol-Kumari @SKAUL05 @HarshCasper

**Comment by salonishah01** [comment]
I would like to work on the problem in python.

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20

**Comment by vatsalkesarwani12** [comment]
@NEEHITGOYAL - C++
@salonishah01  - python
@ritvij14 - Java

**Comment by bagladivyang03** [comment]
@plazzy99 i would like to do in C

**Comment by vatsalkesarwani12** [comment]
@bagladivyang03 - C
