### ISSUE TITLE
Search Insert Position

### ISSUE THREAD

**Issue by bagladivyang03** [HarshCasper/NeoAlgo#1119]
## 💥 Proposal

Given a sorted array and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.

You may assume no duplicates in the array.

Example 1:
Input: [1,3,5,6], 5
Output: 2

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by bagladivyang03** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505  @HarshCasper Pls assign me this in C++ and also add labels and count it in Hakin
 Codes too :)

**Comment by vatsalkesarwani12** [comment]
@bagladivyang03 - Cpp

**Comment by rutujadhanawade** [comment]
I would like to do this in java

**Comment by vatsalkesarwani12** [comment]
@rutujadhanawade - Java assigned

**Comment by ag278** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper I would like to do this in C language. Please assign me this issue

**Comment by rjn01** [comment]
I would like to do this in python. Can you assign me? @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper

**Comment by bagladivyang03** [comment]
#1173

**Comment by bagladivyang03** [comment]
Search Insert Position Cpp #1173

**Comment by 2tanayk** [comment]
I would like to do this in Javascript @HarshCasper

**Comment by rjn01** [comment]
@plazzy99 I want to work on this issue using Python. Earlier I commented as a CH20 participant but hasn't been assigned. Can I take this issue for HacktoberFest

**Comment by MuhammadTanveer94** [comment]
I would like to do this in Javascript @bagladivyang03

**Comment by vatsalkesarwani12** [comment]
> @plazzy99 I want to work on this issue using Python. Earlier I commented as a CH20 participant but hasn't been assigned. Can I take this issue for HacktoberFest

yes you can

**Comment by vatsalkesarwani12** [comment]
> I would like to do this in Javascript @bagladivyang03

assigned you with javascript

**Comment by LON3WO7F** [comment]
> ## boom Proposal
> 
> Given a sorted array and a target value, return the index if the target is found. If not, return the index where it would be if it were inserted in order.
> 
> You may assume no duplicates in the array.
> 
> Example 1:
> Input: [1,3,5,6], 5
> Output: 2
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> 
> Yes

@bagladivyang03 Please assign this to me.
I would like to do it in python.
