### ISSUE TITLE
Binary Tree Sum Replacement

### ISSUE THREAD

**Issue by reethikprasad** [HarshCasper/NeoAlgo#1122]
## 🚀 Feature

To find the sum of child nodes in binary tree

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

## Motivation

There is a common trick which people ignore that is storing data into temp

## Pitch

After creation of binary tree my aim is to create another binary tree with nodes replaced with sum of child node

8 10 1 -1 -1 6 9 -1 -1 7 -1 -1 3 -1 14 13 -1 -1 -1

before replacement
8 
10 3
1 6 14
9 7 13

After Replacement
63
23 27
1 16 13
9 7 13

**Comment by reethikprasad** [comment]
Would like to contribute in C++ as a part of HakinCodes2020.

@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99  @HarshCasper

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20

**Comment by rutujadhanawade** [comment]
I would like to take this in python for CH20
