### ISSUE TITLE
readme updation

### ISSUE THREAD

**Issue by NEEHITGOYAL** [HarshCasper/NeoAlgo#1125]
## 📚 Documentation
i want to update all these readme files in total there are 10 readme files i am updating so kindly can you label this issue with 20 points 
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/cp/README.md
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/cryptography/README.md
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/dp/README.md
https://github.com/TesseractCoding/NeoAlgo/tree/master/C-Plus-Plus/ds
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/graphs/README.md
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/math/README.md
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/other/README.md
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/search/README.md
https://github.com/TesseractCoding/NeoAlgo/tree/master/C-Plus-Plus/sort
https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/blockchain/README.md

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by NEEHITGOYAL** [comment]
i want to update all these readme 
in total there are 10 files

**Comment by atarax665** [comment]
@NEEHITGOYAL No need of opening a new issue for readme update, you can directly put a pull request and mention me there so that I can approve it.
