### ISSUE TITLE
Count Distinct Elements in Every Window

### ISSUE THREAD

**Issue by sukritidawar** [HarshCasper/NeoAlgo#1133]
## 🚀 Feature
Given an array and the size of a window (k), print the number of distinct elements for every window.
Example:
1. Input: arr[] = {10, 20, 20, 10, 30, 40, 10}, k = 4
   Output: 2 3 4 3
2. Input: arr[] = {10, 10, 10, 10}, k = 3
    Output: 1 1
3. Input: arr[] = {10, 20, 30, 40}, k = 3
    Output: 3 3

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Helps in enhancing problem-solving.

## Pitch

Helps in understanding concepts of arrays and hashing.

## Assignees

- C-Plus-Plus: @sukritidawar
- C: @imPGupta 
- Go:
- Java: @rutujadhanawade
- JavaScript:
- Python: @narayan2111

**Comment by sukritidawar** [comment]
I want to work on this issue in c++

**Comment by imPGupta** [comment]
I want to contribute on this issue. Assign me to this in **C++**.
@iamrajiv

**Comment by rutujadhanawade** [comment]
I want to do this in java

**Comment by narayan2111** [comment]
I would like to work on this issue in python

**Comment by narayan2111** [comment]
Kindly assign this issue ASAP @iamrajiv sir, so that we can work and get merged this PR by 2nd of October

**Comment by Kajol-Kumari** [comment]
> I want to contribute on this issue. Assign me to this in **C++**.
> @iamrajiv

Hey @imPGupta as @sukritidawar has already claimed for c++, I can't assign it to you. Rest of the people, please go ahead :)

**Comment by imPGupta** [comment]
Okay. Then assign me this issue in **C**.
@Kajol-Kumari
