### ISSUE TITLE
Stable Marriage Problem

### ISSUE THREAD

**Issue by Preetesh21** [HarshCasper/NeoAlgo#1134]
## 💥 Proposal
The Stable Marriage Problem states that given N men and N women, where each person has ranked all members of the opposite sex in order of preference, marry the men and women together such that there are no two people of the opposite sex who would both rather have each other than their current partners. If there are no such people, all the marriages are “stable” 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Preetesh21** [comment]
I would like to work in C and C++ languages. Kindly assign it to me.

**Comment by salonishah01** [comment]
I would like to work in python.

**Comment by rutujadhanawade** [comment]
I want to do this in java

**Comment by anushkrishnav** [comment]
I have assigned the issue . Have a great day
