### ISSUE TITLE
A* Algorithm

### ISSUE THREAD

**Issue by amoghatsunil** [HarshCasper/NeoAlgo#1138]
## 💥 Proposal

A* is a pathfinding algorithm, A* is a variant of Dijkstra's algorithm, A* assigns a weight to each open node equal to the weight of the edge to that node plus the approximate distance between that node and the finish. This approximate distance is found by the heuristic and represents a minimum possible distance between that node and the end. This allows it to eliminate longer paths once an initial path is found.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Assignees

- C-Plus-Plus: @rutujadhanawade 
- C:
- Go:
- Java: @bagladivyang03 
- JavaScript:
- Python: @amoghatsunil

**Comment by amoghatsunil** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper Please assign me this issue
 I would like to implement this in python  and please add labels.

**Comment by anushkrishnav** [comment]
Assigned. Make sure you follow proper coding and formatting standards. Have a great day

**Comment by rutujadhanawade** [comment]
I would like to this in C++ as a part of CH20

**Comment by bagladivyang03** [comment]
I would like to do this in java pls assign me this :)

**Comment by ritvij14** [comment]
I would like to do this in Javascript for CH20

**Comment by SangeetaMishra** [comment]
I would like to take this in C

**Comment by ritvij14** [comment]
@amoghatsunil please remove my name as I would like to skip this issue.

**Comment by Nirali0029** [comment]
Please assign this to me for python
