### ISSUE TITLE
cp sets question

### ISSUE THREAD

**Issue by bagladivyang03** [HarshCasper/NeoAlgo#1175]
## 💥 Proposal
There is an array of n integers. There are also 2 disjoint sets, A and B, each containing m integers. You like all the integers in set A and dislike all the integers in set B. Your initial happiness is 0. For each i integer in the array, if i.e.  A, you add 1 to your happiness. If i.e. B, you add -1 to your happiness. Otherwise, your happiness does not change. Output your final happiness at the end.

Input Format

The first line contains integers n and m separated by a space.
The second line contains n integers, the elements of the array.
The third and fourth lines contain m integers, A and B, respectively.

Output Format

Output a single integer, your total happiness.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Assignees

- C-Plus-Plus: @SangeetaMishra
- C-Sharp:
- C: @imPGupta
- Go:
- Java: @Vaibhav-Ganatra
- JavaScript:
- Python: @bagladivyang03
- Q-Sharp:

**Comment by bagladivyang03** [comment]
@plazzy99 @siddharth25pandey @Kajol-Kumari @HarshCasper @iamrajiv  pls assign me this in python and add relevant labels too pls :)

**Comment by SangeetaMishra** [comment]
I would like to take this in C++

**Comment by imPGupta** [comment]
I want to contribute to this. Assign me either in **C** or **C++**.

**Comment by ganatra-v** [comment]
@HarshCasper I would like to do this in Java
