### ISSUE TITLE
Dijkstra's Algorithm- Python implementation

### ISSUE THREAD

**Issue by reachpranjal** [HarshCasper/NeoAlgo#1180]
## 💥 Proposal

Task- Given a graph and a source vertex in the graph, find the shortest paths from source to all vertices in the given graph.
Dijkstra’s algorithm is very similar to Prim’s algorithm for minimum spanning tree. Like Prim’s MST, we generate an SPT (shortest path tree) with a given source as root. We maintain two sets, one set contains vertices included in the shortest-path tree, another set includes vertices not yet included in the shortest-path tree. At every step of the algorithm, we find a vertex that is in the other set (set of not yet included) and has a minimum distance from the source.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by reachpranjal** [comment]
Please assign me the task. I'm ready with the code.

**Comment by rutujak24** [comment]
I will take this issue.

**Comment by atarax665** [comment]
@reachpranjal Do check the existing issues before opening a new one. This is a duplicate issue for #47 . Kindly comment there and wait for a project maintainer to assign you the issue in your preferred language.

**Comment by atarax665** [comment]
@rutujak24 Please comment on #47 and do not pull a request before you are assigned the issue.
