### ISSUE TITLE
Adding User Input

### ISSUE THREAD

**Issue by reachpranjal** [HarshCasper/NeoAlgo#1182]
## 🚀 Feature

The python implementation to find the area of geometric shapes is static. Adding a user input feature to it will make the code reusable.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Code Reusability

## Pitch

It could be performed on any number of data and any number of times

**Comment by reachpranjal** [comment]
Please assign the task. I have done the implementation.

**Comment by atarax665** [comment]
@reachpranjal Assigning you this issue, do check the other files in the repository for static input. If you find any just add dynamic inputs code and and raise a PR.

**Comment by rishigarg94** [comment]
hey, i have resolved this issue pls assign it to me, i will create a pr as soon i will be assigned this issue
