### ISSUE TITLE
Polynomial Regression

### ISSUE THREAD

**Issue by reachpranjal** [HarshCasper/NeoAlgo#1184]
## 💥 Proposal

Polynomial Regression is a form of linear regression in which the relationship between the independent variable x and dependent variable y is modeled as an nth degree polynomial. Polynomial regression fits a nonlinear relationship between the value of x and the corresponding conditional mean of y, denoted E(y |x). The goal of polynomial regression is to model a non-linear relationship between the independent and dependent variables (technically, between the independent variable and the conditional mean of the dependent variable).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by reachpranjal** [comment]
The code is ready. Please assign me the task.

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.
