### ISSUE TITLE
All possible sums using FFT

### ISSUE THREAD

**Issue by Rishabh7896** [HarshCasper/NeoAlgo#1195]
## 💥 Proposal<br>
We are given two arrays a[] and b[]. We have to find all possible sums a[i]+b[j], and for each sum count how often it appears.

Let the size of array a be n and array b be m.<br>

### Brute Force Approach:
You traverse through all the elements in <b>O(n&lowast;m)</b>, and generate all possible sums then store at some location. Now the size of the generated sums is (n&lowast;m)=p. Now you check the frequency of the new elements which takes <b>O(p*p)</b>.
<b>Efficiency: O(n&lowast;m+p&lowast;p) = O(n&lowast;m+n&lowast;m&lowast;n&lowast;m) = O(n<sup>2</sup>*m<sup>2</sup>)</b>
<b>Optimized Brute Force Approach:</b>
You can use hashmaps to store the generated sums and obtain the frequency in <b>O(n&lowast;m&lowast;log(n&lowast;m)).</b>
<b>Efficiency: O(n&lowast;m&lowast;log(n&lowast;m))</b>

### Using Fast Fourier Transform:
We construct for the arrays a and b two polynomials A and B. The numbers of the array will act as the exponents in the polynomial (a[i]⇒x<sup>a[i]</sup>); and the coefficients of this term will by how often the number appears in the array.

Then, by multiplying these two polynomials in O(nlogn) time, we get a polynomial C, where the exponents will tell us which sums can be obtained, and the coefficients tell us how often. To demonstrate this on the example:
<p align="center"><b>a[ ]={1, 2, 3}, b[ ]={2, 4} </b>can be written into <b>(1x<sup>1</sup>+1x<sup>2</sup>+1x<sup>3</sup>)(1x<sup>2</sup>+1x<sup>4</sup>)=1x<sup>3</sup>+1x<sup>4</sup>+2x<sup>5</sup>+1x<sup>6</sup>+1x<sup>7</sup></b></p>

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
<b> Yes </b>

**Comment by Rishabh7896** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper @iamrajiv
Please assign me this issue
I would like to implement this in C++ and please add labels.

**Comment by salonishah01** [comment]
I would like to take up the issue in python.

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20

**Comment by rutujadhanawade** [comment]
I would like to do this in C
