### ISSUE TITLE
Add Linear Search Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#12]
**Algorithm:** 

[Linear Search](https://en.wikipedia.org/wiki/Linear_search#:~:text=In%20computer%20science%2C%20a%20linear,whole%20list%20has%20been%20searched.)

**DS:** 

- Searching

**Languages Missing:**

- Java [ Assigned to @MSufiyanAG ]

**Comment by UtkarshChaurasia** [comment]
Can I work on this for the languages C++, JAVA and Python?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @UtkarshChaurasia 

The Code for Java has already been added. You can work with C++ and Python instead. 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by guri76148** [comment]
can i work in javascript?

**Comment by omonimus1** [comment]
Hi to everyone. 
I have created a [pull request](https://github.com/TesseractCoding/NeoAlgo/pull/31) for this issue, adding the implementation of the Linear search algorithms in JavaScripts (will all the tests). 
You can easily test all the source code in a few seconds on [jsfiddle](https://jsfiddle.net/).

The tests run from the pipeline do not pass, can I get any advice about the type of checks done on every pull request? :)

I would like to fix the pull request ASAP and do it properly. 
Thank you  :)

**Comment by sparkingdark** [comment]
I want to work it on C @HarshCasper

**Comment by HarshCasper** [comment]
I have assigned you the Issue @sparkingdark

**Comment by HarshCasper** [comment]
You can start working on it @sparkingdark

**Comment by sparkingdark** [comment]
Thanks ready to work

**Comment by pixan198** [comment]
@HarshCasper I want to work on this in JavaScript

**Comment by MSufiyanAG** [comment]
@ricardoprins  i would like to work on this in java . and i completed #13 please merge it  its pr is #138 .

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @MSufiyanAG 💥

**Comment by atarax665** [comment]
@ricardoprins This issue needs to be closed.

**Comment by HarshCasper** [comment]
@all-contributors please add @bagladivyang03 for code
