### ISSUE TITLE
Addition of Kahn's Algorithm

### ISSUE THREAD

**Issue by Jappan07** [HarshCasper/NeoAlgo#1205]
## 💥 Proposal

This is for the addition of Kahn's Algorithm to the graphs folder in c++ section.
I think it would be a good addition as it is a very important algorithm which is helpful in competitive programming.
May I make a PR for this?

**Comment by ritwikchakraborty123** [comment]
I want to do  it sir

**Comment by Jappan07** [comment]
> I want to do it sir

Sorry, but the task is completed now

**Comment by atarax665** [comment]
Add proper description of the algorithm so that contributors can have a clear idea if they wanna take up this issue or not.

**Comment by ritwikchakraborty123** [comment]
Should I do it?

**Comment by Jappan07** [comment]
> Add proper description of the algorithm so that contributors can have a clear idea if they wanna take up this issue or not.

Description:
Topological sort gives a linear ordering of vertices in a directed acyclic graph such that, for every directed edge a -> b, vertex ‘a’ comes before vertex ‘b’. Remember, a directed acyclic graph has at least one vertex with an in-degree of 0 and one vertex with an out-degree of 0.
Kahn’s Topological Sort Algorithm works by finding vertices which have no incoming edges and removing all outgoing edges from these vertices. 

So, it would be a good addition to the repo if you want.
