### ISSUE TITLE
To take input from the users in the Linear Search and Binary Search in Java

### ISSUE THREAD

**Issue by ymaheshwari1** [HarshCasper/NeoAlgo#1211]
## 🐛 Bug Report
Currently, there are hardcoded inputs in the Linear Search and Binary Search algorithms in Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES

**Comment by ymaheshwari1** [comment]
@Kajol-Kumari 
I am interested in this issue.

**Comment by 2tanayk** [comment]
can I work on this issue? @HarshCasper

**Comment by atarax665** [comment]
@ymaheshwari1 Yeah, you can do it. Also format the code according to [Java style guide](https://google.github.io/styleguide/javaguide.html)
