### ISSUE TITLE
Adding Armstrong Number code in Math section

### ISSUE THREAD

**Issue by suprithars111** [HarshCasper/NeoAlgo#1217]
## 🚀 Feature

In recreational number theory, a narcissistic number is also known as a pluperfect digital invariant (PPDI), an Armstrong number or a plus perfect number is a number that is the sum of its digits each raised to the power of the number of digits.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Assignees

- C-Plus-Plus: @suprithars111
- C-Sharp: @sharur7
- C: @imPGupta
- Go: @Soumik-Dhar
- Java: @rohangawhade
- JavaScript: @2tanayk
- Python: @sukritidawar
- Q-Sharp:

**Comment by suprithars111** [comment]
I want to work in C++ please assign me this

**Comment by sukritidawar** [comment]
I want to do this in python.

**Comment by kumaryash18** [comment]
hey I would like to do it in C please assign

**Comment by rohangawhade** [comment]
I would like to work on this on java.

**Comment by imPGupta** [comment]
I would like to contribute to this issue. Assign me in **C**.
@siddharth25pandey

**Comment by 2tanayk** [comment]
I would like to do this in Javascript @siddharth25pandey please assign this to me if possible  😊

**Comment by siddharth25pandey** [comment]
> I would like to contribute to this issue. Assign me in **C**.
> @siddharth25pandey

@imPGupta Go ahead
All the best

**Comment by siddharth25pandey** [comment]
> I would like to do this in Javascript @siddharth25pandey please assign this to me if possible 😊
@2tanayk  Go ahead
All the best

**Comment by siddharth25pandey** [comment]
> I would like to work on this on java.

@rohangawhade  Go ahead
All the best

**Comment by sharur7** [comment]
I want to work in C-Sharp. Can you please assign it to me? @siddharth25pandey

**Comment by soumik-dhar** [comment]
Can I take a stab at this using Go?

**Comment by chehak123** [comment]
I would like to work on this in c++

**Comment by iamrajiv** [comment]
@chehak123 Implementation in CPP has already been done.

**Comment by ErzaTitania-2001** [comment]
Kindly go through my PR ! @iamrajiv @atarax665 
https://github.com/TesseractCoding/NeoAlgo/commit/463677d985b0b6c19320719c8108bcdfa294b4fd
