### ISSUE TITLE
RSA Algorithm in Cryptography

### ISSUE THREAD

**Issue by rohangawhade** [HarshCasper/NeoAlgo#1222]
## 🚀 Feature

RSA algorithm is a public key encryption technique that can be considered as the most secure way of encryption. It is an asymmetric cryptographic algorithm i.e it has two keys: public key and private key

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by rohangawhade** [comment]
I would like to work on this in python

**Comment by Vishesh-Mittal** [comment]
i would like to work on this in java
