### ISSUE TITLE
Adding Catalan Number code in Math section

### ISSUE THREAD

**Issue by suprithars111** [HarshCasper/NeoAlgo#1232]
## 🚀 Feature

Catalan numbers is a number sequence, which is found useful in a number of combinatorial problems, often involving recursively-defined objects.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Assignees

- C-Plus-Plus: @suprithars111
- C-Sharp: @sharur7
- C: @salonishah01
- Go:
- Java: @rohangawhade
- JavaScript:
- Python: @iamRishabh07
- Q-Sharp:

**Comment by suprithars111** [comment]
@Kajol-Kumari @iamrajiv @plazzy99  I want to work in C++ please assign me this.

**Comment by iamRishabh07** [comment]
@iamrajiv I want to work in python can you assign me.

**Comment by rohangawhade** [comment]
I would like to work on this in java

**Comment by salonishah01** [comment]
I would like to work on this in C.

**Comment by sharur7** [comment]
@iamrajiv  I want to work on this in C-sharp
