### ISSUE TITLE
Add Post-Order Tree Traversal

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#125]
**Algorithm:** 

[Post-Order Tree Traversal](https://en.wikipedia.org/wiki/Tree_traversal)

**DS:** 

Trees

**Languages Supported:**

- C [ Assigned to @gaushikmr ]
- C++ [ Assigned to @chaitanya003 ]
- C#
- Java [ Assigned to @chaitanya003 ]
- Javascript
- Python [ Assigned to @GSNCodes ]

**Comment by chaitanya003** [comment]
Could I do this in C++ and Java ?
@HarshCasper

**Comment by HarshCasper** [comment]
I have assigned you the Issue @chaitanya003 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by GSNCodes** [comment]
Ready to implement this in Python!
@HarshCasper

**Comment by Gaushikmr** [comment]
Can u assign me to do this in C and Python.

**Comment by HarshCasper** [comment]
I have assigned you the Issue @GSNCodes and @gaushikmr in your preferred languages 🙌

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by rohitm131** [comment]
@HarshCasper 
Can i do this in Java ?

**Comment by chaitanya333** [comment]
@rohitm131 It is assigned to me and I have done it just need to push the code

**Comment by rohitm131** [comment]
ok

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C#
