### ISSUE TITLE
Add Binary Search Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#127]
**Algorithm:** 

[Binary Search Tree](https://en.wikipedia.org/wiki/Binary_search_tree)

**DS:** 

Trees

**Languages Supported:**

- C [ Assigned to @jivthesh ]
- C++ [ Assigned to @jivthesh ]
- C#
- Java [ Assigned to @sd2001 ]
- Javascript
- Python [ Assigned to @sd2001 ]

**Comment by sd2001** [comment]
Please can I start working on the binary search tree using Java and Python?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @sd2001 💥

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.

**Comment by jivthesh** [comment]
can I start working on the binary search tree using c and c++ ?

**Comment by jivthesh** [comment]
and python

**Comment by HarshCasper** [comment]
You can work on it in C and C++ @jivthesh 🙌

**Comment by Lakhan-Nad** [comment]
@HarshCasper Can I start working on BInary Search Tree in Java with all inorder preorder and post order traversals

**Comment by Lakhan-Nad** [comment]
> @HarshCasper Can I start working on BInary Search Tree in Java with all inorder preorder and post order traversals

I would like to implement both recursive and iterative methods for all the functions
