### ISSUE TITLE
Bilinear Search

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1270]
**Algorithm: [Bilinear Search](https://www.ijcsmc.com/docs/papers/December2015/V4I12201543.pdf)**
Bilinear search is a modified version of linear search where it searches from both direction. 

**Languages Supported:**
* C : [@sparkingdark ]
* CPP : @Rishabh7896
* Python : [@sparkingdark ]
* Java : @rohangawhade 
* JavaScript :
* GO :
* C# :
* Q# :

**Comment by Rishabh7896** [comment]
I can take it in c++.

**Comment by atarax665** [comment]
@Rishabh7896 Sure. You can start working on this issue in C++.
Happy Coding.

**Comment by rohangawhade** [comment]
I would like to work on this in java

**Comment by atarax665** [comment]
@rohangawhade Assigned in Java.
Make sure you go through the Contribution guidelines.
Happy coding.
