### ISSUE TITLE
Minimum Spanning Tree

### ISSUE THREAD

**Issue by Rishabh7896** [HarshCasper/NeoAlgo#1276]
## 💥 Proposal
There are n vertices and e edges and their weights, you need to construct [minimum spanning tree](https://en.wikipedia.org/wiki/Minimum_spanning_tree).

<b>Proposed Solution:</b>
Scan the array elements, and push it in a vector, sort the array with their weights which takes <b>O(e log e)</b>.
Now iterate through the vector and check whether or not this edge should be added using union - find with path compression
algorithm which takes <b>O(e alpha e)</b>.

<b>Efficiency: O(e log e + e alpha e)</b>
<b>Efficiency of Traditional approach: O(e log e + e log e)</b>

This solution has a slight edge over other algorithms.

<b> Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?</b>
Yes

**Comment by Rishabh7896** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper @iamrajiv
Please assign me this issue
I would like to implement this in C++ and please add labels.

**Comment by Bidonsaha** [comment]
Hi again  @Abhijit2505 @HarshCasper @anushkrishnav, would like to solve this issue in python. Can you assign me this?

**Comment by anushkrishnav** [comment]
Go ahead with it
