### ISSUE TITLE
Trie Data Structure

### ISSUE THREAD

**Issue by JayantGoel001** [HarshCasper/NeoAlgo#1278]
## 🚀 Proposal
[Trie Data Structure](https://en.wikipedia.org/wiki/Trie)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Google Search Engine Uses Trie Data Structure To Search our Queries)

## Pitch

(Trie Data Structure Is A speacial type of data structure which looks similar to a tree but it can variable number of branches like a roadmap.)

## Languages Supported:
- C : 
- CPP : Done
- Python : @Bidonsaha
- Java : 
- JavaScript : 
- Go : 
- C# :

**Comment by Rishabh7896** [comment]
@Kajol-Kumari @plazzy99 @siddharth25pandey @Abhijit2505 @HarshCasper @iamrajiv
Please assign me this issue
I would like to implement this in C++.

**Comment by JayantGoel001** [comment]
@Rishabh7896 I Have Taken This In CPP

**Comment by Bidonsaha** [comment]
Hey @Abhijit2505 @HarshCasper @anushkrishnav can I be assigned this issue to solve in python?

**Comment by atarax665** [comment]
> @Rishabh7896 I Have Taken This In CPP

@CormacKrum Trie data structure has already been implemented in [C++](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/ds/Trie_implementation.cpp), though you can still take this issue in any other language of your choice.

**Comment by atarax665** [comment]
> Hey @Abhijit2505 @HarshCasper @anushkrishnav can I be assigned this issue to solve in python?

@Bidonsaha Assigned in Python.

**Comment by JayantGoel001** [comment]
@atarax665 I Can Implement This is Java Please Assign.

**Comment by vatsalkesarwani12** [comment]
> @atarax665 I Can Implement This is Java Please Assign.

yes you can start working in java

Happy Learning🥳

**Comment by JayantGoel001** [comment]
@atarax665  @plazzy99 Please Accept My PR

**Comment by arnab031** [comment]
Would you assign me this problem in python?
