### ISSUE TITLE
Add a Code to calculate height of a given Binary Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#128]
**Algorithm:** 

Add a Code to calculate the height of a given Binary Tree

**DS:** 

Trees

**Languages Supported:**

- C
- C++ [ Assigned to @asaxena012 ]
- C#
- Java
- Javascript
- Python [ Assigned to @srinivasdasu24 ]

**Comment by asaxena012** [comment]
@HarshCasper Could you assign me this issue? I'll code in C++.

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @asaxena012 💥

**Comment by asaxena012** [comment]
@HarshCasper  I have created a PR for this issue. There is some conflict in the update that I made in README.md.
Please have a look.

**Comment by srinivasdasu24** [comment]
@HarshCasper could you assign this issue I will code in python

**Comment by HarshCasper** [comment]
I have assigned you the Issue @srinivasdasu24 

You can start working on it.

**Comment by srinivasdasu24** [comment]
@HarshCasper  Created pull reuqest https://github.com/TesseractCoding/NeoAlgo/pull/236 for Height of a given binary tree in python

**Comment by rohitkumar-rk** [comment]
I can contribute for Java.

**Comment by Kathan-Vakharia** [comment]
Can you assign me this issue for C language ?

**Comment by sonukushwaha403** [comment]
I would like to work on this problem with JAVA

**Comment by muddhit** [comment]
I want to contribute for Java

**Comment by lipsamishra1609** [comment]
@HarshCasper i would like to contribute in c

**Comment by obli99** [comment]
@HarshCasper i would like to contribute in javascript
