### ISSUE TITLE
wanted to contribute Java implementation for N-Queen and level order traversal of tree 

### ISSUE THREAD

**Issue by NirmalSilwal** [HarshCasper/NeoAlgo#1285]
Hi contributor there, in the [existing repo for Java](https://github.com/TesseractCoding/NeoAlgo/tree/master/Java) there is **no any implementation for N-Queen problem and level order traversal of tree**, which are in general important from interview perspective also.

So I would like to add the code for them. What are your suggestions?

Thanks

**Comment by ArchanaDhaker** [comment]
I would like to add N-Queen problem. kindly assign to me.

**Comment by atarax665** [comment]
@NirmalSilwal You can comment on #401 to contribute level order traversal of tree.
@ArchanaDhaker Comment on #424 to get the N-Queen issue assigned to you.

**Comment by NirmalSilwal** [comment]
Thanks, will comment there.
