### ISSUE TITLE
Addition of Ugly Number Problem

### ISSUE THREAD

**Issue by 13muskanp** [HarshCasper/NeoAlgo#1286]
## 🚀 Feature
**Ugly Number Problem**
Ugly numbers are numbers whose only prime factors are 2, 3 or 5. The sequence 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, … shows the first 11 ugly numbers. By convention, 1 is included.
Given a number n, the task is to find n’th Ugly number.

Example :
Input:
N = 10
Output: 12
Explanation: 10th ugly number is 12.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have.

## Motivation

This problem is considered a hard problem and is frequently asked in placement coding rounds.

## Pitch

This repository has a huge collection of various domains of problems for many languages. Students preparing for placement might especially take advantage. This problem is frequently asked in coding rounds of many MNCs.

## Languages Supported:
- C : @Rishabh7896 
- CPP : @13muskanp
- Python : @salonishah01 
- Java : @CormacKrum
- JavaScript : 
- GO : 
- C# :

**Comment by JayantGoel001** [comment]
Please assign me for  this task in java

**Comment by salonishah01** [comment]
Assign me to work in python

**Comment by Rishabh7896** [comment]
I can take it in C.

**Comment by atarax665** [comment]
@CormacKrum Assigned in Java
@salonishah01 Assigned in Python
@Rishabh7896 Assigned in C

**Comment by heyanurag** [comment]
@atarax665 Please assign me this for Javascript

**Comment by JayantGoel001** [comment]
@atarax665 Please Accept My PR

**Comment by ErzaTitania-2001** [comment]
Ugly Number With Recursion (Addition of Ugly Number Problem #1286) #1424
Kindly go through my PR @atarax665  @iamrajiv

**Comment by Sidhant-Gupta** [comment]
I'll like to take this issue. Please assign me this for cpp.
