### ISSUE TITLE
Add a Code to Calculate the Depth of the Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#129]
**Algorithm:** 

Calculate the Depth of the Tree

**DS:** 

Trees

**Languages Supported:**

- C
- C++
- C#
- Java
- Javascript
- Python [ Assigned to @GSNCodes ]

**Comment by GSNCodes** [comment]
Hi @HarshCasper I can work on this in Python

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can work on it @GSNCodes

**Comment by srinivasdasu24** [comment]
Hi @HarshCasper, I can work on this problem in CPP language

**Comment by bagladivyang03** [comment]
Hi @HarshCasper can  i do this in C++ ?

**Comment by anshul7sh** [comment]
@HarshCasper I want to work on this issue using **_C_** and **_Java_**.

**Comment by muddhit** [comment]
I want to work with java

**Comment by GrayFlash** [comment]
Hi @HarshCasper can I work on Java
