### ISSUE TITLE
Adding 2 numbers with Linked Lists

### ISSUE THREAD

**Issue by csendranshi** [HarshCasper/NeoAlgo#1296]
## 🚀 Feature
Python implementation of Addition of 2 numbers using Linked Lists with carry handling.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

GeeksForGeeks interview guide Problem Statement useful for current placement season

## Pitch

Useful for current placement season. Coding tests for many companies like amazon, microsoft, google had this problem statement

**Comment by csendranshi** [comment]
Please assign me this issue

**Comment by Abhi1398** [comment]
I would love to work on this using python

**Comment by Abhi1398** [comment]
Please assign this to me

**Comment by csendranshi** [comment]
I have solved this issue and snet a pull request

**Comment by chehak123** [comment]
I would like to work on this in c++
