### ISSUE TITLE
Last Digit of a Large Fibonacci Number

### ISSUE THREAD

**Issue by narayan2111** [HarshCasper/NeoAlgo#1298]
## 🚀 Feature

The problem is to find the last digit of 𝑛-th Fibonacci number. Recall that Fibonacci numbers grow exponentially fast. 
For example,
            𝐹200= 280 571 172 992 510 140 037 611 932 413 038 677 189 525
output: 5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Most programs are so slow in finding the last digit of fibonacci number because as 𝑖grows the 𝑖th iteration of the loop computes the sum of longer and longer numbers.  Also, for example,𝐹1000 does not fit into the standard C++int type. To overcome this difficulty, we need to create a program which can works on large digits very fast.

## Pitch

Computing the last digit of 𝐹𝑖 is easy: 
it is just the last digit of the sum of the last digits of 𝐹𝑖−1and 𝐹𝑖−2:
𝐹[𝑖]←(𝐹[𝑖−1] +𝐹[𝑖−2])mod 10
This way, all 𝐹[𝑖]’s are just digits, so they fit perfectly into any standard integer type, and computing a sum of 𝐹[𝑖−1]and𝐹[𝑖−2] is performed very quickly.

**Comment by narayan2111** [comment]
i would like to work on this issue in c++ ,kindly assign this issue to me @iamrajiv @plazzy99

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in Java.

**Comment by vatsalkesarwani12** [comment]
@nutanaarohi123 - Java
@narayan2111 - C++
**Assigned** 
You can start working on the issue.

**Comment by rishigarg94** [comment]
@iamrajiv  i will like to work on this in pyhton

**Comment by anilkumarbasnet** [comment]
@iamrajiv I will like to work this in C.

**Comment by anilkumarbasnet** [comment]
@iamrajiv I will like to work this in C.

**Comment by rishigarg94** [comment]
> 
> 
> @iamrajiv i will like to work on this in pyhton

@plazzy99  pls assign this issue to me in python

**Comment by spandey1296** [comment]
@nutanaarohi123 @plazzy99  @rishigarg94  @narayan2111  I would like to work on java and please assign the issues to me. Thanks

**Comment by spandey1296** [comment]
> The problem is to find the last digit of 𝑛-th Fibonacci number. Recall that Fibonacci numbers grow exponentially fast.
> For example,
> 𝐹200= 280 571 172 992 510 140 037 611 932 413 038 677 189 525
> output: 5

package com.company;

import java.util.Scanner;

public class FibonacciNumber {
    public static void main(String[] args) {
  Scanner sc= new Scanner(System.in);
  

        int n;
        n=sc.nextInt();
        
        int c = get_fibonacci_last_digit(n);
        System.out.println("last nth fibonacci digit is: " + c);
            }

    private static int get_fibonacci_last_digit(int n) {

        int first = 0;
        int second = 1;
        int res = 0;
        for (int i = 2; i <= n; i++) {
            res = (first + second) % 10;
            first = second;
            second = res;
        }

        return res;
    }

}

**Comment by nutanaarohi123** [comment]
> > The problem is to find the last digit of 𝑛-th Fibonacci number. Recall that Fibonacci numbers grow exponentially fast.
> > For example,
> > 𝐹200= 280 571 172 992 510 140 037 611 932 413 038 677 189 525
> > output: 5
> 
> package com.company;
> 
> import java.util.Scanner;
> 
> public class FibonacciNumber {
> public static void main(String[] args) {
> Scanner sc= new Scanner(System.in);
> 
> ```
>     int n;
>     n=sc.nextInt();
>     
>     int c = get_fibonacci_last_digit(n);
>     System.out.println("last nth fibonacci digit is: " + c);
>         }
> 
> private static int get_fibonacci_last_digit(int n) {
> 
>     int first = 0;
>     int second = 1;
>     int res = 0;
>     for (int i = 2; i <= n; i++) {
>         res = (first + second) % 10;
>         first = second;
>         second = res;
>     }
> 
>     return res;
> }
> ```
> 
> }

hey @spandey1296 . this problem is already solved in java. the code you have mention will take more time i.e time complexity is high.

**Comment by chehak123** [comment]
I would like to work on this in c++

**Comment by iamrajiv** [comment]
@chehak123 Implementation in CPP has already been done.

**Comment by abhay313** [comment]
Please assign me I would like to implement it in C++
