### ISSUE TITLE
Fast Program to find Greatest Common Divisor 

### ISSUE THREAD

**Issue by narayan2111** [HarshCasper/NeoAlgo#1299]
## 🚀 Feature

The greatest common divisor GCD(𝑎, 𝑏)of two non-negative integers𝑎and𝑏(which are not both equal to0) is the greatest integer𝑑that divides both𝑎and𝑏.Your goal in this problem is to implement the Euclidean algorithm for computing the greatest common divisor. Efficient algorithm for computing the greatest common divisor is an important basic primitive of commonly used cryptographic algorithms like RSA. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Greatest common divisor is most asked questions in interview.
Efficient algorithm for computing the greatest common divisor is an important 
basic primitive of commonly used cryptographic algorithms like RSA.

## Pitch

**Task** Given two integers 𝑎 and𝑏, find their greatest common divisor.
**Input Format.**The two integers 𝑎, 𝑏 are given in the same line separated by space.
**Constraints.** 1≤𝑎, 𝑏≤2·109.
**Output Format.** OutputGCD(𝑎, 𝑏).

**Comment by narayan2111** [comment]
i would like to work on this issue in C++ ,kindly assign this issue to me @iamrajiv @plazzy99

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in Java.

**Comment by narayan2111** [comment]
Kindly assign this issue @SKAUL05

**Comment by narayan2111** [comment]
Kindly assign this issue to me @iamrajiv @SKAUL05 @plazzy99

**Comment by sumitaccess007** [comment]
Hi @TesseractCoding
I would like to contribute for this problem in Java Programming language, Also I will be making the code more and more dynamic ans with proper documentation.

**Comment by pra17dod** [comment]
I would like to contribute to this issue in cpp, I have solved this problem already. Could you please assign it to me?

**Comment by chehak123** [comment]
I would like to work on this in c++
