### ISSUE TITLE
Add Binary Search Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#13]
**Algorithm:** 

[Binary Search](https://en.wikipedia.org/wiki/Binary_search_algorithm#:~:text=In%20computer%20science%2C%20binary%20search,middle%20element%20of%20the%20array.)

**DS:** 

- Searching

**Languages Missing:**

- C [ Assigned to @kulsoomzahra ]
- C++ [ Assigned to @VaibhaveS ]
- C#
- Python [ Assigned to @kulsoomzahra ]

**Comment by kulsoomzahra** [comment]
Can you assign me this issue? @HarshCasper

**Comment by HarshCasper** [comment]
Thanks for taking this up @kulsoomzahra 

Can you please mention which language would you like to take up for this Issue?

**Comment by VaibhaveS** [comment]
I can work on this too, I can work in c++ as well as python ....

**Comment by kulsoomzahra** [comment]
> Thanks for taking this up @kulsoomzahra
> 
> Can you please mention which language would you like to take up for this Issue?
Python and C also

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @VaibhaveS and @kulsoomzahra

@kulsoomzahra you can take up Python and C. @VaibhaveS I have assigned you C++. If you want to work in the rest of the languages, do let me know here.

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by VaibhaveS** [comment]
Great. I shall start working on it from tommorow onwards...

**Comment by MSufiyanAG** [comment]
Can you assign me this issue? @HarshCasper 
I want to work in java.

**Comment by HarshCasper** [comment]
You can work on this issue @MSufiyanAG

**Comment by Kathan-Vakharia** [comment]
I would like to work on c# version .

**Comment by Sohailsaifi** [comment]
can you assign this issue to me I can work on this for java language?

**Comment by Huzaib** [comment]
Can I take it up in Java?

**Comment by anshita22** [comment]
I want to work on this issue in C++ and python. kindly assign me this issue.
