### ISSUE TITLE
Add AVL Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#130]
**Algorithm:** 

[AVL Tree](https://en.wikipedia.org/wiki/AVL_tree)

**DS:** 

Trees

**Languages Supported:**

- C
- C++
- C#
- Java
- Javascript
- Python

**Comment by vgb-codes** [comment]
I can do this in Python.

**Comment by yashsahay25** [comment]
Kindly assign me this task. I will do this in C.

**Comment by obli99** [comment]
@HarshCasper i want to contribute in java

**Comment by lipsamishra1609** [comment]
can i contribute in javascript?

**Comment by vgb-codes** [comment]
@yashsahay2014 Go ahead with C.
@obli99 Go ahead with Java.
@lipsamishra1609 Go ahead with Javascript.
Please follow the contribution guidelines when submitting your contribution.
