### ISSUE TITLE
Least Common Multiple for large numbers

### ISSUE THREAD

**Issue by narayan2111** [HarshCasper/NeoAlgo#1300]
## 🚀 Feature

The least common multiple of two positive integers 𝑎 and 𝑏 is the least positive integer 𝑚 that is divisible by both 𝑎 and 𝑏.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

**Task.** Given two integers 𝑎 and 𝑏, find their least common multiple.
**Input Format.** The two integers 𝑎 and 𝑏 are given in the same line separated by space.
**Constraints.** 1≤𝑎, 𝑏≤107.
**Output Format.** Output the least common multiple of 𝑎 and 𝑏

## Pitch

This program will calculate the LCM in a very fast way.

**Comment by narayan2111** [comment]
i would like to work on this issue in python. kindly assign this issue to me @iamrajiv @plazzy99

**Comment by yashaswibiyahut** [comment]
I would like to do this in Cpp kindly assign me @iamrajiv @siddharth25pandey @SKAUL05 @Kajol-Kumari

**Comment by AakritiKinra** [comment]
I would like to work on this in C language. Kindly assign me @iamrajiv @SKAUL05 @siddharth25pandey @Kajol-Kumari

**Comment by rishigarg94** [comment]
i would like to work on this issue in java @iamrajiv @plazzy99  pls assign me this issue in java

**Comment by rishigarg94** [comment]
> 
> 
> i would like to work on this issue in java @iamrajiv @plazzy99 pls assign me this issue in java

@yashaswibiyahut  pls assign me this issue

**Comment by chehak123** [comment]
I would like to work on this in c++

**Comment by iamrajiv** [comment]
@chehak123 Implementation in CPP has already been done.

**Comment by rutujak24** [comment]
Please assign this issue to me, would like to work with it for WOC in python.
