### ISSUE TITLE
Happy Number

### ISSUE THREAD

**Issue by xma8lu** [HarshCasper/NeoAlgo#1308]
### Happy Number

A number is called happy if it leads to 1 after a sequence of steps wherein each step number is replaced by the sum of squares of its digit that is if we start with Happy Number and keep replacing it with digits square sum, we reach 1.

For example, 32 is a happy number as the process yields 1 as follows

3^2 + 2^2 = 13
1^2 + 3^2 = 10
1^2 + 0^2 = 1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Languages Supported :**
- C : 
- CPP : 
- Python : @salonishah01 
- Java : @rishigarg94
- JavaScript : 
- C# : 
- GO :

**Comment by salonishah01** [comment]
I would like to work on this in python

**Comment by rishigarg94** [comment]
i would like to work on it in java or pyhton

**Comment by rishigarg94** [comment]
i have done submitting a pr on this issue for java code , please review it

**Comment by rishigarg94** [comment]
@iamrajiv  sir please review my PR

**Comment by atarax665** [comment]
@rishigarg94 Assigned in Java.
@salonishah01 Assigned in Python.

**Comment by xma8lu** [comment]
@atarax665 can you please assign this to me in cpp

**Comment by rishigarg94** [comment]
@atarax665  i have submitted happy number code PR in java, can you please review it.thanks

**Comment by arnab031** [comment]
I would like to work on this in C. Would you please assign it to me?

**Comment by atarax665** [comment]
Assigned in CPP : @aditya-gite-04 
Assigned in C : @arnab031 
Happy Coding.

**Comment by chehak123** [comment]
I would like to work on this in c++
