### ISSUE TITLE
Add Spanning Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#131]
**Algorithm:** 

[Spanning Tree](https://en.wikipedia.org/wiki/Spanning_tree)

**DS:** 

Trees

**Languages Supported:**

- C
- C++
- C#
- Java
- Javascript
- Python

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++.

**Comment by sonukushwaha403** [comment]
I would like to work on this problem with JAVA

**Comment by Ajay0511** [comment]
I would like to work in Python.
