### ISSUE TITLE
Majority Element in array using Moore's Voting Algorithm

### ISSUE THREAD

**Issue by ShrutiRawal** [HarshCasper/NeoAlgo#1311]
Problem - Given an array of n elements, find an element that occurs more than [n/2] times in the array.
I'll implement this using **Java**, kindly assign this to me.

**Comment by rcoder23** [comment]
@ShrutiRawal  I added the solution of the problem .Please merged it

**Comment by ShrutiRawal** [comment]
@rcoder23 I'm just a contributor, you should mention any of the maintainers.

**Comment by rcoder23** [comment]
Hello @plazzy99 @iamrajiv   ,Please review my pull request and merged it .

Thank you
