### ISSUE TITLE
House Robber problem

### ISSUE THREAD

**Issue by ShahriarCodes** [HarshCasper/NeoAlgo#1312]
## 🚀 Feature

LeetCode problem 198.

You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security system connected and it will automatically contact the police if two adjacent houses were broken into on the same night.

Given a list of non-negative integers representing the amount of money of each house, determine the maximum amount of money you can rob tonight without alerting the police.

 Example 1:

Input: nums = [1,2,3,1]
Output: 4
Explanation: Rob house 1 (money = 1) and then rob house 3 (money = 3).
             Total amount you can rob = 1 + 3 = 4.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This problem has not been yet solved in NeoAlgo repository

## Pitch
The problem statement is available [here](https://leetcode.com/problems/house-robber/)
This problem can be solved using Dynamic Programming.

## Language Supported : 
- Python : @shahriar100
- Java
- JavaScript
- C-Plus-Plus
- C#
- GO
- C : @salonishah01

**Comment by ShahriarCodes** [comment]
Please assign this task to me @SKAUL05 @HarshCasper @atarax665 @plazzy99 @iamrajiv

**Comment by AdityaJ7** [comment]
> Please assign this task to me @SKAUL05 @HarshCasper @atarax665 @plazzy99 @iamrajiv

mention the language you want to work in as well

**Comment by ShahriarCodes** [comment]
I can solve the **house robber** problem in these languages 
   - Python
   - Java
   - JavaScript
   - C-Plus-Plus

**Comment by AdityaJ7** [comment]
> I can solve the **house robber** problem in these languages
> 
> * Python
> * Java
> * JavaScript
> * C-Plus-Plus

they assign one language at a time

**Comment by ShahriarCodes** [comment]
I can solve the house robber problem in **Python**.

**Comment by atarax665** [comment]
> I can solve the house robber problem in **Python**.

@shahriar100 Assigned in Python.

**Comment by salonishah01** [comment]
Assign me the issue in C

**Comment by atarax665** [comment]
> Assign me the issue in C

Assigned in C.
Happy Coding!

**Comment by AdityaJ7** [comment]
@atarax665 I'll take this in C++

**Comment by Amanj2000** [comment]
I want to solve the issue in Java.

**Comment by limitless-Sky** [comment]
@shahriar100 Can I work on this in Java?

**Comment by ShahriarCodes** [comment]
> @shahriar100 Can I work on this in Java?

You may ask the repository maintainers to assign you.

**Comment by limitless-Sky** [comment]
@atarax665 Can I work on this problem in java

**Comment by limitless-Sky** [comment]
@iamrajiv I had completed Java Code for this problem. kindly merge it.

**Comment by abhay313** [comment]
Please assign me I would like to implement it in C++
