### ISSUE TITLE
Add Segment Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#132]
**Algorithm:** 

[Segment Tree](https://en.wikipedia.org/wiki/Segment_tree)

**DS:** 

Trees

**Languages Supported:**

- C
- C++
- C#
- Java
- Javascript
- Python

**Comment by Himanshu70565** [comment]
Can I work for implementing segment tree in java?

**Comment by HarshCasper** [comment]
I have assigned you the Issue @Himanshu70565 

You can start working on it.

**Comment by mohithotwani01** [comment]
@HarshCasper Can I work for implementing segment tree in C++?

**Comment by mohithotwani01** [comment]
@plazzy99 can I work on implementing segment tree in c++ for sum of given range and minimum query.
