### ISSUE TITLE
Extended Euclidean Algorithm

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1321]
## 🚀 Algorithm

[Extended Euclidean Algorithm](https://en.wikipedia.org/wiki/Extended_Euclidean_algorithm)

## Languages Available:
* C : @Aanchi-glitch2744 
* C# : 
* JavaScript : 
* Go :

**Comment by rcoder23** [comment]
I want to wok on this issue please assigned to me .

**Comment by atarax665** [comment]
> I want to wok on this issue please assigned to me .

@rcoder23 Do mention the language you want to work in.

**Comment by Aanchi-glitch2744** [comment]
I would like to work on this issue in C

**Comment by atarax665** [comment]
> I would like to work on this issue in C

@Aanchi-glitch2744  You can start working on this issue in C.
Happy Coding!!

**Comment by pra17dod** [comment]
I would like to work on this using CPP. Can you please assign it to me?

**Comment by atarax665** [comment]
> I would like to work on this using CPP. Can you please assign it to me?

This has already been implemented in CPP. You can still take this issue in one of the remaining languages according to your convenience.
