### ISSUE TITLE
Tim Sort

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1322]
**Algorithm: 
[Tim sort](https://en.wikipedia.org/wiki/Timsort)** 

Tim sort is a hybrid stable sorting algorithm, derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data. It was implemented by Tim Peters in 2002 for use in the Python programming language. The algorithm finds sub-sequences of the data that are already ordered (runs) and uses them to sort the remainder more efficiently. This is done by merging runs until certain criteria are fulfilled.

**Languages Supported:**

* C : @salonishah01 
* CPP : Done
* C# :
* Python : @SANKET7738
* Java : @aditya-gite-04
* Go :
* JavaScript :

**Comment by SANKET7738** [comment]
I would like to take this issue in python.

**Comment by salonishah01** [comment]
I can work on this in C.

**Comment by atarax665** [comment]
> I would like to take this issue in python.

@SANKET7738 Assigned in Python.

**Comment by atarax665** [comment]
> I can work on this in C.

@salonishah01 Assigned in C.

**Comment by xma8lu** [comment]
Hey @atarax665  can i work on this in JAVA

**Comment by atarax665** [comment]
@aditya-gite-04 Assigned in Java.

**Comment by chehak123** [comment]
I would like to work on this in c++
