### ISSUE TITLE
Knuth Morris Pratt algorithm

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1323]
## Algorithm :
[Knuth–Morris–Pratt algorithm](https://en.wikipedia.org/wiki/Knuth–Morris–Pratt_algorithm)

## Languages Supported:

- CPP: Done
- C: @salonishah01 
- Python: Done
- Java: @Amanj2000 
- JavaScript: Done
- C# : 
- Go :

**Comment by salonishah01** [comment]
I can take up the issue in C.

**Comment by Amanj2000** [comment]
I would like to work on this in java.
