### ISSUE TITLE
Ternary Search

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1326]
## 🚀 Algorithm

[Ternary Search](https://en.wikipedia.org/wiki/Ternary_search)
(Add both recursive and iterative approach)

## Languages Supported :
- C : @salonishah01 
- CPP : @CormacKrum
- Python : @basharfarid77
- Java : @parjanyaacoder 
- JavaScript : 
- GO : 
- C# :

**Comment by basharfarid77** [comment]
Will be happy to contribute if assigned in python language :)

**Comment by JayantGoel001** [comment]
Please Assign Me This. I Can Do It in CPP

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java.

**Comment by salonishah01** [comment]
I would work on this issue in C

**Comment by atarax665** [comment]
@basharfarid77 Assigned in Python.
@CormacKrum Assigned in C++.
@parjanyaacoder Assigned in Java.
@salonishah01 Assigned in C.

**Comment by ShishirBhandari** [comment]
@atarax665, I will implement it in Javascript.

**Comment by sayantan1413** [comment]
@atarax665 @iamrajiv @plazzy99 Can you assign me the solution of the problem in C-sharp
