### ISSUE TITLE
Add Fenwick Tree

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#133]
**Algorithm:** 

[Fenwick Tree](https://en.wikipedia.org/wiki/Fenwick_tree)

**DS:** 

Trees

**Languages Supported:**

- C [ Assigned to @gaushikmr ]
- C++
- C#
- Java
- Javascript
- Python

**Comment by Gaushikmr** [comment]
Can I do this in C

**Comment by HarshCasper** [comment]
I have assigned you the Issue @gaushikmr 🙌

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by Gaushikmr** [comment]
#133 done in c.

**Comment by GrayFlash** [comment]
Can I work on JAVA
