### ISSUE TITLE
snake and ladder 

### ISSUE THREAD

**Issue by Preetesh21** [HarshCasper/NeoAlgo#1346]
## 🚀 Problem

Add code for snake and ladder problem

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes.

## Motivation

Asked in interviews.

## Pitch
Given a snake and ladder board of order 5x6, find the minimum number of dice throws required to reach the destination or last cell (30th cell) from source (1st cell).

**Comment by pra17dod** [comment]
I would like to work on this problem in CPP language. Could you please assign me?

**Comment by ghost** [comment]
can you assign me this

**Comment by ashu-cybertron** [comment]
i would like to work on this with python please assign this to me

**Comment by ashu-cybertron** [comment]
i would like to work on this with python please assign this to me
