### ISSUE TITLE
Knapsack problem

### ISSUE THREAD

**Issue by pra17dod** [HarshCasper/NeoAlgo#1355]
## 🚀 Feature

[Knapsack problem](https://en.wikipedia.org/wiki/Knapsack_problem)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes, I have read it.

## Motivation
It is a basic and important problem to understand the greedy algorithm.

## Pitch
The knapsack problem is a problem in combinatorial optimization: Given a set of items, each with a weight and a value, determine the number of each item to include in a collection so that the total weight is less than or equal to a given limit and the total value is as large as possible.

**Comment by pra17dod** [comment]
I would like to contribute on this issue in cpp. I have already solved the problem, so please assign me.

**Comment by Amanj2000** [comment]
I want to work on this in c.

**Comment by atarax665** [comment]
#423

**Comment by atarax665** [comment]
Duplicate issue.
