### ISSUE TITLE
Ackerman Function

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1361]
### [Ackerman Function](https://en.wikipedia.org/wiki/Ackermann_function)
![image](https://wikimedia.org/api/rest_v1/media/math/render/svg/b72351763c6665ed2049aec7b29edd24bed292eb)

### Languages Supported :
- C : 
- CPP : DONE
- Java : 
- Python : @pra17dod
- JavaScript : 
- GO : 
- C# :

**Comment by ghost** [comment]
I want to work on this issue

**Comment by pra17dod** [comment]
I would like to work on in python, can you please assign me?

**Comment by atarax665** [comment]
> I want to work on this issue

@shahbazalam07 You also need to mention the language you want to take this issue in.

**Comment by atarax665** [comment]
> I would like to work on in python, can you please assign me?

@pra17dod Assigned in Python. Happy Coding.

**Comment by barnamensch056** [comment]
Assign me, I'll do it in C
