### ISSUE TITLE
Prime Checker Program 

### ISSUE THREAD

**Issue by amit14mitra** [HarshCasper/NeoAlgo#1369]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by snehaa1989** [comment]
Proposal:
I will code this program in C++
I have read the guidelines well and will follow them.

**Comment by amit14mitra** [comment]
> ## 💥 Proposal
> (A clear and concise description of what the proposal is.)
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> (Write your answer here.)

Yes. I have followed them

**Comment by amit14mitra** [comment]
@snehaa1989 assigned to do prime checker program in c++

**Comment by atarax665** [comment]
@amit14mitra @snehaa1989 Comment on #1372 to get this issue assigned to you.
