### ISSUE TITLE
Sieve of Eratosthenes method, for computing prime number

### ISSUE THREAD

**Issue by keshav304** [HarshCasper/NeoAlgo#137]
**Algorithm:** 
In mathematics, the sieve of Eratosthenes is an ancient algorithm for finding all prime numbers up to any given limit.

It does so by iteratively marking as composite (i.e., not prime) the multiples of each prime, starting with the first prime number, 

The multiples of a given prime are generated as a sequence of numbers starting from that prime, with a constant difference between them that is equal to that prime. 

This is the sieve's key distinction from using trial division to sequentially test each candidate number for divisibility by each prime.

**Languages Supported:**
Python.
- C [@atarax665 ]
- C++ [ Assigned to @asaxena012 ]
- Java [@Himanshu70565 ]
- Javascript
- Python [ Assigned to @keshav304 ]

I would like to work on this issue using Python.

**Comment by asaxena012** [comment]
@HarshCasper @ricardoprins Please assign this issue to me in C++. Thanks.

**Comment by HarshCasper** [comment]
Thanks for making this Issue @keshav304 and carrying the true spirit of Open-Source 👀

I have assigned the Issue in C++ to @asaxena012 and in Python to @keshav304. You can start working on it now.

**Comment by Himanshu70565** [comment]
@HarshCasper I would like to work in java.

**Comment by atarax665** [comment]
I would like to take this issue in C.

**Comment by mar-galho** [comment]
Whoever is working on this, you'll get a special mention if you implement not only the original sieve, but also some of its variations :D

**Comment by mar-galho** [comment]
@Himanshu70565 and @atarax665 , game on!
