### ISSUE TITLE
Prime Number

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1372]
## 💥 Proposal

Check if a given number is a Prime Number or not.
e.g : 
```
Input : 
Enter a number : 13
Output : 
13 is a Prime Number.
```
**Note** - Add both iterative and recursive approach.
### Languages Supported : 
- C : 
- CPP : 
- Python : 
- Java : 
- JavaScript : 
- GO : 
- C# :

**Comment by salonishah01** [comment]
I would like to contribute in C and python.

**Comment by manavbhikadiya** [comment]
i would love to this task. please assign this to me. also i have very good knowledge of ds and algo!

**Comment by rishigarg94** [comment]
i would like to contribute in java @atarax665  @plazzy99 @iamrajiv  pls assign this to me

**Comment by elizabethqiu** [comment]
Can I help in Java? Thank you!

**Comment by ashu-cybertron** [comment]
i would like to work on python on this assign me

**Comment by chehak123** [comment]
I would like to work on this in c++

**Comment by limitless-Sky** [comment]
@atarax665 Can I work on this in Java?

**Comment by sayantan1413** [comment]
@atarax665 @plazzy99 @iamrajiv Can you assign the solution of this problem in C-sharp.

**Comment by charlie219** [comment]
@atarax665 @iamrajiv  can I take this issue in Python, if yes then kindly assign me the issue

**Comment by aeyshubh** [comment]
Hello , i would like to do this program in Java @iamrajiv

**Comment by ErzaTitania-2001** [comment]
Can solve this in Kotlin if required!

**Comment by ErzaTitania-2001** [comment]
https://github.com/ErzaTitania-2001/NeoAlgo/commit/ce11e4200d5ca4be394740904d54f58ff5086d0d
Iteratively as well as recursively done in Java.  Please review it.  @atarax665  @iamrajiv

**Comment by ErzaTitania-2001** [comment]
@atarax665 @iamrajiv please review my PR!
