### ISSUE TITLE
Python Style Guide Documentation

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1387]
## 📚 Documentation

Create a Python Style Guide Documentation in the specific `Python` Directory which serves the following purpose: 

- Acquaint the User about the Python Styles Guide and what are the best practices to follow (PEP-8).
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in Python Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by deagleSC** [comment]
Hi. Can you assign me this issue? @atarax665

**Comment by atarax665** [comment]
> Hi. Can you assign me this issue? @atarax665

@DeagleOfficial Assigned to you.
