### ISSUE TITLE
Add No Plagiarism to Contribution Guidelines 

### ISSUE THREAD

**Issue by hemanth-kotagiri** [HarshCasper/NeoAlgo#1388]
## 📚 Documentation

My only request is to add No Plagiarism to the contribution guidelines. So far, I have reviewed two PRs that are directly copied from another website which were authored by someone else. Here they are: #1338 and #1327 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes. In fact, my issue is related to its improvement.

**Comment by dgabriel123** [comment]
Hello @hemanth-kotagiri , may I work on this?

**Comment by hemanth-kotagiri** [comment]
Sorry @dgabriel123. I am working on that. Thanks!

**Comment by hemanth-kotagiri** [comment]
@atarax665 if you are open for collaboration, I am more than happy to join and help this repository and engage in reviewing PRs and issues.
Thanks!

**Comment by HarshCasper** [comment]
Thanks for the contribution @hemanth-kotagiri 

I'm the Project Admin of NeoAlgo and I would like you to join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

**Comment by hemanth-kotagiri** [comment]
@HarshCasper, Awesome! Thanks!
