### ISSUE TITLE
Rectangle Cutting Using DP

### ISSUE THREAD

**Issue by Gaurav6982** [HarshCasper/NeoAlgo#1395]
## 🚀 Feature

Given an a×b rectangle, your task is to cut it into squares. On each move you can select a rectangle and cut it into two rectangles in such a way that all side lengths remain integers. What is the minimum possible number of moves?
## Input
The only input line has two integers a and b.

## Output
Print one integer: the minimum number of moves.

## Example

Input:
3 5

Output:
3
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Write Both Memorization and Tabulation Approach.

## Pitch

Helps One to Understand how Dynamic Programming Works and simply improves the thinking in it.

**Comment by Gaurav6982** [comment]
Please Assign me this for c++ and java. @plazzy99

**Comment by vatsalkesarwani12** [comment]
> Please Assign me this for c++ and java. @plazzy99

assigned java and cpp

**Comment by ashu-cybertron** [comment]
assign me for java

**Comment by vatsalkesarwani12** [comment]
> assign me for java
java is already assigned

**Comment by ashu-cybertron** [comment]
i would like to work on python on this assign me

**Comment by ashu-cybertron** [comment]
i would like work in cpp also please assign to me in C++

**Comment by vatsalkesarwani12** [comment]
> i would like to work on python on this assign me

python assigned
