### ISSUE TITLE
Add Fibonacci Search Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#14]
**Algorithm:** 

[Fibonacci Search](https://en.wikipedia.org/wiki/Fibonacci_search_technique)

**DS:** 

Searching

**Languages Supported:**

- C [@Kathan-Vakharia]
- CPP
- Java [@Kathan-Vakharia]
- Javascript
- Python 
- C#
- Golang

**Comment by Adityanagraj** [comment]
Can i work on this issue in python

**Comment by HarshCasper** [comment]
I have assigned the Issue for Java and Python to @Adityanagraj 

You can start working on it. Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by atarax665** [comment]
@Adityanagraj Are you working on this issue?

**Comment by Adityanagraj** [comment]
no i am working on other issue

**Comment by Kathan-Vakharia** [comment]
I would like to work on C and Java version.

**Comment by atarax665** [comment]
@Kathan-Vakharia Assigned, you can start working on it.

**Comment by Nistha-tech** [comment]
Can I work on this issue in C++ ?

**Comment by HarshCasper** [comment]
@Nistha-tech Contributions for HakinCodes would officially start from 16th August and you can work only on those Issue-specific for `HakinCodes`

**Comment by Kathan-Vakharia** [comment]
I had a misunderstanding. I thought these issues are for `HakinCodes`. I would like to unassign myself on this issue!

**Comment by Anjali2001saxena** [comment]
I would like to work on this in Java

**Comment by kashika3101** [comment]
I would like to work on this issue in cpp.
Please assign it to me

**Comment by ShreyasKadiri** [comment]
I want to work on Java. Please assign me

**Comment by malet-ds** [comment]
I can work this in Java or Python. I am in CH20
