### ISSUE TITLE
Chinese Remainder Theorem

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#1403]
## [Chinese Remainder Theorem](https://en.wikipedia.org/wiki/Chinese_remainder_theorem)

You are given k numbers which are pairwise coprime, and given remainders of these numbers when an unknown number x is divided by them. We need to find the minimum possible value of x that produces given remainders.

Example: 
Input : 
Enter the size of the array : 3
Enter value of coprime divisors : 2 3 5
Enter the value of remainders: 1 2 4

Output : 
x = 29

## Assignees

- C-Plus-Plus: @the-agarwal01
- C-Sharp:
- C: @salonishah01
- Go:
- Java:
- JavaScript:
- Python: @ashu-cybertron
- Q-Sharp:

**Comment by ashu-cybertron** [comment]
assgn me for java and python

**Comment by ashu-cybertron** [comment]
I already did a pull request after writing code please check once
I am new at the open-source so plz help @atarax665

**Comment by ashu-cybertron** [comment]
it's completed in python saved in /python/others plz check @atarax665, but you haven't assigned me yet. plz  assign me and merge my pull request

**Comment by ps428** [comment]
Hi there!

Please assign me for Java, Python3 and C.

Regards

**Comment by charlie219** [comment]
@atarax665 I would love to contribute to the task through Python

**Comment by salonishah01** [comment]
@atarax665 Would like to contribute in C.

**Comment by the-agarwal01** [comment]
@atarax665 Hi,
Would love to contribute it in cpp! Plz assign me the task

**Comment by TrushaT** [comment]
Please assign me for Python

**Comment by iamrajiv** [comment]
@charlie219 @TrushaT Implementation in Python has already been done in #1405.

**Comment by ghost** [comment]
I want to know if I can contribute in MATLAB? Can we add it?

**Comment by aeyshubh** [comment]
As a part of my contribution in Woc , i would like to do this in java.
