### ISSUE TITLE
Implementation of Brick Sort/ Odd even sort

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#141]
**Algorithm: Implementation Of [Brick Sort](https://en.wikipedia.org/wiki/Odd%E2%80%93even_sort)**

an odd–even sort or odd–even transposition sort (also known as brick sort or parity sort) is a relatively simple sorting algorithm, developed originally for use on parallel processors with local interconnections. It is a comparison sort related to bubble sort,   It is a comparison sort related to bubble sort, with which it shares many characteristics. 

**Languages Supported:**
- C [@jivthesh ]
- C++
- C#
- Java
- Python [@sparkingdark ]
- JavaScript
- go
- dart

**Comment by HarshCasper** [comment]
Would you like to work on it @sparkingdark ?

**Comment by sparkingdark** [comment]
Assign  me the python.

**Comment by jivthesh** [comment]
Assign me c

**Comment by vgb-codes** [comment]
@sparkingdark Go ahead with Python
@jivthesh  Go ahead with C

**Comment by santushtisharma10** [comment]
@VijayaGB98 please assign me this issue in C++( HakinCodes(P))

**Comment by sonukushwaha403** [comment]
i would like to work with this by JAVA

**Comment by GrayFlash** [comment]
Can I work on C++
