### ISSUE TITLE
Algorithms and solution for compitative programming

### ISSUE THREAD

**Issue by twok020101** [HarshCasper/NeoAlgo#1423]
Hello,
I'm a compitative programmer and algorithm implimentor. I solve a lot of problems in different ways that are not available. I always try to minimize the time complexity. I would like to contribute solution to the world keeping intention inn mind that  can help a lot of budding programmers with learning logic.

**Comment by ashu-cybertron** [comment]
i would like to work in this in python and java or any one from both ,, please assign me , I hv some experience in it and I  can code in optimized way in contrast of time and space complexity

**Comment by Siddhant-K-code** [comment]
I can contribute Codeforces/ Codechef/ Leetcode Problems' solutions in C++

**Comment by ghost** [comment]
I can contribute MATLAB CODY problems' solutions and Hackerrank Python Solutions.

**Comment by 1711shashank** [comment]
I can contribute Gfg Problems' solutions in C++
