### ISSUE TITLE
ArraySub

### ISSUE THREAD

**Issue by JayantGoel001** [HarshCasper/NeoAlgo#1425]
## 🚀 Feature

Given an array and an integer k, find the maximum for each and every contiguous subarray of size k.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(Sliding window and Deque)

## Pitch

(It shows implementation and algorithm of heap or deque data structure )

I want to implement this in CPP

## Assignees

- C-Plus-Plus: @JayantGoel001 
- C-Sharp:
- C: @ananya0504 
- Go:
- Java: @limitless-Sky 
- JavaScript:
- Python: @ananya0504 
- Q-Sharp:

**Comment by ananya0504** [comment]
Hi, can I implement this problem? Please assign it to me

**Comment by iamrajiv** [comment]
@ananya0504 Sure. Specify the language in which you want to work.

**Comment by JayantGoel001** [comment]
@iamrajiv I have Made a PR 
Please Review It.

**Comment by limitless-Sky** [comment]
@iamrajiv Can I work on this in java.

**Comment by JayantGoel001** [comment]
@iamrajiv  Please Review It.

**Comment by ananya0504** [comment]
I can do it in Python and C
