### ISSUE TITLE
Merge Sort in JavaScript

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1427]
## 🚀 Feature

Adding Merge Sort function in JavaScript sort directory

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To implement a recursive function to sort a list in JavaScript using Merge sort.

## Pitch

Use Divide and Conquer and Recursion to implement merge sort.

**Comment by Siddhant-K-code** [comment]
I can do this in `JavaScript`

**Comment by joeyouss** [comment]
Hey! kindly assign this to me

**Comment by Sameera-Aryasomayajula** [comment]
I would like to work on the C++ version of this algorithm under DWOC.

**Comment by iamrajiv** [comment]
@Sameera-Aryasomayajula Merge sort in C++ has already been implemented.
