### ISSUE TITLE
Add code for number of binary trees to dp folder for Winter Of Code

### ISSUE THREAD

**Issue by yukty2000** [HarshCasper/NeoAlgo#1436]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I want to add the code for the following problem-
Calculate the number of binary trees possible given the length of the preorder traversal-n.
I am going to solve this problem using Dynamic Programming Approach and I want to add it to C-Plus-Plus/dp folder.
Please, assign it to me. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read the contributing guidelines.

## Assignees

- C-Plus-Plus: @yukty2000
- C-Sharp:
- C:
- Go:
- Java: @PuravUdayDesai 
- JavaScript:
- Python: @charlie219 
- Q-Sharp:

**Comment by iamrajiv** [comment]
@yukty2000 Sure but I would suggest of adding other approaches too like solving this using Catalan number or maybe more approaches which exist. Add all the approaches in a single file with proper comments specifying space and time complexity because this repository mainly deals with learning rather than efficient code so people can get to know all the approaches of solving the problem and can deduce better solutions maybe.

**Comment by charlie219** [comment]
@iamrajiv @atarax665 I want to take this issue in Python.
I also want to add other DP algorithms such as

Ugly numbers
Dice Throw Problem
Longest Common Subsequence
Longest Increasing Sequence
Partition Problem
0-1 Knapsack Problem
  
in Python

**Comment by PuravUdayDesai** [comment]
I want to take up this issue in **Java**

**Comment by yukty2000** [comment]
> @yukty2000 Sure but I would suggest of adding other approaches too like solving this using Catalan number or maybe more approaches which exist. Add all the approaches in a single file with proper comments specifying space and time complexity because this repository mainly deals with learning rather than efficient code so people can get to know all the approaches of solving the problem and can deduce better solutions maybe.

Yes, @iamrajiv sir ,I have used the catalan number approach(tabulation) in the linked pull request.
