### ISSUE TITLE
Include MATLAB for Winter of Code

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1438]
Feature:
Include MATLAB

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation:
It is a simple and easy programming language that is currently being used during the online conduction of various labs due to Covid-19.
It might be useful for many of us.

**Comment by iamrajiv** [comment]
Sorry but I don't think this is necessary as of now. We already have `C-Sharp`, `Kotlin` and `Q-Sharp` section which is far behind as compared to other sections so adding this will cause inconsistency since these languages rarely get contributions.

**Comment by ghost** [comment]
Okay sure, Thanks!
