### ISSUE TITLE
Boyer–Moore majority vote algorithm

### ISSUE THREAD

**Issue by aeyshubh** [HarshCasper/NeoAlgo#1439]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
The Boyer–Moore majority vote algorithm is an algorithm for finding the **majority of a sequence** of elements using linear time and constant space. 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

## Assignees

- C-Plus-Plus: @rutujadhanawade 
- C-Sharp:
- C: @barnamensch056 
- Go:
- Java: @ShubhamPatel33 
- JavaScript: @PuravUdayDesai 
- Python: @ShubhamPatel33 
- Q-Sharp:

**Comment by aeyshubh** [comment]
Can i do it in Python @iamrajiv

**Comment by ghost** [comment]
Can I do it in C++?

**Comment by barnamensch056** [comment]
Can I do it in C?

**Comment by PuravUdayDesai** [comment]
I want to take up this issue in **JavaScript**

**Comment by rutujadhanawade** [comment]
I would like to do this in C++ Please assign me this.
