### ISSUE TITLE
Generate all Pythagorean Triples within a Given limit in C++

### ISSUE THREAD

**Issue by deagleSC** [HarshCasper/NeoAlgo#1444]
## 🚀 Feature

(A Program to Generate all the Pythagorean Triples within a User-given limit)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation
(Pythagorean Triples Generation using Rationality relation is an important Math-centric algorithm.)

## Pitch
(A Program to Generate all the Pythagorean Triples within a user-given limit
SAMPLE I/O:
Enter a limit: 20
3 4 5
8 6 10
5 12 13
15 8 17
12 16 20)

**Comment by Sameera-Aryasomayajula** [comment]
Can you please assign this issue to me

**Comment by aryan-anand** [comment]
Can I go ahead with this?

**Comment by nayanajain** [comment]
please assign this issue yo me
