### ISSUE TITLE
Randomized Prim's Algorithm Python

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1453]
## 🚀 Feature

Algorithm for creating a maze.

### Have you read the [Contributing Guidelines on Pull Requests]?
Yes

## Motivation

Mazes are fun. 

## Pitch

This algorithm is a randomized version of Prim's algorithm. This algorithm introduces stylistic variation because the edges closer to the starting point have a lower effective weight.

**Comment by itskrypton** [comment]
@iamrajiv Can I go ahead with this?

**Comment by itskrypton** [comment]
@iamrajiv Kindly respond

**Comment by barnamensch056** [comment]
I can do it in python or C,please assign

**Comment by aryan-anand** [comment]
Can you please assign this issue to me

**Comment by goelesha** [comment]
Pls, assign this issue to me. I am selected for WoC
