### ISSUE TITLE
Dynamic Programming/Winter of code

### ISSUE THREAD

**Issue by atriadhiakri2000** [HarshCasper/NeoAlgo#1455]
## 🚀 Feature
(A clear and concise description of what the feature is.)

Add the following problems:
- **Longest common subsequence
- Longest increasing subsequence
- Egg Dropping Puzzle 
- Count ways to N'th Stair(Order does not matter) 
- Optimal Strategy For A Game 
- Kadane's Algorithm 
- Brackets in Matrix Chain Multiplication 
- Unique BST's 
- Count in array 
- Unique partitions** 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
YES
## Motivation

(Please outline the motivation for the proposal.)
Dynamic programming is used when the given **problem can be divided** into similar s**ub-problems, so that their results can be re-used**. Before solving the current subproblem, dynamic algorithm will try to examine the results of the previously solved subproblems. Mostly, these algorithms are used for optimization.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Since Dynamic Programing is quite **commonly asked interview** . 
Since the core idea is to use the previously calculated data we can use it for databases caching common queries in memory, through dedicated cache tiers storing data to avoid DB access, webservers store common data like configuration that can be used across requests.

**Comment by atriadhiakri2000** [comment]
I want to take Longest common subsequence and Longest increasing subsequence in python. Please assign me the task.

**Comment by ghost** [comment]
Can I take Egg dropping puzzle in python?

**Comment by shraddhavp** [comment]
assigned @itskrypton  and @atriadhiakri2000

**Comment by aeyshubh** [comment]
I would like to take (Count Ways to nth stair) in Java And Python

**Comment by Bharati2612** [comment]
I would like to take egg dropping puzzel in Cpp.Please assign.

**Comment by charlie219** [comment]
I would like to take Unique BST in Python. (Catalan Approach) .

**Comment by rutujadhanawade** [comment]
I would like to work on unique BSTs in C++, java, C

**Comment by jyoti-2** [comment]
Hello!
I would like to work on Karden's algorithm and count on the array in Python3.
pls assign

**Comment by shraddhavp** [comment]
assigned @jyoti-2

**Comment by shraddhavp** [comment]
assigned @rutujadhanawade

**Comment by pranjalshinde** [comment]
I would like to work on Kadane's algorithm in Java, Please assign

**Comment by atriadhiakri2000** [comment]
Egg Dropping Puzzle
Count ways to N'th Stair(Order does not matter)
Optimal Strategy For A Game
Kadane's Algorithm
please assign me these in python
@iamrajiv @shraddhavp @HarshCasper

**Comment by atriadhiakri2000** [comment]
@iamrajiv @shraddhavp @HarshCasper What about the rest can i be assigned to them ?
