### ISSUE TITLE
Addition to Dynamic Programming/Winter of Code

### ISSUE THREAD

**Issue by Bharati2612** [HarshCasper/NeoAlgo#1459]
## 🚀 Feature

(A clear and concise description of what the feature is.)

Add some new set of algorithms in DP section:

- Matrix chain multipliaction

- Egg dropping problem

- 0/1 Knapsack problem

- Subset sum problem

- Longest Common Subsequence

- Partition problem

- Fibonacci Algorithm 

- Rod cutting Problem

- Coin change Problem

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I read it.

## Motivation
(Please outline the motivation for the proposal.)
Dynamic programming uses the three major concepts Optimal Substructure, Memoization and Overlaping Subproblem. So it uses the previously solved subproblems optimal result to compute the next subproblem.To get the optimized result from exponential time to polynomial we use this algorithms.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
These are the most important algorithms which are asked in various technical interviews and competitive programs so it will help to learn and grow.

**Comment by Bharati2612** [comment]
I want to take Matrix chain multiplication in C++. Please someone assign me this.

**Comment by Bharati2612** [comment]
I want to solve 0/1 Knapsack as well in C++.Kindly assign it to me.

**Comment by HarshCasper** [comment]
@Bharati2612 Make two separate PRs for both of the Problems

**Comment by manasisaiba** [comment]
I want to take coin change problem in c++. Please assign it to me!

**Comment by manasisaiba** [comment]
I want to take egg dropping problem assign it me please in c++!

**Comment by Neilblaze** [comment]
@manasisaiba Go for it. Make sure you follow [contributing guidelines](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md) & create separate PR for 2 different problems.

**Comment by rutujadhanawade** [comment]
I would like to take 
Rod cutting Problem in C,C++ and java 
coin change in C, java
@iamrajiv

**Comment by HarshCasper** [comment]
> I would like to take
> Rod cutting Problem in C,C++ and java
> coin change in C, java
> @iamrajiv

Please make a separate Issue @rutujadhanawade 

I am closing this Issue
