### ISSUE TITLE
Addition to Graph Algorithms / Winter of Code

### ISSUE THREAD

**Issue by Bharati2612** [HarshCasper/NeoAlgo#1463]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

Add new set of algorithms to DP section:

- Depth First Search Tree Traversal

- Single Source Shortest Path Algorithm (2 Algorithms)

- Strongly Connected Components.

- Finding Inorder Successor of a Node in a Binary Tree.

- Finding Inorder Predecessor of a Node in a Binary Tree.

I would like to add some other variations of Minimum Spanning Tree and applications of BFS and DFS which are very useful in competitive programming point of view.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
(Write your answer here.)
Yes, I read the guidelines.

**Comment by Bharati2612** [comment]
I would like to take DFS traversal someone please assign it to me. **WoC**

**Comment by rutujadhanawade** [comment]
I would like to take this in C++ and java.
Finding Inorder Successor of a Node in a Binary Tree

**Comment by Neilblaze** [comment]
@rutujadhanawade Go for it! Make sure to follow the [contributing guidelines](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md).

**Comment by RhuthuHegde** [comment]
can I work on dfs algorithm in python?

**Comment by HarshCasper** [comment]
> can I work on dfs algorithm in python?

Go ahead!

**Comment by RhuthuHegde** [comment]
I have made a pull request please review it.
