### ISSUE TITLE
Operating system algorithms for WoC

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1464]
## 💥 Proposal
Addition of Operating system algorithms

Implementations of FCFS scheduling algorithm using C++.
Implementation of Shortest Job First (SJF) Non-Preemptive CPU scheduling algorithm using C++.
Implementation of Shortest Job First (SJF) Preemptive CPU scheduling algorithm using C++.
Implementation of Priority scheduling (Preemptive) algorithm using C++.
Implementation of Priority scheduling (Non-Preemptive) algorithm using C++.
Implementation of the Round Robin CPU Scheduling algorithm using C++.
Analysis of LRU page replacement algorithm and Belady's anomaly

I would like to get these algorithms added which are very useful in competitive programming point of view.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by k-sashank** [comment]
I've just added the required files and created a PR!
Please Review it!

**Comment by ghost** [comment]
Oh, I am extremely sorry, must have missed it.

**Comment by k-sashank** [comment]
@itskrypton I added them earlier!
Waiting for the PR to get merged!
