### ISSUE TITLE
Knapsack Problem - Greedy Method (WoC)

### ISSUE THREAD

**Issue by k-sashank** [HarshCasper/NeoAlgo#1469]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

## Motivation

(Please outline the motivation for the proposal.)
This problem is very prominent in DSA and Competitive Programming.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
The program outputs the optimum method in which objects must be added to a Knapsack based on their weights and Profits. The program takes as input the objects, their profits, and their weights. The output is the maximum profit one might attain using this combination of inputs. This problem is a very famous DSA problem and hence must be added to the repo.

**Comment by k-sashank** [comment]
Please assign this issue to me for Python!

**Comment by atriadhiakri2000** [comment]
I will love to Add this problem

**Comment by Sameera-Aryasomayajula** [comment]
Can I please work on the C++ version of this problem under DWOC ?
