### ISSUE TITLE
Implement Level order traversal of tree

### ISSUE THREAD

**Issue by priyanka2109** [HarshCasper/NeoAlgo#147]
**Algorithm:** 

**DS:** 
Queue
**Languages Supported:**

- c
- c++ [@priyanka2109]
- java [@Vrindagupta6828]
- python [@GSNCodes ]
- javascript

-

**Comment by priyanka2109** [comment]
Please assign it to me in c++

**Comment by GSNCodes** [comment]
Hi @HarshCasper I can work on this in Python

**Comment by Vrindagupta6828** [comment]
Can i work on this in java @vijayaGb98?

**Comment by vgb-codes** [comment]
@VijayaGB98 Go ahead with Java.
