### ISSUE TITLE
Adding MCM problem in Python.

### ISSUE THREAD

**Issue by Pranav016** [HarshCasper/NeoAlgo#1474]
## 🚀 Feature
I would like to add a Dynamic programming question of Matrix Chain multiplication in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [x] Yes

## Motivation
I'll be working on this under **WoC**. Also, it is a very prominent interview problem. 

## Pitch
I would like to add this problem since there are a lot of variations of this problem asked in interviews. I would like to work on this in Python and C++.

**Comment by HarshCasper** [comment]
It is already being worked on by other Contributors.

**Comment by Pranav016** [comment]
> It is already being worked on by other Contributors.

Updated the issue, no one is working on this problem in python so I would like to add its code in Python :)

**Comment by Pranav016** [comment]
@shraddhavp Can I work on this?
