### ISSUE TITLE
Adding Backtracking algorithms in Python.

### ISSUE THREAD

**Issue by Pranav016** [HarshCasper/NeoAlgo#1475]
## 🚀 Feature
I would like to add the following backtracking algorithms to this project in Python language.
1. N-queens
1. Sudoku Solver
1. Rat in maze

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [x] Yes

## Motivation
There are no backtracking algorithms added to the Python folder. I'll be working on this under **WoC**.

## Pitch
These are some of the most famous backtracking problems and are often asked in interviews.

**Comment by HarshCasper** [comment]
Make sure to have different PRs for different algorithms.

**Comment by charlie219** [comment]
@HarshCasper  I want to contribute to the Backtracking Folder with
- Subset Sum
- Knight's Tour Problem
- Hamiltonian Cycle
All the above problems will be using Backtracking in Python. Please assign me the Issue
I will make sure to make separate PR for each of the above mentioned Algo

**Comment by shraddhavp** [comment]
assigned @charlie219
