### ISSUE TITLE
Improve the Python folder structure.

### ISSUE THREAD

**Issue by Pranav016** [HarshCasper/NeoAlgo#1476]
## 💥 Proposal
I would like to improve the Python folder of this project by segregating the various algorithms in its `ds` folder to a more precise ds name. Example- Linked List problems and Trees problems will be segregated to their respective folders instead of a single `ds` folder.

I would like to work on this under **WoC**

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by shraddhavp** [comment]
@Pranav016  what are the extra things you will be adding apart from re-arranging?
