### ISSUE TITLE
Linked List Implementation in JavaScript

### ISSUE THREAD

**Issue by ghost** [HarshCasper/NeoAlgo#1478]
## 🚀 Feature

(A clear and concise description of what the feature is.)
To implement singly linked list in JavaScript using ES6

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)
I found that the ds folder for JavaScript is pretty empty, so contribute to it.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Code implementation with clear and concise comments and structuring.
Please assign this issue to me.

**Comment by ghost** [comment]
@iamrajiv Sir, please assign this issue to me.

**Comment by pranjalshinde** [comment]
Can I solve this in Java? Also add DWOC label to it.

**Comment by HarshCasper** [comment]
> Can I solve this in Java? Also add DWOC label to it.

@pranjalshinde
