### ISSUE TITLE
Graphs/Winter of Code

### ISSUE THREAD

**Issue by atriadhiakri2000** [HarshCasper/NeoAlgo#1479]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Add the following problems:
o	Knight Walk
o	Kosaraju's Algo
o	Detect cycle in an undirected graph 
o	Hamiltonian Path 
o	Topological sort 
o	Bridge Edge in Graph 
o	Your Social Network 
o	Floyd Warshall 
o	Bipartite Graph 
o	Negative weight cycle 
o	Eulerian Path in an Undirected Graph 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
In computer science, a **graph is an abstract data type** that is meant to implement the **undirected graph** and **directed graph** concepts from the field of graph theory within mathematics. 
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
**Google maps** uses graphs for building transportation systems, where **intersection of two(or more) roads** are considered to be a **vertex** and the **road connecting two vertices** is considered to be an **edge**, thus their navigation system is based on the algorithm to calculate the shortest path between two vertices.

**Comment by atriadhiakri2000** [comment]
I want to take Knight Walk and Floyd Warshall in python. Please assign me the task.

**Comment by k-sashank** [comment]
I would like to work on the Topological sort problem in Python. Please assign me the task!

**Comment by barnamensch056** [comment]
Want to go for Hamiltonian path and Eulerian path in undirected graph in python or C.

**Comment by charlie219** [comment]
I want to take the following tasks in Python
- Hamiltonian Path
- Articulation Point
- Topological Sort
- Strongly Connected Component (Tarjan's Algorithm)

@shraddhavp @HarshCasper @iamrajiv  please assign me this task
I will make sure to make different Branches and PR for each of the above-mentioned algorithms

**Comment by atriadhiakri2000** [comment]
I want to be assigned with Bridge Edge in Graph and Your Social Network
@shraddhavp  @HarshCasper  @iamrajiv

**Comment by barnamensch056** [comment]
> Want to go for Hamiltonian path and Eulerian path in undirected graph in python or C.

@shraddhavp @HarshCasper @iamrajiv  kindly assign the task.

**Comment by shraddhavp** [comment]
assigned @atriadhiakri2000

**Comment by charlie219** [comment]
@shraddhavp @HarshCasper @iamrajiv   I would like to have 
- SCC via Kosaraju's Algo
- SCC via Tarjans's Algo
- Bipartite Graph

please assign this task to me

**Comment by atriadhiakri2000** [comment]
Please assign me Eulerian Path in an Undirected Graph 
@shraddhavp  @HarshCasper @iamrajiv

**Comment by shraddhavp** [comment]
ya yor are assigned @atriadhiakri2000
