### ISSUE TITLE
MNIST Dataset Classifier using ANNs

### ISSUE THREAD

**Issue by k-sashank** [HarshCasper/NeoAlgo#1483]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I want to add a Python Notebook which classifies the MNIST Hand-written Digits dataset using TensorFlow (Python).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes.

## Motivation

(Please outline the motivation for the proposal.)
The MNIST dataset is a basic dataset and most Deep Learning enthusiasts get started with this dataset.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
The MNIST (Modified National Institute of Standards and Technology) dataset contains hand-written digits from 0 to 9 (10 classes) which must be classified using a simple Artificial Neural Network. The ANN for this dataset is usually implemented at the beginning of exploring DL.

**Comment by k-sashank** [comment]
Please assign this task to me in Python.

**Comment by k-sashank** [comment]
@iamrajiv @shraddhavp Please assign this task to me in Python.

**Comment by k-sashank** [comment]
@iamrajiv @shraddhavp Please assign this task to me in Python!

**Comment by shraddhavp** [comment]
assugned @k-sashank
