### ISSUE TITLE
Kotlin Algorithms

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#1487]
## 💥 Proposal

I noticed almost zero algorithms are present in the folder of Kolin. Can I add the basic Areas problem as my WoC contribution?
Kindly assign me the Areas Problems in Kotlin.
Thank You

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by fomalhauting** [comment]
Can I take up this task? Kindly assign it to me, please. @shraddhavp

**Comment by shraddhavp** [comment]
assigned @itsIapetus

**Comment by iamvs-2002** [comment]
I do mostly Java, but learning Kotlin for a while. Would love to add some sorting/ searching algorithms in Kotlin. Kindly assign me the issue to add some sorting/ searching algorithms in Kotlin.

**Comment by shraddhavp** [comment]
assigned @iamvs-2002

**Comment by iamvs-2002** [comment]
Thankyou! I am on it.

**Comment by iamvs-2002** [comment]
I am trying to add heapsort.kt file but it is adding it in the same pull request. Is there any way I can make a new pull request for the different issue?

**Comment by iamvs-2002** [comment]
I have started adding the implementations.

These contributions are for DWOC - DevScript Winter of Code.
Thank you!

**Comment by iamvs-2002** [comment]
@shraddhavp There were some issues in the files and also it was those I had learned from youtube. So I closed the pull requests. I'd rather implement them entirely by myself and then submit them.

**Comment by HarshCasper** [comment]
@iamvs-2002 

It would be recommended to make separate Issues for all of them and raise PRs for them subsequently. We are here to help you out :)
