### ISSUE TITLE
Implementation of stack with different operations

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#149]
**DS:Stack** 

**Languages Supported:**
- C
- C++ [@harsh-9in]
- C#
- java
- JavaScript
- python [@GSNCodes ]
- go [@VijayaGB98]
- dart

**Comment by vgb-codes** [comment]
@HarshCasper @ricardoprins  
I can do it in Go.

**Comment by mar-galho** [comment]
@VijayaGB98, you can go with Go then XD

**Comment by harsh7in** [comment]
Can I work on this using c++?

**Comment by mar-galho** [comment]
Sure!

**Comment by MSufiyanAG** [comment]
@ricardoprins I want to do this in java

**Comment by mar-galho** [comment]
@MSufiyanAG awesome!

**Comment by GSNCodes** [comment]
I can work on this in Python!

**Comment by mar-galho** [comment]
Great!

**Comment by sameersrivastava13** [comment]
Can I work on this using C?
@ricardoprins

**Comment by sameersrivastava13** [comment]
@sparkingdark @ricardoprins @HarshCasper 
Can I work on this using C?
