### ISSUE TITLE
Next Permutation

### ISSUE THREAD

**Issue by YASH01009** [HarshCasper/NeoAlgo#1490]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(WoC)

## Pitch

(Implement the next permutation, which rearranges numbers into the numerically next greater permutation of numbers for a given array A of size N)

**Comment by YASH01009** [comment]
Please assign me this issue in C++

**Comment by YASH01009** [comment]
@shraddhavp can u pls look into this issue and assign me this?

**Comment by aryan-anand** [comment]
Can you please assign this issue to me in C++ or python

**Comment by Neilblaze** [comment]
@aryan-anand Assigned for python!

**Comment by pranjalshinde** [comment]
I want to solve this in Java, please assign

**Comment by shraddhavp** [comment]
assigned @pranjalshinde

**Comment by pranjalshinde** [comment]
I have solved the problem and created pull request

**Comment by pranjalshinde** [comment]
#1709

**Comment by pranjalshinde** [comment]
please review my PR https://github.com/TesseractCoding/NeoAlgo/pull/1709

**Comment by pranjalshinde** [comment]
@shraddhavp 

> please review my PR #1709
