### ISSUE TITLE
Check for Bipartite Graph

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1493]
## 🚀 Feature

Add program to check if a given graph is Bipartite. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

2 coloring problem in graph can be solved easily by checking if the graph is bipartite in nature.

## Pitch

Enriches the library

**Comment by gargVader** [comment]
Can I go ahead with this?

**Comment by shraddhavp** [comment]
assigned @gargVader

**Comment by shraddhavp** [comment]
please mention the coding language

**Comment by gargVader** [comment]
Added in C++ #1510

**Comment by charlie219** [comment]
I want to take this issue in Python

**Comment by shivanshugarg12800** [comment]
I want to solve this issue with a relatively shorter code in c++

**Comment by Neilblaze** [comment]
@charlie219 @shivanshugarg12800 Assigned!
