### ISSUE TITLE
Add Cryptography algorithms [Winter of Code]

### ISSUE THREAD

**Issue by Sejal-G** [HarshCasper/NeoAlgo#1494]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

Add a new set of algorithms to the cryptography section:

Implementation of Caeser Cipher in C++
Implementation of Modified Caeser Cipher in C++
Implementation of Homophonic Cipher in C++
Implementation of Rail Fence Cipher (transposition technique) in C++
Implementation of Simple Columnar Transposition in C++
Implementation of Simple Columnar transposition with multiple rounds in C++

### Have you read the [Contributing Guidelines on Pull Requests]
Yes, I have read the guidelines.

**Comment by PuravUdayDesai** [comment]
@shraddhavp I want to take up this issue in **Java**

**Comment by Neilblaze** [comment]
@PuravUdayDesai Go for it!

**Comment by nerdynikhil** [comment]
@shraddhavp @Neilblaze Did PuravUdayDesai completed them? If not, I want to be assigned.

**Comment by PuravUdayDesai** [comment]
@nerdynikhil so sorry for late reply just saw your comment, I am planning to add a pull request tomorrow morning for all the algorithms, thank you so much for your interest and time.

**Comment by PuravUdayDesai** [comment]
> @nerdynikhil so sorry for late reply just saw your comment, I am planning to add a pull request tomorrow morning for all the algorithms, thank you so much for your interest and time.

Sorry for delay
