### ISSUE TITLE
Cody Problem Solutions

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#1495]
## 🚀 Feature

Addition of Problems and solutions of Cody Contest, which is organized by MATLAB on a global level.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I took part in that contest for the first time this year and found a good collection of problems ranging from very easy to very difficult ones. I feel It would be good to have those too.

## Pitch

In miscellaneous can I add the Problems and Solutions of Cody Contest, being organized by MATLAB on a global level.
It has over 50,000 thousand problems. 
Kindly assign it to me if it's appropriate.
Thank You.

**Comment by shraddhavp** [comment]
can you create different issue for atleast 1 or 2 problems for us to figure out? @itsIapetus

**Comment by fomalhauting** [comment]
Okay sure!
