### ISSUE TITLE
House Price Prediction - Machine Learning (WoC)

### ISSUE THREAD

**Issue by k-sashank** [HarshCasper/NeoAlgo#1498]
## 🚀 Feature

(A clear and concise description of what the feature is.)
This Machine Learning algorithm would be able to predict the price of a particular house based on certain inputs (such as Area, City, Country, etc.).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes.

## Motivation

(Please outline the motivation for the proposal.)
The House Price dataset is a very basic Machine Learning Dataset and is used as a starter Dataset for Machine Learning.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
The House Price Prediction dataset has 18 features and a Machine Learning algorithm is trained on this data. Then, whenever the ML model is given these new inputs, it predicts the price of the house. Since this is a basic dataset, the code might help a lot of students wanting to learn Machine Learning.

**Comment by k-sashank** [comment]
Please assign this issue to me in Python!

**Comment by HarshCasper** [comment]
Are you working on it @k-sashank ?
