### ISSUE TITLE
Add Insertion Sort Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#15]
**Algorithm:** 

[Insertion Sort](https://en.wikipedia.org/wiki/Insertion_sort)

**DS:** 

Sorting

**Languages Missing:**

- C#
- Javascript [@sparkingdark ]

**Comment by keshav304** [comment]
can I work on this for languages c++, python?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @keshav304 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also, reference this Issue in your PR so that it becomes easy for us to review.

**Comment by Surajv311** [comment]
@HarshCasper Can you assign me this issue ? I can work on C language

**Comment by HarshCasper** [comment]
I have assigned you the Issue in C @Surajv311 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by RaviAnand111** [comment]
Hey I want to add the algorithm in java Can you assign it to me

**Comment by HarshCasper** [comment]
You can start working on it @RaviAnand111

**Comment by sparkingdark** [comment]
assign me the javascript

**Comment by mar-galho** [comment]
game on, @sparkingdark !

**Comment by bagladivyang03** [comment]
Can i implement this in c++

**Comment by atarax665** [comment]
@bagladivyang03 Sorry, but it has already been implemented in C++.

**Comment by Sohailsaifi** [comment]
can you assign this issue to me I can work on this for java language?

**Comment by vinayvyas911** [comment]
@HarshCasper can you assign me this issue?
I work on JavaScript

**Comment by ShreyasKadiri** [comment]
Can I work on Java?
