### ISSUE TITLE
Implementation of queue 

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#150]
**DS:Queue** 

**Languages Supported:**
- C
- C++
- C#
- Java
- JavaScript
- Python
- Go
- Dart

**Comment by jivthesh** [comment]
can i work in this using c ?

**Comment by srinivasdasu24** [comment]
@sparkingdark can you assign this issue, I will code in python

**Comment by srinivasdasu24** [comment]
@sparkingdark can you assign this issue, I will code in python

**Comment by MSufiyanAG** [comment]
@ricardoprins  I want to work on this in java.

**Comment by mar-galho** [comment]
So, we have:
@jivthesh - C
@srinivasdasu24  - Python
@MSufiyanAG - Java

**Comment by srinivasdasu24** [comment]
@ricardoprins created pull request https://github.com/TesseractCoding/NeoAlgo/pull/234 for queue implementation in python

**Comment by vgb-codes** [comment]
@ricardoprins I can do it in Go.

**Comment by bagladivyang03** [comment]
Can i do this in C++

**Comment by HarshCasper** [comment]
Assigned to you @bagladivyang03 🙌

**Comment by atarax665** [comment]
Queue DS has already been implemented in C++ by @ricardoprins .

**Comment by subhayu99** [comment]
@ricardoprins can I implement Queue in either C or Python?

**Comment by atarax665** [comment]
@subhayu99 You can start working on this in Python.
