### ISSUE TITLE
Cody Problems and Solutions -  All Things Fibonacci

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#1512]
## 🚀 Feature

All Things Fibonacci Problems in Cody Contest organized by MATLAB

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

I took part in Cody Contest this year and found around 50,000+ amazing and fun problems just like this one.

## Pitch

It's everybody's favorite algorithmic sequence. As a result, it shows up everywhere people write code. And there is a collection of 9 Fibonacci-related problems on Cody.

**Comment by fomalhauting** [comment]
I would like to take up this task if it's appropriate, under Misc. Problems and Solutions.
Thank you.

**Comment by fomalhauting** [comment]
@shraddhavp Can I take this up? If so please assign it to me, thank you.

**Comment by shraddhavp** [comment]
assigned @itsIapetus  ,also mention the language you are going to code in

**Comment by fomalhauting** [comment]
As its a MATLAB competition so I will be writing the codes in MATLAB itself.

**Comment by iamrajiv** [comment]
@itsIapetus Sorry but I don't think this is necessary as of now. We already have `C-Sharp`, `Kotlin` and `Q-Sharp` section which is far behind as compared to other sections so adding this will cause inconsistency since these languages rarely get contributions.
