### ISSUE TITLE
N-Queens problem in Java / WoC

### ISSUE THREAD

**Issue by YASH01009** [HarshCasper/NeoAlgo#1524]
## 🚀 Feature

(A backtracking solution for N-Queens problem)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(WoC)

**Comment by YASH01009** [comment]
Please assign this to me in C++, Java

**Comment by charlie219** [comment]
@shraddhavp 
I want to take this task in Python under Backtracking Algorithms

**Comment by YASH01009** [comment]
Sure, @charlie219 I am taking it only in C++ and Java

**Comment by shraddhavp** [comment]
assigned @charlie219  you can do it in python
