### ISSUE TITLE
Josephus Problem / WoC

### ISSUE THREAD

**Issue by YASH01009** [HarshCasper/NeoAlgo#1525]
## 🚀 Feature

(A recursive solution)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(WoC)

**Comment by YASH01009** [comment]
Please assign this to me in C, C++, Java

**Comment by yashaswibiyahut** [comment]
@YASH01009 go with cpp

**Comment by YASH01009** [comment]
Can I do in all three languages or restrict myself to CPP?

**Comment by yashaswibiyahut** [comment]
@YASH01009 firstly complete in one language so that others also get a chance to contribute.

**Comment by mehabhalodiya** [comment]
Please assign this to me in Python.
