### ISSUE TITLE
Math Programs (WoC)

### ISSUE THREAD

**Issue by k-sashank** [HarshCasper/NeoAlgo#1527]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I want to add the following Number programs:
1. Strong Numbers
2. Amstrong Numbers
3. Harshad Numbers
4. Palindrome Numbers
5. Pythagorean Triplet
6. Superfactorial

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes!

## Motivation

(Please outline the motivation for the proposal.)
The above-mentioned numbers are some common programs taught to students in CSE and sometimes asked in interviews.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
The above-mentioned are some lesser-known number types which however are some common programming problems. Input is given to the program to verify whether it is a particular number type or not. These are a few basic number types every programming enthusiast must know.

**Comment by k-sashank** [comment]
@shraddhavp @iamrajiv I would like to do this task in Python!
Please assign it to me!

**Comment by Tausif121** [comment]
@shraddhavp , @iamrajiv , @shraddhavp , Can I add Automorphic number and Kaprekar number in C (or should i make a new issue) ?

**Comment by shraddhavp** [comment]
create a new issue @Tausif121

**Comment by nayanajain** [comment]
Please assign this issue yo me, in c++
