### ISSUE TITLE
[SUGGESTION] Improve structure of repo 

### ISSUE THREAD

**Issue by omonimus1** [HarshCasper/NeoAlgo#154]
For every language, we should add a folder for every data structure and inside this folder, all the implementation of the algorithms related to this D.S.

**Comment by mar-galho** [comment]
We will add more folders once we have more code :)

**Comment by omonimus1** [comment]
@ricardoprins  it will require more time later on doing this. If we just do this structural update now,  we will need to update few rows for every README file :) 

Then we can just update the **how to contribute and checklist for pull request**, and for all the other pull requests in the future it will be automatically done by contributors :) (saving us a lot of time and avoiding effort.

**Comment by mar-galho** [comment]
I have bots to run it, I can do it in less than a second, actually. It won't be an issue. It's just to make sure that we use the best folder structure - there are conflicting suggestions on which to use
