### ISSUE TITLE
C Code for Stack Implementation & Functionalities / WoC

### ISSUE THREAD

**Issue by goelesha** [HarshCasper/NeoAlgo#1542]
## 🚀 Feature

Code in C for stack implementation & code for its functions(puch,pop,etc). 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
WoC

**Comment by goelesha** [comment]
Kindly assign this issue to me.

**Comment by satyampgt4** [comment]
I want to take this same task in c++
