### ISSUE TITLE
Stack based problems

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1544]
## 🚀 Feature

Separate section for stack based problems in C++. Some problems that I want to add :

- Stock Span Problem
- Balanced Parenthesis
- Largest Area Under Histogram

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Such problems will help users understand the application of stack data structure

## Pitch

Only knowing the implementation of stack data structure is not very useful until we have applied it on problems.

**Comment by gargVader** [comment]
Please assign this to me

**Comment by YASH01009** [comment]
@shraddhavp Can u pls look into this issue and assign me in Java..

**Comment by atarax665** [comment]
@gargVader I will advice you to make individual issue for the mentioned stack based problems, it will help the project maintainers to convert it into a general issue and assign it to other willing contributors in other languages.

**Comment by 1711shashank** [comment]
👍
