### ISSUE TITLE
Remove unnecessary README.md in subfolders

### ISSUE THREAD

**Issue by HeinKhantZaw** [HarshCasper/NeoAlgo#1547]
## 📚 Documentation

I found some README.md files while searching algorithms in sub folders of Python folder.
Here is the screenshot.

![bug](https://user-images.githubusercontent.com/40730345/102119826-1e448b80-3e70-11eb-872d-e2aeccd59d28.png)

TBH, I think it's unnecessary to add README.md files in sub folders when we already have README.md for each language. 

And when I track back the commit history, I found that someone push these files during this [commit](https://github.com/TesseractCoding/NeoAlgo/commit/e256dfe598d3cc3d5b2a57c5525b77a80d24eb40)
![bug1](https://user-images.githubusercontent.com/40730345/102120266-b04c9400-3e70-11eb-9728-e487be99d6f2.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

P.S. I'm willing to remove these files if you want me to.

**Comment by mohd-hirani** [comment]
I am interested in this issue;
Kindly assign it to me .
