### ISSUE TITLE
Add Data Encryption Standard(DES) Symmetric Key Cryptography Algorithm / WoC

### ISSUE THREAD

**Issue by PuravUdayDesai** [HarshCasper/NeoAlgo#1553]
## 🚀 Feature

The feature proposal describes to add DES(Data Encryption Standard) Symmetric Key Cryptography Algorithm to the repository, I suggest to work on a **64-bit algorithm**(Plain Text: 64-bits and Cypher Text: 64-bits) in this Feature Request Issue.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

While surfing the repository I found a bundle of useful cryptography algorithms in the repository, but I observed an absence of DES Algorithm, which was one of the widely used symmetric-key cryptography algorithms.

## Pitch

The DES algorithm is the most widely used encryption algorithm in the world, DES has been found vulnerable/breakable against many attacks, reflecting it's a decline in popularity but despite this DES will live in many government and banking for years, due to its successor algorithms Triple-DES, AES, etc.

## Reference for understanding the algorithm 

[The DES Algorithm Illustration](http://page.math.tu-berlin.de/~kant/teaching/hess/krypto-ws2006/des.htm)

**Comment by PuravUdayDesai** [comment]
@iamrajiv I would like to take up this issue in **Java**

**Comment by PuravUdayDesai** [comment]
@iamrajiv can I create a DES folder under Java/Cryptography/ in pull request, as there are many modules in DES, each module has a unique function/task to perform, so I have created separate classes for each function/task. Clubbing each task together under one class which make the code large and chaotic.

**Comment by iamrajiv** [comment]
@PuravUdayDesai Sure. Also, make sure you explain every module with proper code comments.

**Comment by PuravUdayDesai** [comment]
@iamrajiv Sure, I'll do the respective.

**Comment by PuravUdayDesai** [comment]
Ok @HarshCasper I'll do that.

One clarification, there are 12 code files, which resides under 5 different folders and subfolders, so shall I make a PR for every folder/ file.

Sorry, I am a newbie, if you could explain the procedure for which you are looking for, then I'll be glad to understand it, as it'll save yours as well as my time.

Thank you.

**Comment by PuravUdayDesai** [comment]
> Ok @HarshCasper I'll do that.
> 
> One clarification, there are 12 code files, which resides under 5 different folders and subfolders, so shall I make a PR for every folder/ file.
> 
> Sorry, I am a newbie, if you could explain the procedure for which you are looking for, then I'll be glad to understand it, as it'll save yours as well as my time.
> 
> Thank you.

@iamrajiv Please help in the respective matter if possible.

**Comment by HarshCasper** [comment]
> Ok @HarshCasper I'll do that.
> 
> One clarification, there are 12 code files, which resides under 5 different folders and subfolders, so shall I make a PR for every folder/ file.
> 
> Sorry, I am a newbie, if you could explain the procedure for which you are looking for, then I'll be glad to understand it, as it'll save yours as well as my time.
> 
> Thank you.

Yes, please make a PR for them individually.
