### ISSUE TITLE
Depth of the tree for cpp / WOC

### ISSUE THREAD

**Issue by satyampgt4** [HarshCasper/NeoAlgo#1558]
## 🚀 Feature

This is recursion based algorithm to find the depth of tree 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Depth of the tree is very common and important property of tree. sometime it is  ask in interview also.

## Pitch

This algorithm is  part of following topic - graphs , recursion and divide & conquer strategy

**Comment by satyampgt4** [comment]
@shraddhavp @ErzaTitania-2001 @iamrajiv   I would like to do this task 
Please assign it to me!

**Comment by shraddhavp** [comment]
Specify the language to be used

**Comment by satyampgt4** [comment]
i will use c++
