### ISSUE TITLE
Program to Print ancestors of given numbers in BST

### ISSUE THREAD

**Issue by vrandachag** [HarshCasper/NeoAlgo#1565]
## 🚀 Feature

The program will print ancestors of two given numbers in a Binary Search Tree.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by vrandachag** [comment]
I would like to add C++ program for this issue. Please assign this to me.

**Comment by pranjalshinde** [comment]
I would like to work on this problem in Java, please assign
