### ISSUE TITLE
Stock Span Problem - Stack

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1566]
## 🚀 Feature

Stock Span problem in C++. Also suggest a separate section for stack based problems.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Stock span problem is an interesting problem of the stack.

## Pitch

Will help understand the stack data structure

## Assignees:

C: @rutujadhanawade 
C++: @gargVader
Java: @YASH01009 
Python: @rutujadhanawade 
JavaScript:
Go:
C#:

**Comment by gargVader** [comment]
Please assign this to me in c++

**Comment by YASH01009** [comment]
@shraddhavp Please assign this to me in Java

**Comment by gargVader** [comment]
@shraddhavp Should I make separate section for stack based probems?

**Comment by shraddhavp** [comment]
assigned @YASH01009

**Comment by nayanajain** [comment]
please assign this issue yo me in c++

**Comment by gargVader** [comment]
@nayanajain C++ code has been merged via #1600

**Comment by rutujadhanawade** [comment]
I would like to do this in python & C @shraddhavp Please assign this to me.
@iamrajiv
