### ISSUE TITLE
Balanced Parenthesis - Stack

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1567]
## 🚀 Feature

Balanced Parenthesis problem in C++. Also suggest a separate section for stack based problems.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Balanced Parenthesis problem is an interesting problem of stack.

## Pitch

Will help understand the stack data structure

**Comment by gargVader** [comment]
Please assign me this

**Comment by YASH01009** [comment]
@shraddhavp Please assign this to me in Java

**Comment by Rishikeshrajrxl** [comment]
I want to do this in c++

**Comment by pranjalshinde** [comment]
I would like to solve this in Java, please assign

**Comment by Pranav016** [comment]
Can I work on this in Python? @shraddhavp

**Comment by shraddhavp** [comment]
> @shraddhavp Please assign this to me in Java

any updates @YASH01009 ?

**Comment by YASH01009** [comment]
@shraddhavp will do it soon, in a day

**Comment by Anish528** [comment]
I can work on this issue in Java please assign.

**Comment by thevivekpande** [comment]
@shraddhavp @YASH01009 @pranjalshinde @Rishikeshrajrxl  can i work on this?
