### ISSUE TITLE
Largest Area Under Histogram - Stack

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1568]
## 🚀 Feature

Largest Area Under Histogram problem in C++. Also suggest a separate section for stack based problems.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Largest Area Under Histogram is an interesting problem of stack.

## Pitch

Will help understand the stack data structure

**Comment by gargVader** [comment]
Please assign me this

**Comment by YASH01009** [comment]
@shraddhavp Please assign this to me in Java
