### ISSUE TITLE
Vernam CIpher- Winter of Code

### ISSUE THREAD

**Issue by Sidhant-Gupta** [HarshCasper/NeoAlgo#1571]
## 💥 Proposal- Vernam Cipher

(A clear and concise description of what the proposal is.)
Add Vernam Cipher algorithm in the cryptographic section. Vernam Cipher is a symmetric key cryptographic algorithm and is one of the transposition technique that converts plain text into ciphertext.

Tasks-
Encrypt the plain text to cipher text using vernam cipher in C++.
Decrypt the cipher text obtained back to plain text using vernam in C++.

### Have you read the [Contributing Guidelines on Pull Requests]
Yes, I have read.

**Comment by rutujadhanawade** [comment]
I would like to do this in python please assign me this @shraddhavp
