### ISSUE TITLE
Add program to Swap Nodes in a Linked List in Python.

### ISSUE THREAD

**Issue by Pranav016** [HarshCasper/NeoAlgo#1572]
## 🚀 Feature

I would like to add program for Swapping Nodes in a Linked List in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This question is very often asked in the interviews. A lot of students think this is an easy question but actually it is very tricky to solve. 

I would like to work on this issue under **WoC**.

**Comment by mehabhalodiya** [comment]
Hey, can you assign me this?

**Comment by Pranav016** [comment]
> Hey, can you assign me this?

Why would I raise an issue to assign to you? :P

**Comment by mehabhalodiya** [comment]
Ok fine, sorry!

**Comment by Pranav016** [comment]
Can I work on this issue for both WoC and Devscript WoC? Also, please add the relevant tags on this :)

**Comment by Sameera-Aryasomayajula** [comment]
Can I work on the C++ version of this issue under DWOC
