### ISSUE TITLE
New Logo for Tesseract Coding

### ISSUE THREAD

**Issue by Tausif121** [HarshCasper/NeoAlgo#1575]
## 💥 Proposal

I have designed a simple black and white logo.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by shraddhavp** [comment]
@Tausif121 can you send the pictures here ?for viewing

**Comment by Tausif121** [comment]
![TC_logo_by_tausif](https://user-images.githubusercontent.com/64072708/102374498-6cc86600-3fe7-11eb-8694-47ff8a71af25.png)

**Comment by Tausif121** [comment]
This is it.
If you look closely the logo comprises of alphabets TC ,the initials of Tesseract Coding.

**Comment by Tausif121** [comment]
> @Tausif121 can you send the pictures here ?for viewing

@shraddhavp , Is the logo ok, or should i design another?

**Comment by shraddhavp** [comment]
I looks good👌 ,you can design another one too for more choices @Tausif121

**Comment by Tausif121** [comment]
Logo2:
![logo2](https://user-images.githubusercontent.com/64072708/102633638-b1363c00-4176-11eb-9877-7d165ca6ffb4.png)


Logo3:

![logo3_for_TC](https://user-images.githubusercontent.com/64072708/102633902-15f19680-4177-11eb-98e6-9b63cf33eb6b.jpeg)


Logo4:


![logo4_for_TC](https://user-images.githubusercontent.com/64072708/102634271-9617fc00-4177-11eb-85b4-f31c3bec2a46.jpeg)

@shraddhavp , Please see the other 3 logos.

**Comment by shraddhavp** [comment]
Logo 1,2 4 looks good to me @Tausif121

**Comment by shraddhavp** [comment]
you can raise a PR by making a new folder for logo @Tausif121
