### ISSUE TITLE
Add program of Matrix Script in Python.

### ISSUE THREAD

**Issue by mehabhalodiya** [HarshCasper/NeoAlgo#1581]
## 🚀 Feature

Add some in CP section:
I would like to add program for complex Matrix Script in Python.
For Description: https://github.com/TesseractCoding/NeoAlgo/issues/1581#issuecomment-748591755
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This program is going to build ones logical thinking and how to solve a complex problem in a easy way using Regex and Parsing concept.

**Comment by mehabhalodiya** [comment]
I would like to work on this issue.

**Comment by mehabhalodiya** [comment]
You can add this problem in HackerRank folder of miscellaneous.
Please assign this to me. @shraddhavp @iamrajiv @HarshCasper

**Comment by mehabhalodiya** [comment]
Please assign this to me.

**Comment by balapriyac** [comment]
Hi @mehabhalodiya, could you pls add your problem statement in  more detail?
By complex matrix, do you mean matrix with complex entries and what's the motivation  behind using regex in processing such matrices and what operations do you want to perform on the matrix etc. ?

**Comment by mehabhalodiya** [comment]
The matrix script is a  N X M grid of strings. It consists of alphanumeric characters, spaces and symbols (!,@,#,$,%,&).
![image](https://user-images.githubusercontent.com/73488906/102711443-c2e72300-42df-11eb-8137-83d2f6c94a3d.png)


To decode the script, one needs to read each column and select only the alphanumeric characters and connect them. A person reads the column from top to bottom and starts reading from the leftmost column.

If there are symbols or spaces between two alphanumeric characters of the decoded script, then person replaces them with a single space ' ' for better readability.

One feels that there is no need to use 'if' conditions for decoding.

Alphanumeric characters consist of: [A-Z, a-z, and 0-9].

**Comment by balapriyac** [comment]
Thanks, could you add the link to the problem in the description of the issue as well?
And I'll assign it to you.

**Comment by mehabhalodiya** [comment]
Added the link.
