### ISSUE TITLE
Huffman coding using tree

### ISSUE THREAD

**Issue by barnamensch056** [HarshCasper/NeoAlgo#1594]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Implementation of Huffman encoding and decoding using python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
(Please outline the motivation for the proposal.)
It uses greedy algorithm and tree data structure which will help to understand the  concepts related to it.

## Pitch
(Please explain why this feature should be implemented and how it would be used.)
It is widely used in compressing the data in  GZIP, PKZIP formats and multimedia codecs like JPEG and PNG.

**Comment by barnamensch056** [comment]
want to work on this feature please assign @shraddhavp @iamrajiv @HarshCasper

**Comment by shraddhavp** [comment]
assigned @barnamensch056

**Comment by barnamensch056** [comment]
Thanks a lot

**Comment by HarshCasper** [comment]
Is it being worked on?

**Comment by barnamensch056** [comment]
No there are some conflicts
