### ISSUE TITLE
Predict score of 1st innings in an ODI - Machine Learning (WoC) 

### ISSUE THREAD

**Issue by goelesha** [HarshCasper/NeoAlgo#1596]
## 🚀 Feature

(A clear and concise description of what the feature is.)
This Machine Learning algorithm would be able to predict the score of the first innings in an ODI based on certain inputs.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
The ODI dataset is a very basic Machine Learning Dataset and is used as a starter Dataset for Machine Learning.

**Comment by HarshCasper** [comment]
Instead of having Code over Datasets, we prefer to have algorithms used for the purpose. Can you please highlight which algorithm are you going to use?

**Comment by goelesha** [comment]
I thought having code would be better as data cleaning & removing of null values is done in a different way for each dataset. 
I would be using Linear Regression, Decision tree regressor, KNN & Random Forest Regressor.

**Comment by goelesha** [comment]
I thought having code would be better as data cleaning & removing of null values is done in a different way for each dataset.
I would be using Linear Regression, Decision tree regressor & Random Forest Regressor.

**Comment by HarshCasper** [comment]
Use only one of them. Feel free to explore the ML directory and see which algorithms have been implemented. You can work on this dataset with the ones that are not yet implemented.

**Comment by goelesha** [comment]
I will do by random forest regressor

**Comment by rajiv8** [comment]
Hey , i would like to work on this issue , i  can try with different algorithms like linear ,Decision tree, Random forest and try many different regression model and try to figure out which algorithm works good.
