### ISSUE TITLE
Predict Cost of used cars - Machine Learning using Python (WoC)

### ISSUE THREAD

**Issue by goelesha** [HarshCasper/NeoAlgo#1597]
## 🚀 Feature

Predicting the costs of used cars given the data collected from various sources and distributed across various locations in India.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)
The used car dataset is a starter dataset in ML.

**Comment by HarshCasper** [comment]
Instead of having Code over Datasets, we prefer to have algorithms used for the purpose. Can you please highlight which algorithm are you going to use?

**Comment by goelesha** [comment]
I thought having code would be better as data cleaning & removing of null values is done in a different way for each dataset. 
I would be using Linear Regression, Decision tree regressor, KNN & Random Forest Regressor.

**Comment by HarshCasper** [comment]
Use only one of them. Feel free to explore the ML directory and see which algorithms have been implemented. You can work on this dataset with the ones that are not yet implemented.

**Comment by goelesha** [comment]
Okay sure.

**Comment by goelesha** [comment]
I will do by random forest regressor

**Comment by ParthSingh0506** [comment]
It is better to use Random Forest Regressor but you should apply all those models(KNN, Decision Tree, etc). Use only that model in which you get higher accuracy.

**Comment by RhuthuHegde** [comment]
Is the problem attended, or can I work on this issue?

**Comment by HarshCasper** [comment]
> I will do by random forest regressor

Can you check if Random Forest already exists or not? If not, then we may not be able to consider this Issue. 

@RhuthuHegde No, it is not. Before moving ahead with ML/DL Algorithms, we need to have a good clarity of the Issue we are trying to solve.

**Comment by goelesha** [comment]
Random Forest does not exist. So may I proceed with it?

**Comment by goelesha** [comment]
Random Forest does not exist. I can do it by other models also.

**Comment by HarshCasper** [comment]
Reopening this. I mistyped the statement. If Random Forest doesn't exist, please add the algorithm. Let me know if you are working on this, so that I can assign it to you.

**Comment by goelesha** [comment]
Sure. I would like to do it.
