### ISSUE TITLE
Add Bubble Sort Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#16]
**Algorithm:** 

[Bubble Sort](https://en.wikipedia.org/wiki/Bubble_sort)

**DS:** 

Sorting

**Languages Missing:**

- C#

**Comment by swarajpure** [comment]
Will do in C++ and Python

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @swarajpure 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by UtkarshChaurasia** [comment]
Can I work on this for JAVA?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @UtkarshChaurasia 

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by sparkingdark** [comment]
C and JavaScript I want to work.

**Comment by haikelfazzani** [comment]
Can I work on this for **Javascript** ?

**Comment by HarshCasper** [comment]
I have assigned you all the Issue. You can start working on it.

@sparkingdark You can work in C while @haikelfazzani can work in Javascript.

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by sparkingdark** [comment]
Okay I do it.

**Comment by haikelfazzani** [comment]
thanks @HarshCasper

**Comment by UtkarshChaurasia** [comment]
@HarshCasper bubble sort in java is already added.

**Comment by mar-galho** [comment]
We need the implementation for C# - also, if you guys want to work in any other language, just go ahead and create the folder, update the main README.md to include the language and submit it :)

**Comment by ghost** [comment]
I want to work on this in Golang
