### ISSUE TITLE
Add Double Ended Queue to DS

### ISSUE THREAD

**Issue by mehabhalodiya** [HarshCasper/NeoAlgo#1602]
## 🚀 Feature

Need to add in DS:
**Double Ended Queue** : Deque is a linear data structure in which the insertion and deletion operations are performed from both ends. We can say that deque is a generalized version of the queue.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This question is very often asked in the interviews. A lot of students think this is an easy question but actually it is complex to solve as the deque can be implemented using two data structures, i.e., circular array, and doubly linked list.

## Pitch

Deque can be used both as stack and queue as it allows the insertion and deletion operations on both ends.

**Comment by mehabhalodiya** [comment]
I would like to work on this issue.
Please assign this to me in Python.

**Comment by satyampgt4** [comment]
@shraddhavp Please assign this to me for c++.
