### ISSUE TITLE
Kaden's Algorithm

### ISSUE THREAD

**Issue by jyoti-2** [HarshCasper/NeoAlgo#1604]
### Largest possible sum of a contiguous subarray, within a given one-dimensional array using Kaden's Algorithm.

`# max Sum of contiguous subarray
def maxSubArraySum(arr, n):
    current_max = 0
    best_sum = 0

    for i in range(n):
        current_max = max(arr[i], current_max + arr[i])
        best_sum = max(best_sum, current_max)
    return best_sum

arr = [-2, -3, -4, -6, -9]
print(maxSubArraySum(arr, len(arr)))`

**Comment by Siddhant-K-code** [comment]
i can implement this in C++ under `C-Plus-Plus/dp/`

**Comment by shraddhavp** [comment]
assigned @jyoti-2  and @Siddhant-K-code

**Comment by nayanajain** [comment]
Please assign this issue to me in c++

**Comment by Sarthak-9** [comment]
I want to work on this in cpp. Please assign it to me.
@shraddhavp
@dwoc

**Comment by shraddhavp** [comment]
sorry @Sarthak-9  and @nayanajain  it is already assigned

**Comment by Siddhant-K-code** [comment]
@shraddhavp pls review #1749
