### ISSUE TITLE
Re-structure the README.md of Python folder

### ISSUE THREAD

**Issue by charlie219** [HarshCasper/NeoAlgo#1610]
## 🐛 Bug Report

While contributing to the Python folder I encountered a lack of consistency in the `README.md` file. 
- The file contains many heading and algorithm twice/ thrice which makes it long and confusing
- Since there are many similar heading, many Programmers get confused.

I would like to take the task to re-structure the `README.md` to ensure good and fruitful contributions.
@iamrajiv @HarshCasper @atarax665 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by shraddhavp** [comment]
Go ahead

**Comment by shraddhavp** [comment]
assigned @charlie219
