### ISSUE TITLE
Euclidean algorithms

### ISSUE THREAD

**Issue by 1711shashank** [HarshCasper/NeoAlgo#1612]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by 1711shashank** [comment]
please assign this to me

**Comment by shraddhavp** [comment]
please specify the language @1711shashank

**Comment by 1711shashank** [comment]
in C++

**Comment by 1711shashank** [comment]
I am not getting the option to create the PR for this issue or [commit](https://github.com/TesseractCoding/NeoAlgo/pull/1646/commits/ff01d5a9334feccaf29794262324bb07988398a6)
Can any one help me resolve this??

**Comment by shivangi00** [comment]
@shraddhavp I am willing to contribute. 
Language - Java, C
Purpose - contributing via WoC

**Comment by pranjalshinde** [comment]
I would like to solve this in Java, please assign

**Comment by nayanajain** [comment]
I can solve this issue..please assign me
