### ISSUE TITLE
Sort a nearly sorted

### ISSUE THREAD

**Issue by 1711shashank** [HarshCasper/NeoAlgo#1613]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Given an array of n elements, 
where each element is at most k away from its target position. 
The task is to print array in sorted form. 

n denoting number of elements in array,
k denoting the element is at most k positions away from its target position.

**Comment by 1711shashank** [comment]
please assign this to me

**Comment by shraddhavp** [comment]
can you provide more details on the problem ?

**Comment by 1711shashank** [comment]
Given an array of n elements, 
where each element is at most k away from its target position. 
The task is to print array in sorted form. 

n denoting number of elements in array,
k denoting the element is at most k positions away from its target position.

**Comment by 1711shashank** [comment]
@shraddhavp 👍

**Comment by 1711shashank** [comment]
@shraddhavp can i work on this ??

**Comment by shraddhavp** [comment]
yes you can @1711shashank
