### ISSUE TITLE
Rain Water Trapping in Golang

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1614]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Rain Water Trapping is one of the standard problem in DSA and asked in many interviews . It's not present in the Go repository

**Comment by shraddhavp** [comment]
assigned @sujal111
