### ISSUE TITLE
Rotate Element

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1615]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Rotation of elements in an array is a standard DSA question. It's not present in Python here. I want to add it

**Comment by aeyshubh** [comment]
I can take this issue but i need a more precise description @sujal111
