### ISSUE TITLE
Detect and Delete a Loop LinkedList in Python

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1616]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
In this problem,we have to check if Loop is present , if it is present ,we got to delete it

**Comment by KartikeySharma** [comment]
I would like to work on this issue @sujal111 .
Pls assign this to me
