### ISSUE TITLE
Detect Middle Element of a Linked List in C++

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1617]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Rishikeshrajrxl** [comment]
I would like to do this, please assign me

**Comment by sakshi300699** [comment]
I would like to work on this issue

**Comment by Sarthak-9** [comment]
I want to work on this .Please assign it to me.

**Comment by Rishikeshrajrxl** [comment]
@shraddhavp  I am doing this in C++

**Comment by shraddhavp** [comment]
@Sarthak-9 any updates?

**Comment by Sarthak-9** [comment]
My previous PR is merged now. I'll complete this one today.
@shraddhavp
