### ISSUE TITLE
Linear Search in Go Language

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1618]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
In this problem, we will search if an element is present in an array or not

**Comment by shraddhavp** [comment]
go ahead @sujal111
