### ISSUE TITLE
Merge Sort

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1619]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Merge Sort in Python

**Comment by charlie219** [comment]
@sujal111 there is already 2 different types of merge sort present in the repo. I don't this we need to add another similar approach.

**Comment by shraddhavp** [comment]
can you implement it in GO?

**Comment by joeyouss** [comment]
Hi! I would like to work on this issue. Kindly assign it to me.

**Comment by HarshCasper** [comment]
Hello @joeyouss and @sujal111 

I have assigned it to you. You can go ahead with them! Make sure to inform beforehand the language you are going to implement this in and check if the algorithm already exists in the language you are trying to implement.

**Comment by joeyouss** [comment]
Amazing ! Would do it. Thanks !

**Comment by aeyshubh** [comment]
I can do it in Java ,kindly assign it to me

**Comment by swordcom367** [comment]
If it has not already been assigned in go could I do it?

**Comment by Tanmay2510** [comment]
Hey @HarshCasper  I would like to implement this in Java and be a part of DWOC. Can you please assign me this issue?
