### ISSUE TITLE
Reverse a Linked List in Golang

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1620]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by shraddhavp** [comment]
assigned @sujal111

**Comment by pranjalshinde** [comment]
I want to solve this in Java please assign, also add DWOC label to it.

**Comment by shraddhavp** [comment]
assigned @pranjalshinde

**Comment by nick-leslie** [comment]
Could I work on this in go please?

**Comment by shraddhavp** [comment]
go ahead @swordcom367
