### ISSUE TITLE
Factorial of a large Number in Python

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1621]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Finding  factorial of a Large Number

**Comment by KartikeySharma** [comment]
I would like to work on this.
Pls assign this to me if possible @sujal111 . :)

**Comment by manvi0308** [comment]
I would like to work on this

**Comment by RhuthuHegde** [comment]
Can I work on this issue in python?

**Comment by shraddhavp** [comment]
assigned @manvi0308
