### ISSUE TITLE
Longest Subsequence in an Array in C++

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1622]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by 1711shashank** [comment]
Please assign this to me

**Comment by balapriyac** [comment]
@1711shashank, you may start working on the issue.

**Comment by 1711shashank** [comment]
@sujal111 can you provide more details on the problem ?

**Comment by nayanajain** [comment]
please assign this issue to me

**Comment by khusboobothra** [comment]
Please assign this issue to me.

**Comment by shraddhavp** [comment]
assigned @khusboobothra

**Comment by achalesh27022003** [comment]
@shraddhavp mam, I can do this in C++. Please assign it to me.
