### ISSUE TITLE
Circular Linked List Implementation 

### ISSUE THREAD

**Issue by goelesha** [HarshCasper/NeoAlgo#1625]
## 💥 Proposal
Implementation of circular linked list & its functionalities in C

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by goelesha** [comment]
Please assign this issue to me.

**Comment by shivangi00** [comment]
@shraddhavp  I would like to do this in C++

**Comment by mohd-hirani** [comment]
I am interested in this issue;
I can do this in C/C++.

**Comment by razorblade42** [comment]
interested!
i can do this in C/C++/python2/python3

**Comment by shraddhavp** [comment]
@shivangi00  please do in cpp

**Comment by shraddhavp** [comment]
@razorblade42  please go ahead with python

**Comment by bhavya092** [comment]
I would like to help in C++ . Can you assign this to me?

**Comment by srimanikantapalakollu** [comment]
@goelesha please provide your email id for the evaluation.

**Comment by goelesha** [comment]
My email id is goelesha2001@gmail.com

**Comment by thevivekpande** [comment]
@srimani-programmer @shraddhavp @goelesha is this still open?
