### ISSUE TITLE
Median in a running stream of integers - Heaps

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1631]
## 🚀 Feature

Program in C++ to find median in a running stream of integers. Also suggest to make a separate section for heap based problems.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Interesting application of heap data structure

## Pitch

Keeps updating the current median, while new numbers are being given as input
To be implemented in C++.

**Comment by gargVader** [comment]
Please assign this to me

**Comment by balapriyac** [comment]
You've been assigned another issue, you'll be assigned this issue once you've solved the previously assigned one.

**Comment by shraddhavp** [comment]
assigned @gargVader
