### ISSUE TITLE
Merge K sorted arrays - Heaps

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1632]
## 🚀 Feature

Program in C++ to merge K sorted arrays using the approach of heaps. Also suggest a separate section for heap based problems.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Understand heap data structure

## Pitch

Uncommon approach to solve a common problem.

**Comment by gargVader** [comment]
Please assign this to me

**Comment by balapriyac** [comment]
Sure, I've you the issue; you may start working on it.

**Comment by gargVader** [comment]
@balapriyac Should I add a separate section for heap based problems?
