### ISSUE TITLE
Intersection of Linked List

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1636]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Intersection of Linked List in C language

**Comment by joeyouss** [comment]
Hi I would like to work on this. Kindly assign it to me

**Comment by shraddhavp** [comment]
Please provide more explanation @sujal111  on the problem

**Comment by yashaswibiyahut** [comment]
@sujal111 go for it.

**Comment by yashaswibiyahut** [comment]
@joeyouss kindly mention in which language you want to implement.

**Comment by joeyouss** [comment]
> @joeyouss kindly mention in which language you want to implement.

I would like to do it in cpp

**Comment by shraddhavp** [comment]
Assigned @joeyouss

**Comment by kapilkumar2001** [comment]
I would like to do this in java

**Comment by shraddhavp** [comment]
assigned @kapilkumar2001
