### ISSUE TITLE
Spiral Matrix in Golang

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1637]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Implementing Spiral Matrix in Golang

**Comment by sujal111** [comment]
#792 Spiral Matrix in Golang Done

**Comment by pranjalshinde** [comment]
Can I solve this in Java?

**Comment by pranjalshinde** [comment]
Please assign this to me in java and add DWOC label

**Comment by shraddhavp** [comment]
assigned @pranjalshinde

**Comment by nick-leslie** [comment]
could I work on this in go?
