### ISSUE TITLE
Kruskal's algorithm

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1638]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Kruskal's algorithm is one of the most important algorithm in Interview. Implementation in Golang

**Comment by Bharati2612** [comment]
I would like to do this algorithm using C++, please assign.

**Comment by yashaswibiyahut** [comment]
@Bharati2612 go for it

**Comment by mohd-hirani** [comment]
I am interested in this issue;
I can add kruskal's algorithm.

**Comment by Bharati2612** [comment]
> @Bharati2612 go for it

I am working on it.
