### ISSUE TITLE
Counting Sort Implementation

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#164]
**Algorithm: [Counting Sort](https://en.wikipedia.org/wiki/Counting_sort)** 
In computer science, counting sort is an algorithm for sorting a collection of objects according to keys that are small integers; that is, it is an integer sorting algorithm. 

**Languages Supported:**

- C [@m-code12]
- C++ [@harsh-9in ]
- C#
- Java [@shobhu98]
- Python [@srinivasdasu24 ]
- Javascript
- Go

**Comment by harsh7in** [comment]
Plz assign this algorithm issue for c++

**Comment by harsh7in** [comment]
@sparkingdark ??

**Comment by sparkingdark** [comment]
@ricardoprins please assign the issue to @harsh-9in .

**Comment by mar-galho** [comment]
@harsh-9in you're game!

**Comment by srinivasdasu24** [comment]
Hi @ricardoprins  I can solve this problem in python and CPP. Can you please assign me the issue

**Comment by vgb-codes** [comment]
@srinivasdasu24 CPP has been assigned already. I will assign you to python.

**Comment by m-code12** [comment]
I can implement this in C. Please assign it to me.

**Comment by shobhu98** [comment]
Can I  implement in Java?

**Comment by mar-galho** [comment]
Yes to @m-code12 and @shobhu98. 

Just make sure it hasn't been implemented yet!

**Comment by Kathan-Vakharia** [comment]
Can you assign me for js and C versions?

**Comment by Anjali2001saxena** [comment]
I want to contribute in java.

**Comment by vgb-codes** [comment]
@Anjali2001saxena Please check if the issue has been already assigned in Java. Since it has already been assigned, I cannot assign you this issue in Java.

**Comment by vgb-codes** [comment]
@m-code12 @shobhu98 Have you completed your issues?
