### ISSUE TITLE
Letter Case Permutation using recursion

### ISSUE THREAD

**Issue by 1711shashank** [HarshCasper/NeoAlgo#1645]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

Given a string S, we can transform every letter individually to be lowercase or uppercase to create another string.
Print all possible strings we could create. return the output in any order.

**Comment by shraddhavp** [comment]
@1711shashank  please wait for any of the mentors to assign the issue,I get the excitement which is good but please have patience

**Comment by 1711shashank** [comment]
@shraddhavp 
ok I will keep this in mind
