### ISSUE TITLE
Q-Sharp Algorithms

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#1649]
## 🚀 Feature

I would like to add the basic maths algorithms for the area in Q#

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Q-Sharp didn't have any contributions and I would like to add mine.

## Pitch

Addition of basic areas algorithms in Q-Sharp

**Comment by Rishikeshrajrxl** [comment]
I can do this in c++ .

**Comment by shraddhavp** [comment]
assigned @Rishikeshrajrxl
