### ISSUE TITLE
Factorial Using Big Integer

### ISSUE THREAD

**Issue by JayantGoel001** [HarshCasper/NeoAlgo#1651]
## 🚀 Factorial Of A Number

Factorial of a given number using Big Integer

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(Application of Big integers)

## Pitch

Calculation of factorial of big number requires lot of bits that can only be provided by Big Integer.

I want to implement this in **Java**

**Comment by ErzaTitania-2001** [comment]
Can i be assigned this ? @shraddhavp

**Comment by shraddhavp** [comment]
@ErzaTitania-2001  in which language do you want to implement it?

**Comment by ErzaTitania-2001** [comment]
Java. Thanks.
