### ISSUE TITLE
New section for Stack based problems in C++

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1661]
## 🚀 Feature

Add a new section for stack based problems in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Easier for user to search for algorithms. It will also resolve various merge conflicts

## Pitch

@shraddhavp Should I add a separate section for stack based problems?

_Originally posted by @gargVader in https://github.com/TesseractCoding/NeoAlgo/issues/1600#issuecomment-748891844_

yes you can @gargVader

_Originally posted by @shraddhavp in https://github.com/TesseractCoding/NeoAlgo/issues/1600#issuecomment-749057013_

**Comment by gargVader** [comment]
Should I go ahead?

**Comment by gargVader** [comment]
confirmed on slack

**Comment by AayushBangroo** [comment]
Please assign me this one!

**Comment by gargVader** [comment]
@AayushBangroo Stack section was already created and problems added
