### ISSUE TITLE
Add Benjamin Bulb Problem Java/ C++/ C

### ISSUE THREAD

**Issue by shivangi00** [HarshCasper/NeoAlgo#1668]
Benjamin Bulb Problem (also known as Bulb Switcher Problem) is good start for Beginners in any programming language to get into the problem solving thinking process. 

Link to the problem on LeetCode - 
https://leetcode.com/problems/bulb-switcher/

Can solve this problem in all the above languages, do assign me.

@dwoc mentors and @shraddhavp Please consider this.

**Comment by Rishikeshrajrxl** [comment]
I can do this in c++ , do assign me for Tag DWOC

**Comment by shraddhavp** [comment]
@Rishikeshrajrxl  go ahead with cpp

**Comment by shraddhavp** [comment]
@shivangi00  go ahead with java

**Comment by rutujadhanawade** [comment]
I would like to do this in C and python

**Comment by shraddhavp** [comment]
assigned @rutujadhanawade

**Comment by rutujadhanawade** [comment]
@shivangi00 Can you please send the link to the problem statement?

**Comment by shivangi00** [comment]
> @shivangi00 Can you please send the link to the problem statement?

@rutujadhanawade I have added the link in the comment at the top. :)

**Comment by Anish528** [comment]
I can work on this issue in Java please assign under dwoc
