### ISSUE TITLE
Dutch National Flag Problem

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1673]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Dutch National Flag Problem- Sort 0s,1s and 2s

## Assignees 

- Python: @anayjoshi1608
- Java: @pranjalshinde
- C: @muthuannamalai12

**Comment by anay-joshi** [comment]
I know this algo. I can write an explanation and code in python and cpp. Can you assign this to me.

**Comment by Rishikeshrajrxl** [comment]
Assign me this for c++

**Comment by pranjalshinde** [comment]
I would like to solve this in Java, please assign

**Comment by AayushBangroo** [comment]
Interested

**Comment by muthuannamalai12** [comment]
I would like to solve this in C.Kindly assign this to me

**Comment by HarshCasper** [comment]
This Issue is already solved here in C++ https://github.com/TesseractCoding/NeoAlgo/pull/1518/files 

I am assigning this Issue in Python, Java and C to the people who requested.

**Comment by atriadhiakri2000** [comment]
1. Implement Stack / Implement Queue
3. Implement Stack using Queue
4. Implement Queue using Stack
5. Check for balanced parentheses
6. Next Greater Element
@shraddhavp @HarshCasper @iamrajiv    Please assign me these

**Comment by HarshCasper** [comment]
> 1. Implement Stack / Implement Queue
> 2. Implement Stack using Queue
> 3. Implement Queue using Stack
> 4. Check for balanced parentheses
> 5. Next Greater Element
>    @shraddhavp @HarshCasper @iamrajiv    Please assign me these

Already assigned.
