### ISSUE TITLE
Print Left View of a Binary Tree in Python

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1674]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by KartikeySharma** [comment]
Pls assign this to me @sujal111

**Comment by pranjalshinde** [comment]
I want to solve this in Java, Please assign. Also add DWOC label to it
