### ISSUE TITLE
Subarray Of An Array With Given Sum

### ISSUE THREAD

**Issue by ErzaTitania-2001** [HarshCasper/NeoAlgo#1675]
## 🚀 Feature
Find Subarray of an array with given sum in O(n) time.

Input : 
arr[]={1,4,20,3,10,5} ; sum=33
Output : 
Sum found between indexes 2 and 4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

To get more used to competitive programming and time complexities.

**Comment by ErzaTitania-2001** [comment]
@shraddhavp assign me this in Java.

**Comment by shraddhavp** [comment]
@ErzaTitania-2001  please wait for the issue t o be assigned to you,I get the excitement but please have patience

**Comment by ErzaTitania-2001** [comment]
My bad. I have submitted a PR already on the issue. Would you check it out
kindly?
