### ISSUE TITLE
Kadane's Algorithm in python

### ISSUE THREAD

**Issue by joeyouss** [HarshCasper/NeoAlgo#1680]
## 💥 Proposal

I would like to implement kadane's Algorithm in python with proper explanation

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by anay-joshi** [comment]
Can you please assign this to me. I can write an explanation with proper code.

**Comment by shraddhavp** [comment]
it is already present @joeyouss  it is same as issue #1604
