### ISSUE TITLE
Menu driven C Program

### ISSUE THREAD

**Issue by musavveer** [HarshCasper/NeoAlgo#1682]
I have a menu-driven C program to create, insert, display, delete array.
I think this would help for newbies.

**Comment by Rishikeshrajrxl** [comment]
I can do this in   C,  C++, Java , and python.

**Comment by nayanajain** [comment]
please assign this  to me..

**Comment by rajiv8** [comment]
Please assign this task to me, I can do this menu driven program in Python, C, C++, Java
