### ISSUE TITLE
Shortest Distance Between Words

### ISSUE THREAD

**Issue by ErzaTitania-2001** [HarshCasper/NeoAlgo#1685]
## 🚀 Feature

Given a list of words and two words word1 and word2, find the shortest distance between those two words from the list.

Input : words=["practice", "makes", "perfect", "coding","makes"]
word1="coding"
word2="practice"
Output: 3
word1="coding"
word2="makes"
Output : 1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Motivation

Beneficial for Competitive Programming 

## Pitch

Interview question

**Comment by ErzaTitania-2001** [comment]
@shraddhavp can I be assigned this?

**Comment by shraddhavp** [comment]
assigned @ErzaTitania-2001

**Comment by Rishikeshrajrxl** [comment]
I cann do this in c++ and Java, do assign me

**Comment by kapilkumar2001** [comment]
I would like to do this in python under DWOC

**Comment by shraddhavp** [comment]
@Rishikeshrajrxl  go ahead with cpp

**Comment by shraddhavp** [comment]
@kapilkumar2001  go ahead with python
