### ISSUE TITLE
Add Priority Queue in JAVA

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#1689]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

In the data structures, I want to add Priority Queue implemented in Java.

## Motivation

The data structures and algorithms under one roof...hmm...why not add all possible data structures and algorithms?

## Pitch

I will be importing the PriorityQueue Class. The PriorityQueue class provides the functionality of the heap data structure.
It implements the Queue interface.
It will help understand the Queue data structure in a much better way.

**Comment by iamvs-2002** [comment]
Kindly assign this issue to me. I have made a pull request for the same. Kindly review the same.😊

**Comment by iamvs-2002** [comment]
This issue is for DWOC - DevScript Winter of Code.
Thankyou!

**Comment by ankitasantape** [comment]
Please assign this issue to me I would like to implement PriorityQueue using Heap sort with time complexity O(log n) and space complexity O(1)
