### ISSUE TITLE
AI Algorithms

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#1693]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Addition of AI Algorithms such as Breadth First Search, Depth First Search, Best First Search, A*, AO*, etc.
Well, not the implementation rather the algo(pseudo code) with an explanation.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
Many people find it hard to study AI algorithms and having those algorithms here along with other algorithms, would certainly be great.
(Please outline the motivation for the proposal.)

## Pitch
Adding AI algorithms as mentioned above would help people understand them well and will reduce the work of searching one place where all the "algorithms" can be found.
(Please explain why this feature should be implemented and how it would be used.)
I would add the explanation of each algorithm along with the algorithm/pseudo code.

**Comment by iamvs-2002** [comment]
@ShishirBhandari Kindly assign this issue to me.

**Comment by ShishirBhandari** [comment]
@iamvs-2002,
Sorry but I am not the author/maintainer of this repository. So I cannot assign.
You can ask maintainers and authors for this.

I think you can start working on this and get someone to assign it to you later.

Good luck.

**Comment by shraddhavp** [comment]
assigned @iamvs-2002

**Comment by iamvs-2002** [comment]
Thankyou!

**Comment by iamvs-2002** [comment]
@shraddhavp  Please guide me a bit...
Should I make a separate pull request for every AI algorithm(around 10 algorithms) I add, or a common pull request for all the files will work well?

**Comment by iamvs-2002** [comment]
This issue is for DWOC - DevScript Winter of Code.

**Comment by iamvs-2002** [comment]
This is for DWOC - DevScript Winter of Code.
Thank you!

**Comment by shraddhavp** [comment]
> @shraddhavp Please guide me a bit...
> Should I make a separate pull request for every AI algorithm(around 10 algorithms) I add, or a common pull request for all the files will work well?

yes seperate for each

**Comment by iamvs-2002** [comment]
Okay, thankyou! I am on it.

**Comment by shraddhavp** [comment]
@iamvs-2002  updates?/

**Comment by iamvs-2002** [comment]
> @iamvs-2002 updates?/

Hey! I did make a few contributions regarding this issue, but the mentor said, it won't be good to make documentation for the algorithms. So I guess, it may be closed for now.

**Comment by shraddhavp** [comment]
ok
