### ISSUE TITLE
Euler’s Totient Function in Python

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1694]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Euler’s Totient Function in Python is an important part of Number Theory and highly used in CP

**Comment by KartikeySharma** [comment]
I would like to work on this issue if possible.
