### ISSUE TITLE
Carmichael Numbers in Python and C++

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1697]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Rishikeshrajrxl** [comment]
Assign me this in c++

**Comment by shraddhavp** [comment]
assigned @Rishikeshrajrxl
