### ISSUE TITLE
Wilson’s Theorem in C++

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1698]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Rishikeshrajrxl** [comment]
Please assign me this issue

**Comment by KartikeySharma** [comment]
Pls assign this issue to me if possible

**Comment by shraddhavp** [comment]
assigned @Rishikeshrajrxl

**Comment by achalesh27022003** [comment]
Please assign me this issue @shraddhavp mam.
