### ISSUE TITLE
Lucas Theorem in Python

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1699]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Rishikeshrajrxl** [comment]
Assign me this, please

**Comment by shraddhavp** [comment]
as a part of woc or dwoc?

**Comment by Rishikeshrajrxl** [comment]
> as a part of woc or dwoc?

As a of DWOC

**Comment by Rishikeshrajrxl** [comment]
@shraddhavp  please add a level to this issue
