### ISSUE TITLE
Add Quick Sort Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#17]
**Algorithm:** 

[Quick Sort](https://en.wikipedia.org/wiki/Quicksort)

**DS:** 

Sorting

**Languages Missing:**

- C [ Assigned to @Dhairya3124 ]
- C++ [ Assigned to @asaxena012 ]
- Javascript

**Comment by SRILEKHA-V19** [comment]
@HarshCasper , could you please assign this issue to me? I'm willing to take up this task for languages: C, C++, Java, Python. After i'm done with these, i can work on Javascript too.

**Comment by Dhairya3124** [comment]
@HarshCasper Could you assign this issue to me? I want to work in C++.

**Comment by asaxena012** [comment]
@HarshCasper  Could you assign me this issue? I am willing to work on this issue in C++.

**Comment by HarshCasper** [comment]
I have assigned the Issue for Java and Python to @SRILEKHA-V19

You can start working on it. Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by HarshCasper** [comment]
@Dhairya3124 and @asaxena012 There is a conflict here. Probably I can assign you the Issue in C and C++ respectively or if you want to work in some other language, you can do that part as well and I will promptly assign it to you.

**Comment by Dhairya3124** [comment]
@HarshCasper I'll be fine to work upon C language.

**Comment by HarshCasper** [comment]
You can start working on it now @Dhairya3124

**Comment by mar-galho** [comment]
@asaxena012 , you can submit the C++ implementation to it.
