### ISSUE TITLE
Sprague – Grundy Theorem

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1701]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by KartikeySharma** [comment]
Pls assign this to me if possible

**Comment by shraddhavp** [comment]
assigned @KartikeySharma

**Comment by KartikeySharma** [comment]
Pls add the DWOC tag
