### ISSUE TITLE
Robin Karp Algorithm 

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1702]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Rishikeshrajrxl** [comment]
Assign me this issue

**Comment by KartikeySharma** [comment]
Pls assign this to me for DWOC
I have fixed the issue #1701  and I have submitted a PR as well

**Comment by Rishikeshrajrxl** [comment]
assign me for DWOC

**Comment by shraddhavp** [comment]
assigned @KartikeySharma in Java   and @Rishikeshrajrxl  in  C-pp
