### ISSUE TITLE
Stack  Using Queue in CPP

### ISSUE THREAD

**Issue by nehalabhasetwar** [HarshCasper/NeoAlgo#1715]
## 🚀 Feature

Program in CPP to implement stack using queues.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by AayushBangroo** [comment]
Interested

**Comment by Amit366** [comment]
I am also interested

**Comment by Amit366** [comment]
I will grateful to you, if you can assign this to me for DWOC.

**Comment by geekaditi** [comment]
I’d like to take this up in CPP.

**Comment by pranjalshinde** [comment]
I would like to work on this in Java under DWOC, please assign
