### ISSUE TITLE
3 Partition Quick Sort in C++

### ISSUE THREAD

**Issue by KartikeySharma** [HarshCasper/NeoAlgo#1716]
## 🚀 Feature
Quick sort is a very famous algorithm which uses recursion and balances the array based on a chosen element known as the pivot. This creates 2 partitions in a general quick sort. A much faster implementation is the 3 way quicksort which uses 2 pivots for faster sorting

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

-This is a very famous algorithm and this implementation is quite fast as compared to the conventional 2 way quick sort.
-This algorithm does not exist in the sort folder for Cpp

## Pitch

This algorithm is amongst the fastest sorting algorithms that have been devised and I believe that this algorithm should be implemented and documented in this repository

**Comment by shraddhavp** [comment]
please mention WOC or DWOC

**Comment by KartikeySharma** [comment]
Pls add the DWOC tag

**Comment by kotwani2883** [comment]
Kindly assign this problem to me.
