### ISSUE TITLE
Mo's Algorithm C++

### ISSUE THREAD

**Issue by KartikeySharma** [HarshCasper/NeoAlgo#1718]
## 💥 Proposal

It is a general idea that is implemented to improve the speed of query-based algorithms. It is mostly used in CP

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Jassi10000-zz** [comment]
I would like to contribute for this issue.
Assign me this issue with tag DWOC

**Comment by shraddhavp** [comment]
updates @Jassi10000 ?

**Comment by Jassi10000** [comment]
I have already sent a PR for this , plss check once

**Comment by shraddhavp** [comment]
updates @Jassi10000 ?/

**Comment by Jassi10000-zz** [comment]
@shraddhavp mam I have submitted the PR , pls check it will be of 17th January
