### ISSUE TITLE
Evaluate a string expression using BODMAS (Stack)

### ISSUE THREAD

**Issue by AayushBangroo** [HarshCasper/NeoAlgo#1719]
## 💥 Proposal
Evaluate a string expression like "(2+3)*4/5" using stack applying BODMAS rules using C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes

**Comment by AayushBangroo** [comment]
Please assign

**Comment by Apoorve73** [comment]
Okay! @AayushBangroo ! Go ahead! :+1:

**Comment by dsnehasish74** [comment]
Can you assign this to me

**Comment by AnkitaM84** [comment]
Can you assign to me in Java? @HarshCasper

**Comment by Anish528** [comment]
Can you please assign this issue to me in Java

**Comment by HarshCasper** [comment]
> Can you assign this to me

Please state clearly the language you want to work with.

**Comment by achalesh27022003** [comment]
@AayushBangroo  I can do this in C++ sir. Pls assign it to me.

**Comment by yogitasaini** [comment]
please assign it to me in java
