### ISSUE TITLE
Cocktail shaker sort | C++

### ISSUE THREAD

**Issue by sahebsunny** [HarshCasper/NeoAlgo#1722]
## 🚀 Feature

Implementation of the Cocktail shaker sort algorithm in CPP.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It's an interesting and important algorithm to learn.

## Pitch

Cocktail shaker sort, also known as bidirectional bubble sort, cocktail sort, shaker sort, ripple sort, shuffle sort, or shuttle sort, is an extension of bubble sort.

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
Thank you.

**Comment by japneetkaurbhatia** [comment]
Hey 
Can I work on this in java ?

**Comment by riyasingh1004** [comment]
I would like to work on this, please assign this to me. I am fluent in C++.
