### ISSUE TITLE
Fibonacci Search | C

### ISSUE THREAD

**Issue by sahebsunny** [HarshCasper/NeoAlgo#1723]
## 🚀 Feature

Adding Fibonacci Search implementation using C language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It's an interesting algorithm to learn.

## Pitch

Fibonacci search technique is a method of searching a sorted array using a divide and conquer algorithm that narrows down possible locations with the aid of Fibonacci numbers.

**Comment by Amit366** [comment]
I am interested

**Comment by sahebsunny** [comment]
Sir, I have made this issue and I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
Thank you.

**Comment by smriti1313** [comment]
Hi, I would like to have this opportunity to contribute in this.

**Comment by muthuannamalai12** [comment]
I am interrested.Kindly assign me this issue

**Comment by chehak123** [comment]
I would like to work on this issue under DWOC

**Comment by sahebsunny** [comment]
@shraddhavp sir let me work on it

**Comment by sahebsunny** [comment]
@HarshCasper thanks sir

**Comment by sahebsunny** [comment]
@HarshCasper sir I need a suggestion 
I have made a Pull request for issue #1763
but sir when I pushed the changes for this #1723 issue my changes went in the first pull request
i have deleted the files 
But sir how should i make PR for this issue.

**Comment by pranjalshinde** [comment]
I would like to work on this in java under DWOC please assign

**Comment by Anish528** [comment]
I want to work on this issue in Java please assign under dwoc @HarshCasper sir

**Comment by HarshCasper** [comment]
> I would like to work on this in java under DWOC please assign

Assigned. Go ahead 🚀

**Comment by muthuannamalai12** [comment]
I would love to work on this issue in python. Kindly assign me this issue @HarshCasper

**Comment by ShubhamGupta577** [comment]
I would like to work on this issue using C and C++. Please assign me.

**Comment by WertiaCoffee** [comment]
no Sent from Mail for Windows 10 From: Shubham GuptaSent: Monday, February 15, 2021 1:39 PMTo: TesseractCoding/NeoAlgoCc: SubscribedSubject: Re: [TesseractCoding/NeoAlgo] Fibonacci Search | C (#1723) I would like to work on this issue using C and C++. Please assign me.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yogitasaini** [comment]
I would like to work on it in java .Please assign it to me
