### ISSUE TITLE
Jump Search | Python

### ISSUE THREAD

**Issue by sahebsunny** [HarshCasper/NeoAlgo#1724]
## 🚀 Feature

Implementation of the Jump Search in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It's an interesting algorithm to learn.

## Pitch

Jump search or block search refers to a search algorithm for ordered lists.

**Comment by sahebsunny** [comment]
Sir, I love to work on it.
I would be grateful if you can assign this issue to me for DWOC.
Thank you.

**Comment by antaramunshi** [comment]
Can you assign this to me?

**Comment by sahebsunny** [comment]
@HarshCasper sir please let me work on it

**Comment by himanshu007-creator** [comment]
https://github.com/TesseractCoding/NeoAlgo/pull/2151 Please have a look here
