### ISSUE TITLE
Adding Graph Traversal Algorithms 

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#1725]
## 🚀 Feature
I would love to work on Breadth-First Search (BFS) and Depth-First Search (DFS) Graph traversal algorithms in C as a part of DWOC

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

## Motivation
Graphs are a powerful and versatile data structure that easily allows you to represent real-life relationships between different types of data (nodes). Graphs are one of the most difficult topics of data structure and can be asked in interviews. I will be working on-

1.DFS
2.BFS 

 

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Graph traversal is a technique used for searching a vertex in a graph. It is also used to decide the order of vertices is visited in the search process. It is also used to find the edges to be used in the search process without creating loops. In these ways they can be used

**Comment by smriti1313** [comment]
Hi, I would like to work on this . Also let me know if this in included in DWOC2020. Thank you

**Comment by chehak123** [comment]
I would like to work on this issue under DWOC

**Comment by kapilkumar2001** [comment]
I would like to work on this issue in java under DWOC

**Comment by shivanshugarg12800** [comment]
Hi, I would like to work on this issue in C++, please assign this issue to me and add **C++** label to it

**Comment by chehak123** [comment]
> I would like to work on this issue under DWOC

in C++
