### ISSUE TITLE
Program to convert BST to Greater Sum Tree

### ISSUE THREAD

**Issue by vrandachag** [HarshCasper/NeoAlgo#1726]
## 🚀 Feature

Given BST is transformed into greater sum tree where each node contains sum of all nodes greater than that node.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Given a Binary Search Tree (BST), convert it to a Greater Tree such that every key of the original BST is changed to the original key plus sum of all keys greater than the original key in BST.

**Comment by vrandachag** [comment]
I would like to add C++ program for this issue. Please assign this to me.

**Comment by chehak123** [comment]
hii 
i would like to work on this issue under dwoc

**Comment by kapilkumar2001** [comment]
I would like to work on this issue in java
