### ISSUE TITLE
Implementing Tree Data Structure in C++,Python3 using Linked List.

### ISSUE THREAD

**Issue by razorblade42** [HarshCasper/NeoAlgo#1728]
## 🚀 Feature

(A clear and concise description of what the feature is.)
A tree data structure which can have functions like search,insertchild  etc..

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes
## Motivation
It is very important to know about Tree data stucture before going for BSTs,AVL Trees,Red Black Tree etc.
(Please outline the motivation for the proposal.)

## Pitch
It is a good start before learning about other types of trees and also it is a important part of  Data Structures.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by razorblade42** [comment]
I would like to work on it.

**Comment by razorblade42** [comment]
please assign it to me

**Comment by keshav340** [comment]
Can I do it.

**Comment by khusboobothra** [comment]
I am interested in implementing Trees in C++.Can I do it?
