### ISSUE TITLE
(1) A* Pathfinding Algorithm with GUI in Python (2) Adding programs in: (a) C => folders: ds, math, other; (b) JavaScript => various cp, ds, and maths programs

### ISSUE THREAD

**Issue by proghead00** [HarshCasper/NeoAlgo#1733]
## 🚀 Feature

(A clear and concise description of what the feature is.)

**(1) A Star Pathfinding Algorithm with GUI in Python**:
Implemented with pygame, this script will find the shortest distance between two nodes using A* Algorithm.
Instructions/ Keys Functionalities :

- Left Click to add start and end nodes
- Right Click to remove the nodes
- Space Bar to start finding the shortest distance
- 'C' to clear and reset the grid

(2) Under **ds** folder in C =>  _Doubly Linked List_ 

(3) Under **math** folder in C => _palindrome, special no., magic number, binary to decimal (and vice-versa),  Smith no., perfect square no. and so on._

(4) Under **JavaScript**, I'll provide different **cp**, **ds**, and **math** programs

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read the Contributing Guidelines on Pull Requests.

## Motivation

(Please outline the motivation for the proposal.)
People who are visiting this repository have a common purpose - to get most of the popular and well-used data structures and algorithms. The programs I am adding are very popular and are common interview and competitive questions. They will get a tonne of benefits from this.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
These programs enhance the workflow and give a better sight of how we can use different data structures and algorithms and are very common in examinations too.

**Comment by proghead00** [comment]
Please assign this issue to me. Waiting for your response.

**Comment by HarshCasper** [comment]
Hi @proghead00 

Thanks for making this Issue! As a Side-Note, we would not need a GUI for our Code. You can safely omit that part. 

Also, try to make PRs as discrete as possible. Don't push a lot of Code into a single PR. Make PRs with only one language and corresponding README changes.

**Comment by proghead00** [comment]
Okay @HarshCasper . So, I'll omit the GUI as you say.
Can I open multiple PRs then? Like, if I code some programs in C, then open PR, and then code in JS, and again open PR for the same?

**Comment by proghead00** [comment]
And I'd like to get assigned for this :)

**Comment by HarshCasper** [comment]
> Okay @HarshCasper . So, I'll omit the GUI as you say.
> Can I open multiple PRs then? Like, if I code some programs in C, then open PR, and then code in JS, and again open PR for the same?

Works! Please go ahead

**Comment by proghead00** [comment]
@HarshCasper So, I am creating separate branches for separate PRs. 
I already made a branch named **proghead00** 2 days back and added files for **C**.
For the programs for other languages like **JS**, the branch name goes like this:  **proghead00_JS**, and so on.

**Comment by HarshCasper** [comment]
> @HarshCasper So, I am creating separate branches for separate PRs.
> I already made a branch named **proghead00** 2 days back and added files for **C**.
> For the programs for other languages like **JS**, the branch name goes like this: **proghead00_JS**, and so on.

Looks good!

**Comment by proghead00** [comment]
> > @HarshCasper So, I am creating separate branches for separate PRs.
> > I already made a branch named **proghead00** 2 days back and added files for **C**.
> > For the programs for other languages like **JS**, the branch name goes like this: **proghead00_JS**, and so on.
> 
> Looks good!

Should I go and start opening PRs?

**Comment by shraddhavp** [comment]
yes go ahead @proghead00
