### ISSUE TITLE
Tarjan's Algorithm | C++

### ISSUE THREAD

**Issue by singhsaurav23** [HarshCasper/NeoAlgo#1736]
## 🚀 Feature
Implementation of Tarjan's Algorithm in C++ to find the number of strongly connected components in the graph.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

It is an interesting algorithm to learn and implement as it can help one to grasp the concept of strongly connected components and in time and low time of vising a node in a graph.

## Pitch

This is another approach in addition to Kosarajau's Algo to find a number of strongly connected components(SCC). It is based on the idea of in time and low time of a graph. And one can implement it using one DFS call as compared to Kosaraju's which requires 2 DFS calls.

**Comment by singhsaurav23** [comment]
I would like to work on it. Please assign this to me.
I would be grateful if you add a DWOC label to this issue.

**Comment by atharvagadkari05** [comment]
I'm Interested in this and would like to contribute under DWoC.
I've decent knowledge about data structures and algorithms.
Can you please assign me this?

**Comment by HarshCasper** [comment]
> I'm Interested in this and would like to contribute under DWoC.
> I've decent knowledge about data structures and algorithms.
> Can you please assign me this?

Hello @atharvagadkari05 

Since @singhsaurav23 created the Issue and specifically mentioned C++, I have assigned him the Issue on the same. If you would like to take up this Issue in any other language, feel free to suggest!

**Comment by atharvagadkari05** [comment]
@singhsaurav23 
Ok, I'm comfortable in java and would like to contribute in this.

**Comment by atharvagadkari05** [comment]
@shraddhavp  @saurav  do we have to make changes in master branch or in some other branch??

**Comment by singhsaurav23** [comment]
@atharvagadkari05 fork the master, and start making changes on the local branch and then push the changes in the local branch.

**Comment by atharvagadkari05** [comment]
@singhsaurav23 can you be little more
specific about the changes? Do I have to simply write tarjan's algorithm in java and push it to the local branch?

**Comment by Anish528** [comment]
please assign me this issue in Java under Dwoc @HarshCasper sir.
