### ISSUE TITLE
Circular Queue in C

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#1741]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Implementation of Circular Queue Data Structure in C

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
(Write your answer here.)

## Motivation

Making this repo as one step solution for data structures and algorithms.
(Please outline the motivation for the proposal.)

## Pitch

Almost all the data structures and algorithms are there in this wonderful repository, why not add one more to the stack?
(Please explain why this feature should be implemented and how it would be used.)

## Assignees:

C: @@iamvs-2002
C++: @shivangi00
Java:
Python:
JavaScript:
Go:
C#:

**Comment by iamvs-2002** [comment]
Kindly assign me this issue. I have a ready solution for the same.
@shraddhavp 
@DWOC mentors

**Comment by Rishikeshrajrxl** [comment]
Please assign me for c++

**Comment by shivangi00** [comment]
@shraddhavp @dwoc mentors please assign this to me I can do this in C++. Have a ready solution for this.

**Comment by manvi0308** [comment]
Assign me this issue

**Comment by iamvs-2002** [comment]
> Kindly assign me this issue. I have a ready solution for the same.
> @shraddhavp
> @dwoc mentors

@shraddhavp I guess @iamrajiv is already a maintainer for this repository right?

**Comment by iamrajiv** [comment]
@Rishikeshrajrxl @manvi0308 Specify your languages in which you to implement this.

**Comment by Rishikeshrajrxl** [comment]
> @Rishikeshrajrxl @manvi0308 Specify your languages in which you to implement this.
I would like to do in C++

**Comment by iamrajiv** [comment]
@Rishikeshrajrxl C++ is already assigned.

**Comment by iamvs-2002** [comment]
@iamrajiv May I implement it in the C language?

**Comment by iamrajiv** [comment]
@iamvs-2002 Yeah I have already assigned you.

**Comment by iamvs-2002** [comment]
Okay sir, thank you!

**Comment by Rishikeshrajrxl** [comment]
> @Rishikeshrajrxl C++ is already assigned
Then I will do in Java, do assign me

**Comment by iamvs-2002** [comment]
> > @Rishikeshrajrxl C++ is already assigned
> > Then I will do it in Java, do assign me

If you require any help while doing it in Java, do let me know.😉😊

**Comment by Rishikeshrajrxl** [comment]
> > > @Rishikeshrajrxl C++ is already assigned
> > > Then I will do it in Java, do assign me
> 
> If you require any help while doing it in Java, do let me know.😉😊

Sure @iamvs-2002

**Comment by Rishikeshrajrxl** [comment]
Hey, @shraddhavp  can I make more than 1 PR at a time. As I have I pending PR and also I have completed this task.

**Comment by japneetkaurbhatia** [comment]
Hey, I would like to work on this using Java. Can you please assign this to me ?
