### ISSUE TITLE
Burrows Wheeler transform(BWT) in Python

### ISSUE THREAD

**Issue by kartikp36** [HarshCasper/NeoAlgo#1744]
### Winter of code
Implement and add Burrows Wheeler transform algorithm in Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation
[This](https://www.youtube.com/watch?v=4WRANhDiSHM&list=TLPQMjcxMjIwMjCzl4040phelQ&index=2) Google Developers youtube video happens to be my motivation.
BWT is a simple yet widely used popular string compression algorithm, it is useful at places one would be amazed to know of!(Check out 11:50 of the video)
## Pitch

As it is a simple yet useful algorithm that has real world applications, I would like to implement it in Python under [NeoAlgo/Python/cryptography/](https://github.com/TesseractCoding/NeoAlgo/tree/master/Python/cryptography)

**Comment by shraddhavp** [comment]
is this a part of Winter of code or DWOC?

**Comment by kartikp36** [comment]
> is this a part of Winter of code or DWOC?

This is a part of [Winter of Code](https://winterofcode.com/).
And Thank You for assigining me!
