### ISSUE TITLE
Intersection Point of Two Linked Lists

### ISSUE THREAD

**Issue by Jassi10000-zz** [HarshCasper/NeoAlgo#1747]
## 💥 Proposal

" Intersection Point of Two Linked Lists " is a very popular question and is being asked many times in many companies in their interviews . 
I would like to add this problem into NeoAlgo's  repo named as Tesseract Coding .
Please assign me to work on this issue with tag DWOC

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by manvi0308** [comment]
I am willing to contirbute

**Comment by Jassi10000-zz** [comment]
@manvi0308 
 I have already requested for the assignment of issue first

**Comment by Rishikeshrajrxl** [comment]
I would like to do this in C++, for tag DWOC

**Comment by chehak123** [comment]
I would like to work on this issue under DWOC

**Comment by kapilkumar2001** [comment]
I would like to do this in java

**Comment by Sarthak-9** [comment]
I have a solution ready for it in cpp. May I proceed with this under DWOC ?
@dwoc

**Comment by shraddhavp** [comment]
assigned @Sarthak-9 and @Jassi10000

**Comment by Jassi10000-zz** [comment]
I mistakengly removed the assignment as my screen was hanging so the click went on wrong place
but
 I have also made the made PR before , plss check
