### ISSUE TITLE
Defanged IP Address 

### ISSUE THREAD

**Issue by ErzaTitania-2001** [HarshCasper/NeoAlgo#1750]
## 🚀 Feature

Given a valid (IPv4) IP address, return a defanged version of of that IP address. A defanged IP address replaces every period "." with "[.]".

Input : address : "1.1.1.1"
Output : "1[.]1[.]1[.]1"

Input : "255.100.50.0"
Output : "255[.]100[.]50[.]0"

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## Motivation

Competitive Coding.

## Pitch

Interview questions.

**Comment by ErzaTitania-2001** [comment]
@shraddhavp can i be assigned this in JAVA?

**Comment by ErzaTitania-2001** [comment]
@shraddhavp can you add the label, woc ?

**Comment by shraddhavp** [comment]
done @ErzaTitania-2001
