### ISSUE TITLE
Tim sort implementation

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#176]
**Algorithm: [Tim sort](https://en.wikipedia.org/wiki/Timsort)** 

Tim sort is a hybrid stable sorting algorithm, derived from merge sort and insertion sort, designed to perform well on many kinds of real-world data. It was implemented by Tim Peters in 2002 for use in the Python programming language. The algorithm finds sub-sequences of the data that are already ordered (runs) and uses them to sort the remainder more efficiently. This is done by merging runs until certain criteria are fulfilled.

**Languages Supported:**

* C
* C++ [@YashThakare]
* C#
* python
* java
* go
* dart

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++

**Comment by atarax665** [comment]
@YashThakare You can start working on this issue. Have a nice day.

**Comment by viveksahu26** [comment]
I would like to work on this issue in java.. please assign me..

**Comment by atarax665** [comment]
Closing by #1322
