### ISSUE TITLE
Minimum Cost of ropes

### ISSUE THREAD

**Issue by 1711shashank** [HarshCasper/NeoAlgo#1764]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

##Question :

There are given N ropes of different lengths, 
we need to connect these ropes into one rope. 
The cost to connect two ropes is equal to sum of their lengths. 
The task is to connect the ropes with minimum cost.

**Comment by 1711shashank** [comment]
Please assign this to me in C++

**Comment by kapilkumar2001** [comment]
I would like to work on this issue in java.
