### ISSUE TITLE
Propose a new README

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#1768]
## 🚀 Feature

Propose a new README

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Ever since this Project was launched, we have not yet seen a huge adoption of modern Documentation standards even through the Codebase has increased. We would like to have a more enhanced README for the purpose. 

This should consist of: 

- Project Overview
- Languages Supported 
- Contribution Guidelines 
- Contents 
- Communication Channels (Slack Workspace and Discussions)

The primary purpose is to make the README look attractive and better for Contributors to skim through. 

Before taking up this Issue, please let us know what your proposal would be. This Issue would be assigned to only those specific people, whose proposals look better for our current state.

**Comment by tharunc** [comment]
Hello there, 
     I would like to work on the readme.md file issue . Can you please assign it to me.

**Comment by shraddhavp** [comment]
assigned @tharunc

**Comment by muthuannamalai12** [comment]
Hai @HarshCasper 
Let me know if I can open a new issue for the same description. Since it's been 3 days no update regarding it.

**Comment by HarshCasper** [comment]
> Hai @HarshCasper
> Let me know if I can open a new issue for the same description. Since it's been 3 days no update regarding it.

Kindly wait. 7 Days is the buffer period of any Issue

**Comment by muthuannamalai12** [comment]
> > Hai @HarshCasper
> > Let me know if I can open a new issue for the same description. Since it's been 3 days no update regarding it.
> 
> Kindly wait. 7 Days is the buffer period of any Issue
Ok Thank you @HarshCasper

**Comment by tharunc** [comment]
@HarshCasper The templates in the readme,md section is redirecting to an unknown error page. What should I do now ?

**Comment by HarshCasper** [comment]
> @HarshCasper The templates in the readme,md section is redirecting to an unknown error page. What should I do now ?

Can you link them here?

**Comment by jainstuti** [comment]
Hi, I would like to contribute to this as a part of gssoc21. Please assign it to me

**Comment by HarshCasper** [comment]
> Hi, I would like to contribute to this as a part of gssoc21. Please assign it to me

Make a proposal and post on the Discussions. It isn't that easy that you might be taking it. We need a solid proposal on how the README would make the project look better.

**Comment by Ananya88** [comment]
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would like to to update the Readme.md file by adding :

1.How to contribute in this project. The procedure from forking to making a pull request.
2.About how to add issues and etc.

Please assign me with this issue .Thanks.

**Comment by HarshCasper** [comment]
@Ananya88 This is a proposal based Issue. Please make a Proposal on the Discussions tab and we would then assign you the Issue.

**Comment by Ananya88** [comment]
Thanks @HarshCasper  I added the same under documentation tab -> ideas .

**Comment by priyanka001tech** [comment]
Hello there,
I would like to work on the readme.md file issue . Can you please assign it to me.
