### ISSUE TITLE
Add a List to mention Open Source Events

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#1769]
## 🚀 Feature

Add a List to mention Open Source Events

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Add a List to mention Open Source Programs. NeoAlgo has been a part of many Open Source Programs like: 

- HakinCodes Contributor's Hack 
- DSC NSEC's Winter of Code
- DigitalOcean's Hacktoberfest 
- DevScript's DevScript Winter of Code 

Please create an `OPEN_SOURCE_EVENTS.md` and mention them in a bit more detail. If you would like to get some stats about these individual events, drop me a message on Slack and I can help with that.

**Comment by kanishkaa24** [comment]
I would like to work on this.

**Comment by himanshu007-creator** [comment]
@HarshCasper please assign me this issue. I have all resources ready

**Comment by himanshu007-creator** [comment]
> @HarshCasper please assign me this issue. I have all resources ready

Job Done https://github.com/TesseractCoding/NeoAlgo/pull/1945

**Comment by HarshCasper** [comment]
> @HarshCasper please assign me this issue. I have all resources ready

When you say that you have the resources ready, that doesn't mean that you will Copy and Paste from some other repository and paste it here. 

Go over to the Issue and see what I have actually mentioned. I clearly mentioned `Add a List to mention Open Source Programs. NeoAlgo has been a part of many Open Source Programs` and this states, I only want to have a list of programs, NeoAlgo has been a part of. 

What justification does that make for adding GSoC, GSoD and others where we don't even intend to participate?

**Comment by Anish528** [comment]
I would like to contribute to this project under dwoc label @HarshCasper sir

**Comment by vismitap** [comment]
Hey! Can I work on this issue?

**Comment by himanshu007-creator** [comment]
@HarshCasper , sir i would make another try for this issue. Please consider this one

**Comment by anirudhsai20** [comment]
Hi. Can I please work on this issue?

**Comment by HarshCasper** [comment]
Let me know, whoever is looking to work on this Issue for GSSoC '21. I will assign the same.

**Comment by vismitap** [comment]
Please assign this to me as a part of GSSoC!

**Comment by vismitap** [comment]
The coding period for GSSoC starts from 8th March as per new rules. I shall be back with a PR on 8th! 👍
