### ISSUE TITLE
Add a Github Action to auto-assign reviewers

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#1770]
## 🚀 Feature

Add a Github Action to auto-assign reviewers
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

With so many PRs kicking in, every week, its a definite pain to review each of them. What if we can have an Action to auto-assign reviewers, every time a PR is made? 

Make sure to add me ( @HarshCasper ), Rajiv ( @iamrajiv ) and Abhinav ( @atarax665 ) for the reviewers at the least.

**Comment by nr185091** [comment]
Hey @HarshCasper, I would like to take this issue if possible.

**Comment by nrickles3** [comment]
Hey @HarshCasper, I would like to take this issue if possible.

**Comment by atarax665** [comment]
> Hey @HarshCasper, I would like to take this issue if possible.

Sure, I am assigning this issue to you :+1:
