### ISSUE TITLE
Finding path in the 2D Maze

### ISSUE THREAD

**Issue by charlie219** [HarshCasper/NeoAlgo#1771]
# 💥 Proposal

I want to add a folder under Python/graphs named `Finding_path_in_the_Maze` which will house to different pathfinding algorithms. The argument of all these functions will be a Binary maze( 1 is way and 0 is a wall), the source cell and the destination cell. The pathfinding algorithms will be as follow.

- Breadth-First Search
- Depth-First Search
- Dijkstra Algorithm
- A*(astar) Algorithm

The maze will be considered as a graph and one can move in all four directions, in the current cell is (x,y) then the four possible moves will be **(x+1,y)-`DOWN`, (x-1,y)-`UP`, (x,y+1)-`RIGHT`, (x,y-1)-`LEFT`**. One has to print the path from the Source to Destination in the form of string if it's possible to reach. The string will contain **L, R, U and D** denoting the respective direction.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

I request @iamrajiv @atarax665 and @HarshCasper to assign me this issue in Python

**Comment by pranjalshinde** [comment]
I would like to work on this in Java under DWOC
I request @iamrajiv @atarax665 and @HarshCasper to assign me this issue and please add DWOC label to it
