### ISSUE TITLE
Counting Sort | Python

### ISSUE THREAD

**Issue by sahebsunny** [HarshCasper/NeoAlgo#1772]
## 🚀 Feature

Implementation of the Counting Sort algorithm in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It's an interesting and important algorithm to learn.

## Pitch

counting sort is an algorithm for sorting a collection of objects according to keys that are small integers.
Worst complexity: n+r
Average complexity: n+r
Space complexity: n+r

**Comment by sahebsunny** [comment]
Please assign me this sir I want to work

**Comment by kapilkumar2001** [comment]
I would like to do this in java

**Comment by HarshCasper** [comment]
> I would like to do this in java

Please raise a separate Issue for that! I don't want one Issue to be overlapped with multiple PRs. It would be difficult for me to review then.

**Comment by sahebsunny** [comment]
@HarshCasper Sir, I have made this issue and I love to work on it.
I would be grateful if you can assign this issue to me

**Comment by riyasingh1004** [comment]
I would like to work on this issue , please assign this to me.

**Comment by shraddhavp** [comment]
@sahebsunny  assigned

**Comment by sahebsunny** [comment]
thanks @shraddhavp
