### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by Sameera-Aryasomayajula** [HarshCasper/NeoAlgo#1773]
## 🚀 Feature

 An efficient program to find the sum of contiguous subarray within a one-dimensional array of numbers which has the largest sum.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

I would like to work on the C++ version of the kadane's algorithm.

**Comment by samir-0711** [comment]
I want to work on this. Can you assign me this issue?
Also add DWOC label.

**Comment by Sarthak-9** [comment]
I would like to work on this. May I go ahead with this ?
@shraddhavp
@dwoc

**Comment by shriyaMadan** [comment]
I would like to work on this issue. Can add in Python/C++/Java.

**Comment by shraddhavp** [comment]
@Sarthak-9  @shriyaMadan @Sameera-Aryasomayajula @samir-0711  please refer the issue #1604
