### ISSUE TITLE
Sieve of Eratosthenes

### ISSUE THREAD

**Issue by Khimit** [HarshCasper/NeoAlgo#1774]
@iamrajiv  @SKAUL05 @hushee69 @mechiragjain 
### **Sieve of Eratosthenes:**

**Sieve of Eratosthenes** is an efficient algorithm for finding all the prime numbers in a given set of interval.

We can add this algorithm in **C++ , Java , Python** folders.

I want to implement this algorithm in these languages.

**Comment by Khimit** [comment]
@iamrajiv  @SKAUL05 @hushee69 @mechiragjain 
I would like to work on this.
please assign this task to me..
thank you..

And please also add **DWoC** label to this...

**Comment by pranjalshinde** [comment]
@iamrajiv @SKAUL05 @hushee69 @mechiragjain
I would like to work in Java under DWOC please assign

**Comment by shraddhavp** [comment]
@Khimit  assigned

**Comment by shraddhavp** [comment]
> @iamrajiv @SKAUL05 @hushee69 @mechiragjain
> I would like to work in Java under DWOC please assign

as the issue was first created by @Khimit  so assigning it ,do check out other issues @pranjalshinde

**Comment by iamrajiv** [comment]
@Khimit Sieve of Eratosthenes is already implemented in C++, Java and Python.

**Comment by Khimit** [comment]
ohk..
so i am closing this issue now...
thanks
