### ISSUE TITLE
Counting Sort | Java

### ISSUE THREAD

**Issue by samir-0711** [HarshCasper/NeoAlgo#1776]
## 🚀 Feature

Implementation of the Counting Sort algorithm in Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It's an interesting and important algorithm to learn.

## Pitch

Counting sort is an algorithm for sorting a collection of objects according to keys that are small integers.
Worst complexity: O(n+k)
Average complexity: O(n+k)
Space complexity: O(n+k)
where n is the number of elements in input array and k is the range of input.

**Comment by samir-0711** [comment]
I want to work on this. Can you assign me this issue?
Also add DWOC label.

**Comment by Sarthak-9** [comment]
I can work on this for both java and cpp. Please assign it to me.

**Comment by Sarthak-9** [comment]
I can work on this for both java and cpp. May I go ahead with this?

**Comment by Sarthak-9** [comment]
I can work on this for both java and cpp. Please assign it to me.
@shraddhavp
@dwoc

**Comment by shraddhavp** [comment]
@samir-0711  you can go ahead with Java and @Sarthak-9  you can do it with CPP

**Comment by pranjalshinde** [comment]
I would like to work on this in java please assign

**Comment by Sarthak-9** [comment]
> @samir-0711 you can go ahead with Java and @Sarthak-9 you can do it with CPP

Sure

**Comment by japneetkaurbhatia** [comment]
Hey, I would like to work on this using C. Can you please assign this to me ?

**Comment by shraddhavp** [comment]
go ahead @japneetbhatia
