### ISSUE TITLE
Counting Inversions in Python

### ISSUE THREAD

**Issue by charlie219** [HarshCasper/NeoAlgo#1778]
## 💥 Proposal

This will be a Divide and Conquer approach of the inversion problem which will be added under Python/Other/ .
I want to contribute to it in Python.
About the problem:- [Count Inversion](https://www.geeksforgeeks.org/counting-inversions/)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

@atarax665 @iamrajiv and @HarshCasper, please review the issue and assign it to me for Python

**Comment by pranjalshinde** [comment]
I would like to work on this in Java, please assign
also add DWOC tag

**Comment by pranjalshinde** [comment]
can anyone help me with how to mention my pull request here? as @charlie219 has mentioned above?

**Comment by Anish528** [comment]
I want to work on this issue in Java please assign under Dwoc @iamrajiv sir

**Comment by atarax665** [comment]
> I want to work on this issue in Java please assign under Dwoc @iamrajiv sir

We already have an open PR in Java #1931 . You may go ahead with any other language you are comfortable with.
