### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by GSNCodes** [HarshCasper/NeoAlgo#178]
**[Kadane's Algorithm](https://en.wikipedia.org/wiki/Maximum_subarray_problem)**
Used for finding the longest contiguous sub-array sum.

**Languages supported**
- Python
- C [@raksha009]
- CPP 
- Java
- C#
- Golang
- JavaScript

**Comment by harsh7in** [comment]
@GSNCodes Can I work on it?

**Comment by GSNCodes** [comment]
@harsh-9in 
Hey! 
I'm not a reviewer. I've raised an Issue so that it can be assigned to me to work on.
You can maybe ask the reviewer to assign the same in another language.

**Comment by harsh7in** [comment]
okay, No Problem :)

**Comment by mar-galho** [comment]
Hi! @harsh-9in would you be able to write the code in another language?

**Comment by mar-galho** [comment]
@GSNCodes, you can submit the algo in Python :)

**Comment by harsh7in** [comment]
@ricardoprins I can submit it Using c++.

**Comment by mar-galho** [comment]
Perfect, game on @harsh-9in !

**Comment by mar-galho** [comment]
Alright, is anyone here up for a challenge?

**Comment by parjanyaacoder** [comment]
Hello everyone, I am new to this repository. It will be my first contribution to this repo. 
@ricardoprins 
Can I work on this issue in Java.

**Comment by parjanyaacoder** [comment]
@ricardoprins Please assign me this task.

**Comment by vgb-codes** [comment]
@parjanyaacoder Go ahead with Java.

**Comment by ghost** [comment]
I also wanna contribute to this I wanna contribute to it in java
I can write a very bigneer friendly code which a student who is staring only with java can understand @VijayaGB98   please assign me

**Comment by imPGupta** [comment]
Hello, I am new to this repository. I haven't contributed anything to this repo.
I can work on this issue in C, C++ & Python.
@VijayaGB98 can you please assign me this task?

**Comment by vinaykumar7686** [comment]
I can work on Python, C and Java.

**Comment by smriti-21** [comment]
I can work on this using C.

**Comment by pulkitgovrani** [comment]
@ricardoprins @HarshCasper @Kajol-Kumari  Can I work on this in Javascript.

**Comment by raksha009** [comment]
Hi, I created an issue #352  .. but I am not assigned the task here. Plz asssign it to me.

**Comment by raksha009** [comment]
plz assign me this issue @atarax665 @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
@raksha009 please go with C

**Comment by Kathan-Vakharia** [comment]
I would like to work in Golang, @Kajol-Kumari  please assign me :)
