### ISSUE TITLE
Queue, stack, anagram, LetterCount, Vowels and consants

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#1780]
## 💥 Proposal

1. Made the already existing  _queue_ program dynamic.
2. Made a dynamic stack program named Stack2.
3. The _anagram_ program that existed could have taken advantage of python and was a bit lengthy so I changed it
4. Added a program that tells the _occurence of letter_ in a word using a dictionary
5. Added a program that helps to count the number of vowels and constants in a string )

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by atriadhiakri2000** [comment]
1. Implement Stack / Implement Queue
3. Implement Stack using Queue
4. Implement Queue using Stack
5. Check for balanced parentheses
6. Next Greater Element
@shraddhavp @HarshCasper @iamrajiv    Please assign me these

**Comment by shloka-gupta** [comment]
I have made a PR regarding the issues stated above. It is for DWOC. If there are any changes required. Kindly let me know

**Comment by atriadhiakri2000** [comment]
These are not related to Changes But these are related to DWOC. I have already used two of my issues and they are closed now. So I was looking for issues opened under Stacks or queues so that I can ask to be assigned to them.

**Comment by iamrajiv** [comment]
> * Implement Stack / Implement Queue
> * Implement Stack using Queue
> * Implement Queue using Stack
> * Check for balanced parentheses
> * Next Greater Element
>   @shraddhavp @HarshCasper @iamrajiv    Please assign me these

@atriadhiakri2000 Please make a separate issue on this.

**Comment by HarshCasper** [comment]
Hello @chicken-biryani (Damn good Username; I need to cook someday 😆 ) 

Since you have already created an Issue, make separate PRs for all of them.

**Comment by shloka-gupta** [comment]
Works!
Thankyou! (Just order-in)
