### ISSUE TITLE
Count set bits in an integer

### ISSUE THREAD

**Issue by Sameera-Aryasomayajula** [HarshCasper/NeoAlgo#1783]
## 🚀 Feature

An efficient program to count the number of 1s in the binary representation of an integer.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

I would like to do the C++ implementation for this.

**Comment by Sameera-Aryasomayajula** [comment]
Can you please assign this issue to me

**Comment by shraddhavp** [comment]
@Sameera-Aryasomayajula  you can go ahead with cpp

**Comment by iamvs-2002** [comment]
May I solve the same issue in Java?

**Comment by pranjalshinde** [comment]
I want to solve this in java

**Comment by Rishikeshrajrxl** [comment]
I want to do this in python. Please assign me.

**Comment by manvi0308** [comment]
I want to solve this

**Comment by shraddhavp** [comment]
> May I solve the same issue in Java?

you can @iamvs-2002

**Comment by shraddhavp** [comment]
> I want to do this in python. Please assign me.

ok @Rishikeshrajrxl

**Comment by iamvs-2002** [comment]
@shraddhavp Thanks for assigning me the issue.

**Comment by iamvs-2002** [comment]
@shraddhavp Should I make a separate folder for this?

**Comment by shraddhavp** [comment]
no @iamvs-2002  add it in other problems folder

**Comment by iamvs-2002** [comment]
Okay

**Comment by kenkirito** [comment]
can i contribute also

**Comment by Anish528** [comment]
Could I work on this issue in Java

**Comment by achalesh27022003** [comment]
@shraddhavp  mam I can do this implementation in C++. Please assign it to me.

**Comment by shraddhavp** [comment]
go ahead @achalesh27022003

**Comment by achalesh27022003** [comment]
https://github.com/TesseractCoding/NeoAlgo/pull/2099 
Pls merge and  level label it. Thanks

**Comment by iamvs-2002** [comment]
@shraddhavp Kindly add the level label too.
