### ISSUE TITLE
Implementation of Doubly linked list in python.

### ISSUE THREAD

**Issue by Rahul555-droid** [HarshCasper/NeoAlgo#1795]
## 🚀 Double linked list

Implementation of Doubly linked list in python using OOPs.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes and I couldn't find double linked list implemented in python on this repo.
It was implemented in C++ though some time back.

## Motivation
My first contribution on NeoAlgo repository

## Pitch
Doubly linked list has several advantages over singly linked list. 
In DLL we can traverse in both directions forward and backward.
DLL is on average more efficient in delete and insert operations than singly linked list.

Most newbies to coding use python as their first language and hence at times to learn DSA python is used.
Having a python implementation of basic DSA is needed.

**Comment by Rahul555-droid** [comment]
If this issue could be added here then please assign this issue to me with DWOC label.
Thanks :)

**Comment by adysis14** [comment]
I would like to do this, but would this be counted in DWOC? If so, please add appropriate label for it.
 I would like to work on this issue, can you please assign this issue to me?
Thank You.

**Comment by Rahul555-droid** [comment]
Lol I think the admins here have been inactive for long time
