### ISSUE TITLE
Implement Merge Sort Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#18]
**Algorithm:** 

[Merge Sort](https://en.wikipedia.org/wiki/Merge_sort)

**DS:** 

Sorting

**Languages Missing:**
- C#
- Javascript

**Comment by UtkarshChaurasia** [comment]
Can I work on this for languages C++, Java, and Python?

**Comment by HarshCasper** [comment]
@UtkarshChaurasia You already have a lot of Issues under your belt. You can complete the rest of the Issues and then I can assign this to you.

**Comment by Surajv311** [comment]
@HarshCasper Could you assign this issue to me , I can work on this for C , C++ language ?

**Comment by MSufiyanAG** [comment]
@HarshCasper  can you assign this issue to me I can work on this for java language?

**Comment by asaxena012** [comment]
@HarshCasper Could you assign this issue to me? I can work on this issue in C++.

**Comment by HarshCasper** [comment]
I have assigned you all the Issue. You can start working on it.

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by MSufiyanAG** [comment]
@HarshCasper  i have raised a pull request is anything missing in it .
I am asking this because it has not been merged yet.

I also had one more doubt i am now writing code for binary search.
if i upload file before my pull request #59 is merged will it show changes there?

**Comment by srinivasdasu24** [comment]
@HarshCasper can you assign this issue to me ,I will code in python

**Comment by mar-galho** [comment]
Someone already submitted it for Python :(

**Comment by ahampriyanshu** [comment]
Can I implement this algorithm in Golang.

**Comment by Huzaib** [comment]
Can I take it up in Java?
