### ISSUE TITLE
Diameter of a Tree || Python

### ISSUE THREAD

**Issue by Pranav016** [HarshCasper/NeoAlgo#1802]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This question is very often asked in the interviews. A lot of students think this is an easy question but actually it is very tricky to solve. I would like to work on this problem of Diameter of a Tree in Python.

I would like to work on this issue under **WoC** and **Devscript WoC**.

**Comment by shraddhavp** [comment]
assigned @Pranav016

**Comment by Pranav016** [comment]
> assigned @Pranav016

I would be working on this under **WoC**

**Comment by ankitasantape** [comment]
Please assign the issue to me I would like to work on this problem of the Diameter of a Tree in Java under DWoC

**Comment by shraddhavp** [comment]
assigned @ankitasantape
