### ISSUE TITLE
Wrapping Letters

### ISSUE THREAD

**Issue by ErzaTitania-2001** [HarshCasper/NeoAlgo#1804]
## 🚀 Feature

Given a list of sorted characters letters containing only lowercase letters, and given a target letter target, find the smallest element in the list that is larger than the given target. Letters also wrap around. 
Input :  ch='z' ; letters= ['a', 'b']
Output : a

Input : ch = 'a' ; letters = ['c', 'd', 'j']
Output : c
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Competitive Programming

## Pitch

Interview Questions.

**Comment by ErzaTitania-2001** [comment]
@shraddhavp can i be assigned in Java?

**Comment by shraddhavp** [comment]
assigned @ErzaTitania-2001

**Comment by shraddhavp** [comment]
what is the label you want me to add? DWOC OR WOC?

**Comment by ErzaTitania-2001** [comment]
Java, C++, Python.

**Comment by shraddhavp** [comment]
no i meant is this a part of dwoc or woc?

**Comment by ErzaTitania-2001** [comment]
Woc
