### ISSUE TITLE
Bankers Algorithm in Java

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#1806]
## 🚀 Feature

Adding Bankers Algorithm (OS)  in Java. It is one of the deadlock-avoidance methods.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The banker algorithm used to avoid deadlock and allocate resources safely to each process in the computer system. This algorithm is used to test for safely simulating the allocation for determining the maximum amount available for all resources. It also checks for all the possible activities before determining whether allocation should be continued or not.

## Pitch
OS is one of the most important topics for Placements. There are questions related to Process Synchronization and Deadlock. This will help to understand how the algorithm works and how it is implemented in Java.

**Comment by rutujadhanawade** [comment]
I would like to do this in C++

**Comment by shraddhavp** [comment]
go ahead @rutujadhanawade

**Comment by shraddhavp** [comment]
updates @rutujadhanawade ?
