### ISSUE TITLE
DLS (Depth Limited Search) in python

### ISSUE THREAD

**Issue by Harshitha-sa** [HarshCasper/NeoAlgo#1807]
## 🚀 Feature

DLS is used to search a target node in a graph. In order to avoid the infinite loop condition arising in DFS (Depth first search), in depth limited search technique, depth-first search is carried out with a predetermined depth limit.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Depth limited search is better than DFS and requires less time and memory space.

## Pitch

I would like to implement this solution with python. I will have 3 variables in order to carry out the search:-
Target node, Max Depth and Starting Node.
I would like to work for this issue under DWOC

**Comment by RhuthuHegde** [comment]
can I work on this issue?

**Comment by anirudhsai20** [comment]
Hi. Can I please work on this issue under DWOC?
