### ISSUE TITLE
Rabin Karp Algorithm

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1811]
## 🚀 Feature

C++ implementation of Rabin Karp Algorithm.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Rabin Karp is one of the introductory algorithms to find a pattern in a string

## Pitch

Finding a pattern in a string is very helpful

**Comment by gargVader** [comment]
Please assign this to me

**Comment by rutujadhanawade** [comment]
I would like to do this in java @shraddhavp Please assign

**Comment by GVictorsd** [comment]
I would like to implement it in python. Please assign it to me.

**Comment by Neilblaze** [comment]
@rutujadhanawade @GVictorsd go for it!

**Comment by GVictorsd** [comment]
@Neilblaze I am done with my part and I have also raised a PR. Please review and merge.
[MyPR](https://github.com/TesseractCoding/NeoAlgo/pull/1939)
