### ISSUE TITLE
Length of longest subarray with sum K

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1813]
## 🚀 Feature

C++ Program to find length of longest subarray with sum K.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Interesting application of hash.

## Pitch

Used in many competitive programming problems

**Comment by gargVader** [comment]
Please assign this to me

**Comment by gargVader** [comment]
@shraddhavp Can I go ahead with this? I have no pending issues.

**Comment by shraddhavp** [comment]
sure

**Comment by sumitsantape30** [comment]
@shraddhavp @balapriyac  Please assign me this, I'll do it using Java

**Comment by iamvs-2002** [comment]
May I implement the same in Java?

**Comment by shraddhavp** [comment]
@iamvs-2002  you can go ahead with C++

**Comment by thevivekpande** [comment]
@shraddhavp  @atarax665 can i do this in CPP?

**Comment by iamvs-2002** [comment]
> @iamvs-2002 you can go ahead with C++

Kindly unassign me as I am not much comfortable with Cpp. You may assign the same to @thevivekpande 
Thanks.

**Comment by atarax665** [comment]
> @shraddhavp @atarax665 can i do this in CPP?

You can go ahead with CPP. :+1:

**Comment by vismitap** [comment]
May I implement this in python?
