### ISSUE TITLE
Radix sort in Kotlin

### ISSUE THREAD

**Issue by shraddhavp** [HarshCasper/NeoAlgo#1815]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by KartikeySharma** [comment]
I would like to work on this @shraddhavp.
I have submitted a PR to update the existing radix sort to operate on negative numbers too.
The PR is #1817

**Comment by shraddhavp** [comment]
updates @KartikeySharma

**Comment by KartikeySharma** [comment]
I am waiting for PR #1885 to be checked. I have created the code but can't make a PR request else it will be merged with the prev one @shraddhavp

**Comment by KartikeySharma** [comment]
Submitted PR #2015
