### ISSUE TITLE
Binary tree traversals in java

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#1820]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
[DWOC]

## Motivation

Any process for visiting all of the nodes of a binary tree in some order is called a traversal. This single piece of code contains both recursive and nonrecursive implementation of all traversals. BST Traversal is the same as Binary Tree Traversal.

## Pitch
Codes of Preorder traversal, inorder traversal, and postorder traversal of binary tree in both recursive and nonrecursive ways are present.

**Comment by Rishikeshrajrxl** [comment]
I can do it in Java as well as in c++, please assign me this issue for the tag DWOC

**Comment by sumitsantape30** [comment]
> ## 🚀 Feature
> (A clear and concise description of what the feature is.)
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes
> [DWOC]
> 
> ## Motivation
> Any process for visiting all of the nodes of a binary tree in some order is called a traversal. This single piece of code contains both recursive and nonrecursive implementation of all traversals. BST Traversal is the same as Binary Tree Traversal.
> 
> ## Pitch
> Codes of Preorder traversal, inorder traversal, and postorder traversal of binary tree in both recursive and nonrecursive ways are present.

Please assign me this issue, I'll do it in JAVA under DWOC
