### ISSUE TITLE
Huffman Encoder in Java using Heaps

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#1822]
## 🚀 Feature

Huffman code is a particular type of optimal prefix code that is commonly used for lossless data compression. Huffman coding is arguably the most efficient Entropy coding algorithm in information theory.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This code is using the concept of heaps as a priority queue to implement the Huffman Encoder.

## Pitch

A Heap is a special Tree-based data structure. A priority queue is a special type of queue, where the elements within the queue have a specified priority-level. Heaps provide better performance compared to arrays or linked lists so it can be used as a priority queue.

**Comment by nayanajain** [comment]
@shraddhavp  please assign this issue to me in java
