### ISSUE TITLE
Exponential Search in Java

### ISSUE THREAD

**Issue by sakshikhachane** [HarshCasper/NeoAlgo#1826]
## 🚀 Feature
Exponential Search algorithm injava

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)? 
Yes

## Motivation
Exponential search is also known as doubling or galloping search. This mechanism is used to find the range where the search key may present.

## Pitch
It uses the binary search technique to find the exact location of the search key. The searching process becomes faster.

**Comment by sakshikhachane** [comment]
@shraddhavp Please assign me this issue. I am a participant in DWOC.

**Comment by Sarthak-9** [comment]
May I go ahead with cpp for DWOC ?
@shraddhavp

**Comment by shraddhavp** [comment]
yes @Sarthak-9  go ahead in cpp and @sakshikhachane  go ahead in java

**Comment by sakshikhachane** [comment]
@shraddhavp Please add the levels for this issue else it won't get counted.

**Comment by sakshikhachane** [comment]
@shraddhavp Please add a level label to this issue and PR as it isn't getting counted on the leaderboard.
