### ISSUE TITLE
Correcting binary search in C++

### ISSUE THREAD

**Issue by djm-1** [HarshCasper/NeoAlgo#1842]
## 🐛 Bug Report

In C++ binary search code, mid=(lb+ub)/2. But if lb and ub are both near to INT_MAX then summing up them will give integer overflow. So I want to modify the code to avoid integer overflow.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by djm-1** [comment]
Please assign this to me and label it for Devscript winter of code.

**Comment by Rajat-Jain29** [comment]
please assign to me

**Comment by djm-1** [comment]
I created the issue and I can solve it... assign it to me 😀

**Comment by shraddhavp** [comment]
assigned @djm-1

**Comment by djm-1** [comment]
Thank you ma'am

**Comment by djm-1** [comment]
Please label the difficulty
