### ISSUE TITLE
Z Algorithm

### ISSUE THREAD

**Issue by Sameera-Aryasomayajula** [HarshCasper/NeoAlgo#1848]
## 🚀 Feature

Z Algorithm is a linear time pattern search algorithm

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

I would like to work on the C++ version of this algorithm under DWOC.

**Comment by thevivekpande** [comment]
@shraddhavp @Sameera-Aryasomayajula @SKAUL05 @ArchanGhosh can i work on it?

**Comment by ArchanGhosh** [comment]
Yes you can work on this issue.
