### ISSUE TITLE
Length of longest subarray with sum zero

### ISSUE THREAD

**Issue by gargVader** [HarshCasper/NeoAlgo#1857]
## 🚀 Feature

C++ program for length of longest subarray with sum zero

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Interesting application of hash data structure.

## Pitch

Helps understand the hash data structure. Useful for online cp contests

**Comment by gargVader** [comment]
Please assign this to me

**Comment by Rajat-Jain29** [comment]
This involves the use of brute force where two nested loops are used. The outer loop is used to fix the starting position of the sub array, and the inner loop is used for the ending position of the sub-array and if the sum of elements is equal to zero then increase the count.

**Comment by Rajat-Jain29** [comment]
please assign to me I complete this code in C++ language
