### ISSUE TITLE
Rat in a Maze Problem

### ISSUE THREAD

**Issue by nayanajain** [HarshCasper/NeoAlgo#1861]
The problem is described as rat wants to move from source to destination and he can move down and right direction only. The problem will be implemented using backtracking.

**Comment by Rajat-Jain29** [comment]
please assign to me

**Comment by nayanajain** [comment]
@shraddhavp Please assign the issue to me itself...

**Comment by balapriyac** [comment]
@nayanajain I'm assigning it to you

**Comment by balapriyac** [comment]
@nayanajain pls specify the language that you'd be using.

**Comment by Rajat-Jain29** [comment]
C++

**Comment by nayanajain** [comment]
@balapriyac  c++

**Comment by nayanajain** [comment]
Please merge my code.. Thank you very much

**Comment by Rajat-Jain29** [comment]
See I solved the problem

**Comment by geekaditi** [comment]
Can I take this up in CPP?

**Comment by Neilblaze** [comment]
@geekaditi since @nayanajain is contributing in CPP, for now, feel free to catch it up in any other language e.g. java, python etc. :)

**Comment by sumitsantape30** [comment]
> @geekaditi since @nayanajain is contributing in CPP, for now, feel free to catch it up in any other language e.g. java, python etc. :)

Hey @Neilblaze @balapriyac , Please assign me this, I'll do it using Java :)

**Comment by nayanajain** [comment]
Done the requested changes..
can I get the points for this issue, for DWOC

**Comment by thevivekpande** [comment]
@shraddhavp @atarax665  can i do this on java?

**Comment by atarax665** [comment]
> please assign to me

Assigned in C++. :+1:

**Comment by atarax665** [comment]
> > @geekaditi since @nayanajain is contributing in CPP, for now, feel free to catch it up in any other language e.g. java, python etc. :)
> 
> Hey @Neilblaze @balapriyac , Please assign me this, I'll do it using Java :)

Assigned in Java :+1:

**Comment by thevivekpande** [comment]
@atarax665 @Neilblaze @balapriyac  I can do it in Python, Please assign me.

**Comment by HarshCasper** [comment]
> @geekaditi since @nayanajain is contributing in CPP, for now, feel free to catch it up in any other language e.g. java, python etc. :)

Assigning in Python 👍

**Comment by charlie219** [comment]
@HarshCasper this issue is already taken in python
https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/backtracking/RatInMaze.py
