### ISSUE TITLE
Python program to find the gcd of two numbers

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1902]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by sakshi300699** [comment]
<h2>Proposal</h2>
<p>GCD of two numbers is the largest number that can divide both numbers. In python, I can find the GCD of two numbers using recursion.</p>
<h2>Have you read the Contributing Guidelines on Pull Requests?</h2>
<p>Yes</p>

**Comment by sakshi300699** [comment]
I would like to work on this issue in **python** under **DWoC** . Kindly assign this to me.

**Comment by iamvs-2002** [comment]
May I implement the same in Java?

**Comment by Amit366** [comment]
Can I contribute??

**Comment by Sumanpal3108** [comment]
I am DWOC Participant. I would like to work on this issue. Please assign it to me

**Comment by sakshi300699** [comment]
@HarshCasper Could you please add a level tag to this issue under DWoC

**Comment by vismitap** [comment]
Hey! May I implement this in javascript?

**Comment by sakshi300699** [comment]
@HarshCasper  Please add the dwoc and level tag to this

**Comment by ChetasShree** [comment]
I am GSSoC'21 Participant. I would like to work on this issue. Please assign it to me. I will solve it in python
