### ISSUE TITLE
Check if all array elements are pairwise co-prime or not

### ISSUE THREAD

**Issue by sujal111** [HarshCasper/NeoAlgo#1903]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Check if all array elements are pairwise co-prime or not[Imp CP question in number theory]

**Comment by Jassi10000-zz** [comment]
I want to work on this issue . Please assign me with tag DWOC
