### ISSUE TITLE
Stack

### ISSUE THREAD

**Issue by atriadhiakri2000** [HarshCasper/NeoAlgo#1907]
## 🚀 Feature
Allow me to add

- Implement Stack / Implement Queue
- Implement Stack using Queue
- Implement Queue using Stack
- Check for balanced parentheses
- Next Greater Element
- Reverse Words in a String 
- Longest Palindrome in a string 
- Roman Number to Integer and vice versa
- Implement ATOI/STRSTR 
- Longest Common Prefix 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

Stack is quite an **commonly** used **data structure** and is quite **frequently** asked in interviews.

## Pitch

**Stacks** are very important things in **computer science**. Stacks help us **allocate memory**, **parse** and **run code**, add a way to undo the last action, etc. They're behind a bunch of very **important** algorithms, and they're the mechanism by which the CPU runs your code. Without stacks we would be **doomed**.

**Comment by atriadhiakri2000** [comment]
Please assign me all of these
@shraddhavp @HarshCasper @iamrajiv

**Comment by HarshCasper** [comment]
Small Advice: Please make separate PRs for all of them. All the Best 👍

**Comment by japneetkaurbhatia** [comment]
Hey!! Can you assign me this ?

**Comment by Amit366** [comment]
Can I implement in Java??

**Comment by HarshCasper** [comment]
> Hey!! Can you assign me this ?

Mention me the Language



> Can I implement in Java??

Make a separate Issue and mention me there
