### ISSUE TITLE
Different views of binary search tree

### ISSUE THREAD

**Issue by satyampgt4** [HarshCasper/NeoAlgo#1922]
## 🚀 Feature

Different views of binary search tree  in c++

Print Left View of Binary Tree
Print Right View of Binary Tree
Print Top View of Binary Tree
Print  Bottom View of Binary Tree

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

These problem will show how tree will seen from different angles . these question were asked in many interviews.

## Pitch

there are different approaches for different views

**Comment by satyampgt4** [comment]
@shraddhavp  I would like to do this task in c++
Please assign it to me!

**Comment by Ujjwal3009** [comment]
@shraddhavp I can implement same in java. Kindly assign me .

**Comment by shraddhavp** [comment]
assigned @satyampgt4  and @Ujjwal3009

**Comment by achalesh27022003** [comment]
@shraddhavp mam I can do the other remaining top and bottom views in C++. Please assign me.

**Comment by shraddhavp** [comment]
@achalesh27022003  it is already assigned to @Sarthak-9

**Comment by achalesh27022003** [comment]
Please reply it is 24 days now. 😅 please assign me under DWoC.

**Comment by HarshCasper** [comment]
> @shraddhavp mam I can do the other remaining top and bottom views in C++. Please assign me.

Hi @achalesh27022003 

Actually the C++ Code has already been merged. We don't actually need another variant now.
