### ISSUE TITLE
Binary tree traversals in C

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#1923]
## 🚀 Feature
I would love to work on postorder and inorder traversal of binary tree in C language as a part of DWOC
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
The tree is one of the most powerful of the advanced data structures and it often pops up in even more advanced subjects such as AI and compiler design. Surprisingly though, the tree is important in a much more basic application - namely the keeping of an efficient index. I would be working on 
1. Post order Traversal
2. Inorder Traversal 
(Please outline the motivation for the proposal.)

## Pitch
The importance of a binary tree is that it can create a data structure that mimics a "yes/no" decision making process.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC @HarshCasper sir. Kindly assign it to me

**Comment by muthuannamalai12** [comment]
> I would love to work on this issue as a part of DWOC @HarshCasper sir. Kindly assign it to me

Can I start working on it @HarshCasper sir

**Comment by HarshCasper** [comment]
> > I would love to work on this issue as a part of DWOC @HarshCasper sir. Kindly assign it to me
> 
> Can I start working on it @HarshCasper sir

Go ahead! 

Ain't a need to call me Sir! Consider me your best friend here 💯

**Comment by muthuannamalai12** [comment]
> > > I would love to work on this issue as a part of DWOC @HarshCasper sir. Kindly assign it to me
> > 
> > 
> > Can I start working on it @HarshCasper sir
> 
> Go ahead!
> 
> Ain't a need to call me Sir! Consider me your best friend here
Ok. Thank you for assigning it to me

**Comment by Rishikeshrajrxl** [comment]
Please assign me this issue, I can do in C, C++, Java

**Comment by Anish528** [comment]
Please Assign me this issue in Java under Dwoc @HarshCasper sir.

**Comment by Nidhideveloper** [comment]
I would like to contribute in C++ as a participant of GSSOC'21
