### ISSUE TITLE
 Palindrome | C

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#1925]
## 🚀 Feature
Adding Palindrome implementation using C language.
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
It's an interesting algorithm to learn.
(Please outline the motivation for the proposal.)

## Pitch
A palindrome is a technique used to check whether the word is the same when read forward and backward. It can be implemented by first reversing the word and then comparing it with the original
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC @HarshCasper sir. Kindly assign me

**Comment by iamvs-2002** [comment]
May I implement the same in Java?

**Comment by Rishikeshrajrxl** [comment]
Allow me to do this in C, C++ , Java, python  any of these language, @HarshCasper

**Comment by HarshCasper** [comment]
> Allow me to do this in C, C++ , Java, python any of these language, @HarshCasper

Please find the language that it has not been implemented in yet. Please do your own background check.

**Comment by Tanmay2510** [comment]
Can you please assign me this issue as i would love to work on this issue as part of DWOC. @HarshCasper

**Comment by yogitasaini** [comment]
Assign this to me in java

**Comment by Nidhideveloper** [comment]
Please assign this to me as a particant of GSSOC'21

**Comment by Nidhideveloper** [comment]
@HarshCasper I would like to contribute for this as a participant of GSSOC'21
