### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by Sameera-Aryasomayajula** [HarshCasper/NeoAlgo#1929]
## 🚀 Feature

A sorting algorithm that is mainly useful when input is uniformly distributed over a range

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Can I please work on this issue  in C++ under DWOC

**Comment by thevivekpande** [comment]
@Sameera-Aryasomayajula @SKAUL05 @ArchanGhosh @hushee69 can i work on it?

**Comment by ArchanGhosh** [comment]
Yes absolutely. feel free to contribute.
