### ISSUE TITLE
Arrange the list of programs in C-Plus-Plus

### ISSUE THREAD

**Issue by vrandachag** [HarshCasper/NeoAlgo#1938]
## 📚 Documentation

Arrange the list of programs in C-Plus-Plus in lexical order.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

**Comment by vrandachag** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by ankitaggarwal23** [comment]
@vrandachag I have assigned you.

**Comment by ankitaggarwal23** [comment]
@vrandachag I have assigned you.
