### ISSUE TITLE
Bilinear Search implementation

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#195]
**Algorithm: [Bilinear Search](https://www.ijcsmc.com/docs/papers/December2015/V4I12201543.pdf)**

It's a variation of linear search to search a element in an list/array.It search from both side. 

**Languages Supported:**
* C [@sparkingdark ]
* C++ 
* Python [@sparkingdark ]
* Java
* Javascript
* GO

**Comment by sparkingdark** [comment]
assign me in C and python @ricardoprins

**Comment by mar-galho** [comment]
you got it!

**Comment by atarax665** [comment]
@sparkingdark Submit a new PR for bilinear search implementation in C.

**Comment by sparkingdark** [comment]
Okay

**Comment by atarax665** [comment]
I am closing this issue and opening a new issue for the same to get some new contribution by the hacktoberfest contributors.
