### ISSUE TITLE
Regarding Bugs in the repo cloned folder

### ISSUE THREAD

**Issue by Jassi10000-zz** [HarshCasper/NeoAlgo#1960]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

I was submitting a pull request of an issue opened by me named as #1747 regarding the addition of program named as "Find the intersection point of Linked List " which I did using Java . As I opened the cloned folder in my VS Code it showed red marks in the Java folder as well as in JavaScript folder . But I didn't paid much attention and carried on with my new program addition 
 consequence of which was that  : While Submitting the PR , only one check of mine was passed , only the issue named check was pass , so I deleted the PR and again submitted it by deleting the file and again creating that , in hope that my clone version is showing bugs in my pc only , But second time also when I started the process all over again , it showed the same red checks again due to again my PR passed only 1 check . I even checked this problem by clicking the details of deepsource.io to look into the bugs and got to know that the JavaScript , Python and Go had bugs which are countable to 36 , so its my request to please look into this matter so that my efforts don't go in vain  of adding the program and making the respective PR

Here's what I found:

![JS issue](https://user-images.githubusercontent.com/64856348/103805682-ee0c9900-5079-11eb-9a39-4844cae0964e.PNG)

The Contributors who have added these files , had bugs in their additions due to which the contributors can get in problem , pls look into this 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

**Comment by HarshCasper** [comment]
Thanks @Jassi10000 for raising this up! 

We will look into it on immediate basis.
