### ISSUE TITLE
Anagram String 

### ISSUE THREAD

**Issue by thevivekpande** [HarshCasper/NeoAlgo#1969]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation

Anagram is frequently aksed and used cp problem.

## Pitch
An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once

**Comment by thevivekpande** [comment]
@atarax665 please assign this problem to me.

**Comment by atarax665** [comment]
> @atarax665 please assign this problem to me.

Please specify the language you would like to work in.

**Comment by thevivekpande** [comment]
@atarax665 I can do it in CPP and Java both.

**Comment by pranjalshinde** [comment]
I would like to solve this  in Java under DWOC

**Comment by atarax665** [comment]
> @atarax665 I can do it in CPP and Java both.

@thevivekpande You can work on this issue in C++ for now.

**Comment by atarax665** [comment]
> I would like to solve this in Java under DWOC

@pranjalshinde Go ahead with Java.

**Comment by KartikeySharma** [comment]
I would like to work on this issue in C++ @atarax665

**Comment by yogitasaini** [comment]
please assign this problem to me

**Comment by RuchiGitHu** [comment]
hi @atarax665 , I would like to contribute here. I am able to work on this issue by using java. 
Please assign me this issue so that I can assist here.
Looking forward to contribute in this issue.....

**Comment by atarax665** [comment]
> hi @atarax665 , I would like to contribute here. I am able to work on this issue by using java.
> Please assign me this issue so that I can assist here.
> Looking forward to contribute in this issue.....

Sure, you are assigned this issue in java.
