### ISSUE TITLE
Kadane algo

### ISSUE THREAD

**Issue by thevivekpande** [HarshCasper/NeoAlgo#1970]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Kadane algo is frequently used algo to check maximum sum subarray.

## Pitch

Kadane algo is a algorithm used to check maximum sum subarray in any array.

**Comment by thevivekpande** [comment]
@atarax665 please assign this problem to me.

**Comment by shraddhavp** [comment]
it is already implemented
