### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [HarshCasper/NeoAlgo#1973]
## 🚀 Feature

Hello @SKAUL05  @ArchanGhosh  @hushee69  @ShishirBhandari  @mechiragjain  
I would like to add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time , let me know if you are interested in  
Kindly please assign me this issue.
For reference, kindly check out: https://github.com/apps/welcome

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes , this is issue but 

## Motivation

Automate the welcome message and greet message instead of maintainer , motivated from others 

## Pitch

This feature will reuce the work of maintainer , the bot can greet the contributor and tell them that mainatiner will get back to them so that they can wait patiently

**Comment by shraddhavp** [comment]
goahead @akrish4

**Comment by akrish4** [comment]
thank you @shraddhavp 
pls add DWOC and Level label 
there are  5  (Level-1 ,  Level-2  ,  Level-3  ,  Level-4  ,  Level-5)  labels 
kindly add a label you think would be appropriate

**Comment by akrish4** [comment]
there are 5 (Level-1 , Level-2 , Level-3 , Level-4 , Level-5) labels
kindly add a label you think would be appropriate 
DWOC can only count our contribution through the Level label 

@shraddhavp

**Comment by akrish4** [comment]
> there are 5 (Level-1 , Level-2 , Level-3 , Level-4 , Level-5) labels
> kindly add a label you think would be appropriate
> DWOC can only count our contribution through the Level label
> 
> @shraddhavp

@shraddhavp  kindly add the level label so that I can open a pr

**Comment by shraddhavp** [comment]
added @akrish4
