### ISSUE TITLE
Implement stack using Linked List in C language 

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#1983]
## 🚀 Feature
I would love to implement Stack using Linked List data structure in C language as a part of DWOC.
It would have 3 operation namely push, pop, and display
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
The stack is quite a commonly used data structure and is quite frequently asked in interviews.
(Please outline the motivation for the proposal.)

## Pitch
Stacks are very important things in computer science. Stacks help us allocate memory, parse and run code, add a way to undo the last action, etc. They're behind a bunch of very important algorithms, and they're the mechanism by which the CPU runs your code. Without stacks, we would be doomed.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me.

**Comment by bhavya092** [comment]
I would love to contribute to this issue under DWOC....Can you assign this to me?

**Comment by 07yuvraj** [comment]
Hey i would like to do this using c++.May i go ahead?

**Comment by Vrushti24** [comment]
Hey can I work on this issue?

**Comment by achalesh27022003** [comment]
@HarshCasper  sir I can implement it using C++. Please assign me under DWoC.

**Comment by vilsijain** [comment]
Can you assign me i can do in python,c,c++,java
