### ISSUE TITLE
Memory Allocation in Operating Systems in Java

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#1984]
## 🚀 Feature
[DWOC Contribution]
Memory Allocation in Operating Systems 
1. First-Fit Memory Allocation
2. Best-Fit Memory Allocation
3. Worst-Fit Memory Allocation

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The operating system must keep a list of each memory location noting which are free and which are busy. Then as new jobs come into the system, the free partitions must be allocated.

These partitions may be allocated by 3 ways:
best fit: smallest hole (contiguous space) the segment can fit in
first fit: first hole (contiguous space) the segment can fit in
worst fit: largest hole (contiguous space) the segment can fit in

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Can you please label this issue as DWOC?
Also please add the level.

**Comment by shraiyya** [comment]
Please assign me this issue and add the level of the PR for DWOC.

**Comment by vilsijain** [comment]
Can you assign
