### ISSUE TITLE
Queue implemented as a list in C

### ISSUE THREAD

**Issue by KlaraKrmpotic** [HarshCasper/NeoAlgo#1985]
## 🚀 Feature

I would love to implement Queue by using a Linked List data structure in C language.
It would have 5 methods: enqueue, dequeue, isEmpty, isFull, Peek

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Queue is often used in programming it is close to Stack but you can access it from both ends and it goes by logic First-in-First-out.

## Pitch

Application of queue can be seen in real world, basically anywhere where you for example have a line; the first person to come is the first person to go. In programming, you can add things (enqueue) to one side of the queue and delete/remove (dequeue) them from the other. Also, isEmpty would return boolean value of whether or not the queue is empty. isFull returns if there is something in the queue. Peek qould give the value of the next item in the queue without removing it.

**Comment by KlaraKrmpotic** [comment]
Please assign me to this issue , I would love to work on it.

**Comment by bhavya092** [comment]
I would love to contribute to this issue...Can you assign this to me?

**Comment by pranjalshinde** [comment]
I would like to work on this in Java under DWOC, please assign
