### ISSUE TITLE
Euclid Algorithm for finding GCD

### ISSUE THREAD

**Issue by harsh7in** [HarshCasper/NeoAlgo#199]
**Algorithm:**  Euclid Algorithm 

For finding Greatest common divisor

**Languages Supported:**

C [@Vrindagupta6828]
C++ [@harsh-9in ]
python [@GSNCodes ]
java [@rohitm131]
javascript

**Comment by harsh7in** [comment]
Hello reviewers,
May I work on this issue using C++.

**Comment by GSNCodes** [comment]
I could work on the same in Python :)

**Comment by harsh7in** [comment]
@HarshCasper  ??

**Comment by rohitm131** [comment]
can i work on the same in java ?

**Comment by vgb-codes** [comment]
@harsh-9in Please go ahead with C++
@GSNCodes  Please go ahead with Python
@rohitm131 Please go ahead with Java

**Comment by Vrindagupta6828** [comment]
Can i work on the same in c @vijayaGB98?

**Comment by vgb-codes** [comment]
@Vrindagupta6828 Yes go ahead with implementation in C.

**Comment by smriti-21** [comment]
Can I work on this using C?

**Comment by pulkitgovrani** [comment]
@HarshCasper @ricardoprins Can I can work on this in Javascript
