### ISSUE TITLE
Infix to Postfix Conversion

### ISSUE THREAD

**Issue by 07yuvraj** [HarshCasper/NeoAlgo#1997]
## 🚀 Feature

An important feature of stack that converts Infix equation to Postfix.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is an interesting and necessary algorithm of stack.

## Pitch

This is one of the important partical implementation of stack where an infix equation is converted into Postfix equation.

**Comment by ankitasantape** [comment]
Please assign this issue to me under DWoC. 
I would like to solve this using java.

**Comment by 07yuvraj** [comment]
I am doing this with C language kindly assign it to me @ankitaggarwal23 .
