### ISSUE TITLE
Implementation in Java

### ISSUE THREAD

**Issue by Amit366** [HarshCasper/NeoAlgo#1999]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

1) Implementation of Stack using Queue
2) Implementation of Queue using Stack
3) Reverse a String
4) Longest palindrome in a String

Sir, I would like to implement this in Java under the DWOC program. Please assign this issue to me.

**Comment by Sobhit25** [comment]
I would like to do the above implementations using CPP.

**Comment by Amit366** [comment]
@HarshCasper The reverse string PR was merged 2 days back but it wasn't labelled. Please label it with DWOC and level tags so that could be considered .

**Comment by achalesh27022003** [comment]
I can do point 1,2,&4 in C++. Please assign me this issue @Amit366

**Comment by Tanmay2510** [comment]
Can you please assign me this issue? @HarshCasper

**Comment by Amit366** [comment]
@Tanmay2510 I am already working on this issue

**Comment by Tanmay2510** [comment]
Hey @Amit366 actually I am a newbie. Is it like  that two cannot work on the same issue? Should I make a new issue proposing new topic?

**Comment by Amit366** [comment]
Yes u can create a new issue and start working on it

**Comment by Tanmay2510** [comment]
Thanks @Amit366

**Comment by achalesh27022003** [comment]
> I can do point 1,2,&4 in C++. Please assign me this issue @Amit366
@HarshCasper sir Please assign me under DWoC.

**Comment by HarshCasper** [comment]
> I can do point 1,2,&4 in C++. Please assign me this issue @Amit366

Go ahead!
