### ISSUE TITLE
All-contributors bot config

### ISSUE THREAD

**Issue by mar-galho** [HarshCasper/NeoAlgo#2]
A

**Comment by mar-galho** [comment]
@all-contributors please add @HarshCasper and @ricardoprins for content and doc.

**Comment by born-2learn** [comment]
@all-contributors please add @born-2learn  for content and doc

**Comment by born-2learn** [comment]
@all-contributors please add @HarshCasper and @ricardoprins for content and doc.

**Comment by born-2learn** [comment]
@all-contributors please add @ricardoprins  for content and doc

**Comment by mar-galho** [comment]
Since the bot is up and running, I'm closing this issue.
