### ISSUE TITLE
Locally Weighted Regression

### ISSUE THREAD

**Issue by infiniteoverflow** [HarshCasper/NeoAlgo#2000]
## 🚀 Feature

I would like to add a Machine learning model of a locally weighted regression algorithm to the Python folder.
 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

It’s inspired by cases when linear regression, which simply fits a line, isn’t sufficient, but we don’t want to overfit either.

## Pitch

This model can be used to fit non-linear data without overfitting the regression line. This considers the weight of the nearby data points and uses it to predict the target for a given data point.

**Comment by infiniteoverflow** [comment]
I would like to work on this as a part of DevScript Winter of Code.

**Comment by shraddhavp** [comment]
go ahead @infiniteoverflow
