### ISSUE TITLE
Divisor Game(CP)

### ISSUE THREAD

**Issue by Sumanpal3108** [HarshCasper/NeoAlgo#2003]
## 🚀 Feature

I want to add a new problem to the Repo under the folder CP named Divisor Game(LeetCode)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I found this Problem In leetcode biweekly Contest described as follows

Alice and Bob take turns playing a game, with Alice starting first.

Initially, there is a number N on the chalkboard.  On each player's turn, that player makes a move consisting of:

Choosing any x with 0 < x < N and N % x == 0.
Replacing the number N on the chalkboard with N - x.
Also, if a player cannot make a move, they lose the game.

Return True if and only if Alice wins the game, assuming both players play optimally.

## Pitch

I want to Upload the solution to the problem in Python as a participant Of DWOC Program.. Please assign it to me

**Comment by Sobhit25** [comment]
I want to also contribute to it using CPP. Please assign this to me or should I create a new PR?
