### ISSUE TITLE
Stack Implementation in C++

### ISSUE THREAD

**Issue by Sobhit25** [HarshCasper/NeoAlgo#2004]
## 🚀 Feature

Allow me to add
Implement Stack / Implement Queue
Implement Stack using Queue
Implement Queue using Stack
Check for balanced parentheses
Next Greater Element
Reverse Words in a String
Longest Palindrome in a string
Longest Common Prefix

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

Stack is quite a commonly used data structure and is quite frequently asked in interviews. I will implement in cpp.

## Pitch

Stacks are very important things in computer science. Stacks help us allocate memory, parse and run code, add a way to undo the last action, etc. They're behind a bunch of very important algorithms, and they're the mechanism by which the CPU runs your code. Without stacks, we would be doomed.

**Comment by Sobhit25** [comment]
I want to take part in it as a part of the DWOC Program.

**Comment by achalesh27022003** [comment]
@Sobhit25 I want to work on this issue in C++. You can assign it to me and pls label it DWoC. Thanks

**Comment by Vrushti24** [comment]
Hey can I work on this issue

**Comment by tiwariadarsh** [comment]
Hello I am Adarsh , 2nd year IIIT gwalior student.
I want to work on this issue during GSSOC. Please assign this work to me.
Thankyou
