### ISSUE TITLE
Sleep sort in Java

### ISSUE THREAD

**Issue by sakshikhachane** [HarshCasper/NeoAlgo#2018]
## 🚀 Feature

[DWOC Contribution]
Sleep sort in Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
Sleep sort works by starting a separate task for each item to be sorted, where each task sleeps for an interval corresponding to the item's sort key, then emits the item. Items are then collected sequentially in time.

## Pitch
(Please explain why this feature should be implemented and how it would be used.)

**Comment by sakshikhachane** [comment]
@HarshCasper Please assign me this issue.

**Comment by sakshikhachane** [comment]
@anushkrishnav Please add DWOC tag and level to this issue. Thank you :)

**Comment by Sarthak-9** [comment]
@shraddhavp I want to work on this in CPP. Please assign me for this.

**Comment by shraddhavp** [comment]
go ahead @Sarthak-9

**Comment by sakshikhachane** [comment]
@shraddhavp Can I do this in python as I have completed with java?

**Comment by sakshikhachane** [comment]
@shraddhavp May I start?

**Comment by shraddhavp** [comment]
@sakshikhachane  go ahead
and please do not close the issue others are also working on it

**Comment by achalesh27022003** [comment]
@shraddhavp mam I can implement this in C++. Please assign me

**Comment by vismitap** [comment]
May I implement this in javascript? Please assign this to me.

**Comment by anushkrishnav** [comment]
If its not already done then go ahead :)

**Comment by vismitap** [comment]
> If its not already done then go ahead :)

It is already done! Just checked. I will take up some other issue, np😅.

**Comment by achalesh27022003** [comment]
@vismitap bro it is not done in C++ & JS.

**Comment by vismitap** [comment]
> @vismitap bro it is not done in C++ & JS.
![image](https://user-images.githubusercontent.com/47056243/107393261-9c47aa80-6b20-11eb-8694-d3b8ac415408.png)

**Comment by achalesh27022003** [comment]
Sorry my bad!! It is not done in C++😅

**Comment by vismitap** [comment]
> Sorry my bad!! It is not done in C++😅

Np, thanks for helping though! 😀👍✌

**Comment by achalesh27022003** [comment]
Please review this PR #2144 under DWoC . Added sleep sort in C++ with markdown file.

**Comment by achalesh27022003** [comment]
@atarax665  sir my PR in C++ is going under review sir. Please keep open the issue till then😅😅

**Comment by achalesh27022003** [comment]
https://github.com/TesseractCoding/NeoAlgo/pull/2144
