### ISSUE TITLE
Breadth First Search or BFS for a Graph

### ISSUE THREAD

**Issue by kenkirito** [HarshCasper/NeoAlgo#2021]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I am really interested in compective programming. i enjoy doing dsa algorithum

## Pitch

Web Crawlers: Search engines or web crawlers can easily build multiple levels of indexes by employing BFS. BFS implementation starts from the source, which is the web page, and then it visits all the links from that source.
Navigation Systems: BFS can help find all the neighboring locations from the main or source location.
Network Broadcasting: A broadcasted packet is guided by the BFS algorithm to find and reach all the nodes it has the address for.

**Comment by ankitasantape** [comment]
Please assign me this code
