### ISSUE TITLE
Issue in Python Directory Readme File

### ISSUE THREAD

**Issue by harsha-sam** [HarshCasper/NeoAlgo#2029]
## 📚 Documentation

![image](https://user-images.githubusercontent.com/56500849/104913125-2b92ef80-59b3-11eb-93bd-8b9a9a7d77f4.png)
As you can see above, some of the ds problem links (Inorder, postorder, LinkedList, etc) are under the Cryptography section. Those problems should be moved to the Data Structures section in the readme file.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by harsha-sam** [comment]
I would like to fix this

**Comment by sheetalj2205** [comment]
I would like to work on this issue for gssoc'21. Can you please assign this to me?
