### ISSUE TITLE
Invert a Binary Tree in Python

### ISSUE THREAD

**Issue by harsha-sam** [HarshCasper/NeoAlgo#2030]
## 🚀 Feature

I would like to add : 
- Invert Binary Tree Problem in Python (recursive)
- Invert Binary Tree Problem in Python (iterative) 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Binary Tree problems are most common in Interviews and Competitive Programming. 

## Pitch

This problem can be used to invert a given binary tree.

**Comment by harsha-sam** [comment]
I would like to work on this

**Comment by shraddhavp** [comment]
go ahead @harsha-sam

**Comment by sakshikhachane** [comment]
@shraddhavp Can I do it in java?
