### ISSUE TITLE
ARMSTRONG NUMBER IN JAVA

### ISSUE THREAD

**Issue by tharunc** [HarshCasper/NeoAlgo#2036]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I would love to add ARMSTRONG NUMBER implementation in JAVA.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
YES
## Motivation

(Please outline the motivation for the proposal.)
An Armstrong number of a three-digit number is a number in which the sum of the cube of the digits is equal to the number itself. Hence 153 is an Armstrong number.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This enhances the Code Quality of Programmers.

**Comment by tharunc** [comment]
I WOULD LOVE TO WORK ON THIS ISSUE AS A PART OF **DWOC**. KINDLY ASSIGN ME THIS ISSUE.

**Comment by nayanajain** [comment]
Please assign me under DWOC for c plus plus, java and python

**Comment by Sarthak-9** [comment]
I can work  on this algorithm in CPP. Please assign it to me.

**Comment by HarshCasper** [comment]
@tharunc : Java
@nayanajain : Python
@Sarthak-9 : C++
@satyampgt4 :JavaScript

**Comment by sakshikhachane** [comment]
@HarshCasper Can I do this in PHP?

**Comment by satyampgt4** [comment]
@shraddhavp   i would like to work on it in JavaScript please assign it to me

**Comment by nayanajain** [comment]
@HarshCasper  this program is already made in python

**Comment by shraddhavp** [comment]
go ahead @satyampgt4

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.

**Comment by AkanshaUniyal** [comment]
Respected sir/ma'am, I'll be obliged to design this algorithm using JAVA
