### ISSUE TITLE
Calendar program in c++

### ISSUE THREAD

**Issue by himanshu007-creator** [HarshCasper/NeoAlgo#2038]
## 💥 Proposal
this program will accept input as a year and print the calendar of whole year

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES

**Comment by iamvs-2002** [comment]
May I implement a program to find the number of days between 2 dates in C?

**Comment by atarax665** [comment]
This issue doesn't fit in any of the domain that we cover in this repository.
