### ISSUE TITLE
Palindrome | Python

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#2044]
## 🚀 Feature
I would love to add Palindrome implementation using python language as a part of DWOC.
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
It's an interesting algorithm to learn.
(Please outline the motivation for the proposal.)

## Pitch
A palindrome is a technique used to check whether the word is the same when read forward and backward. It can be implemented by first reversing the word and then comparing it with the original
(Please explain why this feature should be implemented and how it would be used.)

**Comment by simarpreetsingh-019** [comment]
I would like to do this, but would this be counted in DWOC also? If so, please add appropriate label for it.
@muthuannamalai12 I would like to work on this issue.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by muthuannamalai12** [comment]
@shraddhavp Can you please assign me this issue as a part of DWOC

**Comment by shraddhavp** [comment]
go ahead @muthuannamalai12

**Comment by yogitasaini** [comment]
I would like to  do this , please assign it to me in java

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.
I can also do it in another language like Javascript, Java, C++, python, etc.

**Comment by kapilkumar2001** [comment]
I would like to do this in C++ under DWoC.

**Comment by ChetasShree** [comment]
I am GSSoC'21 Participant. I would like to work on this issue. Please assign it to me. I will solve it in python
