### ISSUE TITLE
Evaluation of postfix expression in C language

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#2045]
## 🚀 Feature
Given a postfix expression (as a string), the program must print the result after evaluating the expression. I would love to work on this as a part of DWOC.
For example:
Input:
73426^*+*8+

Output:
1821
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
This helps in better understanding of stacks
(Please outline the motivation for the proposal.)

## Pitch
This problem helps to have a grip over stack operations
(Please explain why this feature should be implemented and how it would be used.)

**Comment by Sarthak-9** [comment]
@shraddhavp I would like to work on this in CPP. Please assign it to me

**Comment by shraddhavp** [comment]
go ahead @Sarthak-9  in cpp and @muthuannamalai12  in C

**Comment by achalesh27022003** [comment]
I would like to work for it in C++ @shraddhavp mam.

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.
