### ISSUE TITLE
Page Replacement Algorithms in Operating Systems (Java)-DWOC

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#2054]
## 🚀 Feature

A page replacement algorithm looks at the limited information about accesses to the pages provided by hardware and tries to guess which pages should be replaced.
The simplest page-replacement algorithm is a FIFO algorithm. The first-in, first-out (FIFO) page replacement algorithm is a low-overhead algorithm that requires little bookkeeping on the part of the operating system.
In the Least Recently Used (LRU) page replacement policy, the page that is used least recently will be replaced.
Optimal Page Replacement algorithm is the best page replacement algorithm as it gives the least number of page faults.
[DWOC ISSUE]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Used Java for implementation

**Comment by shraiyya** [comment]
Please add DWOC Tag and Level.

**Comment by shraddhavp** [comment]
assigned @shraiyya
