### ISSUE TITLE
map, sort, filter, reduce in javascript

### ISSUE THREAD

**Issue by Sloth-Panda** [HarshCasper/NeoAlgo#2059]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Would like to show how these 4 works with proper example(under Dwoc, Swoc) 
Would like to 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by Sloth-Panda** [comment]
@shraddhavp would like to do this kindly let me know

**Comment by shraddhavp** [comment]
go ahead @Sloth-Panda

**Comment by Sloth-Panda** [comment]
@shraddhavp kindly check the pr and dwoc and level tags to the pr too
