### ISSUE TITLE
AVL tree in Java

### ISSUE THREAD

**Issue by sakshikhachane** [HarshCasper/NeoAlgo#2065]
## 🚀 Feature

(A clear and concise description of what the feature is.)
AVL tree is a self-balancing binary search tree.
Programming language - Java .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)? 

Yes

## Motivation

AVL tree is asked in interviews.

## Pitch

 AVL tree is used for indexing large records in a database to improve search.

**Comment by sakshikhachane** [comment]
@HarshCasper Please assign me this issue. I am a participant in DWOC.

**Comment by sakshikhachane** [comment]
@anushkrishnav @shraddhavp Please assign me this issue under DWOC.

**Comment by shraddhavp** [comment]
assigned @sakshikhachane

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.

**Comment by sakshikhachane** [comment]
@shraddhavp May I do the AVL tree implementation in python and cpp.

**Comment by sakshikhachane** [comment]
@shraddhavp May I proceed?

**Comment by sakshikhachane** [comment]
@atarax665 May I do AVL tree implementation in python and cpp?

**Comment by atarax665** [comment]
> @atarax665 May I do AVL tree implementation in python and cpp?

Sure. Go ahead.

**Comment by sakshikhachane** [comment]
@atarax665 Should I submit both the codes in one PR or should I make two different PRs for this?

**Comment by anushkrishnav** [comment]
@sakshikhachane it's cool if you can make 2 sep PR as it's easy to review.
