### ISSUE TITLE
finding out the  closest Pair of Points using Divide and Conquer algorithm

### ISSUE THREAD

**Issue by Sloth-Panda** [HarshCasper/NeoAlgo#2074]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Given an  array of n-points on a plane its required to find-out the closest pair of points 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by Sloth-Panda** [comment]
@shraddhavp let me know I want to add this to the repo

**Comment by adysis14** [comment]
@shraddhavp can you please assign this issue to me? I would love to work on this issue under DWOC label .
Thank you.

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.
