### ISSUE TITLE
Implementation of selection sort using js

### ISSUE THREAD

**Issue by Sloth-Panda** [HarshCasper/NeoAlgo#2075]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Would like to implement selection sort using js
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by Sloth-Panda** [comment]
@shraddhavp let me know would like to add this under DWOC

**Comment by Sloth-Panda** [comment]
@shraddhavp @atarax665 @HarshCasper  kindly check the pr.

Should someone really make a pr without getting assigned?

**Comment by Siddhant-K-code** [comment]
what's the status of this issue?

**Comment by achalesh27022003** [comment]
@Sloth-Panda sir I can implement selection sort using C++. Please assign me under DWoC.

**Comment by Sloth-Panda** [comment]
@achalesh27022003 dude I am a participant like you only don't call sir. I am on this issue BTW maintainor has asked for correction if he assigns you in c++ you can go ahead till then wait.

**Comment by achalesh27022003** [comment]
@shraddhavp  mam please assign me this issue to implement in C++.

**Comment by HarshCasper** [comment]
> @shraddhavp mam please assign me this issue to implement in C++.

Go ahead!
