### ISSUE TITLE
Swap 2 numbers using Bit Manipulation techniques

### ISSUE THREAD

**Issue by nayanajain** [HarshCasper/NeoAlgo#2095]
@HarshCasper  I would like to contribute to this issue under DWOC
I can do in c++ and java

**Comment by adysis14** [comment]
Can you please assign this issue to me? I would love to work on this issue under DWOC.
Thank you

**Comment by rcoder23** [comment]
I would like to solve this issue using java

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.

**Comment by Nidhideveloper** [comment]
I would like to contribute as a participant of GSSOC'21
