### ISSUE TITLE
Add program of "Maximize it!" in Python

### ISSUE THREAD

**Issue by mehabhalodiya** [HarshCasper/NeoAlgo#2096]
## 🚀 Feature

Add some in [Miscellaneous](https://github.com/TesseractCoding/NeoAlgo/tree/master/Miscellaneous/HackerRank) section:
I would like to add program for [Maximize it!](https://www.hackerrank.com/challenges/maximize-it/problem) in Python 3.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

This program is going to build ones logical thinking and how to solve a complex problem using Itertools and also it's success rate is about 78.88%. Hence, it will help you that how to solve a function requirements.

## Pitch

As it is under Itertools in HackerRank.

**Comment by mehabhalodiya** [comment]
I would like to work on this under GSSoC'21. 
Kindly assign me this!
@HarshCasper @anushkrishnav @shraddhavp @atarax665

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue under DWOC label.

**Comment by mehabhalodiya** [comment]
Why it is to be assigned to you if the issue is raised by me and I would to contribute on this?
Kindly check other issues @Dhriti-Roy on which no one is working! Thank you.
