### ISSUE TITLE
AES implementation in Python

### ISSUE THREAD

**Issue by Salonii02** [HarshCasper/NeoAlgo#2098]
## 🚀 Feature

This is going to be the implementation of the Advanced Encryption Standard (AES) algorithm in python
 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

Popular and widely adopted symmetric encryption algorithm nowadays is the Advanced Encryption Standard (AES). It is found at least six times faster than triple DES. AES encrypts and decrypts data using 128/192/256-bit keys into 128-bit blocks.

## Pitch

Popular and widely adopted symmetric encryption algorithm nowadays is the Advanced Encryption Standard (AES). It is found at least six times faster than triple DES.

**Comment by Salonii02** [comment]
I would like to work on this as a part of DWOC. Kindly Assign me this issue.
@HarshCasper @anushkrishnav

**Comment by anushkrishnav** [comment]
Done Good Luck !!

**Comment by Salonii02** [comment]
Hello @anushkrishnav,
I have added AES implementation in python first using pycrypto and later using pycryptodome since security checks were not successful. Library mentioned in your analysis check is pyca/cryptography for which I will have to implement in a new manner.
can you guide me here or using pycrypto or pycryptodome library is fine.
