### ISSUE TITLE
Implement Priority Queue

### ISSUE THREAD

**Issue by harsh7in** [HarshCasper/NeoAlgo#210]
**DS:**   Priority Queue

**Languages Supported:**
C
C++ [@harsh-9in ]
C#
python
java [@rohitm131 ]

**Comment by harsh7in** [comment]
Hey @HarshCasper , 
May I work on this issue using C++.

**Comment by rohitm131** [comment]
@HarshCasper 
Can i work on this issue using java

**Comment by vgb-codes** [comment]
@harsh-9in Go ahead with C++.
@rohitm131  Go ahead with Java.

**Comment by odavhad** [comment]
I want to work on this issue using Python.
