### ISSUE TITLE
To cyclically (clockwise) rotate a list of integers by N, Python, CP

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#2106]
## 💥 Proposal

Given a list of integers, cyclically rotate the list clockwise by N
Example: 
Input: [1, 2, 3, 4, 5]
Output: [5, 1, 2, 3, 4]
The list is rotated by 1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by shloka-gupta** [comment]
I would like to work on this proposal under DWOC

**Comment by nayanajain** [comment]
I would like to work for java and c++under DWOC.

please assign to me

**Comment by shloka-gupta** [comment]
@atarax665

**Comment by atarax665** [comment]
> I would like to work on this proposal under DWOC

Go ahead @chicken-biryani
