### ISSUE TITLE
Sorting algorithms and removing duplicates from a string using recursion.

### ISSUE THREAD

**Issue by Tanmay2510** [HarshCasper/NeoAlgo#2108]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

1. -   Merge Sort.
2. -   Quick Sort.
3. -   Removing duplicates from a string(using recursion).

All using JAVA
I would like to contribute these as part of DWOC. Please assign this issue to me.

**Comment by Tanmay2510** [comment]
Hey I would like to work on this issue kindly assign me @HarshCasper @anushkrishnav @shraddhavp

**Comment by yogitasaini** [comment]
Hey I would like to work on this issue please kindly assign ma

**Comment by IShahnawazShaikh** [comment]
I would like to work on this issue kindly assign to me @HarshCasper

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.
