### ISSUE TITLE
Bucket Sort in C++

### ISSUE THREAD

**Issue by m-code12** [HarshCasper/NeoAlgo#2110]
I would like to add Bucket Sort in C++ without using Insertion Sort as a part of DWOC. @shraddhavp @anushkrishnav Could you assign me this issue?

**Comment by harshbaid-13** [comment]
is this issue still open?

**Comment by m-code12** [comment]
> is this issue still open?

I am working on it @am-here

**Comment by m-code12** [comment]
@shraddhavp @anushkrishnav Can I implement Bucket Sort in Go as well?

**Comment by atarax665** [comment]
> @shraddhavp @anushkrishnav Can I implement Bucket Sort in Go

> I would like to add Bucket Sort in C++ without using Insertion Sort as a part of DWOC. @shraddhavp @anushkrishnav Could you assign me this issue?

You can implement this but it would be better if you can add the required changes in the existing Bucket Sort file, and make proper changes in the driver code to format the output.

**Comment by atarax665** [comment]
> @shraddhavp @anushkrishnav Can I implement Bucket Sort in Go as well?

Sure, go ahead.

**Comment by m-code12** [comment]
> > @shraddhavp @anushkrishnav Can I implement Bucket Sort in Go
> 
> > I would like to add Bucket Sort in C++ without using Insertion Sort as a part of DWOC. @shraddhavp @anushkrishnav Could you assign me this issue?
> 
> You can implement this but it would be better if you can add the required changes in the existing Bucket Sort file, and make proper changes in the driver code to format the output.

Okay will make the changes in it and raise a pr.
