### ISSUE TITLE
Implementing Tries and performing search, count words in Tries using Java.

### ISSUE THREAD

**Issue by Tanmay2510** [HarshCasper/NeoAlgo#2115]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

1. Tries
2. Search Word in Trie.
3. Count Words in Trie.

All using JAVA
I would like to contribute these as part of DWOC. Please assign this issue to me.

**Comment by Tanmay2510** [comment]
Hey I would like to contribute these as a part of DWOC. Kindly assign this issue to me @HarshCasper @anushkrishnav @shraddhavp @atarax665

**Comment by ankitasantape** [comment]
Please assign this issue to me under DWOC. I would like to implement Tries using Java.
