### ISSUE TITLE
Nearest Greater to Right Element

### ISSUE THREAD

**Issue by nayanajain** [HarshCasper/NeoAlgo#2116]
@shraddhavp  Please assign this issue to me under DWOC..  
I would like to work in c++

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue. I can do it in Python, C, C++, Java.

**Comment by anshu-30** [comment]
I would like to solve this issue . Kindly provide me the access

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by anushkrishnav** [comment]
> @shraddhavp Please assign this issue to me under DWOC..
> I would like to work in c++

DWOC is over but if you wish to work on it WIll assign

**Comment by anushkrishnav** [comment]
> Hi, i want to contribute as a participant of gssoc'21

You can contribute without being a participant too !! Also, GSSOC is not open yet !! If you are interested I will assign it to you

**Comment by HarshCasper** [comment]
@chehak123 

Let us know the language that you will be using to solve the Issue. Also please make the PR once the Coding Period starts.

**Comment by kotwani2883** [comment]
@chehak123  @anshu-30  @Dhriti-Roy  are you doing this?
If not @anushkrishnav  kindly assign this to me as a part of GSSOC'21.between i am proficient in c++.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon in cpp?

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!

**Comment by anushkrishnav** [comment]
Cool Sure

**Comment by Sakshi0401** [comment]
Hey 

> As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon in cpp?

Hey @anushkrishnav I can work upon this issue using python and JavaScript too

**Comment by anushkrishnav** [comment]
> Hey
> 
> > As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon in cpp?
> 
> Hey @anushkrishnav I can work upon this issue using python and JavaScript too

Good luck

**Comment by Sakshi0401** [comment]
> > Hey
> > > As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon in cpp?
> > 
> > 
> > Hey @anushkrishnav I can work upon this issue using python and JavaScript too
> 
> Good luck

So can I be assigned the issue to work upon or I can start working on it without being assigned?

**Comment by AasthaGoyalgit** [comment]
Thanks!! @anushkrishnav for assigning me this issue .I'll try my level best.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
I can do this in GO

**Comment by anushkrishnav** [comment]
Please make an individual issue on the language you want to implement this.
