### ISSUE TITLE
The README.md in every folder for every language is either empty or has a dummy character.

### ISSUE THREAD

**Issue by vismitap** [HarshCasper/NeoAlgo#2117]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)
The README.md file for every language in every category is either empty, or has some dummy character like 'a'. 
Refer 
![image](https://user-images.githubusercontent.com/47056243/107391789-1119e500-6b1f-11eb-8539-0ebc495d4479.png)
![image](https://user-images.githubusercontent.com/47056243/107392166-6950e700-6b1f-11eb-8146-0c4f2e721ace.png)

Do we really need to have a README.md for every folder and every language? If Yes, then README.md files need updation.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

**Comment by vismitap** [comment]
If README.md needs to be updated, Please let me know!

**Comment by Dhriti-Roy** [comment]
I would like to do it. kindly assign me for this issue.

**Comment by soumyavemuri** [comment]
Hello, I'd like to work on adding readme files under each directory to act as a sort of navigation and visualization of the content. I would like to be assigned this under GSSOC '21 please.

**Comment by soumyavemuri** [comment]
Hello, I'd like to work on adding readme files under each directory to act as a sort of navigation and visualization of the content.

**Comment by gat786** [comment]
If you must have seen the repository and the dummy characters. They are there for a reason and most being because we don't have any content there yet. Its great that you want to fix them and make this repository a better place. 
Go ahead and do that!
