### ISSUE TITLE
To have a section for hackathon problem statements with solutions.

### ISSUE THREAD

**Issue by bhav09** [HarshCasper/NeoAlgo#2119]
## 🚀 Feature

A section for hackathons that are held across different domains for different tech stack. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I have realised that there are a lot of people who want to learn new things but are not really comfortable in participating in hackathons publicly. There are also instances where people want to try to learn from these events and participate but they don't know which ones to really go for. So this section is a culmination where the ones who are not comfortable in taking part publicly can access the data to it and also the ones who are late in the race would be able to access and find all the problem statements and solutions to these hackathons/competitions at one place. 

## Pitch

This feature will be added as a resource to the repository. It will have sub-sections which will have the folder name as the name of the competition. These sub-sections/sub-folders will have problem statements in the readme.md file of that sub-section which will be used for informing about the competition: problem statement, when was it held, who hosted it and the dataset. 
This subsection will also have a dummy solution which won't be the most optimal solution but a solution good enough to make the newbie understand the problem and how to approach it.

**Comment by gat786** [comment]
Hackathon Problems are too broad to be covered over here. Because All I have seen here is direct questions which can be quantified into an algorithm and written code for. Although @HarshCasper might have some more ideas about how we can go forward with this.

**Comment by bhav09** [comment]
I agree, @gat786. We can make segregate different hackathons on the grounds of their domains. Like different section for data science, web dev etc. I would like to know your views on this too, @HarshCasper

**Comment by HarshCasper** [comment]
That would make the Project having too many solutions that would simply disturb the flow of the Project. Closing the Issue.
