### ISSUE TITLE
Implementing Prim's and Kruskal's algorithm using Java.

### ISSUE THREAD

**Issue by Tanmay2510** [HarshCasper/NeoAlgo#2121]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

1. Prim's Algorithm
2. Kruskal's Algorithm

 I would like contribute these as a part of DWOC. Kindly assign me

**Comment by Tanmay2510** [comment]
Hey, I would like to contribute this as a part of DWOC. Please assign this issue to me @atarax665 @anushkrishnav @Aanisha @HarshCasper

**Comment by chehak123** [comment]
Hey, I would like to contribute this as a part of GSSOC

**Comment by anushkrishnav** [comment]
@Tanmay2510 Start on it good luck but DWOC is over!! But you are still welcomed to contribute and Learn

**Comment by HarshCasper** [comment]
@Tanmay2510 

Let us know if you are planning to work on it. If not, please let us know as well, by unassigning yourself. We would appreciate honesty more than just ghosting us out after having an Issue :) 

@chehak123 

I have assigned you this issue. Note that you cannot work on more than 2 Issues at a single time. (You already have one)

**Comment by Tanmay2510** [comment]
> @Tanmay2510 
> 
> Let us know if you are planning to work on it. If not, please let us know as well, by unassigning yourself. We would appreciate honesty more than just ghosting us out after having an Issue :) 
> 
> @chehak123 
> 
> I have assigned you this issue. Note that you cannot work on more than 2 Issues at a single time. (You already have one)

@HarshCasper I have made a new pull request on this issue.
Can you please review it?

**Comment by HarshCasper** [comment]
> > @Tanmay2510
> > Let us know if you are planning to work on it. If not, please let us know as well, by unassigning yourself. We would appreciate honesty more than just ghosting us out after having an Issue :)
> > @chehak123
> > I have assigned you this issue. Note that you cannot work on more than 2 Issues at a single time. (You already have one)
> 
> @HarshCasper I have made a new pull request on this issue.
> Can you please review it?

Ideally you should link PRs to the Issues you are assigned to. That makes the review process easier and more productive.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
I can do this in GO
