### ISSUE TITLE
Reverse words in a given string , python, cp

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#2122]
## 💥 Proposal

( The program takes a string and prints the words of the string in a reverse order 
The program's example

Input:
S = i like this program very much
Output: much very program this like i
)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(YES)

**Comment by chicken-biryani** [comment]
I would like to work on this under DWOC

**Comment by Sarthak-9** [comment]
I would like to contribute in C and C++. Please assign me.
@shraddhavp

**Comment by chicken-biryani** [comment]
@atarax665

**Comment by ShubhamGupta577** [comment]
I would like to contribute in C, C++, Python. Please assign this to me.

**Comment by AkanshaUniyal** [comment]
Respected Ma'am/Sir, I would like to contribute in this issue using JAVA

**Comment by maanpatel2492** [comment]
I would like to solve this issue today.
(under GSSOC21)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by shloka-gupta** [comment]
I would like to work on this under GSSOC'21

**Comment by HarshCasper** [comment]
@maanpatel2492 @chicken-biryani 

Let us know here on the languages that you are planning to use to solve this Issue

**Comment by shloka-gupta** [comment]
@HarshCasper Python on my end

**Comment by RuchiGitHu** [comment]
> @maanpatel2492 @chicken-biryani
> 
> Let us know here on the languages that you are planning to use to solve this Issue

hi @HarshCasper , I want to solve this issue using java...
Please assign this issue to me under GSSOC 21 using java language.
Looking forward to contribute here....
Thanks in Advance.

**Comment by maanpatel2492** [comment]
> > @maanpatel2492 @chicken-biryani
> > Let us know here on the languages that you are planning to use to solve this Issue
> 
> hi @HarshCasper , I want to solve this issue using java...
> Please assign this issue to me under GSSOC 21 using java language.
> Looking forward to contribute here....
> Thanks in Advance.

c++

**Comment by RuchiGitHu** [comment]
> > > @maanpatel2492 @chicken-biryani
> > > Let us know here on the languages that you are planning to use to solve this Issue
> > 
> > 
> > hi @HarshCasper , I want to solve this issue using java...
> > Please assign this issue to me under GSSOC 21 using java language.
> > Looking forward to contribute here....
> > Thanks in Advance.
> 
> c++

Hi @HarshCasper. Please let me clear that, is you want me to solve this issue using C++ language?
Thanks for your reply...

**Comment by ChetasShree** [comment]
hi @HarshCasper , I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 using python language.
Looking forward to contribute here...

**Comment by yogitasaini** [comment]
please , assign this task to me java under GSSOC'21

**Comment by shloka-gupta** [comment]
Hey, @ChetasShree @yogitasaini 
**It's great to see your enthusiasm and keep up with it**. But the issue has already been assigned, in Python, Java, and C++ to me (@chicken-biryani ), @RuchiGitHu, and @maanpatel2492 respectively.

**It's always a great practice to go through the discussion under an issue**. (i.e the above comments in the top to bottom order) to see whether it has been assigned or not. 

But do not get discouraged. You can always create your own issues (after going through the project and Readme file properly) or grab other issues that have not been assigned in the language of your comfort.

The **process of reading** may feel tedious and boring at first, but it's an **important step.** and you'll get used to it.

I repeat, **do not get discouraged, you are here to learn**. All the best.

**Comment by ChetasShree** [comment]
> Hey, @ChetasShree @yogitasaini
> **It's great to see your enthusiasm and keep up with it**. But the issue has already been assigned, in Python, Java, and C++ to me (@chicken-biryani ), @RuchiGitHu, and @maanpatel2492 respectively.
> 
> **It's always a great practice to go through the discussion under an issue**. (i.e the above comments in the top to bottom order) to see whether it has been assigned or not.
> 
> But do not get discouraged. You can always create your own issues (after going through the project and Readme file properly) or grab other issues that have not been assigned in the language of your comfort.
> 
> The **process of reading** may feel tedious and boring at first, but it's an **important step.** and you'll get used to it.
> 
> I repeat, **do not get discouraged, you are here to learn**. All the best.

ya sure thank you so much @chicken-biryani

**Comment by HarshCasper** [comment]
Thanks for motivating co-contributors @chicken-biryani 

Really appreciate that!

**Comment by kiruba-r11** [comment]
@HarshCasper Can I work on this issue under GSSoC'21 in Kotlin (if Kotlin can be used in this repo). Thanks

**Comment by HarshCasper** [comment]
@kiruba-r11 I don't appreciate the spamming in the repository. If you are dead serious about contributing, create an Issue and then mention me up there. I will not be so appreciative of the exact same request in multiple issues.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by shloka-gupta** [comment]
Hey @guruc-134 same goes for this issue. It has already been assigned. Browse through other issues. Or you can always create your own issues. But make sure you go through the ReadMe file and the discussion under an issue.
