### ISSUE TITLE
Implementation of Queue using Stack

### ISSUE THREAD

**Issue by Meghag5** [HarshCasper/NeoAlgo#2134]
In this algorithm we will use two stack to implement queue.

**Comment by Meghag5** [comment]
Please assign it to me and add tags to this issue.

**Comment by Vrushti24** [comment]
I can also work on this

**Comment by sukritidawar** [comment]
I would like to work on this in C++

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21
