### ISSUE TITLE
Find all divisors of a natural number , Python, CP

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#2136]
## 💥 Proposal

(Given a natural number n, print all distinct divisors of it.
Input : n = 10       
Output: 1 2 5 10
)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(YES)

**Comment by chicken-biryani** [comment]
I would like to work on this, under DWOC

**Comment by chicken-biryani** [comment]
@atarax665

**Comment by sakshi300699** [comment]
Would like to work on this in C++

**Comment by salma2vec** [comment]
I would like to work on this.

**Comment by anirudhsai20** [comment]
Hi. Can you please assign me this issue under DWOC?

**Comment by shloka-gupta** [comment]
I would like to work on this under GSSOC'21

**Comment by Nidhideveloper** [comment]
Please, assign this to me. I want to contribute as a participant of GSSOC'21

**Comment by AkanshaUniyal** [comment]
I want to do this in JAVA. Please assign me this under GSSoC'21

**Comment by HarshCasper** [comment]
@chicken-biryani @Nidhideveloper @AkanshaUniyal 

I have assigned you three this Issue. Please let us know beforehand about the language that you are planning to use to solve this. Thanks!

**Comment by shloka-gupta** [comment]
@HarshCasper Python from my end

**Comment by AkanshaUniyal** [comment]
@HarshCasper  I would like to do that in JAVA

**Comment by Nidhideveloper** [comment]
@HarshCasper I would like to do it in C++

**Comment by Nidhideveloper** [comment]
> @HarshCasper I would like to do it in C++

@HarshCasper Sir, could you please name the file name under NeoAlgo, as I am unable to find it anywhere under c++ or python category. Please sir, as I am very new to onpen source contribution.

**Comment by HarshCasper** [comment]
> > @HarshCasper I would like to do it in C++
> 
> @HarshCasper Sir, could you please name the file name under NeoAlgo, as I am unable to find it anywhere under c++ or python category. Please sir, as I am very new to onpen source contribution.

We are building a Contributor Guideline. Please wait until its ready. 

Ideally it would be available before the Coding Period starts and you can make the PR once the Coding Period starts. It would be great if your fellow contributors @chicken-biryani and @AkanshaUniyal can help you out.

**Comment by ChetasShree** [comment]
hi @HarshCasper , I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 using python language.
Looking forward to contribute here...

**Comment by kiruba-r11** [comment]
@HarshCasper Can I work on this issue under GSSoC'21 in Kotlin. Thanks

**Comment by HarshCasper** [comment]
@ChetasShree You should understand that we don't take duplicated codes. Did you take the chance to go through the above comments and see who is taking the issue on what language. If not, please don't expect us to be so mindful of your requests on every Issue that exists. 

@kiruba-r11 Same applies here. Please don't spam requests on every issue. Instead take the initiative and make an issue.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
I can do this in GO
