### ISSUE TITLE
Implement knapsack fractional problem (GREEDY APPROACH)

### ISSUE THREAD

**Issue by bagladivyang03** [HarshCasper/NeoAlgo#2138]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Implement a knapsack fractional problem using a greedy approach.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES
I will be using C++ to solve this problem.

**Comment by bagladivyang03** [comment]
I would like to work on this issue in C++.
Anyone pls assign me :)

**Comment by nayanajain** [comment]
I would like to work under this issue in java, c++
Please assign this issue to me under DWOC

**Comment by vermatanu** [comment]
I would like to work on this issue in python. Please assign it to me.

**Comment by bagladivyang03** [comment]
@HarshCasper Could u pls assign me this in C++ :)

**Comment by vilsijain** [comment]
Can you assign i have good approach I have done C ,python ,c++
you can merge Fractional Knapsack Problem
