### ISSUE TITLE
Want to add Zig-Zag traversal of Binary Tree under graphs section of C-Plus-Plus.

### ISSUE THREAD

**Issue by tanyarajhans** [HarshCasper/NeoAlgo#2142]
## 🚀 Feature

Zig-Zag traversal of Binary Tree would be a great addition to graphs section of C-Plus-Plus being a famous Binary Tree question both for interviews and coding rounds asked in top companies like Amazon, Microsoft etc.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I am familiar with contributing guidelines on PR. 

## Motivation

I am efficient in Problem Solving using C++ and Java and have solved more than 800 problems on various online judges like GeeksforGeeks, LeetCode, HackerRank etc. You can check my profile here:

https://leetcode.com/tanyarajhans7/
https://auth.geeksforgeeks.org/user/tanyarajhans7/practice/
https://www.hackerrank.com/tanyarajhans7

## Pitch

As we all know, Zig-Zag traversal of Binary Tree continues to be a famous interview question to this day. Adding this problem will make this repository perfect to prepare for DSA interviews and who knows, the reader stumbles upon the very same problem in an interview and later thanks us endlessly?

**Comment by ankan1811** [comment]
I can work on this algorithm in CPP as a part of  GSSoC'21. Please assign it to me.

**Comment by gat786** [comment]
This looks like a plan @tanyarajhans. And a good addition to the repository. Although you might want to check in if there is already the same thing implement here, If not then go ahead and implement it and mention us when you have done so. :-)

**Comment by HarshCasper** [comment]
Hi @TanyaAggrawal 

I have assigned you this Issue in C++ 

@ankan1811 : I could not assign you this Issue because you plan to work on it using C++ itself. @TanyaAggrawal is already working on it. Please take up the Issue in some other language or find another Issue. Thanks!

**Comment by tanyarajhans** [comment]
Hey @HarshCasper, I added this in C++ as you know already, I will also contribute in Java for this problem.

**Comment by HarshCasper** [comment]
Go ahead. 

From next time, please link your PR to this Issue so that its easy for us to track things.

**Comment by gat786** [comment]
Yeah, for some reasons I forgot to assign it to her 🤣 
Even after commenting to get started with it.

**Comment by tanyarajhans** [comment]
@gat786 @HarshCasper I have sent the PR.

**Comment by HarshCasper** [comment]
It would be reviewed after the Coding period starts.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by gat786** [comment]
This issue is taken by tanya :-)
