### ISSUE TITLE
Russian Peasant Algorithm

### ISSUE THREAD

**Issue by nayanajain** [HarshCasper/NeoAlgo#2147]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

It is a special way of multiplying 2 numbers without the use of multiplication operator

**Comment by nayanajain** [comment]
@HarshCasper  Please assign this issue to me
I would like to contribute in c++ under DWOC

**Comment by nayanajain** [comment]
Please merge my PR

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Nidhideveloper** [comment]
@HarshCasper Please assign this issue to me, I would like to contribute in C and JAVA as a participant of GSSOC'21
