### ISSUE TITLE
Implementation on Heaps in Java

### ISSUE THREAD

**Issue by shraiyya** [HarshCasper/NeoAlgo#2148]
## 🚀 Feature

A Heap is a special Tree-based data structure in which the tree is a complete binary tree. A tree is said to be complete if all its levels, except possibly the deepest, are complete. A heap has many applications, including the most efficient implementation of priority queues, which are useful in many applications. Heapsort is a comparison-based sorting algorithm. Heaps are often implemented in an array rather than a linked list.
 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
Please add the DWOC tag and level.

## Motivation

This is a menu-driven code that contains the Implementation of the heap. It has operations like add into a heap, delete an element of a heap, create a heap, and sort a heap.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by asimarise** [comment]
I would like to work on this issue

**Comment by suyashi912** [comment]
Hey,
I would love to complete this task assigned under the mentorship of GSSoc'21. I am proficient in programming in various languages including Java. I promise to deliver on time in case this task in assigned to me. Thanks :)

**Comment by HarshCasper** [comment]
> Hey,
> I would love to complete this task assigned under the mentorship of GSSoc'21. I am proficient in programming in various languages including Java. I promise to deliver on time in case this task in assigned to me. Thanks :)

Hello @suyashi912 👋 

We would work on this once the program would start. You would be working with me, so I promise we would have a nice set of issues where you can put your intellectual skills to test :)

**Comment by HarshCasper** [comment]
> I would like to work on this issue

Please let me know in what language you would like to work. Thanks!

**Comment by asimarise** [comment]
> > I would like to work on this issue
> 
> Please let me know in what language you would like to work. Thanks!

I have also been selected for GSSoC'21. I would probably like to work in C++(but I'm also familiar with Javascript and Python). Thank You
