### ISSUE TITLE
CPU Scheduling algorithms in Java

### ISSUE THREAD

**Issue by sakshikhachane** [HarshCasper/NeoAlgo#2153]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

CPU Scheduling is a process of determining which process will own CPU for execution while another process is on hold. The main task of CPU scheduling is to make sure that whenever the CPU remains idle, the OS at least selects one of the processes available in the ready queue for execution. CPU Scheduler selects one of the processes in memory that are ready for execution.

Will implement -

- [ ] FCFS (First come first serve)
- [ ] RR (Round Robin)
- [ ] SJF (Shortest Job First)
- [ ] SRTF (Shortest Remaining time first)

**Comment by sakshikhachane** [comment]
@atarax665 @HarshCasper Please assign me this issue under DWOC.

**Comment by saaiswetha** [comment]
I would like to take up this issue. I'm a part of GSSOC'21 and would like to contribute.

**Comment by HarshCasper** [comment]
> I would like to take up this issue. I'm a part of GSSOC'21 and would like to contribute.

Hi @saaiswetha 

GSSoC Issues will open in some time. Kindly have patience till then :)

**Comment by sakshikhachane** [comment]
@HarshCasper Should I make individual PRs or make only 1 PR consisting of all algorithms?
