### ISSUE TITLE
Remove minimum parantheses to make Valid Parentheses

### ISSUE THREAD

**Issue by sukritidawar** [HarshCasper/NeoAlgo#2154]
## 🚀 Feature

Given a string of '(' , ')' and lowercase english characters. 

The task is to remove the minimum number of parentheses so that the resulting parentheses string is valid.
A parentheses string is valid if and only if:
1.It is the empty string, contains only lowercase characters, or
2.It can be written as AB (A concatenated with B), where A and B are valid strings, or
3.It can be written as (A), where A is a valid string.

Example:
1. Input: "he((l)l)o)"
   Output: "he((l)l)o"
2. Input: ")))((("
    Output: ""

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Helps in enhancing problem-solving.

## Pitch

Helps in understanding the basics of stacks.

**Comment by sukritidawar** [comment]
I want to work on this issue in c++

**Comment by yashikajotwani12** [comment]
I want to work on this issue . I have solved many questions on strings in c++. please assign me this.

**Comment by nandinib1999** [comment]
I would like to work on this in Python

**Comment by keshav2508** [comment]
I would like to work on this in c++. please assign this to me .

**Comment by HarshCasper** [comment]
@sukritidawar @yashikajotwani12 @nandinib1999 @keshav2508 

Are you all participating in GSSoC '21 ?

**Comment by sukritidawar** [comment]
> @sukritidawar @yashikajotwani12 @nandinib1999 @keshav2508
> 
> Are you all participating in GSSoC '21 ?

yes, I am

**Comment by HarshCasper** [comment]
Welcome Back @sukritidawar ! 

We hope you can build up on your contributions from Contributor's Hack :)

**Comment by sukritidawar** [comment]
> Welcome Back @sukritidawar !
> 
> We hope you can build up on your contributions from Contributor's Hack :)

Yes definitely! 
Thank you :)

**Comment by yashikajotwani12** [comment]
> @sukritidawar @yashikajotwani12 @nandinib1999 @keshav2508
> 
> Are you all participating in GSSoC '21 ?

yes mam!!

**Comment by keshav2508** [comment]
yes i am

**Comment by HarshCasper** [comment]
@yashikajotwani12 @keshav2508 

The Issue is already taken up by @sukritidawar in C++. Please let me know if you plan to work on it in some other language. 

And @yashikajotwani12 please refer me by `he/him` tags :)

**Comment by yashikajotwani12** [comment]
> @yashikajotwani12 @keshav2508
> 
> The Issue is already taken up by @sukritidawar in C++. Please let me know if you plan to work on it in some other language.
> 
> And @yashikajotwani12 please refer me by `he/him` tags :)

I would like to do the same in python. Please assign me .

**Comment by HarshCasper** [comment]
@nandinib1999 I have assigned you this Issue in Python. 

@yashikajotwani12 Please take up this Issue is some other language, since @nandinib1999 claimed it first

**Comment by yashikajotwani12** [comment]
> @nandinib1999 I have assigned you this Issue in Python.
> 
> @yashikajotwani12 Please take up this Issue is some other language, since @nandinib1999 claimed it first

I can implement it in c. May I @HarshCasper

**Comment by HarshCasper** [comment]
> > @nandinib1999 I have assigned you this Issue in Python.
> > @yashikajotwani12 Please take up this Issue is some other language, since @nandinib1999 claimed it first
> 
> I can implement it in c. May I @HarshCasper

Assigned :+1:

**Comment by yashikajotwani12** [comment]
> > > @nandinib1999 I have assigned you this Issue in Python.
> > > @yashikajotwani12 Please take up this Issue is some other language, since @nandinib1999 claimed it first
> > 
> > 
> > I can implement it in c. May I @HarshCasper
> 
> Assigned 👍

Thankyou So much :)

**Comment by DevilAJ** [comment]
@HarshCasper
I would like to work on this issue in Java.
I am a GSSOC '21 participant.
My code will have comment lines to make it explanatory and understandable to everyone.
I will be very happy if I am assigned this issue and allowed to work on this.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by nandinib1999** [comment]
> @nandinib1999 I have assigned you this Issue in Python.
> 
> @yashikajotwani12 Please take up this Issue is some other language, since @nandinib1999 claimed it first

Thanks a lot!
