### ISSUE TITLE
[CP] Check Pangram 

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#2158]
## 💥 Proposal

A pangram is a string that contains every letter of the alphabet.
Example: "The quick brown fox jumps over the lazy dog"
The string contains all letters in the English alphabet, so return pangram.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Languages:
- Java : @AkanshaUniyal
- Python : @chicken-biryani 
- CPP : @ankan1811

**Comment by chicken-biryani** [comment]
@atarax665 I would like to work on this issue under DWOC

**Comment by anirudhsai20** [comment]
Hi. Can you please assign me this issue under DWOC?

**Comment by AkanshaUniyal** [comment]
hey, I want to write this algorithm using JAVA please assign me this under GSSOC'21

**Comment by shloka-gupta** [comment]
I would like to work on this under GSSOC'21

**Comment by ankan1811** [comment]
hey, I want to write this algorithm using C++.Please assign me this under GSSOC'21

**Comment by ChetasShree** [comment]
hi @HarshCasper , I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 using python language.
Looking forward to contribute here...

**Comment by atarax665** [comment]
> hi @HarshCasper , I want to solve this issue using python...
> Please assign this issue to me under GSSOC 21 using python language.
> Looking forward to contribute here...

Hey @ChetasShree,
Sorry, this issue has already been assigned to someone else in python and java, but you can still contribute in any other language you are comfortable with.

**Comment by ChetasShree** [comment]
> > hi @HarshCasper , I want to solve this issue using python...
> > Please assign this issue to me under GSSOC 21 using python language.
> > Looking forward to contribute here...
> 
> Hey @ChetasShree,
> Sorry, this issue has already been assigned to someone else in python and java, but you can still contribute in any other language you are comfortable with.

can I contribute it using c++?

**Comment by ankan1811** [comment]
Hi @atarax665  you have assigned me this in C++ for GSSOC'21 at the top (according to my previous issue which you have closed) but you have forgot  to add me as assignee at the top right corner. Please can you add me as assignee?

**Comment by atarax665** [comment]
> Hi @atarax665 you have assigned me this in C++ at the top (according to my previous issue which you have closed) but you have forgot to add me as assignee at the top right corner. Please can you add me as assignee?

Actually a PR or Issue can only be assigned to anyone who has commented on the issue or pull request, anyone with write permissions to the repository, and organization members with read permissions to the repository. Though I have mention you for CPP in the issue description itself. As you have commented now so I have added you as assignee.

**Comment by ChetasShree** [comment]
> > > hi @HarshCasper , I want to solve this issue using python...
> > > Please assign this issue to me under GSSOC 21 using python language.
> > > Looking forward to contribute here...
> > 
> > 
> > Hey @ChetasShree,
> > Sorry, this issue has already been assigned to someone else in python and java, but you can still contribute in any other language you are comfortable with.
> 
> can I contribute it using c++? @atarax665

**Comment by HarshCasper** [comment]
> > > > hi @HarshCasper , I want to solve this issue using python...
> > > > Please assign this issue to me under GSSOC 21 using python language.
> > > > Looking forward to contribute here...
> > > 
> > > 
> > > Hey @ChetasShree,
> > > Sorry, this issue has already been assigned to someone else in python and java, but you can still contribute in any other language you are comfortable with.
> > 
> > 
> > can I contribute it using c++? @atarax665

The first rule before you ask yourself to be assigned an Issue, is to first check if someone is already working on it. In your case, its C++ and @ankan1811 is already working on it.

Next time, please be specific and state the language you want to work on, after verifying if no one else is working on it.

**Comment by kiruba-r11** [comment]
@HarshCasper Can I work on this issue in Kotlin under GSSoC'21. Thanks
