### ISSUE TITLE
Coin Change Problem Using DP

### ISSUE THREAD

**Issue by harsh7in** [HarshCasper/NeoAlgo#216]
**Algorithm:** Dynamic Programming

**Languages Supported:**
C [@anshul7sh]
C++ [@harsh-9in ]
Java [@Huzaib]
Javascript
Python [@Alifbhanvadiya14]

**Comment by harsh7in** [comment]
@HarshCasper May I work on this issue using C++ ?

**Comment by vgb-codes** [comment]
@harsh-9in Please go ahead with C++.

**Comment by vgb-codes** [comment]
@harsh-9in Have you completed the issue?

**Comment by Nistha-tech** [comment]
@VijayaGB98 Can I work on this issue in C and python ?

**Comment by anshulontech** [comment]
@HarshCasper @VijayaGB98 May I work on this issue using **C** and **Java** ?

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++

**Comment by Alifbhanvadiya14** [comment]
I would like to work on this issue in Python

**Comment by Huzaib** [comment]
Can I take it up in Java?

**Comment by vgb-codes** [comment]
@anshul7sh Go ahead with C.
@YashThakare C++ is already done.
@Alifbhanvadiya14 Go ahead with Python.
@Huzaib Go ahead with Java.
Please follow the contribution guidelines when submitting your contribution.

**Comment by Huzaib** [comment]
# Have you read the Contributing Guidelines on Pull Requests?
### Yes

# Description
This algorithm finds the minimum number of coins required to complete a given sum.
Here each coin is available in infinite number and time complexity is O(length of coins array * sum)

## Checklist
- [x] I have read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and added the link to my code.
## Related Issues or Pull Requests
#216
