### ISSUE TITLE
Merging two Linked List using c

### ISSUE THREAD

**Issue by saimanoharhm** [HarshCasper/NeoAlgo#2171]
I would like to contribute merging two singly linked list code using c language in this project. Could you please assign this for me. @HarshCasper

**Comment by saimanoharhm** [comment]
@gat786 could you pls assign this for me

**Comment by gat786** [comment]
Have fun!

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by Nidhideveloper** [comment]
@gat786 I want to contribute for this as a participant of GSSOC'21

**Comment by gat786** [comment]
Pick an issue or topic for me to assign it to you.
If you want to contribute. Pick a thing which you know and will be comfortable in writing it.

**Comment by Nidhideveloper** [comment]
> Pick an issue or topic for me to assign it to you.
> If you want to contribute. Pick a thing which you know and will be comfortable in writing it.

MERGING TWO LINKED LIST USING C/C++

**Comment by HarshCasper** [comment]
@chehak123 @Nidhideveloper 

I would suggest stopping spamming that you want to work on an Issue everywhere. Both of you have been assigned a couple of Issues. 

I will soon post a thread on how you should make an Issue soon. Thanks!

**Comment by ankan1811** [comment]
I want to do this (Merging two Linked lists) in C++. Can someone please assign it to me?

**Comment by gat786** [comment]
@Nidhideveloper This issue is created by @saimanoharhm for working on it himself. If you are not able to understand such a simple fact. DONT SCREAM IN ALL CAPS AT ME!

**Comment by RritikaG** [comment]
Hey ! @gat786 @HarshCasper  I would like to implement this issue in Java as a part of GSSOC'21. Please assign me this.

**Comment by yogitasaini** [comment]
Please assign this to me in java under GSSOC'21

**Comment by HarshCasper** [comment]
@RritikaG @yogitasaini 

Please make separate Issues for yourself. Its hard to manage individual contributions from a single Issue. Also note that if someone has already made the Issue, and started work on it, it makes no sense for you to do same as well, as we will not accept duplicate contributions.
