### ISSUE TITLE
Singly Linked list, Stack and queue

### ISSUE THREAD

**Issue by saimanoharhm** [HarshCasper/NeoAlgo#2172]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to contribute few codes for singly linked list, stack and queue which is not present in this project using c language. 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes

**Comment by gat786** [comment]
Seems Like a plan to me!
Go ahead and do it!

**Comment by maanpatel2492** [comment]
I would like to solve #2172 issue today.
(under GSSOC21)

**Comment by gat786** [comment]
Well @saimanoharhm has listed that he wants to take this issue. If he is not working on it you can take the issue! 😁

**Comment by saimanoharhm** [comment]
@gat786 Could you pls assign this for me.

**Comment by gat786** [comment]
There you go. But as this is a big issue both you and @maanpatel2492 can work on it together. If you guys wish so. I can assign it to both of you 😁

**Comment by saimanoharhm** [comment]
Ok No problem. Let me know what codes will you do @maanpatel2492  . So, that we don't clash

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by maanpatel2492** [comment]
> Ok No problem. Let me know what codes will you do @maanpatel2492 . So, that we don't clash

Print the Middle of a given linked list
Delete the elements in an linked list whose sum is equal to zero
Delete middle of linked list
Remove duplicate elements from sorted linked list
Add 1 to a number represented as a linked list
Find nth node from the end of linked list
Function to check if a singly linked list is a palindrome
Reverse alternate k node in a singly linked list
Delete last occurrence of an item from linked list
Rotate a linked list.
Delete n nodes after m nodes of a linked list.
Merge a linked list into another linked list at alternate positions.
Write a function to delete a linked list.
Write a function to reverse the nodes of a linked list.

**Comment by maanpatel2492** [comment]
> > Ok No problem. Let me know what codes will you do @maanpatel2492 . So, that we don't clash
> 
> Print the Middle of a given linked list
> Delete the elements in an linked list whose sum is equal to zero
> Delete middle of linked list
> Remove duplicate elements from sorted linked list
> Add 1 to a number represented as a linked list
> Find nth node from the end of linked list
> Function to check if a singly linked list is a palindrome
> Reverse alternate k node in a singly linked list
> Delete last occurrence of an item from linked list
> Rotate a linked list.
> Delete n nodes after m nodes of a linked list.
> Merge a linked list into another linked list at alternate positions.
> Write a function to delete a linked list.
> Write a function to reverse the nodes of a linked list.

Should I start or wait for assign

**Comment by HarshCasper** [comment]
@saimanoharhm @maanpatel2492 

It would be really messy if you are putting one common Issue to solve a lot of problems. I would suggest that you go with creating separate Issue for every problem and making a PR for them individually. 

If you have a solid proposal, make a [Discussion](https://github.com/TesseractCoding/NeoAlgo/discussions) thread, tinker out the details with me and then create Issues. That would ensure that you are on a consistent path. 

As of now, I will close this Issue for everyone.
