### ISSUE TITLE
Implementing Left Rotation in Array using C++

### ISSUE THREAD

**Issue by Pavan-Kumar122** [HarshCasper/NeoAlgo#2176]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
1) I wanted to add a new Feature under C++ section i.e. Left Rotation of array which asked by most of the interviewers and it will be good if we add the algorithm.

2) Yes i've read the contributing guidelines.
## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
We can implement this feature by just using a simple modulo operator for finding the position from where the rotation starts.

**Comment by Pavan-Kumar122** [comment]
@HarshCasper  please assign this issue to me under DWOC , it will be really helpful to students.

**Comment by bagladivyang03** [comment]
@HarshCasper I would like to do in C, So assign me

**Comment by maanpatel2492** [comment]
I would like to solve this issue today.
(under GSSOC21)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21
