### ISSUE TITLE
Segmented Sieve

### ISSUE THREAD

**Issue by harsh7in** [HarshCasper/NeoAlgo#218]
**Algorithm:** Segmented Sieve
 An extension of sieve

**Languages Supported:**
C
C++ [@harsh-9in ]
Java
Python

**Comment by harsh7in** [comment]
@ricardoprins Can I work on this issue using C++.

**Comment by mar-galho** [comment]
Sure!

**Comment by pulkitgovrani** [comment]
@ricardoprins @HarshCasper  Can i work on this in java

**Comment by Jyotika999** [comment]
Can i work in C ?
