### ISSUE TITLE
Enhancement of the README>md file.

### ISSUE THREAD

**Issue by anirudhsai20** [HarshCasper/NeoAlgo#2181]
## 📚 Documentation

(A clear and concise description of what the issue is.)
The README.md file has to be updated by mentioning the listing of this project in DWOC or in any other open source programs. Also there are a lot of grammatical mistakes in the README.md file that needs to be corrected.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.
(Write your answer here.)

**Comment by anirudhsai20** [comment]
Hi @TesseractCoding. Please assign me this issue under DWOC.

**Comment by gat786** [comment]
Which README file are you mentioning here?
Maybe DWOC is closely related to our organisation but this is an altogether a different project. So I'm not sure what you are mentioning here. Although @HarshCasper  can help us both here.

**Comment by gat786** [comment]
And for the grammatical mistakes if you find any be sure to raise a PR for that.

**Comment by HarshCasper** [comment]
Raise a PR for grammatical mistakes. No need of having Issues here. 

For a completely new README, make a proposal on the [Discussions](https://github.com/TesseractCoding/NeoAlgo/discussions)
