### ISSUE TITLE
N Queen Problem in C

### ISSUE THREAD

**Issue by m-code12** [HarshCasper/NeoAlgo#2185]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by m-code12** [comment]
@anushkrishnav @atarax665 @shraddhavp @HarshCasper Can I implement this?

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by HarshCasper** [comment]
@m-code12 DWoC is already over. Are you still planning to work on it for GSSoC '21 ? 

@chehak123 : You already have two Issues under your belt.

**Comment by m-code12** [comment]
> @m-code12 DWoC is already over. Are you still planning to work on it for GSSoC '21 ?
> 
> @chehak123 : You already have two Issues under your belt.

Yes I'll work on it for GSSoC '21.

**Comment by Shreyash41** [comment]
@HarshCasper Hey, I would like to contribute to this N-Queen Problem in C++ and JAVA as well. Please assign it to me.

**Comment by HarshCasper** [comment]
> @HarshCasper Hey, I would like to contribute to this N-Queen Problem in C++ and JAVA as well. Please assign it to me.

Make a separate Issue

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.
