### ISSUE TITLE
Hacker rank 

### ISSUE THREAD

**Issue by saimanoharhm** [HarshCasper/NeoAlgo#2190]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to contribute hackerrank problems using c.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by maanpatel2492** [comment]
I would like to solve #2190 today.
(under GSSOC21)

**Comment by chehak123** [comment]
Hi, i want to contribute as a participant of gssoc'21

**Comment by HarshCasper** [comment]
Too ambiguous to assign. 

I will put up some guidelines on creating Issues soon.
