### ISSUE TITLE
Add algorithims in Rust language

### ISSUE THREAD

**Issue by abhikjain360** [HarshCasper/NeoAlgo#2193]
## 🚀 Feature

Start implementing algorithms in [Rust](https://www.rust-lang.org/)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes ofcourse!

## Motivation

This repo doesn't have it, so I want to add it. Also seems like no one else is working on it.

## Pitch

Rust is growing in popularity, and not as much resources on it compared to C++ or Python. Will be a nice addition to this repo. I enjoy coding Rust (and StackOverflow survey shows that so does most developers who have tried Rust), and want to try this!

### Implementation

Rust ships with an awesome package+project management utility called `cargo`, and it is the recommended way to start coding. So we will need to use it's [workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html) feature. but fret not, I know my way around cargo :smiley: .

This will add a lot more complexity to code than just simply putting all files in a directory, but will make code more organized, readable and usable.

**Comment by gat786** [comment]
Looks like a great idea!
I would suggest look at other languages structure and start building similar for rust. Copy all the important readme files. Create appropriate folder structure and make sure you don't break any regulations or code-of-conducts

**Comment by HarshCasper** [comment]
That's a wonderful pitch @abhikjain360 

Really appreciate your push through to make the project more diverse. I have a question:  Would it be possible for you to work on a proposal of what algorithms are you planning to implement in Rust? 

The advantages of a proposal would be that, I can set a Project Board for you where you can work on the algorithms and you will have the freedom to create Issues, take them up and complete the Project Work. 

We can have a look at an evenly distributed sequence across Easy, Medium and Hard Algorithms. Let me know what you think and you can create a discussion and we can tinker out more details. 

Thanks!

**Comment by abhikjain360** [comment]
Sure! I can write a proposal.

For now I plan to catch up with C++ part, and in the corresponding PR that I created (#2196), you can see that I copied the [`README.md`](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/README.md) from the C++ part, and just changed list to a checklist, with appropriate changes in links. Those links don't work for now as files don't exist yet.

As for deviding the algorithms into Easy, Medium & Hard, we can maybe just reuse the README.md by adding a label (text or emoji) after each algorithm mentioned?

We can talk in more detail if you wish via email (abhikjain360@gmail.com) or discord (mega#0508).

**Comment by gat786** [comment]
To the moon! Baby!

**Comment by gat786** [comment]
Sounds like a plan! Also to include only those links to files for which the implementation has been done. For what I have seen you have copied the cpp Readme's and changed the filenames to match it to their rust counterparts which you are yet to write down. 

Go step by step. Do it One algo at a time but don't provide broken links to things which don't yet exist.

**Comment by stuckinforloop** [comment]
Hey, can I work on the sorting algorithms part. I think I will be able to contribute that in Rust.

**Comment by abhikjain360** [comment]
@neel229 sure!

It's nice seeing others wanting to contribute to the idea! You can start working, but please wait until #2196 get's merged so that you have a ready-made template with you. Then you can start with creating an issue and work on it. Meanwhile you can maybe try get starting with seeing from [C++'s sorting part](https://github.com/TesseractCoding/NeoAlgo/tree/master/C-Plus-Plus/sort), writing your own and then merging it with code base later when PR is merged.

Do read the [`best practices`](https://github.com/TesseractCoding/NeoAlgo/pull/2196/files#diff-40f5196d09cda72eb7de2ff00e99465fd6283310ff6f7e6424e4e7473846b135) guidelines before merging though.

Thanks!

**Comment by stuckinforloop** [comment]
I think I'll wait for the PR to merge.

**Comment by Hamza3226** [comment]
Hello, I am a GSSOC'21 participant and would like to contribute to this project.

**Comment by abhikjain360** [comment]
It seems this feature can not be added at this time, as reviewers are busy. I am closing the issue along with the corresponding PR.
