### ISSUE TITLE
add a .clang-format

### ISSUE THREAD

**Issue by abhikjain360** [HarshCasper/NeoAlgo#2194]
## 🚀 Feature

Easy C++ linting using clang-format

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, ofcourse!

## Motivation

Keeping the best practices guide while coding is extra mental burden, plus people might have preferences and/or habits.

## Pitch

Add a `.clang-format` file, following the guidelines as mentioned in the C++ code's folder. This will ensure that merge requests don't cause conflict and enforce a uniform styling guide without putting the burden to do so on the coder. Maybe we even add as a post git commit hook.

### Drawbacks

This might still not fix the naming convention (snake_case vs camelCase)

### Additional notes

[docs](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) for `clang-format`

**Comment by HarshCasper** [comment]
Great Pitch! 

Thanks for the initiative :)
