### ISSUE TITLE
binary tree basic  implementation in javascript

### ISSUE THREAD

**Issue by Deadbullfrog05** [HarshCasper/NeoAlgo#2202]
I want to code binary tree basic implementation,insertion and deletion in javascript language.

**Comment by vgb-codes** [comment]
@Deadbullfrog05 Please fill out the fields in the template to better understand your proposal.

**Comment by maanpatel2492** [comment]
Hey,I would solve this issue.
(under GSSOC21).

**Comment by vgb-codes** [comment]
@maanpatel2492 Which language? Because it is already solved for some programming languages like Java. @Deadbullfrog05 will take up Javascript.

**Comment by maanpatel2492** [comment]
> @maanpatel2492 Which language? Because it is already solved for some programming languages like Java. @Deadbullfrog05 will take up Javascript.

c++ or python

**Comment by HarshCasper** [comment]
> > @maanpatel2492 Which language? Because it is already solved for some programming languages like Java. @Deadbullfrog05 will take up Javascript.
> 
> c++ or python

Make a seperate Issue. Also have a look before if the code is already present or not. Don't jump on the bandwagon
