### ISSUE TITLE
Implementing Longest increasing subsequence DP problem In Javascript

### ISSUE THREAD

**Issue by noob-26** [HarshCasper/NeoAlgo#2204]
I want to contribute the DP solution of the longest increasing subsequence in JS as part of GSSoC 2021.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
