### ISSUE TITLE
Bogo Sorting in Python

### ISSUE THREAD

**Issue by vybhav72954** [HarshCasper/NeoAlgo#2207]
## 🚀 Feature

Bogo Sort or Moneky Sort a.k.a. Stupid  Sort in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yup

## Pitch

BogoSort, Monkey Sort, or inefficient sort is notoriously famous for being one of the worst sortings algorithms with an infinite upper bound.

And for this very reason, is quite popular. Though completely useless as an algorithm Is a good learning tool at teaching how inefficient an algo could be.

**Comment by vybhav72954** [comment]
I can implement this in other languages as well.

**Comment by HarshCasper** [comment]
Welcome here @vybhav72954 :) 

Are you looking to participate through GSSoC or on your own bidding?

**Comment by ChetasShree** [comment]
hi @HarshCasper , I want to solve this issue using python...
Please assign this issue to me under GSSOC 21 using python language.
Looking forward to contribute here...

**Comment by vybhav72954** [comment]
> hi @HarshCasper , I want to solve this issue using python...
> Please assign this issue to me under GSSOC 21 using python language.
> Looking forward to contribute here...
> 

This is assigned to me already 🙂

**Comment by vybhav72954** [comment]
@HarshCasper Shall I do it in Python only or any other language as well.
