### ISSUE TITLE
Implement Largest Rectangular Area in Histogram Stack C++

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2209]
## 🚀 Feature

I want to contribute to the solution of the Largest Rectangular Area in Histogram in C-Plus-Plus using Stack as part of GSSoC 2021.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

**Comment by ankan1811** [comment]
I want to do this using Divide and Conquer algorithm as a part of GSSoC'21.Please assign it to me.
