### ISSUE TITLE
Implement Banker's algorithm for Operating System in C.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [HarshCasper/NeoAlgo#2211]
## 🚀 Feature

**Banker's algorithm** used to avoid deadlock and allocate resources safely to each process in the computer system. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by Karthik-Nayak98** [comment]
I am a participant in GSSOC21. I would like to implement this code in C.

**Comment by Sarthak-9** [comment]
I want to contribute to this algorithm in C++. Please assign me

**Comment by HarshCasper** [comment]
> I want to contribute to this algorithm in C++. Please assign me

Make a separate Issue.

**Comment by pganguli** [comment]
> ## rocket Feature
> 
> (A clear and concise description of what the feature is.)
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> 
> Yes
> ## Motivation
> 
> (Please outline the motivation for the proposal.)
> ## Pitch
> 
> (Please explain why this feature should be implemented and how it would be used.)

Can you please outline the general premise of Banker's algorithm in the description of your issue?
