### ISSUE TITLE
Implement Bucket Sort in C++

### ISSUE THREAD

**Issue by ShubhamGupta577** [HarshCasper/NeoAlgo#2214]
## 🚀 Feature

Bucket Sort is a sorting technique that sorts the elements by first dividing the elements into several groups called buckets. The elements inside each bucket are sorted using any of the suitable sorting algorithms or recursively calling the same algorithm.
* Use **Scatter-gather approach**. 
* Best case time complexity- **O(n+k)**
* Worst case time complexity-**O(n^2)**

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To add more useful sorting techniques.

## Pitch
Keypoints of bucket sort-
* In bucket sort is that once the elements are distributed into buckets, each bucket can be processed independently of the others.
* It also means that you can sort all of the buckets in parallel with one another.
* Bucket sort is useful when there is a large dataset

**Comment by ShubhamGupta577** [comment]
I want to work on this issue using C++ under GSSOC'21.

**Comment by atarax665** [comment]
Bucket Sort has already been implemented in CPP. You can check it out [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/sort/bucket_sort.cpp).
