### ISSUE TITLE
Bits Manipulation in Cpp

### ISSUE THREAD

**Issue by aakriti1318** [HarshCasper/NeoAlgo#2221]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Knowledge of bits manipulation in doing arithmetic operation will increase the efficiency of the program.

## Pitch

Bits Manipulation is relatively faster in doing arithmetic operations. I would like to contribute to this topic. Could you please assign this for me? @HarshCasper

**Comment by soukarsha122** [comment]
I would like to work on this issue as part of gssoc 21

**Comment by priyanka001tech** [comment]
I also would like to work on this issue as part of gssoc 21
