### ISSUE TITLE
Kahn Algorithm for Topological Sort in C++

### ISSUE THREAD

**Issue by Avash027** [HarshCasper/NeoAlgo#2224]
## 🚀 Feature

Kahn's Algorithm is used for the topological sort of any graph in CPP

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Kahn's Algorithm is an important topic in graph traversal and is knowing how to implement it will help to solve various problems. 

## Pitch

Graph problems are generally lengthy so once implemented here it can be used as a reference later.Having solved more than 500 problems on various coding platforms I can implement this alogrithm

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
