### ISSUE TITLE
Infix to Postfix Expression in C and JAVA

### ISSUE THREAD

**Issue by Meghna180401** [HarshCasper/NeoAlgo#2225]
## 🚀 Feature

I would like to implement Infix to Postfix Expression in C and JAVA as a part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

**Comment by RritikaG** [comment]
@Meghna180401  I would like to contribute the issues in Java as a part of GSSOC'21. Please assign me this.

**Comment by HarshCasper** [comment]
@Meghna180401 

It is highly recommended to do a proper research before you create an Issue. For your information, `Infix to Postfix` already exists for both C and Java. 

[Infix to Postfix in C](https://github.com/TesseractCoding/NeoAlgo/blob/master/C/ds/infix_to_postfix.c)
[Infix to Postfix in Java](https://github.com/TesseractCoding/NeoAlgo/blob/master/Java/ds/Infix_to_Postfix.java) 

Please don't duplicate the Issues and do a background research before you start working on any Issue. Thanks!
