### ISSUE TITLE
Iterative Binary Search in C

### ISSUE THREAD

**Issue by sumitgsh** [HarshCasper/NeoAlgo#2227]
## 🚀 Feature

(A clear and concise description of what the feature is.)
It will help us realise binary search using only pointers
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes 
## Motivation

(Please outline the motivation for the proposal.)
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Realising Binary Search Using Recursion may be difficult for a "First Timer" ,so a Iterative solution will help everyone capture the concept pretty Easily..

**Comment by sumitgsh** [comment]
Would love to work on this issue using C as a part of GsSoc21

**Comment by kiruba-r11** [comment]
@HarshCasper Can I work on this issue in Kotlin under GSSoC'21. Thanks

**Comment by HarshCasper** [comment]
@kiruba-r11 Make a separate issue. Thanks!

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
