### ISSUE TITLE
Wave Sort in C++

### ISSUE THREAD

**Issue by gayatri517** [HarshCasper/NeoAlgo#2228]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Given an array of integers, sort the array into a wave like arrangement, that is A[0 to n-1] is sorted in the form A[0]>=A[1]<=A[2]>=A[3]....

Example : 
               Input:  arr[] = {20 80 40 35 10 15 70}
               Output: arr[] = {80 20 40 10 35 15 70}

                Input:  arr[] = {12 20 45 60 5}
                Output: arr[] = {20 12 60 5 45}
## Motivation

This is a popular interview question and has been asked in Google, Adobe and amazon. This question helps in enhancing the problem solving skills.

## Pitch

This question helps in better understanding of arrays.

**Comment by gayatri517** [comment]
I want to work on this issue in C++ as a participant of GSSOC'21

**Comment by tanvi355** [comment]
Hey! Can i work on this in Java under GSSoC' 21?

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by priyanka001tech** [comment]
As a GSSOC'21 participant I would like to contribute. I can code it in java.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Wave Sort problem using C++
i will write the clean code with  brief commenting and algorithm.

so i would like @HarshCasper  to please assign this project to me :)
