### ISSUE TITLE
Check if a binary tree is a Binary Search Tree in Java.

### ISSUE THREAD

**Issue by Meghna180401** [HarshCasper/NeoAlgo#2229]
## 🚀 Feature

I would like to implement the solution to check if a binary tree is a Binary Search Tree in Java.
I would include test cases,complexities as well as the detailed algorithmic explanation for the same and also the common approach which leads to wrong answers.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by krishmurarka** [comment]
I would like to implement the solution to check if a binary tree is a Binary Search Tree in c++.

pls assign me this issue

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
