### ISSUE TITLE
Jump Search | C

### ISSUE THREAD

**Issue by muthuannamalai12** [HarshCasper/NeoAlgo#2233]
## 🚀 Feature
Implementation of the Jump Search in C
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
It's an interesting algorithm to learn.
(Please outline the motivation for the proposal.)

## Pitch
Jump search or block search refers to a search algorithm for ordered lists.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by muthuannamalai12** [comment]
I would love to work on this issue. Kindly assign me this issue as a part of GSSOC'21

**Comment by tanvi355** [comment]
I would like to implement this algorithm in C++ and java under GSSoC'21

**Comment by vgb-codes** [comment]
@tanvi355 Please create a new issue.
