### ISSUE TITLE
Adjacent Elements Product, Python , CP

### ISSUE THREAD

**Issue by shloka-gupta** [HarshCasper/NeoAlgo#2236]
## 💥 Proposal

( When given an array of integers, we have to find the pair of adjacent elements that have the largest product and return that product.
Example:
input Array = [3, 6, -2, -5, 7, 3]
Output= 21 
for 7 and 3 at position 4 and 5 give largest product. )

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(YES)

**Comment by shloka-gupta** [comment]
I would like to solve this under GSSOC'21, in Python

**Comment by rohanbabbar04** [comment]
I would like to implement the same in C language as a part of GSSOC '21

**Comment by maanpatel2492** [comment]
I would like to solve this under GSSOC'21,in c++

**Comment by tanvi355** [comment]
I would like to work on it in Java under GSSoC'21

**Comment by HarshCasper** [comment]
@rohanbabbar04 @maanpatel2492 @tanvi355 

Make seperate Issues

**Comment by kiruba-r11** [comment]
@HarshCasper I would like to work on this issue in Kotlin under GSSoC'21. Thanks

**Comment by HarshCasper** [comment]
@kiruba-r11 Read the above message

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by shloka-gupta** [comment]
Hey @guruc-134 ! Its great to see your enthusiasm. Keep up with it. However, the issue has already been assigned to me (@chicken-biryani )

I am assuming you are new to open source, so here are a few tips to get you started :

- Its always a good practice to read the discussion under an issue (i.e the comments in top to bottom order). By doing so you will understand whether the issue has been assigned or not.

- Do not get discouraged, you can always create your own issue or browse through other issues.

- Always read the ReadMe file. 

All the reading may seem unnecessary, and boring but its a very important step.

And again, do not get discouraged. We all have started out somewhere. It may feel intimidating at first but once you get a hang of things, it will be fun.

All the best. Keep going.
