### ISSUE TITLE
Addition of Quick Sort in C

### ISSUE THREAD

**Issue by shadowasphodel2919** [HarshCasper/NeoAlgo#2238]
## 🚀 Feature
Addition of quick sort in cp in C language.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
Seeing as so many sorting techniques have been added before quick sort. It will be a valid and noteworthy addition to cp algorithms.

## Pitch
It is a crucial sorting technique and has been asked in many coding interviews.

**Comment by shadowasphodel2919** [comment]
I want to work on this issue as a participant of GSSoC' 21 in C language.

**Comment by vgb-codes** [comment]
@shadowasphodel2919 Go ahead with C.

**Comment by shadowasphodel2919** [comment]
@HarshCasper  I am currently working on this issue is there some complication?
