### ISSUE TITLE
Add Selection Sort Algorithm in Javascript

### ISSUE THREAD

**Issue by Avash027** [HarshCasper/NeoAlgo#2241]
## 🚀 Feature

Selection sort is a basic sorting algorithm 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES
## Motivation

Selection sort is one of the basic algorithms. As javascript is one of the most popular languages this algorithm should be implemented in this language.

## Pitch

After it is implemented it can be used as a reference to learn this algorithm. Having a fair bit of experience in algorithms I can implement this in javascript.

**Comment by d-rat** [comment]
@Avash027
  can you assign me this as I can implement this in javascript.

**Comment by SAY-droid427** [comment]
I would like to implement the selection sort algorithm in C++ and C. Could you assign it to me?

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
