### ISSUE TITLE
Adding Fibonacci Search in C++

### ISSUE THREAD

**Issue by maneprajakta** [HarshCasper/NeoAlgo#2242]
## 🚀 Feature
Adding Fibonacci Search under Search Section in C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I want to contribute to this feature as a part of  GSSoC 2021.

## Pitch

This feature will add one more Searching algorithm to the project which is for sorted arrays.

**Comment by maneprajakta** [comment]
I want to work on this issue.

**Comment by vgb-codes** [comment]
@maneprajakta Go ahead with C++.

**Comment by maneprajakta** [comment]
@vgb-codes  Sure

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?

**Comment by priyanka001tech** [comment]
Hello,
I would like to work on it
