### ISSUE TITLE
Implementation of Stack using queues

### ISSUE THREAD

**Issue by Meghag5** [HarshCasper/NeoAlgo#2244]
## 📚 Documentation

(A clear and concise description of what the issue is.)
The issue is of implementing stack using 2 queues in c++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Assignees
* @Meghag5 : C++
* @DEEPALI-SUK : Python
* @ritvij14 : Java
* @sumitgsh : C

**Comment by Meghag5** [comment]
please assign it to me for GSSOC 2021

**Comment by DEEPALI-SUK** [comment]
I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021. I will implement in C++.
Thank you.

**Comment by siddharth25pandey** [comment]
> I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021. I will implement in C++.
> Thank you.

@DEEPALI-SUK C++ is already assigned. You can work in different language.

**Comment by DEEPALI-SUK** [comment]
Can I try in C or Python?

**Comment by ritvij14** [comment]
@siddharth25pandey can I take this in Java and Go as a part of GSSOC '21?

**Comment by sumitgsh** [comment]
@siddharth25pandey I would love  to work on this issue in C end u can assign @DEEPALI-SUK to work on  python

**Comment by itsnishchay26** [comment]
I would like to contribute to this issue as I have studied this implementation in my 3rd Semester, lately.

It'll be like brushing up my concepts of Stack using queues.

I would like to write code in C++, with proper variable names, comments and indentation.

Please assign me this issue

**Comment by siddharth25pandey** [comment]
> I would like to contribute to this issue as I have studied this implementation in my 3rd Semester, lately.
> 
> It'll be like brushing up my concepts of Stack using queues.
> 
> I would like to write code in C++, with proper variable names, comments and indentation.
> 
> Please assign me this issue

@itsnishchay26 Check [this](https://github.com/TesseractCoding/NeoAlgo/issues/2244#issuecomment-792443207)

**Comment by siddharth25pandey** [comment]
@DEEPALI-SUK , @ritvij14 , @sumitgsh  Assigned. Make sure you follow proper coding and formatting standards. Have a great day ahead.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by siddharth25pandey** [comment]
> I would like to implement the above question in Python, I will write neat and clean commented code
> please assign me this issue under GSSoC 2021

@guruc-134 Python is already assigned to someone.

**Comment by DEEPALI-SUK** [comment]
Please could you tell me, in which folder I can add my code for making a PR?

**Comment by siddharth25pandey** [comment]
> Please could you tell me, in which folder I can add my code for making a PR?

@DEEPALI-SUK As Its an implementation of Queue, Better to include in the ds directory

**Comment by DEEPALI-SUK** [comment]
Sir, kindly review my PR.

**Comment by sakshi012000** [comment]
I want to work on this issue and want to contribute to this. I am a participant of GSSOC 2021. Please could you assign me this issue as a part of GSSOC 2021. I will implement in C++.
Thank you.
