### ISSUE TITLE
Cycle Sort | C

### ISSUE THREAD

**Issue by vieee** [HarshCasper/NeoAlgo#2246]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

I would like to implement cycle sort in C as a part of GSSOC'21. Please assign me this.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by Meghna180401** [comment]
I would like to implement Cycle Sort in Java as a part of GSSOC'21. Kindly assign me.
