### ISSUE TITLE
Merge Sort implementation in Python

### ISSUE THREAD

**Issue by msbuddhu** [HarshCasper/NeoAlgo#2248]
## 🚀 Feature

( Merge Sort is a Divide and Conquer algorithm. It divides the input array into two halves, calls itself for the two halves, and then merges the two sorted halves.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(I want to contribute to the implementation of Merge Sort  in Python.)

## Motivation

(I am new to the Data Structure and Algorithm world. I am implementing all the Data Structure and Algorithm in Python these days.)

## Pitch

(Going through the codebase of NeoAlgo I found that there was no implementation for Merge Sort  in Python section.)

**Comment by siddharth25pandey** [comment]
@msbuddhu Assigned. All the best 👍

**Comment by msbuddhu** [comment]
@siddharth25pandey I have created a PR for issue #2248. Please have a look.

**Comment by siddharth25pandey** [comment]
@msbuddhu Plagiarized PR
