### ISSUE TITLE
Jump search | C++ and Java

### ISSUE THREAD

**Issue by tanvi355** [HarshCasper/NeoAlgo#2249]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Implementation of jump search in C++ and Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
I want to contribute this under GSSoC'21.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
It can add to our knowledge of searching algorithms.

**Comment by iamvs-2002** [comment]
Kindly allow me to implement it in Java as a part of GSSOC'21.

**Comment by HarshCasper** [comment]
@iamvs-2002 Make a separate Issue

**Comment by iamvs-2002** [comment]
> @iamvs-2002 Make a separate Issue

Alright

**Comment by tanvi355** [comment]
@HarshCasper I just saw that this is already implemented in C++ and Java.
So should close this and look for other issues as it will be repeated otherwise ?
