### ISSUE TITLE
Top K frequent elements under heap section in C++.

### ISSUE THREAD

**Issue by tanyarajhans** [HarshCasper/NeoAlgo#2252]
## 🚀 Feature

Wanted to add top K frequent elements under heap, which happens to be a famous interview question in cpp.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

It would be a great addition to the repository and would prove to be really helpful. Also, I want to contribute as a part of GSSoC'21.

## Pitch

It has been a famous interview question on heap and the question can be solved by various other approaches but using heap is the most efficient one.

**Comment by SAY-droid427** [comment]
Can I contribute the code?

**Comment by tanyarajhans** [comment]
Merged #2252
