### ISSUE TITLE
Adjacent Element Product in C

### ISSUE THREAD

**Issue by rohanbabbar04** [HarshCasper/NeoAlgo#2255]
## 💥 Proposal

Find the pair of adjacent elements that have the largest product in a given array and return that product.
Example:
input Array = [3, 6, -2, -5, 7, 3]
Output= 21
for 7 and 3 at position 4 and 5 respectively we get the largest product i.e. 21
Hence it should return 21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by sumitsantape30** [comment]
Hey Please assign me this issue. I'm GSSOC21 participant
