### ISSUE TITLE
StairCase Search

### ISSUE THREAD

**Issue by Akash20x** [HarshCasper/NeoAlgo#2257]
## 🚀 Feature

StairCase search is also commonly known as Search in a Row and Column sorted array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 

## Motivation

Want to add this as it is not covered in repo. 

## Pitch

Want to implement Staircase search in python and want to aware people about this type of search.

**Comment by Akash20x** [comment]
Please assign me this issue as a part of GSSoC'21

**Comment by rohanbabbar04** [comment]
Please assign me this issue in C language as a part of GSSOC'21.

**Comment by Akash20x** [comment]
Please check my pull request

**Comment by Akash20x** [comment]
Sorry I forget to resend pull request, please open it I will send pull request
