### ISSUE TITLE
Arrange numbers in an array such that to form the biggest number 

### ISSUE THREAD

**Issue by Nidhideveloper** [HarshCasper/NeoAlgo#2258]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

This problem is not present in the repo so, I wanted to add this. As well I wanted to contribute to NeoAlgo as a GSSOC'21 participant.

## Pitch

This is a good problem solving question in array, which would enhance the number of good problems present on the site.

**Comment by Nidhideveloper** [comment]
I want to work on this issue in C++, as a participant of GSSOC'21. Please assign this to me.

**Comment by iamvs-2002** [comment]
Kindly allow me to do it in Java.

**Comment by Pranjal9999999** [comment]
I want to work on this issue using c++, as a GSSOC 2021 participant.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by itsnishchay26** [comment]
I would like to contribute to this issue as I have studied this implementation in my last semester.

It'll be like brushing up my concepts of array operations.

I would like to write code in C++, with proper variable names, comments and indentation as a participant in GSSoC'21.

Please assign me this issue as it'll be my first issue to fix in this 3-month open-source journey.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code

please assign me this issue under GSSoC 2021

**Comment by iamvs-2002** [comment]
> Kindly allow me to do it in Java.

@HarshCasper KIndly assign me this issue in Java.
