### ISSUE TITLE
Adding Kadane's Algorithm in Python

### ISSUE THREAD

**Issue by WaderManasi** [HarshCasper/NeoAlgo#2261]
## 🚀 Feature

Dynamic programming - Adding Kadane's Algorithm source code in Python language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

Being part of gssoc'21

### Pitch

It is efficient approach for getting maximum contiguous subarray sum

**Comment by WaderManasi** [comment]
I would like to work on this issue.

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by WaderManasi** [comment]
Thank you assigning @HarshCasper

**Comment by vgb-codes** [comment]
@pallavidhere23 Please create a new issue with preferably one language of your choice.

**Comment by anushka00** [comment]
Hi, I am a gssoc'21 participant and want to contribute in this  great project. I'll write the code  in compliance to all the noted guidelines with proper comments .  I would like to work on this issue.

I will write code in c++ and Java with proper guidelines as stated in the readme file .

**Comment by vgb-codes** [comment]
@anushka00 Please create a new issue with preferably one language of your choice. Please check whether your contribution already exists by using the search functionality before creating your issue.
