### ISSUE TITLE
Check if given number is Armstrong number using normal and recursive methods, using Kotlin.

### ISSUE THREAD

**Issue by ritvij14** [HarshCasper/NeoAlgo#2262]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Checking whether the given number input by user is Armstrong number or not. We will have 2 separate files, one which checks it in the normal method and the other which checks it with recursive method.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes
(Write your answer here.)

## Motivation
I saw these particular pieces of code in the java folder so I thought that it should be there in Kotlin too.
(Please outline the motivation for the proposal.)

**Comment by ritvij14** [comment]
I would like to add these 2 codes for Kotlin as a part of GSSOC '21.

**Comment by ritvij14** [comment]
@HarshCasper a small request could you please change the Java tag to Kotlin tag 😅

**Comment by Alleny244** [comment]
Hello 
I am a GSSOC'21 participant
I would like to contribute in this issue
 I can implement this by both recursive as well as iterative method and with proper comment for better understanding.
I will also add 2-3 testcases for better understanding

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by ritvij14** [comment]
@Coder-Srinivas its already implemented in Java. You can have a look at what codes are there in the Java folder of the repository.

**Comment by Coder-Srinivas** [comment]
@ritvij14 Sure Thank you

**Comment by dhruvinfo28** [comment]
Hey, I would love to contribute by doing the same in C++ under GSSOC2021

**Comment by ritvij14** [comment]
> Hey, I would love to contribute by doing the same in C++ under GSSOC2021

@dhruvinfo28 this issue is only for Kotlin. Check C++ folder and if Armstrong code is not there, create your own issue.
