### ISSUE TITLE
Adjacent Elements Product, C++ , CP

### ISSUE THREAD

**Issue by maanpatel2492** [HarshCasper/NeoAlgo#2263]
## 💥 Proposal

(When given an array of integers, we have to find the pair of adjacent elements that have the largest product and return that product.
Example:
input Array = [3, 6, -2, -5, 7, 3]
Output= 21
for 7 and 3 at position 4 and 5 give largest product.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(YES)

**Comment by maanpatel2492** [comment]
I would like to solve this under GSSOC'21, in C++

**Comment by NithishKumar2000** [comment]
I would like to solve this under GSSOC 2021, in C (or) C++
