### ISSUE TITLE
Pythagoras Theorem Golang [GSSoC]

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#2264]
## 🚀 Feature

Addition of Pythagoras theorem in Golang

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

I want to add Pythagoras theorem in golang.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

It will be under the Maths section and will help increase the number of algorithms in Go

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
