### ISSUE TITLE
Addition of HeapSort in C

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/NeoAlgo#2267]
## 🚀 Feature

Add Heap sort sorting algorithm in C 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

It is a very important sorting technique. And is asked in many coding interviews 
I would like to implement this in C as a part of GSSOC'21. Please assign me this.

**Comment by deek121477** [comment]
Hey, I would love to contribute to this issue as a part of Gssoc'21. Could you plz assign me?

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
