### ISSUE TITLE
Addition of cycle detection in linked list

### ISSUE THREAD

**Issue by sssash18** [HarshCasper/NeoAlgo#2268]
## 💥 Proposal
Addition of hare and tortoise algorithm for cycle detection in linked list
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
YES

**Comment by sssash18** [comment]
I would like to do it as part of GSSOC 2021 for C++

**Comment by pallavidhere23** [comment]
I am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
