### ISSUE TITLE
Kahn's Algorithm

### ISSUE THREAD

**Issue by dhruvinfo28** [HarshCasper/NeoAlgo#2271]
## 🚀 Feature

Kahn's algorithm is an algorithm for finding Topological sort for a graph. Since Topological sort is only possible for a Directed acyclic graph, this algorithm will also have a cycle detection logic. This is a BFS based approach.

### Have you read the [Contributing Guidelines on Pull Requests] 

Yes

## Motivation

I love data structures and algorithms. As a participant of gssoc 2021 I would like to contribute for the same .

## Pitch

The currently available algorithm for topological sort in C++ code base is a DFS based approach and will output some order even if the directed graph is cyclic. This algorithm checks for a cycle also and won't output any order instead will prompt that the graph has a cycle. 
Kindly assign me this under GSSOC 2021

**Comment by guruc-134** [comment]
I would like to implement the above question for Khan's Algorithm in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
