### ISSUE TITLE
Peak element in an Array

### ISSUE THREAD

**Issue by DevilAJ** [HarshCasper/NeoAlgo#2274]
## 💥 Proposal

An array element is a peak if it is NOT smaller than its neighbours. For corner elements, we need to consider only one neighbour. 
I would like to solve this using Divide & Conquer algo.

I would like to implement it in c++
My code will contain proper comments with working discriptions.

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
