### ISSUE TITLE
Jump search Algorithm in Java

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#2277]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)

## Pitch
Would add to a searching algorithm, thereby making it a better one-stop solution for all ds/algos.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by iamvs-2002** [comment]
@HarshCasper Kindly assign me this issue as a part of GSSOC'21.

**Comment by Simi06** [comment]
Can I please have this issue assigned to me under GSSoC'21.

**Comment by bhardwaj-ishita** [comment]
@HarshCasper I would love to contribute to this issue. Kindly assign me this issue as a part of GSSoC'21

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Jump search Algorithm using Java
i will write the clean code with  brief commenting and algorithm.

so i would like @HarshCasper  to please assign this project to me :)

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
