### ISSUE TITLE
Binary Exponentiation

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#228]
**Algorithm:** 

Binary Exponentiation

**Languages Supported:**

C [@iamrajiv ] #239
CPP [@iamrajiv ] #239
Java [@SangeetaMishra] #367
Python [@SangeetaMishra] #367

**Comment by iamrajiv** [comment]
@ricardoprins  I want to work on this issue using C & C++

**Comment by mar-galho** [comment]
Alright!

**Comment by SangeetaMishra** [comment]
@ricardoprins  I want to work on this issue using Java and Python.

**Comment by iamrajiv** [comment]
@SangeetaMishra Sure. I hope you have gone through, https://github.com/TesseractCoding/NeoAlgo#contributing-guidelines

**Comment by Gaurav6982** [comment]
I would like to work on this issue using javascript (js). @plazzy99

**Comment by vatsalkesarwani12** [comment]
> I would like to work on this issue using javascript (js). @plazzy99 

Assigned to you
