### ISSUE TITLE
Check whether a number is palindrome or not.

### ISSUE THREAD

**Issue by Aarushi3113** [HarshCasper/NeoAlgo#2280]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
A **palindrome** number is one that remains the *same* when it's digits are reversed.

I am a GSSOC'21 participant and  would like to implement this code in  Python and C++.
My code will be clean and with proper documentation.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes I have read and understood the Contributing Guidelines on Pull Requests.

**Comment by SAY-droid427** [comment]
I am a GSSOC'21 participant and would like to contribute the code for checking whether a string is palindrome or not using C++ and C.Please assign it to me

**Comment by simarjeet30** [comment]
I am a GSSOC 21 participant and I would love to contribute in it ,I know python , C , C++ well.
and I know data structure well.

**Comment by Omar-Hegazi** [comment]
I am a GSSOC'21 participant and would like to contribute in solving whether a number is palindrome or not. I know Python and C#.

**Comment by vgb-codes** [comment]
@Aarushi3113 specify which language you want to code in (one language).
@SAY-droid427 @simarjeet30 @Omar-Hegazi Please create separate issues. Specify the problem you want to solve. Don't say "I want to solve X" or "I want to solve X using A,B,C languages". Say "I want to solve X using A language".

**Comment by Aarushi3113** [comment]
> @Aarushi3113 specify which language you want to code in (one language).
> @SAY-droid427 @simarjeet30 @Omar-Hegazi Please create separate issues. Specify the problem you want to solve. Don't say "I want to solve X" or "I want to solve X using A,B,C languages". Say "I want to solve X using A language".

I want to write the above mentioned code in Python language.

**Comment by vgb-codes** [comment]
@Aarushi3113 To check whether a number is a palindrome using Python has already been implemented [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/math/Palindrome.py). Hence, I am closing this issue.
