### ISSUE TITLE
Algorithm to find if a graph is Bipartite.

### ISSUE THREAD

**Issue by kedar-s** [HarshCasper/NeoAlgo#2281]
## 🚀 Feature

Java implementation for the algorithm to find if a graph is Bipartite with a full explanation of its concept and implementation details would be added.

I would like to do the java implementation please.
[GSSoC]

**Comment by SAY-droid427** [comment]
I would like to add the algorithm to find if a graph is bipartite or not in C++. Please assign me this issue. [GSSOC'21]

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by guruc-134** [comment]
I would like to implement the above question for Finding out if a given graph is BiPartite or not in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
