### ISSUE TITLE
Algorithm to find "Longest Palindromic Subsequence" (Dynamic Programming) in cpp

### ISSUE THREAD

**Issue by VA-ibh-AV** [HarshCasper/NeoAlgo#2282]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

would like to add "Longest Palindromic Subsequence" Problem Solution Using Dynamic Programming in cpp

**Comment by VA-ibh-AV** [comment]
Kindly assign me this issue as a part of GSSOC'21.

**Comment by SAY-droid427** [comment]
Would like to add the "Longest Palindromic Subsequence" in C++ and C using Dynamic programming as a part of GSSOC'21

**Comment by diksh735** [comment]
Kindly assign this issue to me as a part of GSSOC'21. If you want just the algorithm I can do that or If even the implementation is required I can do that as well.

**Comment by vgb-codes** [comment]
@BullHoN You haven't specified which language you want to work with. Please specify only one language.
@SAY-droid427 @diksh735 Please create separate issues.

**Comment by jainstuti** [comment]
I would like to contribute to this problem in 3 types of solutions(including dp). Please assign it to me as a part of gssoc21.

**Comment by vgb-codes** [comment]
@jainstuti Create a separate issue with details of your contribution and the language you want to work with.

**Comment by VA-ibh-AV** [comment]
@vgb-codes I had specified the language and made the pull request please check

**Comment by HarshCasper** [comment]
@BullHoN Never make a PR until and unless someone assigns you the Issue. Please be nice to us, so that we can be nice to you. Thanks!

**Comment by VA-ibh-AV** [comment]
@HarshCasper sorry, I should have waited, thanks for pointing out

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021
