### ISSUE TITLE
Unbounded knapsack in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2286]
## 💥 Proposal

I would like to add the code for implementing unbounded knapsack in C++ under GSSOC'21.Please assign me this issue.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by diksh735** [comment]
I would like to work on this issue as a part of GSSOC'21.

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the Unbounded Knapsack in Java under GSSoC 2021. I would add comments at regular intervals and write clean code.
