### ISSUE TITLE
Post-order, pre-oder and inorder traversal of a BST in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2288]
## 💥 Proposal

I would like to add the code for post-order, pre-order and inorder traversal of a binary search tree in C++.Please assign this issue to me.[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by diksh735** [comment]
I would like to work on this issue as a part of GSSOC'21. Please assign this issue to me.

**Comment by jainstuti** [comment]
I would like to contribute to this as a part of gssoc21. Please assign it to me.

**Comment by siddharth25pandey** [comment]
@SAY-droid427 Already implemented [here](https://github.com/TesseractCoding/NeoAlgo/tree/master/C-Plus-Plus/graphs)
