### ISSUE TITLE
Word Break Problem in c++

### ISSUE THREAD

**Issue by Meghag5** [HarshCasper/NeoAlgo#2295]
## 📚 Documentation

(A clear and concise description of what the issue is.)
This problem is solved using backtracking in c++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by Meghag5** [comment]
please assign it to me for GSSOC 2021 in c++.

**Comment by vgb-codes** [comment]
@Meghag5 Go ahead with C++.

**Comment by HarshCasper** [comment]
@all-contributors bot please add @Meghag5 for code
