### ISSUE TITLE
[Cpp][Math/Number Theory] Modular Exponentiation

### ISSUE THREAD

**Issue by Nkap23** [HarshCasper/NeoAlgo#2299]
## 🚀 Feature

Modular exponentiation is used to compute pow(n1,n2)%mod (n1^n2%mod) in log(n2) time!

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read the contributing guidelines on PRs

## Motivation

I am a Competitive Programmer and I love Data Structures & Algorithms, I believe this algorithm is one of the basic yet one of the most used algorithms used. I want to contribute and add this algorithm to this repo, so in the future newcomers can refer to it and understand it.

## Pitch

As mentioned, this algorithm computes pow(n1,n2) in log(n2). The normal algorithm would take O(n2) times. This O(n2) is not feasible when n2 is larger than 10^7 or 10^8. So this algorithm is a must when dealing with large numbers!

**Comment by vgb-codes** [comment]
@Nkap23 Go ahead with CPP.

**Comment by Coder-Srinivas** [comment]
Can I implement Modular Exponentiation in Java under GSSoC 2021

**Comment by guruc-134** [comment]
Hi, can i implement this in Python,
I would be writing the algorithm with comments 
can u assign me this issue in GSSoC 2021
