### ISSUE TITLE
Implementing Trie data structure in java and python

### ISSUE THREAD

**Issue by samar08** [HarshCasper/NeoAlgo#2301]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Hi, I am a GSSOC 2021 participant. I want to implement Trie data structure in both python and java. I will provide proper documentation mentioning the uses of trie and provide proper comments and code structure in order to make it understandable to a newbie in coding. 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation
My main aim is to provide proper documentation and implementation of trie data structure in order to make it easy for the freshers to understand easily.
(Please outline the motivation for the proposal.)

## Pitch
This algorithm helps to understand the trie data structure and helps the students to understand its implementation.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by vgb-codes** [comment]
@samar08 Please pick one language you want to work with. Trie has been implemented using Python [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/ds/Trie.py).

**Comment by HarshCasper** [comment]
@samar08 

I am assigning you this Issue in Java.

**Comment by samar08** [comment]
Ok sure, thank you. I will implement it in java.

**Comment by samar08** [comment]
Sorry I closed this issue by mistake. Please assign me this issue.
