### ISSUE TITLE
I want to implement the code for finding the greatest element to the right of each number in the array using stacks in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2307]
## 💥 Proposal

I want to implement the code for finding the greatest element to the right of each number in the array using stacks in C++. Please assign this issue to me. [GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by rohan-kulkarni-25** [comment]
I will like t Work on This issue? Can I or is anyone working on it? I am new here I am a Participant of GSSOC !!

**Comment by SAY-droid427** [comment]
@rohank2502 I am working on it

**Comment by rohan-kulkarni-25** [comment]
Ok @SAY-droid427

**Comment by guruc-134** [comment]
can I implement the python version of the code?

**Comment by Coder-Srinivas** [comment]
Can I implement the same in Java?
