### ISSUE TITLE
Length Of Longest Common Substring C++ (Dynamic Programming)

### ISSUE THREAD

**Issue by maneprajakta** [HarshCasper/NeoAlgo#2308]
## 🚀 Feature

I want to add a solution for Finding the length of common substring between two strings using Dynamic Programming under the dynamic programming section in C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I would like to work on it as a part of GSSOC'21.

## Pitch

An efficient approach to solve this problem is by using DP.

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .

**Comment by Amit366** [comment]
@HarshCasper can I implement it in Java?
