### ISSUE TITLE
Iterative Binary Search in Kotlin

### ISSUE THREAD

**Issue by kiruba-r11** [HarshCasper/NeoAlgo#2312]
## 🚀 Feature

Binary Search is a better searching algorithm than linear search in a sorted collection of elements. I would like to implement the iterative version of it in Kotlin.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES

## Motivation
There are no searching algorithms in the Kotlin directory of this repository, so it just motivated me to add one.

## Pitch
Binary Search algorithm is the most used searching algorithm. Also, it has various uses like finding the first and last occurrence of a key, finding the peak element, etc. Adding this algorithm would help to solve other problems related to it.

**Comment by kiruba-r11** [comment]
@HarshCasper I would like to work on this issue in Kotlin under GSSoC'21. Thanks

**Comment by kiruba-r11** [comment]
@HarshCasper Can I create a folder named `search` inside `Kotlin` to add my binarySearch.kt file into it?

**Comment by kiruba-r11** [comment]
@bhav09 Can you help me out about whether I can create a folder named `search` inside the `Kotlin` directory to add my binarySearch.kt file into it?

**Comment by bhav09** [comment]
@kiruba-r11, you have to follow the same convection as other languages. Yes, you have to make the folder named search inside Kotlin dir.
