### ISSUE TITLE
Length of longest palindromic subsequence in a string using dynamic programming in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2315]
## 💥 Proposal

I would like to add the code for Length of longest palindromic subsequence in a string using dynamic programming in C++.Please assign this issue to me[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

]Yes

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I wish to work on this using C++. Hope to hear back from you . I will give some testcases with proper explanation too.
Thank you .
