### ISSUE TITLE
Improved Bubble Sort

### ISSUE THREAD

**Issue by imsushant12** [HarshCasper/NeoAlgo#2316]
## 🚀 Feature

I want to add improved bubble sort algorithm to make it adaptive.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I would like to work on it under GSSoc'21

## Pitch

This feature will make the bubble sort algorithm adaptive so that its best case complexity will become O(n)

**Comment by HarshCasper** [comment]
Issue Title states: `Improved Binary Search`

Issue Description states: `Improved Bubble Sort`

What exactly will you be doing?

**Comment by imsushant12** [comment]
I will be using a flag variable inside first for loop which will help to keep track if the array is already sorted .  If it is already sorted then it will not enter the inner loop.

**Comment by HarshCasper** [comment]
So what exactly are you trying to achieve here, may I know?

**Comment by imsushant12** [comment]
It won't check further if the array is already sorted on every step (any swaps made). This check is necessary, in order to preserve adaptive property.

**Comment by SrinivasRedyy221** [comment]
Hello Im a participant at GSSoS'21.
I want work on this issue.
please assign it to me.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Improved Bubble Sort using C++

i can make the bubble sort optimized by ADAPTIVE WAY
i will write the clean code with  brief commenting and algorithm.

so i would like @HarshCasper  to please assign this project to me :)

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description and best time complexity .
please assign me this issue.

**Comment by Dhriti-Roy** [comment]
I am a Gssoc'21 participant , I would like to work on it . Kindly assigned it to me.
