### ISSUE TITLE
Tiling Problem 2 x n in C++ and Java

### ISSUE THREAD

**Issue by weirdrag08** [HarshCasper/NeoAlgo#2320]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Given a “2 x n” board and tiles of size “2 x 1”, count the number of ways to tile the given board using the 2 x 1 tiles. A tile can either be placed horizontally i.e., as a 1 x 2 tile or vertically i.e., as 2 x 1 tile.  I would do this algorithm with proper comments.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!
