### ISSUE TITLE
Zero Sum Subarray in C++

### ISSUE THREAD

**Issue by gokulkannan7** [HarshCasper/NeoAlgo#2322]
## 💥 Proposal

I would like to add code for the total number of zero-sum subarrays in a given array which will be submitted in  C++ with proper comments and different solution from brute to optimal.
Pls do assign the issue to me (GSSOC'21)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean  commented code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by gokulkannan7** [comment]
@HarshCasper, I have opened a PR, can u please review it?

**Comment by Simi06** [comment]
Can I contribute to this issue?

**Comment by gokulkannan7** [comment]
@HarshCasper Can u review the changes once?
