### ISSUE TITLE
Doubly Linked List Implementation in C Language

### ISSUE THREAD

**Issue by imsushant12** [HarshCasper/NeoAlgo#2323]
## 🚀 Feature

I want to add implementation of Doubly Linked List in C Language with its common operations like insertion (start, end, any position) , deletion (start, end, any position), traversal etc.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I want to contribute under GSSoC'21.

## Pitch

I could find the implementation of Doubly Linked list in C Language so I want to add this feature using a menu driven program.

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by Abhinaba006** [comment]
I am a GSSOC21 participant, please assign me, I will like to contribute

**Comment by guruc-134** [comment]
Can I implement the Doubly LInked list in Python

**Comment by imsushant12** [comment]
Thankyou for assigning, working on it!

**Comment by prithwirajmitra2001** [comment]
I am a GSSOC participant. Please assign me this project. Wish to work on it

**Comment by vidhi1121** [comment]
i want to work with this project under Gssoc'21

**Comment by priyanka001tech** [comment]
I would like to implement the above problem in c++ under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.
