### ISSUE TITLE
Merge two sorted list in c++

### ISSUE THREAD

**Issue by Meghag5** [HarshCasper/NeoAlgo#2326]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to add the code for Merge two sorted list in linked list in C++.Please assign this issue to me[GSSOC'21]
in this problem we will have to merge two sorted linked list and will have to make a single list.
eg. 
Input: l1 = [1,2,4], l2 = [1,3,4]
Output: [1,1,2,3,4,4]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes.)

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by vidhi1121** [comment]
could you assign it to me i would like to solve it.

**Comment by Meghag5** [comment]
@HarshCasper pls assign it me again i by mistake unassigned it
