### ISSUE TITLE
Implementation of N Queens Problem in Python

### ISSUE THREAD

**Issue by guruc-134** [HarshCasper/NeoAlgo#2333]
## 💥  I would like to implement the N Queens Problem in Python

This problem is to find an arrangement of N queens on a chess board, such that no queen can attack any other queens on the board. The chess queens can attack in any direction as horizontal, vertical, horizontal and diagonal way

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

I would like to implement this using BackTracking

**Comment by siddharth25pandey** [comment]
@guruc-134 Already implemented [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/backtracking/N_Queens.py)
