### ISSUE TITLE
Implementation of N-Queens Problem in Java and JavaScript using Backtracking

### ISSUE THREAD

**Issue by Coder-Srinivas** [HarshCasper/NeoAlgo#2334]
## 💥 Proposal

N-Queens problem, is the total number of way we can place N queens on a NxN Chessboard such that no two Queens kill each other. I would like to implement it in Java and JavaScript using Backtracking.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by siddharth25pandey** [comment]
@Coder-Srinivas Already implemented in Java [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/Java/cp/NQueens.java)
create a different issue for Javascript
