### ISSUE TITLE
Implement Queue Data Strucuture using C++ Language.

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2335]
## 🚀 Feature

I would like to add some New Features to C++ Folder:-

Adding New Queue Folder.
Implementing Queue using Arrays in C++. 

I would like to contribute to this issue under GSSOC'21. Please Assign me this issue.

## Pitch
I didn't see any implementation of Queue Data Structure or any Queue Folder in C++, hence I want to contribute it to this Project.

**Comment by siddharth25pandey** [comment]
@Shreyash41 Already implemented [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/ds/queue.cpp)
