### ISSUE TITLE
Middle Element of LinkedList in JAVA

### ISSUE THREAD

**Issue by Priya730** [HarshCasper/NeoAlgo#2337]
## 🚀 Feature

Program to find the middle element of a LinkedList.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute under GSSoC'21

## Pitch

I would like to add the code to find the middle element of a LinkedList in JAVA under the Data Structures folder of Codes in Java. Kindly assign the issue to me.

**Comment by nitinjaiswal7537** [comment]
@HarshCasper i would like to contribute as an Gssoc participant could you assign me this work
