### ISSUE TITLE
Count the Number of Squares in a Grid ( in all Axis ) in Python and JavaScript

### ISSUE THREAD

**Issue by guruc-134** [HarshCasper/NeoAlgo#2340]
## 💥 I would like to implement the algorithm which finds the number of Squares in a given grid. Using Python and JavaScript

Given a NxM grid we are supposed to find the number of squares present in that grid in **all the possible** axises

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

I will solve this using combinatorics and maths. in Python as well as JavaScript

**Comment by Coder-Srinivas** [comment]
I would like to implement the above problem in Java under GSSoC 2021. I would add comments at regular intervals and write clean code. Please assign this issue to me.

**Comment by guruc-134** [comment]
@HarshCasper  added the programs in python and javascript please review the changes.

**Comment by HarshCasper** [comment]
You have spammed PRs on us. Not something we would appreciate or tolerate.

**Comment by guruc-134** [comment]
@HarshCasper  just to clarify, I dint mean to spam the repo with my PR's I'm a beginner, as I was getting mistakes while merging, I was updating them and then sending PR's with those changes
