### ISSUE TITLE
Painter Partition Problem in Java and JavaScript using Binary Search

### ISSUE THREAD

**Issue by Coder-Srinivas** [HarshCasper/NeoAlgo#2341]
## 💥 Proposal

Painters Partition problem is used to find the minimum cost given to painters to finish painting the houses. I would like to implement this problem in Java and JavaScript using Binary Search.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
I would like to implement the above question in Java, I'll put comments in required areas and write clean code
Can you please assign me this issue under GSSoC 2021.
