### ISSUE TITLE
K Closest Points to Origin (Using Heap)

### ISSUE THREAD

**Issue by paulamib123** [HarshCasper/NeoAlgo#2342]
## 🚀 Feature
I want to add the K closest Points to Origin problem.
Problem Statement:
We are given an Array of points where points[i] = [xi, yi] which represents a point on the X-Y Plane and an integer K, we have to return K points nearest to origin i.e (0, 0).
I will do it in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
I would like to contribute for GSSoC'21.

## Pitch
I would want to add more problems under the Heaps section to make it more diverse.

**Comment by abhinav5481** [comment]
Hi,
I would like to work on this. Could you please assign it to me as part of GSSOC'21
