### ISSUE TITLE
MinMax Algorithm implementation in Java

### ISSUE THREAD

**Issue by Devansu-Yadav** [HarshCasper/NeoAlgo#2344]
## 🚀 Feature

(A clear and concise description of what the feature is.)

I want to add the implementation of the **MinMax Algorithm** in **Java** to find the min and max elements in an array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

Yes.
## Motivation

(Please outline the motivation for the proposal.)

I want to contribute under GSSoC'21
## Pitch

(Please explain why this feature should be implemented and how it would be used.)

I didn't see an implementation of this Algorithm in Java hence I want to contribute it to this Project. This algorithm is used to find the **minimum and maximum elements in an Array** which uses the Divide N Conquer approach.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by Devansu-Yadav** [comment]
@AasthaGoyalgit It has already been assigned to me. U could try looking for other issues or u can create one as well!
