### ISSUE TITLE
Implement Previous Greater Element using Stack in C++ Language.

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2345]
## 🚀 Feature

I would like to Implement the **Previous Greater Element using Stack** in **C++ Language**.
I would Like to Contribute to this under GSSOC'21.

## Pitch

I didn't find this in C++ Language to find Previous Greater element using stack in C++ Language. I would like to contribute to this issue. Please assign me under GSSOC'21.

**Comment by Sakshi0401** [comment]
As a GSSOC'21 participant I would like to contribute. so can I be assigned the issue to work upon?
