### ISSUE TITLE
Implementing Fractional Knapsack in Java and JavaScript

### ISSUE THREAD

**Issue by Coder-Srinivas** [HarshCasper/NeoAlgo#2347]
## 💥 Proposal

Fractional Knapsack is a greedy problem where the values of the items picked should be maximum. I would like to implement this problem in Java and JavaScript. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ireneelizabethsabu** [comment]
Hi,
I am a particpant of GSSOC'21. I would love to implement the Fractional knapsack algorithm in cpp.
Kindly assign this to me.

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
Hey @HarshCasper I have a small doubt regarding pull requests. I have been assigned with multiple issues so when I keep a pull request regarding a particular issue, all the files added for previous pull requests will be seen as additions as they have not been merged. So should I delete those files and create a new pull request or is there any way around?

**Comment by Coder-Srinivas** [comment]
Hey @HarshCasper @atarax665  , I have created a different branch and generated a pull request. Please review it😊.

**Comment by atarax665** [comment]
> Hey @HarshCasper I have a small doubt regarding pull requests. I have been assigned with multiple issues so when I keep a pull request regarding a particular issue, all the files added for previous pull requests will be seen as additions as they have not been merged. So should I delete those files and create a new pull request or is there any way around?

Always make Pull request from a new branch, create a separate branch for each issue and do corresponding changes in that branch itself and then raise a PR.
