### ISSUE TITLE
Job Scheduling to Maximize Profit in Java using Dynamic Programming

### ISSUE THREAD

**Issue by Coder-Srinivas** [HarshCasper/NeoAlgo#2349]
## 💥 Proposal

Job Scheduling Problem is used to pick the right jobs to maximize the end profit. I would like to implement this problem in Java using Dynamic Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by guruc-134** [comment]
I would like to implement the above question in Python, I will write neat and clean code
please assign me this issue under GSSoC 2021

**Comment by Coder-Srinivas** [comment]
Hey @HarshCasper @atarax665 , I have added the code and made necessary changes. Please review it😊.
