### ISSUE TITLE
Wiggle Sort

### ISSUE THREAD

**Issue by aish2002** [HarshCasper/NeoAlgo#2354]
## 🚀 Feature

Given an unsorted array arr , sort the array such that arr[0]<arr[1]>arr[2]<arr[3].. in C++ language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As part GSSOC'21

## Pitch

This algorithm is different from normal sorting. I can implement this in C++

**Comment by AasthaGoyalgit** [comment]
Hey!!

I am interested in this issue in java problems as a GSSOC'21 participant .
I'll be glad to work on this issue.

Thanks!!
