### ISSUE TITLE
Implementation of In-order Traversal in Java

### ISSUE THREAD

**Issue by nagasrihith608** [HarshCasper/NeoAlgo#2358]
## 🚀 Feature
I would like to implement the in-order traversal in Java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
To add a new feature.

Please assign this to me under GSSOC'21

**Comment by singhtaran1005** [comment]
assign me

**Comment by nitinjaiswal7537** [comment]
@HarshCasper  i would like to contribute as an Gssoc participant

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
