### ISSUE TITLE
Implement the code for finding out the index of the first 1 in an array of 0 and 1 using binary search in C++ 

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2359]
## 💥 Proposal

Implement the code for finding out the index of the first 1 in an array of 0 and 1 using binary search in C++ .Please assign this to me.[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by btanisha** [comment]
Hey, I can write the code for this in C, C++ and Java. Please assign this to me.
