### ISSUE TITLE
Sort an array of 0 ,1 , and 2 using dutch national flag Algorithm.

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#2360]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This is a very famous question based on dutch national flag algorithm.Its a classical problem asked in many  interviews.

## Pitch

I didn't see an implementation of this Algorithm in C++ hence I want to contribute it to this Project.I have proficiency in C++.Kindly assign this to me as a part of GSSOC'21.

**Comment by btanisha** [comment]
Hey, I'm a GSSOC participant and I'm confident that I can solve this with proper explanation and an easy-to-understand code. I'm comfortable with C++ and Java. Please assign this to me.

**Comment by abhishek7997** [comment]
Hi, I am a GSSOC 21 participant, having a strong knowledge in C++ and python. I am a 3 star coder on codechef (username: abhishek7997), I can write the code with formatting and comment. Please assign this task to me.

**Comment by HarshCasper** [comment]
It already exists [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp)
