### ISSUE TITLE
Implementation of car fueling problem in c++

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [HarshCasper/NeoAlgo#2362]
💥 Proposal

Implementation of car fueling problem in c++.Kindly assign me this [GSSOC 21].

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Sri-vishnu-r1431** [comment]
I am a GSSOC'21 participant, I wish to contribute to it and I am a beginner to open source development.Kindly assign this to me

**Comment by Abhinaba006** [comment]
I will like to contribute to this issue, I am a GSSOC 21 participant, please assign me.

**Comment by Suvraneel** [comment]
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C language.
Kindly assign me this issue under GSSOC '21...
