### ISSUE TITLE
Inplementation of Depth-first search of trees in C++

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [HarshCasper/NeoAlgo#2363]
💥 Proposal

Implementation of depth-first search in C++.

 Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Pitch**

I didn't see DFS being implemented in C++(graph section). So I want to contribute to this open source project.Kindly assign this to me as a part of GSSOC 21.

**Comment by Amit366** [comment]
@HarshCasper sir can I implement it using Java??

**Comment by HarshCasper** [comment]
@Amit366 Make a separate Issue. Also no "Sir"/"Madam" here. We are all on an equal footing here :)

**Comment by itsnishchay26** [comment]
I would like to contribute to this issue in C++ and I have studied this in my last semester.

Please assign me this issue under GSSoC'21.

I will come up with proper code, variable names, comments and indentation.
