### ISSUE TITLE
Creating a Greeting bot for the project.

### ISSUE THREAD

**Issue by Karthik-Nayak98** [HarshCasper/NeoAlgo#2364]
## 🚀 Feature

I want to add a bot that greets the person when he creates a new issue or a pull request. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by HarshCasper** [comment]
cc: @anushkrishnav @gat786 

Can you have a look?

**Comment by anushkrishnav** [comment]
We prefer saying hello to our contributors by ourselves unless you can make a bot to say hello and add tags to it

**Comment by Karthik-Nayak98** [comment]
Are you telling to create a bot that adds tags as well as greets the person? @anushkrishnav

**Comment by anushkrishnav** [comment]
Greet by adding our link to contributors guideline and at the same time add the tag Proposal

**Comment by gat786** [comment]
Yeah if you are up for it @Karthik-Nayak98 we can assign you the task

**Comment by Karthik-Nayak98** [comment]
Yeah, you can assign this issue. I will try to complete this task.

**Comment by anushkrishnav** [comment]
Here is the link for the [doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing)

**Comment by Karthik-Nayak98** [comment]
> Greet by adding our link to contributors guideline and at the same time add the tag Proposal

The tag 'Proposal' is a label right?

**Comment by gat786** [comment]
Yea

**Comment by anushkrishnav** [comment]
@Karthik-Nayak98 what is the status ? we need it up as soon as possible

**Comment by Karthik-Nayak98** [comment]
I am working on it. Will push it soon.

**Comment by Karthik-Nayak98** [comment]
Should I paste the link for the doc or any certain portion of that?

**Comment by Karthik-Nayak98** [comment]
![github com_Karthik-Nayak98_test-action-repo_issues_47](https://user-images.githubusercontent.com/39642646/111032136-d0b8ca00-8430-11eb-987e-9ce0cdbe36f7.png)

Is this fine? @anushkrishnav

**Comment by anushkrishnav** [comment]
Looks good also try to add this comment 
" To get assigned to this particular issue please use '/assign' "

**Comment by anushkrishnav** [comment]
And we are good to merge also add GSSoc'21 tag

**Comment by Karthik-Nayak98** [comment]
Instead of adding the link of guide to the whole doc. Can we add certain steps so it would be easy for the participants to follow?
example:

- Fork the Repository
- Clone Repository: `git clone https://github.com/<USERNAME>/NeoAlgo.git`
- Enter the Repository: `cd NeoAlgo`
- Set upstream to the original branch using the command 
- `git remote add upstream https://github.com/TesseractCoding/NeoAlgo.git`
-  `git pull upstream master`
- create a new branch with the name issue-<issue-number>
- checkout to the new branch `git checkout issue-<issue-name>`
- make your changes and push the code. `git push origin issue-<issue-number>`
- then make a PR
Is this fine? @anushkrishnav

**Comment by Karthik-Nayak98** [comment]
![github com_Karthik-Nayak98_test-action-repo_pull_49](https://user-images.githubusercontent.com/39642646/111032748-c4823c00-8433-11eb-8fb7-090d568837fc.png)
This is the message for the PR
@anushkrishnav

**Comment by anushkrishnav** [comment]
No let the doc be there. We made that for a reason.
