### ISSUE TITLE
Dijkstra : Shortest Reach

### ISSUE THREAD

**Issue by Amit366** [HarshCasper/NeoAlgo#2365]
## 💥 Proposal

I will be implementing Dijkstra's algorithm to find shortest path. 
I will be using Java. Please assign this issue to me under GSSOC. 

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

(Write your answer here.)

**Comment by itsnishchay26** [comment]
I would like to contribute to this issue in C++ and I have studied this algorithm in my last semester.

Please assign me this issue under GSSoC'21.

I will come up with proper code, variable names, comments and indentation.

**Comment by Suvraneel** [comment]
[C++]
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21...
