### ISSUE TITLE
Implementation of Depth-first search of trees in Java

### ISSUE THREAD

**Issue by Amit366** [HarshCasper/NeoAlgo#2368]
## 💥 Proposal

Implementation of Depth-first search of trees in Java

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

@HarshCasper please assign this issue to me under GSSOC

**Comment by manastole03** [comment]
Hey, I am Manas Tole a GSSOC'21 Participant .
I am having experience in Java Programming language as well as I am doing Competitive programming.
Please assign this issue to me :)

**Comment by nupurrajal** [comment]
Hey there,
If this issue is still unassigned, I would like to work on it.

**Comment by Suvraneel** [comment]
[C++]
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me this issue under GSSOC '21...
