### ISSUE TITLE
Krishnamurthy Number 

### ISSUE THREAD

**Issue by Somparna-c** [HarshCasper/NeoAlgo#2369]
## 🚀 Feature

I would like to write a program in C++ to find whether a given number is a Krishnamurthy number. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation 

To contribute to this project as a participant of GSSOC'21.

**Comment by nitinjaiswal7537** [comment]
@Somparna-c  i would like to contribute to it as an Gssoc participant

**Comment by Zeo-shark** [comment]
@Somparna-c  I would like to contribute to your repo by solving this issue kindly assign it to me

**Comment by vgb-codes** [comment]
@Somparna-c Go ahead with C++.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by priyanka001tech** [comment]
Hi,
I would like to work on this issue in c . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
