### ISSUE TITLE
Adding Code to find the number of occurrences of an element in an array in C++

### ISSUE THREAD

**Issue by noob-26** [HarshCasper/NeoAlgo#2370]
I want to add the program to find the number of occurrences of an element in an array using binary search in C++ as part of GSSoC 2021.

**Comment by nitinjaiswal7537** [comment]
@noob-26  could you assign it to me i would like to solve it

**Comment by itsnishchay26** [comment]
I would like to contribute to this issue in C++.

Please assign me this issue under GSSoC'21.

I will come up with proper code, variable names, comments and indentation.

**Comment by ritesh1731** [comment]
I would like to contribute to this issue under GSSOC21. Can you please assign me?

**Comment by vidhi1121** [comment]
I would like to contribute to this issue in C++.

**Comment by HarshCasper** [comment]
Too layman!
