### ISSUE TITLE
[GSSOC'21] String Algorithms

### ISSUE THREAD

**Issue by manastole03** [HarshCasper/NeoAlgo#2377]
## 💥 Proposal

Hey, I am Manas Tole a GSSOC'21 Participant. I am having experience in java Coding as well as I am doing Competitive coding in the java programming language.
I want to add some the below mentioned algorithms in this project with Java Programming language :

1)Program to find that String palindrome.
2)Program for String reversal .
3)Program to remove Duplicates from string.
4)Program for String rotation .
5)Program to remove White spaces from string.
6)Program to check that string is Palindrome or not.
7)Program to check that string is Anagram or not.
8)Program for String to Integer conversion
9)Program for Integer to String conversion
10)Program to Count vowels and consonants
11)Count the number of occurences
12)Program to generate all possible valid IP addresses from given string.
13)World Wrap Problem
14)Balanced Parenthesis problem

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes, I read. 

Please assign this task to me :)
Thank-you

**Comment by vgb-codes** [comment]
Please refer to the guidelines detailed [here](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit).
