### ISSUE TITLE
Infix to Prefix in C

### ISSUE THREAD

**Issue by taruni-always** [HarshCasper/NeoAlgo#2381]
## 🚀 Feature

I want to add the code for Infix to Prefix expressions in C.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute under GSSoC 2021

## Pitch

I was able to find the code for infix to postfix but not for infix to prefix expressions in C language. Please assign this to me.

**Comment by Na2001** [comment]
can you assign convertion of infix to postfix and expression evaluation in C

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute this algorithm using C
with detailed commenting and explained algorithm 

I have read the Contributing Guidelines on Pull request 

so i would like @HarshCasper  to assign this project to me :)

**Comment by taruni-always** [comment]
@HarshCasper , I have written the code, added the link to the README file and then raised a PR. However, the changes in readme file are not being reflected. I was working on another issue in the same project and I think I added the link in the wrong branch. I apologise for this. Please tell me what to do.

**Comment by taruni-always** [comment]
#2657 Please review this

**Comment by taruni-always** [comment]
Please add the level labels for this.
