### ISSUE TITLE
List out prime numbers

### ISSUE THREAD

**Issue by kanchi12P** [HarshCasper/NeoAlgo#2382]
## 🚀 Feature

To list prime numbers from given numbers from 1 to n

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I want to contribute as a GSSoC'21 participant

## Pitch

can be used to shorten the code for any problem where  prime numbers are to be listed out.

**Comment by kanchi12P** [comment]
please assign it to me

**Comment by ankan1811** [comment]
I want to do this in C++ as a GSSoC participant

**Comment by gat786** [comment]
This is a very vague issue filed
