### ISSUE TITLE
Infix, Prefix, Postfix Notation Conversions [C++]

### ISSUE THREAD

**Issue by Suvraneel** [HarshCasper/NeoAlgo#2384]
## 🚀 Feature
I wish to implement these in [C++] ... Please assign me these
1. Infix to Postfix Conversion
2. Postfix evaluation
3. All other possible notation conversions utilising stack.

## Motivation
Highlighting applications of Stacks
**Note- The ones inside code folder of NeoAlgo/C++/stack are in C language & not in CPP language**

**Comment by Simi06** [comment]
I want to implement these. please assign this to me.

**Comment by HarshCasper** [comment]
Don't make one issue for a lot of codes you are trying out. Also some of them are already implemented.
