### ISSUE TITLE
Merge Sort in O(1) space complexity  in C language

### ISSUE THREAD

**Issue by rohanbabbar04** [HarshCasper/NeoAlgo#2388]
## 🐛 Bug Report
https://github.com/TesseractCoding/NeoAlgo/blob/master/C/sort/mergesort_in_O(1)_space_complexity.c
Line 7: The declaration of the function void swap() is incorrect.
Line 15: Min is not declared(no inbuilt minimum function in C).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by rohanbabbar04** [comment]
I would like to correct this issue

**Comment by vanshika2906** [comment]
I would like to work on this issue. Kindly assign it to me. Thank You!
