### ISSUE TITLE
Polynomial Arithmetics using Linked List in C++

### ISSUE THREAD

**Issue by Suvraneel** [HarshCasper/NeoAlgo#2389]
## 🚀 Feature

Please assign me these issues under GSSOC '21 :
1. Polynomial Addition
2. Polynomial Substraction
using linked lists...

CPP language   [C++]

**Comment by Na2001** [comment]
hey can i do this in c.Addition and multiplication.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Polynomial Arithmetics using Linked List using C++
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @HarshCasper  , @bhav09  to please assign this Issue to me :)

**Comment by Suvraneel** [comment]
P.S~ My other issues are done... I'm still here for the assign 🙂 I even have the program made in C++🖤

**Comment by Lza-etc** [comment]
Hi
Would you mind me assigning to solve this issue.
I would like to contribute in Polynomial arithmetics using Linked list in cpp.

**Comment by ankitaggarwal23** [comment]
> Hi
> Would you mind me assigning to solve this issue.
> I would like to contribute in Polynomial arithmetics using Linked list in cpp.

@Lza-etc  Actually Someone else is already working on C++.  Can't assign you in C++.

**Comment by Suvraneel** [comment]
@ankitaggarwal23  As you can see, this was initially raised by me but I had 3 assigned ones at that time (all merged 🖤)... 
Can you now assign me this in Java... (Since someone has already been assigned C)
