### ISSUE TITLE
Sparse Matrix Representation using Linked List

### ISSUE THREAD

**Issue by aish2002** [HarshCasper/NeoAlgo#2391]
I'm a GSSOC'21 Participant
## 🚀 Feature

I can implement Sparse Matrix Representation using Linked List in C language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

Memory efficiency

## Pitch
Sparse matrices can be represented efficiently using linked lists without wastage of memory.

**Comment by kirtijha014** [comment]
Hello maintainers!
As a participant/CA for GSSOC '21,
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21...

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
