### ISSUE TITLE
Smallest element to the right of each element using stack in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2393]
## 💥 Proposal

I would like to add the code to implement the smallest element to the right of each element using stack in C++. Please assign this issue to me.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES

**Comment by srisatya12** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21
