### ISSUE TITLE
Find the maximum element in Bitonic array.

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#2395]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I would like to provide a proper explanation and clean code for finding the maximum element in a Bitonic array in C++.

Computation time complexity reduces to O( logn ) .

Kindly assign this issue to me [GSSOC'21] as I can provide a clear documentation for the same.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by srisatya12** [comment]
I want to contribute to this issue. Please assign me this task as a part of GSSoC'21

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
