### ISSUE TITLE
Construction of Binary Tree From it's preorder and inorder traversal in C

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/NeoAlgo#2396]
## 🚀 Feature

Constructing a binary tree given it's preorder and inorder traversal in c

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

It is a classic problem in data structures and is asked in many coding interviews
I would like to implement this in C as a part of GSSOC'21. Please assign me this

**Comment by Suvraneel** [comment]
[C++]
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me this issue under GSSOC '21...

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Construction of Binary Tree From it's preorder and inorder traversal using C
i will write the clean code with  brief commenting and algorithm.

so i would like @HarshCasper  to please assign this project to me :)
