### ISSUE TITLE
Level Order in BST

### ISSUE THREAD

**Issue by Suvraneel** [HarshCasper/NeoAlgo#2397]
## 🚀 Feature

Implementing:
level order traversal 
finding height of the BST

 in C language and CPP language

## Assignment

Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me these issues under GSSOC '21...

**Comment by srividhya14** [comment]
I am a GSSOC21 participant I would like to contribute this issue by coding preorder, inorder , levelorder ,postorder traversal in c++

**Comment by prithwirajmitra2001** [comment]
I am a GSSOC21 participant and wish to work on this issue

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by HarshCasper** [comment]
Break down this into multiple Issues. Also some of them are already implemented.

**Comment by hritikkhurana10sm** [comment]
Hi, I am Hritik Khurana , I would like to work on this issue in C++ . Could you please assign it to me as a GSSOC'21 participant?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by srividhya14** [comment]
Hello @HarshCasper 

> I am a GSSOC21 participant I would like to contribute this issue by coding preorder, inorder , levelorder ,postorder traversal in c++

Hello maintainers! I checked out the repo and I found level order hasn't been included yet in C++  and in C. I request you to kindly assign me this issue. I have read contributing guidelines on pull requests.

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by Diksha-11** [comment]
Hello I'm Disksha, I'm also a gssoc'21 participant.
I will work on this issue in C++
Thus,  I request @anushkrishnav to please /assign me this issue.

**Comment by anushkrishnav** [comment]
@Diksha-11 please make your own issue on what you think you should work and assign it using the bot but make sure its not already there

**Comment by Jaagrav** [comment]
> @Diksha-11 please make your own issue on what you think you should work and assign it using the bot but make sure its not already there

@anushkrishnav, you should really mention how beginners can do this, they wouldn't know the bot commands right? Add the commands to CONTRIBUTING.md

**Comment by Jaagrav** [comment]
> @Diksha-11 please make your own issue on what you think you should work and assign it using the bot but make sure its not already there

After creating an issue, comment `/assign` to assign the issue to yourself, GitHub actions not would assign you automatically.
