### ISSUE TITLE
Depth First Search Python

### ISSUE THREAD

**Issue by soumyavemuri** [HarshCasper/NeoAlgo#2398]
## 🐛 Bug Report

Currently, the depth first search code written in Python code is incorrect. The [code ](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/search/dfs.py)under DFS is actually that of Breadth-First Search. 

I am a GSSoC Participant, I would like to work on adding the Depth First Search Implementation in Python please.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by prithwirajmitra2001** [comment]
I am a GSSCO 21 participant. Would like to work on this issue

**Comment by LazySukanta** [comment]
I would like to contribute, Assign me for this project as I am GSSOC (participate)2021.

**Comment by soumyavemuri** [comment]
@ankitaggarwal23 Please assign the level label to my contribution whenever possible for you. Thank you!

**Comment by ankitaggarwal23** [comment]
Our team is working on this. don't worry we will assign.
