### ISSUE TITLE
Is Graph Cyclic in Java

### ISSUE THREAD

**Issue by Nivedita967** [HarshCasper/NeoAlgo#2404]
## 💥 Proposal

I would like to add code for "Is Graph Cyclic" in Java with proper comments.
Please assign this issue to me under GSSOC.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by anushkrishnav** [comment]
We already have [Directed graph cyclic Detection](https://github.com/TesseractCoding/NeoAlgo/blob/master/Java/graphs/DirectedCycleDetection.java)
