### ISSUE TITLE
Merge Sort in C#

### ISSUE THREAD

**Issue by Omar-Hegazi** [HarshCasper/NeoAlgo#2407]
## 💥 Proposal

I would like to add code for Merge Sort algorithm which will be submitted in C# with proper comments and an explanation of the solution as part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by vgb-codes** [comment]
@Omar-Hegazi Go ahead with the assigned issue.
