### ISSUE TITLE
Subset sum problem

### ISSUE THREAD

**Issue by NitiKaur** [HarshCasper/NeoAlgo#2408]
Please let me work on this problem in c++ using DP
Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum. 

I have read the contribution guidelines

**Comment by vgb-codes** [comment]
@NitiKaur Go ahead with the issue.

**Comment by Meghna180401** [comment]
I would like to implement the solution to the same problem #2408 in Java.
@vgb-codes Please assign me this.

I have read the contribution guidelines.

**Comment by SrinivasRedyy221** [comment]
hello im participant at GSS0C'21.
i can solve it in c++'
please assign it to me.

**Comment by NitiKaur** [comment]
@SrinivasRedyy221  already requested by me. Plz find some other issue! :)
