### ISSUE TITLE
HeapSort C, Java, Python

### ISSUE THREAD

**Issue by Aleena-Ashraf** [HarshCasper/NeoAlgo#2409]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

This is a very potential question in coding. Being a part of the GSSOC'21, I would like to implement this in C or Java, or Python.
Please do assign this to me.

**Comment by banshita209** [comment]
I am a GSSOC participant.

I'll like to implement Heap Sort in Java 

please assign it to me.

**Comment by Swetha126** [comment]
Hello! I am a GSSOC'21 participant. I have read the guidelines clearly. 
I am proficient in C and Python and would like to implement Heap sort in the same.
I will make my code easily understandable by adding appropriate comments and add the time complexity of the program as well. Please assign me this issue

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
Yes,I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by Komal-99** [comment]
Hi,
Yes i have read the contribution guidelines on pull request 
Would like to add Python heap sort  function , Kindly assign it to me
Thanks

**Comment by HarshCasper** [comment]
Don't propose multiple languages in one single Issue
