### ISSUE TITLE
Optimizing Sieve of Eratosthenes

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#241]
The code for `Sieve of Eratosthenes` program in `C` and `CPP` is not efficient and can be improved much by using `boolean` instead of `int` also using dynamic array will help in for the large value of `n`.

**Comment by iamrajiv** [comment]
@ricardoprins I would like to work on this. Should I make new `Sieve of Eratosthenes` file or should make changes to the existing file?

**Comment by mar-galho** [comment]
I believe that, for the learning process, you should add your code under the existing file, making comments on why the changes are good for the code.

Are you aware about the variations on the Sieve of Erastosthenes? If you could implement them as well it would be great :)

I'll try to also add other sieves to other languages - I've added my code for the Sieve of Atkin in Java

**Comment by atarax665** [comment]
@iamrajiv Are you working on this issue in C ?

**Comment by iamrajiv** [comment]
@atarax665 You can work on this in C. Also, for reference, I have added CPP code in #243

**Comment by iamrajiv** [comment]
@atarax665 You can work on this in C. Also, for reference, I have added C++ code in #243

**Comment by mar-galho** [comment]
Great!

**Comment by rutujadhanawade** [comment]
I would like to work on this issue in C as a part of woc.

**Comment by rutujadhanawade** [comment]
I have a doubt, should I create a new file or just make changes in an existing file?

**Comment by iamrajiv** [comment]
@rutujadhanawade Make changes to the same file and add this approach in that with proper comments for reference take a look of this #243.
