### ISSUE TITLE
Minimum Number of Jumps

### ISSUE THREAD

**Issue by NitiKaur** [HarshCasper/NeoAlgo#2410]
Please assign this issue to me.I want to work on it in C++ using DP
There are various follow ups to this problem and I want to work on all of them
Here is the description
Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
