### ISSUE TITLE
Calculator using swing in java

### ISSUE THREAD

**Issue by Na2001** [HarshCasper/NeoAlgo#2412]
Calculator using swing in java.can you assign this to me.

**Comment by Alleny244** [comment]
Hey, I am a GSSOC'21 Participant .
I am having experience in Java Programming language as well as I am doing Competitive programming.
Please assign this issue to me :)

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by HarshCasper** [comment]
We don't work on GUI Apps.
