### ISSUE TITLE
Golang Algorithms

### ISSUE THREAD

**Issue by fomalhauting** [HarshCasper/NeoAlgo#2414]
## 🚀 Feature

I would like to work on a few basic Golang algorithms

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Increase in algorithms in Golang

## Pitch

Flyod's Triangle
Pascal's Triangle
Pyramid of Numbers
Palindrome

**Comment by HarshCasper** [comment]
Make separate Issues. Thanks!
