### ISSUE TITLE
Check whether a given string is palindrome using doubly linked lists

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2420]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
We can check whether a given string is palindrome or not using doubly linked list data structure
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This is a very potential question in coding. Being a part of the GSSOC'21, I would like to implement this in C or Java, or Python.
Please do assign this to me.

**Comment by Swetha126** [comment]
Hey! I am a GSSOC'21 participant 
I would like to give the code for checking whether the given string is a palindrome using Python with appropriate comments and the time and space complexity.
Please do assign this to me.

**Comment by Swetha126** [comment]
Hey @HarshCasper ! I have completed coding and have opened a pull request. Do have a look at it and let me know the changes if any. Thank you!
