### ISSUE TITLE
Program to reverse the content of queue in stack

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2421]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
Hereby using the code ,one can reverse the content of queue using Stack data structure
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This is a very potential question in coding. Being a part of the GSSOC'21, I would like to implement this in C or Java, or Python.
Please do assign this to me

**Comment by prithwirajmitra2001** [comment]
I am a GSSOC 21 participant. Wish to work on this issue

**Comment by pankaz20** [comment]
Yes,I have read the contribution guidelines.
And,I want to work on this issue as a gssoc21 participant.

**Comment by Alleny244** [comment]
@HarshCasper  Since I have the issues resolved can this issue be reassigned to me 
since Issues will be assigned on a first come, first serve basis. as per the guidelines
