### ISSUE TITLE
Priority Queue in C

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2422]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
To Implement a Priority Queue using arrays in C
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This is a very potential question in coding. Being a part of the GSSOC'21, I would like to implement this in C .
Please do assign this to me

**Comment by Swetha126** [comment]
Hey! I am a GSSOC'21 participant.
I have read the guidelines clearly.
I would like to implement  following functions in priority queue using C with clear comments : 
 1. Heapify the tree
 2. Insert an element into the tree 
 3. Delete an element from the tree

Please do assign this to me

**Comment by Suvraneel** [comment]
[C++]
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me this issue under GSSOC '21...

**Comment by HarshCasper** [comment]
You already have a lot of issues under your belt @Alleny244 

Assigned to @Suvraneel

**Comment by Alleny244** [comment]
@HarshCasper  Since I have the issues resolved can this issue be reassigned to me 
since Issues will be assigned on a first come, first serve basis. as per the guidelines

**Comment by Suvraneel** [comment]
@Alleny244  I've been resolving 2 issues too (1 merged)... working on this one now ...
