### ISSUE TITLE
Improving Linked List in JavaScript

### ISSUE THREAD

**Issue by TidbitsJS** [HarshCasper/NeoAlgo#2428]
## Dynamic Linked List

The task is to improve the present Linked List program & make it dynamic.
 We can improve it in this way -
1. Take user input for addition deletion & display nodes
2. Display linked List
3. Append an element in Linked List
4. Prepend an element in Linked List
5. Insert an element at any given position in the Linked List
6. Delete any element of the Linked List
7. Reverse the Linked List
8. Get the size of the Linked List 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by TidbitsJS** [comment]
I would like to work on this @HarshCasper 
Assign this to me as a part of the GSSOC event

**Comment by HarshCasper** [comment]
Break down your Issue into multiple separate issues.
