### ISSUE TITLE
Sparse Matrix

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2430]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
program to efficiently represent a sparse matrix
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Being a part of the GSSOC'21, I would like to implement this in java and in C  .Please do assign this to me

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by Alleny244** [comment]
@HarshCasper I have uploaded the code from another branch and made a pull request
https://github.com/TesseractCoding/NeoAlgo/pull/2527

**Comment by Na2001** [comment]
Can I do this please :)

**Comment by AasthaGoyalgit** [comment]
Can i work on this in java?

**Comment by Alleny244** [comment]
@HarshCasper have made the required changes

**Comment by Alleny244** [comment]
@HarshCasper I have opened a new pull request
https://github.com/TesseractCoding/NeoAlgo/pull/2857
But its shows DeepSource: Java (beta) Failing after 8s — Analysis Failed: Issues detected that need attention. this error
Everyone is facing this issue 
PLEASE TRY TO RESOLVE THIS ISSUE .ITS A BUG I GUESS
