### ISSUE TITLE
first-fit, best-fit and worst-fit memory allocations (Dynamic Memory Allocation)

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2431]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
To Simulate first-fit, best-fit and worst-fit memory allocations in java and c
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Being a part of the GSSOC'21, I would like to implement this in java and C .Please do assign this to me

**Comment by HarshCasper** [comment]
This Issue is for Java only as of now

**Comment by Alleny244** [comment]
@HarshCasper 
To which directory in the java folder this code should be pushed ?
Is it under 'ds' or 'others'

**Comment by Alleny244** [comment]
I have pushed the code and made the pull request
https://github.com/TesseractCoding/NeoAlgo/pull/2766

**Comment by Alleny244** [comment]
@HarshCasper I have opened a new pull request
https://github.com/TesseractCoding/NeoAlgo/pull/2858
But its shows DeepSource: Java (beta) Failing after 8s — Analysis Failed: Issues detected that need attention. this error
Everyone is facing this issue 
PLEASE TRY TO RESOLVE THIS ISSUE .ITS A BUG I GUESS
