### ISSUE TITLE
Graphics Programs in C (using graphics.h)

### ISSUE THREAD

**Issue by Suvraneel** [HarshCasper/NeoAlgo#2432]
## 🚀 Feature

Graphics & Animation Programs utilising a simple primitive header (graphics.h) in C language...
Includes :
Ball bouncing off edges of screen.

## Assignment
Hello maintainers!  
As a participant/CA for GSSOC '21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C.
Kindly assign me these issues under GSSOC '21...

**Comment by HarshCasper** [comment]
Break this down into multiple separate Issues.

**Comment by Suvraneel** [comment]
> Break this down into multiple separate Issues.

@HarshCasper 
In that case , I'm editing it to "Ball bouncing off edges of screen" only.[C language]
Please assign me
