### ISSUE TITLE
Basic Mathematics Problems in Golang

### ISSUE THREAD

**Issue by BeAgarwal** [HarshCasper/NeoAlgo#2434]
## 🚀 Feature

**Description**
I want to several basic Mathematics problems in Golang

- [ ]  Sieve of Eratosthenes
- [ ]  Palindrome Number
- [ ]  Ugly Number
- [ ]  Extended Euclidean Algorithm

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read the Contributing Guidelines.

## Motivation

I want to excel in the Golang language so I want to work with Golang.

Please assign this to me.

**Comment by HarshCasper** [comment]
Break this down into multiple separate Issues.
