### ISSUE TITLE
User-Defined  Exceptions

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2438]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
A Java program that shows how to create a user-defined exception.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by HarshCasper** [comment]
We don't show language-specific implementations but rather focus on the Data Structures and Algorithm side of things.
