### ISSUE TITLE
Conversions of Polish Notations in C

### ISSUE THREAD

**Issue by Tanya170620** [HarshCasper/NeoAlgo#2439]
## 🚀 Feature

Adding polish notation conversions in C of-
       1. Infix to prefix
       2. Postfix to prefix
       3. Postfix to infix
       4. Prefix to infix 
       
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I am a participant of GSSoC'21 and a budding Data Structure and Algorithms enthusiast. It would be a great motivation for me if you could assign this issue to me.

## Pitch

I am a GSSoC'21 participant and I would love to contribute to open source platform.

**Comment by HarshCasper** [comment]
Don't put a lot of code contribution change in one single issue. Besides, some of them already exists in C directory.

**Comment by Tanya170620** [comment]
So can I do it just for postfix to prefix conversion in C.
