### ISSUE TITLE
[ALGO/DS] Ackerman Function

### ISSUE THREAD

**Issue by vgb-codes** [HarshCasper/NeoAlgo#244]
Ackerman Function
![image](https://user-images.githubusercontent.com/25801504/86638675-ccf2bf00-bfe8-11ea-99da-512441e4e195.png)

Math
C
C++ [@yogesh-kansal ]
C#
Python
Java
Golang
Javascript

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue

**Comment by atarax665** [comment]
@YashThakare Game on!!

**Comment by yogesh-kansal** [comment]
i would like to work on it in c++

**Comment by vgb-codes** [comment]
@atarax665 please check @YashThakare PR.

**Comment by vgb-codes** [comment]
@yogesh-kansal Cpp code has already been sent for PR. Thus, I cannot assign you Cpp.

**Comment by vgb-codes** [comment]
> @yogesh-kansal Cpp code has already been sent for PR. Thus, I cannot assign you Cpp.

@yogesh-kansal on further inspection, I can assign you Cpp. Please go ahead with Cpp.
Please follow the contribution guidelines when submitting your code.
