### ISSUE TITLE
Add test examples and edit description to Armstrong.js 

### ISSUE THREAD

**Issue by CoreyJamesLynch** [HarshCasper/NeoAlgo#2440]
## 📚 Documentation

# Description of algorithm lines 2 - 5,
- using inconsistent naming i.e. angstrom and  Armstrong.
- use of 'program' and 'programme' both work however 'program' is recommended in a computational context.
[Program](https://www.grammarly.com/blog/program-programme/)

# Line 40 Example uses inconsistent input/output 
- 321 is not an Armstrong number

# Add additional examples
- False test case
- Edge case of 0

# Add short circuit before while loop on line 27

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. I'm still new to open source contributions but directions suggested I open an issue first before submitting any changes.

**Comment by Swetha126** [comment]
Hey! I am a GSSOC'21 participant.
I have read the guidelines and would like to contribute in resolving this issue.
Please assign me this issue

**Comment by HarshCasper** [comment]
Thanks @CoreyJamesLynch 

Would you like to work on it or shall I put this Issue open to assignment?

**Comment by CoreyJamesLynch** [comment]
Hey Harsh, I'd like to work on it, thanks for asking.

**Comment by Komal-99** [comment]
Hi 
I have read the Contributions guidelines on pull request
I would like to work on this issue , Kindly assign it to me

**Comment by atarax665** [comment]
> Hi
> I have read the Contributions guidelines on pull request
> I would like to work on this issue , Kindly assign it to me

Sorry @Komal-99, this issue has already been assigned to @CoreyJamesLynch . You can open you own issue or browse other open issues.

**Comment by Komal-99** [comment]
okay no problem
