### ISSUE TITLE
 Finding a pair of element 

### ISSUE THREAD

**Issue by saimanoharhm** [HarshCasper/NeoAlgo#2442]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
 Finding a pair of element with sum k using hash table in a Unsorted array using c

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by saimanoharhm** [comment]
@gat786 Could you pls assign this for me

**Comment by kushal13112001** [comment]
@gat786 Could you pls assign this for me i will solve in python
