### ISSUE TITLE
Form the Mirror Tree of a Binary Tree

### ISSUE THREAD

**Issue by Sarthak-9** [HarshCasper/NeoAlgo#2448]
## 🚀 Feature

I would like to add a C++ Algorithm which creates the mirror tree of a given binary tree 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute this algorithm for GSSOC'21 as I am enthusiastic to work on Data Structures and Algorithms. 

## Pitch

This is an important algorithm which forms the mirror tree of a binary tree and can be widely used to solve problems which require inversion of a binary tree. It interchanges the left and right children of all non-leaf nodes .Please do assign this to me

**Comment by pallavidhere23** [comment]
am a GSSOC'2021 participant. Please assign me this work.I am good at C++,C,Java and python.Also good at algorithm and data structures.I will write programmes with detailed explanation and proper commenting.
