### ISSUE TITLE
Adding Neon number solution in C language under math section

### ISSUE THREAD

**Issue by Madhumitamoi** [HarshCasper/NeoAlgo#2449]
## 🚀 Feature

(A clear and concise description of what the feature is.)
A neon number is a number where the sum of digits of square of the number is equal to the number. This is a basic problem which I want to add under the math section in C language to help the newbie coders. 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes I have been through the guidelines.

## Motivation

(Please outline the motivation for the proposal.)
As a GSSoC'21 Participant I want to contribute in different open source using my basic knowledge and help others to learn as well.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Since NeoAlgo claims to have solution to all types of problems under one roof, I found this basic math problem is missing and hence I want to add this problem solution. For many learners basic knowledge is important to grasp the concept and implement it further. Therefore I want to give the solution being a Gssoc'21 Participant

**Comment by anurag01a** [comment]
Is this issue still open?
