### ISSUE TITLE
Removing duplicates from sorted linked list in c  

### ISSUE THREAD

**Issue by Vishruta-Patil** [HarshCasper/NeoAlgo#2453]
## 🚀 Feature
(A clear and concise of what the feature is)
C Program which removes duplicate elements from sorted linked list 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes 

## Motivation

(Please outline the motivation for the proposal.)
As a GSSOC participant I want to contribute in the project using my knowledge and help others to learn and grow as well. 

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Many times we come in the situation where in the list elements are repeated , which consumes the memory . To overcome the situation I want to contribute  and help others to solve the  problem.

**Comment by Vishruta-Patil** [comment]
I would like to work on this issue as a GSSOC participant

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I want to work on this using C++. Please assign me this. I will give examples with proper explanation too.

**Comment by Vishruta-Patil** [comment]
Added the required changes. @HarshCasper @iamrajiv please  review the changes.

**Comment by AbhignaSowgandhika02** [comment]
As a participant of GSSOC'21, I am willing to provide clean code in python for the same. @HarshCasper please assign me so that I can start providing proper explanations and examples.
