### ISSUE TITLE
Count Inversion

### ISSUE THREAD

**Issue by Omar-Hegazi** [HarshCasper/NeoAlgo#2456]
## 💥 Proposal

I would like to add code for Count Inversion  problem which will be submitted in C# with proper comments and an explanation of the solution as part of GSSOC'21.

Count Inversion problem:
the elements at indices i and j where i < j and arr[j] > arr[i] is considered an inversion. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by machine-sg** [comment]
I am a GSSOC'21 participant and I want to work on this using C++. Please assign me this. I will give examples with proper explanation too.
