### ISSUE TITLE
Reverse a doubly link list in C++

### ISSUE THREAD

**Issue by SamarpanCoder2002** [HarshCasper/NeoAlgo#2457]
## 💥 Proposal

(Problem: Reverse a Doubly Link List in C++)
I am also a **_gssoc'21_** participant.... I would like to add this problem in that.... If I can go forward with that, Please assign me to here... Thanks 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue  . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by SamarpanCoder2002** [comment]
> ## 💥 Proposal
> (Problem: Reverse a Doubly Link List in C++)
> I am also a **_gssoc'21_** participant.... I would like to add this problem in that.... If I can go forward with that, Please assign me to here... Thanks
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> yes

Thanks a lot for assigning me here... I will surely make a pull request as soon as possible

**Comment by SamarpanCoder2002** [comment]
> > ## 💥 Proposal
> > (Problem: Reverse a Doubly Link List in C++)
> > I am also a **_gssoc'21_** participant.... I would like to add this problem in that.... If I can go forward with that, Please assign me to here... Thanks
> > ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> > yes
> 
> Thanks a lot for assigning me here... I will surely make a pull request as soon as possible

I already make a pull request regarding to that(https://github.com/TesseractCoding/NeoAlgo/pull/2526#issue-589389169)... please check it out and merge the pull request if that ok.....

**Comment by priyanka001tech** [comment]
Hi,
I would like to work on this issue . Could you please assign it to me?
