### ISSUE TITLE
Adding a new sorting algorithm on Python

### ISSUE THREAD

**Issue by noviicee** [HarshCasper/NeoAlgo#2458]
## 💥 Proposal

I wish to add an interesting sorting algorithm in Python known as Monkey-Sort.
I will also add the details on it in my file

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

**Comment by siddharth-143** [comment]
I would like to contribute
Assign me for this project as I am GSSOC (participate)2021

**Comment by noviicee** [comment]
Thank you @HarshCasper :)

**Comment by noviicee** [comment]
@HarshCasper do I need to update the main readme and contributor's list too for the link to the new file,
Or just the readme in the corresponding folder where I have added code..??
