### ISSUE TITLE
Power set using Bitwise Operations in C++

### ISSUE THREAD

**Issue by YashPaste** [HarshCasper/NeoAlgo#2460]
## 💥 Proposal

I would like to add code to Find Power set (set of all possible subsets) using Bitwise Operators which will be submitted in C++ with proper comments and an explanation of the solution.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by sandeepN06** [comment]
I am ready to work on this please assign this to me!

**Comment by ishitakapoor26** [comment]
I want to work on this issue. Please assign to me.
