### ISSUE TITLE
Adding new Sorting Algo in Python in Python... #GSSOC'21

### ISSUE THREAD

**Issue by Aarushi3113** [HarshCasper/NeoAlgo#2461]
## 💥 Proposal

I would like to add **Bucket Sort** in *Python* language.
I would write clean code and follow the guidelines. I would also provide a clear and concise documentation for the program.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read and understood the Contributing Guidelines on PR.

**Comment by siddharth25pandey** [comment]
@Aarushi3113 Assigned. Make sure you follow proper coding and formatting standards. All the very best
