### ISSUE TITLE
LCM of n elements in Python...[GSSOC'21]

### ISSUE THREAD

**Issue by Aarushi3113** [HarshCasper/NeoAlgo#2462]
## 💥 Proposal

I would like to add the code for calculating LCM of n numbers in *Python* language.
I would provide a proper documentation and write clean code while keeping the guidelines in mind.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read and understood the contributing guidelines.

**Comment by priyanka001tech** [comment]
Hi,
I would like to work on it. Please assign me.

**Comment by siddharth25pandey** [comment]
@Aarushi3113 Not a valid issue.
