### ISSUE TITLE
Neon number  under mathematics section

### ISSUE THREAD

**Issue by ankan1811** [HarshCasper/NeoAlgo#2463]
## 💥 Proposal

A neon number is a number where the sum of digits of square of the number is equal to the number. The task is to check and print neon numbers in a range.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankan1811** [comment]
@bhav09 I want to implement this in C++ as a part of GSSoC'21. Please assign it to me.

**Comment by ankan1811** [comment]
@siddharth25pandey  @atarax665  It would be nice if any mentor can add a level tag to this issue like easy or medium.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute Neon number problem in C++
i have readed the contributing guidelines on Pull request 

so i would like @bhav09 to assign this project to me :)

**Comment by siddharth25pandey** [comment]
> Hi I am GSSoC'21 participant
> 
> i would like to contribute Neon number problem in C++
> i have readed the contributing guidelines on Pull request
> 
> so i would like @bhav09 to assign this project to me :)

@ananddasani Already assigned for C++.  You can work for different languages.

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey @atarax665 It would be nice if any mentor can add a level tag to this issue like easy or medium.

@ankan1811 Done

**Comment by ananddasani** [comment]
> > Hi I am GSSoC'21 participant
> > i would like to contribute Neon number problem in C++
> > i have readed the contributing guidelines on Pull request
> > so i would like @bhav09 to assign this project to me :)
> 
> @ananddasani Already assigned for C++. You can work for different languages.

Should i try for JAVA ?

**Comment by siddharth25pandey** [comment]
> > > Hi I am GSSoC'21 participant
> > > i would like to contribute Neon number problem in C++
> > > i have readed the contributing guidelines on Pull request
> > > so i would like @bhav09 to assign this project to me :)
> > 
> > 
> > @ananddasani Already assigned for C++. You can work for different languages.
> 
> Should i try for JAVA ?

@ananddasani Go ahead for Java

**Comment by shreyadubey0902** [comment]
can i also work on it

**Comment by bhav09** [comment]
Hey @shreyadubey0902, it has already been assigned as of now. However, you can choose to open a new issue of a topic that hasn't been covered yet.
