### ISSUE TITLE
Adding a new column wise sorting algorithm for 2D matrix of order n x m in C++ (GSSOC'21)

### ISSUE THREAD

**Issue by aarushirai2210** [HarshCasper/NeoAlgo#2464]
## 💥 Proposal
 I wish to add an algorithm for sorting a 2D matrix of order **N X M** in a column wise
manner. I am a GSSOC'21 participant.
Language : C++

### **Have you read the** [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by anushkrishnav** [comment]
Go for it but make sure the project isn't already there

**Comment by aarushirai2210** [comment]
Sure. Please assign it to me.

**Comment by aarushirai2210** [comment]
Please assign it the label of GSSOC as well and assign it to me so that no one else can take this proposal up.
