### ISSUE TITLE
Postfix to Prefix Conversion

### ISSUE THREAD

**Issue by Tanya170620** [HarshCasper/NeoAlgo#2465]
## 🚀 Feature

It will convert a postfix expression to prefix expression using stack in C.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I am a GSSoC'21 participant and would love to contribute to open source platform.

## Pitch

As postfix to prefix conversion is not present in C repo, I would like to do it as a participant of GSSoc'21.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in C as well as in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by btanisha** [comment]
I can work on the same in C++ and python. @HarshCasper Please assign it to me

**Comment by sparshiigupta** [comment]
Hello,
I am GSSoC'21 participant and would like to work on this issue in C. Please assign it to me.

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by Diksha-11** [comment]
I also would like to work on this issue.
I request @anushkrishnav  to please /assign me this issue.

**Comment by anushkrishnav** [comment]
Please find a Unique problem and make an issue and assign it with the help on bot .
If the algo/ds exsist on our repo already we will close your PR so please take a look into it
Good Luck
@Diksha-11 @Dimple115 @btanisha
