### ISSUE TITLE
Reversal algorithm for array rotation (GSSoC'21)

### ISSUE THREAD

**Issue by C0DE-RUNNER** [HarshCasper/NeoAlgo#2467]
## 💥 Proposal

Reversal algorithm for array rotation

Let AB are the two parts of the input array where A = arr[0..d-1] and B = arr[d..n-1]. The idea of the algorithm is : 
 

Reverse A to get ArB, where Ar is reverse of A.
Reverse B to get ArBr, where Br is reverse of B.
Reverse all to get (ArBr) r = BA.
Example : 
Let the array be arr[] = [1, 2, 3, 4, 5, 6, 7], d =2 and n = 7 
A = [1, 2] and B = [3, 4, 5, 6, 7] 
 

Reverse A, we get ArB = [2, 1, 3, 4, 5, 6, 7]
Reverse B, we get ArBr = [2, 1, 7, 6, 5, 4, 3]
Reverse all, we get (ArBr)r = [3, 4, 5, 6, 7, 1,2]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by Mohitmadhav** [comment]
Hello, I am a GSSoC Participant and would like to work on this issue in C++.
Can you please assign this to me @C0DE-RUNNER @born-2learn ?

**Comment by Mohitmadhav** [comment]
The cpp file is not getting uploaded ..SHould I just type the code here @HarshCasper?
(Sorry for being late, I am having exams right now)

**Comment by Mohitmadhav** [comment]
@C0DE-RUNNER @HarshCasper in which folder should I add my cpp file?
