### ISSUE TITLE
Sieve of Eratosthenes in Golang

### ISSUE THREAD

**Issue by BeAgarwal** [HarshCasper/NeoAlgo#2471]
### Description
Sieve of Eratosthenes in Golang language.

- [x] Sieve of Eratosthenes

### Have you read the Contributing Guidelines on Pull Requests?
Yes, I have read the Contributing Guidelines.

### Motivation
I want to excel in the Golang language so I want to work with Golang.

### Pitch
For GSSoC'21

Please assign this to me.

**Comment by siddharth25pandey** [comment]
@BeAgarwal Assigned. Make sure you follow proper coding and formatting standards. Have a great day ahead !

**Comment by BeAgarwal** [comment]
PR Merged
