### ISSUE TITLE
Mean of range in array in C++

### ISSUE THREAD

**Issue by C0DE-RUNNER** [HarshCasper/NeoAlgo#2475]
## 💥 Proposal

Given an array of n integers. You are given q queries. Write a program to print floor value of mean in range l to r for each query in a new line.

Examples :

Input : arr[] = {1, 2, 3, 4, 5}
        q = 3
        0 2
        1 3
        0 4
Output : 2
         3
         3
Here for 0 to 2 (1 + 2 + 3) / 3 = 2

Input : arr[] = {6, 7, 8, 10}
        q = 2
        0 3
        1 2
Output : 7
         7

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by LazySukanta** [comment]
I would like to contribute, Assign me for this project as I am GSSOC (participate)2021.

**Comment by siddharth25pandey** [comment]
@C0DE-RUNNER Invalid issue
