### ISSUE TITLE
Merge Without Extra Space C++ (GSSoc'21)

### ISSUE THREAD

**Issue by C0DE-RUNNER** [HarshCasper/NeoAlgo#2477]
## 💥 Proposal
Given two sorted arrays arr1[] of size N and arr2[] of size M. Each array is sorted in non-decreasing order. Merge the two arrays into one sorted array in non-decreasing order without using any extra space.

Input:
N = 2, M = 3
arr1[] = {10, 12}
arr2[] = {5, 18, 20}
Output: 5 10 12 18 20
Explanation: Since you can't use any
extra space, modify the given arrays
to form 
arr1[] = {5, 10}
arr2[] = {12, 18, 20}

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Karan-29** [comment]
Hi i am a GSSOc'21 participant. Can you assign it to me. I would like to work on this. Thanks

**Comment by vishakha-aggarwal** [comment]
Hey , I can solve this issue. Can you please assign it to me?

**Comment by neha07kumari** [comment]
### Feature
Solutions of Merge without extra space

### Language: C++
Have you read the Contributing Guidelines on Pull Requests?
Yes

### Motivation
I want to contribute to it under GSSoC'21.

### Pitch:
I would like to take up this task to implement it in C++. @bhav09

**Comment by vishakha-aggarwal** [comment]
Hey , I can solve this issue. Kindly assign it to me.

**Comment by vishakha-aggarwal** [comment]
Hey, I want to solve this question under GSSOC'21. I have read the contributing guidelines of pull request. I will implement this task in C++

**Comment by bhav09** [comment]
Since the issue was opened by @C0DE-RUNNER, the issue will be appointed to her.
