### ISSUE TITLE
4 Sum Problem.

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#2480]
## 🚀 Feature

I want to add an algorithm which finds four elements that sum to a given value .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Since it is one of the very frequently asked questions in interviews , As a GSSOC participant I want to contribute in the project using my knowledge and help others to learn and grow as well.

## Pitch

As the naive approach that everyone thinks runs in cubic time, this can be improved  into quadratic time using hashing .

**Comment by kotwani2883** [comment]
Kindly assign this to me as a part of GSSOC'21.

**Comment by machine-sg** [comment]
Hi, I am a GSSOC'21 participant and I want to work on this using C++. I will explain with proper explanation. Please assign me this.

**Comment by vanshika2906** [comment]
I am GSSOC'21 participant with knowledge of data structure and algorithms want to work on this issue. Kindly assign it to me. Thank You!
