### ISSUE TITLE
[GSSOC'21] Finding intersection point in a Y shaped Linked List

### ISSUE THREAD

**Issue by machine-sg** [HarshCasper/NeoAlgo#2481]
## 💥 Proposal

Hi, I am a GSSOC'21 participant and I want to work on this using C++. I have 7 methods to discuss and I will explain each and every method with proper explanation. Please assign me this.

**Comment by Nikitha2309** [comment]
I am a GSSoC'21 participant and I want to work on this issue. I am already familiar with this algorithm. 

Please assign this issue to me under the label of GSSoC'21. 

I can provide optimised yet understandable code with quality code , highly understandable comments and easy as well as corner test cases . 

I can work on this issue in C, C++ as well as Python 

I have read Contributing Guidelines on Pull Requests.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by hritikkhurana10sm** [comment]
Hii ,  I am Hritik Khurana(P) , GSSoC'21 participant and I want to work on this issue . Kindly please assign.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
