### ISSUE TITLE
[GSSOC'21] Kruskal's Algorithm

### ISSUE THREAD

**Issue by machine-sg** [HarshCasper/NeoAlgo#2482]
## 💥 Proposal

Hello, I am a GSSOC'21 participant and I want to add the code of this algorithm. My code will be in C++. I will also give some other examples which will be solved using this algorithm with proper explanation. Please assign me this. Hope to hear you.
Thank you .

**Comment by Nikitha2309** [comment]
I am a GSSoC'21 participant and want to work on this issue. Please assign this PR to me. I am familiar with this algorithm and already solved several problems related to that.

**Comment by vermatanu** [comment]
i can do this in java. please assign this to me!

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute this algorithm using C++ 

so i would like @bhav09 to please assign this project to me :)

**Comment by bhav09** [comment]
Hey, Kruskal's algo already exists hence cannot be assigned. 
Closing the issue.
