### ISSUE TITLE
Implementation of Stack  using Linklist  in C++

### ISSUE THREAD

**Issue by devu26** [HarshCasper/NeoAlgo#2486]
Stack is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out).
Here I want to implement stack using link list. please assign this issue to me.

**Comment by harshbhalala-04** [comment]
I want to contribute to this project and my programming language will be C++. I have knowledge of implementing a link list using stack. I am a GSSOC'21 participant. Please assign this issue to me

**Comment by Apoorve73** [comment]
Kindly open a new issue while following the template! Thanks :)
