### ISSUE TITLE
[GSSOC'21] seive of eratosthenes

### ISSUE THREAD

**Issue by anotherwebguy** [HarshCasper/NeoAlgo#2488]
## 💥 Proposal

As a participant of gssoc'21 i would like to contribute this algo to find all the prime numbers within a number range using seive of eratosthenes in c++. Plz assign me this issue .
@HarshCasper @bhav09 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by btanisha** [comment]
Hi I would like to contribute to this, please assign this to me. I'm a GSSOC participant.

**Comment by priyanka001tech** [comment]
Hi I would like to contribute to this. I'm a GSSOC participant.

**Comment by ananddasani** [comment]
Hi i am GSSoC'21 participant 

I want to contribute this Seive of Eratosthenes  using C++

so , I would like @bhav09 and @HarshCasper to please assign me this project :)

**Comment by anotherwebguy** [comment]
> Hi i am GSSoC'21 participant
> 
> I want to contribute this Seive of Eratosthenes using C++
> 
> so , I would like @bhav09 and @HarshCasper to please assign me this project :)

Hello @ananddasani i've already made an pr for seive of eratosthenes so it's now done , but i'am sure u can find other issues to contribute to or u can either create one issue and then work on it
