### ISSUE TITLE
Extended Euclid Algorithm

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#249]
**Algorithm:** 
Extended Euclid Algorithm

**Languages Supported:**
C
CPP [@atarax665 ]
C#
Java [@Himanshu70565]
JavaScript
Python [@atarax665]
Golang

**Comment by atarax665** [comment]
@ricardoprins I would like to work on this issue in C++ and python.

**Comment by vgb-codes** [comment]
@atarax665 Go ahead! C++ and Python

**Comment by Himanshu70565** [comment]
@VijayaGB98  I would like to work in Java.

**Comment by vgb-codes** [comment]
@Himanshu70565 Please go ahead.

**Comment by Yash-Thakare22** [comment]
I would like to work on issue in C
