### ISSUE TITLE
Implementation of Dijkstra's algorithm using C (GSSOC'21)

### ISSUE THREAD

**Issue by aarushirai2210** [HarshCasper/NeoAlgo#2490]
## 💥 Proposal

I would like to contribute a code for Dijkstra's algorithm for single source shortest path, using C . 
I am a GSSOC'21 participant.
Language : C

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in C and can also in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by harshbhalala-04** [comment]
I would like to contribute a code for Dijkstra's algorithm using C and also I would like to implement it in C++ also. I am a GSSOC'21 participant. Please assign this issue to me
