### ISSUE TITLE
Adjacency Matrix C, Java

### ISSUE THREAD

**Issue by Aleena-Ashraf** [HarshCasper/NeoAlgo#2493]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

Hey, being a GSSOC'21 participant i would like to implement the Adjacency Matrix using C or Java.
This is a very potential question and hence want to work on it.
Please do assign me this.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue. Could you please assign it to me?

Thanks!!

**Comment by Apoorve73** [comment]
@AasthaGoyalgit we assign issue on FCFS basis, but you can always open a new issue and work on it.
