### ISSUE TITLE
Job Scheduling algorithm - Greedy Problem in JAVA

### ISSUE THREAD

**Issue by krishna-y2000** [HarshCasper/NeoAlgo#2494]
## 💥 Proposal

Hello,
I want to add Job Scheduling algorithm.It is  part of greedy problems.There are very few problems on greedy so i would like to add this one. I wish to code in JAVA.I will be solving with different test cases for better understanding of problem.
Please Assign this task to me .

 Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes !!

**Comment by sukritidawar** [comment]
I would like to work on this issue in C++ as a part of GSSOC'21

**Comment by Apoorve73** [comment]
@sukritidawar, issues are assigned on fcfs basis, but you can always open a new issue and work on it. :)

**Comment by krishna-y2000** [comment]
@ankitaggarwal23  , 
please check my pr and merge it ,
you can find my running code here : [Code](
https://ideone.com/mx0a1S)
Please also assign GSSOC'21 tag as it is mandatory to label.
Thanks.
