### ISSUE TITLE
Find duplicates in an array of N+1 integers

### ISSUE THREAD

**Issue by poojitha2002** [HarshCasper/NeoAlgo#2495]
The problem statement is to find the repeating element/duplicate in given array. The array contains numbers ranging from 1 to N+1 . I have 5 methods to discuss ranging from brute force to optimized solution.

Hope this issue will be assigned to me. 

Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read all the guidelines.

**Comment by imsushant12** [comment]
I want to contribute on it under gssoc'21. I can implement this issue in C Language. I will write clean and explanatory code along with time and space complexities of each approach.

**Comment by ishwari20** [comment]
I would like to work on this issue, i can put multiple approaches for the same. I code in C++. Please assign this issue to me.
