### ISSUE TITLE
Comb Sort 

### ISSUE THREAD

**Issue by sanjaysunil34** [HarshCasper/NeoAlgo#2500]
## 🚀 Feature

Given an unsorted array, sort the array using comb sort algorithm in C language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As part of GSSOC'21

**Comment by adiig7** [comment]
Can i work on this? @bhav09

**Comment by bhav09** [comment]
@adiig7, we assign on fcfs basis. So ideally the issue would be assigned to @sanjaysunil34. 
However, you can open another issue about the same and can try implementing with a different programming lang.
Hope this helps :)
