### ISSUE TITLE
Infix To Prefix

### ISSUE THREAD

**Issue by kevla-4121** [HarshCasper/NeoAlgo#2504]
In stack I like to add a code for the  conversation of Infix To Prefix using c++.
Please assign this issue to me.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by taruni-always** [comment]
Hello, I would like to work on the code in C Language. Please assign this to me under GSSoC '21

**Comment by priyanka001tech** [comment]
Hi,
I would like to work on this issue in c++ . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!

**Comment by priyanka001tech** [comment]
In stack I like to add a code for the conversation of Infix To Prefix and prefix to infix as well using c++.
Please assign this issue to me.

**Comment by Apoorve73** [comment]
Kindly use the issue template while opening an issue! For now, I am closing this one. You can open another one using template.
