### ISSUE TITLE
Selection Sort and Cycle Sort in JavaScript

### ISSUE THREAD

**Issue by ireneelizabethsabu** [HarshCasper/NeoAlgo#2505]
Hi,
I would like to implement using JavaScript the following sorting algorithms.

1.Selection Sort
2.Cycle Sort
Please assign this to me as part of GSSOC'21.

**Comment by sukritidawar** [comment]
I would like to work on this issue in C++ as a part of GSSOC'21

**Comment by Apoorve73** [comment]
@sukritidawar, the one who has opened up the issue has the very right to take up the issue at first. But still, you can always open another issue and work on it! :)

**Comment by Apoorve73** [comment]
@ireneelizabethsabu go for it if it hasn't been implemented already. All the Best :+1:

**Comment by sukritidawar** [comment]
> @sukritidawar, the one who has opened up the issue has the very right to take up the issue at first. But still, you can always open another issue and work on it! :)

I was asking to implement this issue in C++ since the one who opened it wanted to do it in JavaScript. But okay, I'll create a new issue.

**Comment by Apoorve73** [comment]
Sure thing @sukritidawar ! All the best :+1:
