### ISSUE TITLE
Sublist Search in C++ and Java

### ISSUE THREAD

**Issue by ireneelizabethsabu** [HarshCasper/NeoAlgo#2506]
Sublist Search is used to search for a list in another linked list.
eg: list1 =  1 -> 2 -> 3
      list2  = 4 -> 1 -> 2 -> 3 -> 5
      here sublist search returns true since list1 is a sublist of list2

I am a participant of GSSOC'21. kindly assign this to me.

**Comment by AasthaGoyalgit** [comment]
Hi,
I would like to work on this issue in java and c++ . Could you please assign it to me?
I have read Contributing Guidelines on Pull Requests.
Thanks!!
