### ISSUE TITLE
Trapping Rain Water problem in C++ (GSSOc'21)

### ISSUE THREAD

**Issue by Karan-29** [HarshCasper/NeoAlgo#2508]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
There will be given n non-negative integers representing buildings where the width of each building is 1. Compute how much water it can trap after raining.

Example:- 
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
Explanation: If we carefully observe using a block diagram, we see that:-
1 unit of water is stored from index [1, 3] and [9, 11], Total=2.
4 units of water is stored from index [3, 7], Total=6.
Hence 6 units of rain water is being trapped.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
YES

**Comment by Karan-29** [comment]
Please assign this issue to me. I would like to work on this.

**Comment by raunakpandey1** [comment]
Hello I am a GSSoC21 Participant. I would like to contribute to this.

**Comment by Vishakha-sta** [comment]
Hello, I am a GSSoC'21 participant. I had read all the Contributing Guidelines on Pull Requests.
I am good with c++ coding
I would like to contribute in this issue.
