### ISSUE TITLE
Level order traversal  in C++

### ISSUE THREAD

**Issue by hritikgupta92** [HarshCasper/NeoAlgo#2509]
## 🚀 Feature

 Level order is a traversal in a binary tree in a BFS fashion.

**Comment by hritikgupta92** [comment]
I would like to work on this issue,can you assign me? @atarax665

**Comment by Chahat226** [comment]
Hi, I am Chahat, a GSSOC'21 Participant. I am highly experienced in competitive programming in C++. I would like to contribute the level order traversal algorithm in C++ to this project.
Please assign this task to me :)
Thank you.

**Comment by hritikgupta92** [comment]
@HarshCasper  I have made pull request #2630 plz check it out

**Comment by hritikgupta92** [comment]
@HarshCasper  Can you check pull request #2885

**Comment by hritikgupta92** [comment]
@HarshCasper  Can you check pull request #3329

**Comment by hritikgupta92** [comment]
@HarshCasper  Can you check pull request #3408
