### ISSUE TITLE
An algorithm to take input of a Integer number and prints its digits in reverse order as output. (C++/CP)[GSSoC'21]

### ISSUE THREAD

**Issue by ayush0402** [HarshCasper/NeoAlgo#2513]
## 🚀 Feature

I will write an algorithm using C++ which will take input of an Integer value and reverses the number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I feel I can add a few algorithms to the CP section of C++ folder, and I feel starting out with this simple one. This is my first ever open source contribution attempt as a fresher. Would be very happy if this issue is assigned to me.

## Pitch

This algorithm is pretty basic and is many a times implemented in CP questions. If NeoAlgo is aiming to have all the possible algos under same directory then it should be included there. :)

**Comment by raunakpandey1** [comment]
Hello I am a GSSoC21 Participant. I would like to contribute to this.

**Comment by Vishakha-sta** [comment]
Hi, I am a GSSoC'21 participant .
I would like to contribute to this problem

**Comment by priyanka001tech** [comment]
Hi, I am a GSSoC'21 participant .I would like to contribute to this problem.
I can surely put my best effort to solve it.

**Comment by HarshCasper** [comment]
Too layman!
