### ISSUE TITLE
Take input of TIME in 12 Hour Format and gives output of the same in 24 Hour format. (C++/CP)[GSSoC'21]

### ISSUE THREAD

**Issue by ayush0402** [HarshCasper/NeoAlgo#2514]
## 🚀 Feature

I will write an algorithm in C++ which will take input for time in an specified 12 Hour format (HH:MM AM/PM) and convert and give output of the same in 24 Hour format (HH_24:MM).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

This is the my second idea I am pitching for CP in C++. This is my first ever open source contribution attempt as a fresher. Would be very happy if this issue is assigned to me.

## Pitch

I have experienced need of using this algorithm in CP contest a few times now. And I feel this should be included in a  directory containing all the possible CP algorithms.

**Comment by samrat1223** [comment]
Hey can I work on this issue ?

**Comment by btanisha** [comment]
I would like to contribute to this, I'm a GSSOC participant.

**Comment by Vishakha-sta** [comment]
Hello, I am a GSSoC'21 participant. I had read all the Contributing Guidelines on Pull Requests.
I am good with c++ coding.
I would like to contribute in this issue.

**Comment by HarshCasper** [comment]
Too layman!
