### ISSUE TITLE
Reverse a Linked List 

### ISSUE THREAD

**Issue by TidbitsJS** [HarshCasper/NeoAlgo#2523]
## Reversal of Linked List

Program to reverse the given linked list in JavaScript. Following things can be done -
1. Reverse a Linked List
2. Display the newly reversed Linked List

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The goal is to help people understand how a linked list can be reversed in JavaScript

## Event

GSSoC'21

**Comment by TidbitsJS** [comment]
As I had been instructed, I have created multiple issues for the dynamically linked list program
Kindly assign this to me as a part of GSSOC @HarshCasper

**Comment by HarshCasper** [comment]
Please work on the existing Issues first

**Comment by AbhignaSowgandhika02** [comment]
As a participant of GSSOC'211, I am willing to provide clean code in python for the same. @HarshCasper Please assign this to me so that I can work on providing the necessary code.

**Comment by TidbitsJS** [comment]
Can you assign this to me now? @HarshCasper & @atarax665 
Part of GSSOC'21 
I Will do it in JavaScript :)

**Comment by Gautam204** [comment]
I want to contribute by giving the solution to this issue in C , Can you assign this to me now? @HarshCasper & @atarax665 as I am part of GSSOC'21

**Comment by TidbitsJS** [comment]
@Gautam204 & @AbhignaSowgandhika02 ... I have assigned myself as I have created the issue. But as I am going to do it in JavaScript & you guys want to do it in a different language. So with the mentor's permission, you can assign yourself as well. Do consult with them
