### ISSUE TITLE
Iterative Binary Search in C Language

### ISSUE THREAD

**Issue by imsushant12** [HarshCasper/NeoAlgo#2528]
## 🚀 Feature

Binary Search algorithm : Iterative approach in C Language will example and explanation.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute on it under gssoc'21.

## Pitch

I have found only the recursive approach of binary search in C directory. So this will be the iterative approach of the Binary Search Algorithm with time complexity O(log n).

**Comment by bhav09** [comment]
Appreciate your enthusiasm. However, this issue has already been resolved. 
You can find it here: https://github.com/TesseractCoding/NeoAlgo/blob/master/C/search/BinarySearch.C
Hence closing the issue.
