### ISSUE TITLE
Stack Using Queue

### ISSUE THREAD

**Issue by Abhinaba006** [HarshCasper/NeoAlgo#2535]
## 🚀 Feature

Building a stack by using two queues in cpp

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Abhinaba006** [comment]
@bhav09 , sir please assign me to do this work, I am a GSSOC21 participant, I can do this in cpp.

**Comment by bhav09** [comment]
Sure.

**Comment by Abhinaba006** [comment]
Sir @bhav09 , Can you please add GSSOC21 label to this issue, as a GSSOC21 participant that will help me a lot, my code is almost ready I am sending the pr asap

**Comment by bhav09** [comment]
Sure.

**Comment by Abhinaba006** [comment]
Thank you, sir, I have sent the pr.  but it is failing in deepsource java (beta) test, I don't know why it is happening, what should I do now

**Comment by Abhinaba006** [comment]
@bhav09 , sir can you add the level2 or level3 label also(it was a new feature I added), so I can get the points, I saw this now in the gssoc pdf given to us, and once again a big thanks to you sir, It was my first pr.

**Comment by HarshCasper** [comment]
It already exists.

**Comment by Abhinaba006** [comment]
Okay
