### ISSUE TITLE
Reverse alternate k nodes in a Singly Linked List in Java

### ISSUE THREAD

**Issue by Meghna180401** [HarshCasper/NeoAlgo#2538]
## 🚀 Feature

I want to implement the solution to reverse alternate k nodes in a singly linked list in Java as a part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by adiig7** [comment]
Can i take up this?
