### ISSUE TITLE
Pancake Sorting

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#254]
Pancake Sorting 

An Algorithm to sort an array by on;y reversing a part of the array or the whole array. 

Java [@parjanyaacoder]
C [@santushtisharma10]
C++ [@kashika3101]
Python [@Ajay0511]

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java.

**Comment by vgb-codes** [comment]
@parjanyaacoder Go ahead with Java

**Comment by parjanyaacoder** [comment]
Solved in Java by #255 
I hope I have done everything. @VijayaGB98 Pls check. Also I have commented on #178 Please assign me.

**Comment by Gaushikmr** [comment]
I would like to work on this issue on C and python

**Comment by atarax665** [comment]
@ricardoprins Assign @gaushikmr this issue.

**Comment by santushtisharma10** [comment]
I would like to work on this issue in C and C++

**Comment by santushtisharma10** [comment]
HakinCodes(P)

**Comment by Ajay0511** [comment]
I would like to do it in Python

**Comment by kashika3101** [comment]
I would like to work on this issue in c++

**Comment by vgb-codes** [comment]
@santushtisharma10 Go ahead with C.
@Ajay0511 Go ahead with Python.
@kashika3101 Go ahead with C++.
Please follow the contribution guidelines when submitting your contribution.
