### ISSUE TITLE
Max and min Heap implementation

### ISSUE THREAD

**Issue by dhruvinfo28** [HarshCasper/NeoAlgo#2541]
## 🚀 Feature

A basic implementation of a max and a min heap using C++ along with all the basic update, delete , insert operations.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

## Motivation

I have been loving contributing to this repo so far , and would love to make further contributions.  Also regarding this specific feature request , implementation of heap data structure specifically isn't there.

## Pitch

For a beginner in DS and algo, jumping straight away to pre-written code i.e. STL could be quite overwhelming. Hence a basic implementation with update, insert, delete queries would be a big help. And since everything lives under this repo it would be a nice add on.
Kindly assign this to me under GSSOC2021

**Comment by Abhinaba006** [comment]
@bhav09 please assign me on this issue, I can solve this problem using cpp.

**Comment by dhruvinfo28** [comment]
@bhav09 thanks for assigning, I'm on it.

**Comment by taruni-always** [comment]
Hello. I would like to implement the same in C Language. Please assign this to me under GSSoC '21.

**Comment by bhav09** [comment]
Hey @taruni-always, you can open a new issue regarding its implementation in C. Will have a look at it and assign the issue to you :)
