### ISSUE TITLE
Number of K-Length Sublists with Average at Least Target [Python]

### ISSUE THREAD

**Issue by kushal13112001** [HarshCasper/NeoAlgo#2545]
## 💥 Proposal

Given a list of integers nums, and integers k and target, return the number of sublists whose length is k and its 
average value ≥ target.

**Constraints**

n ≤ 100,000 where n is the length of nums

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by kushal13112001** [comment]
Hey @SKAUL05 @nrickles3 @ArchanGhosh @hushee69 I would like to take up this issue and solve it with a brief description and with proper code and test cases. Please assign me this issue

**Comment by kushal13112001** [comment]
sir  @bhav09 Gssoc'21 label not applied ?

**Comment by bhav09** [comment]
Will do it, thanks for pointing it out :)

**Comment by kushal13112001** [comment]
yes sir Thank you :)
