### ISSUE TITLE
Update of readme file of cp in Java

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2549]
## 📚 Documentation

The readme file of cp of Java is empty. Better providing the list of problems included in java/cp.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by adiig7** [comment]
@bhav09 if this seems valid please assign it to me.

**Comment by bhav09** [comment]
Seems legit. I am assigning it to you. All the best @adiig7 :)

**Comment by adiig7** [comment]
@bhav09 Can you please add Gssoc 2021 label to it?
