### ISSUE TITLE
Moore's Voting algorithm in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2551]
## 💥 Proposal

I would like to contribute the code for Moore's voting algorithm in C++. Please assign this issue to me.[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by bhav09** [comment]
Sure. All the best @SAY-droid427
