### ISSUE TITLE
Merge Intervals in C++

### ISSUE THREAD

**Issue by Maitryee-Choudhary** [HarshCasper/NeoAlgo#2553]
## 💥 Proposal

Given a 2D array of intervals where intervals[i]={start_time,end_time} , merge all the overlapping intervals and return the array of non-overlapping intervals that cover all the intervals in the input.
GSSoC'21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

Hey @bhav09  please look into this issue and please assign to me.

**Comment by bhav09** [comment]
Sure @Maitryee-Choudhary. All the best.

**Comment by Maitryee-Choudhary** [comment]
> Sure @Maitryee-Choudhary. All the best.

Thank You!
