### ISSUE TITLE
Reverse a Linked List in Python

### ISSUE THREAD

**Issue by Shreejichandra** [HarshCasper/NeoAlgo#2554]
## 💥 Proposal

I would like to contribute the code to reverse a linked list and display the newly reversed linked list in Python. Please assign this issue to me.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by bhav09** [comment]
Hey @Shreejichandra, thanks for opening this issue. The topic you have chosen its issue has already been covered and merged. 
You can find it here: https://github.com/TesseractCoding/NeoAlgo/pull/344
Closing the issue.
