### ISSUE TITLE
Detect Loop in linked list using C++

### ISSUE THREAD

**Issue by Sakshi0401** [HarshCasper/NeoAlgo#2556]
Hello @anushkrishnav  as a participant of **GSSoC'21** I would like to work on this problem **'Detect Loop in linked list'** using C++.

**Question :**
Given a linked list of N nodes. The task is to check if the the linked list has a loop. 

A linked list is said to contain a cycle if any node is visited more than once while traversing the list. 

**Example :**
In below example node containing value 3 is pointing to node 2

![image](https://user-images.githubusercontent.com/64726139/110648858-1a11db00-81df-11eb-8d39-dcba2b76177c.png)

Hence the output will be **1**

**Comment by Apoorve73** [comment]
@Sakshi0401 go for it if it hasn't been implemented already. All the Best :+1:

**Comment by taruni-always** [comment]
Hello, I would like to implement this in C Language. Please assign this to me under GSSoC '21 @Apoorve73

**Comment by Apoorve73** [comment]
@taruni-always , we assign issues on FCFS basis. But, you can always open a new issue and work on it. Thanks :)

**Comment by taruni-always** [comment]
@Apoorve73 Agreed. However, it hasn't been assigned in C language. I'm asking you to assign it to me for implementing in C. (As this is a related issue) But if you want me to make another issue, I would do it. Anything works fine with me :-)

**Comment by Apoorve73** [comment]
Oops! My bad! Go ahead with creating another issue! Thanks! :+1:
