### ISSUE TITLE
Rotten Oranges Problem in C++

### ISSUE THREAD

**Issue by prithwirajmitra2001** [HarshCasper/NeoAlgo#2564]
## 🚀 Feature

This is a very popular graph related problem. 
Question - There are a set of oranges in a certain manner some of which are rotten while others are fresh.
The objective is to find the total time taken for all the oranges to become rotten when coming in contact with rotten oranges.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes I have read all the guidelines.

## Motivation

I am a GSSoC 21 participant. I wish to work on this issue. Please assign me this task.

## Pitch

I will implement this task in C++.

**Comment by prithwirajmitra2001** [comment]
Would you please assign me @Apoorve73

**Comment by Apoorve73** [comment]
@prithwirajmitra2001 go for it if it hasn't been implemented already. All the Best :+1:

**Comment by prithwirajmitra2001** [comment]
It has not yet been implemented. Working on it. Thank you sir.

**Comment by prithwirajmitra2001** [comment]
Sir this issue has not been given the GSSoC'21 tag. Please give the tags.
Also either Level2 or Level3 tag also needs to be given depending upon the type of issue.

**Comment by Apoorve73** [comment]
Sure thing @prithwirajmitra2001! I have added the GSSoC tag for now. We will tag the Level when you make a PR! +1
