### ISSUE TITLE
Rabin Carp Algorithm in C++

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2565]
## 🚀 Feature
Adding rabin carp algorithm in C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

**Comment by Apoorve73** [comment]
@adiig7 go for it if it hasn't been implemented already. All the Best :+1:

**Comment by adiig7** [comment]
@Apoorve73 already checked. Can you please add GSSOC 2021 label to the issue?
