### ISSUE TITLE
Armstrong number probem in Python

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2567]
## 🚀 Feature
Adding armstrong number code written in python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by anushkrishnav** [comment]
> ##  Feature
> Adding armstrong number code written in python.
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes.

Go for it but make sure its not already present

**Comment by adiig7** [comment]
Yes already checked.

**Comment by adiig7** [comment]
@anushkrishnav can you please add GSSOC 2021 label to it?
