### ISSUE TITLE
Adjacency list representation of graph

### ISSUE THREAD

**Issue by aish2002** [HarshCasper/NeoAlgo#2572]
## 🚀 Feature

As a GSSOC'21 participant I would like to implement the most efficient representation of graph in C

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Graph is an important data structure

## Pitch
An efficient representation is required for graph as it is used in solving a wide variety of problems

**Comment by anushkrishnav** [comment]
what do you mean by representation also before you reply take a look at [this](https://github.com/TesseractCoding/NeoAlgo/tree/master/C/graphs) and check if it's been implemented already

**Comment by aish2002** [comment]
Graph can be represented using linked list rather than a matrix and is more efficient in terms of memory. I intend use 2 linked lists - one for the nodes and one for the edges corresponding to each node . This is not implemented in this repo

**Comment by siddharth25pandey** [comment]
@aish2002 Assigned. Make sure you follow proper coding and formatting standards. All the very best

**Comment by aish2002** [comment]
Sure. Thank you
