### ISSUE TITLE
Snake Game in Python

### ISSUE THREAD

**Issue by Swetha126** [HarshCasper/NeoAlgo#2573]
## 🚀 Feature

I would like to add a snake game using python to this project.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes i have read the guidelines clearly

## Motivation

I wish to contribute a fun, interactive and user friendly snake game. 

## Pitch

I would be implementing this using GUI programming and the special libraries available in python.

I am a GSSOC'21 participant and wish to contribute to this project. Can you please assign me this issue?

**Comment by Swetha126** [comment]
Hello @bhav09 ! 
I have given the pull request for this issue. Do have a look at it and let me know the changes if any.
Thank you!

**Comment by bhav09** [comment]
@Swetha126 can you please link the PR here. That would be helpful.

**Comment by Swetha126** [comment]
Ya sure will do!
