### ISSUE TITLE
Selection Sort & Radix Sort in JavaScript sorting

### ISSUE THREAD

**Issue by micky2001** [HarshCasper/NeoAlgo#2574]
Selection Sort & Radix Sort in JavaScript sorting

**Comment by bhav09** [comment]
Quicksort is there already.  You can go for Selection and Radix Sort. All the best

**Comment by gat786** [comment]
Quicksort is already available in our JS library of things. But good to go for Selection sort.

**Comment by gat786** [comment]
Also, I just now noticed your title as well as description are of two different topics.

![image](https://user-images.githubusercontent.com/22629774/110672964-379e6f00-81f6-11eb-9467-d28fbf6dcd39.png)

Stop trolling man

**Comment by micky2001** [comment]
Sorry Sir for the mistake!!
I was about to write Radix sort but by mistake submitted the issue with Quick sort
This is my first attempt in open source
Won't repeat this again

**Comment by bhav09** [comment]
No worries @micky2001 we understand. Do your best. Keep learning.

**Comment by gat786** [comment]
Also dont spam 5 issues at a time. Take your time and do small incremental steps. Its easier for you as well as for us to maintain a flow.
