### ISSUE TITLE
Issue in Readme file in Sorting Algorithms for Python

### ISSUE THREAD

**Issue by noviicee** [HarshCasper/NeoAlgo#2575]
## 📚 Documentation

Hey! What is up with the readme file present in the Sorting Algorithms in Python. It just contains a letter 'a'. Do you want to modify it or clean it, or maybe add some description about the folder or files or anything else in it?
If yes, I am ready to make it better. U can assign it to me :)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

**Comment by bhav09** [comment]
Go for it. @noviicee

**Comment by noviicee** [comment]
Thank you @bhav09 
So basically do I need to just clear it or add some information to it..??

**Comment by bhav09** [comment]
Write a readme file that would tell more about the subfolder. You can refer a few readme files of a few subfolders that have already been set up. Good luck.

**Comment by noviicee** [comment]
Okay. Up to it!

**Comment by noviicee** [comment]
> Okay. Up to it!

Can you add GSSOC'21 tag on this one..?

**Comment by bhav09** [comment]
Sure

**Comment by noviicee** [comment]
Actually a label tag denoting the level of this issue also should be added as they won't accept contributions without the label tag :)
I think the level 0 would be okay for this one because it is a short document change.

**Comment by bhav09** [comment]
We have an "easy" tag for that. Can surely add it.

**Comment by noviicee** [comment]
Done and created a PR.
But I don't understand why  *DeepSource: Java (beta)*  test is failing..

**Comment by bhav09** [comment]
Your PR will be reviewed soon. Ignore that check error as of now. 
Also, mention the link to your PR, I will review it.

**Comment by noviicee** [comment]
@bhav09 
Here is the link- https://github.com/TesseractCoding/NeoAlgo/pull/2992
