### ISSUE TITLE
Celebrity problem(Stack Data structure) in C++ DS

### ISSUE THREAD

**Issue by micky2001** [HarshCasper/NeoAlgo#2576]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
The problem is, 
In a party of N people, only one person is known to everyone. Such a person may be present in the party, if yes, (s)he doesn’t know anyone in the party. We can only ask questions like “does A know B? “. Find the stranger (celebrity) in the minimum number of questions.

**Comment by gat786** [comment]
Atleast, complete the issue template which we have provided in-order for us to assign them to you. 

`(A clear and concise description of what the proposal is.)` is something which should be filled by you

Also you removed the checkboxes in which you had to agree for doing things
