### ISSUE TITLE
Rotation Of a number in C++ math

### ISSUE THREAD

**Issue by micky2001** [HarshCasper/NeoAlgo#2577]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
The problem statement is,
Given an integer n & number of rotation k, the task is to generate all the left shift or right numbers possible. A left shift number is a number that is generated when all the digits of the number are shifted one position to the left by k rotation  and the right shift is when all the digits of the number are shifted one position to the right by k rotation.

Ex:
N= 253896, k = 2
Output: 962538
For k= -2
Output : 389625

**Comment by bhav09** [comment]
@micky2001 you need to mention what your approach is and what you are trying to do in the proposal. Please write in it for us to understand what you are trying to do and if it has not been added already in the repo you would be assigned the task. 
Closing the issue.
