### ISSUE TITLE
Duplicate Bracket using Stack C++

### ISSUE THREAD

**Issue by micky2001** [HarshCasper/NeoAlgo#2578]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by gat786** [comment]
Stop spamming issues left and right
