### ISSUE TITLE
Next greater element, Stock Span & Largest Area Histogram using stack C++

### ISSUE THREAD

**Issue by micky2001** [HarshCasper/NeoAlgo#2579]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by bhav09** [comment]
@micky2001  you need to write and tell us more about your contribution to the selected area. That would really be helpful.
Thanks
![image](https://user-images.githubusercontent.com/50860603/110672791-06be3a00-81f6-11eb-8714-d8875a906c75.png)
![image](https://user-images.githubusercontent.com/50860603/110672859-19387380-81f6-11eb-84ee-f8282717353d.png)

Closing the issue.
