### ISSUE TITLE
Implementation of Ackermann Function using C++

### ISSUE THREAD

**Issue by anushkasethi1710** [HarshCasper/NeoAlgo#2580]
## 🚀 Feature

Ackermann's function is a recursive mathematical algorithm that can be used to test how well a computer performs recursion. Write a function A(m,n) that solves Ackermann's function. Use the following logic in your function:

If m=0 then return n+1
If n=0 then return A(m-1,1)
Otherwise, return A(m-1, A(m, n-1))

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

This function depicts how there can exist a function that can only be executed recursively and especially because it provides a counterexample that every function that is computed can be computed primitive recursively.

**Comment by gat786** [comment]
Sorry to say but @anushkasethi1710 this function is already present in our library. 

You are free to do any other function or improve the current implementation of things if you find any bugs in it. But I can't assign this issue to you.
