### ISSUE TITLE
Height of a binary tree in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2581]
## 💥 Proposal

I would like to add the code of Height of a binary tree in C++.Please assign me this issue.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by bhav09** [comment]
@SAY-droid427, it already exists. You can try improving it or open an issue that is completely new to us. 
Closing the issue.
