### ISSUE TITLE
C++ Program of Fast Exponentiation using Bit Masking

### ISSUE THREAD

**Issue by anushkasethi1710** [HarshCasper/NeoAlgo#2583]
## 🚀 Feature

Helps user find Fast Exponentiation of a number using the method of Bit Manipulation.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by atarax665** [comment]
Assigned @anushkasethi1710.
Happy coding!

**Comment by anushkasethi1710** [comment]
Thank you :)
