### ISSUE TITLE
Bubble Sort in C#

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2584]
## 🚀 Feature

Adding bubble sort code in C# language.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by bhav09** [comment]
It already exists. We encourage you to have a look at the issues/files that are already there in the repo before raising the issue. 
Closing. 
Happy coding :)
