### ISSUE TITLE
Reverse individual words of a string using stacks

### ISSUE THREAD

**Issue by taruni-always** [HarshCasper/NeoAlgo#2585]
## 🚀 Feature

The idea is to reverse the individual words of the input string with the help of stacks.
Sample input:  Bring me food
Sample output: gnirB em doof

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

I want to contribute to it under GSSoC '21
## Pitch

It is a good application for stack data structure. I would like to take up this task to implement it in C and/or Python.

**Comment by bhav09** [comment]
Assigning to you. All the best. 
Happy Learning

**Comment by SrinivasRedyy221** [comment]
hello Im a participant at GSSoC'21
i want to work the issue in c.

**Comment by taruni-always** [comment]
Thank you for assigning this to me @bhav09 . 
This particular code goes into ds folder of the respective languages, am I right? (Just making sure)

**Comment by bhav09** [comment]
Yes, it does. @taruni-always 
@SrinivasRedyy221 you can check if its done already for C or not. If not then you can open the issue and I will assign it to you.

**Comment by taruni-always** [comment]
@bhav09 Okay, thanks. ALso, I'm doing this in C and Python.

**Comment by bhav09** [comment]
We would be able to merge only for what the issue was raised initially. We encourage you to do it with C++ as of now. 
Happy Learning!

**Comment by taruni-always** [comment]
@bhav09 The issue was raised for C and python initially. I have mentioned it in the issue clearly.

**Comment by bhav09** [comment]
Oh, I am sorry, you can proceed with C and Python.

**Comment by taruni-always** [comment]
It's okay. Small doubt, should I make two separate PRs?

**Comment by bhav09** [comment]
One would work.

**Comment by taruni-always** [comment]
Okayy. Thank you.

**Comment by taruni-always** [comment]
Please add the level labels for this.
