### ISSUE TITLE
Sorting the elements of a stack in C

### ISSUE THREAD

**Issue by Tanya170620** [HarshCasper/NeoAlgo#2596]
## 🚀 Feature

It will sort the elements of the stack in ascending order without defining any extra user defined stack.
Language: C

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute to it under GSSoC'21.

## Pitch

It is a good application for stack data structure. I would like to take up this task to implement it in C.

**Comment by kavyasree-123** [comment]
Hi ,i'm a gssoc'21 participant ,thank you for giving us this chance, very excited as a beginner want solve this issue. i've read all the guidelines and will give a good structure to code and description ,very much good at c programming .
please assign it to me

**Comment by gat786** [comment]
@kavyasree-123 @Tanya170620 has created this issue for her to work on it. If she permits you to take this issue on behalf of her we can arrange that. But for GsSOC we will assign the issue to the person who has created it. Hope that makes sense.

**Comment by gat786** [comment]
Also try defining your proposal in a better way next time around @Tanya170620.

**Comment by Tanya170620** [comment]
Sure, I will keep that in mind. Thank you. @gat786

**Comment by Tanya170620** [comment]
@gat786 Could you please give the GSSoC'21 label.

**Comment by Vishal-Singh-1996** [comment]
I would like to solve this problem in java pls assign it to me...
@gat786 @Tanya170620

**Comment by gat786** [comment]
Create a new issue with detailed description
