### ISSUE TITLE
Numpy Library

### ISSUE THREAD

**Issue by Vrindagupta6828** [HarshCasper/NeoAlgo#260]
**Algorithm:** Image analysis by numpy

**DS:** 

**Languages Supported:** Python

**Comment by Vrindagupta6828** [comment]
I want to work on it @HarshCasper

**Comment by vgb-codes** [comment]
What dataset and techniques will you be using?

**Comment by Vrindagupta6828** [comment]
Hello @VijayaGB98
I will be using a single image from my system which could be replaced by any image replacing just the path.I will use numy library to do that by creating mask and rgb intensity .

**Comment by vgb-codes** [comment]
Will you be doing other functions like gamma, binarization and slicing?

**Comment by Vrindagupta6828** [comment]
@VijayaGB98 yes a little bit

**Comment by vgb-codes** [comment]
@Vrindagupta6828 I'll assign you this issue, Me and my teammates will review it when you submit a PR.

**Comment by Vrindagupta6828** [comment]
Ok thank you

**Comment by Vrindagupta6828** [comment]
I have issued a pull request please merge it. #300

**Comment by atarax665** [comment]
@Vrindagupta6828 Are you still working on this?

**Comment by atarax665** [comment]
@Vrindagupta6828 Leave a comment if you are still working on it.
