### ISSUE TITLE
C++ program to check if the number is a Lucky Number or not.

### ISSUE THREAD

**Issue by eksdee-sama** [HarshCasper/NeoAlgo#2600]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(I am a GSSOC'21 participant. I noticed Lucky Numbers program was not present here in any of the languages ,So I thought of adding it in C++)

## Pitch

(In number theory, a lucky number is a natural number in a set which is generated by a certain "sieve". This sieve is similar to the Sieve of Eratosthenes that generates the primes, but it eliminates numbers based on their position in the remaining set, instead of their value (or position in the initial set of natural numbers).
Start with a rundown of numbers beginning with 1: 

1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	16	17	18	19	20	21	22	23	24	25 

Consistently number (every much number) in the rundown is dispensed with, leaving just the odd numbers: 

1		3		5		7		9		11		13		15		17		19		21		23		25 

The main number excess in the rundown after 1 is 3, so every third number which stays in the rundown (only one out of every odd various of 3) is dispensed with. The first of these is 5: 

1		3				7		9				13		15				19		21				25 

The following enduring number is presently 7, so every seventh leftover number is disposed of. The first of these is 19: 

1		3				7		9				13		15						21				25 

Keep eliminating the nth leftover numbers, where n is the following number in the rundown after the last enduring number. Next in this model is 9. 

A liveliness showing the lucky number sifter. The numbers on a red foundation are lucky numbers. At the point when a number is disposed of its experience changes from dark to purple. 

One way that the use of the technique contrasts from that of the Sieve of Eratosthenes is that for n being the number being duplicated on a particular pass, the main number dispensed with on the pass is the n-th staying number that has not yet been wiped out, instead of the number 2n. In other words, the rundown of numbers this sifter tallies through is distinctive on each pass (for instance 1, 3, 7, 9, 13, 15, 19... on the third pass), though in the Sieve of Eratosthenes, the sifter consistently tallies through the whole unique rundown (1, 2, 3...). 

At the point when this method has been done totally, the leftover whole numbers are the lucky numbers: 

1, 3, 7, 9, 13, 15, 21, 25, 31, 33, 37, 43, 49, 51, 63, 67, 69, 73, 75, 79, 87, 93, 99, 105, 111, 115, 127, 129, 133, 135, 141, 151, 159, 163, 169, 171, 189, 193, 195, 201, 205, 211, 219, 223, 231, 235, 237, 241, 259, 261, 267, 273, 283, 285, 289, 297, ...)

**Comment by eksdee-sama** [comment]
I would like to take up this issue and solve it with a brief description and with proper code and test cases. Please assign me this issue

**Comment by Prakash-poka** [comment]
yeah seems good for this project
