### ISSUE TITLE
Removing spaces from a String in C++

### ISSUE THREAD

**Issue by RaiyanMahin** [HarshCasper/NeoAlgo#2604]
## 🚀 Feature

The feature is removing spaces from a string in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

As a GSSOC'21 participant I would like to contribute to this project.

## Pitch

This feature can be implemented in C++ by using getline function and stringstream. In Competitive Programming,  for string related problems we need to remove spaces to get our expected output.

**Comment by agamgupta2015** [comment]
I want to work on this issue in C++ as a part of GSSOC'21
