### ISSUE TITLE
Generating BST from it's Preorder Traversal

### ISSUE THREAD

**Issue by sakshigoel19** [HarshCasper/NeoAlgo#2605]
Given preorder traversal of a binary search tree, construct it's Binary search tree.

 Have you read the [Contributing Guidelines on Pull Requests] Yes

Please assign me it under GSSOC'21.

**Comment by sakshigoel19** [comment]
@bhav09  I would like to do it in C++ with proper documentation.

**Comment by gat786** [comment]
The description you have provided is incomplete and I would recommend you to check it and improve it again.

**Comment by bhav09** [comment]
Hey @sakshigoel19 if you can please help us with detailed information about the issue along with the language you will be implementing it in. That would really be helpful.

**Comment by btanisha** [comment]
Hey, I'm a GSSOC participant, and the complete problem statement should be Generating BST from preorder and inorder traversal. I can write well-documented code in C/C++ with proper explanation and comments. @gat786 please assign it to me.

**Comment by sakshigoel19** [comment]
@gat786  Preorder traversal of a binary tree is given as an array. For a BST, inorder traversal is simply the ascending order of the given preorder traversal so it is not needed separately. The output is root of the BST constructed. I will write well documented code in C++ giving an iterative solution which works in O(n) time. Please assign me this issue.

**Comment by bhav09** [comment]
All the best. Assigned.

**Comment by gat786** [comment]
Looks great. I want to see this kind of issue creation request next time around.

**Comment by sakshigoel19** [comment]
Okay! Thank you so much.

**Comment by neha07kumari** [comment]
Hey! myself a GSSOC'21 participant.
I would like to work on this issue using C++. Please assign me @bhav09
