### ISSUE TITLE
[GSSoC 21 ] Proposal to add a new folder for Julia 

### ISSUE THREAD

**Issue by Saviour1001** [HarshCasper/NeoAlgo#2607]
## 💥 Proposal

The Github repo already consists of multiple languages. Julia is a language that is built for faster mathematical calculations. It has the speed of C++ and syntax similar to Python. Currently, there are not many platforms where one could practice DSA in Julia and thus I want to add the algorithms in a new folder named "Julia". I could add code in the forms of .jl files and jupyter notebooks with the kernels of Julia. This way we could enhance the diversity of the project and adding a new language such as Julia would be a cool feature of the repo. 
I aim to add multiple algorithms in the Julia folder and want to contribute to it for a long time.

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

**Comment by gat786** [comment]
If you are up for a challenge and know about Julia enough and think that you can take this task forward I will assign it to you.

**Comment by Saviour1001** [comment]
I am learning still. I know the basics of Julia and want to go further in the language. I could apply basic DSAs such as Recursions and Dictionaries. I am willing to learn on the go and also share whatever Algos I make. I have opened a discussion in the repository where I have shown a sample code about how will the code files look like. I am willing to take the challenge of adding multiple algorithms in Julia. 
I have this one doubt though, should I mention a new issue for each algorithm I want to add to the repository as I also want these contributions to get counted under GSSoC.  @gat786

**Comment by gat786** [comment]
Well if you want your efforts to be counted towards GsSOC then you should do as per the program requirements. And I think they assign points per successful PR. So you would have to go throught that hoop. You should confirm that with officials though. Let me have a look at the code sample you have submitted before assigning this issue to you.

**Comment by Saviour1001** [comment]
Fine I will go as per the process. Could you right now assign me the issue of adding a folder of Julia with a couple of basic algorithms? Will need to add the changes to the main ReadMe as well about adding a new language.

**Comment by Saviour1001** [comment]
@gat786  have a look at this Github repo of mine. I want to add similar codes in NeoAlgo.
[Repo](https://github.com/Saviour1001/Julia_Competitve_Coding)

**Comment by Saviour1001** [comment]
I want to add Kadane's algorithm at First

**Comment by HarshCasper** [comment]
I'm closing this Issue. Start making individual issue and work on the same. I have created the `Julia` tag now
