### ISSUE TITLE
Linear Search in kotlin

### ISSUE THREAD

**Issue by nagasrihith608** [HarshCasper/NeoAlgo#2609]
## 🚀 Feature

Linear Search algorithm in Kotlin.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

To add this new feature to linear search in Kotlin

Respected @HarshCasper, Please assign me this issue under GSSOC'21.

**Comment by gat786** [comment]
Have fun!
