### ISSUE TITLE
JumpSearch implementation in C

### ISSUE THREAD

**Issue by nidh-ish** [HarshCasper/NeoAlgo#2611]
## 🚀 Feature

Jump sort algorithm implementation in C language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To add this new feature.

Please assign this feature to me under GSSOC'21.

**Comment by nidh-ish** [comment]
Is someone going to assign this issue to me?

**Comment by nidh-ish** [comment]
@bhav09 @ankitaggarwal23 @gat786 ??

**Comment by bhav09** [comment]
We are flooded with contributors requesting for PRs and Issues. Sorry for the delay, hope you understand.

**Comment by nidh-ish** [comment]
Yeah, I understand. Thanks for assigning the issue. And sorry for bothering you.

**Comment by bhav09** [comment]
Anytime bro :)
Happy learning!
