### ISSUE TITLE
Converting decimal number to binary in C++ language 

### ISSUE THREAD

**Issue by SrishtiArya07** [HarshCasper/NeoAlgo#2612]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Hereby using this code, one can convert the decimal number into its equivalent binary number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

## Motivation

(Please outline the motivation for the proposal.)
I found this basic math problem that is widely used in competitive programming missing, and hence want to add its solution.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This problem will be very useful for understanding the basic concepts of binary numbers. 
As a GSSoC'21 participant, I would like to add the solution to this problem in the C++ language. 
Please assign it to me.

**Comment by agamgupta2015** [comment]
I want to work on this issue in C++ as a part of GSSOC'21

**Comment by Tanya170620** [comment]
I would like to do this in C as a part of GSSoC'21.

**Comment by ghost** [comment]
Can i contribute with java and python
