### ISSUE TITLE
Nth fibonacci number in series 

### ISSUE THREAD

**Issue by srisatya12** [HarshCasper/NeoAlgo#2613]
## 🚀 Feature

Finding nth fibonacci number in the series using c language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I did

## Motivation
I presume that as it's a beginner friendly code it might be helpful for the upcoming noobs

## Pitch
When I was learning a language I felt that writing a code for a given program doesn't improve skills but we need to have an idea how the program can be asked in different ways. If the  mentors or the organisers of this project feels that this programm is good ,please assign me this issue as a participants of GSSOC'21 I would like to add solution for this program.

**Comment by agamgupta2015** [comment]
I want to work on this issue in C++ as a part of GSSOC'21

**Comment by priyanka001tech** [comment]
I want to work on this issue in C++ as well as java as a part of GSSOC'21. So please assign me.

**Comment by ishitakapoor26** [comment]
I want to work on this issue in C++ as a part of GSSOC'21

**Comment by Priyanshu078** [comment]
I am a GSSOC participant 
Please assign me this issue

**Comment by srisatya12** [comment]
This issue was created by @srisatya1197 but may I know why the issue is assigned to @ishitakapoor26
