### ISSUE TITLE
Snake game in Java

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#2617]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Kindly allow me to implement the 2D snake game in Java as a part of GSSOC'21.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes, I have.
(Write your answer here.)

**Comment by Varun8216889** [comment]
As I am a beginner, Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me.
