### ISSUE TITLE
Guessing Number game in python 

### ISSUE THREAD

**Issue by soumikbaithalu** [HarshCasper/NeoAlgo#2620]
## 🚀 Feature

I would like to add a Gussing number game using python to this project.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes I have read the guidelines clearly

## Motivation

I wish to contribute a fun, interactive, and user-friendly guessing number game.

## Pitch

I am a GSSOC'21 participant and wish to contribute to this project. Can you please assign me this issue?

**Comment by Naman-12911** [comment]
Hello sir I want to solve this issue please assign me under GSSOC.

**Comment by soumikbaithalu** [comment]
@Naman-12911 I have completed the code I waited for admin to merge it you can look other issues

**Comment by Naman-12911** [comment]
Ohk fine
