### ISSUE TITLE
Sleep Sort in C#

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2621]
## 🚀 Feature

Adding sleep sort program in C# language.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

GSSOC 2021.

**Comment by gat786** [comment]
Thanks for contributing 😉
