### ISSUE TITLE
Evaluation of polynomial using linked list in C

### ISSUE THREAD

**Issue by Vishruta-Patil** [HarshCasper/NeoAlgo#2625]
## 🚀 Feature
Create , Display and evaluate polynomial using linked list in C
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes
(Write your answer here.)

## Motivation
As a GSSOC participant I want to contribute in the project using my knowledge and help others to learn and grow as well.
(Please outline the motivation for the proposal.)

## Pitch
We use polynomials to model the curves also polynomials  are used to design roads, buildings and other structures.  I want to contribute and help others to solve the problem.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by Vishruta-Patil** [comment]
I would like to work on this issue as a GSSOC participant

**Comment by Astha-glitch** [comment]
I would love to contribute to it as a participant of GSSoC'21

**Comment by Vishruta-Patil** [comment]
@HarshCasper @iamrajiv can you please assign me the issue

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 can you please assign me this issue
