### ISSUE TITLE
number of trailing zero's in a factorial

### ISSUE THREAD

**Issue by ASLManasa** [HarshCasper/NeoAlgo#2626]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes 

## Motivation

For large numbers is tough to calculate manually.  it would be useful for new coders.

## Pitch
It logic is important. it would be uself to improve coding skills and how to approach a problem.
As a GSS0C'21 particiant i want You to please assign this issue to me I would like to work on this.

**Comment by priyanka001tech** [comment]
I want to work on it. I can code it. I have read the Contributing Guidelines on Pull Requests. As a GSS0C'21 particiant i want You to please assign this issue to me.

**Comment by Mohitmadhav** [comment]
Hello, I'm a GSSoC participant.
Can I work on this issue, please?

**Comment by simarjeet30** [comment]
I am simarjeet ,gssoc 21 participant , I want to work on this issue in c++/c .please assign this to me .
