### ISSUE TITLE
Roots of Quadratic equation in Java [math]

### ISSUE THREAD

**Issue by nagasaisriya** [HarshCasper/NeoAlgo#2628]
## 🚀 Feature
Solving Quadratic equations in Java-A program that prints all real solutions to quadratic equation ax^2+bx+c=0, if discriminant is negative displays a message "roots are imaginary".
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.
## Motivation
I would like to contribute to this project under GSSOC'21.
(Please outline the motivation for the proposal.)

## Pitch
Quadratic equations are actually used in everyday life, as when calculating areas, determining a product's profit or formulating the speed of an object
(Please explain why this feature should be implemented and how it would be used.)
`/assign`

**Comment by nagasaisriya** [comment]
Can you please assign me this issue?

**Comment by harshvs7** [comment]
I would like to work on it as a part of GSSOC'21.
Can you please assign the work to me?
