### ISSUE TITLE
Digits in Factorial C++ 

### ISSUE THREAD

**Issue by nagasaisriya** [HarshCasper/NeoAlgo#2633]
## 🚀 Feature
Given an integer N. Find the number of digits that appear in its factorial.[works for large integers too]
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
I would like to contribute to this project under GSSOC
(Please outline the motivation for the proposal.)

## Pitch
The factorial operation is encountered in many areas of mathematics, notably in combinatorics, algebra, and mathematical analysis.
(Please explain why this feature should be implemented and how it would be used.)
`/assign`

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.
