### ISSUE TITLE
Contributor's Handbook for better Contributions

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#2638]
## Introduction 

Over the period of reviewing more than 1,500+ Pull Requests for the past few months, we realized that contributors always remain at a loss of how they can land good contributions. 

To tackle, this we have built a **Contributor's Handbook**, especially for the first-time and experienced contributors who will be working on NeoAlgo for the next one month and even beyond. 

The handbook that runs almost 20+ Pages, is expected to be consumed fully in a binge-read that would introduce you to how your review process goes like, the best Git workflow that we are expecting, and how we invalidate the Pull Requests from some of the new contributors. 

Here is the Google Doc Link: https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/ 

If you found it too long to read, here are some of the highlighted points: 

* Contribution Workflow 
     - Exploring the Project 
     - Making your first Issue
     - Making your first Pull Request
     - Reviewing your Pull Request 
 * Style Guidelines 
     - Flow
     - Directory Naming
     - Code Formatting
     - Automated Tools
 * Continuous Integration Checks
     - Assigning the Reviewers 
     - Issue/PR Labeller
     - Stale Action
     - DeepSource
 * Adding a Proposal 
 * Maintainer Notes 
    - Plagiarism 
    - Taking up Issues
    - Pull Request Reviews 
    - Be Nice, Be Respectful
 * How to ask for help?

One thing that I would like to highlight: Take this handbook **seriously**. We have been reviewing a lot of bad PRs that would not be eventually merged and we don't want it to happen at any time. As a new contributor, we want you to make quality contributions and reach out to the people who can help. 

If you have any suggestions, drop them as a comment on the Google Doc.

Thanks!

**Comment by i-shreyagarg** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by HarshCasper** [comment]
> I am a participant of GSSOC'21
> I would like to contribute in this

This is not an issue you can contribute to. It is a handbook for everyone to read.
