### ISSUE TITLE
Lowest Common Ancestor in Binary Search Tree

### ISSUE THREAD

**Issue by Jassi10000-zz** [HarshCasper/NeoAlgo#2639]
## 🚀 Feature

(A clear and concise description of what the feature is.)
To find LCA ( Lowest Common Ancestor ) in BST.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

## Motivation

(Please outline the motivation for the proposal.)
I would like to contribute to NeoAlgo under GSSOC'21
I already have made the changes to my forked version of this project  in Java Folder, just waiting to be assigned and will make a quick PR

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
Binary Search Trees are one of the favourite topics of interviewers , these days new questions are evolving in every interview , so the ques am gonna contribute to the repo is being asked a lot these days in interviews.

**Comment by vanshika2906** [comment]
I would like to work to NeoAlgo under GSSOC'21. Kindly assign it to me. Thank you!

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description and best time complexity .
please assign me this issue.

**Comment by Jassi10000** [comment]
@HarshCasper  I have opened the issue 7 days back , also done with the code in forked version , can you please assign this to me , would be grateful

**Comment by Jassi10000-zz** [comment]
@anushkrishnav Sir I have opened this issue 9 days ago , but still no one has assigned me yet , am ready with the code , can you please assign it to me  with " GSSOC "  and associated " Level "  so that I can move forward with my PR

**Comment by anushkrishnav** [comment]
> @anushkrishnav Sir I have opened this issue 9 days ago , but still no one has assigned me yet , am ready with the code , can you please assign it to me with " GSSOC " and associated " Level " so that I can move forward with my PR

It means that you have not read the guidelines or actively following the issues you can self assign it by using '/assign'

**Comment by Jassi10000-zz** [comment]
> > @anushkrishnav Sir I have opened this issue 9 days ago , but still no one has assigned me yet , am ready with the code , can you please assign it to me with " GSSOC " and associated " Level " so that I can move forward with my PR
> 
> It means that you have not read the guidelines or actively following the issues you can self assign it by using '/assign'

Actually I got to know about that 2 days back only , I didnt read that 9 days ago , 
I even tried  to  ' /assign ' in this issue  but till 1 hour the bot didn't assigned me the issue , that's why was confused
anyways  thanks for helping sir

**Comment by anushkrishnav** [comment]
Ahh no worries I think it's all good now if you need any more guidance feel free to tag me also read the guidelines properly will clear most of the doubts

**Comment by Jassi10000-zz** [comment]
Sure sir @anushkrishnav  , thank you
