### ISSUE TITLE
Kruskal's Minimum Spanning Tree Algorithm

### ISSUE THREAD

**Issue by sonalsingh25** [HarshCasper/NeoAlgo#2641]
## 💥 Proposal

Hi . I would like to add this important algorithm in your project in the Greedy Algorithms section.. My folder will go as NeoAlgo/Java/Greedy_Algorithms/
I request you to assign this issue. I'll for sure abide by the rules and the code of conduct.

**Comment by gat786** [comment]
Have you read the code of conduct? Those checkboxes act as an indication that you have done the things mentioned with it. I would recommend you to not remove them next time onwards.

Also this seems like a good addition to our repository so I will assign it to you!

**Comment by sonalsingh25** [comment]
I am really Sorry Sir . I thought it was only for my reference. I am also a gssoc participant so please add that label too . And I have created a PR please check on that whenever it suits you.
