### ISSUE TITLE
Adding and deleting elements in a linked list python

### ISSUE THREAD

**Issue by AbhignaSowgandhika02** [HarshCasper/NeoAlgo#2643]
## 🚀 Feature
This will enable us to add or delete elements from the beginning, end or in between a Linked List using python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes, I have.

## Pitch
This feature should be implemented because it is necessary to know how to add or delete nodes from a list.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by sandeepN06** [comment]
Hello can you please assign it to me . I am ready to solve this issue
