### ISSUE TITLE
Three way - Merge Sort In C++ (GSSOC'21)

### ISSUE THREAD

**Issue by Harikrishnan6336** [HarshCasper/NeoAlgo#2647]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
3 way merge sort is a variant of merge sort in which the array is split into three subarrays.
I would like to implement the same in C Plus Plus(C++) as part of GSSOC'21

Kindly assign this issue to me.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.
