### ISSUE TITLE
Palindrome Linked List

### ISSUE THREAD

**Issue by salma2vec** [HarshCasper/NeoAlgo#2652]
## 🚀 Feature

(A clear and concise description of what the feature is.)
This will enable us to check if a given linked list is a palindrome using Java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read it thoroughly.
## Motivation

(Please outline the motivation for the proposal.)
I would like to contribute to this project as a participant at GSSoC'21.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This feature should be implemented because it is necessary to know how to identify whether the given singly linked list is a palindrome or not.

**Comment by salma2vec** [comment]
I have made a PR for the same. Kindly merge it. #2891

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
