### ISSUE TITLE
Competitive Programming: Sort Colors

### ISSUE THREAD

**Issue by Anshika-Srivastava** [HarshCasper/NeoAlgo#2653]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I want to add a question in Competitive Programming section.
Question: 
Given an array nums with n objects colored red, white, or blue, sort them in-place so that objects of the same color are adjacent, with the colors in the order red, white, and blue.

We will use the integers 0, 1, and 2 to represent the color red, white, and blue, respectively.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Answer: Yes
(Write your answer here.)
I would like to provide my approach for this question in C++. Please assign this to me.

**Comment by gat786** [comment]
I have assigned it to you. Whenever you make a pr mention this issue.
