### ISSUE TITLE
Mathematics: Happy Number

### ISSUE THREAD

**Issue by Anshika-Srivastava** [HarshCasper/NeoAlgo#2654]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Question:
Write an algorithm to determine if a number n is happy.

A happy number is a number defined by the following process:

Starting with any positive integer, replace the number by the sum of the squares of its digits.
Repeat the process until the number equals 1 (where it will stay), or it loops endlessly in a cycle which does not include 1.
Those numbers for which this process ends in 1 are happy.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Answer: Yes
(Write your answer here.)
I would like to contribute my approach for this question in  c++. Please assign this to me!

**Comment by gat786** [comment]
You have two issues in your hand now. Please complete these before adding another issue. Happy Contributing 🎉🥳

**Comment by Anshika-Srivastava** [comment]
Thank you so much!
