### ISSUE TITLE
0 absent in Fibonacci Series

### ISSUE THREAD

**Issue by Prakash-poka** [HarshCasper/NeoAlgo#2662]
## 🐛 Bug Report

In the file Fibonacci.py, the code prints the Fibonacci series excluding the initial 0.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Prakash-poka** [comment]
Please assign me this issue.

**Comment by sargun06** [comment]
Assign me this bug
