### ISSUE TITLE
Vernam cipher implementation in C 

### ISSUE THREAD

**Issue by nidh-ish** [HarshCasper/NeoAlgo#2663]
## 🚀 Feature

Through this code, I will be implementing Vernam cipher in the C language. It is a symmetric key cryptographic algorithm in which the size of the plain-text and the key is the same.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Vernam cipher also known as a one-time pad follows the principle of perfect secrecy. I would like to implement this in the C language.

## Pitch

Please assign this to me under GSSOC'21.

**Comment by chiragagrawal9200** [comment]
@bhav09 @gat786 @iamrajiv @Apoorve73 I would like to work on this issue...please assign it to me. I am a gssoc participant.

**Comment by nidh-ish** [comment]
@bhav09 When are you going to assign?
