### ISSUE TITLE
Tower of Hanoi in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2664]
## 💥 Proposal

I want to add the code for Tower Of Hanoi in C++.Please assign this issue to me[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by priyanka001tech** [comment]
I want to work on it.I can code it in c++. I have read the Contributing Guidelines on Pull Requests. So Please assign me

**Comment by Rutikab12** [comment]
Hey I am GSSoC'21 participant. I will love to contribute to this issue using iterative/recursive approach in c++. If possible assign it to me in anyone of the approach.

**Comment by SAY-droid427** [comment]
@bhav09 @HarshCasper Please assign this issue to me so that I can start working on it. I had opened this issue on 11/3/21

**Comment by bhav09** [comment]
I am assigning you the task @SAY-droid427

**Comment by manasvvi1** [comment]
please assign this issue to me, i would like to work in cpp.
