### ISSUE TITLE
Implementing Sieve of Atkin in C++ and C (GSSOC '21)

### ISSUE THREAD

**Issue by ShubhamGupta577** [HarshCasper/NeoAlgo#2665]
### Sieve of Atkin
Sieve of Atkin is a modern algorithm for finding all prime numbers up to a specified integer. Compared with the ancient **Sieve of Eratosthenes,** which marks off multiples of primes, the **Sieve of Atkin does some preliminary work and then marks off multiples of squares of primes,** thus achieving a better theoretical asymptotic complexity.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

To add a more efficient method for generating prime numbers

## Pitch
As compared to other algorithms for generating prime numbers under a range, it has better asymptotic complexity
* **Time Complexity - O(N/ log log N)**
* **Space Complexity - O(N^0.5)**

**Comment by ShubhamGupta577** [comment]
I want to implement it in C and C++ under GSSOC '21.

**Comment by ShubhamGupta577** [comment]
@bhav09 Please assign me this issue.

**Comment by bhav09** [comment]
Hey sure!
