### ISSUE TITLE
Java Program to check whether number is Armstrong or not

### ISSUE THREAD

**Issue by neha-baisane** [HarshCasper/NeoAlgo#2666]
## 🚀 Feature
Program in Java to check whether the number is Amstrong or not.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
As a GSSOC'21 participant I would like to work on this issue. 

## Pitch
For every programmer basic should be clear hence this is one of the most useful program for students to practise.

**Comment by priyanka001tech** [comment]
I want to work on it.I can code it in java. I have read the Contributing Guidelines on Pull Requests. So Please assign me

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by neha-baisane** [comment]
when will the issue get assigned?

**Comment by Priyanshu078** [comment]
I am a GSSOC participant, Can I work on this issue, I can code it in Java programming language.

**Comment by neha-baisane** [comment]
@bhav09 please assign me this issue.
