### ISSUE TITLE
Rod cutting Dynamic problem in C++

### ISSUE THREAD

**Issue by Priyanka7011** [HarshCasper/NeoAlgo#2667]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Rod cutting problem is a famous DP problem and I would love to share my code with others.

## Motivation

GSSOC 2021 participant.

## Pitch
It is a basic problem and implementation of this will help students to understand dp problems better

**Comment by Madhvi19** [comment]
I want to work on this.

**Comment by Priyanka7011** [comment]
also please add GSSOC21 label
