### ISSUE TITLE
Rail Fence Cipher in C language[GSSOC'21]

### ISSUE THREAD

**Issue by nagasrihith608** [HarshCasper/NeoAlgo#2668]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
Rail fence cipher implementation in C programing language. This is a form of transposition cipher which encrypts the plain text into ciphertext by rearranging the characters. I would like to implement this algorithm in C language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read all the contributing guidelines, please assign this issue to me under GSSOC'21.
Thank You.

**Comment by swarnalii** [comment]
Yes, I have read all the contributing guidelines, please assign this issue to me under GSSOC'21.

**Comment by nagasrihith608** [comment]
@bhav09 please assign this issue to me under GSSoC'21.
Thank You.

**Comment by bhav09** [comment]
All the best. Happy learning!
