### ISSUE TITLE
[GSSOC'21] FCFS CPU Scheduling algorithm in c++

### ISSUE THREAD

**Issue by anotherwebguy** [HarshCasper/NeoAlgo#2673]
## 💥 Proposal

First come, first served (FCFS), is the simplest scheduling algorithm. FCFS simply queues processes in the order that they arrive in the ready queue.

Plz assign me this issue @siddharth25pandey @HarshCasper 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by anotherwebguy** [comment]
> ## 💥 Proposal
> First come, first served (FCFS), is the simplest scheduling algorithm. FCFS simply queues processes in the order that they arrive in the ready queue.
> 
> Plz assign me this issue @siddharth25pandey @HarshCasper
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes.

Hey @HarshCasper @siddharth25pandey

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by HarshCasper** [comment]
> Hey, I am Kanchan Jeswani, a GSSOC'21 participant.
> I am a Competitive Programmer and C++ enthusiastic.
> I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
> Please assign me this issue.
> Hope to hear from you.
> Discord username kanchan19#3152
> 
> @anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

This is not Algo-Phantoms

**Comment by kanchan1910** [comment]
Apologies sir for my mistake! @HarshCasper
