### ISSUE TITLE
Add all Important Algorithms for Bit Manipulation

### ISSUE THREAD

**Issue by saumyasrivastava08** [HarshCasper/NeoAlgo#2674]

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
