### ISSUE TITLE
Playfair Cipher in Python [GSSOC'21]

### ISSUE THREAD

**Issue by nandinib1999** [HarshCasper/NeoAlgo#2676]
## 💥 Proposal

I would like to implement Playfair Cipher in Python. I saw some previously opened issues for the same but the PR was not merged for Python afaik.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by anushkrishnav** [comment]
Make sure it doesn't exist already good luck.

**Comment by nandinib1999** [comment]
Can you please add the "level" tag?

**Comment by anushkrishnav** [comment]
It will be doene o the PR dw about it

**Comment by nandinib1999** [comment]
Okay thanks!
