### ISSUE TITLE
Implement Painter's Partition Problem (Binary Search) using Java

### ISSUE THREAD

**Issue by mohdarif8299** [HarshCasper/NeoAlgo#2679]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

## Motivation

This problem consists to paint n boards of given length A[i...n] and there will be k no of painters available and each painter takes B unit of time to paint a particular board. Our task is to find the minimum time to get this job done under the constraints that any painter will only paint continuous sections of boards, say board {2, 3, 4} or only board {1} or nothing but not board {2, 4, 5}.
This problem will be solved using the concept of binary search algorithm with Time Complexity O(NLogN) and space complexity O(1).

## Pitch

This problem will be give the real time use of binary search algorithm in order to find the minimum time required to paint the given boards.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
