### ISSUE TITLE
Check whether a given graph is Bipartite or not in C++

### ISSUE THREAD

**Issue by Palak2820** [HarshCasper/NeoAlgo#2680]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(YES.)

## Motivation

(GSSOC 2021 participant)

## Pitch

Implementation of bipartite graph problem.

**Comment by Ritish758** [comment]
\assign

**Comment by gargVader** [comment]
Duplicate #1510
