### ISSUE TITLE
"DNF Sort" in C++

### ISSUE THREAD

**Issue by VaibhavNarula** [HarshCasper/NeoAlgo#2681]
## 🚀 Feature

Given an array containing only 0, 1 and 2. The task is to sort the array in the given time complexity of O(N), single pass and O(1) space.

I would like to implement it in C++.
My code will contain proper comments with working descriptions.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

With the help of mid-pointer, the task can be done in O(N) time and O(1) space. Please assign this issue under GSSoC'21.

**Comment by priyanka001tech** [comment]
I would like to do it. I have a knowledge of dnf sort. I have read the Contributing Guidelines on Pull Requests. So please assign me.

**Comment by VaibhavNarula** [comment]
I am already working on it. Just waiting for assignment and then i'll make a Pull Request.

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by VaibhavNarula** [comment]
@bhav09 sir please add GSSoC label too.

**Comment by bhav09** [comment]
Sure.
