### ISSUE TITLE
Average of Levels in Binary Tree

### ISSUE THREAD

**Issue by ANUJAGRAWAL2000** [HarshCasper/NeoAlgo#2682]
## 📚 Documentation 
(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Given a binary tree, Find the average value of the nodes on each level in the form of an array. 

Example:
Input: root = [3,9,20,15,7,null,null]
Output: [3.00000,14.50000,11.00000]

Hey @hushee69 I want to work on this issue under 'NeoAlgo/C-plus-plus/cp' as a participants of GSSOC'21.

yes !!

**Comment by ANUJAGRAWAL2000** [comment]
I want to work on this issue and add the code in C++.
I will add proper description and comment.
Plz assign  to me!!

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
