### ISSUE TITLE
Three Way Merge Sort in C

### ISSUE THREAD

**Issue by Harikrishnan6336** [HarshCasper/NeoAlgo#2683]
## 💥 Proposal

3 way merge sort is a variant of merge sort in which the array is split into three subarrays.
I would like to implement the same in C  as part of GSSOC'21

Kindly assign this issue to me.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Harikrishnan6336** [comment]
@bhav09 Kindly assign this issue to me as part of GSSOC'21

**Comment by bhav09** [comment]
Assigned! Happy learning :)
