### ISSUE TITLE
(GSSOC'21) Modified Bubble sort with improved time complexity

### ISSUE THREAD

**Issue by btanisha** [HarshCasper/NeoAlgo#2686]
I'm a GSSOC 2021 participant. I checked the C++ folder and noticed that this algorithm was missing. Please assign this issue. I'll write a clean, well explained, and concise code for the same.

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in Modified Bubble sort with improved time complexity
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @bhav09  to please assign this Issue to me,

i will make this algorithm more adaptive :)

**Comment by ananddasani** [comment]
> Hi I am GSSoC'21 participant
> 
> i would like to contribute in Modified Bubble sort with improved time complexity
> i will write the clean and optimized code , by keeping best case time and space complexity in mind and
> with brief commenting and algorithm.
> 
> so i would like @bhav09 to please assign this Issue to me,
> 
> i will make this algorithm more adaptive :)

@bhav09 sir i can use C++/JAVA :)

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by bhav09** [comment]
You can open a separate issue for the same, where you can propose to implement in the language you aspire to do.

**Comment by ananddasani** [comment]
> You can open a separate issue for the same, where you can propose to implement in the language you aspire to do.

@bhav09 sir i have opened this issue please go through it ,
and if you found all ok then please assign this issue to me so that i can start contributing :)
