### ISSUE TITLE
(GSSOC'21) Counting sort in python

### ISSUE THREAD

**Issue by btanisha** [HarshCasper/NeoAlgo#2687]
I'm a GSSOC participant. I would like to contribute by including the counting sort algorithm program in python language. Please assign this issue to me.

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. I'll solve this by cpp. Can you please assign this to me?

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by Naman-12911** [comment]
Hello sir, I want to solve this question with python along with comments.
I completely solved #3130 this code.
Kindly assign me this issue under GSSOC

**Comment by ishitakapoor26** [comment]
I'm a GSSOC participant. I would like to contribute by including the counting sort algorithm program in python language. Please assign this issue to me.
