### ISSUE TITLE
A* Search

### ISSUE THREAD

**Issue by pshivesh8** [HarshCasper/NeoAlgo#2688]
## 🚀 Feature

Problem Statement: We can consider a 2D Grid having several obstacles and we start from a source cell to reach towards a goal cell.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

To approximate the shortest path in real-life situations, like- in maps, games where there can be many hindrances.

## Pitch

AI search algorithm using heuristics.
I will solve that in cpp.

Hey, @bhav09 please look into this issue and please assign it to me as a part of GSSoC'21

**Comment by bhav09** [comment]
Sure, the issue seems legit. All the best. Happy Learning.

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. I'll solve that in cpp. Can you please assign this to me?

**Comment by bhav09** [comment]
Hey @rk05-lenavo, the issue has already been assigned. Nevertheless, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then.
Happy learning!
