### ISSUE TITLE
Bead Sort 

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#269]
Bead Sort Implementation 

Bead Sort also known as Gravity sort is an algorithm to sort an array. 

Java (@parjanyaacoder)
Python (@anushkrishnav)
C#
C++
C
JavaScript

**Comment by parjanyaacoder** [comment]
@anushkrishnav  @ricardoprins @VijayaGB98 Please assign this issue to me for Java.

**Comment by vgb-codes** [comment]
@VijayaGB98 Alright go ahead with Java.

**Comment by anushkrishnav** [comment]
@VijayaGB98 @ricardoprins  Kindly assign this issue to me (Python )

**Comment by vgb-codes** [comment]
@anushkrishnav Sure go ahead with Python.

**Comment by anushkrishnav** [comment]
> @anushkrishnav Sure go ahead with Python.

Awesome thank you

**Comment by parjanyaacoder** [comment]
Solved in Java by #270 .

**Comment by anushkrishnav** [comment]
Solved Bead Sort in Python #287

**Comment by anushkrishnav** [comment]
Let's finish this It's quite challenging but interesting to work with. Reach out to me if you need help
