### ISSUE TITLE
I want to add Problem K-Tree under the dp section of c-plus-plus

### ISSUE THREAD

**Issue by yr7000** [HarshCasper/NeoAlgo#2691]
## 🚀 Feature

Problem k tree would be a great addition to dp section of c-plus-plus. It is one of the codeforces c level problems and it is really a great problem to understand the importance of the DP state in dynamic programming
Question link: https://codeforces.com/problemset/problem/431/C
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

I love to solve dynamic programming questions. while I am solving this problem I learned many new things related to dp and felt that this problem is very good and interesting for problem-solving enthusiasts.

## Pitch

As we all Know Dynamic Programming is one of the most famous topics. While solving a DP problem one should understand the importance of the DP state and forming a recurrence relation and using them to solve the problem. I hope this K-Tree problem helps many to understand the correct way of defining the DP state. I would like to contribute my approach to this problem using the concept of memoization in c++.
Hey, @bhav09  please look into this issue and please assign this to me under GSSOC2021.
Thank you.

**Comment by yr7000** [comment]
hey @anushkrishnav. Thanks for assigning this issue to me. I made the pull request successfully. If possible please add gssoc tag to this issue.
Thank you.

**Comment by anushkrishnav** [comment]
I will look into it shortly
