### ISSUE TITLE
(GSSOC'21)palindromic string

### ISSUE THREAD

**Issue by krishantraj** [HarshCasper/NeoAlgo#2695]
## 💥 Proposal

Hello, I have a code to check whether a string is a palindrome or not, in C++/JAVA. I checked the c++ and java folders and didn't found it. So I want to contribute the same, as a part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

-YES

**Comment by anushkrishnav** [comment]
Make sure it doesn't exist already good luck.

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152

@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by krishantraj** [comment]
Hey, I should have asked this previously that, should I upload code for both **C++ & JAVA** or any single one. As the tag mentioned I made a PR for this issue in **JAVA** though I'm comfortable in **C++** also.
Should I go forward to contribute to this issue in **C++**.

**Comment by khusheekapoor** [comment]
Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

**Comment by krishantraj** [comment]
> Hello! I am a GSSoC'21 Participant. I would like to work on this issue. Would be highly obliged if you could assign it to me. I will be using Java. Thanks!

if u would have gone through the above-closed PR, I mentioned that the code for this issue already exists. So merging any PR will not be of any use .thankyou u can look for other issues . I think this issue is closed now.
