### ISSUE TITLE
(GSSOC 2021) Implementation of AVL trees in C++

### ISSUE THREAD

**Issue by tanya12181** [HarshCasper/NeoAlgo#2696]
## Have you read the Contributing Guidelines on Pull Requests?
Yes.
## Motivation
useful for indexing large records in the database to speed up the search.
## Pitch
For a beginner, it is a very confusing topic and being dealt with this confusion first hand, I would like to add its implementation in cpp to help others understand its working.
I have implemented avl trees before and would like to add its implementation under data structures in c plus plus folder. Kindly assign this issue to me @bhav09.

**Comment by tanya12181** [comment]
i checked the data structures folder in c plus plus and didn't find code regarding avl trees. so I really want to contribute here. Kindly look into this issue @bhav09.

**Comment by bhav09** [comment]
Happy Learning! @tanya12181

**Comment by neha07kumari** [comment]
I would like to work on this issue using C++. Kindly assign me  @bhav09

**Comment by bhav09** [comment]
@neha07kumari, issues are assigned on a first come first serve basis. And it has already been issued to the one who has opened it.
However, you can open new issue of the same by implementing it from a different programming language. 
Happy learning!
