### ISSUE TITLE
Shortest Job First(SJF) Scheduling in C

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2702]
## 🚀 Feature
Adding code for shortest job first scheduling(operating system) in C language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
GSSOC 2021

**Comment by tanya12181** [comment]
hey, i can do its implementation in cpp. Kindly assign this issue to me.

**Comment by adiig7** [comment]
Hey @bhav09 please look into this if seems legit please assign it to me.

**Comment by bhav09** [comment]
We assign issues on a first come first serve basis. This issue will be assigned to @adiig7
