### ISSUE TITLE
Converting Integer to Roman in Golang

### ISSUE THREAD

**Issue by BeShraddha** [HarshCasper/NeoAlgo#2703]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I want to contribute by adding
- [x] Converting Integer to Roman in Golang

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read the contributing guidelines.

## Motivation

I want to contribute in open-source

## Pitch

#gssoc21

**Comment by anushkrishnav** [comment]
Good luck

**Comment by BeShraddha** [comment]
Thank you
