### ISSUE TITLE
Add a new language RUST programming language

### ISSUE THREAD

**Issue by sritasngh** [HarshCasper/NeoAlgo#2704]
## 💥 Proposal

Since Rust is blazingly fast and memory-efficient: with no runtime or garbage collector with great documentation, a friendly compiler with useful error messages, and top-notch tooling — an integrated package manager and build tool, smart multi-editor support with auto-completion and type inspections, an auto-formatter, and more. So including RUST programming language would be great :)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by itssingh** [comment]
Also I would like to work on this issue, implementing most of Data structure and algorithms section problem :)

**Comment by anushkrishnav** [comment]
Solid Idea make an issue for every Algo or DS you implement I am closing the idea since It's general. Good luck

**Comment by sritasngh** [comment]
@anushkrishnav There would be a requirement to add a new folder, should I go ahead and create a new folder named rust?

**Comment by anushkrishnav** [comment]
Yes please do
