### ISSUE TITLE
C++ (Competitive Programming) Two pointers Method link is not working

### ISSUE THREAD

**Issue by Krishan-2000** [HarshCasper/NeoAlgo#2706]
## 🐛 Bug Report

In C++ Competitive programming Column topic i.e. Two Pointers Method is not working after clicking on it. It's showing "404 File Not Found"  Please assign this bug to me I will surely improve this bug. @HarshCasper  

Gssoc'21 participant

![Screenshot (802)](https://user-images.githubusercontent.com/67598647/110834588-b7ded600-82c3-11eb-9805-3d101b7cff16.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Krishan-2000** [comment]
@bhav09 Sir, Can I start working on this issue ?

**Comment by bhav09** [comment]
Can you share a screenshot where the URL is visible too? Thanks.

**Comment by Krishan-2000** [comment]
![Screenshot (813)](https://user-images.githubusercontent.com/67598647/111200827-297e9300-85e8-11eb-87b9-ef12aee8ec3a.png)
![Screenshot (812)_LI](https://user-images.githubusercontent.com/67598647/111200832-2aafc000-85e8-11eb-8dfe-6adaf3ecca9a.jpg)

**Comment by anishsingh935** [comment]
Hi I can fix this issues can I contribute??
