### ISSUE TITLE
Fibonacci Search in Java language

### ISSUE THREAD

**Issue by adiig7** [HarshCasper/NeoAlgo#2708]
## 🚀 Feature

Adding Fibonacci search algorithm in Java.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.
## Motivation

GSSOC 2021

**Comment by shreyadubey0902** [comment]
can I also work on it

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by harshvs7** [comment]
I would like to work on it as a part of GSSOC'21.
Can you please assign the work to me?

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
