### ISSUE TITLE
DFS in C++

### ISSUE THREAD

**Issue by dhruvinfo28** [HarshCasper/NeoAlgo#2709]
## 🚀 Feature

Depth First search for a graph

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

## Pitch

Depth First Search for a graph is not present in the C++ code base(only BFS is there). It is one of the foundation for learning graph algorithms.

Kindly assign me under gssoc21

**Comment by anushkrishnav** [comment]
Good luck, Format the code properly and read our guidelines before you contribute

**Comment by bhav09** [comment]
@dhruvinfo28, happy learning!

**Comment by richakumari19** [comment]
I'm the participant of GSSOC'21.Please assign me this issue. i'll solve this from c++.

**Comment by bhav09** [comment]
It has already been assigned. However, you can open a new issue if you have a unique problem statement or an algorithm that you would like to contribute and share with us.

**Comment by dhruvinfo28** [comment]
Thankyou for assigning! I'll be on it once my previous PR gets reviewed and merged.
