### ISSUE TITLE
Add a search bar in c++ section

### ISSUE THREAD

**Issue by LalitMishra1504** [HarshCasper/NeoAlgo#2711]
## 🚀 Feature

It can make user to search question easily by typing it in search box.
I am a gssoc'21 participant so can you please assign me this @HarshCasper @siddharth25pandey 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
it can save time of programmer he/she can easily access the question and solve it.

**Comment by anushkrishnav** [comment]
How are you planning to implement it?

**Comment by LalitMishra1504** [comment]
I will use Javascript and html Css to add searchbar
In which if a user search a particular value I will compare it with li and check if it is same or not

**Comment by Varun8216889** [comment]
As I am a beginner, Can I start my contribution by working on this issue under GSSoC'21? Kindly assign it to me.
