### ISSUE TITLE
Diameter of Binary Tree in C (GSSoC'21)

### ISSUE THREAD

**Issue by sparshiigupta** [HarshCasper/NeoAlgo#2716]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I would like to implement the algorithm for finding the diameter of binary tree using C. 
The diameter of a tree is the number of nodes on the longest path between two leaves in the tree.

I am a GSSoC'21 participant and would like to work on this issue.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by ankitaggarwal23** [comment]
@sparshiigupta Hi, I assigned you, Happy Coding!😊

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by ankitaggarwal23** [comment]
> I am a GSSOC'21 participant and want to work on issue.
> I can provide the code in C++ with proper comment description .
> please assign me this issue.

@neha030 Hi, You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
