### ISSUE TITLE
Want to work on Arithmetic Slices problem in C++ (GSSOC '21)

### ISSUE THREAD

**Issue by ShreyashRoyzada** [HarshCasper/NeoAlgo#2717]
### Arithmetic Slices Problem
An integer array is called arithmetic if it consists of at **least three elements** and if the difference between any two consecutive elements is the same.

For example, [1,3,5,7,9], [7,7,7,7], and [3,-1,-5,-9] are arithmetic sequences.

Given an integer array nums, return the number of arithmetic subarrays of nums.

Input / Output Example :

Input: nums = [1,2,3,4]
Output: 3
Explanation: We have 3 arithmetic slices in nums: [1, 2, 3], [2, 3, 4] and [1,2,3,4] itself.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have.

## Motivation

The problem felt like a good starting point. 

## Pitch

Could not find the problem in the C++ codebase nor any such issue raised. Requesting you to assign me this problem. I am a participant of GSSOC '21.

**Comment by ShreyashRoyzada** [comment]
Can you please assign this to me as a part of GSSOC '21?

**Comment by ankitaggarwal23** [comment]
@ShreyashRoyzada Hi Shreyash, I assigned you. Happy Coding!😊
