### ISSUE TITLE
Scramble String

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#2718]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I would like to provide a proper explanation and clean code for finding the whether 2 strings of equal length are scrambled string or not. It is a very famous question based on DP.Since it is frequently asked in many product based companies, I would like to contribute the code in C++ as apart of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by kotwani2883** [comment]
Kindly Assign this to me as part of GSSOC'21.
Thanks!!

**Comment by bhav09** [comment]
All the best. Happy learning!
