### ISSUE TITLE
Reverse linked list in C (GSSoC'21)

### ISSUE THREAD

**Issue by sparshiigupta** [HarshCasper/NeoAlgo#2719]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to implement reversing a linked list in C.
I am a GSSoC'21 participant and would like to work on this issue.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by sparshiigupta** [comment]
@bhav09 Sir, please assign it to me.

**Comment by bhav09** [comment]
@sparshiigupta, since it doesn't exist in the C folder. I am assigning it to you. 
Happy learning!

**Comment by sparshiigupta** [comment]
Thank you so much!

**Comment by richakumari19** [comment]
I'm the participant from GSSOC'21. please assign me this issue,i would like to work on it

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by bhav09** [comment]
Hello @neha030, the issue has already been assigned. You can check out a new one that hasn't been assigned to anyone or can start contributing by opening an issue of your own, we would get back to you soon, then.

**Comment by ananddasani** [comment]
@bhav09 sir , count sort is not in repo under C language

can i open issue and start to contribute ?

**Comment by bhav09** [comment]
Sure @ananddasani :)

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by bhav09** [comment]
Hey @Dimple115, thanks for reaching out but this task has already been assigned to someone. However, you can start contributing by opening a unique issue and the mentors' team will surely review it.
