### ISSUE TITLE
Depth First Search (Graph) in Golang

### ISSUE THREAD

**Issue by BeAgarwal** [HarshCasper/NeoAlgo#2721]
## 🚀 Feature

- [x]  **Depth First Search (Graph) in Golang**

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read the guidelines.

##GSSOC21

Please assign this to me.

**Comment by ankitaggarwal23** [comment]
@BeAgarwal I assigned you, Happy Coding!😊

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by ankitaggarwal23** [comment]
> I am a GSSOC'21 participant and want to work on issue.
> I can provide the code in C++ with proper comment description .
> please assign me this issue.

@neha030 You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
