### ISSUE TITLE
Knight’s travails [gssoc21]

### ISSUE THREAD

**Issue by kavyasree-123** [HarshCasper/NeoAlgo#2724]
## 🚀 Feature

**Knight’s travails.** 
It is a great feature to Choosing a search algorithm for finding the shortest path in this case
Applying the appropriate search algorithm to find the best possible move from the starting square to the ending square.
If you want to know the simplest way your knight can move from one square (or node) to another in a two-dimensional setup.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**yes i have read it carefully**

## Motivation

**_

_gssoc21._

_**
want to contribute on new topics and  discuss new topics

## Pitch
Creating a script for a board game and a night
T**reating all possible moves of the knight as children in the tree structure**
Ensuring that any move does not go off the board

****

**Comment by kavyasree-123** [comment]
hi, can i start a pr and work on it

**Comment by kavyasree-123** [comment]
its all about:
Given a N*N board with the Knight placed on the first block of an empty board. Moving according to the rules of chess knight must visit each square exactly once. Print the order of each the cell in which they are visited.
input:
N = 8
Output:
0  59  38  33  30  17   8  63
37  34  31  60   9  62  29  16
58   1  36  39  32  27  18   7
35  48  41  26  61  10  15  28
42  57   2  49  40  23   6  19
47  50  45  54  25  20  11  14
56  43  52   3  22  13  24   5
51  46  55  44  53   4  21  12

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Can you please specify in which language you want to work?

**Comment by kavyasree-123** [comment]
C++ ☺️

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 I assigned you, Happy Coding!😊

**Comment by kavyasree-123** [comment]
thank you so much....

**Comment by kavyasree-123** [comment]
solved the issue knight's traversal #2724.

**Comment by kavyasree-123** [comment]
Done on the issue knight travail#2724
Please consider.

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Your PR is already reviewed and merged. [#2724](https://github.com/kavyasree-123/NeoAlgo/pull/1)
