### ISSUE TITLE
Previous Greater Element using Stack in C++

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2725]
## 🚀 Feature

I would like to Implement the Previous Greater Element using Stack in C++ Language.
I would Like to Contribute to this under GSSOC'21.

## Pitch

I didn't find this in C++ Language to find Previous Greater element using stack in C++ Language. I would like to contribute to this issue. Please assign me under GSSOC'21.

**Comment by Shreyash41** [comment]
@HarshCasper Sir, Please assign it to me.

**Comment by bhav09** [comment]
@Shreyash41, can you please tell me what does "previous greater" mean?  Is it finding the second greatest element in the stack?

**Comment by Shreyash41** [comment]
@bhav09 Thanks Sir, for your time. Sir, This the basic concept of Data Structures that can be used in multiple questions. Suppose we have an array of distinct integers, we have to find the closest greater on the left of every element. If there is no greater element on left, then print -1.

For Example :
N = 5
Input : arr[N] = {20, 30, 10, 5, 15}
Output : -1  -1  30  10 30

These types of questions will help to solve multiple problems like "[132 Pattern](https://leetcode.com/problems/132-pattern/)" which is a medium-level question on Leetcode.
Hope you find the importance of this. If useful, then Please assign it to me I would like to contribute to this.

**Comment by bhav09** [comment]
Oh yes, I know. Apparently, the initial description was minimal. Good luck.
