### ISSUE TITLE
To find the Sum of Digits

### ISSUE THREAD

**Issue by Sweeti-Gupta** [HarshCasper/NeoAlgo#2726]
## 💥 Proposal

The code will sum up the individual digits of the number input by user.

"Example"

1) Suppose the user inputs 345, the output will be 3+4+5=12;
2) The user inputs 8975,the output will be 8+9+7+5=29;

Hey @hushee69 , I want to add this question in the 'NeoAlgo/Java/math' as I didn't find it the java folder. So, I want to contribute the same as a part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by bhav09** [comment]
You are assigned. Happy learning.

**Comment by drishika2002** [comment]
Can I code the same question in cpp?

**Comment by ankitaggarwal23** [comment]
> Can I code the same question in cpp?

**Comment by ankitaggarwal23** [comment]
@drishika2002 You are assigned with C++.

**Comment by drishika2002** [comment]
@ankitaggarwal23 Thank you sir

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 Thank you sir

You're Welcome, Happy Coding!😊

**Comment by Sweeti-Gupta** [comment]
Hi @atarax665 ,please label this issue with level tag.

**Comment by ankitaggarwal23** [comment]
@Sweeti-Gupta Don't worry labels will be added to all the issues and merged PR's by this weekend. Our team is working on it.

**Comment by Sweeti-Gupta** [comment]
@ankitaggarwal23 Ok Sir. Thank you!
