### ISSUE TITLE
Smallest element in an array using Stack

### ISSUE THREAD

**Issue by zhcet19** [HarshCasper/NeoAlgo#2728]
## 💥 Proposal

I am faiz,an participant of GSSOC' 2021 and a avid competitive coder.I find that there is no solution of how to find minimum element of an array using stack in your repository.Hence please assign me to do this.I will write all its operation for example push(),pop(),isempty() etc.

My idea is that in finding the minimum element of an array using stack in O(1) space complexity as well as time complexity we can define a min val that stores current minimum in stack.To handle  minimum element removal from stack  we can push 2n-min into the stack instead of pushing n so that previous mimimum element can be retrieved using current min.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

**Comment by zhcet19** [comment]
please assign me this as it doesn't exists presently in the stack section @siddharth25pandey @atarax665 @HarshCasper

**Comment by ankitaggarwal23** [comment]
@zhcet19 Hi Faiz, Kindly specify in which language you want to work, so that I can assign you?

**Comment by zhcet19** [comment]
I want to work in c++

**Comment by ankitaggarwal23** [comment]
@zhcet19 I assigned you, Happy Coding!😊

**Comment by anishsingh935** [comment]
Hi kindly assign me I also want to contribute in this issue
