### ISSUE TITLE
Adding KMP string matching algorithm that works in linear time

### ISSUE THREAD

**Issue by zhcet19** [HarshCasper/NeoAlgo#2729]
## 💥 Proposal

I am Faiz, GSSOC' 2021 participant and a avid competitive coder.I would like to add KMP string matching algorithm that works in O(N) time complexity in place of Naive string matching algorithm  that works in O(N^2) time complexity.

Example: - String A:- TESSERACTCODING
                String B:-RACT

My KMP() string matching algo will look for string B in string A and would return index 5 as RACT starts from index 5 in string B else if it wouldn' t find string B it would have return -1 .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

**Comment by zhcet19** [comment]
please assign me this as it doesn't exists presently in repository @siddharth25pandey @atarax665 @HarshCasper

**Comment by ankitaggarwal23** [comment]
@zhcet19 Hi Faiz, Kindly specify in which language you want to work, so that I can assign you?

**Comment by zhcet19** [comment]
I want to work in c++

**Comment by ankitaggarwal23** [comment]
@zhcet19 I assigned you, Happy Coding!😊
