### ISSUE TITLE
Adding Krishnamurthy Number.

### ISSUE THREAD

**Issue by Madhumitamoi** [HarshCasper/NeoAlgo#2730]
## 🚀 Feature

(A clear and concise description of what the feature is.)
A Krishnamurthy number is a number whose sum of the factorial of digits is equal to the number itself. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes.
## Motivation

(Please outline the motivation for the proposal.)
As a part of my Gssoc'21 contribution, I want to add Krishnamurthy number solution under C language.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This solution I found was missing in the existing problems and hence I want to give the solution.

**Comment by ankitaggarwal23** [comment]
@Madhumitamoi I assigned you, Happy Coding!😊

**Comment by Madhumitamoi** [comment]
Added Krishnamurthy number.
