### ISSUE TITLE
Cheapest Flights Within K Stops under heap section in C++ 

### ISSUE THREAD

**Issue by ankan1811** [HarshCasper/NeoAlgo#2731]
## 💥 Proposal

There are n cities connected by m flights. Each flight starts from city u and arrives at v with a price w.
Now given all the cities and flights, together with starting city src and the destination dst, your task is to find the cheapest price from src to dst with up to k stops. If there is no such route, output -1.

Input: 
n = 3, edges = [[0,1,100],[1,2,100],[0,2,500]]
src = 0, dst = 2, k = 1
Output: 200

This is a leetcode medium level problem.
I want to implement this in C++ as a part of GSSoC'21. 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankan1811** [comment]
This is a leetcode medium level problem of heap. I want to implement this in C++ as a part of GSSoC'21. Please assign this to me . @siddharth25pandey @atarax665  @ankitaggarwal23

**Comment by ankitaggarwal23** [comment]
@ankan1811 Great, I assigned you. Happy Coding!😊

**Comment by ankan1811** [comment]
@ankitaggarwal23 The C++ label has been removed by github bot by mistake...Please add it again. It would be also nice if you could add a level to this issue like medium.  Thank you !!!
