### ISSUE TITLE
Median of two sorted Arrays

### ISSUE THREAD

**Issue by IShahnawazShaikh** [HarshCasper/NeoAlgo#2735]
Finding median of two sorted array
we will have two sorted arrays of size N and M respectively and element in array can be duplicated.
we will find median of array without merging the two arrays.

eg:  
A = [1, 4, 5]
B = [2, 3]
merged : [1,2,3,4,5]
output : 3
If we merge the job is so simple. In this case TC O(N+M) , SC O(N+M)
but I will apply binary search instead of two pointer and will do it in TC O(log(max-min)*(logm+logn)), SC O(1).

## Motivation

Finding median is important in many applications and if we do it without using no space and less time it would be best.

hey! @bhav09 may I start working on this issue in **JAVA**. I am GSSOC'21 Participant.

**Comment by bhav09** [comment]
Good luck @IShahnawazShaikh :)

**Comment by vabhv1903** [comment]
@bhav09  sir can i work on this issue in c++ language . I am also a GSSOC'21 participant.

**Comment by bhav09** [comment]
Hey @vabhv1903, it has already been assigned. You can open a new issue on a new topic that you would like to contribute and if it is not in the repo ie unique; we will assign the task to you. Happy learning!

**Comment by IShahnawazShaikh** [comment]
Thanks @bhav09 sir I am on it
