### ISSUE TITLE
maxHeap, minHeap and Heapsort

### ISSUE THREAD

**Issue by taruni-always** [HarshCasper/NeoAlgo#2749]
## 🚀 Feature

Implementing maxHeap, minHeap and heapSort in C language.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## Motivation

I would like to work on this under GSSoC '21
## Pitch

I have found heap implementation in C++ and python but not in C language. Also, I would like to write the code for heapsort in C. Please assign this to me.

in referrence to: https://github.com/TesseractCoding/NeoAlgo/issues/2541#issuecomment-797266194

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by ankitaggarwal23** [comment]
@taruni-always I assigned you, Happy Coding!😊

**Comment by taruni-always** [comment]
@ankitaggarwal23 Thank you for assigning it to me. On it now!

**Comment by taruni-always** [comment]
Please add the level labels for this.

**Comment by ankitaggarwal23** [comment]
@taruni-always Don't worry labels will be added to all the issues and merged PR's by this weekend. Our team is working on it.

**Comment by taruni-always** [comment]
@ankitaggarwal23 Should I create a seperate directory for heaps or should I add the code i C/ds folder?

**Comment by ankitaggarwal23** [comment]
Yes you have to add your code in C/ds section and also you have to update in the readme as well.
