### ISSUE TITLE
Queue Implementation

### ISSUE THREAD

**Issue by rayvantsahni** [HarshCasper/NeoAlgo#275]
**DS:** Queue implementation in Python

**Languages Supported:** Python

**Comment by Vrindagupta6828** [comment]
I want to work on this @VijayaGB98

**Comment by subhayu99** [comment]
@rayvantsahni Stacks in Python has already been implemented.

**Comment by rayvantsahni** [comment]
> @rayvantsahni Stacks in Python has already been implemented.

Well. But i clearly wrote "Queue" and not stacks. And they are not the same thing! @subhayu99

**Comment by atarax665** [comment]
@rayvantsahni There already exists an issue for Queue implementation. Check Issue #150

**Comment by atarax665** [comment]
@Vrindagupta6828 You can comment on issue #150 . I will assign it to you.

**Comment by atarax665** [comment]
Closing this issue duplicate issue of queue implementation.

**Comment by Vrindagupta6828** [comment]
@atarax665  But it is already assigned and maybe also completed there.

**Comment by atarax665** [comment]
@Vrindagupta6828 I can see that someone opened a PR for the same before you, but no worries you can still implement Queue using linked list.

**Comment by Vrindagupta6828** [comment]
Ok

**Comment by Vrindagupta6828** [comment]
@atarax665 should i comment on #150 that i want to work on it?
