### ISSUE TITLE
Combining_alternate_nodes_of_a_Linked_list

### ISSUE THREAD

**Issue by Mohim-Singla** [HarshCasper/NeoAlgo#2750]
I want to implement a program that combines alternate nodes of two NULL terminated linked lists in a single linked list.
For ex:
if LL1 is: 1->3->5->7 and LL2 is: 2->4->6->8

Then the result would be: 1->2->3->4->5->6->7->8
Language : C++

**Comment by bhav09** [comment]
It is a good addition. I am assigning you the issue. Happy Learning!
