### ISSUE TITLE
Interval List Intersections

### ISSUE THREAD

**Issue by ANUJAGRAWAL2000** [HarshCasper/NeoAlgo#2751]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
In this Problem we will be given two lists of closed intervals, firstList and secondList, where firstList[i] = [starti, endi] and secondList[j] = [startj, endj]. Each list of intervals is pairwise disjoint and in sorted order.

we have to print the intersection of these two interval lists.

Example:
Input: firstList = [[0,2],[5,10],[13,23],[24,25]], secondList = [[1,5],[8,12],[15,24],[25,26]]
Output: [[1,2],[5,5],[8,10],[15,23],[24,24],[25,25]]

Hey @hushee69 , I want to work on this issue under 'NeoAlgo/C-plus-plus/cp'. I want to work on this issue as participants of GSSOC'21.

Yes I have read the guidelines carefully.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by ankitaggarwal23** [comment]
@ANUJAGRAWAL2000 I assigned you, Happy Coding!😊

**Comment by ANUJAGRAWAL2000** [comment]
Hey @hushee69, I have created the PR for this issue. I add the code, description, I/O sample and make it also adjustable for small devices like mobile phone,etc.
https://github.com/TesseractCoding/NeoAlgo/pull/2895

**Comment by ANUJAGRAWAL2000** [comment]
Hello @ankitaggarwal23 Can u please tell me that I have made the PR for Interval List Intersections #2751.
But I didn't received any comment on it. Will it take time or I did something wrong?

**Comment by anushkrishnav** [comment]
Give it some time we will review it soon

**Comment by ANUJAGRAWAL2000** [comment]
This PR has been merged.
