### ISSUE TITLE
GSSOC 2021 Even Pair Sum Problem

### ISSUE THREAD

**Issue by mansi-9** [HarshCasper/NeoAlgo#2752]
Two positive integers A and B are given. Find the number of pairs of positive integers (X,Y) such that 1≤X≤A, 1≤Y≤B and X+Y is even.

**Input**
The first line of the input contains a single integer T denoting the number of test cases. The description of T test cases follows.
The first and only line of each test case contains two space-separated integers A and B.
**Output**
For each test case, print a single line containing one integer ― the number of valid pairs.
**Constraints**
1≤T≤1,000
1≤A,B≤109

**Example Input**
4
1 1
2 3
4 6
8 9
**Example Output**
1
3
12
36

**### Motivation**
This is a nice competitive programming problem that would include brainstorming and the biggest constraint over here is time and this kind of problem is the basis of many other cp problems. It is one of the problem that came in December long challenge of codechef 2020 and being a competitive programmer, I would like to share it with all.

hey! @bhav09 may I start working on this issue in **C++**. I am **GSSOC'21** Participant.

**Comment by bhav09** [comment]
Great! You have been assigned.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by richakumari19** [comment]
I'm the participant from GSSOC'21. I'll solve this issue from c++. please assign me this issue.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Actually Someone else is already working on C++. So Can you select any other language you want to work?

**Comment by mansi-9** [comment]
@bhav09 With kind request would you please help me to know why issue has been closed before PR being merged?

**Comment by mansi-9** [comment]
@ankitaggarwal23  @bhav09 please let me know about it. Would PR be considered?

**Comment by bhav09** [comment]
Hey @mansi-9, I might have done it by mistake. Sorry about that.
However, your PR has been reviewed and have requested changes. Need not worry, your PR will be considered.

**Comment by mansi-9** [comment]
@ankitaggarwal23 @bhav09 please assign level label to it.Thnx!!
