### ISSUE TITLE
Check if Binary Tree is symmetric

### ISSUE THREAD

**Issue by Ashee-Kanungo** [HarshCasper/NeoAlgo#2753]
## 🚀 Feature

It is a problem of binary tree in which we find if the given binary tree is symmetric or not.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As a participant of GSSoC'21, I want to contribute to this project.

## Pitch

This is a very common problem of binary tree and hence, should be added.
I would like to solve it using c++ and I assure you that I would write a clear code with proper comments.
I request you to please assign me this problem.

**Comment by simran130810** [comment]
I'm Simran (GSSoC'21 participant). I want to solve this issue in C++ and Java both.
Please assign this issue to me.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by ankitaggarwal23** [comment]
@Ashee-Kanungo Hi, I assigned you. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
@ishvik Actually Someone else is already working on C++. So Can you select any other language you want to work?

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. I would love to do it using java. Could you please assign me?

**Comment by simran130810** [comment]
> @ishvik Actually Someone else is already working on C++. So Can you select any other language you want to work?

yaa I can do it with java also.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
@ishvik Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
