### ISSUE TITLE
Convert Binary Tree to Doubly Linked List

### ISSUE THREAD

**Issue by Ashee-Kanungo** [HarshCasper/NeoAlgo#2754]
## 🚀 Feature
This problem is to convert a given binary tree to a doubly linked list.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As a participant of GSSoC'21, I want to contribute to this project.

## Pitch

This is a problem of binary tree and hence, should be added.
I would like to solve it using c++ and I assure you that I would write a clear code with proper comments.
I request you to please assign me this problem.

**Comment by ankitaggarwal23** [comment]
@Ashee-Kanungo Hi, I assigned you, Happy Coding!😊

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by richakumari19** [comment]
I'm the participant from GSSOC'21. I'll solve this issue from c++. please assign me this issue.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Actually Someone else is already working on C++. So Can you select any other language you want to work?

**Comment by Anagha-2000** [comment]
Hi, I would like to work on this issue in python. I'm a participant at GSSOC'2021

**Comment by ankitaggarwal23** [comment]
@Anagha-2000 you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by Anagha-2000** [comment]
Ok sure

**Comment by Anagha-2000** [comment]
@ankitaggarwal23 I have created an issue. Please assign it to me.
