### ISSUE TITLE
converting a integer into a binary string .

### ISSUE THREAD

**Issue by vabhv1903** [HarshCasper/NeoAlgo#2755]
converting a integer into a binary string is important sometimes  and if we do it without using much space and less time it would be best.

hey! @bhav09 may I start working on this issue in C++. I am GSSOC'21 Participant.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by vabhv1903** [comment]
> You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

@anushkrishnav  sorry to say sir but i didnt get your point of how to assign it to ourself

**Comment by vabhv1903** [comment]
'/assign'

**Comment by anushkrishnav** [comment]
just add a comment with ' /assign' without ' '

**Comment by vabhv1903** [comment]
> converting a integer into a binary string is important sometimes and if we do it without using much space and less time it would be best.
> 
> hey! @bhav09 may I start working on this issue in C++. I am GSSOC'21 Participant.

/assign

**Comment by vabhv1903** [comment]
> just add a comment with ' /assign' without ' '

okay thanks sir
