### ISSUE TITLE
Program to implement Queue using two stacks. 

### ISSUE THREAD

**Issue by nabin-nath** [HarshCasper/NeoAlgo#2756]
I would like to implement this in c and cpp

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by ankitaggarwal23** [comment]
Need to add a description and your approach. Thanks, Closing as of now.
