### ISSUE TITLE
Reverse the linked list in pairs.

### ISSUE THREAD

**Issue by nabin-nath** [HarshCasper/NeoAlgo#2757]
If you have a linked list that holds 
1 → 2 → 3→ 4→ X, 
then after the function has been called the linked list would hold 
2 → 1 → 4→3 → X. 

I can code this in c and cpp.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed.

**Comment by ankitaggarwal23** [comment]
@nabin-nath Need to add a description and your approach and Kindly Don't Spam. Thanks, Closing as of now.
