### ISSUE TITLE
Want to add Stack algorithm in java.

### ISSUE THREAD

**Issue by simran130810** [HarshCasper/NeoAlgo#2758]
## 💥 Proposal

I want to add Stack algorithms in Java.
Please assign this issue to me.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed

**Comment by ankitaggarwal23** [comment]
@ishvik Need to add a description and your approach. Thanks, Closing as of now.
