### ISSUE TITLE
Word Boggle using Backtracking

### ISSUE THREAD

**Issue by Ashee-Kanungo** [HarshCasper/NeoAlgo#2759]
## 🚀 Feature

It is a backtracking problem in which we have a dictionary of several words and a MxN board in which every cell has one character, and we have to check the number of words which are present in dictionary and can be formed by the sequence of adjacent characters on board.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As a participant of GSSoC'21, I want to contribute to this project.

## Pitch

This is a backtracking problem and hence, should be added.
I would like to solve it using c++ and I assure you that I would write a clear code with proper comments.
I request you to please assign me this problem.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed

**Comment by ankitaggarwal23** [comment]
@Ashee-Kanungo Hi, I assigned you. Happy Coding!😊
