### ISSUE TITLE
Jump Search

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#276]
Jump Search

Jump Search is an algorithm to find an element in a sorted array. 

Java

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java.
 @ricardoprins @VijayaGB98
Please assign it to me

**Comment by mar-galho** [comment]
Looking forward to see your contribution!

**Comment by parjanyaacoder** [comment]
Solved by #296

**Comment by atarax665** [comment]
@ricardoprins @VijayaGB98 I would like to work on this in C++.

**Comment by mar-galho** [comment]
It will be great to have your contribution on this!
