### ISSUE TITLE
Program to find and replace a pattern (series of characters) in a sentence.  Sentence and pattern are taken from the user. 

### ISSUE THREAD

**Issue by nabin-nath** [HarshCasper/NeoAlgo#2761]
It will be like the porgramme will ask the user:
Enter the sentence: I like to play football
Enter the word to replace: football
Enter the new word: Cricket
Output: I like to play Cricket

**Comment by nabin-nath** [comment]
I want to add this in c and cpp

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed
