### ISSUE TITLE
Loop detection in linked list in C language

### ISSUE THREAD

**Issue by taruni-always** [HarshCasper/NeoAlgo#2764]
## 🚀 Feature

Detecting a loop is present or not in a linked list.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## Motivation

I want to contribute under GSSoC '21
## Pitch

This feature has not been implemented in C language. Therefore, I would like to work on it.
Please assign this to me @Apoorve73 

in referrence with: https://github.com/TesseractCoding/NeoAlgo/issues/2556#issuecomment-797304155

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. I would love to do it using C or C++. Could you please assign me?

**Comment by taruni-always** [comment]
@rk05-lenavo it has already been assigned in C and C++.

**Comment by taruni-always** [comment]
Please add the level labels for this.
