### ISSUE TITLE
Rat in Maze ,CP in C

### ISSUE THREAD

**Issue by rohanbabbar04** [HarshCasper/NeoAlgo#2765]
## 🚀 Feature
Link of the problem:-  https://practice.geeksforgeeks.org/problems/rat-in-a-maze-problem/1
There is a rat who is at the starting point of a matrix and wants to reach
 to the ending point i.e at the last coordinate of the matrix.
 1 denotes the point where it is possible for the mouse to go and
 0 denotes the dead end
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Would like to work on this problem as a part of GSSOC '21 in C.

## Pitch

An interesting CP problem.

**Comment by priyanka001tech** [comment]
I would like to work on this problem as a part of GSSOC '21 in C as well as c++. So, please assign me.

**Comment by HarshCasper** [comment]
Sorry. I was just trying out our new CI Bot. Good going @anushkrishnav
