### ISSUE TITLE
Morse code decryption

### ISSUE THREAD

**Issue by nabin-nath** [HarshCasper/NeoAlgo#2767]
Here we will ask the user the enter a morse code and then decrypt it, for ex the output in the terminal will look like
Enter a Morse code with spaces: .... . .-.. .-.. --- .-- --- .-. .-.. -.. .---- ..--- ...--
Your entered: HELLOWORLD123

I would like to add this in cpp.

**Comment by HarshCasper** [comment]
We don't need it under our scope
