### ISSUE TITLE
Circular Queue Data structure in C-Plus-Plus

### ISSUE THREAD

**Issue by anuragmukherjee2001** [HarshCasper/NeoAlgo#2768]
##  Proposal

Circular Queue data structure is an enhancement of linear queue data structure. It is a linear data structure based on the First In First Out (FIFO) principle. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read the contributing guidelines.

## Motivation
I am participating in GSSoC'21, so I want to contribute to this project. Apart from this, I found this repository very knowledgeable, consisting data structures and algorithms of different programming languages. 

## Pitch

There are some disadvantages of linear queue, which can be easily solved using circular queue data structure. Circular queue are very helpful in real world also. Circular queue data structure is useful in memory management in our electronic devices. The scheduling of tasks done by CPU, is also a real world application of circular queue. So, circular queue is a very important data structure, which helps us to solve many simple and complex problems.

I would like to implement circular queue data structure using C-Plus-Plus programming language, with proper comments.
So, I request you to kindly assign this issue to me.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed

**Comment by ankitaggarwal23** [comment]
@anuragmukherjee2001 Hi, I assigned you. Happy Coding!😊
