### ISSUE TITLE
Infix to Prefix in C++

### ISSUE THREAD

**Issue by vabhv1903** [HarshCasper/NeoAlgo#2769]
## 🚀 Feature

I want to add the code for Infix to Prefix expressions in C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

I want to contribute under GSSoC 2021
## Pitch

I was able to find the code for infix to postfix but not for infix to prefix expressions in C++ language. @bhav09  sir Please assign this to me.

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed

**Comment by iamvs-2002** [comment]
@anushkrishnav May I implement the same in Java as a part of GSSOC'21?

**Comment by bhav09** [comment]
@iamvs-2002 you can choose to, for sure but make sure you have created an issue for java first. In that issue, you can mention this issue.

**Comment by iamvs-2002** [comment]
> @iamvs-2002 you can choose to, for sure but make sure you have created an issue for java first. In that issue, you can mention this issue.

Alright.
Thanks.
