### ISSUE TITLE
Magic Numbers in math in C++

### ISSUE THREAD

**Issue by tarunyadav148** [HarshCasper/NeoAlgo#2770]
## 🚀 Feature

Checking whether a given number is a magic number or not.

(
A number is said to be a magic number if the sum of its digits are calculated recursively till a single digit comes by adding the sum of digits after every addition. If single digit comes out to be 1 then the number is a magic number.
For example  1729
1+7+2+9=19
1+9=10
1+0=1
So,  it comes out 1. Hence, 1729 is a magic number.
)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to contribute under GSSoC '21

## Pitch

Code for checking magic numbers is not available in math in c++.
Therefore, I want to work on it.
Please assign this to me.

**Comment by priyanka001tech** [comment]
Code for checking magic numbers is not available in math in c++.Therefore, I want to work on it as gssoc 2021 participant.So,
Please assign this to me.

**Comment by tarunyadav148** [comment]
@HarshCasper  Please assign me this task.

**Comment by bhav09** [comment]
We assign on a first-come-first-serve basis. So the issue will be assigned to @tarunyadav148
