### ISSUE TITLE
Replace all occurrences of 'pi'.

### ISSUE THREAD

**Issue by gayatri517** [HarshCasper/NeoAlgo#2772]
## 🚀 Feature

You are given a string, you have to replace all the occurrence of "pi" into 3.14.
Example : 
1)Input: xpighpilmpipi
Output: x3.14gh3.14lm3.143.14

2)Input: abcpipikjpilk
Output: abc3.143.14kj3.14lk

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This question ensures better understanding of recursion and its concepts. 

## Pitch

It enhances problem solving techniques.

**Comment by gayatri517** [comment]
@HarshCasper I would like to work on this issue please assign it to me. I am participant of GSSOC.

**Comment by bhav09** [comment]
Do tell us the language you would use to implement it. It will help us in adding the respective label to this issue.

**Comment by gayatri517** [comment]
I will be working on this issue in C++.
