### ISSUE TITLE
9.2 Next_Permutation Best Way

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [HarshCasper/NeoAlgo#2797]
**My code is clear and well understanding
Please assign it to me**

**Comment by anushkrishnav** [comment]
You can assign the Issue for yourself by using the '/assign' command. Make sure The algorithm/ data structure you are trying to add doesn't already exist. read the [Doc](https://docs.google.com/document/d/1WYYc2ymImxS6-TKB6pRX77A9zpXb_ujGjdpfMaTDXwc/edit?usp=sharing) before you proceed

**Comment by ankitaggarwal23** [comment]
Need to add a description and your approach. Thanks, Closing as of now.
