### ISSUE TITLE
New Algorithm Idea open for intrested coders.

### ISSUE THREAD

**Issue by harryciscos** [HarshCasper/NeoAlgo#2815]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
We could have this algorithm implemented:-

We have been given tree lets say T with vertices set V, now try giving an algorithm to find the minimum cardinality subset of vertices W. Given every vertex in the set V has an edge with at least one vertex in set W.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

You can work on adding this feature or assign this algorithm to someone interested to solve. Happy Coding!

**Comment by ankitaggarwal23** [comment]
@harryciscos Can you please bit more elaborate how you're going to implement and also tell us whether you are working under Gssoc as a participant?

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by ankitaggarwal23** [comment]
@HitainKakkar If you want to work in this issue. Just Create open a new issue and link that issue no as well in the description and we will assign you then.
