### ISSUE TITLE
Merge Two Sorted Arrays (Two Pointers) Java

### ISSUE THREAD

**Issue by mohdarif8299** [HarshCasper/NeoAlgo#2818]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

## Motivation

Merging Two Sorted Arrays using Two pointer Approach in Java
Example:
A[] = {2,3,5,6}
B[] = {1,4,7}
After Merging
C[] = {1,2,3,4,5,6,7}
Time Complexity O(A.length+B.lenth)
Splace Complexity O(A.size()+ B.size())

## Pitch
This is a helpful approach used in Merge Sort, where we merge two sorted arrays and the resultant array is sorted accordingly.

@bhav09  can I work on this issue. I'm a GSSOC'21 Participant.

**Comment by ankitaggarwal23** [comment]
@mohdarif8299 Hi, I assigned you. Happy Coding!😊

**Comment by mohdarif8299** [comment]
Thank you @ankitaggarwal23 . I am on it.
