### ISSUE TITLE
Check for string Palindrome (using Hashing + Two Pointer)

### ISSUE THREAD

**Issue by IShahnawazShaikh** [HarshCasper/NeoAlgo#2819]
hey! @bhav09  (I am GSSOC'21 Participant) may I implement function which check for string is palindrome or not in JAVA.
I will use 2 approaches (hashing, 2 pointer).

In 2 pointer approach the complexity for checking single string would be O(N) but for N queries it would be O(Q*N).
In hashing approach the complexity for checking single string would be O(N) but for N queries it would be O(Q+N).
In each query we will have range [L,R] to check substring is palindrome or not.
eg:  abcba
In range [0,4] substring is palindrome
in range [1,3] substring is palindrome
in range [2,4] substring is not palindrome
##Motivation
We can check any substring from string is this palindrome or not.
I will use Rabin-Karp algorithm to implement this.

**Comment by ankitaggarwal23** [comment]
@IShahnawazShaikh Hi, I assigned you. Happy Coding!😊

**Comment by IShahnawazShaikh** [comment]
Thanks @ankitaggarwal23 sir I am on it.

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. I would love to do it using C++. Could you please assign me?

**Comment by ankitaggarwal23** [comment]
> I'm the participant in GSSOC'21. I would love to do it using C++. Could you please assign me?

@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
