### ISSUE TITLE
Implementation of Mod Power function algorithm using bit in Java.

### ISSUE THREAD

**Issue by IShahnawazShaikh** [HarshCasper/NeoAlgo#2820]
Hey @bhav09 sir I am GSSOC'21 Participant and I want to add Power Function algorithm using bit if u allow me.
## Motivation
 In most of the problems we calculate power of X raised to Y. There is inbuilt function in ##JAVA to calculate power but we cannot use Mod(1e9+7) while calculating power. To get rid of overflow issues we usually do Mod . I will implement power function algorithm by using bit and will use Mod.

**Comment by ankitaggarwal23** [comment]
@IShahnawazShaikh Hi, I assigned you. Happy Coding!😊

**Comment by IShahnawazShaikh** [comment]
Thanks @ankitaggarwal23 sir I am on it.

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. I would love to do it using java. Could you please assign me?

**Comment by ankitaggarwal23** [comment]
> I'm the participant in GSSOC'21. I would love to do it using java. Could you please assign me?

@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
