### ISSUE TITLE
[GSSOC'2021]Strong Number in python

### ISSUE THREAD

**Issue by javeed3157** [HarshCasper/NeoAlgo#2826]
## 💥 Proposal

Given input number is Strong number or not
EX   :   1! + 4! + 5!   =>  1 + 24 + 120   =>   145

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

Please assign this issue to me.

**Comment by ankitaggarwal23** [comment]
@javeed3157 Hi,I assigned you. Happy Coding!😊

**Comment by richakumari19** [comment]
I'm the participant in GSSOC'21. I would love to do it using python. Could you please assign me?

**Comment by javeed3157** [comment]
Thank you so much this is going to be my first open source contribution 😊.

**Comment by ankitaggarwal23** [comment]
> I'm the participant in GSSOC'21. I would love to do it using python. Could you please assign me?

@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by Samiksha2809** [comment]
Hey, I'm a GSSOC'21 participant. I would like to work on this issue using C. 
Please assign this issue to me.
Thankyou!!

**Comment by ankitaggarwal23** [comment]
@sam2809 You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by javeed3157** [comment]
@ankitaggarwal23  please have a look at my PR
