### ISSUE TITLE
Comb Sort Algorithm Implementation in Java

### ISSUE THREAD

**Issue by Devansu-Yadav** [HarshCasper/NeoAlgo#2827]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

Yes.
## Motivation

(Please outline the motivation for the proposal.)

I am exploring some of the uncommon sorting algorithms and hence I would like to implement this algorithm in Java
## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Comb sort is a relatively simple sorting algorithm which is an improvement on the Bubble Sort algorithm. I think it would be an interesting addition to the list of various sorting algorithms in this Project

**Comment by Devansu-Yadav** [comment]
@iamrajiv  @bhav09 Can u pls assign me this issue?

**Comment by ankitaggarwal23** [comment]
@Devansu-Yadav Hi, I assigned you. Happy Coding!😊

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me? I'll be using java.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Actually Someone else is already working on Java. So Can you select any other language you want to work?

**Comment by richakumari19** [comment]
@ankitaggarwal23 Okay I can also work on c++,Python.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 Okay I can also work on c++,Python.

@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
