### ISSUE TITLE
N-Meetings in one Room C++

### ISSUE THREAD

**Issue by gokulkannan7** [HarshCasper/NeoAlgo#2829]
## 💥 Proposal

I would like to add code for the Maximum number of meetings that can be done in one room, given the start and end times of various appointments, in C++ with proper comments
Pls do assign the issue to me (GSSOC'21)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by gokulkannan7** [comment]
@iamrajiv @bhav09 Can u pls assign me this issue?

**Comment by ankitaggarwal23** [comment]
@gokulkannan7 Hi, I assigned you. Happy Coding!😊

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Actually Someone else is already working on C++. So Can you select any other language you want to work?

**Comment by richakumari19** [comment]
@ankitaggarwal23 okay I can also work on java,Python.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 okay I can also work on java,Python.

@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by gokulkannan7** [comment]
@ankitaggarwal23, I have created a PR, can you check once? It was wriiten resolve conflicts, how shall i solve that problem?

**Comment by gokulkannan7** [comment]
@ankitaggarwal23, I have created a PR, can you check once? It was written resolve conflicts, how shall I solve that problem?
