### ISSUE TITLE
Reverse Linked List 

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#283]
**Algorithm:** To reverse a linked list.

**Languages supported:**
* C++ [@yashaswibiyahut]
* C [@Sohailsaifi]
* GO
* Python [@alifbhanvadiya14]
* Java [@parjanyaacoder]
* Javascript
* C#

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java. @ricardoprins @VijayaGB98 Please assign this issue.

**Comment by parjanyaacoder** [comment]
Anybody please assign me this issue? Please assign I am looking forward for some serious contribution.

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++

**Comment by mar-galho** [comment]
Alright! Looking forward to see your contributions!

**Comment by parjanyaacoder** [comment]
Solved by #296

**Comment by odavhad** [comment]
I would like to work on this issue in C and Python.

**Comment by Kathan-Vakharia** [comment]
I would like to work in javascript version

**Comment by Sohailsaifi** [comment]
can you assign this issue to me I can work on this for c language?

**Comment by vgb-codes** [comment]
@Sohailsaifi go ahead with C

**Comment by sonukushwaha403** [comment]
i would like to solve it in java please assign me
(java)

**Comment by Alifbhanvadiya14** [comment]
I would like to solve it in python

**Comment by infoarpit** [comment]
I will do this in Java.
Please assign me this task when contribution begin after 16th .

**Comment by Himanshu44626748** [comment]
I would like to do this in java. Please assign me on 16th August

**Comment by yashaswibiyahut** [comment]
Would like to do in c++.
please assign me.

**Comment by vgb-codes** [comment]
@infoarpit @Himanshu44626748 @sonukushwaha403 First come first serve basis so issue was solved by @parjanyaacoder in java.

**Comment by vgb-codes** [comment]
@Alifbhanvadiya14 go ahead with python.
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
@yashaswibiyahut Go ahead with C++.
Please follow the contribution guidelines when submitting your contribution.

**Comment by neha07kumari** [comment]
I would like to work on this issue and solve using the language C

**Comment by riya-joshi-401** [comment]
I would like to solve this in C !!!!

**Comment by vgb-codes** [comment]
@neha07kumari and @riya-joshi-401, Please check the first post to see if the issue has been taken by someone else. As C has been taken, I cannot assign you the task. 

The languages you can choose are Go and C#.

**Comment by yashaswibiyahut** [comment]
I have PR the Reverse Link list in c++..Kindly review it @VijayaGB98

**Comment by yashaswibiyahut** [comment]
@plazzy99 the code is implemented but the code is not working that`s why it assigned to me so that i can resolve the errors which i already mentioned in the issue template.
You should check the previous code and mine code before closing the PR.

**Comment by vatsalkesarwani12** [comment]
> @plazzy99 the code is implemented but the code is not working thats why it assigned to me so that i can resolve the errors.
> You can check the previous code and mine code before closing the PR.

I have reopend the request and will check soon both the code
