### ISSUE TITLE
Avl Tree Deletion

### ISSUE THREAD

**Issue by nitinjaiswal7537** [HarshCasper/NeoAlgo#2833]
Hey @SKAUL05 @nrickles3 @ArchanGhosh @ShishirBhandari @hushee69 
## 🚀 Features
###Issue In this issue i would like to contribute you the algorithm for deleting an element from an Avl tree

## Motivation
Gssoc21 participant 

## Pitch

This features will solve the issue of deleting an element from an Avl Tree

**Comment by ankitaggarwal23** [comment]
@nitinjaiswal7537 Need to add a description and your approach. Thanks, Closing as of now.
