### ISSUE TITLE
Lucky numbers

### ISSUE THREAD

**Issue by Anu-123-gif** [HarshCasper/NeoAlgo#2835]
## 🚀 Feature
Add a solution to the problem :
Lucky Numbers in cpp/cp
Lucky number is a number that consists of digits 7 and 8 only. Find the maximum number of offices in the new building of the Tax Office given that a door-plate can hold a number not longer than n digits.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation

GSSOC'21

Please assign this issue to me, thanks! 
`/assign`

**Comment by ankitaggarwal23** [comment]
@Anu-123-gif Hi, I assigned you. Happy Coding!😊

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Actually Someone else is already working on C++. So Can you select any other language you want to work?

**Comment by richakumari19** [comment]
@ankitaggarwal23 I can also work on java, Python.

**Comment by Anu-123-gif** [comment]
@ankitaggarwal23 I can write this code in java as well once my PR passes all checks. I don't know the issue right now :(
@rk05-lenavo you can work on this in python if you wish, thanks!

**Comment by richakumari19** [comment]
@Anu-123-gif @ankitaggarwal23  yeah sure Please assign me.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Hi, you can open a new one with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by richakumari19** [comment]
@ankitaggarwal23 means I have to create a new issue. Right?

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 means I have to create a new issue. Right?

@rk05-lenavo Yes, you have to create a new issue mentioning the language you want to work.
