### ISSUE TITLE
Tech Stack Update ( LOGO add ) 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [HarshCasper/NeoAlgo#2853]
I will like to add tech stack logo used in our project this will make our project attractive !! Will start to work on this issue as soon as i get assigned !!

**Comment by Apoorve73** [comment]
That's a nice idea, @rohank2502 ! Please open a new issue using the recommended template. Also, make sure you read the Contributing Guidelines before opening an issue or making a PR. For now, I am closing this issue.
Thanks :)

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> That's a nice idea, @rohank2502 ! Please open a new issue using the recommended template. Also, make sure you read the Contributing Guidelines before opening an issue or making a PR. For now, I am closing this issue.
> Thanks :)

Ook Sorry !! I will make new issue
