### ISSUE TITLE
Adding Contributor section in readme  ( Automatically )

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [HarshCasper/NeoAlgo#2854]
I will like to add a feature this will update contributor list in read me automatically !! Will start to work on this issue as soon as i get assigend !!

**Comment by ankitaggarwal23** [comment]
@rohank2502 Can you please bit more elaborate how you're going to implement and also tell us whether you are working under Gssoc as a participant?

**Comment by rohan-kulkarni-25** [comment]
Yes Sure I have  implemented the same idea in my repository you can have a
look there please https://github.com/rohank2502/Learn-GITHUB Yes I am GSSOC
participant !!

**Comment by ankitaggarwal23** [comment]
@rohank2502 Hi, I assigned you. Happy Coding!😊
