### ISSUE TITLE
LCM of two Numbers, Java, Javascript

### ISSUE THREAD

**Issue by balarka135** [HarshCasper/NeoAlgo#2855]
## 🚀 Feature
1. I want to add LCM of two numbers using Java , JavaScript .
(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch
Because finding lcm of two number is a popular and necessary question
(Please explain why this feature should be implemented and how it would be used.)

**Comment by balarka135** [comment]
Please Assign me this issue

**Comment by sakshi012000** [comment]
Hi,
I am GSSOC'21 participant
please assign me this. I will do this in C++
