### ISSUE TITLE
[ALGO/DS] Directed Acyclic Graph

### ISSUE THREAD

**Issue by mar-galho** [HarshCasper/NeoAlgo#286]
**Algorithm:** 
 [Directed Acyclic Graph] (https://en.wikipedia.org/wiki/Directed_acyclic_graph)

This is a tough nut to crack, but I trust in the ability of our amazing contributors!

**Languages Supported:**
- Python
- Go
- C
- C++
- C+++...just kidding - C#
- Java
- JavaScript
- R?

**Comment by Adil-Asif** [comment]
@ricardoprins i would like to give this a try in c++, can you assign me this and can you tell me how can i become a contributor for Neoalgo

**Comment by mar-galho** [comment]
You're more than welcome! Just submit stuff here, and you'll already be a contributor!

**Comment by parjanyaacoder** [comment]
@ricardoprins Please see the issues opened by me and assign them to me.

**Comment by anushkrishnav** [comment]
I will work with python . DAG would be intresting to code . @VijayaGB98 @ricardoprins
