### ISSUE TITLE
Magic Number in C

### ISSUE THREAD

**Issue by TechSpiritSS** [HarshCasper/NeoAlgo#2861]
## 🚀 Feature

Checking whether a given number is a magic number or not.

A number is said to be a magic number if the sum of its digits are calculated recursively till a single digit comes by adding the sum of digits after every addition. If single digit comes out to be 1 then the number is a magic number.
For example 1729
1+7+2+9=19
1+9=10
1+0=1
So, it comes out 1. Hence, 1729 is a magic number.

### Have you read the [Contributing Guidelines on Pull Requests]
YES

## Motivation
Contribution under GSSoC 21

## Pitch
I saw issue on this for C++ languages, so I thought to provide a C code for the same.

**Comment by Apoorve73** [comment]
All the best! :+1:
