### ISSUE TITLE
LCM of two numbers in C

### ISSUE THREAD

**Issue by TechSpiritSS** [HarshCasper/NeoAlgo#2865]
## 🚀 Feature

A C code to calculate the LCM of 2 numbers

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

## Motivation
Contribution under GSSoC 21

## Pitch
I have seen issue for Java and JavaScript so I am creating this one for C

**Comment by Apoorve73** [comment]
From now onwards you can assign the issue opened by you yourself by just typing in ```/assign``` in the comment.
Thanks! :+1:

**Comment by TechSpiritSS** [comment]
@harshvs7 I have already asked for its PR

**Comment by Vedika-Agrawal** [comment]
Hello, I am GSSOC'21 participant. I want to add the code of concatenation of two strings in C. I will write the code with proper comments and examples.
Can you please assign this  issue to me under GSSOC?

**Comment by Vedika-Agrawal** [comment]
Hello, I am GSSOC'21 participant. I want to add the code to "LCM of two numbers in C". I will write the code with proper comments and examples.
Can you please assign this  issue to me under GSSOC?
