### ISSUE TITLE
Random Forest Algorithm

### ISSUE THREAD

**Issue by malavikarajeshvikraman** [HarshCasper/NeoAlgo#2870]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

Yes

## Motivation

(Please outline the motivation for the proposal.)

GSSOC'21

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

I am participating in GSSOC'21 this year and I am a ML enthusiast .So I can contribute the random forest python code here.
So please kindly do  assign this to me.

**Comment by bhav09** [comment]
All the best. Happy Learning!

**Comment by malavikarajeshvikraman** [comment]
Thank you @bhav09 . Will start working on it
