### ISSUE TITLE
Inverting a Binary Tree in Javascript

### ISSUE THREAD

**Issue by Alleny244** [HarshCasper/NeoAlgo#2871]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
To Invert a Binary Tree in Javascript
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
I am participating in GSSOC'21 this year .This is an important question in javascript
So please kindly do assign this to me.

**Comment by Apoorve73** [comment]
@Alleny244, from now onwards you can assign the issue opened by you yourself by just typing in ```/assign``` in the comment.
Thanks! :+1:
