### ISSUE TITLE
Two "Singly Linked List" programs in documentation

### ISSUE THREAD

**Issue by saatviknagpal** [HarshCasper/NeoAlgo#2872]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests]
(https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes, I've read the guidelines.

(Write your answer here.)

There are 2 links of "Singly Linked List" one with Python and another with C++ in C++ documentation.

As a GSSOC21 Participant , I would like to remove the python link/file from the documentation for c++. 
![double-singly-ll](https://user-images.githubusercontent.com/61618767/110946935-83bbf180-8365-11eb-96cb-d993a6746ba4.png)

Please assign me this issue @bhav09

**Comment by Apoorve73** [comment]
@Saatvik21  Please make sure you follow the issue template before opening any issue!

**Comment by bhav09** [comment]
All the best @Saatvik21 :)

**Comment by saatviknagpal** [comment]
> All the best @Saatvik21 :)

Sir please add GSSOC label for this issue.
