### ISSUE TITLE
Trapping Rainwater

### ISSUE THREAD

**Issue by Rishika30** [HarshCasper/NeoAlgo#2873]
I would like to add the Trapping Rainwater problem's solution in c++. I will also add the time,space complexities to it. Please assign this issue to me.

**Comment by bhav09** [comment]
Hey @Rishika30 can you please elaborate a bit more on your approach and also tell us whether you are working under Gssoc as a participant?

**Comment by Rishika30** [comment]
Yes I am a Gssoc'21 participant. I will use two pointer approach to solve it in which rainwater stored at each index is difference between min(left_max height,right_max height) and height of cuurent index.

**Comment by ankitaggarwal23** [comment]
@Rishika30 I didn't get your approach Can you add bit more how you are going to implement!

**Comment by Rishika30** [comment]
@ankitaggarwal23 Two pointers will be there left and right initialised with 0 and n-1. And left_max,right_max also as 0. 
Then we start iterating the array by comparing whether left<=right. 
If array[left]<array[right] then see if array[left]>=left_max and if that is true then update left_max with array[left] otherwise it means that some water will be trapped in that index as some height on left to that particular index and some height to right of that index are greater than height of that index. And it can be calculated by result+=max_left- array[left]. And then do left++ . 
If array[left]>array[right] then we compare and see if array[right]>=right_max and if true, update right_max. Else some water will be trapped which is calculated by result+=right_max-array[right] and do right--.  
This time complexity will be O(n) and space complexity will be O(1) which is better than any other appraoch to solve this.

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 Two pointers will be there left and right initialised with 0 and n-1. And left_max,right_max also as 0.
> Then we start iterating the array by comparing whether left<=right.
> If array[left]<array[right] then see if array[left]>=left_max and if that is true then update left_max with array[left] otherwise it means that some water will be trapped in that index as some height on left to that particular index and some height to right of that index are greater than height of that index. And it can be calculated by result+=max_left- array[left]. And then do left++ .
> If array[left]>array[right] then we compare and see if array[right]>=right_max and if true, update right_max. Else some water will be trapped which is calculated by result+=right_max-array[right] and do right--.
> This time complexity will be O(n) and space complexity will be O(1) which is better than any other appraoch to solve this.

@Rishika30 Hi, I assigned you. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
> I am a GSSOC'21 participant and want to work on issue.
> I can provide the code in C++ with proper comment description .
> please assign me this issue.

@neha030 Actually @Rishika30 is already working on C++. So Can you select any other language you want to work?
You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by kanchan1910** [comment]
@ankitaggarwal23, sir I can solve this problem in **python**,
The approach is using two pointers,
First initialize left pointer to 0 and right pointer to size-1
Till left<right  , will update left_Max and right_Max with max(left_Max, height[left]) and max(right_Max, height[right])
update total water trapped according to left_Max and right_Max 

Time complexity: O(n)

Space complexity: O(1)

@ankitaggarwal23, thank you for your time and consideration, kindly assign this to me.

**Comment by Rishika30** [comment]
@ankitaggarwal23 I have added the file and created pull request #2928 but it is showing one check was not successful Deepsource java(beta) one. Could you please tell if it is alright or not
