### ISSUE TITLE
Add Tech Stack Logo In read me 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [HarshCasper/NeoAlgo#2879]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes I have !!

(Write your answer here.)
I will like to add the logo of each tech stack which we are using in our repository this will make our read me more attractive !!

**Comment by rohan-kulkarni-25** [comment]
@Apoorve73  Have a look please !!

**Comment by ankitaggarwal23** [comment]
@rohank2502 Can you tell us whether you are working under Gssoc as a participant?

**Comment by rohan-kulkarni-25** [comment]
yes !!

**Comment by ankitaggarwal23** [comment]
@rohank2502 Hi, I assigned you. Happy Coding!😊

**Comment by rohan-kulkarni-25** [comment]
Which tech stack logo will you like to get assigned ?

**Comment by ankitaggarwal23** [comment]
> Which tech stack logo will you like to get assigned ?

You have mentioned this `I will like to add the logo of each tech stack which we are using in our repository this will make our read me more attractive !!`
