### ISSUE TITLE
Checking, is binary tree symmetric or not

### ISSUE THREAD

**Issue by simran130810** [HarshCasper/NeoAlgo#2880]
## 🚀 Feature

Problem with symmetric nature of binary tree.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As I'm a participant of GSSoC'21 and interested in Data Structures and algorithm
, I want to add this feature to the project.  

## Pitch
Sometimes, algorithm doesn't work because of symmetric nature of binary tree so I would like to add this feature in java with proper comments and documentation. 
Please assign this to me.

**Comment by ankitaggarwal23** [comment]
@ishvik Hi, I assigned you. Happy Coding!😊

**Comment by simran130810** [comment]
> @ishvik Hi, I assigned you. Happy Coding!😊

Thank You😊

**Comment by kanchan1910** [comment]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant. 
I am a Competitive Programmer and C++ enthusiastic.
I would love to solve this problem using CPP with well-explained code and along with its time and space complexity.
Please assign me this issue.
Hope to hear from you.
Discord username  kanchan19#3152
@ankitaggarwal23, please assign this to me, thank you!!

**Comment by ankitaggarwal23** [comment]
@kanchan1910 As someone is already working on C++ and Java. You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
