### ISSUE TITLE
Implementing decision tree classification in python

### ISSUE THREAD

**Issue by rray14** [HarshCasper/NeoAlgo#2888]
## 💥 Proposal

Hi I am a participant of GSSoC'21, I'll be contributing my part to NeoAlgo by adding the decision tree classification algo, with all the steps to build an optimized classifier using the Scikit-learn package
Please assign me this issue

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
@rray14 Hi, I assigned you. Happy Coding!😊
