### ISSUE TITLE
GSSOC 2021 Toggle kth bit from right (bit manipulation)

### ISSUE THREAD

**Issue by mansi-9** [HarshCasper/NeoAlgo#2890]
This program would aim at toggling kth bit from right using bitwise operations.

### Motivation
This problem could be done by using xor and shift bitwise operator. It would strengthen the basic concepts.

May I start working on this issue in C++. I am GSSOC'21 Participant.

**Comment by mansi-9** [comment]
@anushkrishnav please assign me.

**Comment by ankitaggarwal23** [comment]
@mansi-9 Hi, I assigned you. Happy Coding!😊

**Comment by mansi-9** [comment]
Thank you!!!

**Comment by anushkrishnav** [comment]
Awesome @ankitaggarwal23
