### ISSUE TITLE
GSSOC 2021 minimum no. of swaps needed to sort the array

### ISSUE THREAD

**Issue by mansi-9** [HarshCasper/NeoAlgo#2894]
Minimum no. of swaps needed to sort the array
I would like to work on it in c++. I am a GSSOC 2021 participant.

**Comment by neha030** [comment]
I am a GSSOC'21 participant and want to work on issue.
I can provide the code in C++ with proper comment description .
please assign me this issue.

**Comment by mansi-9** [comment]
@ankitaggarwal23 please assign me this issue.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 please assign me this issue.

@mansi-9 Hi, I assigned you. Happy Coding!😊

**Comment by mansi-9** [comment]
thank you !!!

**Comment by mansi-9** [comment]
@ankitaggarwal23 please assign level label to it.Thnx!!

**Comment by ankitaggarwal23** [comment]
level tag is already there
