### ISSUE TITLE
Check if two trees are Mirror in C++

### ISSUE THREAD

**Issue by richakumari19** [HarshCasper/NeoAlgo#2902]
**Assume Two Binary Trees, write a function that returns true if two trees are mirror of each other, else false**

### **Have you read the [Contributing Guidelines on Pull Requests]**

Yes, I've read the guidelines.

As a GSSOC21 Participant , I would love to work on this issue.
@ankitaggarwal23  Please assign me this issue

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Hi, I assigned you. Happy Coding!😊

**Comment by richakumari19** [comment]
@ankitaggarwal23 Thank You so much for assigning me.

**Comment by rk05-lenavo** [comment]
@ankitaggarwal23 have created a pull request for the Check if two tree are Mirror. Please review the code and merge it if you find it good.

**Comment by rk05-lenavo** [comment]
@ankitaggarwal23 have created a pull request for this issue. Please review the code and merge it if you find it good.

**Comment by richakumari19** [comment]
@ankitaggarwal23  have created a pull request for this issue. Please review the code and merge it if you find it good.

**Comment by rk05-lenavo** [comment]
@ankitaggarwal23 why my request has been closed.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Your PR is closed because You didn't link your issue and also marked in the description [here](https://github.com/TesseractCoding/NeoAlgo/pull/2955).
