### ISSUE TITLE
Avl tree

### ISSUE THREAD

**Issue by saimanoharhm** [HarshCasper/NeoAlgo#2903]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I want to contribute to LL and LR rotation codes from avl tree concepts using c.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by ankitaggarwal23** [comment]
@saimanoharhm Can you please bit more elaborate your approach how you're going to implement and also tell us whether you are working under Gssoc as a participant?

**Comment by saimanoharhm** [comment]
@ankitaggarwal23 I will write a code for Avl tree and it will include creation of avl tree using recursive method, and also LL Rotation, LR rotation, RR rotation, RL rotation of avl tree using iterative method and I am a Gssoc participant.
