### ISSUE TITLE
Mathematics Sine Function

### ISSUE THREAD

**Issue by XZANATOL** [HarshCasper/NeoAlgo#2906]
## 🚀 Feature

I would like to add an algorithm that can calculate the Trignometric Sine function

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [x] Yes

## Motivation

I noticed that you have a section for mathematics and I love maths as I am an Engineering student. I also like writing clean readable code and interested in DSA, So mixing these provide lots of fun and challenges. I am also a GSSOC'21 participant and like coding in Python.

## Pitch

It can help understand how scientific calculators can calculate Sine function, in addition to, knowing how to deal with negative angles and those that are bigger than 360 degrees, and quadrant signs.

## Details

* Code will accept user angle input and angle mode. (degrees/radians)
* Comments will be added to follow the code flow and be easy to read.
* Code will also use the math library to compare the accuracy of the algorithm.

**Comment by ankitaggarwal23** [comment]
@XZANATOL Hi, I assigned you. Happy Coding!😊
