### ISSUE TITLE
Invalid Links

### ISSUE THREAD

**Issue by XZANATOL** [HarshCasper/NeoAlgo#2907]
## 📚 Documentation

In the Readme.MD file of the repository => Contributing Guidelines section:
* 4th point, the added template link links to a 404 page

Also the slack link is expired

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [x] Yes

**Comment by ankitaggarwal23** [comment]
@XZANATOL Can you please bit more elaborate how you're going to implement and also tell us whether you are working under Gssoc as a participant?

**Comment by XZANATOL** [comment]
@ankitaggarwal23 If you can provide me a copy of templates you wish the repository to follow, I can make a documentation for it, or I can make my own custom one.

But please check the PR #3037 linked with Issue #2906 before going any furthur with this issue, as I am assigned there.
