### ISSUE TITLE
Delete duplicate nodes in an unsorted linked list in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2909]
## 💥 Proposal

I would like to delete duplicate nodes in an unsorted linked list in C++.Please assign the issue to me

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by rachit-geek** [comment]
YES, I have read the contributing guidelines.
As a Participant,I would like to solve this issue...Please assign me this issue @SAY-droid427

**Comment by ankitaggarwal23** [comment]
@SAY-droid427 Can you tell us whether you are working under Gssoc as a participant?

**Comment by SAY-droid427** [comment]
@ankitaggarwal23 Yes. I am workins as a participant in GSSOC'21.Please assign this issue to me

**Comment by rachit-geek** [comment]
@ankitaggarwal23 sir please assign me this issue

**Comment by ankitaggarwal23** [comment]
@SAY-droid427 Hi, I assigned you. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
@rachit-geek As someone is already working on C++. You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by SAY-droid427** [comment]
I will create a PR for this issue today. I hadn't been able to work on this the last few days due to some problem
