### ISSUE TITLE
Unbounded Binary Search 

### ISSUE THREAD

**Issue by AmanBisht01** [HarshCasper/NeoAlgo#2910]
**Explanation**

Unbounded Binary Search is missing in **NeoAlgo/C-Plus-Plus/search/**

Find the point where a monotonically increasing function becomes positive first time.

**Have you read the [Contributing Guidelines on Pull Requests]**
Yes, I've read the guidelines.

As a GSSOC21 Participant, I would love to work on this issue.
@ankitaggarwal23 Please assign me this issue

**Comment by ankitaggarwal23** [comment]
@AmanBisht01 Can you please bit more elaborate your approach how you're going to implement?

**Comment by AmanBisht01** [comment]
The function is monotonically increasing with respect to the value of x, i.e., the value of f(x+1) is greater than f(x) for every input x. Find the value ‘n’ where f() becomes positive for the first time. Since f() is monotonically increasing, values of f(n+1), f(n+2),… must be positive and values of f(n-2), f(n-3), .. must be negative.

**Approach**
**O(n)**: A simple solution is to start from I equals to 0 and one by one calculate the value of f(i) for 1, 2, 3, 4 .. etc until we find a 
         positive f(i). 

**O(Logn)**: We can’t directly apply Binary Search as we don’t have an upper limit or high index.The idea is to do repeated doubling until we find a positive value, i.e., check values of f() for following values until f(i) becomes positive. Let 'high' be the value of i when f() becomes positive for first time.
We can apply Binary Search now, we can use ‘high/2’ as low and ‘high’ as high indexes in binary search. The result n must lie between ‘high/2’ and ‘high’.

**Comment by ankitaggarwal23** [comment]
@AmanBisht01 Hi, I assigned you. Happy Coding!😊

**Comment by AmanBisht01** [comment]
@ankitaggarwal23 i have  created PR please review it.
