### ISSUE TITLE
No.OfSetBitsInANumber In Java

### ISSUE THREAD

**Issue by asthakri50** [HarshCasper/NeoAlgo#2911]
## 💥 Proposal
Hey @HarshCasper, @Aanisha, @atarax665, @anushkrishnav,

I am a GSSOC'21 participant and I want to make changes to the file NeoAlgo/Java/other/SetBitsInInteger.java

I found that the problem has been solved using iteration. I would solve the same problem using Bit-Masking in Java with a lesser no of code lines. 

Please assign me this issue.

Thank you.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

# Yes, I have gone through the Contributing Guidelines and would abide by them.

**Comment by ankitaggarwal23** [comment]
@asthakri50 Hi, We assigned you. You can start working on it. Happy Coding!😊

**Comment by asthakri50** [comment]
I have opened a pull request for this issue. Please review it.
