### ISSUE TITLE
Implement Bucket Sort in C#

### ISSUE THREAD

**Issue by Akhilesh2002** [HarshCasper/NeoAlgo#2915]
## 🚀 Feature

Bucket Sort is a sorting technique that sorts the elements by first dividing the elements into several groups called buckets. The elements inside each bucket are sorted using any of the suitable sorting algorithms or recursively calling the same algorithm.

* Use Scatter-gather approach.
* Best case time complexity- O(n+k)
* Worst case time complexity-O(n^2)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

To add more sorting algorithms in C#

## Pitch
In bucket sort is that once the elements are distributed into buckets, each bucket can be processed independently of the others.
It also means that you can sort all of the buckets in parallel with one another.
Bucket sort is useful when there is a large dataset.

**Comment by Akhilesh2002** [comment]
I want to implement this under GSSOC ' 2021. Please assign this issue to me

**Comment by anushkrishnav** [comment]
comment '/assign' to get assigned

**Comment by ankitaggarwal23** [comment]
@Akhilesh2002 Hi, I assigned you. Happy Coding!😊
