### ISSUE TITLE
Implement Crossword Puzzle in Python

### ISSUE THREAD

**Issue by arnab031** [HarshCasper/NeoAlgo#2918]
## 💥 Proposal

A 10*10 Crossword grid is provided to you, along with a set of words (or names of places) which need to be filled into the grid. Cells are marked either + or -. Cells marked with a - are to be filled with the word list.

The following shows an example crossword from the input crossword  grid and the list of words to fit,
![image_2021-03-13_012551](https://user-images.githubusercontent.com/51916075/110991759-0dd27d00-839b-11eb-97f7-62c8afc0532a.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by arnab031** [comment]
As a GSSOC21 Participant , I would like to work on this issue. @ankitaggarwal23

**Comment by bhav09** [comment]
That's a good problem statement. I am assigning it to you.
Happy learning!
