### ISSUE TITLE
Bit manipulation(Set Clear Check bit)

### ISSUE THREAD

**Issue by dhruvinfo28** [HarshCasper/NeoAlgo#2920]
## 🚀 Feature

Set , Clear , Check bit for C++ Code base.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

## Pitch

The C++ code base doesn't have it.  Also these are the fundamentals when it comes to bit manipulation.

**Comment by bhav09** [comment]
Hey @dhruvinfo28, I am assigning it to you :)
Happy Coding :)

**Comment by dhruvinfo28** [comment]
@bhav09 Thankyou for assigning! I'm on it :)

**Comment by sonalsingh25** [comment]
I can code this in java . Please assign me if you can!

**Comment by bhav09** [comment]
@sonal251001, you can have a check at java folder if it has not been mentioned/implemented there, you can open an issue will review it and then will assign it to you. 
Happy coding!
