### ISSUE TITLE
add emi calculator in c++

### ISSUE THREAD

**Issue by iamsonukushwaha** [HarshCasper/NeoAlgo#2923]
## 🚀 Feature

want a add a program for calculating emi

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**PS**: Please assign this issue to me. I'll start working on it as soon as it gets assigned to me.

**Comment by bhav09** [comment]
All the best!

**Comment by iamsonukushwaha** [comment]
one ( @bhav09 ) is saying okay you can add and the other ( @HarshCasper ) is not

what is this ?
