### ISSUE TITLE
add simple and compound interest calculator in c

### ISSUE THREAD

**Issue by iamsonukushwaha** [HarshCasper/NeoAlgo#2924]
## 🚀 Feature

want a add a program for calculating simple and compound interest calculator in c

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**PS:** Please assign this issue to me. I'll start working on it as soon as it gets assigned to me.

**Comment by bhav09** [comment]
All the best. Happy Coding :)
