### ISSUE TITLE
GSSOC'21 Generate all valid parentheses (Backtracking Algorithm)

### ISSUE THREAD

**Issue by kanchan1910** [HarshCasper/NeoAlgo#2926]
Hey, I am Kanchan Jeswani, a GSSOC'21 participant I want to add the code for the problem "Generate all valid parentheses".

The problem statement is as follows:

Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses of length 2*n.

For example, given n = 3, a solution set is:
[
"((()))",
"(()())",
"(())()",
"()(())",
"()()()"
]
for n = 1
[
"()"
]
for n = 2
[
"(())",
"()()"
]

The input of the form: an integer n
Output: the vector of all possible combinations of well-formed parentheses of length 2*n in the form of a vector of strings like shown in the above examples.

n =3 means, there are 3 open parentheses and 3 close parentheses, and we have to form all well-formed possible combinations using these parentheses, so the first parenthesis MUST be an opening parenthesis, and the last parenthesis MUST be a closing parenthesis, for it to be a valid combination. In a similar way, we can generate all valid combinations using a backtracking algorithm.

constraint : 1 <= n <= 8

I would love to solve this problem using CPP with well-explained code.
Please assign me this.
Hope to hear from you.
Discord username kanchan19#3152

@bhav09 thank you for your time and consideration
@anubhavitis @dheerajkotwani @tarun26091999 @todi-2000 @geekquad @plazzy99 @rudrakshi99

**Comment by bhav09** [comment]
Assigned! All the best :)

**Comment by kanchan1910** [comment]
@bhav, thank you sir!
