### ISSUE TITLE
Breadth First Search

### ISSUE THREAD

**Issue by neha030** [HarshCasper/NeoAlgo#2929]
## 🚀 Feature
I am a GSSOC'21 participant.
I can implement this using C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Pitch

Please assign me this.

**Comment by bhav09** [comment]
Hey @neha030, it already exists. You can try to open a new issue that hasn't been implemented yet. We will assign it to you. 
Closing the issue as of now.
