### ISSUE TITLE
Diameter of a Binary Tree

### ISSUE THREAD

**Issue by neha030** [HarshCasper/NeoAlgo#2930]
## 🚀 Feature
I am a GSSOC'21 participant.
I can implement this using C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Pitch

Please assign me this.

**Comment by ankitaggarwal23** [comment]
@neha030 Hi, I assigned you. Happy Coding!😊

**Comment by neha030** [comment]
I am facing some issue my commits for the issue #2930 is there in #3015.
therefore i request to please review my code there.
