### ISSUE TITLE
job sequencing with deadlines.

### ISSUE THREAD

**Issue by captainra1** [HarshCasper/NeoAlgo#2933]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
given:n-jobs,profit with each job and deadlines
now, we have to schedule the m-jobs(sometimes may be m=n) so that we can get maximum profit. 
I would be using array to solve the problem.

## Motivation

(Please outline the motivation for the proposal.)
there are n-jobs given with deadlines  and profit associated with the jobs and each job take unit time in order to execute.
we have to select a sub jobs so that they should complete in their deadlines and profit should be maximize.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
this algorithm has many uses in the real world i.e, it used in FDM( frequency division multiplexing) in communication system
to solve above problem I will be using array and solve this via greedy strategy.

**Comment by ankitaggarwal23** [comment]
@captainra1 Can you tell us whether you are working under Gssoc as a participant and in which language you want to work?

**Comment by captainra1** [comment]
yes, I am a GSSOC's participant and I want to do it in c++ lang.

**Comment by ankitaggarwal23** [comment]
@captainra1 Hi, I assigned you. Happy Coding!😊

**Comment by captainra1** [comment]
thanks
