### ISSUE TITLE
weird algorithm

### ISSUE THREAD

**Issue by vabhv1903** [HarshCasper/NeoAlgo#2934]
## 🚀 Feature

Consider an algorithm that takes as input a positive integer n. If n is even, the algorithm divides it by two, and if n is odd, the algorithm multiplies it by three and adds one. The algorithm repeats this, until n is one.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

@bhav09  sir can you please assign this problem to me . I am GSSOC'21 participant.

**Comment by bhav09** [comment]
A great problem to practice. All the best!
However, you would use C++?

**Comment by ananddasani** [comment]
Hi I am GSSoC'21 participant 

i would like to contribute in weird algorithm  issue #2934
i will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.

so i would like @bhav09 to please assign this Issue to me :)

**Comment by bhav09** [comment]
Hey, it will be assigned to @vabhv1903. We assign of fcfs basis. 
Happy learning!

**Comment by vabhv1903** [comment]
> A great problem to practice. All the best!
> However, you would use C++?

yes ill use c++
