### ISSUE TITLE
Implement Children Sum Property of Trees in C++ Language

### ISSUE THREAD

**Issue by Shreyash41** [HarshCasper/NeoAlgo#2936]
## 🚀 Feature

I would like to implement Children Sum Property of Trees Data Structure in C++ Language.
I would like to contribute to this under GSSOC'21. Please assign it to me.

## Pitch

Children Sum Property is a property in which the sum of values of the left child and right child should be equal to the value of their node. If both children are present return True else return False. This Should be implemented using Trees Data Structures. 

@bhav09 @HarshCasper   sir can you please assign this problem to me as a GSSOC'21 participant.

**Comment by bhav09** [comment]
Nice one! Go ahead @Shreyash41.

**Comment by Shreyash41** [comment]
@bhav09 Thanks for your time, sir. Sir, I think you forget to assign this issue to me :)

**Comment by bhav09** [comment]
Yea, I am sorry. I am into handling a lot of issues so .... :/
