### ISSUE TITLE
Rabin-Karp Algorithm for Pattern Searching [gssoc21]

### ISSUE THREAD

**Issue by kavyasree-123** [HarshCasper/NeoAlgo#2943]
## 💥 Proposal

**Rabin-Karp Algorithm** 
used for pattern searching
The average and best-case running time of the Rabin-Karp algorithm is O(n+m), but its worst-case time is O(nm)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes i have read it carefully

**Comment by kavyasree-123** [comment]
To give a clear idea lets have inputs and outputs

Input:  str[] = "abcdefghji"
        word[] = "abc"
Output: Pattern is at position 1

**Comment by kavyasree-123** [comment]
want to work on this issue please assign it to me
@bhav09 @HarshCasper @asthakri50

**Comment by bhav09** [comment]
@kavyasree-123, what is the programming language you would be implementing it on?

**Comment by kavyasree-123** [comment]
in c language

**Comment by bhav09** [comment]
Great, all the best!
