### ISSUE TITLE
Longest Common Subsequence using Dynamic Progrmming

### ISSUE THREAD

**Issue by Yukti-1** [HarshCasper/NeoAlgo#2948]
I will write the code in C++.

May I be assigned this issue ?

**Comment by ankitaggarwal23** [comment]
@Yukti-1 Need to add a description and your approach and also tell us whether you are working under Gssoc as a participant?

**Comment by Yukti-1** [comment]
Yes, I am a participant under Gssoc 2021.

I want to add the algorithm to find longest common subsequence between two strings. The algorithm will find the count of the longest subsequence as well as also print the subsequence which is common. 
This algorithm will follow DP approach. 

I will write the code in C++. And also a brief description which will explain the code and it's workflow.

**Comment by ankitaggarwal23** [comment]
@Yukti-1 Hi, I assigned you. Happy Coding!😊
