### ISSUE TITLE
Reverse a Circular Linked list [GSSOC]

### ISSUE THREAD

**Issue by neha030** [HarshCasper/NeoAlgo#2950]
## 🚀 Feature

I am a GSSOC'21 participant .
I can not see the code for reversing the circular linked list in the C++ folder and thus want to provide the code in C++ for the same.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Pitch

please assign me this issue.

**Comment by ankitaggarwal23** [comment]
@neha030 Hi, I assigned you. Happy Coding!😊
