### ISSUE TITLE
Checking if a linked list is palindrome or not using stacks in C++

### ISSUE THREAD

**Issue by SAY-droid427** [HarshCasper/NeoAlgo#2951]
## 💥 Proposal

I want to add a code for checking if a linked list is palindrome or not using stacks in C++.Please assign me this issue[GSSOC'21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by ankitaggarwal23** [comment]
@SAY-droid427 Hi, I assigned you. Happy Coding!😊
