### ISSUE TITLE
DOUBLY CIRCULAR Linked list [GSSOC'21]

### ISSUE THREAD

**Issue by neha030** [HarshCasper/NeoAlgo#2954]
## 💥 Proposal

I am a GSSOC'21 participant.
I want to add the code for doubly circular linked list in C++.
1.Delete from beginning
2.Delete from END
3.Delete from SPECIFIC POSITION
4.INSERT from beginning
5.INSERT from END
6.INSERT from SPECIFIC POSITION

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by ankitaggarwal23** [comment]
@neha030 Hi, I assigned you. Happy Coding!😊
