### ISSUE TITLE
Smallest divisible number 

### ISSUE THREAD

**Issue by AmanBisht01** [HarshCasper/NeoAlgo#2957]
Given a number N, find an integer denoting the smallest number evenly divisible by each number from 1 to n.

I would like to contribute to this under GSSOC'21. Please assign it to me.

**NeoAlgo/C-Plus-Plus/math/**

**Comment by ankitaggarwal23** [comment]
@AmanBisht01 Hi, I assigned you. Happy Coding!😊

**Comment by Pallavi-02** [comment]
Hey....i'm GSSoC'21 participant. Please assign me this issue.I would like to contribute on this.

**Comment by AmanBisht01** [comment]
Thanks, @ankitaggarwal23 😊

**Comment by ankitaggarwal23** [comment]
> Hey....i'm GSSoC'21 participant. Please assign me this issue. I would like to contribute on this.

 @Pallavi-02 Actually Someone else is already working on C++. You can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by Pallavi-02** [comment]
Ohkkk

**Comment by AmanBisht01** [comment]
I see that most of the recent PR's got failed in DeepSource Java beta check ! Don't know why :(

**Comment by atarax665** [comment]
> I see that most of the recent PR's got failed in DeepSource Java beta check ! Don't know why :(

There is some glitch in the deepsource Java CI. Don't worry about it.
