### ISSUE TITLE
Fibonacci numbers

### ISSUE THREAD

**Issue by richakumari19** [HarshCasper/NeoAlgo#2962]
The Fibonacci numbers are the numbers in the following integer sequence.
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, ……..

In mathematical terms, the sequence Fn of Fibonacci numbers is defined by the recurrence relation 

Fn = Fn-1 + Fn-2

### **Have you read the [Contributing Guidelines on Pull Requests]**

Yes, I've read the guidelines.

As a GSSOC21 Participant , I would love to work on this issue.
@ankitaggarwal23 Please assign me this issue under GSSOC'21

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo  
Check whether it is already there in the repo under the subsection of programming language you are willing to contribute.
If, yes, drop it and open a new issue with a new and unique idea.
If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
Issues will be assigned on a first come first serve basis.

Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
> @rk05-lenavo
> Check whether it is already there in the repo under the subsection of programming language you are willing to contribute.
> If, yes, drop it and open a new issue with a new and unique idea.
> If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
> Issues will be assigned on a first come first serve basis.
> 
> Happy Coding!😊

As of now I'm closing this. Thanks.
