### ISSUE TITLE
Find Prime number till n ( Method 1) ( nestedloop) ( C++)

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [HarshCasper/NeoAlgo#2963]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES

(Write your answer here.)
I will like to add code in CPP which find the prime number till the input given by the user and print the number and also gives the count of numbers !!

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for this issue in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
