### ISSUE TITLE
Finding Prime Number in a range from a to b ( Method 1 ) ( nestedloop) ( c++)

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [HarshCasper/NeoAlgo#2964]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

(Write your answer here.)
I will like to add code in c++ language which gives prime number  in range a to b given by user !!

**Comment by Dimple115** [comment]
Hey, I'm gssoc'21 participant, I would like to give my hand in this project. Please assign this issue to me.

**Comment by simarjeet30** [comment]
I am a GSSOC participant ,will like to add code in c++ language which gives prime number in range a to b given by user !!

**Comment by Priyanshu078** [comment]
I want to contribute to this issue please assign me this issue.
I would like to like to add code in c++ language which gives prime numbers in range a to b given by the user.

**Comment by Priyanshu078** [comment]
I am a GSSOC participant

**Comment by RuchiGitHu** [comment]
Hi @HarshCasper ,
Please assign this issue to me using java language. I want to work on this issue. Looking forward to learn new from contributions.
Thanks in advance...

**Comment by Priyanshu078** [comment]
Please assign me this issue 
I am a GSSOC participant

**Comment by rohan-kulkarni-25** [comment]
Why I am not asked for getting assigned I created issue I should get assigned !

**Comment by RuchiGitHu** [comment]
> Why I am not asked for getting assigned I created issue I should get assigned !

@rohank2502, after creating an issue you can assign yourself for the issue automatically just by /assign command. The bot will assign you for that issue..
