### ISSUE TITLE
Flip the Binary Tree

### ISSUE THREAD

**Issue by richakumari19** [HarshCasper/NeoAlgo#2965]
**Assume a binary tree, the task is to flip the binary tree towards the right direction that is clockwise.**

### **Have you read the [Contributing Guidelines on Pull Requests]**

Yes, I've read the guidelines.

As a GSSOC21 Participant , I would love to work on this issue.
@ankitaggarwal23 Please assign me this issue under GSSOC'21

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo Can you please bit more elaborate how you're going to implement and also in which language you want to work?

**Comment by richakumari19** [comment]
@ankitaggarwal23 In this leftmost node becomes the root of the flipped tree and its parent becomes its right child and the right sibling becomes its left child and the same should be done for all left most nodes recursively. I'll be using C++.

**Comment by ankitaggarwal23** [comment]
@rk05-lenavo I can't assign you now because you already have more than 3 issues open. Kindly first finish that first. We can't assign  issues to contributor who already have 3 or more than that opened. Thanks, Closing as of now.
