### ISSUE TITLE
Proposal to change an existing code

### ISSUE THREAD

**Issue by Mohim-Singla** [HarshCasper/NeoAlgo#2966]
## 💥 Proposal to change an existing code

C-Plus-Plus/stack/Check_for_balanced_parenthesis.cpp  
This program checks the brackets balancing for only the round ( ) parenthesis I want to make some minor changes and  improve this code to give the desired output for:-
1. square [ ] and curly { } parenthesis too.
2. [   (   ]  ) This is invalid parenthesis whereas [  (  )  ] this is balanced and valid parenthesis.

Please check if this issue can be assigned to me or not. Thank you!

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
@Mohim-Singla Awesome that you want to update some existing code. Can you tell us whether you are working under Gssoc as a participant?

**Comment by Mohim-Singla** [comment]
@ankitaggarwal23 yes, I'm participant of GSSoC 21

**Comment by ankitaggarwal23** [comment]
Great! @Mohim-Singla Hi, I assigned you. Happy Coding!😊

**Comment by Mohim-Singla** [comment]
@ankitaggarwal23  Please review this pull request.
