### ISSUE TITLE
Implementation of Trie Data structure Using Java Hashmap

### ISSUE THREAD

**Issue by pm0824** [HarshCasper/NeoAlgo#2968]
## 💥 Proposal

Hii, I am Prachi
I want to add Java program to perform insert and search operations on Trie Data Structure.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes and I'll follow the same.

I am GSSoC'21 participant and would like to contribute to this project.
Kindly assign me this issue.

**Comment by ankitaggarwal23** [comment]
@pm0824 Hi, I assigned you. Happy Coding!😊
