### ISSUE TITLE
Finding Linked List is Palindrome or Not

### ISSUE THREAD

**Issue by sumitgsh** [HarshCasper/NeoAlgo#2969]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes ofcourse!!
## Motivation

(Please outline the motivation for the proposal.)
Its a Classical Problem which is often asked in Interviews!!

Problem Statement:
Given a linked list you need to find whether the given linked list is Palindrome or Not
Input: 1->2->1
Output: Palindrome

Input:1->2->3
Output: Not Palindrome

Input: 1
Output: Palindrome(a no is always palindrome)

## Pitch
(Please explain why this feature should be implemented and how it would be used.)
This problem will help developers realize how Linked List data structure can be used in various Set of problems :)

**Comment by sumitgsh** [comment]
@siddharth25pandey @HarshCasper @iamrajiv  can u please assign me the issue !!
Would love to work on C as a part of GsSoc21

**Comment by niserene** [comment]
@siddharth25pandey @iamrajiv @HarshCasper , I would like to contribute for the issue in Java/C++ , please  assign this task to me

**Comment by cintamg** [comment]
@siddharth25pandey @iamrajiv @HarshCasper I m a GSSOC'21 participant, I would like to contribute to this issue in Java, please assign this issue to me.

**Comment by ankitaggarwal23** [comment]
> @siddharth25pandey @HarshCasper @iamrajiv can u please assign me the issue !!
> Would love to work on C as a part of GsSoc21

@sumitgsh Hey, can you tell me which DSA you are going to implement as already this kind of issue someone else already solving.

**Comment by ankitaggarwal23** [comment]
> @siddharth25pandey @iamrajiv @HarshCasper , I would like to contribute for the issue in Java/C++ , please assign this task to me

@nishantsahu961 Hey, can you tell me which DSA you are going to implement as already this kind of issue someone else already solving and also you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
> @siddharth25pandey @iamrajiv @HarshCasper I m a GSSOC'21 participant, I would like to contribute to this issue in Java, please assign this issue to me.

@cintamg Hey, can you tell me which DSA you are going to implement as already this kind of issue someone else already solving and also you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊

**Comment by cintamg** [comment]
@ankitaggarwal23 I am going to implement this using a doubly-linked list, in Java.

**Comment by ankitaggarwal23** [comment]
@sumitgsh @cintamg @nishantsahu961 
Check whether it is already there in the repo under the subsection of programming lang you are willing to contribute.
If, yes, drop it and open a new issue with a new and unique idea.
If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
Issues will be assigned on a first come first serve basis.

Happy Coding!😊

**Comment by cintamg** [comment]
@ankitaggarwal23
Can u tell me how I can mention the link to this issue while creating the new issue?

**Comment by sumitgsh** [comment]
> @sumitgsh Hey, can you tell me which DSA you are going to implement as already this kind of issue someone else already solving.

@ankitaggarwal23  I would be using two pointers approach and will STACK as well.
I had seen someone else is working on the issue, but I want to work using C language, as no one is working on that(Even I mentioned in the first comment of the issue)
Others who are working on the same are:
Issue no:#2951(working in C++)
Issue no: #2891(Working in java)

**Comment by ankitaggarwal23** [comment]
@sumitgsh Hi, I assigned you. Happy Coding!😊
