### ISSUE TITLE
Infix to Prefix Expression in Java

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#2970]
## 🚀 Feature

(A clear and concise description of what the feature is.)
I want to implement a Java program to convert an infix expression to a prefix expression.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
I would like to implement it as a part of GSSOC'21.
(Please outline the motivation for the proposal.)

## Pitch
I would like to implement a Java program to convert an infix expression to a prefix expression.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by iamvs-2002** [comment]
The related issue is #2769

**Comment by iamvs-2002** [comment]
Kindly assign me this issue.

**Comment by ankitaggarwal23** [comment]
@iamvs-2002 Hi, I assigned you. Happy Coding!😊

**Comment by iamvs-2002** [comment]
> @iamvs-2002 Hi, I assigned you. Happy Coding!😊

Thank you!
