### ISSUE TITLE
QUICK SORTING IN C

### ISSUE THREAD

**Issue by Sakshi2517** [HarshCasper/NeoAlgo#2975]
**Description**
quick sorting of elements in the array in ascending order
here i will take end element of array as a pivot element of the array finally after the loop we will get the position to interchange the pivot with index so that all the elements greater than pivot will be right side and lesser than pivot will be left side
hey  @HarshCasper i want to add this question in the 'NeoAlgo/C'.

**Comment by ankitaggarwal23** [comment]
@Sakshi2517 Hi, I assigned you. Happy Coding!😊

**Comment by Pallavi-02** [comment]
I'm GSSoC'21 Participant . Please assign me this issue.I would love to work on this.

**Comment by ASLManasa** [comment]
@ankitaggarwal23 I'm GSSoC'21 Participant . Please assign me this issue.I would like to work in java.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 I'm GSSoC'21 Participant . Please assign me this issue. I would like to work in java.

Hi @ASLManasa Actually Someone else is already working on C++. So you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
Also before opening a new issue,
- Check whether it is already there in the repo under the subsection of programming language you are willing to contribute.
- If, yes, drop it and open a new issue with a new and unique idea.
- If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
Issues will be assigned on a first come first serve basis.

**Comment by ankitaggarwal23** [comment]
> I'm GSSoC'21 Participant . Please assign me this issue. I would love to work on this.

Hi @Pallavi-02 Actually Someone else is already working on C++. So you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
Also before opening a new issue,
- Check whether it is already there in the repo under the subsection of programming language you are willing to contribute.
- If, yes, drop it and open a new issue with a new and unique idea.
- If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
Issues will be assigned on a first come first serve basis.

**Comment by Vedika-Agrawal** [comment]
Hello,I am GSSOC participant .I want to add the code to "QUICK SHORTING IN C" Iwill write the code with proper comments and examples .
Can you please assign this issue to me under GSSOC.

**Comment by ankitaggarwal23** [comment]
@Vedika-Agrawal Actually Someone else is already working on C. So Can't assign you in C.
