### ISSUE TITLE
First and last occurrence of x in array.

### ISSUE THREAD

**Issue by mu593** [HarshCasper/NeoAlgo#2977]
## 🚀 Feature

(I write a code in cpp, can you assign me this issue.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Help to people to crack coding interview.)

## Pitch

(As this question ask in many technical Interview.)

**Comment by ankitaggarwal23** [comment]
Need to add a description and can you please bit more elaborate how you're going to implement and also tell us whether you are working under Gssoc as a participant? Thanks, Closing as of now.
