### ISSUE TITLE
Bubble Sort Algorithm

### ISSUE THREAD

**Issue by jyoti-anjaly** [HarshCasper/NeoAlgo#2979]
## 📚 Documentation

Hello , I am GSSOC'21 Participant. And I want to add "Bubble Sort Article" in C++ that how Bubble Sort Algorithm works.
Can you please assign me this issue? 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by Simar05519** [comment]
Thankyou for assigning
