### ISSUE TITLE
Expressing n as a product of prime numbers (in C++)

### ISSUE THREAD

**Issue by divya-rai-42** [HarshCasper/NeoAlgo#2980]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read the contributing guidelines.
Through this algorithm , we can represent a number n(>1) as product of prime numbers. For example, if the input is 12 then output will be (2,2,3) , if input is 28 then output will be (2,2,7).

**Comment by ankitaggarwal23** [comment]
@divya-rai-42 Hi Can you tell us whether you are working under Gssoc as a participant?

**Comment by divya-rai-42** [comment]
Yes , sir!

**Comment by ankitaggarwal23** [comment]
@divya-rai-42 Hi, I assigned you. Happy Coding!😊

**Comment by Pallavi-02** [comment]
I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on

**Comment by divya-rai-42** [comment]
@ankitaggarwal23  
Thank you sir!

**Comment by ankitaggarwal23** [comment]
> I'm the Participant of GSSOC'21. Please assign me this issue.I would love to work on

Hi @Pallavi-02 Actually Someone else is already working on C++. So you can open a new issue with the same concept but with implementation in a different programming language. We will assign it to you then. Happy Coding!😊
Also before opening a new issue,
- Check whether it is already there in the repo under the subsection of programming language you are willing to contribute.
- If, yes, drop it and open a new issue with a new and unique idea.
- If no, open a new issue by mentioning the link to this issue and the programming language you would want to contribute in.
Issues will be assigned on a first come first serve basis.

**Comment by divya-rai-42** [comment]
Sir, can you please inform me within how many days will I have to submit my work . Actually , my end semester examinations are commencing from 15th March and will continue till 19th of March. It would be highly obliging if I am permitted to submit it after 19th March.

**Comment by ankitaggarwal23** [comment]
> Sir, can you please inform me within how many days will I have to submit my work . Actually , my end semester examinations are commencing from 15th March and will continue till 19th of March. It would be highly obliging if I am permitted to submit it after 19th March.

@divya-rai-42 No issue, You can submit this after your exams also!
