### ISSUE TITLE
Creating a password generator (in Python)

### ISSUE THREAD

**Issue by divya-rai-42** [HarshCasper/NeoAlgo#2982]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read the contribution guidelines.
Through this algorithm, we can create a password of a length  of user's choice. It will contain atleast one uppercase alphabet, one lowercase alphabet, one integer and one special character (from @,#,$,&,*). Therefore, minimum length of the password will be four characters.
I will be using random library of python.

**Comment by Naman-12911** [comment]
Hello sir I want fix this issue please assign me under GSSOC

**Comment by divya-rai-42** [comment]
Sir, can you please inform me within how many days will I have to submit my work . Actually , my end semester examinations are commencing from 15th March and will continue till 19th of March. It would be highly obliging if I am permitted to submit it after 19th March.

**Comment by Naman-12911** [comment]
I will sumbit this code by today.

**Comment by Naman-12911** [comment]
<img width="601" alt="2021-03-14 (2)" src="https://user-images.githubusercontent.com/66183578/111063451-8557f780-84d4-11eb-9cd0-ab6bb87d19f4.png">
)

I have included 3 screen shots.
Is this output is ohk??
or I do some modifications

**Comment by Naman-12911** [comment]
> Hello sir I want fix this issue please assign me under GSSOC

I created a pull request you can merge it.

**Comment by Naman-12911** [comment]
<img width="960" alt="2021-03-14 (3)" src="https://user-images.githubusercontent.com/66183578/111078346-f3bfa880-851a-11eb-8ade-dd177a1c5588.png">
when I  create a  pull request . why I got this issue please tell me.

**Comment by atarax665** [comment]
> Sir, can you please inform me within how many days will I have to submit my work . Actually , my end semester examinations are commencing from 15th March and will continue till 19th of March. It would be highly obliging if I am permitted to submit it after 19th March.

You are free to submit your work after 19th March. But @Naman-12911 has already made a PR for this issue in Python so can you please contribute it in some other language you are comfortable with.

**Comment by atarax665** [comment]
> <img alt="2021-03-14 (3)" width="960" src="https://user-images.githubusercontent.com/66183578/111078346-f3bfa880-851a-11eb-8ade-dd177a1c5588.png">
> 
> when I create a pull request . why I got this issue please tell me.

@Naman-12911  You can ignore the java CI as it has some glitch but please check detailed analysis of python CI and make changes accordingly. I can find that your program have 3 style error and 1 anti-pattern error. Please resolve them.

**Comment by Naman-12911** [comment]
> > <img alt="2021-03-14 (3)" width="960" src="https://user-images.githubusercontent.com/66183578/111078346-f3bfa880-851a-11eb-8ade-dd177a1c5588.png">
> > when I create a pull request . why I got this issue please tell me.
> 
> @Naman-12911 You can ignore the java CI as it has some glitch but please check detailed analysis of python CI and make changes accordingly. I can find that your program have 3 style error and 1 anti-pattern error. Please resolve them.
Ohk thanks. I will resolve it.
