### ISSUE TITLE
Count of subsets with given difference in c++ using Dynamic Programming

### ISSUE THREAD

**Issue by shriya030** [HarshCasper/NeoAlgo#2985]
## 🚀 Feature
I am GSSOC'21 participant and would like to add this problem of counting subsets with the given difference in c++ using Dynamic Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)
Since everyone thinks that Dynamic programming is very tough, so I want to give a simple approach to this problem which seems to be tough

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This problem can be easily implemented by using the problem that is the count of subsets with a given sum.

**Comment by ankitaggarwal23** [comment]
@shriya030 Hi, I assigned you. Happy Coding!😊
