### ISSUE TITLE
Infix to Postfix in Java

### ISSUE THREAD

**Issue by iamvs-2002** [HarshCasper/NeoAlgo#2988]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

## Motivation
I would like to implement a program to convert infix to postfix in Java as a part of GSSOC'21.
(Please outline the motivation for the proposal.)

## Pitch
It is very similar to #2970 
It's just the reverse of the prefix expression. Kindly allow me to implement the same for Postfix too.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by ankitaggarwal23** [comment]
@iamvs-2002 Hi, I assigned you. Happy Coding!😊

**Comment by iamvs-2002** [comment]
> @iamvs-2002 Hi, I assigned you. Happy Coding!😊

Thanks a lot.
