### ISSUE TITLE
Lexicographic rank of a string in C

### ISSUE THREAD

**Issue by rohanbabbar04** [HarshCasper/NeoAlgo#2993]
## 🚀 Feature

Given a string, find its rank among all its permutations sorted lexicographically. For example, rank of “abc” is 1, rank of “acb” is 2, and rank of “cba” is 6. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Would like to solve this problem as a part of GSSOC'21

## Pitch

This problem is asked in interviews of many companies and is an important CP question.

**Comment by ankitaggarwal23** [comment]
@rohanbabbar04 Hi, I assigned you. Happy Coding!😊
