### ISSUE TITLE
Rotate unsorted array by k elements (Juggling Algorithm)

### ISSUE THREAD

**Issue by sakshigoel19** [HarshCasper/NeoAlgo#2994]
## 💥 Proposal
Given an unsorted array of n elements , rotate it by k elements in the counter clockwise direction. I am a GSSOC'21 participant and I would like to implement it using the juggling algorithm which works in O(n) time. I will write well documented code in C++. @gat786  Please assign this issue to me.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

**Comment by ankitaggarwal23** [comment]
@sakshigoel19 Hi, I assigned you. Happy Coding!😊
