### ISSUE TITLE
Smallest Positive missing number

### ISSUE THREAD

**Issue by priyanka001tech** [HarshCasper/NeoAlgo#2995]
## 💥 Proposal

To find smallest positive missing number in the given array using c++.(THIS PROBLEM IS ASKED BY AMAZON,SAMSUNG,SNAPDEAL etc,)

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

Example:
0,-10,1,3,-20
Output: 2

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by Simar05519** [comment]
I have requested for this issue first 2days back but it is assigned to
someone else who has requested later

**Comment by HarshCasper** [comment]
> /assign

As a first and last warning, don't use `/assign` for those issues you have *NOT* created.

**Comment by priyanka001tech** [comment]
Please review this
