### ISSUE TITLE
Find largest word in a sentence in cpp

### ISSUE THREAD

**Issue by priyanka001tech** [HarshCasper/NeoAlgo#2998]
## 💥 Proposal

Find largest word in a sentence in c++ where input is taken using cin.getline() function.

### Have you read the [Contributing Guidelines on Pull Requests]
YES

I would like to code it as a gssoc'21 participant.

**Comment by Simar05519** [comment]
Recently I had done this program with less time complexity. I want to work on this issue. Please assign to me.

**Comment by AkanshaUniyal** [comment]
@HarshCasper  I would like to do this using Java. Please assign me under GSSOC'21

**Comment by Simar05519** [comment]
Is it assigned to me?

**Comment by Priyanshu078** [comment]
I want to contribute to this issue  please sign it to me

**Comment by Priyanshu078** [comment]
I am a GSSOC Participant

**Comment by adysis14** [comment]
hello! I am interested in contributing to this issue . kindly assign this issue to me under gssoc'21.

Thank You
