### ISSUE TITLE
ADDING IMPORTANT PATTERN PROBLEMS

### ISSUE THREAD

**Issue by vishakha-aggarwal** [HarshCasper/NeoAlgo#3000]
### **EXPLANATION:**

OUR TASK IS TO PRINT THE PATTERNS THE FOLLOWING PATTERNS BY IMPLEMENTING LOOPS ::

1. FLOYD'S TRIANGLE
2. HOLLOW BUTTERFLY
3. SOLID BUTTERFLY
4. HOLLOW RECTANGLE
5. HOLLOW PARALLELOGRAM
6. SOLID PARALLELOGRAM
7. HOLLOW DIAMOND
8. SOLID DIAMOND
9. PASCAL TRIANGLE
10. PALINDROME PATTERN

Hey @HarshCasper  , I want to add these pattern problems in C++ language in `NeoAlgo/C-Plus-Plus` .

**Comment by vishakha-aggarwal** [comment]
Hey admins, I have created this issue. I want to work on this issue under GSSOC'21.
I have read all the contributing guidelines.

**Comment by vishakha-aggarwal** [comment]
Hey admins, I have created this issue. I want to work on this issue under GSSOC'21.
I have read all the contributing guidelines. Please assign it to me.

**Comment by ankitaggarwal23** [comment]
@vishakha-aggarwal Are you going to print all the pattern at once or you are creating a some menu driven program. I didn't get exactly. Can you please bit more elaborate how you're going to implement?

**Comment by vishakha-aggarwal** [comment]
I was thinking to create a folder in which there will be all the programs.

**Comment by vishakha-aggarwal** [comment]
I can also create a menu driven if you would prefer that.

**Comment by ankitaggarwal23** [comment]
> I was thinking to create a folder in which there will be all the programs.

Means your are writing different programs for each case? Is it so?
Take your time how your going to implement this add the same thing in the description as well then I will assign you.

**Comment by vishakha-aggarwal** [comment]
I have decided to create a menu driven calling different functions. Is it convenient to you to do so?

**Comment by ankitaggarwal23** [comment]
@vishakha-aggarwal Hi, I assigned you. Happy Coding!😊

**Comment by vishakha-aggarwal** [comment]
Thanks for assigning 😊
