### ISSUE TITLE
To check for palindrome in c#2969

### ISSUE THREAD

**Issue by cintamg** [HarshCasper/NeoAlgo#3001]
To find whether the string is a palindrome or not.

Test case 1:

Input : malayalam

Output : Palindrome
_____________________

Test case 2:

Input : 123454321

Output : Palindrome
_____________________

Test case 3:

Input : 12345

Output : Not palindrome

Hey @ankitaggarwal23 I want to add this question in the NeoAlgo/Code/C/dp

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by ankitaggarwal23** [comment]
@cintamg Can you tell us whether you are working under Gssoc as a participant?

**Comment by Simar05519** [comment]
Yes,I am working on it. If you have any doubt I can share also

**Comment by cintamg** [comment]
@ankitaggarwal23 I am a GSSOC participant.

**Comment by ankitaggarwal23** [comment]
@cintamg Hi, I assigned you. Happy Coding!😊

**Comment by Simar05519** [comment]
Is the issue assigned to me?

**Comment by ankitaggarwal23** [comment]
@Simar05519 is this your github name @cintamg ?

**Comment by Simar05519** [comment]
My github name is Simar05519

**Comment by ankitaggarwal23** [comment]
Okay, @Simar05519  Actually Someone else is already working on C++, C, Java, C#. I can't assign you in that issue. You can choose different issue in which you want to work. I will assign you if no one is working on that issue. Happy Coding!😊

**Comment by Simar05519** [comment]
So it means I am not assigned with this issue?

**Comment by ankitaggarwal23** [comment]
@Simar05519 Yes I can't. Already so many participants are already working.

**Comment by ankitaggarwal23** [comment]
@Simar05519 Don't worry there are many issues available. You can explore in issues section.

**Comment by Simar05519** [comment]
Ok, thanks.
