### ISSUE TITLE
All unique prime factors of n (in C++)

### ISSUE THREAD

**Issue by Kirti1807** [HarshCasper/NeoAlgo#3005]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes , I have read the contributing guidelines.
Hey , I am Kirti as a GSSoc'21 participant,
In this algorithm  we can find all unique prime factors of any number n where n>1.For example if n is 24 then output will be (2,3), if  n is 30 then out put will be (2,3,5).
Please assign this task to me!

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by simarjeet30** [comment]
Hey , I am Simarjeet ,a GSSoc'21 participant,
In this algorithm we can find all unique prime factors of any number n .For example if n is 20 then output will be (2,5)
Please assign this task to me!

**Comment by samya02** [comment]
Hey I am Samya , a GSSOC'21 participant.
I want to work on this issue. I can work on python, c++ as well. Please assign this task to me !
Thanks!

**Comment by ShyrenMore** [comment]
Hello, I am Shyren, a GSSoC'21 participant,
Please assign this task to me!
My **approach** to solving this problem would be by **using Sieve of Eratosthenes** and then **storing the prime factors in a set**
I can implement the above approach using C++
I have read the Contributing Guidelines on Pull Requests

**Comment by Naman-12911** [comment]
I want to solve this issue please assign me.
Under GSSOC.
I solve this issue in cpp
