### ISSUE TITLE
Lexicographically Largest Palindromic Subsequence

### ISSUE THREAD

**Issue by sanskruti-shahu** [HarshCasper/NeoAlgo#3007]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Hey I am Participant of GSSOC'21. And I have read all the Contributing Guidelines.
I want to propose a program which take string of any length as input and in output we get lexicographically largest palindrome string with its length. 
For Example:  Input = bassoon   Output = ss 2. 
@ankitaggarwal23  Please assign me this issue.

**Comment by ankitaggarwal23** [comment]
@sanskruti-shahu Hi, I assigned you. Happy Coding!😊

**Comment by ankitaggarwal23** [comment]
@sanskruti-shahu Hi, Can you tell me in which language you want to work. So that I can assign you!

**Comment by sanskruti-shahu** [comment]
Sir, I want to work in C++ language.

**Comment by ankitaggarwal23** [comment]
@sanskruti-shahu Hi, I assigned you. Happy Coding!😊

**Comment by sanskruti-shahu** [comment]
Thank You Sir!!
