### ISSUE TITLE
Intro Sort

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#301]
Intro Sort:
It is a hybrid sorting algorithm that initially uses quicksort, but switches to heap sort if the depth of the recursion is too deep, and uses insertion sort for small cases. The most popular C++ STL Algorithm- sort() used Intro sort.

### Languages:
* C++
* Python [@atarax665 ]
* C
* C#
* Javascript
* GO

**Comment by atarax665** [comment]
I would like to take this issue in Python.

**Comment by atarax665** [comment]
Done

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++.

**Comment by viveksahu26** [comment]
I would like to work on this issue in java.. Please assign me this issue..

**Comment by Lakhan-Nad** [comment]
Hey @atarax665 I would like to work on this issue in JavaScript. I have already implemented this in C++ 
[check it here](https://gist.github.com/Lakhan-Nad/78f55ae9a88f6eb42902fccfd0bb267f).

**Comment by kashika3101** [comment]
I would like to work on this issue in c++ . Please assign it to me
