### ISSUE TITLE
All permutation of a string

### ISSUE THREAD

**Issue by Kirti1807** [HarshCasper/NeoAlgo#3010]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes, I have read the contributing guidelines.
hey, I am Kirti as a GSSoC '21 participant,
Through this method we can find all permutation of a string. for example if given string is "abc" then output will be ("abc","acb","bac","bca","cab","cba").
Please assign this task to me!

**Comment by ankitaggarwal23** [comment]
@Kirti1807 Can you tell me in which language you want to work. So that I can assign you?

**Comment by Kirti1807** [comment]
sir , I want to work in C++

**Comment by ankitaggarwal23** [comment]
@Kirti1807 Hi, I assigned you. Happy Coding!😊

**Comment by Kirti1807** [comment]
Thank you sir!😊
