### ISSUE TITLE
C Program to Concatenate Two Strings 

### ISSUE THREAD

**Issue by jyoti-anjaly** [HarshCasper/NeoAlgo#3011]
## 💥 Proposal

Hello, I am GSSOC'21 participant. I want to add the code of concatenation of two strings in C. I will write the code with proper comments and examples.
Can you please assign this issue to me under GSSOC?

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes , I have read the Contributing guidelines.

**Comment by ankitaggarwal23** [comment]
@jyoti-anjaly Hi, I assigned you. Happy Coding!😊

**Comment by jatinyadav5004** [comment]
Hello, I am GSSOC'21 participant. I want to add the code of concatenation of two strings in C. I will write the code with proper comments and examples too .
Can u assign me this under GISSOC.

**Comment by ankitaggarwal23** [comment]
> Hello, I am GSSOC'21 participant. I want to add the code of concatenation of two strings in C. I will write the code with proper comments and examples too .
> Can u assign me this under GISSOC.

@jatinyadav5004  Actually Someone else is already working on C.

**Comment by jyoti-anjaly** [comment]
@ankitaggarwal23 Can you please check whether the file added by me is correct or not? I am getting one error but I am facing difficulty in solving that.

**Comment by ansi22-zz** [comment]
Hello mentors :)
I would like to add the same ,i.e, concatenation of two strings in C++.
Kindly assign it to me.
@ankitaggarwal23

**Comment by jyoti-anjaly** [comment]
@ankitaggarwal23 Sir,  Can you please check my work?  My second  pull request number is #3103
I'm so sorry as I'd not mentioned earlier my issue number in my first pull request.And for this mistake of not mentioning issue number, my first pull request got closed.
