### ISSUE TITLE
Lazy Propagation in Segment Tree

### ISSUE THREAD

**Issue by vanshika2906** [HarshCasper/NeoAlgo#3025]
## 🚀 Feature
When there are many updates and updates are done on a range, we can postpone some updates (avoid recursive calls in update) and do those updates only when required.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes.

## Motivation
Lazy Propagation – An optimization to make range updates faster

## Pitch
The idea is to initialize all elements of lazy[] as 0. A value 0 in lazy[i] indicates that there are no pending updates on node i in segment tree. A non-zero value of lazy[i] means that this amount needs to be added to node i in segment tree before making any query to the node.

**Comment by vanshika2906** [comment]
I am a GSSOC Participant. Good Knowledge of Data Structures and want to work on this. Please Assign this issue to me.

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
