### ISSUE TITLE
Array Manipulation in C++

### ISSUE THREAD

**Issue by yr7000** [HarshCasper/NeoAlgo#3027]
## 🚀 Feature

Array manipulation is one of hackerrank problems. It is a nice variation of the prefix sum problem.
Question link: https://www.hackerrank.com/challenges/crush/problem

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation
While solving this problem I learned a new optimization technique, Which can be used in many problems in various contests to reduce the time complexity.

## Pitch

This problem will teach us a new optimization technique and it is a nice variation of the prefix sum problem. 
I would like to contribute my approach to this problem using c++.
Hey, @ankitaggarwal23  please look into this issue and please assign this to me under GSSOC2021.
Thank you.

**Comment by yr7000** [comment]
Hey @anushkrishnav please look into this issue and please assign this to me under gssoc2021
Thank you.

**Comment by yr7000** [comment]
Hey @ankitaggarwal23 please look into this issue and please assign this to me under gssoc2021
Thank you.

**Comment by bhav09** [comment]
All the best.

**Comment by yr7000** [comment]
Thank you @bhav09 for assigning this issue to me
