### ISSUE TITLE
Printing Tribonacci series up to "n" number of terms.

### ISSUE THREAD

**Issue by AkanshaUniyal** [HarshCasper/NeoAlgo#3028]
## 💥 Proposal

This Algorithm prints Tribonacci series up to "n" terms where the value of "n" is to be provided by the user.
a(n)=a(n-1)+a(n-2)+a(n-3)

For Example:
(input) n=10
(output):  0, 0, 1, 1, 2, 4, 7, 13, 24, 44

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by AkanshaUniyal** [comment]
Hey @ankitaggarwal23 please assign this issue to me under GSSOC'21. I want do to this in Java Language.

**Comment by ankitaggarwal23** [comment]
@AkanshaUniyal Hi, I assigned you. Happy Coding!😊

**Comment by AkanshaUniyal** [comment]
@ankitaggarwal23 can you please tell me in which folder should I upload it? I mean algo or math?

**Comment by ankitaggarwal23** [comment]
@AkanshaUniyal Add in math folder.
