### ISSUE TITLE
Conversion of Binary Number to Decimal Number in C++

### ISSUE THREAD

**Issue by sanskruti-shahu** [HarshCasper/NeoAlgo#3029]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Hey I am GSSOC'21 Participant and I have read the Contributing Guidelines.
I want to propose a program in which Binary Number (up to 10 digits) will be given as input and in output we get the number in its Decimal form.
Example: Input  1000   Output  8
@ankitaggarwal23 Please assign me this issue.

**Comment by simarjeet30** [comment]
Hey I am GSSOC'21 Participant ,
I want to write a program:
input: Binary Number
output:  we get the number in its Decimal form.
Example: Input 1000 Output 8
@ankitaggarwal23 Please assign me this issue.
