### ISSUE TITLE
Sorting algorithms in C++

### ISSUE THREAD

**Issue by neha07kumari** [HarshCasper/NeoAlgo#3030]

**Comment by neha07kumari** [comment]
### Feature
Solutions of all sorting algorithms in C++

### Language: C++
### Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
I want to contribute to it under GSSoC'21.

### Pitch:
I would like to take up this task to implement it in C++. @bhav09

**Comment by bhav09** [comment]
Hey @neha07kumari, solutions to sorting algorithms are already there in the C++ directory. However, you can choose to work on a unique sorting algo that hasn't been implemented yet and then open the issue for that. 
Closing the issue as of now.
