### ISSUE TITLE
Find duplicate element code(using XOR)

### ISSUE THREAD

**Issue by kanchi12P** [HarshCasper/NeoAlgo#3032]
## 🚀 Feature
finding the duplicate number in an array of n+1 number ;
finding two missing numbers in an array of n-2 integers from 1 to n;

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation
its a good problem for the implementation of bit manipulation
## Pitch
bit manipulation( using XOR) makes this type of problem very easy
so I would like to add it.

**I am gssoc'21 participant**
**please assign it to me**

**Comment by ankitaggarwal23** [comment]
@kanchi12P Can you tell me in which language you want to work?

**Comment by kanchi12P** [comment]
I want to work in C++.

**Comment by kanchi12P** [comment]
@ankitaggarwal23 shall I start working?

**Comment by ankitaggarwal23** [comment]
@kanchi12P Hi, I assigned you. Happy Coding!😊
