### ISSUE TITLE
NQueen Problem for CPP

### ISSUE THREAD

**Issue by dsnehasish74** [HarshCasper/NeoAlgo#3038]
I want to add for the solution of this NQueen Problem solution using Backtracking  as a part of GSSOC21

**Comment by Naman-12911** [comment]
Hello I want to solve this problem under GSSOC please assign me

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
