### ISSUE TITLE
non-functional link in README.md

### ISSUE THREAD

**Issue by malirl** [HarshCasper/NeoAlgo#3039]
## 📚 Documentation

`README.md` has one non-functional link referenced to some .md that doesn't exist in the specified folder `ISSUE_TEMPLATE` at line 34.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
@amalir Actually Someone else is already working on this type of issue [here](https://github.com/TesseractCoding/NeoAlgo/issues/2907#issuecomment-798780741). Thanks, Closing as of now.
