### ISSUE TITLE
Trapping Rainwater Problem in C++

### ISSUE THREAD

**Issue by hritikgupta92** [HarshCasper/NeoAlgo#3040]
I'll be solving one the most difficult problem in array i.e Trapping rainwater or Rainwater harvesting problem using C++

**Comment by hritikgupta92** [comment]
@hushee69 please assign this issue to me.

**Comment by sakshi2707** [comment]
@hushee69 please assign me this issue, under gssoc

**Comment by Naman-12911** [comment]
I want to solve this problem with c++ under GSSOC

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
