### ISSUE TITLE
ALGORITHM: Fibonacci Search in cpp

### ISSUE THREAD

**Issue by Op-panda** [HarshCasper/NeoAlgo#3042]
## 🚀 Feature

****Fibonacci search**** is a searching algorithm, similar to binary search but have many differences too.  

### Have you read the [Contributing Guidelines on Pull Requests]
YES

## Motivation

- To get all the data structure and algorithm under one roof. 
- of course, GSSOC'21 is too a valid reason.

##### Pitch

It is one of the important algorithm that needs to be covered. 
I will be implementing it in **CPP**

**Comment by simarjeet30** [comment]
I want to work on this issue in C/C++/python . please assign this issue to me

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
