### ISSUE TITLE
ARRAY : Inverse of an array 

### ISSUE THREAD

**Issue by Op-panda** [HarshCasper/NeoAlgo#3043]
## please assign me this issue

This is very standard problem, in which we swaps the indices of the array with element.
This type of basic questions can make the users understand of the feel and concept of array.

### Have you read the [Contributing Guidelines on Pull Requests]
YES

I will be implementing the problem code in CPP with proper comments and explaination along with test cases.
code will be mine , I can guarantee that.

**Comment by simarjeet30** [comment]
I am a GSSOC21 participant ,I want to contribute to this issue in c++.please assign this issue to me

**Comment by yogitasaini** [comment]
please assign this task to me in java under GSSOC'21

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar

**Comment by simarjeet30** [comment]
please assign it to me @HarshCasper

**Comment by manasvvi1** [comment]
please assign this issue to me, i would like to work in cpp.
