### ISSUE TITLE
[REVIEWS] HELP NEEDED WITH ISSUES!

### ISSUE THREAD

**Issue by mar-galho** [HarshCasper/NeoAlgo#306]
As you may have noticed, we have a long list of issues here.

We need a brave soul to check whether we have any issues that have been dealt with - and please report to me whether there are any issues that may be closed (if the corresponding code has already been implemented, for example).

Since we are still looking for more reviewers for NeoAlgo, if you are interested in becoming a reviewer and help us manage this repo, this is a great test for you.

Please reply to this topic if you are interested in helping!

-Ricardo

**Comment by atarax665** [comment]
@ricardoprins I'm interested. I will be glad to help you guys in managing this repository. It will be a whole new experience for me.

**Comment by mar-galho** [comment]
Do you want to get started with this #306 then?

**Comment by atarax665** [comment]
Yes.

**Comment by atarax665** [comment]
@ricardoprins Can I help you with reviewing codes too? There are people who have been assigned issues a month back but we haven't heard anything from them yet.

**Comment by Rishikeshrajrxl** [comment]
Hey, can somebody merge my pull request for issue #392

**Comment by Rishikeshrajrxl** [comment]
I am really interested in reviewing it.
