### ISSUE TITLE
Check for palindromes C++

### ISSUE THREAD

**Issue by anjali494** [HarshCasper/NeoAlgo#3066]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
This program check if a given string is a palindrome or not.
i have seen this issue in python language but not in c++. I am a GSSOC'21 participant and would like to be assigned to this issue.

**Comment by samar08** [comment]
Hi ,I'm samar. I will implement code for above problem in Java. Please assign this issue to me.
