### ISSUE TITLE
Finding Pythagorian Triplet in C++

### ISSUE THREAD

**Issue by sanskruti-shahu** [HarshCasper/NeoAlgo#3076]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Hey!! I am GSSOC'21 participant. I have read contribution guidelines.
I want  to propose a program in which user will provide 3 integer input and the program will check whether the given input is pythagorian triplet or not.
Example: INPUT  12 13 5
               OUTPUT  Given triplet is pythagorian triplet

**Comment by HarshCasper** [comment]
This issue is open for anyone to take up. Just use `/assign` to take it up automatically

**Comment by Kirti1807** [comment]
Hello , I am Kirti can I work on it in C++
