### ISSUE TITLE
Polynomial addition using linked list.

### ISSUE THREAD

**Issue by cintamg** [HarshCasper/NeoAlgo#3083]
This is to add to polynomial expressions using linked list.

Example :
p1 =8x^3 + 3x^2 + 2x +6
p2 =23x^4 + 18x - 3
Resultant polynomial =23x^4 + 8x^3 + 3x^2 + 20x + 3

Hey @ankitaggarwal23 I want to add this question in the NeoAlgo/Code/C/dp.

**Comment by Suvraneel** [comment]
Duplicate issue #2389 
Already assigned to someone else...
kindly close this issue & PR

**Comment by ankitaggarwal23** [comment]
> Duplicate issue #2389
> Already assigned to someone else...
> kindly close this issue & PR

Thank you @Suvraneel for informing us. Will take necessary action.
