### ISSUE TITLE
ADDITION OF TWO BINARY NUMBERS

### ISSUE THREAD

**Issue by vishakha-aggarwal** [HarshCasper/NeoAlgo#3091]
### **EXPLANATION:**

Our task is to read two binary numbers from the user and we have to print the sum of those binary numbers.

**EXAMPLE:**

Input:
a=10101 (first binary number)
b=11011 (second binary number)

Output:
110000 

Hey @HarshCasper , I want to add this question in C++ language in `NeoAlgo/C-Plus-Plus` .

**Comment by vishakha-aggarwal** [comment]
Hey admins, I have created this issue. I want to work on it under GSSOC'21 . I have read all the contributing guidelines.
Kindly assign it to me.

**Comment by Samiksha519** [comment]
hello admins, I would like to work on this issue. kindly assign it to me. I find it really interesting.

**Comment by simarjeet30** [comment]
hello I am gssoc 21 participant , I would like to work on this issue. kindly assign it to m in C/C++/python.

**Comment by manasvvi1** [comment]
please assign this issue to me, i would like to work in cpp or in c.
