### ISSUE TITLE
SOME IMPORTANT NUMBER CONVERSIONS

### ISSUE THREAD

**Issue by vishakha-aggarwal** [HarshCasper/NeoAlgo#3095]
### **EXPLANATION:**

Our task is to create a menu driven program to perform following number conversions:

1. Binary to Decimal
2. Octal to Decimal
3. Hexadecimal to Decimal
4. Decimal to Binary
5. Decimal to Octal
6. Decimal to Hexadecimal

Hey admins, I want to add these important conversions in `NeoAlgo/C-Plus-Plus/other`.

**Comment by vishakha-aggarwal** [comment]
Hey admins, I have created this issue. I want to work on this under GSSOC'21. Please assign it to me.
I have read all the contributing guidelines.

**Comment by ankitaggarwal23** [comment]
@vishakha-aggarwal Found similar issue open by you #4371
