### ISSUE TITLE
Closed Hashing 

### ISSUE THREAD

**Issue by aish2002** [HarshCasper/NeoAlgo#3099]
## 🚀 Feature

I would like to implement Hash table using linear probing in C and C ++ as part of GSSOC'21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Hash Table is an inevitable data structure used for mapping keys with values

## Pitch

Hashing is an important technique in data structures and linear probing is a collision resolution technique which can be implemented using arrays

**Comment by HarshCasper** [comment]
> /assign

Don't self-assign Issues to yourself if you have not created them. Its a disrespect to the contributors who are putting up the hard work in making the Issues with prior research

**Comment by nikitajangid33** [comment]
I am really sorry for the same. I didn't meant to do this. I am newbie, i
was just exploring the site and projects. I had no clue that if I write
/assign it will assign me the issue. All these things are so new to me.
Sorry for the inconvenience, you can unassigned me if you want to.
