### ISSUE TITLE
To add all algorithm of Bit manipulation (Like brian-kernighans-algorithm)

### ISSUE THREAD

**Issue by saumyasrivastava08** [HarshCasper/NeoAlgo#3111]
## 💥 Proposal

(I will be uploading all the important algorithms regarding bit manipulation . please assign me this issue.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by iamrajiv** [comment]
@saumyasrivastava08 Update the issue description by adding all program names you want to add.
