### ISSUE TITLE
Adding Breath First search Graph code  in JavaScript 

### ISSUE THREAD

**Issue by Abhijit25Mishra** [HarshCasper/NeoAlgo#3118]
## 💥 Proposal

I saw a lot of code missing in the JavaScript section, I happen to have just learned JS would like to try and implement it 

in this particular issue I would like to work on **Breath First Search**

**Comment by HitainKakkar** [comment]
Greetings sir/Mam,
I would like to contribute the code for Bubble Sort Algorithm #933 in C++/CPP.
The code is ready. I have added the code , along with proper explanation of the algorithm , test cases , time complexity and space complexity of the same, as per the guidelines.
Kindly assign it to me.
This is regarding GSSOC'21.

Regards,
Hitain Kakkar
