### ISSUE TITLE
Adding Dijkstra algorithm Graph code in JavaScript

### ISSUE THREAD

**Issue by Abhijit25Mishra** [HarshCasper/NeoAlgo#3120]
## 💥 Proposal

I saw a lot of code missing in the JavaScript section, I happen to have just learned JS would like to try and implement it 

in this particular issue I would like to work on **Dijkstra algorithm**

**Comment by ritikasharma99** [comment]
Hi!! I am GSSOC'21 participant and would like to work on it in Java.
