### ISSUE TITLE
DS Priority Queue

### ISSUE THREAD

**Issue by ChiragTutlani** [HarshCasper/NeoAlgo#319]
**DS:** Priority queue

**Languages Supported:** C++

**Comment by ChiragTutlani** [comment]
I want to work on this. Please assign this to me.

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++.

**Comment by odavhad** [comment]
I would like to work on this issue in Python and C.

**Comment by vatsalkesarwani12** [comment]
I would like to contribute to this issue in java

**Comment by Sohailsaifi** [comment]
I would like to contribute to this issue in java

**Comment by Sohailsaifi** [comment]
I would like to contribute to this issue in c.

**Comment by imPGupta** [comment]
I can contribute on this in both C and CPP.

**Comment by Himanshu44626748** [comment]
I would like to work on this in java

**Comment by malet-ds** [comment]
I can work on this for Java or Python (or both). I am in CH20 and I am new to open source.

**Comment by lipsamishra1609** [comment]
i would like to work on this in javascript.
