### ISSUE TITLE
Exponential Search

### ISSUE THREAD

**Issue by rayvantsahni** [HarshCasper/NeoAlgo#323]
**Algorithm:** [Exponential Search](https://en.wikipedia.org/wiki/Exponential_search)

**Languages Supported:**
* C++
* C
* Javascript
* Python [@rayvantsahni]
* C#
* GO

**Comment by atarax665** [comment]
@rayvantsahni Sure, go for it.

**Comment by rayvantsahni** [comment]
Thank you

**Comment by Nagasuruthika** [comment]
I would like to work with C++ and Javascript - Hakincodes(P)

**Comment by SangeetaMishra** [comment]
@atarax665 I would like to work on this issue for C, C++ and Java.

**Comment by vinaykumar7686** [comment]
I would like to work with Python and Java

**Comment by viveksahu26** [comment]
I would to work on this issue on java.. so , please assign me..
