### ISSUE TITLE
Rabin-Karp Algorithm for Pattern Searching | C, Java

### ISSUE THREAD

**Issue by vieee** [HarshCasper/NeoAlgo#3247]
## 🚀 Feature

Implementation of Rabin-Karp Algorithm for Pattern Searching in C, Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
Contribution

## Pitch
For String Matching

**Comment by iamrajiv** [comment]
@vieee Rabin-Karp Algorithm is already been added in #340.
