### ISSUE TITLE
Job Scheduling with Maximum Profit

### ISSUE THREAD

**Issue by kratimitra** [HarshCasper/NeoAlgo#3276]
## 💥 Proposal

Hey,
I am Krati Mitra (Discord username Krati(P)#8709), a GSSOC'21 participant.
I want to add the code for the issue "Job Scheduling with Maximum Profit".

Task:
We are given X number of Jobs and their starting time, end time, and profit value of accomplishing them.
We have to find the maximum profit of any subset of them such that there is no overlapping between the time durations of the jobs.

Input is three arrays: BeginTime , EndTime , Profit
Output is an integer of Maximum profit of subset of Jobs

For example,
Example #1:
Input: startTime = [1,1], endTime = [5,6], profit = [12,17]
Output: 17
Explanation: We can choose the job with maximum profit i.e. second job .
 Thus the output is 17

Example #2:
Input: startTime = [2,7], endTime = [7,12], profit = [2,8]
Output: 10
Explanation: We can complete both the jobs with maximum profit= profit by first job + profit by second job 
as their time ranges does not clashes with each other 
Thus the output is 10

I can contribute to solve this issue using C++.
This problem can be solved using
a) Recursion with time complexity of O(N*2^N).
b)Dynamic Programming with time complexity of O(N^2).
c)Binary Search with time complexity of O(NlogN).

I'll try to inculcate these three approaches in my code.
Please assign me this task.

Thank You

**Comment by kanchan1910** [comment]
hey, @kratimitra  you have created this issue, so you better contribute to it, sorry for the inconvenience.
I am unassigning it!
happy coding..
