### ISSUE TITLE
Implementing Fibonacci Search in java

### ISSUE THREAD

**Issue by iamharshitpandeyy** [HarshCasper/NeoAlgo#3292]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Vishal-Singh-1996** [comment]
Pls assign it to me would like to create in java
