### ISSUE TITLE
(gssoc21 )Prim's Algorithm in cpp

### ISSUE THREAD

**Issue by kavyasree-123** [HarshCasper/NeoAlgo#3304]
## 🚀 Feature

Prim's Algorithm is used to find the minimum spanning tree from a graph.
input: {
  {5, 7, 85, 2, 1, 58, 45,1,7},
  {54 , 0, 75, 9, 2, 46 ,17,4,5},
  {63, 16, 0, 41, 66 , 48,36,48,84},
  {7, 9, 5, 0,65, 1,3,87,59 },
  {6, 72, 76, 75,48,95,49,46,47},
  {19, 25,65,39,17,24,28,12,14},
  {76,89,94,15,14,28,27,78,74},
  {1,75,48,75,48,63,15,4,8},
  {3,37,36,18,25,2,9,29,43}
};
output :Weight of ele, Edge of graph                                                                                                                                                         
1  0 - 4                                                                                                                                                                             
1  0 - 7                                                                                                                                                                             
2  0 - 3                                                                                                                                                                             
1  3 - 5                                                                                                                                                                             
3  3 - 6                                                                                                                                                                             
5  3 - 2                                                                                                                                                                             
7  0 - 1                                                                                                                                                                             
5  1 - 8

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation
to add to cpp ds
to add the new issues to have algorithm not mentioned already

## Pitch
Prim's algorithm finds the subset of edges that includes every vertex of the graph such that the sum of the weights of the edges can be minimized.

**Comment by kavyasree-123** [comment]
I want to add this issue which no one have already implemented .
please assign me this issue in python
i created this

**Comment by kanchan1910** [comment]
hey, @kavyasree-123 you have created this issue, so you better contribute to it, sorry for the inconvenience.
I am unassigning it!
happy coding

**Comment by kavyasree-123** [comment]
thank u so much.
