### ISSUE TITLE
Refactoring and enhancing the workflow of NeoAlgo

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#331]
**Is your feature request related to a problem? Please describe.**

Problems:

- the repositoryhas broken links across the readme files of different section.
- the wrong nomenclature of folders and files across the repository i.e. using `dp`, `sort` etc.
- grammatical and typo mistakes across repository.

**Describe the solution you'd like**

Solutions:

- fixing the broken links across all readme files of the repository.
- naming the folder and files with proper nomenclature and also make sure that all other programming language sections have the same name to maintain uniformity across the repo.
- fixing typos and grammatical mistakes.
- updating contributing guidelines to specify coding style format to use in different programming languages which will enhance the readability of code.
- updating the badges with flat-square style format something like this

<a href="https://github.com/TesseractCoding/NeoAlgo/blob/master/LICENSE" target="_blank"><img src="https://img.shields.io/github/license/tesseractcoding/neoalgo?style=flat-square" /></a> <img src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square" alt="PRs Welcome" /> <a href="https://github.com/TesseractCoding/NeoAlgo/pulls" target="_blank"><img alt="GitHub pull requests" src="https://img.shields.io/github/issues-pr/tesseractcoding/neoalgo?style=flat-square" /></a> <a href="https://github.com/TesseractCoding/NeoAlgo/issues" target="_blank"><img alt="GitHub issues" src="https://img.shields.io/github/issues/tesseractcoding/neoalgo?style=flat-square" /></a> <a href="https://github.com/TesseractCoding/NeoAlgo/blob/master/README.md#contributors-" target="_blank"><img alt="Github All Contributors" src="https://img.shields.io/github/all-contributors/tesseractcoding/neoalgo?style=flat-square" /></a>

**Additional context**

We may refactor and update more things which are not listed in the above problems as go through the problems.

**Comment by mar-galho** [comment]
Great ideas!

**Comment by vgb-codes** [comment]
These are valid and constructive points!
