### ISSUE TITLE
Check if a number is a palindrome or not

### ISSUE THREAD

**Issue by KarishmaVanwari** [HarshCasper/NeoAlgo#3318]
**Explanation**:

Given a number , find if the number is a palindrome or not.

**Example**:

Sample Input 1 : 12321
sample Output 1 : YES

Sample Input 2 : 12356
Sample Output 2 : NO

Hey @SKAUL05 sir , I want to add this question in the 'NeoAlgo/C-Plus-Plus/cp/'. Please have a look!

**Comment by kshithih** [comment]
Kindly issue this probleme to me .I am participant of GSSOC'21 I would implement this in python or C
