### ISSUE TITLE
3 SUM problem

### ISSUE THREAD

**Issue by Nidhideveloper** [HarshCasper/NeoAlgo#3327]
## 🚀 Feature

3 Sum problem is a good question which is highly concept building with respect to programming skills. This problem is a good problem of array and has been asked in many interviews of the top MNCs.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

HIGHLY CONCEPT BUILDING

## Pitch

3 Sum problem is a good question which is highly concept building with respect to programming skills.

**Comment by Nidhideveloper** [comment]
I would like to contribute to this issue as a participant of gssoc21 in java. Plz assign this to me.

**Comment by sujoypal51** [comment]
I can contribute to this issue by using C, C++, Python3. I am a GSSOC'21 participant.Please assign this issue to me.

**Comment by HONEYBIST** [comment]
I am a participant of GSSOC . I want to work on this issue , kindly assign this issue to me.

**Comment by nikitajangid33** [comment]
I can contribute to this issue in c++, Kindly  assign it to me.

Thanks and Regards,
 Nikita Jangid
Gssoc'21 Participant

**Comment by Amanduttbhagat** [comment]
Hello,
I would like to contribute to this issue in "Java" as a GSSoC 2021 participant
