### ISSUE TITLE
Optimised Bubble Sort

### ISSUE THREAD

**Issue by XZANATOL** [HarshCasper/NeoAlgo#3335]
## 🚀 Feature

Classic bubble sort indeed does it's job, but it always continue looping even when the array is already sorted. This algorithm will give a small optimisation to stop when sorted as it can detects when the array reaches the sorted phase.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [x] Yes

## Motivation

I am a GSSOC participant, and I like writing clean readable Python code along with Data Structures & Algorithms.

## Pitch

It will help build a foundation where a programmer must take care of sorted situations and gives an idea about how to increase the effciency of an existing algorithm.

## Details
* Worst & best time complixeties will be provided.
* User will be able to enter his own list.

**Comment by XZANATOL** [comment]
@ankitaggarwal23 Shall I use the bot assign functionality in this issue and future ones, or wait for reviews?

**Comment by ankitaggarwal23** [comment]
@XZANATOL I would suggest you to not take up the new one issue if you already have ongoing issue there or review pending because as per guidelines one contributor can take max 2-3 issues and if he/she solved and all the reviews and everything done then start with the new one.

Otherwise, what happen if one person is contributing in all the issues it is not fair to other participants. We have to be fair to all the participants as well.

**Comment by XZANATOL** [comment]
My latest issue was considering the Sine Function and already got merged on PR #3037 now I don't have assigned issues, and the issue of #2907 got closed for unknown reason.

I do understand what you are pointing at, but technically I'm free/don't have any other ongoing issues. :thinking:

**Comment by ankitaggarwal23** [comment]
@XZANATOL  Then okay you can take up new issue. Happy coding.
Before creating or taking up new issue just check once if any issue is already available or merged. If not just go for it.

**Comment by XZANATOL** [comment]
ok, I will, Thanks

**Comment by ankitaggarwal23** [comment]
@XZANATOL Hi, I assigned you. Happy Coding!😊
