### ISSUE TITLE
Rabin Karp Algorithm

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#334]
**Algorithm: [Rabin-Karp Algorithm](https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm)**

**Language Supported:**
- C++ [@YashThakare ]
- C
- Java [@parjanyaacoder]
- Python [@AdityaJ7]
- C#
- Javascript
- Golang

**Comment by parjanyaacoder** [comment]
@ricardoprins I would like to work on this issue in Java Language.

**Comment by atarax665** [comment]
@parjanyaacoder Here you go!

**Comment by parjanyaacoder** [comment]
Solved by pull request #340

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++.

**Comment by atarax665** [comment]
@YashThakare Get started! Please check your existing pull requests too, you need to do some changes before we can merge it.

**Comment by AdityaJ7** [comment]
I would like to work on this issue in python

**Comment by atarax665** [comment]
@AdityaJ7 Assigned! Get started.

**Comment by Nagasuruthika** [comment]
Hey, I would like to work on this issue In C also I'm a HakinCode Community Can I start contributing.

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Assigned! Get started.

Solved the python issue in  Pull Request #351

**Comment by Jyotika999** [comment]
Can i work in c or c++?

**Comment by kashika3101** [comment]
Please assign me this issue in C language

**Comment by obli99** [comment]
@atarax665 i would like to contribute in Javascript

**Comment by lipsamishra1609** [comment]
can i work in Golang?

**Comment by imPGupta** [comment]
@atarax665 I want to contribute to this issue either in **C** or **C++**
