### ISSUE TITLE
Linear Search in Kotlin

### ISSUE THREAD

**Issue by kiruba-r11** [HarshCasper/NeoAlgo#3350]
## 🚀 Feature

Linear Search is a searching algorithm that is performed by comparing each and every element of the array until the key is found. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
This algorithm is not present in the Kotlin directory, so it just motivated me to add one. 

## Pitch
It is used in various problems where Binary Search cannot be performed due to unsorted order of elements.

**Comment by kiruba-r11** [comment]
@bhav09 Please assign me this issue under GSSoC'21. Thanks

**Comment by kiruba-r11** [comment]
@HarshCasper Please assign this to me

**Comment by bhav09** [comment]
@kiruba-r11, you can assign an issue to yourself. Only if you could have read the instruction of the Github bot in this issue, you would have come to know. 
You can comment with /assign to self assign an issue.
