### ISSUE TITLE
A different approach for Quotient-Remainder Sorting algorithm in C++.

### ISSUE THREAD

**Issue by DEEPIKA-SUK** [HarshCasper/NeoAlgo#3358]
## 💥 Proposal

Elements of the array are sorted on the basis of their quotient and remainder obtained when divided by the size of the array( in C++).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by sakshi012000** [comment]
Can I work on python in this issue? I m a GSSoC  participant.

**Comment by sakshi012000** [comment]
Can I work on python in this issue? I am a GSSoC participant.

**Comment by DEEPIKA-SUK** [comment]
@HarshCasper @siddharth25pandey Kindly review my PR.
