### ISSUE TITLE
Linked List Algorithm Implementations

### ISSUE THREAD

**Issue by Abhijit2505** [HarshCasper/NeoAlgo#336]
**Algorithm:** Linked list Implementations

**DS:** Linked List

**Languages Supported:** CPP, Python

**Comment by Abhijit2505** [comment]
I would like to add all the implementations of Linked List algorithms in CPP and python.

**Comment by atarax665** [comment]
@Abhijit2505 It would be better if you create individual issues for different implementations.

**Comment by Abhijit2505** [comment]
Should I close this issue @atarax665 ?

**Comment by atarax665** [comment]
@Abhijit2505 Yeah.

**Comment by atarax665** [comment]
@Abhijit2505 Yeah, create a new issues. I will be assigning you the issues there.
