### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by Grace-Hephzibah** [HarshCasper/NeoAlgo#3375]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The Fibonacci Sequence

The Fibonacci sequence appears in nature all around us, in the arrangement of seeds in a sunflower and the spiral of a nautilus for example.

The Fibonacci sequence begins with  0 and 1 as its first and second terms. After these first two elements, each subsequent element is equal to the sum of the previous two elements.

## Pitch

This is one of the popular coding question.

**Comment by Grace-Hephzibah** [comment]
https://github.com/TesseractCoding/NeoAlgo/pull/3377

I have made the pull request. (Fibonacci series in C)

**Comment by Samiksha2809** [comment]
Hey, I'm a GSSOC'21 participant. I would like to add the code for Fibonacci series in Java. Please assign this issue to me.
Thankyou!!

**Comment by AdityaRaj-ar** [comment]
Hello, I am Aditya Raj, a Participant of GSSOC'21 and I am really in search of an issue in which I would contribute. I am completely a beginner but I will my best to contribute to this project as I am really enthusiast to learn how to contribute to projects. Therefore it's my humble request to please assign this issue to me. I would fulfil all the necessary requirements of this project. So please assign this issue to me. Thank You
