### ISSUE TITLE
Remove Duplicate words from String

### ISSUE THREAD

**Issue by RuchiGitHu** [HarshCasper/NeoAlgo#3389]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
This will remove the duplicate words from the String, for example:
Input : Ram went went to to to  school school.
Output : Ram went to school.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by RuchiGitHu** [comment]
Please /assign this issue to me using java language... 
Looking forward for reply.... @atarax665 , @HarshCasper

**Comment by Naman-12911** [comment]
I want to solve this issue please assign me under GSSOC.
I am recently solved #3130 issue. please assign this it to me

**Comment by NishikantaRay** [comment]
Please /assign this issue to me under GSSOC.

**Comment by atarax665** [comment]
@RuchiGitHu @Naman-12911 @NishikantaRay Please mention the language that you guys are willing to contribute in so that I can assign you the issue accordingly.

**Comment by NishikantaRay** [comment]
Java

**Comment by Naman-12911** [comment]
I will solve this issue with python.

**Comment by Manvi1411** [comment]
/assign 
I will solve this using cpp

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu @Naman-12911 @NishikantaRay Please mention the language that you guys are willing to contribute in so that I can assign you the issue accordingly.

@atarax665 , I want to solve this issue in java, as I mentioned same in my comment as well just by creating issue...
Thanks for assigning issue....
