### ISSUE TITLE
Artificial Intelligence Algorithms

### ISSUE THREAD

**Issue by siddharth25pandey** [HarshCasper/NeoAlgo#3392]
## 💥 Proposal

Add AI Algorithms for different Problem set
Example:
*Search Algorithm*: 
* Breadth-first Search (Uninformed Search)
* Depth-first Search (Uninformed Search)
* Depth-limited Search (Uninformed Search)
* Iterative deepening depth-first search (Uninformed Search)
* Uniform cost search (Uninformed Search)
* Bidirectional Search (Uninformed Search)
* Best-first Search Algorithm (Greedy Search) (Informed Search)
* A *star* Algorithm (Informed Search)
* Hill Climbing Algorithm (Local Search)
* Genetic Algorithm Implementation for 8 Queen Problem, Sudoku Solver

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by theSatvik** [comment]
@siddharth25pandey  I would like to work on artificial Intelligence Algorithms, can you please assign me this issue?

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey I would like to work on artificial Intelligence Algorithms, can you please assign me this issue?

@theSatvik Please mention the name of the Algorithm

**Comment by theSatvik** [comment]
@siddharth25pandey Yes Sir.

1. Breadth-first search (Uninformed Search)
2. Depth-first search (Uninformed Search)
3. Depth-limited search (Uninformed Search)
4. Iterative-deepening search (Uninformed Search)
5. Uniform-cost search (Uninformed Search)
 
We only have to write the algorithms with explanations right, @siddharth25pandey?

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey Yes Sir.
> 
> 1. Breadth-first search (Uninformed Search)
> 2. Depth-first search (Uninformed Search)
> 3. Depth-limited search (Uninformed Search)
> 4. Iterative-deepening search (Uninformed Search)
> 5. Uniform-cost search (Uninformed Search)
> 
> We only have to write the algorithms with explanations right, @siddharth25pandey?

@theSatvik You need to explain each one the Algorithm with an example Problem set.
Also, please mention your language, you are most comfortable in.

**Comment by theSatvik** [comment]
Okay, @siddharth25pandey please assign it to me.

**Comment by siddharth25pandey** [comment]
@theSatvik mention your language, you are most comfortable in.

**Comment by theSatvik** [comment]
Hi @siddharth25pandey, should I add all other algorithms as well?

**Comment by siddharth25pandey** [comment]
@theSatvik Yeah, you can work on the remaining Assigned Algo but meanwhile have a look on the changes requested in the previous created PR
