### ISSUE TITLE
Implementation of bit difference using c++

### ISSUE THREAD

**Issue by Debashish-hub** [HarshCasper/NeoAlgo#3413]
## 🚀 Feature

(A clear and concise description of what the feature is.)

Bit difference is a concept of  bit masking which I will be implementing using c++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

It would be great if I would be assigned with this issue @born-2learn 

Thank you

**Comment by jaimehta19** [comment]
I can do Sum of bit differences for numbers  0 to n in C++.
Kindly assign me this issue
