### ISSUE TITLE
Reverse Linked List

### ISSUE THREAD

**Issue by Abhijit2505** [HarshCasper/NeoAlgo#343]
**Algorithm:** Reversing A Linked List using Recursive and Iterative Approach

**DS:** Linked List

**Languages Supported:** 
* CPP [@Abhijit2505]
* Python [@Abhijit2505]
* C [@YashThakare]
* Python
* Javascript
* C# [@YashThakare]
* Golang

**Comment by Abhijit2505** [comment]
I would like to submit both the Python and CPP approach.

**Comment by atarax665** [comment]
@Abhijit2505 Assigned, get started!

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C++.

**Comment by atarax665** [comment]
@YashThakare Go ahead!

**Comment by atarax665** [comment]
@YashThakare Sorry, I have already assigned this issue to @Abhijit2505 in C++. You can still implement this in C though.

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C and C#

**Comment by Abhijit2505** [comment]
> @Abhijit2505 Assigned, get started!

I have added the CPP and Python approach and made a PR as well. Thank you.

**Comment by atarax665** [comment]
> > @Abhijit2505 Assigned, get started!
> 
> I have added the CPP and Python approach and made a PR as well. Thank you.

Great work.

**Comment by atarax665** [comment]
@YashThakare You can start working on this issue in C and C#.

**Comment by Kritika37** [comment]
I would like to work on this issue in Javascript.

**Comment by viveksahu26** [comment]
I would like to work on this issue on java.. so, please assign me..

**Comment by sonukushwaha403** [comment]
so, please assign me.. I would like to work on this issue on by python

**Comment by Himanshu44626748** [comment]
I would like to do this in C

**Comment by Vivek214-Candy** [comment]
I want contribute in javascript please assign to me
