### ISSUE TITLE
Linear Search Algorithm in Kotlin

### ISSUE THREAD

**Issue by nagasrihith608** [HarshCasper/NeoAlgo#3434]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
I would like to implement an algorithm that searches for a given number in a given list of numbers in linear time.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes
(Write your answer here.)

@HarshCasper, please assign this issue to me under GSSoC'21.

**Comment by anushkrishnav** [comment]
@nagasrihith608! kindly finish you existing issues before you open up a new one. Thank you

**Comment by nagasrihith608** [comment]
@anushkrishnav, sure actually there were other issues I opened and they didn't assign me. thank you
