### ISSUE TITLE
Optimal Binary Search Tree Problem using Java

### ISSUE THREAD

**Issue by Devansu-Yadav** [HarshCasper/NeoAlgo#3454]
## 🚀 Feature

(A clear and concise description of what the feature is.)

Given a sorted array keys[0.. n-1] of words to be searched and an array p[0.. n-1] of frequency counts, where p[i] is the number of searches to keys[i]. Also given an array q[0.. n-1] of frequency counts, where q[i] is the number of searches for word keys[i] misspelled by the user. Construct a Binary Search Tree of all words such that the total cost of all the searches(including the misspelled words) is as small as possible.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

Yes.
## Motivation

(Please outline the motivation for the proposal.)

This is an important problem that uses different concepts like Dynamic Programming, Binary Search Trees. Since there is no solution added to the project, I would like to add it for Java
## Pitch

(Please explain why this feature should be implemented and how it would be used.)

It is an important problem that can be asked in different programming tests hence a solution for it would be helpful for everyone to refer to.

**Comment by Devansu-Yadav** [comment]
@HarshCasper @ankitaggarwal23 It seems like this issue got closed by the bot since I had not closed the previous issues for which my PRs were merged. So can u pls open this issue again or probably look into it?

**Comment by anushkrishnav** [comment]
You should be able to close the older issues made by you if you have merged the PR. Cool I have reopened the Issue for you , great work remb to close your open issues before you make an issue next time

**Comment by Devansu-Yadav** [comment]
Yes, I closed the older issues. I will remember this before opening an issue next time👍
