### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by iamharshitpandeyy** [HarshCasper/NeoAlgo#3493]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by ankitaggarwal23** [comment]
@HarshitPandey251  Someone else is already working on C++ here #3436. Before you opened an issue. Closing this issue.
