### ISSUE TITLE
[ALGO/DS] Name : Data Structures Algorithms

### ISSUE THREAD

**Issue by howdyAnkit** [HarshCasper/NeoAlgo#350]
**Algorithm:**
- [x] HashMap 
- [x] Doubly Linked List
- [x] Queues
**DS:**

**Languages Supported:**
- [x] Javascript

**Comment by Jyotika999** [comment]
I want to work on Queues. Can I be assigned with this issue?

**Comment by iamrajiv** [comment]
@Jyotika999 Sure. I hope you have gone through, https://github.com/TesseractCoding/NeoAlgo#contributing-guidelines

**Comment by Jyotika999** [comment]
Yes Sir

**Comment by Jyotika999** [comment]
Can I work in C language?

**Comment by howdyAnkit** [comment]
@iamrajiv  Can you assign me for
 HashMap
 Doubly Linked List
 Queues In Javascript?

**Comment by iamrajiv** [comment]
> Can I work in C language?

@Jyotika999 Queue implementation is already been done in C.

**Comment by iamrajiv** [comment]
> @iamrajiv Can you assign me for
> HashMap
> Doubly Linked List
> Queues In Javascript?

@howdyAnkit  Queue implementation is already been done in JavaScript, you can work on the implementation of HashMap and Doubly Linked List in  JavaScript.

**Comment by howdyAnkit** [comment]
Can you assign me the same? @iamrajiv

**Comment by kashika3101** [comment]
Please assign me the doubly linked lists in C

**Comment by nutanaarohi123** [comment]
I want to take up this issue.
**Sorting Algorithm**
1. Insertion Sort
2.Selection Sort
3.Bubble Sort

Language Supported: **JAVA**

I have read all the contributing guidelines. Please assign this task.
