### ISSUE TITLE
Adding Bit-Manipulation algorithms to C++ C-plus-plus 

### ISSUE THREAD

**Issue by amandewatnitrr** [HarshCasper/NeoAlgo#3563]
## 💥 Proposal

Adding new algorithms to Bit_manipulation for C++ C-Plus-Plus

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
@amandewatnitrr Someone else is already assigned to similar issue #2559
