### ISSUE TITLE
Check whether a given graph is Bipartite or not in C++

### ISSUE THREAD

**Issue by jaimehta19** [HarshCasper/NeoAlgo#3566]
## 🚀 Feature

( Checking whether a given graph is Bipartite or not.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(A Bipartite Graph is a graph whose vertices can be divided into two independent sets, U and V such that every edge (u, v) either connects a vertex from U to V or a vertex from V to U..)

## Pitch

(MEDIUM LEVEL PROBLEM TO IMPLEMENT AND GOOD TO IMPROVE PROBLEM  SOLVING SKILLS .)

**Comment by anmol201212** [comment]
Please assign me this issue. I would do it in C++.

**Comment by anmol201212** [comment]
Please assign me this issue.  I would do it in C++.
/assign

**Comment by gargVader** [comment]
@anmol201212 #1510 duplicate
