### ISSUE TITLE
Find if string is K-Palindrome or not in C++ or JAVA

### ISSUE THREAD

**Issue by jaimehta19** [HarshCasper/NeoAlgo#3569]
## 💥 Proposal
Given a string, find out if the string is K-Palindrome or not. A k-palindrome string transforms into a palindrome on removing at most k characters from it.

Input : String - abcdecba, k = 1
Output : Yes

Input  : String - abcdeca, K = 2
Output : Yes

**Comment by simarjeet30** [comment]
Given a string, find out if the string is K-Palindrome or not. A k-palindrome string transforms into a palindrome on removing at most k characters from it.

Input : String - abcdecba, k = 1
Output : Yes

Input : String - abcdeca, K = 2
Output : Yes
I am a gssoc participant ,please assign this task to me

**Comment by jaimehta19** [comment]
@simarjeet30 please type /assign as a new comment .You will be assigned .
