### ISSUE TITLE
Priority Queues using Max Heap

### ISSUE THREAD

**Issue by Ayushisood** [HarshCasper/NeoAlgo#3605]
## 💥 Proposal

I want to add Priority Queues using Max Heap (using C++)in the NeoAlgo under GSSOC'21
Kindly assign this issue to me so I can also start contribution in NeoAlgo.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes , I have read the Contributing Guidelines and will follow the mentioned rules.

**Comment by Ayushisood** [comment]
@SKAUL05 Please check this issue once as i should have been assigned but the bot assigned it to someone else

**Comment by SKAUL05** [comment]
Assigned @Ayushisood

**Comment by jaimehta19** [comment]
@SKAUL05  Isn't it wrong to unassign someone ?? I spent my time on it 🤷

**Comment by SKAUL05** [comment]
Well issue was created by @Ayushisood and she commented assign first, so I assigned it to her. If any PR doesn't come from her it's up for reassigning.

@jaimehta1912  I definitely appreciate your time and efforts, and I'll request you to hold on this one as it's purely FCFS. As an alternative if you both can figure out a way to work on the same issue simultaneously with different flavours of one script that would be awesome.

**Comment by jaimehta19** [comment]
@SKAUL05  Yess , she was assigned first  and I have no problem in that  but because of her comment was edited , I got assigned .So technically I was  assigned first .
But anyways No problem 👍
