### ISSUE TITLE
Tower of Hanoi

### ISSUE THREAD

**Issue by anshmishra010** [HarshCasper/NeoAlgo#3623]
## 🚀 Feature

Tower of Hanoi is a mathematical puzzle where we have three rods and n disks.
The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules: 

1) Only one disk can be moved at a time.
2) Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
3) No disk may be placed on top of a smaller disk.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This is very famous question and whosoever practice CP knows about this question . 

## Pitch

I want to add the solution of this question using C++ language in your miscellaneous section in problems.
And I am GSSoC'21 participant so I want to contribute under it.

**Comment by rohanbabbar04** [comment]
@anshmishra010 
The problem is already there in the repository, do take up a different issue or do it in a different language. 
Also before putting up a new issue do search the previous issues from the option above.

**Comment by anshmishra010** [comment]
okay !
