### ISSUE TITLE
allcontributors  is not updating README

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#366]
## 🐛 Bug Report

allcontributors bot is not updating README file when it is called.
Related PR: #365

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by mar-galho** [comment]
I believe I have fixed it now 👍🏻

**Comment by mar-galho** [comment]
@iamrajiv can you check? We also need a link to the Contributors file in the README.md I guess

**Comment by iamrajiv** [comment]
@ricardoprins Yeah, it is fixed now
