### ISSUE TITLE
dark theme UI

### ISSUE THREAD

**Issue by mohammedjameel24** [HarshCasper/NeoAlgo#3675]
## 🚀 Feature

SWITCHABLE DARK THEME UI

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes
## Motivation
less eye strain for readers
(Please outline the motivation for the proposal.)

## Pitch
pure javascript implementation
(Please explain why this feature should be implemented and how it would be used.)

**Comment by ravjotsandhu** [comment]
@mohammedjameel24 are you working on it? If not I would like to take it up
