### ISSUE TITLE
Union of two unsorted array

### ISSUE THREAD

**Issue by Sapna2001** [HarshCasper/NeoAlgo#3715]
## 💥 Proposal

To find the union of two unsorted arrays under others section.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

I am a GSSOC '21 participant. Please assign me this issue with relevant labels and level categories.

**Comment by jaimehta19** [comment]
@Sapna2001 I am done with the code part but u closed ?

**Comment by Sapna2001** [comment]
@jaimehta1912 you are not supposed to self-assign issues you have not created. Check discord.

**Comment by jaimehta1912** [comment]
@Sapna2001 read the statement again what you said and what it means .And don't create issue if you are doing just for points  .First learn how to get assign yourself
