### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by mittal-pooja** [HarshCasper/NeoAlgo#3739]
## 🚀 Feature

A Binary Search Tree implemented in Golang, which contains  methods like Insertion, Searching along with a go_test file.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

I'm participating in gssoc21 and want to contribute to DSA implementation in Golang, as very few resources exists in the same.

## Pitch

This explains the basic working of a Binary Search Tree like adding a node and searching for a node . This could prove useful for all of the Go Developers out there who want to crack coding interviews for Golang.

**Comment by neha07kumari** [comment]
Hey!! I'm a GSSOC'21 participant . please assign me this issue .I would like to contribute it in C++ or C language. @bhav09

**Comment by neha07kumari** [comment]
Hey!! I'm a GSSOC'21 participant . please assign me this issue .I would like to contribute it in C++ or C language. @bhav09
