### ISSUE TITLE
Knuth–Morris–Pratt algorithm

### ISSUE THREAD

**Issue by anshulontech** [HarshCasper/NeoAlgo#376]
Algorithm :- <a href="https://en.wikipedia.org/wiki/Knuth–Morris–Pratt_algorithm">Knuth–Morris–Pratt algorithm</a>

**Language Supported**:

- Cpp [@anshul7sh]
- C
- Python [@YashThakare]
- Java
- JavaScript

**Comment by anshul7sh** [comment]
@atarax665   I would like to work on this issue using c++.

**Comment by anshulontech** [comment]
@HarshCasper , @atarax665 I would like to work on this issue using **C++**.

**Comment by vgb-codes** [comment]
@anshul7sh go ahead with C++

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java. Please assign. Thanks.

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in Python

**Comment by vgb-codes** [comment]
@YashThakare Go ahead with Python.

**Comment by ghost** [comment]
I would like to work on this issue in C.

**Comment by atarax665** [comment]
Closed by #1323
