### ISSUE TITLE
Add Queue using circular array

### ISSUE THREAD

**Issue by piyushgoell** [HarshCasper/NeoAlgo#377]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is a linear data structure which follows a particular order (First in First out) and used almost everywhere .

## Pitch

Queue is used to solve many real life problem. Some of its best applications are ticketing system. synchronization between slow and fast device and many more.

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C

**Comment by viveksahu26** [comment]
I wuould like to work on this issue in java.. kindly assign me..

**Comment by shankhanil007** [comment]
I would like to work on this issue in C++ as a part of Hackin Codes 2020
