### ISSUE TITLE
Multilevel inheritance in c++

### ISSUE THREAD

**Issue by PANKAJ3590** [HarshCasper/NeoAlgo#3773]
## 🚀 Feature

Multilevel inheritance

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

calculating the marks of four subjects, input student information , displaying them using different classes with the help of multilevel inheritance.

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

I will create a class which will take input of student information, another class which will take input of marks of 4 subjects, and by another class I will display this all using multilevel inheritance.

**Comment by anishsingh935** [comment]
can I contribute to this issues ??
I have understand the issue and can fix.
