### ISSUE TITLE
IMPLEMENTATION OF AVL TREE IN C

### ISSUE THREAD

**Issue by neha07kumari** [HarshCasper/NeoAlgo#3806]
### Feature
Solutions of AVL tree in C

### Have you read the Contributing Guidelines on Pull Requests?
Yes

### Motivation
I want to contribute to it under GSSoC'21.

### Pitch:
I would like to take up this task to implement it in C. @bhav09 

/assign

**Comment by codeakki** [comment]
Hello @neha07kumari  ### Im experienced In DSA and Algo please assign this issue to me i will complete this issue in c++

**Comment by codeakki** [comment]
### Added full working of AVL tree in c language
https://github.com/TesseractCoding/NeoAlgo/pull/3814#issue-597524164

**Comment by codeakki** [comment]
Added full implementation of AVL tree in c language #3814 
Mentors of programs are requested to review my code

**Comment by codeakki** [comment]
#4127     Added Implementation oF AVL Tree
