### ISSUE TITLE
Next Greater element (in C++)

### ISSUE THREAD

**Issue by divya-rai-42** [HarshCasper/NeoAlgo#3819]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read the Contributing Guidelines on pull request.

This algorithm will print the next greater element for all the indices in an array. For the index which has no greater element to the right , -1 shall be printed.
Sample input : 4 5 2 25
Sample output: 5 25 25 -1
I will solve this in O(n) time complexity.

**Comment by divya-rai-42** [comment]
@ankitaggarwal23 sir please open  this issue now. Both of my issues , that were raised earlier, have been completed. Please allow me to work on this issue.

**Comment by ankitaggarwal23** [comment]
Create a new one, as it is closed by bot we can't reopen otherwise it again closed
