### ISSUE TITLE
link is not edited properly.

### ISSUE THREAD

**Issue by RuchiGitHu** [HarshCasper/NeoAlgo#3845]
## 🐛 Bug Report

(A clear and concise description of what the bug is : Only one word has a link from sentence which is not looking good in README file.) I want to correct it, may I ?
![image](https://user-images.githubusercontent.com/71754179/111963027-10cb1d00-8ac1-11eb-9e47-bc5def47577e.png)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by RuchiGitHu** [comment]
> ## 🐛 Bug Report
> (A clear and concise description of what the bug is : Only one word has a link from sentence which is not looking good in README file.) I want to correct it, may I ?
> ![image](https://user-images.githubusercontent.com/71754179/111963027-10cb1d00-8ac1-11eb-9e47-bc5def47577e.png)
> 
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
> Yes

Please let me know if I can resolve it @HarshCasper @atarax665 
Thanks in advance..

**Comment by Jassi10000-zz** [comment]
@RuchiGitHu Actually all the contributors who  have contributed to these problems have not put the right url's of their newly added files , that's why the problem is occuring

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu Actually all the contributors who have contributed to these problems have not put the right url's of their newly added files , that's why the problem is occuring

It's fine @Jassi10000 , can I correct it? I have no issue if this bug solution will not count for GSSOC 21, just clarifying from my side.
I want to correct it because it's not looking good in readme, please allow me to proceed for same.

**Comment by pankaz20** [comment]
@RuchiGitHu use bot command given above for this to be assigned.

**Comment by Jassi10000-zz** [comment]
> > @RuchiGitHu Actually all the contributors who have contributed to these problems have not put the right url's of their newly added files , that's why the problem is occuring
> 
> It's fine @Jassi10000 , can I correct it? I have no issue if this bug solution will not count for GSSOC 21, just clarifying from my side.
> I want to correct it because it's not looking good in readme, please allow me to proceed for same.

@RuchiGitHu Am too a GSSOC'21 participant 
thus  you have to  self assign yourself

use   " /assign " and you are good to go , feel free to ask doubts

**Comment by RuchiGitHu** [comment]
> > > @RuchiGitHu Actually all the contributors who have contributed to these problems have not put the right url's of their newly added files , that's why the problem is occuring
> > 
> > 
> > It's fine @Jassi10000 , can I correct it? I have no issue if this bug solution will not count for GSSOC 21, just clarifying from my side.
> > I want to correct it because it's not looking good in readme, please allow me to proceed for same.
> 
> @RuchiGitHu Am too a GSSOC'21 participant
> thus you have to self assign yourself
> 
> use " /assign " and you are good to go , feel free to ask doubts

Thanks for your help...

**Comment by Jassi10000-zz** [comment]
@RuchiGitHu Just comment simply  , don't highlight any message
