### ISSUE TITLE
strings are anagrams or not 

### ISSUE THREAD

**Issue by aastha-io** [HarshCasper/NeoAlgo#3846]
program to check if two strings are anagrams or not, Please assign this to me.

**Comment by ANAMIKA1410** [comment]
from collections import Counter
 
# function to check if two strings are
# anagram or not
def check(s1, s2):
   
    # implementing counter function
    if(Counter(s1) == Counter(s2)):
        print("The strings are anagrams.")
    else:
        print("The strings aren't anagrams.")
