### ISSUE TITLE
Printing all paths of a binary tree that leads to a particular sum with any node as root

### ISSUE THREAD

**Issue by ujjawal-1999** [HarshCasper/NeoAlgo#385]
**Algorithm** - To print all the paths of a binary tree that leads to a given sum with any node taken as root.

**Languages Supported**

- C [@ujjawal-1999]

- C++ [@shankhanil007]

- Java

- Python [@pradeep98]

**Comment by ujjawal-1999** [comment]
I would like to contribute to this issue in C, C++. @VijayaGB98 please assign.

**Comment by pradeep98** [comment]
I'm up for this to implement in python. please assign the task. @VijayaGB98

**Comment by shankhanil007** [comment]
I would like to work on this issue in C++ as a part of Hackin Codes 2020

**Comment by vgb-codes** [comment]
@pradeep98 Go ahead with Python.
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
@ujjawal-1999 Go ahead with C. @shankhanil007 can proceed with C++.
Please follow the contribution guidelines when submitting your contribution.
