### ISSUE TITLE
shell sort

### ISSUE THREAD

**Issue by Ahana001** [HarshCasper/NeoAlgo#387]
Algorithm:  Shell sort

**Language Supported**

c#
c++
java
python

**Comment by Ahana001** [comment]
Can I work on this for JAVA, python,c# and c++?

**Comment by salonilakhotia** [comment]
I have PR the ShellSort in JAVA..Kindly review it

**Comment by Himanshu44626748** [comment]
I would like to do this in java

**Comment by aniketsingh98571** [comment]
I would like to do this in C++ as a part of HakinCodes 2020 Contributor's Hack

**Comment by rgrupesh** [comment]
Please, assign me this issue. I want to work in C

**Comment by aniketsingh98571** [comment]
> I would like to do this in C++ as a part of HakinCodes 2020 Contributor's Hack @Kajol-Kumari @Ahana001 @Abhijit2505 @HarshCasper

**Comment by yashaswibiyahut** [comment]
I would like to do this in C as a part of HakinCodes 2020 Contributor's Hack @Kajol-Kumari @Ahana001 @Abhijit2505 @HarshCasper

**Comment by narayan2111** [comment]
i would like to work on this issue in Python .
@plazzy99

**Comment by vatsalkesarwani12** [comment]
@Ahana001 - C#
@salonilakhotia  - JAVA
@aniketsingh98571  -cpp
@yashaswibiyahut  -c
@narayan2111 -python

Go ahead
Happy Coding!!

**Comment by aniketsingh98571** [comment]
@plazzy99 @Kajol-Kumari @atarax665
