### ISSUE TITLE
Create a mirror tree from the given binary tree

### ISSUE THREAD

**Issue by Ayushee11** [HarshCasper/NeoAlgo#3880]
To create a new binary tree which is a mirror image of the given binary tree.
Please assign this to me.
 **/assign**
@HarshCasper

**Comment by Jassi10000-zz** [comment]
@Ayushee11  Just comment  " /assign " and you are good to go

**Comment by HarshCasper** [comment]
@sanjitcodes Unassigned you and closing your PR. Don't take up someone else's Issue.
