### ISSUE TITLE
Removing duplicacy of characters from a word

### ISSUE THREAD

**Issue by AkanshaUniyal** [HarshCasper/NeoAlgo#3894]
## 💥 Proposal

Input: Mississippi
Output: Misp

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AkanshaUniyal** [comment]
@HarshCasper please assign me this under GSSOC'21. I would like to do this using Java.

**Comment by khusheekapoor** [comment]
Hello! I am a participant in GSSoC'21. I am really intrigued by this issue. Would be highly obliged if you could assign this to me. I can work on this using Java, Python, C and C++. Thank you!
