### ISSUE TITLE
Implement Depth First Search

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#39]
**Algorithm:** 

[Depth First Search](https://en.wikipedia.org/wiki/Depth-first_search)

**DS:** 

Graphs

**Languages Supported:**

- C [ Assigned to @kulsoomzahra ]
- C++ 
- Java [ Assigned to @rohitkumar-rk ]
- Javascript
- Python [ Assigned to @anushkrishnav ]

**Comment by anushkrishnav** [comment]
I can contribute for Python . Kindly assign it to me thank you

**Comment by kulsoomzahra** [comment]
@HarshCasper Can you assign this issue to me? for C

**Comment by HarshCasper** [comment]
I have assigned you the Issue @kulsoomzahra and @anushkrishnav 

You can start working on the same

**Comment by anushkrishnav** [comment]
[
> I have assigned you the Issue @kulsoomzahra and @anushkrishnav
> 
> You can start working on the same
]
Someone has already got it done ,But its not very optimal.- Python

**Comment by rohitkumar-rk** [comment]
I can contribute for Java.

**Comment by HarshCasper** [comment]
@anushkrishnav Can you please explain how you can optimize this further?

I have assigned you the Issue @rohitkumar-rk 

You can start working on this

**Comment by anushkrishnav** [comment]
> @anushkrishnav Can you please explain how you can optimize this further?
> 
> I have assigned you the Issue @rohitkumar-rk
> 
> You can start working on this

1There are too many unwanted functions .
2 No clear info for User on what values he/she needs to enter . 
3 defaultdict from collections module can be used
Issued a PR will be easy for you  to compare
Improved DFS #242 
Thanks for your time :) .

**Comment by rohitkumar-rk** [comment]
I used the same function break-up as In BFS (Already in your repo)  to make sure they are similar and Isn't it better to write modular code?
Also  Input is taken in similar way.
Can you please elaborate 3rd Point.

**Comment by atarax665** [comment]
@kulsoomzahra Are you working on this?

**Comment by anushkrishnav** [comment]
@atarax665 I have reassigned the issue to you . Good luck :)

**Comment by SangeetaMishra** [comment]
@HarshCasper I wish to work on this issue using C++. Can you assign it to me?
