### ISSUE TITLE
TOWER OF HANOI in C (GSSOC'21)

### ISSUE THREAD

**Issue by ananddasani** [HarshCasper/NeoAlgo#3902]
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes !

AIM :: **TOWER OF HANOI in C**

## Motivation

As i didn't found TOWER OF HANOI in C, So i am willing to contribute it...

## Pitch

Hi I am GSSoC'21 participant,
"I am looking to work on the TOWER OF HANOI in C"

I will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.
I will use C language.

**Comment by rohanbabbar04** [comment]
@ananddasani Tower of hanoi is already there in C do take up a different issue or do it in a different language
