### ISSUE TITLE
Tanspose and rortate matrix

### ISSUE THREAD

**Issue by prerna2712** [HarshCasper/NeoAlgo#3912]
## 💥 Proposal

Tranposing and rotating matrix are often required and these have some good tricks which are easy to use.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by prerna2712** [comment]
Can I work on this issue in C++?
Under GSSoC '21

**Comment by apoorva0107** [comment]
Can I work on this issue in Java under GSSoC'21?

**Comment by ishitakapoor26** [comment]
Can I work on this issue in C++ in GSSoC'21?

**Comment by Naman-12911** [comment]
can I work on this issue.
