### ISSUE TITLE
To find the kth prime factor of a given number

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#392]
## 🚀 Feature

( I have written a algorithm in c++. To find the kth prime factor of a given number. 
  for our Miscellaneous  problem section. I will upload it. )

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Pitch

(Given two numbers n and k,  Find the k-th prime factor among all prime factors of n.)

**Comment by sameersrivastava13** [comment]
I would like to work on this issue using C.

**Comment by Rishikeshrajrxl** [comment]
sorry bro but I am  already done with it in c++, and I think C and C++ are almost similar in this code, So try some other probelm
