### ISSUE TITLE
Checking for correct parenthesis order by using stack

### ISSUE THREAD

**Issue by SanketH17** [HarshCasper/NeoAlgo#3926]
By using a stack we can check whether the entered algebraic expression is correct or not by checking its parenthesis order.

/***********************************************************/
Example : 
Enter algebraic expression : [a(b+c)d]
 
Output: Balanced parenthesis
         Valid expression

/***********************************************************/

Enter algebraic expression : [(a+b)

Output: Not Balanced Parenthesis
         Left Parenthesis is more than the right parenthesis
         Invalid Expression
/************************************************************/
Enter algebraic expression : (a+b)]

Output: Not Balanced Parenthesis
         Left Parenthesis is more than the right parenthesis
         Invalid expression
/*************************************************************/

@hushee69 please this 
I want to add a solution to this problem into the NeoAlgo/C

**Comment by anishsingh935** [comment]
Hi can I use switch case instead of if ,else to work it fast !!

**Comment by anishsingh935** [comment]
Hi I have committed some changes please review
