### ISSUE TITLE
Floyd’s Cycle-Finding Algorithm

### ISSUE THREAD

**Issue by Ahana001** [HarshCasper/NeoAlgo#393]
## 💥 Proposal

Algorithm:  Floyd’s Cycle-Finding Algorithm

Language supported 
C
Java
Python 
C#
C++

**Comment by Ahana001** [comment]
Can i work on it?

**Comment by sonukushwaha403** [comment]
i would like to work with java

**Comment by infoarpit** [comment]
I will do this in C++.
Please assign me this task when contribution begin after 16th .

**Comment by infoarpit** [comment]
I will do this in Java.
Please assign me this task when contribution begin after 16th .

**Comment by Jkp2072** [comment]
i would like to work on it in c++

**Comment by shankhanil007** [comment]
I would like to work on it in C++ for Hackin Codes 2020

**Comment by muddhit** [comment]
i want to contribute it for java

**Comment by pragyajaiswa05l** [comment]
would like to contribute in c++ as a part of HakinCodes 2020

**Comment by viveksahu26** [comment]
I would like to work with this issue.. please assign me this issue..

**Comment by Ajay0511** [comment]
I would like to do it in Python.

**Comment by Ajay0511** [comment]
I would like to do it in Python.

**Comment by Rishikeshrajrxl** [comment]
I would like to do this in c++
