### ISSUE TITLE
How to check if a given number is even/odd without using Arithmetic operator? in CPP

### ISSUE THREAD

**Issue by vinc3nati** [HarshCasper/NeoAlgo#3979]
## 💥 Proposal

There are many ways to find if a number is even or odd in C++ but before moving into technical details on finding even and odd number in C++ let's what is even and odd number in terms of Mathematics. Any number which is completely divisible by 2 is called even number while number which is not completely divisible by 2 is called odd number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

So the way of finding even and an odd number without using arithmetic operator is by using the bitwise operator in C++. In binary format, the even number has there LSB always zero while the odd number has there LSB as 1 by using this information and bitwise & operator we can find if a number is even or odd in C++.  i.e. we use **bit manipulation**

GSSOC21 ISSUE.

**Comment by ishitakapoor26** [comment]
Can i work on this issue? (/assign)

**Comment by vinc3nati** [comment]
I am planning to work on it . You can say I have already worked on it just here to get confirmation from the admin.

**Comment by Naman-12911** [comment]
can I solve this issue please assign me. under GSSOC
