### ISSUE TITLE
Welcome to HakinCodes Contributor's Hack 2020

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#398]
Hello, Everyone ✨🙌

Thanks for showing your interest in being a part of the [Contributor's Hack](https://hakincodes.tech/) 💥

We are super delighted to have you on board for your Contributions on [NeoAlgo](https://github.com/TesseractCoding/NeoAlgo) 🙌

Here are the Mentors for the Project: 

| Name 📛  |      Social Media #️⃣ |  Github 🐱‍💻 |
|----------|:-------------:|------:|
| Kajol Kumari |  [LinkedIn](https://www.linkedin.com/in/kajol-kumari-73245b166/) | [Github](https://github.com/Kajol-Kumari) |
| Sarath Kaul |    [LinkedIn](https://www.linkedin.com/in/skaul05/) |   [Github](https://github.com/SKAUL05) |
| Rohan Rout | [LinkedIn](https://www.linkedin.com/in/routrohan/) |  [Github](https://github.com/routrohan) |
| Abhijit Tripathy | [LinkedIn](https://www.linkedin.com/in/abhijit-tripathy-415912187/) |  [Github](https://github.com/Abhijit2505) |
| Vatsal kesarwani | [LinkedIn](https://www.linkedin.com/in/vatsal-kesarwani-4a3858171/) |  [Github](https://github.com/plazzy99) |
| Siddharth Pandey | [LinkedIn](https://www.linkedin.com/in/siddharth25pandey/) |  [Github](https://github.com/siddharth25pandey) |

Here are some 12 Rules, you should be following while doing Open-Source to make your Contributions shine during the whole process:
- Be Nice, Be Respectful (BNBR)
- Check if the Issue you created, exists or not.
- Make proper commit messages and document your PR well.
- Always add Comments in your Code and explain it at points.
- Dynamic Input is always preferred over static Driver Code.
- Squash your commits before you push them.
- Always create a Pull Request from a Branch; Never from the Master.
- Follow proper Code conventions. Using i, j in Loops show a poor understanding of Code Quality. Use proper Variable, Function Names.
- Issues would be served on "First Come, First Serve" basis.
- Issues would be tagged as Easy, Medium, Hard. Scores would be assigned on the difficulty of Issue you solve.
- Code would be reviewed by Mentors before they are merged. Every PR requires 3 Reviews.
- No person can take up more than 2 Issues at a single point of time.

<b>Regards,</b>
<i>Harsh Mishra (@harshcasper), Project Administrator</i> 🤗

**Comment by sonukushwaha403** [comment]
assign this issue to me @HarshCasper  CH20
