### ISSUE TITLE
The Stock Span Problem in C++

### ISSUE THREAD

**Issue by sayantani11** [HarshCasper/NeoAlgo#3987]
## 💥 Proposal

Find the span of the stocks for all the days

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES, I read the guidelines and want to contribute as a GSSOC'21 participant

**Comment by codeakki** [comment]
#3814 Full implementation of AVL tree and Stock span problem p

**Comment by codeakki** [comment]
#4132
