### ISSUE TITLE
All basic functionality of Stack

### ISSUE THREAD

**Issue by siddharth25pandey** [HarshCasper/NeoAlgo#399]
### Description
Implement the basic functionality of stack such as **push, pop, peek** without using **Inbuilt Functions**.
Also show Empty & Full Functions for the stack.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Please make sure that you have gone through the Contributing Guidelines

## Motivation
Please have a clear & precise code for this issue.
Thanks!
Happy Coding !

**Comment by Alifbhanvadiya14** [comment]
I would like to solve in python

**Comment by Rishikeshrajrxl** [comment]
Please assign me this task. I will do in c++.

**Comment by Sohailsaifi** [comment]
I would like to do this in C.

**Comment by Yash-Thakare22** [comment]
I would like to do this in C++

**Comment by Yuvraj-kadale** [comment]
Would like to make it in C and python!!

**Comment by yashsahay25** [comment]
Kindly assign me this task. I will do it in C.

**Comment by yashaswibiyahut** [comment]
I would like to do this in c++.
Please assign me this task.

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java as a contribution to Hakin Codes. Pls assign.

**Comment by siddharth25pandey** [comment]
## NOTE
### Allotment of issues is based on **First Come First Serve basis**. Also, A participant can work at most **two** issues at a time.

**Comment by siddharth25pandey** [comment]
> I would like to solve in python

@Alifbhanvadiya14  Go ahead with Python.
 Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Please assign me this task. I will do in c++.

@Rishikeshrajrxl  Go ahead with C++
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to do this in C.

@Sohailsaifi  Go ahead with C
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to do this in C++

@YashThakare Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Would like to make it in C and python!!

@Yuvraj-kadale Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Kindly assign me this task. I will do it in C.

@yashsahay2014 Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to do this in c++.
> Please assign me this task.

@yashaswibiyahut Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in Java as a contribution to Hakin Codes. Pls assign.

@parjanyaacoder Go ahead with Java.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by ghost** [comment]
I would like to work on this in Golang.

**Comment by siddharth25pandey** [comment]
@odavhad  Assigned to work on Go Lang
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Kathan-Vakharia** [comment]
I would like to work in Golang or python or java(any one if it is available )on this issue.

**Comment by siddharth25pandey** [comment]
> I would like to work in Golang or python or java(any one if it is available )on this issue.

@Kathan-Vakharia  Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by pragyajaiswa05l** [comment]
would like to implement the all the basic functionality of stack using template so as to make it generic .
please assign this task to me would like to contribute as a part of HackinCodes2020

**Comment by siddharth25pandey** [comment]
> would like to implement the all the basic functionality of stack using template so as to make it generic .
> please assign this task to me would like to contribute as a part of HackinCodes2020

@pragyajaiswa05l Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by pulkitgovrani** [comment]
I would like to work on this in javascript

**Comment by ankitaggarwal23** [comment]
I would like to work on this issue in java.

**Comment by siddharth25pandey** [comment]
> I would like to work on this in javascript

 @pulkitgovrani Go ahead with Javascript
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in java.

@ankitaggarwal23 Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020
@Sreelakshmi00 
Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

@Sreelakshmi00 Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by akshitasinghal4444** [comment]
I would like to work on this issue in C.

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in C.

Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by Rishikeshrajrxl** [comment]
> > Please assign me this task. I will do in c++.
> 
> @Rishikeshrajrxl Go ahead with C++
> Also, make sure that you have gone through the Contributions Guideline thoroughly.
> All the Best!
> Happy Coding !

@siddharth25pandey  I should do this using array Data structure , right?

**Comment by siddharth25pandey** [comment]
> > > Please assign me this task. I will do in c++.
> > 
> > 
> > @Rishikeshrajrxl Go ahead with C++
> > Also, make sure that you have gone through the Contributions Guideline thoroughly.
> > All the Best!
> > Happy Coding !
> 
> @siddharth25pandey I should do this using array Data structure , right?

@Rishikeshrajrxl it's your choice, you can use any (Array / Linked list ) in which you are Comfortable.

**Comment by riya-joshi-401** [comment]
i would like to work upon this in c please assign me

**Comment by siddharth25pandey** [comment]
> i would like to work upon this in c please assign me

@riya-joshi-401 Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
## At present all the allocation work has been done for this issue.

**Comment by pulkitgovrani** [comment]
@siddharth25pandey sir i have implemented stack in javascript. Can you please review it and provide the feedback.
My PR number is  #777

**Comment by samriddhisv** [comment]
Hey, I'd love to contribute to this using C
