### ISSUE TITLE
Implement Breadth First Search

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#40]
**Algorithm:** 

[Breadth First Search](https://en.wikipedia.org/wiki/Breadth-first_search)

**DS:** 

Graphs

**Languages Supported:**

- C [ Assigned to @kulsoomzahra ]
- C++ [ Assigned to @harsh-9in ]
- Java [ Assigned to @Himanshu70565 ]
- Javascript
- Python [ Assigned to @sparkingdark ]

**Comment by sparkingdark** [comment]
want to work in c and python. @HarshCasper

**Comment by harsh7in** [comment]
@HarshCasper Can I work on it using c++

**Comment by harsh-9in** [comment]
Can I work on this using c++? @HarshCasper

**Comment by Himanshu70565** [comment]
@HarshCasper  Can I work for implementation in java ?

**Comment by kulsoomzahra** [comment]
@HarshCasper Can i work on this in C?

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You all can start working on them

**Comment by riya-joshi-401** [comment]
i would like to work upon this in using c please assign me ( as a part of Hakin Codes 2020 )

**Comment by obli99** [comment]
@HarshCasper i could like to contribute in javascript

**Comment by kulsoomzahra** [comment]
@HarshCasper sorry for the delay I'll complete my part very soon!
