### ISSUE TITLE
All basic functionalities of Singly Linked List

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#400]
### Singly Linked List (SLL) must contains all these features:**
 * Add a node at the front of SLL.
* Insertion, Deletion of a node at the beginning, at the end & at a given position.
* Count of total Number of nodes present
* Traversing the SLL
* Printing the data present in the node.
* Having empty & full functions checkers

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Please make sure that you have read the Contributing Guideline

Thanks!

### Happy Coding !

**Languages Supported:**
- C : @Sohailsaifi 
- CPP : @Rishikeshrajrxl 
- Python : @SangeetaMishra 
- Java : @parjanyaacoder 
- C# : 
- JavaScript : 
- GO : @GajjarMiten

**Comment by Rishikeshrajrxl** [comment]
I will do this in C++. 
Please assign me this task when contribution begin after 16th .

**Comment by siddharth25pandey** [comment]
@Rishikeshrajrxl , I will assign you after the Contest will start.

**Comment by Sohailsaifi** [comment]
I will do this in C.

**Comment by Yash-Thakare22** [comment]
I would like to do this in C++

**Comment by Rishikeshrajrxl** [comment]
> @Rishikeshrajrxl , I will assign you after the Contest will start.

Ok

**Comment by Himanshu44626748** [comment]
I would like to do this in C

**Comment by yashaswibiyahut** [comment]
Would love to do this in c++.

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java as a contribution to Hakin Codes. Thank You.

**Comment by siddharth25pandey** [comment]
> I will do this in C++.
> Please assign me this task when contribution begin after 16th .

@Rishikeshrajrxl  Go ahead with C++
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
## NOTE
### Allotment of issues is based on **First Come First Serve basis**. Also, A participant can work at most **two** issues at a time.

**Comment by siddharth25pandey** [comment]
> I will do this in C++.
> Please assign me this task when contribution begin after 16th .

@Rishikeshrajrxl Go ahead with C++.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I will do this in C.

@Sohailsaifi Go ahead with C.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to do this in C++

@YashThakare Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to do this in C

@Himanshu44626748 Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Would love to do this in c++.

@yashaswibiyahut  Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue in Java as a contribution to Hakin Codes. Thank You.

@parjanyaacoder Go ahead with Java.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by SangeetaMishra** [comment]
I would like to work on this in python

**Comment by GajjarMiten** [comment]
I would like to work on this in Golang.

**Comment by siddharth25pandey** [comment]
> I would like to work on this in python

@SangeetaMishra Go ahead with Python.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this in Golang.

@GajjarMiten  Assigned to work on Go Lang.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by parjanyaacoder** [comment]
Solved this issue in Java by #428 . Please review

**Comment by SangeetaMishra** [comment]
> > I would like to work on this in python
> 
> @SangeetaMishra Go ahead with Python.
> Also, make sure that you have gone through the Contributions Guideline thoroughly.
> All the Best!
> Happy Coding !

Solved it in Python #435

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by riya-joshi-401** [comment]
I would love to contribute this in C .!!!!!!!

**Comment by Adityanagraj** [comment]
I would like to work on this issue in Python as part of HaikinCodes Contributor's Hack 2020

**Comment by siddharth25pandey** [comment]
## At present all the allocation work has been done for this issue.

**Comment by samriddhisv** [comment]
I would love to work on this in C
