### ISSUE TITLE
Level order traversal of tree.

### ISSUE THREAD

**Issue by Jkp2072** [HarshCasper/NeoAlgo#401]
## 💥 Proposal

To implement level order traversal of  a tree.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

i would like to implement it in c++ for hackinCodes2020
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by Jkp2072** [comment]
i would like to do it in c++

**Comment by Lakhan-Nad** [comment]
I would like to do it in Java

**Comment by shankhanil007** [comment]
I would like to work on this issue in C++ as a part of Hackin Codes 2020

**Comment by pragyajaiswa05l** [comment]
would like to make a contribution in c++

**Comment by peeky1811** [comment]
I would love to code it in Cpp/C.

**Comment by Kajol-Kumari** [comment]
@shankhanil007 @pragyajaiswa05l  c++ is already taken up. 
@peeky1811 please go with C

**Comment by Lakhan-Nad** [comment]
@Kajol-Kumari  I just saw that level Order Traversal is already implemented in Java in master branch so I am unassigning myself.
