### ISSUE TITLE
Distance between two nodes in a tree

### ISSUE THREAD

**Issue by piyushgoell** [HarshCasper/NeoAlgo#402]
### Have you read the [Contributing Guidelines on Pull Requests]
Yes

(Write your answer here.)

## Motivation

There are lot of real problems where we need to find distance between two given points or nodes.

## Pitch

Time Complexity should be O(N).

**Comment by anubhvshrma18** [comment]
I would like to take this issue in C.

**Comment by pradeep98** [comment]
I would like to take this issue in PYTHON. @piyushgoell

**Comment by shankhanil007** [comment]
I would like to solve this issue in C++ as a part of Hackin Codes 2020

**Comment by pragyajaiswa05l** [comment]
Would like to make a contribution in c++ for HackinCodes2020.

**Comment by nutanaarohi123** [comment]
I would like to take this issue in JAVA  as a part of Hackin Codes 2020.
