### ISSUE TITLE
Convert a Binary Tree into Doubly Linked List

### ISSUE THREAD

**Issue by piyushgoell** [HarshCasper/NeoAlgo#403]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

As every node in a **Binary Tree** has two pointer one points to left and other another points to right. Aldo in **Doubly Linked List** we have two pointers next and previous.
![Untitled](https://user-images.githubusercontent.com/34750712/90267954-e7d01300-de73-11ea-9442-3cc4ff1e78f2.png)

**Comment by anubhvshrma18** [comment]
I would like to take this issue in C .

**Comment by ghost** [comment]
I want to work on this issue in Golang

**Comment by shankhanil007** [comment]
I would like to work on this issue in C++ as a part of Hackin Codes 2020

**Comment by viveksahu26** [comment]
I would like to work on this issue in java.. please assign me this issue..
