### ISSUE TITLE
Three Sum

### ISSUE THREAD

**Issue by anshmishra010** [HarshCasper/NeoAlgo#4054]
## 🚀 Feature
We have to find the sum of the target value using using three digit present in the list.
I'll provide the optimized solution using two pointer technique.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is a famous question which asked during interview.

## Pitch

I would like to add this code .
I am a GSSoC'21 participant so i want to contribute under it.

**Comment by anshmishra010** [comment]
Please check , I have made the changes.

**Comment by HarshCasper** [comment]
@anshmishra010 Kindly link the PR here
