### ISSUE TITLE
Finding number of digits in an integer

### ISSUE THREAD

**Issue by imPGupta** [HarshCasper/NeoAlgo#406]
**Algorithm: [Find number of digits in an integer](https://www.geeksforgeeks.org/program-count-digits-integer-3-different-methods/)**

**Language Supported**
- C [@Sohailsaifi]
- CPP [@sukritidawar]
- Python [@Sapna2001]
- Java  [@infoarpit]
- C# [@imPGupta]
- JavaScript [@gupta-piyush19]
- GO

**Comment by imPGupta** [comment]
I want to contribute on this. Can you assign me?

**Comment by atarax665** [comment]
@imPGupta You need to specify that in which language you wanna work on this issue.

**Comment by infoarpit** [comment]
i would like to work it in java please assign it to me
(java)

**Comment by sukritidawar** [comment]
I want to work on this issue in C++

**Comment by Sapna2001** [comment]
I want to work on this issue in python

**Comment by Sohailsaifi** [comment]
I want to work on this issue in c.

**Comment by gupta-piyush19** [comment]
i want to work on this issue. i can work in JavaScript, C++ and C .

**Comment by imPGupta** [comment]
@atarax665  I want to work on this issue in C, CPP and Python.

**Comment by VijayaGB98** [comment]
@infoarpit Go ahead with Java.
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
I apologize for accidentally closing the issue. Please hold on.

**Comment by vgb-codes** [comment]
@sukritidawar Go ahead with C++.
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
@Sapna2001 Go ahead with Python
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
@Sohailsaifi Go ahead with C.
Please follow the contribution guidelines when submitting your contribution.

**Comment by imPGupta** [comment]
@VijayaGB98 sir, Please assign me this task. I want to contribute this issue in C, CPP and Python. I have created this issue,

**Comment by vgb-codes** [comment]
@gupta-piyush19 Go ahead with Javascript.
Please follow the contribution guidelines when submitting your contribution.

**Comment by vgb-codes** [comment]
@imPGupta C, C++ and Python issues have been taken. Issues are assigned on a first-come first-serve basis. If you would like to work on the issue in Go or C#. I can assign it to you.

**Comment by imPGupta** [comment]
@VijayaGB98  ok sir. But I have commented first on this issue.

> I want to contribute on this. Can you assign me?

**Comment by vgb-codes** [comment]
@imPGupta Which language do you want to contribute in. As of now I can assign you either C# or Go.

**Comment by imPGupta** [comment]
@VijayaGB98 I can do this with C#

**Comment by vgb-codes** [comment]
@imPGupta Go ahead with C#.
Please follow the contribution guidelines when submitting your contribution.

**Comment by Himanshu44626748** [comment]
I would like to do this in java. Please assign me.

**Comment by vgb-codes** [comment]
@Himanshu44626748 Please check if the issue for a particular language has been already taken by someone else. As Java is already assigned, I cannot assign it to you. I can however assign you to contribute using Go.

**Comment by Himanshu44626748** [comment]
> @Himanshu44626748 Please check if the issue for a particular language has been already taken by someone else. As Java is already assigned, I cannot assign it to you. I can however assign you to contribute using Go.

I'm not comfortable in Go.

**Comment by vgb-codes** [comment]
@Himanshu44626748 Then you are free to find another issue where I or someone else can assign you the issue in the languages that you are comfortable with.
