### ISSUE TITLE
Largest Rectangle in a Histogram C++

### ISSUE THREAD

**Issue by sayantani11** [HarshCasper/NeoAlgo#4062]
## 💥 Proposal

A Histogram is a kind of Bar graph.
Given an array. Each element represents the height to the histogram's bar and the width of each bar is 1. To find the area of the largest rectangle in the histogram.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, and I want to contribute to it as a GSSOC'21 participant.

**Comment by ankan1811** [comment]
@sayantani11 the problem is already present under stack section of C++.Please check before picking up a question. Thanks .
