### ISSUE TITLE
Readme for Java folder

### ISSUE THREAD

**Issue by Sapna2001** [HarshCasper/NeoAlgo#407]
## 📚 Documentation

Adding content into Readme file in Java folder

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

Please assign me this issue.

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by Sapna2001** [comment]
Please assign me this issue.
