### ISSUE TITLE
find the cycle in a undirected graph using disjoint sets

### ISSUE THREAD

**Issue by AltCtrlDel1999** [HarshCasper/NeoAlgo#409]
## 🚀 Feature

Algorithm to detect a cycle in undirected graph by using disjoint sets

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

(Write your answer here.)

## Motivation

To understand concepts of disjoint sets

**Comment by AltCtrlDel1999** [comment]
I want to contribute to this issue in java

**Comment by kushagraiitbbs** [comment]
I want to contribute this issue in C++.
