### ISSUE TITLE
Generating all subsequences of a given string

### ISSUE THREAD

**Issue by ujjawal-1999** [HarshCasper/NeoAlgo#410]
Generating all subsequences using bit masking.
Languages -

> C [@ujjawal-1999]

> C++ [@ujjawal-1999]

> Java [@anime19]

> Python [@neha07kumari]

**Comment by ujjawal-1999** [comment]
I'll work on the C and C++ implementation. @VijayaGB98 please assign the task.

**Comment by vgb-codes** [comment]
@ujjawal-1999 Go ahead. I will assign C and C++. 
Make sure to follow contribution guidelines.

**Comment by anime19** [comment]
I would like to work in this issue in java please assign it to me.

**Comment by vgb-codes** [comment]
@anime19 Go ahead with Java.
Please following the contribution guidelines when submitting your contribution.

**Comment by neha07kumari** [comment]
I would like to work on this issue using python language

**Comment by vgb-codes** [comment]
@neha07kumari Go ahead with Python.
Please following the contribution guidelines when submitting your contribution.

**Comment by peeky1811** [comment]
I would like to contribute to this in Python.

**Comment by vgb-codes** [comment]
@peeky1811 Please check the first post to see whether the issue has been taken in the language that you are currently requesting for. Since it has been taken by someone else, I cannot assign you this issue in Python.

**Comment by peeky1811** [comment]
> @peeky1811 Please check the first post to see whether the issue has been taken in the language that you are currently requesting for. Since it has been taken by someone else, I cannot assign you this issue in Python.

It's ok. 👍
