### ISSUE TITLE
Adding SleepSort Algorithm in JavaScript

### ISSUE THREAD

**Issue by gupta-piyush19** [HarshCasper/NeoAlgo#411]
## 🚀 Feature

I would like sleep sort algorithm/technique in [JavaScript Sort](https://github.com/TesseractCoding/NeoAlgo/tree/master/JavaScript/sort) Section

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
I would like to spread my knowledge regarding this unique sorting technique, can i work on this issue?
## Pitch
SleepSort algorithm in javascript is a Unique way of sorting an array, which most of the javaScript users doesn't know.
Sleepsort is an algorithm which works on basic timeout function but can sort an array easily. I will write a clean, self-explanatory code of this algorithm.

**Comment by Himanshu44626748** [comment]
I would like to do this in java

**Comment by SKAUL05** [comment]
@gupta-piyush19 Go ahead with implementation in Javascript. 
Do remember to mention constraints in your algo like `negative numbers`
