### ISSUE TITLE
Implementation of Queue using Stacks & Vice-versa

### ISSUE THREAD

**Issue by siddharth25pandey** [HarshCasper/NeoAlgo#412]
## 🚀 Description
You have to create **Queue using Stacks** & vice-versa i.e. **Creation of Stack using Queues**.
Make sure you have to build these Programs Individually in a **single executable file**. without using **Inbuilt Functions**.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Please make sure that you have read the Contributing Guideline
Thanks!

**Comment by Himanshu44626748** [comment]
I would like to do this in java. Please assign me.

**Comment by ag278** [comment]
I would like to work on this issue. Please assign me this issue.
I have read all the guidelines and I want to do this in c++

**Comment by sonukushwaha403** [comment]
I would like to work with python , please assign it to me

**Comment by siddharth25pandey** [comment]
> I would like to do this in java. Please assign me.

 @Himanshu44626748  Go ahead with java.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work on this issue. Please assign me this issue.
> I have read all the guidelines and I want to do this in c++

@ag278 Go ahead with C++.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by kritikaparmar-programmer** [comment]
Hii , I would like to work with C , please assign it to me

**Comment by siddharth25pandey** [comment]
> I would like to work with python , please assign it to me

 @sonukushwaha403  Go ahead with Python.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Hii , I would like to work with C , please assign it to me

@kritikaparmar-programmer Go ahead with C.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
## NOTE
### Allotment of issues is based on **First Come First Serve basis**. Also, A participant can work at most **two** issues at a time.

**Comment by infoarpit** [comment]
I would like to do this in java please assign it to me

**Comment by GajjarMiten** [comment]
Hey, @siddharth25pandey I would like to do it with Golang.

**Comment by siddharth25pandey** [comment]
> I would like to do this in java please assign it to me

@infoarpit Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by siddharth25pandey** [comment]
> Hey, @siddharth25pandey I would like to do it with Golang.

@GajjarMiten  Assigned to work on Go Lang
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !
