### ISSUE TITLE
Scramble String Problem Dynamic Programming in c++

### ISSUE THREAD

**Issue by ManuGupta9780** [HarshCasper/NeoAlgo#4131]
## 💥 Proposal

If a string S is given, we can represent it as a binary tree by partitioning it into two non-empty substrings recursively. Then in order to scramble the string, we may choose any non-leaf node and swap its two children. We can perform this operation any number of times. The objective of this problem is, when two strings A and B of the same length are given, determine if B is a scrambled string of A.

The solution of this problem will be implemented using Dynamic Programming in C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by kotwani2883** [comment]
I have already opened a issue for the same and created a pull req too. Here you go -https://github.com/TesseractCoding/NeoAlgo/pull/4145.  It would be better to close the issue otherwise there would be conflicts.
Thanks.
