### ISSUE TITLE
Print the occurrence of the given number in the list/array using Binary Search Technique

### ISSUE THREAD

**Issue by vatsalkesarwani12** [HarshCasper/NeoAlgo#414]
#### Input 
- Size of the array/list 
- Elements in the array/list 
- A number whose occurrence is to be printed 

#### Program should do 
- Find the occurrence of the given number using the above technique

#### Sample Test Case
**Input**
5
1 4 2 3 4
4

**Output**
Occurrence of '4'  : 2

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Please make sure that you have read the Contributing Guideline

Thanks!

**Happy Coding !**

Programming Languages For Implementations:
* CPP - @narayan2111
* Python - @Kathan-Vakharia
* C - @Surajv311 
* GO
* Java - @sonukushwaha403

**Comment by narayan2111** [comment]
I would like to work on this issue using c++. Please assign this to me.

**Comment by narayan2111** [comment]
I also would like to work on this issue using Python. Please assign this to me.

**Comment by Kathan-Vakharia** [comment]
I would like to work on this issue with python or java or golang or js (any one of these if it is available )

**Comment by sonukushwaha403** [comment]
I would like to work in java

**Comment by Abhijit2505** [comment]
@narayan2111 Go ahead with C++.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Abhijit2505** [comment]
@Kathan-Vakharia Go ahead with Python.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Abhijit2505** [comment]
@sonukushwaha403 Go ahead with Java. This one is your second assigned issue of this week. Hope you are enjoying the program as well. Do share your experience with us in communication channels 😊
All the Best!
Happy Coding !

**Comment by Surajv311** [comment]
I would like to work in C. Could you please assign it to me ?

**Comment by Abhijit2505** [comment]
@Surajv311 Go ahead with C.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by vatsalkesarwani12** [comment]
@Sreelakshmi00 your friend already assigned it before 

Try assigning another issue

**Comment by avishmehta68710** [comment]
i would like to work on this issue in python
can you please assign ???

**Comment by vatsalkesarwani12** [comment]
@avishmehta68710 python has been already assigned to someone.

Find another issue and assign it to yourself
