### ISSUE TITLE
Traversals in Binary Tree

### ISSUE THREAD

**Issue by Abhijit2505** [HarshCasper/NeoAlgo#415]
## 🚀 Problem Statement

Used Data Structure - **Binary Tree**

A binary tree can be traversed in the following ways,

* Preorder Traversal
* Postorder Traversal
* Inorder Traversal

## Motivation

Traversal techniques use two more classical Algorithmic Design Approach namely **recursion** & **iteration over loop**. 

## Available Programming Languages:
* Preorder Traversal
    
   -  C++ - @AkM-2018
   - Python - @pradeep98
   - C - @rohangawhade
   - Java - @Harshak50
   - GO

* Postorder Traversal
    
   -  C++ - @Kritika37
   - Python - @AdityaJ7
   - C - @PREETIKATANEJA
   - Java - @nlok5923
   - GO

* Inorder Traversal
    
   -  C++ - @bagladivyang03 
   - Python - @rutujadhanawade
   - C - @cherryWood55
   - Java - @SangeetaMishra 
   - GO - @Kathan-Vakharia

## Method To Take on the issue
Do mention your interest to take on the issue in the format ``<Traversal Name> - <programming language>``
For example - **preorder Traversal** - **python**
Please choose any one traversal and one programming language only.

**Comment by pradeep98** [comment]
I'm on for PYTHON. @Abhijit2505 please assign the task.

**Comment by Abhijit2505** [comment]
@pradeep98, I would like you to read the complete issue again, and the section **Method To Take On the Issue** properly.

**Comment by pradeep98** [comment]
preorder Traversal - python
inorder Traversal - python
postorder Traversal - python
@Abhijit2505

**Comment by Abhijit2505** [comment]
@pradeep98 choose any one. Should I assign the first one i.e. **preorder Traversal**

**Comment by pradeep98** [comment]
Yeah I'm fine with it.
preorder Traversal - python

**Comment by Abhijit2505** [comment]
@pradeep98 get stared with **preorder Traversal - python**.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Harshak50** [comment]
Preorder Traversal - java
I would like to work on this.

**Comment by AkM-2018** [comment]
Preorder traversal - C++
I would like to work on this.

**Comment by bagladivyang03** [comment]
Inorder traversal - c++
I would like to work on this

**Comment by Kathan-Vakharia** [comment]
Inorder traversal - Golang or C or python (anyone of these in order if available)

**Comment by Abhijit2505** [comment]
@AkM-2018  get stared with **Preorder Traversal - C++**.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by Abhijit2505** [comment]
@bagladivyang03 get stared with **Inorder Traversal - C++**.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding!

**Comment by Abhijit2505** [comment]
@Kathan-Vakharia , this is the second issue assigned to you, Do get started with **Inorder Traversal - GOLANG**. Hope you are enjoying the program as well. Do share your experience with us in the communication channels.
All the very best.
Happy Coding.

**Comment by AdityaJ7** [comment]
I would like to work on post order traversal in python

**Comment by Abhijit2505** [comment]
@Harshak50 get stared with **Preorder Traversal - Java**.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by Abhijit2505** [comment]
@AdityaJ7  get stared with **Postorder Traversal - Python**.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by Kritika37** [comment]
I would like to work on this issue in C++ Postorder traversal

**Comment by nlok5923** [comment]
@Abhijit2505 I would like to work on postorder and in order traversal using java. Please assign it to me.

**Comment by cherryWood55** [comment]
Inorder traversal - C
I would like to work on this issue.

**Comment by Abhijit2505** [comment]
@Kritika37 get stared with **Postorder Traversal - C++**.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by Abhijit2505** [comment]
> @Abhijit2505 I would like to work on postorder and in order traversal using java. Please assign it to me.

@nlok5923 I would like to assign you **postorder traversal -Java** only. We don't accept two assignments in the same issue.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by nlok5923** [comment]
@Abhijit2505  please do let me work on post order traversal in java.please assign it to me.i had read contributing guidelines

**Comment by Abhijit2505** [comment]
> @Abhijit2505 please do let me work on post order traversal in java.please assign it to me.i had read contributing guidelines

Get into the action, you have been assigned the same in the above reply only.

**Comment by SangeetaMishra** [comment]
I want to work on postorder traversal in C++

**Comment by Abhijit2505** [comment]
@cherryWood55 get stared with **Inorder Traversal - C**.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by SangeetaMishra** [comment]
I would like to work on inorder traversal in java

**Comment by Abhijit2505** [comment]
> I want to work on postorder traversal in python

This has already been assigned to someone else. I would like you to take some time and see which slots are available and then comment. That will help me to distribute the task as well.

**Comment by Abhijit2505** [comment]
@SangeetaMishra get stared with Inorder Traversal - Java.
Also, make sure that you have gone through the Contributions Guidelines thoroughly.
All the Best!
Happy Coding!

**Comment by rutujadhanawade** [comment]
I would like to work on this issue.

Inorder traversal -> Python

**Comment by rohangawhade** [comment]
I would like to work on 
preorder traversal -> C

**Comment by PREETIKATANEJA** [comment]
I would like to work on post-order traversal in C language @Abhijit2505

**Comment by Kajol-Kumari** [comment]
Hey people! So as github allows only 10 assignees per issue so i have unassigned everyone as we can't keep some assigned and others don't, please look in the issue description to see who are assigned for what language. 

Happy Learning :)

**Comment by Abhijit2505** [comment]
@rutujadhanawade, @rohangawhade and @PREETIKATANEJA , you three have been assigned your respective tasks by @Kajol-Kumari . Do have a look at the first issue comment of this thread where the tasks have been assigned and get started.
All the very best.
Happy coding.

**Comment by AdityaJ7** [comment]
@rutujadhanawade  you were assigned In-order traversal. Post-order was assigned to me by @Abhijit2505

**Comment by rutujadhanawade** [comment]
> @rutujadhanawade you were assigned In-order traversal. Post-order was assigned to me by @Abhijit2505

I am sorry about it.. 
Dont worry, I will close my previous PR and I will again make a PR of Inorder traversal. @AdityaJ7

**Comment by bagladivyang03** [comment]
I have already done inorder in c++

**Comment by bagladivyang03** [comment]
It was assigned to me by @Abhijit2505

**Comment by rutujadhanawade** [comment]
> I have already done inorder in c++

I am doing it in Python.

**Comment by bagladivyang03** [comment]
> > I have already done inorder in c++
> 
> I am doing it in Python.

Oh ohk 👍
