### ISSUE TITLE
z-algorithm

### ISSUE THREAD

**Issue by pragyajaiswa05l** [HarshCasper/NeoAlgo#417]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation
Linear time pattern searching Algorithm.
(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This algorithm finds all occurrences of a pattern in a text in linear time.

## Assignees

- C-Plus-Plus: @SangeetaMishra
- C: @SangeetaMishra
- Go:
- Java: @ritvij14
- JavaScript: @ritvij14
- Python: @SayaniG371

**Comment by pragyajaiswa05l** [comment]
would like to implement in c++ as a part of HakinCodes2020
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by ghost** [comment]
Would Like to implement in Python as a part of HakinCodes2020

**Comment by HarshCasper** [comment]
I have assigned the Issue in Python to @SayaniG371 and in C++ to @pragyajaiswa05l

**Comment by ankitaggarwal23** [comment]
I would like to work on this issue in C and java both.

**Comment by vatsalkesarwani12** [comment]
@ankitaggarwal23 you have  been assigned with one issue before so I can assign you with one of the above two mentions

Go with C

**Comment by ankitaggarwal23** [comment]
@plazzy99 Bro I don't know Go so you can I assign me in C

**Comment by ankitaggarwal23** [comment]
@plazzy99 May be someone else familier with Go can Do with Go.

**Comment by vatsalkesarwani12** [comment]
@ankitaggarwal23  I assigned you with language: C

**Comment by SangeetaMishra** [comment]
@plazzy99 Can you please assign it to me in C++

**Comment by ritvij14** [comment]
@plazzy99 I would like to do this in Java.

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you please assign it to me in C++

**Comment by iamrajiv** [comment]
@pragyajaiswa05l Are you still working on this or should I assign C++ to other because your PR #550 was not valid to be merged.

**Comment by iamrajiv** [comment]
@ankitaggarwal23 Are you still working on this with C?

**Comment by ritvij14** [comment]
@iamrajiv can I also do this in JS? Already submitted PR for Java.

**Comment by iamrajiv** [comment]
@ritvij14 Sure.

**Comment by iamrajiv** [comment]
@SangeetaMishra Sure. Go ahead with C++.

**Comment by iamrajiv** [comment]
@ritvij14 Sure. Go ahead with JavaScript.

**Comment by ankitaggarwal23** [comment]
@iamrajiv Yes I'm working with C.

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you assign this to me in C as well

**Comment by iamrajiv** [comment]
@SangeetaMishra Sure.

**Comment by SangeetaMishra** [comment]
@iamrajiv @atarax665 @plazzy99 @Kajol-Kumari  I have added code in C and C++
