### ISSUE TITLE
QUICK SORT

### ISSUE THREAD

**Issue by rgrupesh** [HarshCasper/NeoAlgo#418]
## 🚀 Feature

(Add Quick Sort algorithm in C.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

## Motivation

(It is faster than other O(nlogn) algorithm. It can deal with huge list of number effectively.)

## Pitch

(Quick Sort is widely used sorting algorithm. Also, known as partition exchange sort. This works better than other divide-and-conquer algorithm. Because it sorts in place, no additional storage is required as well. )

**Comment by rgrupesh** [comment]
Please, assign me this issue. I want to work in C as a part of Hackin Codes 2020.

**Comment by shankhanil007** [comment]
I would like to solve this issue in C++ as a part of Hackin Codes 2020

**Comment by Anjali2001saxena** [comment]
I want to work on this issue in java.

**Comment by pragyajaiswa05l** [comment]
would like to contribute in c++ as a part of HakinCodes2020

**Comment by HarshCasper** [comment]
I have assigned the Issue to you @rgrupesh in C

For rest of the languages, we have the implementation

**Comment by kashika3101** [comment]
I would like to work on this issue in c++

**Comment by vishaljss2021** [comment]
I would like to work in time complexity of quick sort using C.
