### ISSUE TITLE
Vertical Order Traversal in Binary Tree - C++

### ISSUE THREAD

**Issue by shivanshugarg12800** [HarshCasper/NeoAlgo#4187]
## 🚀 Feature
This is  Hard level Binary Tree  Algorithm where you have to traverse the tree in vertical order and print the order through a vector

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read all the contribution guidelines

## Motivation
We have read about different Traversals in the Binary Tree as Inorder, Preorder, PostOrder, Level order traversal, and Depth-first traversal.
This is another kind of Traversal where you have to traverse the tree in vertical order.

## Pitch
Implementing this algorithm will surely let students learn more about the Binary trees and implementation of vector, map and queue to another level.

**Comment by shivanshugarg12800** [comment]
I would like to implement this algorithm in C++ language under GSSOC'21

**Comment by ankitaggarwal23** [comment]
@all-contributors bot please add @shivanshugarg12800 for code
