### ISSUE TITLE
All basic functionality of queue

### ISSUE THREAD

**Issue by pragyajaiswa05l** [HarshCasper/NeoAlgo#419]
## 🚀  Description
Implement the basic functionality of queue such as **push, pop, peek**  without using **Inbuilt Functions**.
Also show Empty & Full Functions for the stack.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Please make sure that you have gone through the Contributing Guidelines

## Pitch

A Queue is a linear structure which follows a particular order in which the operations are performed. The order is First In First Out (FIFO).

**Comment by pragyajaiswa05l** [comment]
would like to contribute in c++ as a part of HakinCodes2020.
would implement it using template so as to make it generic.
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by peeky1811** [comment]
Hi @pragyajaiswa05l. I will be happy to work in the Python implementation of this.
If python is not available then only C.
Gopika Murali
Participant at Contributor's Hack '20, HakinCodes

**Comment by Kajol-Kumari** [comment]
> Hi @pragyajaiswa05l. I will be happy to work in the Python implementation of this.
> If python is not available then only C.
> Gopika Murali
> Participant at Contributor's Hack '20, HakinCodes

Hey @peeky1811 please go with python

**Comment by cherryWood55** [comment]
@pragyajaiswa05l  I would like to work in C.

**Comment by infoarpit** [comment]
I would like to work in java. Please assign it to me
Participant at Contributor's Hack '20, HakinCodes

**Comment by siddharth25pandey** [comment]
> @pragyajaiswa05l I would like to work in C.

@cherryWood55 Go ahead with C.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by siddharth25pandey** [comment]
> I would like to work in java. Please assign it to me
> Participant at Contributor's Hack '20, HakinCodes

@infoarpit Go ahead with Java.
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by AakritiKinra** [comment]
I would like to take this up in C++ as part of contributor's hack 2020.

**Comment by siddharth25pandey** [comment]
> I would like to take this up in C++ as part of contributor's hack 2020.

@AakritiKinra  Sorry to say, but someone before you, had commented to work on this issue. Therefore,
Better to look on some different issue or wait if someone will do wrong, then in that case this issue will be transferred to you in that particular language by priority order,
Thanks !
Happy Coding !

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by vatsalkesarwani12** [comment]
> I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020
@Sreelakshmi00 Sorry to say, but someone before you had commented to work on this issue. Therefore,
Better to look at some different issue or wait if someone will do wrong, then, in that case, this issue will be transferred to you in that particular language by priority order.
Thanks!
Happy Coding!

**Comment by ghost** [comment]
I want to contribute to this issue in Golang.

**Comment by siddharth25pandey** [comment]
> I want to contribute to this issue in Golang.

@odavhad  Start working with GoLang
Also, make sure that you have gone through the Contributions Guideline thoroughly.
All the Best!
Happy Coding !

**Comment by riya-joshi-401** [comment]
i would like to work upon this in c please assign me

**Comment by siddharth25pandey** [comment]
## At present all the allocation work has been done for this issue.

**Comment by peeky1811** [comment]
> > Hi @pragyajaiswa05l. I will be happy to work in the Python implementation of this.
> > If python is not available then only C.
> > Gopika Murali
> > Participant at Contributor's Hack '20, HakinCodes
> 
> Hey @peeky1811 please go with python

I just checked out the NeoAlgo/Python/ds/Queue.py / repository and the basic implementation of Queue has already been done in Python by @subhayu99 15 days ago. I'm not clear on what I should do now. Should I unassign myself?
Correct me if I'm wrong, please @Kajol-Kumari.
![image](https://user-images.githubusercontent.com/52784562/90346948-b52c4300-e04a-11ea-9e41-0b793558f067.png)

**Comment by Kajol-Kumari** [comment]
@peeky1811 as it's already done, p\we don't need to do it twice, please look for the other issue :)

**Comment by tejan-singh** [comment]
I want to work on this in Python
