### ISSUE TITLE
Palindrome

### ISSUE THREAD

**Issue by Anjali2001saxena** [HarshCasper/NeoAlgo#420]
## 🚀 Feature

Add algorithm to check for palindrome.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Palindrome is one of the basic but yet important topic.

## Pitch

Palindrome means if word remains same even after reversing it and it is used at many places.

**Comment by shankhanil007** [comment]
I would like to solve this issue in C++ as a part of Hackin Codes 2020

**Comment by Anjali2001saxena** [comment]
I would like to solve in Java.

**Comment by peeky1811** [comment]
Hi I would like to solve this in Cpp and Python because I'm well versed in it. Or else C is similar to Cpp, so I'll work on that too.
Gopika Murali
Participant at Contributor's Hack '20, HakinCodes

**Comment by bagladivyang03** [comment]
I will work in python for this

**Comment by viveksahu26** [comment]
I would solve this issue in java.. so, please assign me..

**Comment by chandankrsahu** [comment]
I would like to solve this issue in C++ as a part of Hackin Codes 2020.@Kajol-Kumari @Abhijit2505

**Comment by pulkitgovrani** [comment]
I would like to work on this issue in javascript

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by vishaljss2021** [comment]
I would like to solve this issue in C

**Comment by shubham5351** [comment]
I would like to work on python.

**Comment by siddharth25pandey** [comment]
## This issue is not the part of **Hakin Codes Contributors' Hack 2020**
