### ISSUE TITLE
Maximum length substring with even no. of each vowel (using bitmasking) in CPP

### ISSUE THREAD

**Issue by bitaashna** [HarshCasper/NeoAlgo#4214]
## 💥 Proposal
I would like to add maximum length substring with even number of each vowel (using bitmasking) in CPP

### Have you read the [Contributing Guidelines on Pull Requests]
Yes,I have

I would like to work on it as a part of GSSOC'21 .Please assign it to me.

**Comment by bitaashna** [comment]
@HarshCasper can you please assign it to me.

**Comment by HarshCasper** [comment]
@all-contributors bot please add @bitaashna for code
