### ISSUE TITLE
Knapsack Problem in DP.

### ISSUE THREAD

**Issue by Nistha-tech** [HarshCasper/NeoAlgo#423]
### **0 1 Knapsack**
A thief robbing a store and can carry a maximal weight of W into his knapsack. There are N items and ith item weigh wi and is value vi. What is the maximum value V, that thief can take ?
Input Format :
Line 1 : N i.e. number of items
Line 2 : N Integers i.e. weights of items separated by space
Line 3 : N Integers i.e. values of items separated by space
Line 4 : Integer W i.e. maximum weight thief can carry
Output Format :
Line 1 : Maximum value V
Constraints
1 <= N <= 20
1<= wi <= 100
1 <= vi <= 100
Sample Input 1 :
4
1 2 4 5
5 4 8 6
5
Sample Output :
13

**Have you read the [Contributing Guidelines on Pull Requests]**
Yes

Happy Coding :)

**Comment by peeky1811** [comment]
I will try to work on this issue in Cpp/Python as I'm well versed in both. Only if both cannot be provided I'll work with C as that is the label.
Gopika Murali
Participant at Contributor's Hack '20, HakinCodes

**Comment by SayaniG371** [comment]
Would like to code this in python as a part of HakinCodes 2020

**Comment by Nistha-tech** [comment]
I would like to work on this issue in Cpp and Python as a part of HakinCodes @Kajol-Kumari .

**Comment by pragyajaiswa05l** [comment]
I would like to contribute in c++ as a part of HakinCodes 2020

**Comment by vinayvyas911** [comment]
I would like to contribute in c++ as a part of HakinCodes 2020

**Comment by HarshCasper** [comment]
I am assigning the Issue to you @pragyajaiswa05l in C++ and to @peeky1811 in Python

@Nistha-tech You cannot work on it yet, as you have two issues under your belt now.

**Comment by chandankrsahu** [comment]
I would like to contribute in C language as a part of HakinCodes 2020

**Comment by neha07kumari** [comment]
I would like to work on this issue using the C  and Java language. @Kajol-Kumari

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by Huzaib** [comment]
Can I take it up in Java?

**Comment by vishaljss2021** [comment]
I would love to solve knapsack problem in C or C++.

**Comment by GrayFlash** [comment]
@HarshCasper @atarax665 is this issue still available in Java.
