### ISSUE TITLE
Add N-Queen in DP

### ISSUE THREAD

**Issue by subhayu99** [HarshCasper/NeoAlgo#424]
## 🚀 Feature

The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

N-Queen is one of the most famous DP Implementation. I just saw that there is no N-Queen problem listed on the repository and that's why this issue is made.

## Pitch

...

## Assignees 

- C++: @shankhanil007
- C and Python: @subhayu99

**Comment by shankhanil007** [comment]
I would like to solve this issue in C++

**Comment by subhayu99** [comment]
I want to work on this in both **C** and **Python**

**Comment by ankitaggarwal23** [comment]
I would like to work on this issue in java and C#.

**Comment by subhayu99** [comment]
@HarshCasper Can I make another PR for the Python version of N-Queen until [this PR](https://github.com/TesseractCoding/NeoAlgo/pull/457) is merged?

**Comment by Huzaib** [comment]
If the implementation in java is open, please assign it to me

**Comment by NirmalSilwal** [comment]
Hi, can I add the **implementation in Java** for N-Queen problem?
