### ISSUE TITLE
[GSSOC'21]

### ISSUE THREAD

**Issue by anumshka** [HarshCasper/NeoAlgo#4253]
## 🚀 Feature

(A clear and concise description of what the feature is.)
Hello,
Standard Template Library is a soul of C++ language.
I have a code that provides basics of vectors, maps and sets in C++.It would be a perfect guide for beginners in competitive programming.
Please assign this to me.
Thankyou.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
---YES

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)
---A quick guide to STL for new programmers.

## Pitch

(Please explain why this feature should be implemented and how it would be used.)
---A necessary and sufficient knowledge of STL is required for common programming contests.

**Comment by ankitaggarwal23** [comment]
No need of such problems
