### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by Anjali2001saxena** [HarshCasper/NeoAlgo#426]
## 🚀 Feature
Add Bucket Sort Algorithm.

### Have you read the [Contributing Guidelines on Pull Requests]
yes

## Motivation
This algorithm deals with much lesser amount of elements at each step than the original so is easy to execute.

## Pitch

Elements are divided in different buckets and each bucket is sorted indivitually at a time.

**Comment by Anjali2001saxena** [comment]
I want to work on this issue in C++.

**Comment by avinashkranjan** [comment]
I want to work on this issue in C

**Comment by Kajol-Kumari** [comment]
Sure @Anjali2001saxena and @avinashkranjan you people can work on this :)

**Comment by ritvij14** [comment]
I would like to take this issue in Java.

**Comment by santushtisharma10** [comment]
@Kajol-Kumari I would like to work on this issue in Python

**Comment by SKAUL05** [comment]
> @Kajol-Kumari I would like to work on this issue in Python

@santushtisharma10 Go Ahead with `Python`

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

**Comment by SKAUL05** [comment]
> I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020

Already assigned to @Anjali2001saxena for C++.

**Comment by Adityanagraj** [comment]
I would like to work on this issue in Python as part of HaikinCodes Contributor's Hack 2020

**Comment by Kajol-Kumari** [comment]
> I would like to work on this issue in Python as part of HaikinCodes Contributor's Hack 2020

Hey @Adityanagraj we have already assigned @santushtisharma10 for python. Also please look at the comments and assignments first before commenting to avoid unnecessary comments :)

**Comment by ahampriyanshu** [comment]
Please assign this to me in Golang.
