### ISSUE TITLE
KMP Algorithm

### ISSUE THREAD

**Issue by Nistha-tech** [HarshCasper/NeoAlgo#427]
### **KMP Algorithm for Pattern Searching**

Input : hakincodes
           kin(pattern to be searched)
output : pattern found at index 2.

### Have you read the [Contributing Guidelines on Pull Requests]?
Yes

## Motivation
Used in various important concepts of string search and string algorithms.

## Pitch
A very important algorithm used to solve questions of string in less time complexity.

## Assignees 

- Python : @anubhvshrma18
- Java : @Vivek214-Candy
- C : @kushagraiitbbs
- JavaScript : @ritvij14
- GO : @odavhad
- C# : 
Happy Coding :)

**Comment by Nistha-tech** [comment]
I would like to work on this issue in Cpp as a part of hakin codes.
@Kajol-Kumari

**Comment by anubhvshrma18** [comment]
I would like to work on this issue in python as a part to hakin codes 
@Kajol-Kumari

**Comment by Nistha-tech** [comment]
@HarshCasper please add CH20 label also.

**Comment by SangeetaMishra** [comment]
I would like to work in Java.

**Comment by kushagraiitbbs** [comment]
I would like to contribute to this issue in C as to take part in hakincodes @HarshCasper

**Comment by ritvij14** [comment]
I would like to work on this issue with Javascript as part of HakinCodes.

**Comment by ghost** [comment]
I would like to contribute in Golang

**Comment by Vivek214-Candy** [comment]
I want to contribute in java/javascript/python

**Comment by ritvij14** [comment]
@Kajol-Kumari, @siddharth25pandey could you please assign the issue to us according to the language preferences so we can start working?

**Comment by atarax665** [comment]
Assigning:
C -> @kushagraiitbbs 
JavaScript -> @ritvij14 
GO -> @odavhad 
Java -> @Vivek214-Candy 
Please go through the Contribution Guidelines ( #398 ) before raising your PR.
Happy Coding!

**Comment by ghost** [comment]
@Kajol-Kumari i want to work on this issue in java please assign me this

**Comment by atarax665** [comment]
@HarshAgarwal-DEV Sorry, this issue is already assigned to someone in Java.

**Comment by ritvij14** [comment]
@atarax665 I am working on javascript for this issue, and I have a doubt, do we assume that the pattern appears in the text once only or can it be there multiple times? If yes, do we show all results?

Also, which folder should I put this into?
