### ISSUE TITLE
Search in a rotated and sorted array

### ISSUE THREAD

**Issue by SwarnimaShishodia** [HarshCasper/NeoAlgo#4273]
## 💥 Proposal

(Code in C++ for finding the position of element in a rotated and sorted array, if element is not present, print -1)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by taruni-always** [comment]
I would like to work on this in C/C++/Python. Please assign this to me (under GSSoC'21) if it's available.
