### ISSUE TITLE
Implement Kruskal's Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#43]
**Algorithm:** 

[Kruskal's Algorithm](https://en.wikipedia.org/wiki/Kruskal%27s_algorithm)

**DS:** 

Graphs

**Languages Supported:**

- C [ Assigned to @TanyaAggarwal ]
- C++  [ Assigned to @TanyaAggarwal ]
- Java  [ Assigned to @TanyaAggarwal ]
- Javascript
- Python  [ Assigned to @TanyaAggarwal ]

**Comment by TanyaAggrawal** [comment]
I would like to take this issue for c, c++, java and python.

**Comment by HarshCasper** [comment]
I have assigned you the Issue on C, C++, Java and Python. You can start working on it @TanyaAggrawal

**Comment by lipsamishra1609** [comment]
i would like to contribute in javascript.

**Comment by anshita22** [comment]
I would like to work on this issue in C, C++ and Python
