### ISSUE TITLE
String Rotation 

### ISSUE THREAD

**Issue by smv1999** [HarshCasper/NeoAlgo#433]
## 🚀 String Rotation based on Queries
A String str and number of queries q are given as input. The queries are in the form space separated values with the direction and the amount by which the string is to be rotated. The first characters after each query is concatenated as a separate string and is checked whether it is an anagram of the original string. If yes, print YES otherwise print NO.
For ex:
Input:
career
3
L 2
R 3
L 2
Output:
NO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Helps in Understanding String Shift operations

## Pitch

This will increase the understanding of string manipulation.

Happy Coding!

**Comment by smv1999** [comment]
I would like to work on this issue in Cpp as a part of HakinCodes @Abhijit2505

**Comment by SKAUL05** [comment]
> I would like to work on this issue in Cpp as a part of HakinCodes @Abhijit2505

@smv1999 Go Ahead with C++

**Comment by infoarpit** [comment]
I would like to work in java

**Comment by Lakhan-Nad** [comment]
I would like to implement it in C and Java @SKAUL05

**Comment by SKAUL05** [comment]
> I would like to implement it in C and Java @SKAUL05

Sure thing but could assign you only for one language. Which one do you want @Lakhan-Nad ?

**Comment by Lakhan-Nad** [comment]
> > I would like to implement it in C and Java @SKAUL05
> 
> Sure thing but could assign you only for one language. Which one do you want @Lakhan-Nad ?

I would do it in C

**Comment by SKAUL05** [comment]
> > > I would like to implement it in C and Java @SKAUL05
> > 
> > 
> > Sure thing but could assign you only for one language. Which one do you want @Lakhan-Nad ?
> 
> I would do it in C

Go ahead with C.

**Comment by Lakhan-Nad** [comment]
> > > > I would like to implement it in C and Java @SKAUL05
> > > 
> > > 
> > > Sure thing but could assign you only for one language. Which one do you want @Lakhan-Nad ?
> > 
> > 
> > I would do it in C
> 
> Go ahead with C.

Thankyou

**Comment by ghost** [comment]
I would like to work on this in Python

**Comment by SKAUL05** [comment]
> I would like to work on this in Python

Go ahead with Python

**Comment by Lakhan-Nad** [comment]
@smv1999 wasn't the initial question about forming substrings?

**Comment by smv1999** [comment]
Yes @Lakhan-Nad . I edited the issue but forgot to mention the changes made. I would like to apologize to everyone for this. The revised question is to form anagrams. Please everyone check the updated issue.

**Comment by Lakhan-Nad** [comment]
@smv1999 bro you could have created a new issue rather than changing the original question. I have already made a PR for the original one ! @SKAUL05 what should I do  now?

**Comment by smv1999** [comment]
@Lakhan-Nad really sorry. Either you can revert your PR and create a new one or ask for clarification in the Slack Channel.

**Comment by SKAUL05** [comment]
Create new issues accordingly

**Comment by smv1999** [comment]
@SKAUL05 What shall I do now ?

**Comment by SKAUL05** [comment]
> @SKAUL05 What shall I do now ?

@smv1999 & @Lakhan-Nad discuss amongst urself and decide whether u want to create a new issue.
And then create it accordingly with appropriate title and description.

**Comment by smv1999** [comment]
Okay @SKAUL05 . I would suggest @Lakhan-Nad to revert his PR and create a new one after changing the functionality to forming anagrams. Or else, create a new issue accordingly!

**Comment by Lakhan-Nad** [comment]
> Okay @SKAUL05 . I would suggest @Lakhan-Nad to revert his PR and create a new one after changing the functionality to forming anagrams. Or else, create a new issue accordingly!

Okay I will close this PR @smv1999 can you create a new issue with same problem statement as last one?

**Comment by smv1999** [comment]
Yes sure @Lakhan-Nad !
