### ISSUE TITLE
Lomuto’s and Hoare’s partition techniques

### ISSUE THREAD

**Issue by infoarpit** [HarshCasper/NeoAlgo#434]
## 🚀 Feature

Implement partition techniques Lomuto’s and Hoare’s partition techniques used in quicksort.

## Pitch
Different partition techniques have different time complexities which could decide more efficient ones.

**Comment by PrasadMulherkar** [comment]
I would like to work on this issue in Java

**Comment by atarax665** [comment]
Partition techniques can be explained in Quick Sort Algorithm itself, I don't think we need to add partition techniques programs individually.
