### ISSUE TITLE
Optimizing the Bubble Sort Algorithm

### ISSUE THREAD

**Issue by anubhvshrma18** [HarshCasper/NeoAlgo#436]
## 🚀 Feature
I would like to add an optimized solution of Bubble sort  .
The recent solution would check for swapping if the array is already sorted ,
therefore this feature would check if array is already sorted and stops swapping. This will help in reducing the execution time. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
Reducing the execution time.

## Pitch

This will help to understand the algorithm better and it will reduce the time complexity of it also.
Happy Coding :)

## Assignees: 
- @anubhvshrma18 : C++ 
- @Lakhan-Nad : Java 
- @bikash1317 : Python
- @nutanaarohi123 : C

**Comment by anubhvshrma18** [comment]
i would like to take this issue in C++ as a part of Hakin Codes

**Comment by Lakhan-Nad** [comment]
I would like to do this in Java

**Comment by chandankrsahu** [comment]
I would like to take this issue in C++ as a part of Hakin Codes.@Kajol-Kumari @Abhijit2505

**Comment by bikash1317** [comment]
I would like to take this issue in Python 3.7 as a part of HackinCodes

**Comment by NitikaGupta16** [comment]
I would like to take this issue in C++ as a part of HakinCodes

**Comment by bikash1317** [comment]
Ok thanks for letting me know and choosing me ..

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in C.
Kindly assign me this issue @HarshCasper @iamrajiv @Kajol-Kumari @atarax665 @Abhijit2505

**Comment by Abhijit2505** [comment]
@nutanaarohi123 , get started with C
