### ISSUE TITLE
prime factorization using sieve

### ISSUE THREAD

**Issue by chandankrsahu** [HarshCasper/NeoAlgo#437]
An efficient method to calculate the prime factorization using O(n) space and O(log n) time complexity

**Comment by chandankrsahu** [comment]
i would like to take this issue in C++ as a part of Hakin Codes

**Comment by chandankrsahu** [comment]
@Abhijit2505 @Kajol-Kumari

**Comment by reethikprasad** [comment]
I would like to take up this issue and solve it in C++ with a time complexity of O(logN) as part of Hakin Codes

**Comment by kashika3101** [comment]
I would like to work on this issue in C++ and C as a part of HackinCodes

**Comment by Kajol-Kumari** [comment]
> I would like to take up this issue and solve it in C++ with a time complexity of O(logN) as part of Hakin Codes

Hey @reethikprasad as @chandansahuji has already commented I can't assign it to you for c++, please feel free to choose any other language :)

**Comment by Kajol-Kumari** [comment]
> I would like to work on this issue in C++ and C as a part of HackinCodes

@kashika3101  Please go with C as C++ is already taken up by @chandansahuji

**Comment by anime19** [comment]
I would like to take this issue in JAVA.
Please assign this issue to me.
Participant at HakinCodes
@Kajol-Kumari

**Comment by vatsalkesarwani12** [comment]
@anime19 assigned Java to you

Hope you read the contribution guideline 

Happy Coding!

**Comment by Nagasuruthika** [comment]
I would like to work on this issue in Python.

**Comment by ankitaggarwal23** [comment]
I would like to work on this issue in C#.

**Comment by Nagasuruthika** [comment]
> I would like to work on this issue in Python.

@Kajol-Kumari @plazzy99 Can I?

**Comment by Kajol-Kumari** [comment]
Hey @ankitaggarwal23 please go with c# and @Nagasuruthika please go with Python.

Happy Learning :)

**Comment by ankitaggarwal23** [comment]
@iamrajiv Kindly review my PR #1221 .
