### ISSUE TITLE
Longest Common Subsequence Problem in DP

### ISSUE THREAD

**Issue by Joshitha18** [HarshCasper/NeoAlgo#438]
## 💥 Proposal
Given two sequences, find the length of longest subsequence present in both of them. A subsequence is a sequence that appears in the same relative order, but not necessarily contiguous.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

**Comment by Joshitha18** [comment]
I would like to work on it in C++ @Kajol-Kumari @Abhijit2505 as a part of HakinCodes

**Comment by NitikaGupta16** [comment]
I would like to work on it in C++ as a part of HakinCodes @Kajol-Kumari @Abhijit2505

**Comment by shubha028** [comment]
I would like to work on it using java as a part of HakinCodes .Please assign me this issue

**Comment by Kajol-Kumari** [comment]
Hey @Joshitha18 I think we already have it [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/dp/longest_increasing_subsequence.cpp) If you proposal is different from what I pointed out, please feel free to put your points here.

**Comment by Joshitha18** [comment]
@Kajol-Kumari It's Longest increasing subsequence, this is longest common subsequence. Both are not same

**Comment by Kajol-Kumari** [comment]
> I would like to work on it in C++ as a part of HakinCodes @Kajol-Kumari @Abhijit2505

Hey @Nitikagupta16 please choose any other language as c++ and java has already been take up

**Comment by yashsahay25** [comment]
I would like to work on it in C as a part of HakinCodes 2020. Kindly assign me this issue.

**Comment by santushtisharma10** [comment]
@Kajol-Kumari @SKAUL05 I would like to work on this issue in Python

**Comment by shubha028** [comment]
@Kajol-Kumari  I have made a pull request please check .

**Comment by yashsahay25** [comment]
@Kajol-Kumari I have made a pull request. Kindly check it.
