### ISSUE TITLE
Maximum topology short CP /C++

### ISSUE THREAD

**Issue by codeakki** [HarshCasper/NeoAlgo#4389]
## 💥 Proposal

It is an important Cp Topic that is very useful 
For example, consider the tree below:

                          2
                1                  3
The sorted list of pairs is ((2,2),(1,3),(1,1)).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by codeakki** [comment]
#4392

**Comment by codeakki** [comment]
#4654

**Comment by bhav09** [comment]
Merged.
