### ISSUE TITLE
Implement Prim's Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#44]
**Algorithm:** 

[Prim's Algorithm](https://en.wikipedia.org/wiki/Prim%27s_algorithm)

**DS:** 

Graphs

**Languages Supported:**

- C [ Assigned to @ShubhamRattra ]
- C++  [ Assigned to @ShubhamRattra ]
- Java  [ Assigned to @ShubhamRattra ]
- Javascript
- Python  [ Assigned to @ShubhamRattra ]

**Comment by ShubhamRattra** [comment]
I would like to take issue for c, c++, java and python.

**Comment by HarshCasper** [comment]
I have assigned you the Issue. You can start working on it @ShubhamRattra 💥

Please follow the general guidelines:

- Make a Branch off your Master and work on that.
- Make a proper README of how your Script works and what all libraries and modules you have used.
- Add Proper Comments and focus on Clean Code, in practice.
- Also reference this Issue in your PR so that it becomes easy for us to review.

**Comment by lipsamishra1609** [comment]
i would like to contribute in javascript.
