### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by kushagraiitbbs** [HarshCasper/NeoAlgo#441]
This algorithm calculates the maximum sum of subarray in O(n).( where n is the size of array). It gives the basic knowledge of dp on arrays.

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
As this algorithm has not been included in any issue for Hakincodes.

## Pitch
This algorithm gives the understanding of questions related to sum on array.

**Comment by kushagraiitbbs** [comment]
I want to contribute to this issue in C++ @HarshCasper @Abhijit2505

**Comment by SKAUL05** [comment]
It's already there in python 
https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/other/Kadanes_Algorithm.py
Check it for other languages also @HarshCasper @Abhijit2505

**Comment by reethikprasad** [comment]
I want to contribute to this issue in C language as a part of Hakins code @HarshCasper

**Comment by Sreelakshmi00** [comment]
I would like to work on this issue in C++ as part of HaikinCodes Contributor's Hack 2020
