### ISSUE TITLE
Euler's totient function

### ISSUE THREAD

**Issue by kushagraiitbbs** [HarshCasper/NeoAlgo#445]
F(n) denotes Euler's totient function.where n is natural number.F(n) counts all the numbers between 1 to n ( both exclusive) that are relatively prime to n.

### Have you read the [Contributing Guidelines on Pull Requests]
Yes.

## Motivation
As it has not beed added in any issue in hakin-codes.

## Pitch
It is a core technique of number theory which is very helpful in competitive programming.

**Comment by kushagraiitbbs** [comment]
I want to contribute to this issue in c++. @SKAUL05 @Abhijit2505 @HarshCasper @plazzy99

**Comment by ishitakeshawani** [comment]
@HarshCasper I want to work on this issue in java. please assign me this and please add CH20 label on it.

**Comment by vatsalkesarwani12** [comment]
@kushagraiitbbs go with c++

Hope you have gone through the contributor's guidelines to make pr

Happy Coding!

**Comment by vatsalkesarwani12** [comment]
@Ishita1608 go with java

Hope you have gone through the contributor's guidelines to make pr

Happy Coding!

**Comment by ishitakeshawani** [comment]
yes, I read it. thank you for assigning me.

**Comment by mharshita** [comment]
@plazzy99 I work on this issue in C for Contributors Hack 2020. Please assign this to me.

**Comment by yyash01** [comment]
Hi, can I contribute to this issue in C  @plazzy99

**Comment by kushagraiitbbs** [comment]
Sir, please add the difficulty level @plazzy99

**Comment by ag278** [comment]
I work on this issue in python
 for Contributors Hack 2020. Please assign this to me.

**Comment by vatsalkesarwani12** [comment]
@mharshita yeah you can contribute in C 

But first, go through the contributor's guidelines before making any pr

Happy coding!

**Comment by vatsalkesarwani12** [comment]
@yyash01 sorry your friend mentioned it before to contribute in C

There are many issues, find another one and ask me to assign 

Happy Coding!

**Comment by vatsalkesarwani12** [comment]
@ag278 go and work on this issue with python

Happy coding!

**Comment by mharshita** [comment]
@plazzy99 Okay. Thanks!

**Comment by kushagraiitbbs** [comment]
@plazzy99 Sir,actually in a hurry I have given the wrong topic because it is an application of euler's totient function. Sir, may I edit the issue. Sir, my problem statement will remain same of calculating no. of coprime between 1 and n.

**Comment by pulkitgovrani** [comment]
I would like to work on this in Javascript @plazzy99

**Comment by vatsalkesarwani12** [comment]
@pulkitgovrani go with js

Happy Coding

**Comment by mharshita** [comment]
@plazzy99 I am dropping this issue. Sorry for the inconvenience.

**Comment by SangeetaMishra** [comment]
@siddharth25pandey Can you assign it to me for C?

**Comment by SangeetaMishra** [comment]
@iamrajiv  Can you please assign this issue to me in C? The previous assignee has removed their assignment.

**Comment by iamrajiv** [comment]
@Ishita1608 Are you still working on this?

**Comment by SangeetaMishra** [comment]
@iamrajiv I have added the C code.

**Comment by SangeetaMishra** [comment]
@iamrajiv I have added the C code.

**Comment by ishitakeshawani** [comment]
> @Ishita1608 Are you still working on this?

no

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you assign it to me for Java

**Comment by iamrajiv** [comment]
@SangeetaMishra Go ahead with Java.

**Comment by SangeetaMishra** [comment]
@iamrajiv Added Java Code
