### ISSUE TITLE
Longest Common Subsequence in C | GSSoC'21 | Dynamic Programming

### ISSUE THREAD

**Issue by Harikrishnan6336** [HarshCasper/NeoAlgo#4472]
## 💥 Proposal

Longest Common Subsequence in C 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by ankitaggarwal23** [comment]
@Harikrishnan6336 Someone is already working on this issue here #3713. Kindly check before opening issue.
