### ISSUE TITLE
Rabin karp algorithm  in c [gssoc21]

### ISSUE THREAD

**Issue by kavyasree-123** [HarshCasper/NeoAlgo#4475]
## 💥 Proposal
Rabin-Karp is  pattern searching algorithm to find the pattern in a more efficient way, 
finds the hash value. When the hash value is matched, then only it tries to check each character 
To give a clear idea lets have inputs and outputs

Input: str[] = "abcdefghji"
word[] = "abc"
Output: Pattern is at position 1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Someone is already working in this issue in C here #4052. Kindly check before opening an issue.
