### ISSUE TITLE
Zig Zag Tree Traversal in C++

### ISSUE THREAD

**Issue by anushkasethi1710** [HarshCasper/NeoAlgo#4476]
## 💥 Proposal

Hi :) I would like to work on Zig Zag traversal of a binary tree in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Issue already available
