### ISSUE TITLE
Merge Overlapping Subintervals  

### ISSUE THREAD

**Issue by ishitakeshawani** [HarshCasper/NeoAlgo#449]
### Given a collection of intervals, merge all overlapping intervals.
Languages
C
 CPP 
Java
JavaScript
 Go lang
Python
C# 

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

(https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

## Motivation

This question will help to improve the thinking style of your in programming.

## Pitch

It will be in *CP* In Any language. It can be solved using by an array, Stack, linked list, vector. It will help to think about how we can solve complex problems by different data structures.

**Comment by ishitakeshawani** [comment]
@Abhijit2505 
I want to provide an optimum solution for it.please assign me this.

**Comment by ishitakeshawani** [comment]
please add a label on it. @plazzy99

**Comment by ishitakeshawani** [comment]
@Abhijit2505 I want to do it in java. please assign me.

**Comment by DrSehgal7** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99 @siddharth25pandey
Can you please assign this issue to me. I would like to contribute in C++. Thank you!

**Comment by vatsalkesarwani12** [comment]
@Ishita1608 please elaborate for issue

**Comment by ishitakeshawani** [comment]
Done! Please add difficulty level and CH20 Label. 
@plazzy99

**Comment by DrSehgal7** [comment]
@plazzy99 I would like to contribute in C++.Thank you!

**Comment by MohammadSameer08** [comment]
i can do this using C

**Comment by Nagasuruthika** [comment]
I would like to contribute in Python.Thank you!

**Comment by Nagasuruthika** [comment]
> I would like to contribute in Python.Thank you!

@plazzy99

**Comment by SKAUL05** [comment]
Assigning to following according to languages:
C: @MohammadSameer08 
C++: @DrSehgal7 
Java: @Ishita1608 
Python: @Nagasuruthika

**Comment by ishitakeshawani** [comment]
@plazzy99 can you please add CH20 label on this issue.
