### ISSUE TITLE
Finding smallest period of a string in CPP

### ISSUE THREAD

**Issue by singhsaurav23** [HarshCasper/NeoAlgo#4498]
## 💥 Proposal

Find the period of the string where the period of the string is the minimum value of k (k >= 1), that satisfies A[i] = A[i % k] for all valid i using z function in CPP.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
@singhsaurav23 Why Found that you are spamming opening PR for same issue many time also when we approved you again closed.
