### ISSUE TITLE
Implementation Of Interpolation Search Algorithm

### ISSUE THREAD

**Issue by sharur7** [HarshCasper/NeoAlgo#451]
## 🚀 Feature

The Interpolation Search Algorithm:
Interpolation search is an algorithm for searching for a key in an array that has been ordered by numerical values assigned to the keys.

Language Supported:

C
CPP
Python
Java
C#
JavaScript
GO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is an improved variant of binary search. 
It has not yet been added to this repository.

## Pitch

Though the implementation of Binary search and Interpolation search is the same, the Interpolation search works better than Binary Search.
This search algorithm works on the probing position of the required value.
Interpolation search parallels how humans search through a telephone book. 
Instead of comparing against every item like the linear search, it attempts to find the item by approximating how far the item is likely to be from the current position.

I would like to take up this task to add a clean, informative, and workable code in C++ & Python.

**Comment by sharur7** [comment]
@siddharth25pandey @plazzy99 @Kajol-Kumari @Abhijit2505 @SKAUL05 
Can you please add the relevant labels to it and assign the issue to me.  Thank you!

**Comment by Ajay0511** [comment]
I would like to do it in Python.

**Comment by nlok5923** [comment]
please assign this task to me i would like to do in in CPP.

**Comment by vatsalkesarwani12** [comment]
@sharur7 Go with C++ and Python

Happy coding!!

**Comment by vatsalkesarwani12** [comment]
@Ajay0511 and @nlok5923 both the language was already asked to assign by your friend 

If You want to contribute in any other language please comment

**Comment by nutanaarohi123** [comment]
I want to take up this issue in JAVA.pls, assign this task to me.

- [x] Yes, I have read all the **contributing guidelines.**

**Comment by SKAUL05** [comment]
> I want to take up this issue in JAVA.pls, assign this task to me.
> 
> * [x]  Yes, I have read all the **contributing guidelines.**

Go Ahead with Java. 
Follow the Contribution Guidelines carefully.
All the best

**Comment by yashaswibiyahut** [comment]
I would like to do this in C. Please assign this task to me.

**Comment by mharshita** [comment]
@plazzy99  Please assign this issue to me in JavaScript.

**Comment by vatsalkesarwani12** [comment]
@yashaswibiyahut go ahead with C
@mharshita  go ahead with javaScript

**Comment by yashaswibiyahut** [comment]
I have PR the Interpolation Search in C..Kindly review it @plazzy99

**Comment by nutanaarohi123** [comment]
pls, add difficulty label to this issue @HarshCasper @iamrajiv
