### ISSUE TITLE
Window Sliding Technique

### ISSUE THREAD

**Issue by imPGupta** [HarshCasper/NeoAlgo#452]
To find maximum sum of K consecutive elements of an array.
Reference- [Window sliding technique](https://www.geeksforgeeks.org/window-sliding-technique/)

**Language Supported**
- C [@imPGupta]
- CPP [@piyushgoell]
- Python [@sukritidawar]
- Java  [@shubha028]
- C# 
- JavaScript [@Naman-1234]
- GO

**Comment by imPGupta** [comment]
I want to contribute in C and CPP to this issue

**Comment by shubha028** [comment]
I want to contribute in java. Please assign me this issue.

**Comment by sukritidawar** [comment]
I want to work on this issue in python.

**Comment by piyushgoell** [comment]
i want to work on this issue in C++

**Comment by Naman-1234** [comment]
I can do this in C++ and Python
I have read the **contribution guidelines**
Giving the brief overview of how will i solve it is by using **doubly ended queue** as each time we have to insert one element in right and delete one element from left.

**Comment by atarax665** [comment]
@imPGupta You can take this issue in C.
Happy Coding!

**Comment by atarax665** [comment]
@shubha028 You can do this in Java.
Get started !

**Comment by atarax665** [comment]
@sukritidawar You can start working on this issue in Python.
Happy coding!

**Comment by atarax665** [comment]
@piyushgoell Assigned in C++
Happy Coding!

**Comment by atarax665** [comment]
@Naman-1234 You can work on this in JavaScript. I am excited to see your approach to this problem.
Happy coding!

**Comment by piyushgoell** [comment]
@atarax665 review my PR
