### ISSUE TITLE
Generic trees with any number of children

### ISSUE THREAD

**Issue by stratospher** [HarshCasper/NeoAlgo#455]
## 🚀 Feature

Implement tree operations on generic trees like:
1. building tree
2. computing height
3. different tree traversals
4. counting nodes

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

to simulate a tree data structure which can have many children for HakinCodes

## Pitch

I would like to add code for generic trees in cpp.

**Comment by stratospher** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99 @siddharth25pandey 
Can you please add the relevant labels to it and assign the issue to me. Thank you!

**Comment by vatsalkesarwani12** [comment]
@stratospher in which language you want to contribute

**Comment by stratospher** [comment]
> @stratospher in which language you want to contribute

I would like to code in cpp. @plazzy99 could u assign it to me?

**Comment by vatsalkesarwani12** [comment]
@stratospher go with c++

Happy Coding!

**Comment by Vivek214-Candy** [comment]
I want to contribute in java please assign to me
