### ISSUE TITLE
Nth Term

### ISSUE THREAD

**Issue by Amanduttbhagat** [HarshCasper/NeoAlgo#4576]
## 🚀 Feature

Nth Term(in Java) :  
  print the Nth term of the given sequence : 
  1,2,3,4,6,9,13,19,...

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Concept Building

## Pitch

one of the most important question

**Comment by siddharth25pandey** [comment]
@Amanduttbhagat The Issue is **Invalid**
As this Program doesn't depicts any Algo nor it is a General Algo for any Nth Term Sequence
