### ISSUE TITLE
Graph Problem:-Minimum Number of Swaps Required to Sort an Array 

### ISSUE THREAD

**Issue by DrSehgal7** [HarshCasper/NeoAlgo#461]
## 🚀 Feature

You are given an unordered array consisting of consecutive integers  [1, 2, 3, ..., n] without any duplicates. You are allowed to swap any two elements. You need to find the minimum number of swaps required to sort the array in ascending order.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation
As it has not beed added in any issue in hakin-codes.

## Pitch
Very Common Algorithm. It is Useful in Solving Many Graph related Problems.

**Comment by DrSehgal7** [comment]
Would like to contribute in C++ as a part of HakinCodes2020.

@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey @HarshCasper

**Comment by DrSehgal7** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99 @siddharth25pandey
Can you please add the relevant labels to it and assign the issue to me. Thank you!

**Comment by Kajol-Kumari** [comment]
Hey @DrSehgal7 can you please mention the language you are going to do it?

**Comment by DrSehgal7** [comment]
@Kajol-Kumari  Would like to work on it on C++ and C both

**Comment by DrSehgal7** [comment]
@Kajol-Kumari Would like to work on C++ and C both

**Comment by AkM-2018** [comment]
I would like to work on this in Python

**Comment by ritvij14** [comment]
I would like to work on this in Java.

**Comment by vatsalkesarwani12** [comment]
@ritvij14 go with java

**Comment by ritvij14** [comment]
@DrSehgal7 I had a doubt about this algorithm. Is the array consisting of any set of consecutive integers that are arranged unordered? Or is it like the first N consecutive integers from 1 to N?

**Comment by DrSehgal7** [comment]
@ritvij14 For example N= 50 so you will have an array of 50 elements and all of them will be from 1 to 50 without duplicates.
For eg:-
N=10
array[]={3 7 6 9 1 8 10 4 2 5}
ans=9

I hope your doubt is clear now!

**Comment by ritvij14** [comment]
@DrSehgal7 yes it's clear now, thanks for the clarification. :D
