### ISSUE TITLE
Decimal to Hexadecimal conversion in C

### ISSUE THREAD

**Issue by MayureeS** [HarshCasper/NeoAlgo#4623]
## 💥 Proposal

Given a number in Decimal form, convert it into its Hexadecimal form. I would write code in C.
Ex:
Input : 10
Output: A

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by YandaSaketh** [comment]
Hello team,
I hope you are doing well.
I would like to contribute for this question in C++
Please assign this to me.
