### ISSUE TITLE
Pascal Triangle

### ISSUE THREAD

**Issue by YandaSaketh** [HarshCasper/NeoAlgo#4653]
## 💥 Proposal
Hello team,
I'm Saketh, GSSOC'21 participant.
Please assign this issue to me.

Print Pascal Triangle for a given input.(c++)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Issue already available #3652
