### ISSUE TITLE
DP solution for Fibonacci

### ISSUE THREAD

**Issue by Joshitha18** [HarshCasper/NeoAlgo#466]
## 💥 Proposal

Both Top-down and Bottom-Up DP approach for solving Finonacci Numbers in optimized way with Time Complexity O(n)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by Joshitha18** [comment]
I want to work on it in C++ @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by AltCtrlDel1999** [comment]
I want to work on it in java

**Comment by nlok5923** [comment]
i would like to work on this issue with CPP language @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by ashishsahu1** [comment]
I want to work in python. @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by chandankrsahu** [comment]
I would like to contribute in C language as part of hackincodes.@plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by Kajol-Kumari** [comment]
> i would like to work on this issue with CPP language @plazzy99 @Kajol-Kumari @Abhijit2505

@nlok5923 c++ is already taken by @Joshitha18 so can't assign it to you as we need to follow FCFS :)

**Comment by Huzaib** [comment]
If it is open in java, can you please assign it to me

**Comment by ashishsahu1** [comment]
> I want to work in python. @plazzy99 @Kajol-Kumari @Abhijit2505

@Kajol-Kumari  I have done my pr but it is yet to be merged.

**Comment by neha07kumari** [comment]
I want to work on this issue and use Python for it. Please assign me @Joshitha18  @Kajol-Kumari
