### ISSUE TITLE
String Rotation based on Queries

### ISSUE THREAD

**Issue by smv1999** [HarshCasper/NeoAlgo#468]
## 🚀 Feature

A String str and number of queries q are given as input. The queries are in the form space separated values with the direction and the amount by which the string is to be rotated. The first characters after each query is concatenated as a separate string and is checked whether it is a **substring** of the original string. If yes, print YES otherwise print NO.
For ex:
Input:
career
3
L 2
R 3
L 2
Output:
NO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Helps in Understanding String Shift operations

## Pitch

This will increase the understanding of string manipulation.

Happy Coding!

**Comment by Naman-1234** [comment]
I can do that in c++

**Comment by MohammadSameer08** [comment]
i can do this in java

**Comment by PrasadMulherkar** [comment]
I can do this in python
