### ISSUE TITLE
Implementation of Merge Sort using both ways sequential as well as parallel . 

### ISSUE THREAD

**Issue by PinkyWalia** [HarshCasper/NeoAlgo#469]
## 🚀 Feature

Sort an array of random integers with merge sort using both sequential as well as parallel implementation. 

Language Supported

C
CPP
Python
Java
C#
JavaScript
GO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

This will help to understand the Merge sort algorithm better in term of both time and space complexity as we have taken both ways sequential as well as parallelism.
Happy Coding :)

**Comment by PinkyWalia** [comment]
I want to contribute in python. Please assign me this issue.Thank you!
@HarshCasper @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by SKAUL05** [comment]
@PinkyWalia Go Ahead with Python

**Comment by kushagraiitbbs** [comment]
I want to contribute in c++ @SKAUL05 @HarshCasper 
@Abhijit2505 @Kajol-Kumari @plazzy99

**Comment by kushagraiitbbs** [comment]
sir please add difficulty level @SKAUL05 @HarshCasper @Abhijit2505 @Kajol-Kumari @plazzy99

**Comment by kashika3101** [comment]
I want to contribute to this issue in C / C++
Please assign me this issue

**Comment by ghost** [comment]
I want to contribute to this issue in Golang.

**Comment by Nishtha3512** [comment]
I want to contribute in Java. Please assign it to me.

**Comment by ankitaggarwal23** [comment]
I want to contribute to this issue in C

**Comment by vatsalkesarwani12** [comment]
@kushagraiitbbs go ahead with c++

Happy Coding!

**Comment by vatsalkesarwani12** [comment]
> I want to contribute in Java. Please assign it to me.

@Nishtha3512 go ahead with java

Hope you went through the contribution guidelines

Happy Coding!

**Comment by PinkyWalia** [comment]
> @PinkyWalia Go Ahead with Python

@plazzy99 @SKAUL05 the assignment has removed by me due to certain mistake. Please reassign it again.

**Comment by vatsalkesarwani12** [comment]
@PinkyWalia better stay alert from next time 
Assigning you again

**Comment by Vivek214-Candy** [comment]
I would like to contribute in java /javascript. Please assign to me

**Comment by Vivek214-Candy** [comment]
I want to contribute in python too... Please assign to me

**Comment by GajjarMiten** [comment]
Hey, @plazzy99 I would like to do it in Golang.

**Comment by vatsalkesarwani12** [comment]
@GajjarMiten go with golang

**Comment by neha07kumari** [comment]
I want to contribute in C Language. Please assign me @PinkyWalia
