### ISSUE TITLE
Implement Dijkstra's Algorithm

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#47]
**Algorithm:** 

[Dijkstra's Algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)

**DS:** 

Graphs

**Languages Missing:**

- C 
- C++ __[Assigned to @atarax665]__
- Javascript
- Python __[Assigned to @atarax665]__

**Comment by atarax665** [comment]
I'll like to take this issue in C++ and python.

**Comment by mar-galho** [comment]
I'm taking this in Java and uploading it right now.

**Comment by atarax665** [comment]
@ricardoprins Hard or medium, any one of the label should be removed.

**Comment by Jyotika999** [comment]
Can i work this in C language?

**Comment by lipsamishra1609** [comment]
i would like to contribute in javascript.

**Comment by reachpranjal** [comment]
I can take this in C and JS.

**Comment by Sidhant-Gupta** [comment]
I'll like to resolve this issue in cpp.
