### ISSUE TITLE
Improving Quick Sort in Python by reduction of number of lines of code

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [HarshCasper/NeoAlgo#4743]
## 🚀 Feature

To improve the existing quick sort in python by reducing the number of lines of code

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

Kindly assign me this as a part of Gssoc 21

**Comment by ankitaggarwal23** [comment]
@Sri-vishnu-r1431 Incomplete issue no existing code file issue number mentioned which you want to modify

**Comment by Sri-vishnu-r1431** [comment]
kindly reissue to me again as exams were going on I was not able to contribute.I deeply apologize for my fault@ankitaggarwal23
