### ISSUE TITLE
Length of longest common substring in Java

### ISSUE THREAD

**Issue by shahina-bano** [HarshCasper/NeoAlgo#4749]
## 💥 Proposal

I would like to add the solution code for this problem in Java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
We can't assign you this problem again as this problem found under plagiarism here #4708.
Closing this PR and Issue. You can choose different problem but not this one again.
