### ISSUE TITLE
Stack implementation using singly Linked List. 

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#478]
## 💥 Proposal

(All Basic operation of stack using singly Linked List .) 
Push
Pop
Peek
Empty checker function. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes.)

**Comment by Rishikeshrajrxl** [comment]
I would like to do this in c++

**Comment by Rishikeshrajrxl** [comment]
I would like to do this in c++.

**Comment by siddharth25pandey** [comment]
@Rishikeshrajrxl  This issue is already exist[ 399](https://github.com/TesseractCoding/NeoAlgo/issues/399)

**Comment by Rishikeshrajrxl** [comment]
@siddharth25pandey 
 In #399 will be implementing using Array data structure.
But here  I will be implementing it using Linked List.

**Comment by siddharth25pandey** [comment]
@Rishikeshrajrxl We cannot make too much variety of issues of the same Algorithm.
Better to look on some different issues.
Thanks !

**Comment by Rishikeshrajrxl** [comment]
ok
