### ISSUE TITLE
Move all negative numbers to beginning and positive to end in python 

### ISSUE THREAD

**Issue by soumikbaithalu** [HarshCasper/NeoAlgo#4813]
## 🚀 Feature

An array contains both positive and negative numbers in random order. Rearrange the array elements so that all negative numbers appear before all positive numbers.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read 

## Motivation

To contribute to GSSOC'21 

## Pitch

This a easy code using sort method we can applied but we can alter methods

**Comment by soumik2012** [comment]
hey @Ab

> /assign

this is my  my issue

**Comment by soumikbaithalu** [comment]
> /assign

This is my issue you can't take it from me could you, please unassign so I can take it @AbdelrahmanDeghedy

**Comment by AbdelrahmanDeghedy** [comment]
Ok, sorry.
How can I un-assign it?

**Comment by AbdelrahmanDeghedy** [comment]
Done, I apologize again.

Good Luck!

**Comment by soumikbaithalu** [comment]
> Done, I apologize again.
> 
> Good Luck!

thank you so much sorry for rude

**Comment by siddharth25pandey** [comment]
@soumik2012 Issue is not **Valid**.
As this issue don't leads to any Algorithm.
