### ISSUE TITLE
Wave Sort in C++

### ISSUE THREAD

**Issue by madhuvanthi27** [HarshCasper/NeoAlgo#4831]
## 🚀 Feature

Given an array of integers, return the array which is sorted into a wave like array.
In other words, arrange the elements into a sequence such that `a1 >= a2 <= a3 >= a4 <= a5...`

**Example:**
Given [1, 2, 3, 4]
One possible answer : [2, 1, 4, 3]
Another possible answer : [4, 1, 3, 2]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes. I have read the contributing guidelines.

## Motivation

I came across this question long back when I was practicing for my STEP interview. The question seemed a bit tricky to me but the solution is really simple and has a simple logic. It felt good after solving this question.

## Pitch

This is a beginner level problem. But the question might seem a little tricky to some people. The logic is also quite simple. Arrays are always important from interview point of view because they cover the basics. Solving this question will make them more confident in arrays.

I would love to work on this issue under GSSOC'21. I have the solution in C++.

**Comment by ankitaggarwal23** [comment]
Problem already present here #2245. Before opening such issue check first whether it is present or not. I will save yours and ours time as well.
