### ISSUE TITLE
Swapping three nos. without use of another variable

### ISSUE THREAD

**Issue by bishalshaw-164** [HarshCasper/NeoAlgo#4834]
## 💥 Proposal

I am a GSSOC participant and want to work on Swapping three nos. without using of another variable
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Vishal-Singh-1996** [comment]
Pls assign it me also would like to do this In java......

**Comment by ankitaggarwal23** [comment]
Don't need such concept based problem
