### ISSUE TITLE
Affine substitution Cipher 

### ISSUE THREAD

**Issue by riya-joshi-401** [HarshCasper/NeoAlgo#486]
## 🚀 Feature

Implementing Affine substitution cipher : both encryption and decryption 
- The program should have encryption function and decryption function for each cipher. 
- The function should take a message and a key / or keys as input from the user and display the expected output.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

The Affine cipher is a type of monoalphabetic substitution cipher which uses a combination of Additive and Multiplicative Ciphers.

## Pitch

It's a very important algorithm in the field of cryptography.

## Assignees

C++: @SangeetaMishra
C: @nutanaarohi123
Python: @riya-joshi-401
Java: @PrasadMulherkar

**Comment by riya-joshi-401** [comment]
i want to work on this using python !!!

**Comment by obli99** [comment]
I wannt to work on it in java

**Comment by PrasadMulherkar** [comment]
I would like to work on this in Java usign Java8 features

**Comment by SangeetaMishra** [comment]
@Kajol-Kumari I would like to work on this in C++.

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in C.kindly assign this issue to me @Kajol-Kumari  @iamrajiv  @siddharth25pandey

**Comment by iamrajiv** [comment]
@SangeetaMishra Go ahead with C++ and @nutanaarohi123 Go ahead with C.

**Comment by nutanaarohi123** [comment]
> @SangeetaMishra Go ahead with C++ and @nutanaarohi123 Go ahead with C.

pls, assign. It's not showing @iamrajiv

**Comment by SangeetaMishra** [comment]
@iamrajiv  Solved it in C++ #757
