### ISSUE TITLE
Transpose a square matrix

### ISSUE THREAD

**Issue by ANSHIKA1806** [HarshCasper/NeoAlgo#4867]
Question : Write a program to transpose a square matrix.

SAMPLE INPUT: Enter the elements of matrix.
1 2 3 4 5 6 7 8 9
SAMPLE OUTPUT: The elements of matrix are
1 2 3
4 5 6
7 8 9
The elements of the transpose of matrix are
1 4 7
2 5 8
3 6 9

@HarshCasper @bhav09 @gargVader @iamrajiv @born-2learn @siddharth25pandey @anushkrishnav @Apoorve73 @ankitaggarwal23 
Please assign this problem to me.

### Assignee
@ANSHIKA1806 : C and JAVA
@somya1252: C++

**Comment by somya1252** [comment]
Hello Admin, Please assign this issue to me

**Comment by siddharth25pandey** [comment]
> Hello Admin, Please assign this issue to me
@somya1252 Please read the message given by **github-actions**

**Comment by siddharth25pandey** [comment]
@ANSHIKA1806 , @somya1252 Please read the message given by **github-actions**

**Comment by ANSHIKA1806** [comment]
@siddharth25pandey Sir I want to implement this question in Java and C. Please assign this to me.

**Comment by somya1252** [comment]
Can I implement this in C++

**Comment by siddharth25pandey** [comment]
@ANSHIKA1806 , @somya1252 Go ahead, All the very best 👍
