### ISSUE TITLE
Hashing in C++

### ISSUE THREAD

**Issue by Debashish-hub** [HarshCasper/NeoAlgo#4869]
## 🚀 Feature

Hashing in C++.
Various problems like Is sudoku valid, triplet sum in array, Key pair, Intersection of two arrays can be solved using hashing.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Competitive coding

## Pitch

These are some of the must do coding questions for interviews in various companies.

**Comment by rachit-geek** [comment]
/assign
I would like to solve this issue. Please assign me this issue @Debashish-hub

**Comment by ankitaggarwal23** [comment]
Need more details
