### ISSUE TITLE
Evaluate Expression in C++

### ISSUE THREAD

**Issue by Op-panda** [HarshCasper/NeoAlgo#4874]
## 💥 Proposal

A cp problem in C++ 

Think of a situation in which the user has to access the computer but to login he/she has to evaluate an expression.
The expression on the screen will be of the form: 22 + 362 + 5678...........
But the user know that the actual form is different from the form shown on screen, and that is , 2^2 + 36^2 + 567^8 ........
The power digit is always 1 digit.
If anyone evaluate the actual form correctly, he/she will be able to login into the computer.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by ankitaggarwal23** [comment]
Need more details

**Comment by Op-panda** [comment]
Think of a situation in which the user has to access the computer but to login he/she has to evaluate an expression.
The expression on the screen will be of the form: 22 + 362 + 5678...........  
But the user know that the actual form is different from the form shown on screen, and that is , 2^2 + 36^2 + 567^8 ........
The power digit is always 1 digit.
If anyone evaluate the actual form correctly, he/she will be able to login into the computer.

**Comment by ankitaggarwal23** [comment]
You can start working.

**Comment by i-shreyagarg** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by ankitaggarwal23** [comment]
@einhawking Someone is already working in this issue. If you want to choose another language and open your issue.

**Comment by siddharth25pandey** [comment]
@Op-panda This issue doesn't leads to any Algorithm. Hence **Invalid**
