### ISSUE TITLE
Rat in a Maze problem 

### ISSUE THREAD

**Issue by PriyanshuChatterjee** [HarshCasper/NeoAlgo#4877]
## 💥 Proposal

Rat in a maze is a problem that is solved using a backtracking algorithm in graphs. Here the Rat maze problem will be solved with C plus plus.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Problem already present #2047
