### ISSUE TITLE
Diameter of a binary tree

### ISSUE THREAD

**Issue by TechTarun** [HarshCasper/NeoAlgo#493]
## 🚀 Description

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

Binary tree forms an important part of interview questions and diameter of a binary tree one of the most asked question.

## Pitch

Diameter of a binary tree is the longest path between 2 leaf nodes that may or may not pass through the root node. Also, the length of the path will be represented as the sum of edges in the path.

**Comment by TechTarun** [comment]
Description is same as pitch.

**Comment by TechTarun** [comment]
I want to solve the question in python language. Kindly assign me the issue.

**Comment by stratospher** [comment]
I would like to do it in C++. Please assign me the issue.

**Comment by prashansasaxena** [comment]
I would like to solve this in Java.Please assign me the issue.
