### ISSUE TITLE
Detect loop in a linked list

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#494]
## 💥 Proposal

( In a Given linked list, check if the linked list has loop or not.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

**Comment by Rishikeshrajrxl** [comment]
@siddharth25pandey , I would like to do this in c++.
Please assign the work.

**Comment by pradeep98** [comment]
I would like to do in Python.

**Comment by Naman-1234** [comment]
i can do that in C, Pls assign me this issue.
**Have you read the contributing guidelines on Pull Requests?
Ans . Yes**
Description :This is a very simple questions and according to me the most efficient way to do this is by taking **two pointers.**

**Comment by SandipNayak** [comment]
I would like to solve this in Java pls assign it to me...

**Comment by viveksahu26** [comment]
I would like to work with this issue in java.. kindly assign me..

**Comment by Rishikeshrajrxl** [comment]
@Kajol-Kumari , please assign this issue.

**Comment by anshita22** [comment]
I would like to work on this issue in C++. Kindly assign this issue to me.
