### ISSUE TITLE
Intersection Point in Y Shapped Linked Lists

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#495]
## 💥 Proposal

(Suppose there are given two singly linked lists of different  size N and M, Now get the point where two linked lists intersect each other)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes)

**Comment by Rishikeshrajrxl** [comment]
@plazzy99 , I would like to do this in c++.
Please assign the work.

**Comment by pradeep98** [comment]
I would like to do this in Python

**Comment by SandipNayak** [comment]
I would like to this solve this in C ,please assign it to me.

**Comment by viveksahu26** [comment]
I would like to work with this issue in java.. kindly, assign me..

**Comment by Rishikeshrajrxl** [comment]
@siddharth25pandey, @plazzy99 , @iamrajiv  .
Please assign this Issue. My all assigned work are done. I am waiting.

**Comment by vatsalkesarwani12** [comment]
@Rishikeshrajrxl go  with c++
@pradeep98  go with python
@SandipNayak go with c
@viveksahu26 go with java
