### ISSUE TITLE
Print the number of ways the amount N can be represented by the given coin using DP 

### ISSUE THREAD

**Issue by vatsalkesarwani12** [HarshCasper/NeoAlgo#497]
#### Program should do
Given a value N, if we want to make a change for N cents, and we have an infinite supply of each of S = { S1, S2, .., Sm} valued coins, how many ways can we make the change? 
The order of coins doesn’t matter.
##### Input: 
N = 4 
S = {1,2,3}
##### Explanation
there are four solutions: {1,1,1,1},{1,1,2},{2,2},{1,3}
##### Output
4
##### Input
N = 10 
S = {2, 5, 3, 6}
##### Explanation
there are five solutions: {2,2,2,2,2}, {2,2,3,3}, {2,2,6}, {2,3,5} and {5,5}
##### Output
5

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Please make sure that you have read the Contributing Guideline

Thanks!

Happy Coding!

##Programming Languages For Implementations:

- C++ -
- Python -  **@diyajaiswal11**
- C - **@diyajaiswal11**
- GO - **odavhad**
- Java - **@Kritika37**

**Comment by diyajaiswal11** [comment]
@plazzy99  I'm interested in solving this issue in C and Python. Please assign this to me.

**Comment by Joshitha18** [comment]
I want to work on it in C++ @plazzy99

**Comment by vatsalkesarwani12** [comment]
@diyajaiswal11 go ahead with C and python

Hope you have gone through the contribution guidelines 

Happy Coding!

**Comment by vatsalkesarwani12** [comment]
@Joshitha18 please wait for your opened pr to merge 
You will be assigned soon

**Comment by Kritika37** [comment]
i would like to work on this in java or C++

**Comment by vatsalkesarwani12** [comment]
@Kritika37 go ahead with java

Hope you have gone through the contribution guidelines

Happy Coding!

**Comment by Kritika37** [comment]
> @Kritika37 go ahead with java
> 
> Hope you have gone through the contribution guidelines
> 
> Happy Coding!

hey may I assume the number of coins up to 500 ?

**Comment by Kritika37** [comment]
> @Kritika37 go ahead with java
> 
> Hope you have gone through the contribution guidelines
> 
> Happy Coding!

Hey there was some problem but i solved it. By mistake, I removed my assignment. Please reassign it  @plazzy99

**Comment by ghost** [comment]
I would like to contribute in Golang

**Comment by vatsalkesarwani12** [comment]
> I would like to contribute in Golang

@odavhad go with golang

**Comment by SangeetaMishra** [comment]
@plazzy99  I would like to contribute in C++

**Comment by SangeetaMishra** [comment]
@plazzy99  I would like to contribute in C++

**Comment by yashaswibiyahut** [comment]
Would like to do this in C++ kindly assign me this issue @Kajol-Kumari @SKAUL05

**Comment by HarshCasper** [comment]
@yashaswibiyahut You are already working on two issues. Make a PR for them before you move forward with next issues.

**Comment by SangeetaMishra** [comment]
@plazzy99 Can you assign it to me in C++

**Comment by ritvij14** [comment]
@plazzy99 can I take this in Java if the assignee is not working on it?

**Comment by Kritika37** [comment]
> @plazzy99 can I take this in Java if the assignee is not working on it?

Hey I have already completed the code, I have to just remove the conflict and merge. @ritvij14

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you please assign this to me in C++
