### ISSUE TITLE
Delete Middle of Linked List

### ISSUE THREAD

**Issue by Rishikeshrajrxl** [HarshCasper/NeoAlgo#499]
## 🚀 Feature

Given a singly linked list, delete middle of the linked list. For example, if given linked list is 1->2->3->4->5 then linked list should be modified to 1->2->4->5.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by Rishikeshrajrxl** [comment]
I would like to do this in c++.

**Comment by Naman-1234** [comment]
I will do that in C,Pls assign me this issue,

**Comment by SandipNayak** [comment]
I want to solve this issue in java

**Comment by Shishir198** [comment]
I want to solve this issue in python3

**Comment by viveksahu26** [comment]
I would like to work with this issue in java..

**Comment by Rishikeshrajrxl** [comment]
@Kajol-Kumari , please assign this issue.

**Comment by viveksahu26** [comment]
i haven't assign any issue yet.. so please assign me this issue.. i would like to solve this in java..

**Comment by Ananya88** [comment]
I would like to contribute in C++ for this ,please assign so @SKAUL05 @Kajol-Kumari @siddharth25pandey
