### ISSUE TITLE
Improve footer of website

### ISSUE THREAD

**Issue by akshay1027** [HarshCasper/NeoAlgo#5006]
## 🚀 Feature
Improvements we can add to Footer are :
1)Find us with logo
2)Call us with logo
3)Mail us with logo
4)Website logo
5)What this website is about
6)Follow us
-Instagram link with logo
-LinkedIn link with logo
-Twitter link with logo
-etc
7)Useful links
-Home
-Services
-About Us
-Contact Us etc
8)Subscribe
-Email address
9)Copyrights
10) All the above with responsive UI

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes 

I would like to work on this issue!

**Comment by SrirajBehera** [comment]
Can I work on this issue? I am a GSSOC participant. I'm a beginner but I want to learn and work.

**Comment by akshay1027** [comment]
Hey @SrirajBehera I want to work on this, hence why created the issue, am waiting for their response :)

**Comment by ankitaggarwal23** [comment]
No need of such issue till now.
