### ISSUE TITLE
Links in the readme to open in a new tab

### ISSUE THREAD

**Issue by akshay1027** [HarshCasper/NeoAlgo#5007]
## 🚀 Feature
Links in the readme to open in a new tab so that it is easier for the user to navigate to GitHub codebase.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by ankitaggarwal23** [comment]
No need of such problem as of now.
