### ISSUE TITLE
Trapping Rainwater

### ISSUE THREAD

**Issue by sneha-nitdgp** [HarshCasper/NeoAlgo#5019]
## 💥 Proposal

(I'd like to add trapping rainwater problem in stack section under C++)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

**Comment by ankitaggarwal23** [comment]
Problem already available #3670
