### ISSUE TITLE
Is sudoku valid

### ISSUE THREAD

**Issue by Debashish-hub** [HarshCasper/NeoAlgo#5033]
## 🚀 Feature

Is sudoku valid is a problem that to be solved using hashing in c++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Competitive coding 

## Pitch

C++ can be used to solve this problem using hashing.

**Comment by rachit-geek** [comment]
/assign
please assign me this issue @Debashish-hub

**Comment by Debashish-hub** [comment]
Why it's not assigned to me, I have created the issue as a gssoc 21 participant.
Is there anyone @Abhijit2505 @ankitaggarwal23 ... who can look into it.

**Comment by ankitaggarwal23** [comment]
@Debashish-hub I assigned you.

**Comment by i-shreyagarg** [comment]
I am a participant of GSSOC'21
I would like to contribute in this

**Comment by ankitaggarwal23** [comment]
@einhawking Someone is already working in this issue. If you want to choose another language and open your issue.
