### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by rgrupesh** [HarshCasper/NeoAlgo#504]
## 🚀 Feature

(Add Shell  Sort.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

## Motivation

(Shell sort is improvement over insertion sort.)

## Pitch

(It compares elements separated by a gap of several positions. This enables it to take bigger steps towards expected position which improves the performance of this algorithm.)

**Comment by rgrupesh** [comment]
Please, assign me this issue. I want to work in C

**Comment by ishitakeshawani** [comment]
I want to solve it in Java. Please assign me it.

**Comment by NEEHITGOYAL** [comment]
I want to solve it in c++. please assign it to me
@Kajol-Kumari @SKAUL05

**Comment by SandipNayak** [comment]
I want to solve it in python,please assign it to me

**Comment by atarax665** [comment]
@rgrupesh This is a duplicate issue, refer to issue #387 . @Ishita1608 @NEEHITGOYAL @SandipNayak comment on #387 . You will be assigned the issue there.
