### ISSUE TITLE
Sort characters by frequency

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#5044]
## 💥 Proposal

Given a string, sort it in decreasing order based on the frequency of characters.It is one of the most commonly asked questions in many of the product based companies

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by kotwani2883** [comment]
Kindly assign this issue to me as a part of GSSOC'21.
Thanks!

**Comment by sumitsantape30** [comment]
Please assign me this issue, will code using Java. I'm participant of GSSoC'21.

**Comment by kotwani2883** [comment]
You can create a different issue for a separate language.
