### ISSUE TITLE
Maxproductsubarray

### ISSUE THREAD

**Issue by rachit-geek** [HarshCasper/NeoAlgo#5063]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
find out the maximum product of an subarray
Pitch
Input: nums = [2,3,-2,4]
Output: 6
Explanation: [2,3] has the largest product 6.

**Comment by rachit-geek** [comment]
/assign
Assign me this issue @ankitaggarwal23

**Comment by ByteCodeLearners** [comment]
We can work on this issue.

**Comment by Abkt2001** [comment]
We can work on this issue
