### ISSUE TITLE
BFS in golang

### ISSUE THREAD

**Issue by nagasrihith608** [HarshCasper/NeoAlgo#5068]
## 💥 Proposal

(A clear and concise description of what the proposal is.)
BFS in golang
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
yes

**Comment by nagasrihith608** [comment]
@ankitaggarwal23, what is the problem? why did you unassign? It's not been 21 days, so why did you unassign it.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23, what is the problem? why did you unassign? It's not been 21 days, so why did you unassign it.

Read the instructions as I already told yesterday and also this issue I already assigned to someone else. Can't do anything.
