### ISSUE TITLE
Implement all the basic functionalities of a doubly linked list

### ISSUE THREAD

**Issue by riya-joshi-401** [HarshCasper/NeoAlgo#508]
## 🚀 Feature

- Implementation of creation, insertion, and deletion of nodes ( at all possible positions ) in a doubly linked list .
- finding the length of DLL
- Traversing and printing the DLL

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

As it has not been added in any issue in Hakin Codes.

## Pitch

Doubly linked list is a type of linked list in which each node apart from storing its data has two links.

**Comment by riya-joshi-401** [comment]
i would like to work upon this in C  as a part of Hakin code please assign me! @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by SandipNayak** [comment]
i would like to work upon this in Java as a part of Hakin code please assign me! @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by jannatulferdaws** [comment]
I would like to work upon this in c++ & python as a part of HakinCodes Please assign me! @plazzy99 @Kajol-Kumari @Abhijit2505

**Comment by Naman-1234** [comment]
I can do that in C++ or python,in whichever u say,Pls assign me this issue

**Comment by Kajol-Kumari** [comment]
@jannatulferdaws please go with c++ for this issue.
@Naman-1234 please go with python for this issue.
@riya-joshi-401 please go with C for this issue.
@SandipNayak please go with java for this issue.

Happy Learning :)

**Comment by Kathan-Vakharia** [comment]
I would like to work on this issue with golang ,  @Kajol-Kumari @plazzy99 @Abhijit2505  can you please assign me :)

**Comment by vatsalkesarwani12** [comment]
@Kathan-Vakharia please go with golang for this issue

**Comment by pulkitgovrani** [comment]
I would like to work on this in Javascript @Kajol-Kumari

**Comment by salonilakhotia** [comment]
@Kajol-Kumari is this issue open to do on java?

**Comment by vatsalkesarwani12** [comment]
@salonilakhotia assigned javascript, go ahead and happy learning.

**Comment by salonilakhotia** [comment]
@plazzy99 I think u miss understood me..I would love to it on java :(

**Comment by vatsalkesarwani12** [comment]
> @plazzy99 I think u miss understood me..I would love to it on java :(

I am sorry

As java been assigned to someone you have to wait or ask a mentor to assign some other issue
