### ISSUE TITLE
Implementation of Brute force string search algorithm

### ISSUE THREAD

**Issue by prasadvpatil** [HarshCasper/NeoAlgo#509]
## 🚀 Feature

Align the pattern against the first m characters of the text and start matching the corresponding pairs of characters from left to right until either all m pairs of characters match or a mismatching pair is encountered. In the latter case, shift the pattern one position to the right and resume character comparisons, starting again with the first character of the pattern and its counterpart in the text.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Its one of the easy method to implement string search.  Helps for beginners to learn and implement basic codes first.

## Pitch

We can implement according to the below algorithm.

Brute_Force_String_Match (T[0…n-1], P[0…m-1])
// Implements brute force string match
// Input:- An array T[0…n-1] of n characters representing a text and an array P[0…m-1] of m characters representing a pattern
// Output:- The index of the first character in the text that starts a matching substring or -1 if the search is unsuccessful
<pre>
for i from 0 to n-m do
       j = 0
      while j < m and P[ j ] = T [ i + j ] do
            j = j + 1
      if j = m
           return i
return -1
</pre>

**Comment by prasadvpatil** [comment]
I would like to work upon this in C @Kajol-Kumari @Abhijit2505 @SKAUL05 @plazzy99

**Comment by Naman-1234** [comment]
i will do it in python3,Pls assign it to me.

**Comment by Kajol-Kumari** [comment]
Hey @prasadvpatil let's not go with the brute force algorithm for this as it's quiet naive! Maybe go for `Rabin–Karp` or `Boyer–Moore string-search algorithm` for this.

**Comment by NitikaGupta16** [comment]
I will work upon it in C++ @Kajol-Kumari @SKAUL05
