### ISSUE TITLE
Reverse array in Java and C++

### ISSUE THREAD

**Issue by jugalnagar** [HarshCasper/NeoAlgo#5093]
## Reverse array in o(n/2) time complexity using Java and CPP also.

 I can code this problem in both java and CPP. Please assign this issue to me

**Comment by shubhidua** [comment]
**Reverse array in o(n/2) time complexity using Java.**
I can code this problem in java. Please assign this issue to me

**Yes, I Have read the** [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues).
