### ISSUE TITLE
Activity Selection in python

### ISSUE THREAD

**Issue by shahina-bano** [HarshCasper/NeoAlgo#5114]
## 💥 Proposal

I want to contribute its solution in python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by dikshajoshi18** [comment]
hey, I would love to work on this issue in c++.
/assign

**Comment by shahina-bano** [comment]
@dikshajoshi18 If you want to contribute, you can create new issues on your and assign it yourself for non existing problems in the repo. Since the above issue is taken by me so you can't contribute in this.

**Comment by dikshajoshi18** [comment]
> @dikshajoshi18 If you want to contribute, you can create new issues on your and assign it yourself for non existing problems in the repo. Since the above issue is taken by me so you can't contribute in this.


I m not taking up your issue I m just doing it in another language, if u can read above.

**Comment by shahina-bano** [comment]
@dikshajoshi18 firstly please mark your words to be used in public, you don't have to be rude. Secondly, I said that you have to create a new issue, you can't contribute to any issue which is open by others by simply commenting on them. Thirdly, for your help, this issue is already taken by another participant in CPP. So from next time onwards, read the instructions on how to contribute to projects for every repo before randomly commenting :)

**Comment by dikshajoshi18** [comment]
> @dikshajoshi18 firstly please mark your words to be used in public, you don't have to be rude. Secondly, I said that you have to create a new issue, you can't contribute to any issue which is open by others by simply commenting on them. Thirdly, for your help, this issue is already taken by another participant in CPP. So from next time onwards, read the instructions on how to contribute to projects for every repo before randomly commenting :)

I m sorry if I sounded rude and thanks for the info... This project was first of it's kind. (Using bot) 
In earlier projects we did commented for someone to assign us the task... I was misunderstood by you.

**Comment by shahina-bano** [comment]
Yeah, I can understand the bot thing, that's why I told you to create a new issue in the very first comment. 
And welcome, I'll be happy to help you with future queries :)

**Comment by dikshajoshi18** [comment]
Thanks a lot ❤
