### ISSUE TITLE
Matrix transpose and Matrix Addition in python

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/NeoAlgo#5125]
## 🚀 Feature

Matrix transpose and Matrix Addition in python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes
## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Matrix addition multiplication and transpose using different languages

**Comment by ankitaggarwal23** [comment]
@aaadddiii Before opening such issues check whether issues are present or not and we can't assign you for all languages as well right now.
