### ISSUE TITLE
Find k closest numbers (Java)

### ISSUE THREAD

**Issue by balarka135** [HarshCasper/NeoAlgo#5133]
## 💥 Proposal
Given a sorted number array and two integers ‘K’ and ‘X’, find ‘K’ closest numbers to ‘X’ in the array. Return the numbers in the sorted order. ‘X’ is not necessarily present in the array

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by balarka135** [comment]
I would like to work on this issue. please assign it to me. (GSSOC 21)

**Comment by dikshajoshi18** [comment]
hey, I would love to work on this issue in c++.
discord: diksha#6684

**Comment by dikshajoshi18** [comment]
> I would like to work on this issue. please assign it to me. (GSSOC 21)

hey just to help you... no one will assign ....just write a comment "/assign" and it will be assigned to you

**Comment by balarka135** [comment]
thank you @dikshajoshi18
