### ISSUE TITLE
Find k closest numbers in c++

### ISSUE THREAD

**Issue by dikshajoshi18** [HarshCasper/NeoAlgo#5134]
## 💥 Proposal
Find k closest numbers in c++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by richakumari19** [comment]
I'm GSSOC'21 Participant. Kindly assign me this issue. I would like to work on this issue in any language you suggest.
