### ISSUE TITLE
Max and min heap 

### ISSUE THREAD

**Issue by bagladivyang03** [HarshCasper/NeoAlgo#515]
## 🚀 Feature

- Implementation of max and min heap using arrays

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

This issue was not yet given in hakin codes and heap is an imp data structure.

## Pitch

A heap is a tree-based data structure. There are two types of heaps:-
MAX and MIN Heap

## Assignees 

- @bagladivyang03 : C++
- @viveksahu26 : Java
- @nutanaarohi123 : C, Python

**Comment by bagladivyang03** [comment]
Hi everyone could  anyone pls assign this in c++ to me as a part of hakin codes 
@Abhijit2505 @Kajol-Kumari @siddharth25pandey @plazzy99

**Comment by viveksahu26** [comment]
Can I get this issue, so that I can work it in java..

**Comment by atarax665** [comment]
@bagladivyang03 We can create a new issue for heap sort. It would be better.

**Comment by bagladivyang03** [comment]
@atarax665 Yeah that is also fine i just want to contribute this problem in hakins code
@SKAUL05 could u pls assign and add relevant labels to it

**Comment by bagladivyang03** [comment]
I like to work in C++

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in C. Kindly assign @HarshCasper @atarax665 @Abhijit2505

**Comment by SangeetaMishra** [comment]
@atarax665  I would like to work on this in C as part of CH20.

**Comment by Abhijit2505** [comment]
@nutanaarohi123, please get started with C

**Comment by Abhijit2505** [comment]
> @atarax665 I would like to work on this in C as part of CH20.

@SangeetaMishra, in CH20, it's first come first serve for the issues. C has been assigned.

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in Python @iamrajiv
