### ISSUE TITLE
Add contributors in the bottom of readme file 

### ISSUE THREAD

**Issue by srisatya12** [HarshCasper/NeoAlgo#5172]
I want to add contributors in the readme file at the bottom .I'm a participant of GSSOC'21 please assign this issue to me .
ADD:

![sc](https://user-images.githubusercontent.com/78905067/113713759-5284d600-9705-11eb-885b-597f3d89b365.png)

**Comment by ghost** [comment]
@srisatya1197 will you be working on this?

**Comment by srisatya12** [comment]
Yes.
