### ISSUE TITLE
Go LIFO and FIFO program

### ISSUE THREAD

**Issue by DeepNinja07x** [HarshCasper/NeoAlgo#518]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.
I want to contribute by adding LIFO(Stack) and FIFO(Queue) programs using Go.

**Comment by siddharth25pandey** [comment]
@DeepNinja07x 
## This issue is already present.

**Comment by DeepNinja07x** [comment]
@siddharth25pandey so can I create pull request

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey so can I create pull request

@DeepNinja07x  you can check the relevant issue. You have not to send the PR for this issue
