### ISSUE TITLE
Heapify-Faster method to create heap

### ISSUE THREAD

**Issue by Vishruta-Patil** [HarshCasper/NeoAlgo#5187]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes
(Write your answer here.)

## Motivation
As a GSSOC'21 participant I want to contribute and help others through my solution
(Please outline the motivation for the proposal.)

## Pitch
In this program heap is created by less number of adjustments. Which makes it faster process of creating heap.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 @HarshCasper I would like to work on this issue

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 can you please assign the issue

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 @HarshCasper  
while pushing the code , I am getting 403 error. Can you please help me to solve this issue

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 @HarshCasper
while pushing the code , I am getting 403 error. Can you please help me to solve this issue

**Comment by Vishruta-Patil** [comment]
I am getting an error while pushing code.
Error: permission denied. Unable to access. The requested URL returned error:403
Please help me to solve this issue. I am not able to contribute from last 20 days.
@ankitaggarwal23 @HarshCasper @bhav09 @anushkrishnav

**Comment by anushkrishnav** [comment]
What is the issue if you can add a screenshot that would be useful to debug

**Comment by Vishruta-Patil** [comment]
remote: Permission to TesseractCoding/NeoAlgo.git denied to Vishruta-Patil.
fatal: unable to access 'https://github.com/TesseractCoding/NeoAlgo.git/': The requested URL returned error: 403

Above is the error message  which I get after the command : git push origin branch-name

Please help me with the issue @anushkrishnav

**Comment by ankitaggarwal23** [comment]
Send the SC then only we will come to know also tell us what command you use from starting how you fork , clone etc I guess in this two only you did mistake most probably What I think you directly clone from TC repo? Isn't it true?

**Comment by anushkrishnav** [comment]
> remote: Permission to TesseractCoding/NeoAlgo.git denied to Vishruta-Patil.
> fatal: unable to access 'https://github.com/TesseractCoding/NeoAlgo.git/': The requested URL returned error: 403
> 
> Above is the error message which I get after the command : git push origin branch-name
> 
> Please help me with the issue @anushkrishnav

I can only help you if you send a screenshot like I asked, 
The problem I think is like ankit said you cloned directly 
Things you need to do copy your file alone and move it to some other folder and delete Neoalgo then come back to github and fork this repo then clone the fork ( in your repo) and then move your algo file back to the newly cloned repo and the do a push it will work.

**Comment by Vishruta-Patil** [comment]
Thank you so much @anushkrishnav  @ankitaggarwal23
