### ISSUE TITLE
Bucket Sort in C++

### ISSUE THREAD

**Issue by Vishruta-Patil** [HarshCasper/NeoAlgo#5189]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes
(Write your answer here.)

## Motivation
As a GSSOC'21 participant I want to contribute and help others through my solution
(Please outline the motivation for the proposal.)

## Pitch
Bucket sort is used when input is uniformly distributed over a range. Therefore this algorithm can be implemented in many problems.
(Please explain why this feature should be implemented and how it would be used.)

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 @HarshCasper I would like to work on this issue

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 can you please assign the issue

**Comment by ankitaggarwal23** [comment]
Problem already present here. #2167
