### ISSUE TITLE
(CH20) Implementation of Playfair cipher using Python

### ISSUE THREAD

**Issue by sharanya02** [HarshCasper/NeoAlgo#519]
### Implementation of -

- Playfair cipher

## Motivation

One of the most common and important cryptographic techniques, which is quite interesting to implement at the same time.

## Pitch
Cryptography is very essential for security and these algorithms might provide some insights on it.

**Comment by atarax665** [comment]
@sharanya02 It would be better if you create separate issues for various cryptography algorithms else it would get really chaotic to keep track of all the algorithms in one issue.

**Comment by sharanya02** [comment]
okay I'll do that.

**Comment by sharanya02** [comment]
@Kajol-Kumari  @SKAUL05  @Abhijit2505  @plazzy99 9 @siddharth25pandey 
Can you please add the relevant labels to it and assign the issue to me. I would like to work on it with python.Thank you!

**Comment by parjanyaacoder** [comment]
Please assign me this issue in Java.

**Comment by SKAUL05** [comment]
Assigning
Java : @parjanyaacoder 
Python : @sharanya02

**Comment by atarax665** [comment]
Visit #785 for Updates.
