### ISSUE TITLE
Using bitwise operators to print binary of a number in C++

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [HarshCasper/NeoAlgo#5204]
## 🚀 Feature

Using bitwise operators to print binary of a number in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Simi06** [comment]
I would like to contribute to the above problem in CPP. am a GSSoC'21 participant. Kindly assign this to me.

**Comment by Simi06** [comment]
**/assign**
