### ISSUE TITLE
Remove the Miscellaneous link from readme of this repository

### ISSUE THREAD

**Issue by gat786** [HarshCasper/NeoAlgo#5208]
## 📚 Documentation

In the root readme where the languages are listed there is a field for Miscellaneous which is no longer present in the repository and it will be good if that is removed from the readme as well.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

**Comment by rohanbabbar04** [comment]
I will do it @gat786
