### ISSUE TITLE
Number System Convertor 

### ISSUE THREAD

**Issue by ankitabasera** [HarshCasper/NeoAlgo#5219]
## 🚀 Feature

I want to add a program, which will be able to perform conversions between any two number systems mentioned below:
1. Decimals
2. Binary
3. Octal
4. Hexadecimal

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read these guidelines.

## Motivation

As a programmer, it is essential to have a basic knowledge of the number systems mentioned above. So, I want to add code for this program.

## Pitch

Using this program, users will be able to perform conversions between any two number systems, and also this program will provide an easy as well as a quick way to do this.

I am a GSSOC participant and would like to code in the C++ language for this program.

**Comment by ankitaggarwal23** [comment]
Problem already present
