### ISSUE TITLE
BFS & DFS in Graphs

### ISSUE THREAD

**Issue by prashansasaxena** [HarshCasper/NeoAlgo#524]
## 🚀 Graph Traversal Algorithms

Breadth First Search and Depth First Search are the basic graph traversal algorithms.
BFS follows  level order traversal approach while DFS follows depth traversal approach.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Graphs are very important data structures and traversals form the basic of this data structure.

## Pitch

Graphs find many implementations in the real world.Ex: Shortest distance

**Comment by Naman-1234** [comment]
I can do that in C,Pls assign me this issue.
I have read the **contributing guidelines on pull requests.**

**Comment by lipsamishra1609** [comment]
I would like to contribute on this issue in java.
