### ISSUE TITLE
Kadane Algorithm in Julia

### ISSUE THREAD

**Issue by Harikrishnan6336** [HarshCasper/NeoAlgo#5308]
## 💥 Proposal

Kadane Algorithm in Julia

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by ankitaggarwal23** [comment]
Already present here #3593
