### ISSUE TITLE
Kadane Algorithm

### ISSUE THREAD

**Issue by pragyajaiswa05l** [HarshCasper/NeoAlgo#532]
## 🚀 Feature

Simple idea of the Kadane’s algorithm is to look for all positive contiguous segments of the array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

Kadane’s algorithm is used to find out the maximum subarray sum from an array of integers.

**Comment by pragyajaiswa05l** [comment]
would like to contribute in c++ as a part of HakinCodes2020.
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by atarax665** [comment]
@pragyajaiswa05l Duplicate issue. Please check #178
