### ISSUE TITLE
Proposal for changing existing code

### ISSUE THREAD

**Issue by Mohim-Singla** [HarshCasper/NeoAlgo#5345]
## 💥 Proposal

The following DP program is not implemented as dynamic programing questions approach, rather it has been implemented using recursion. I would like to change the implementation of the program using dynamic programing approach. Programing language used: C++. 

 C-Plus-Plus/dp/Minimum_Sum_Partition.cpp

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

@HarshCasper Please assign me this issue.

**Comment by Mohim-Singla** [comment]
Also, I have updated the file name to comply with the program functioning.

**Comment by ankitaggarwal23** [comment]
As minimum sum partition problem available here #5255
