### ISSUE TITLE
Create a Contributor's Guideline

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#542]
## 📚 Documentation

Currently, the Project Codebase lacks a Contributor's Guideline which is detrimental for new contributors. We need a good documentation that can actually help new contributors to understand how they can start contributing to this Project. The basic features we are currently looking for are: 

- Refactor the existing ```CONTRIBUTING.md``` to allow new users to get started with knowing how to contribute.
- Add Screenshots wherever possible. 
- Add the basic information about creating Issues, Pull Requests and Branching.
- Mention tutorials related to Git and Github to help them better understand.

This Issue would be later a part of our Wiki which we are working on right now.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Rishikeshrajrxl** [comment]
I would like to work on this issue.

**Comment by devanshiv123** [comment]
I would like to contribute.

**Comment by HarshCasper** [comment]
Assigned to you @Rishikeshrajrxl
