### ISSUE TITLE
Add a Tutorial on resolving Merge Conflicts and pulling new changes to Fork

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#543]
## 📚 Documentation

I am looking for a Tutorial which can later form a part of our `Wiki` page which gives the new contributors a broad idea on how they can resolve Merge Conflicts and pull new changes to their fork, making it even with the master. 

These tutorials will make a part of a separate directory under `Tutorials/` and would include all the Markdown Files for various tutorials and know-how of important concepts. As part of this Issue: 

- Add a broad tutorial on how to resolve Merge Conflicts on Github or a general-purpose Text Editor like VS Code. 
- Add a tutorial on how to make our fork even with the Master. 
- Add tutorial links (Articles/YouTube Videos) wherever possible. 
- Show an in-general example on performing both the operations.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Rishikeshrajrxl** [comment]
I would like to work on this .

**Comment by HarshCasper** [comment]
Assigned to you @Rishikeshrajrxl
