### ISSUE TITLE
Add a C++ Style Guide Documentation

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#544]
## 📚 Documentation

Create a C++ Style Guide Documentation in the specific `C-Plus-Plus` Directory which serves the following purpose: 

- Acquaint the User about the C++ Styles Guide and what are the best practices to follow.
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in C++ Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by Kritika37** [comment]
I would like to work on this.

**Comment by piyushgoell** [comment]
i would also like to contribute on this too.

**Comment by HarshCasper** [comment]
I have assigned to you @Kritika37

**Comment by akanksha-saini** [comment]
Can I contribute to this issue @HarshCasper as @Kritika37 have closed her PR.

**Comment by Kritika37** [comment]
> Can I contribute to this issue @HarshCasper as @Kritika37 have closed her PR.

I have closed it for some correction and will be sending new PR soon @akanksha-saini
