### ISSUE TITLE
Add a Python Style Documentation

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#545]
## 📚 Documentation

Create a Python Style Guide Documentation in the specific `Python` Directory which serves the following purpose: 

- Acquaint the User about the Python Styles Guide and what are the best practices to follow (PEP-8).
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in Python Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by sanusoumya17** [comment]
I would like to work on this issue

**Comment by atarax665** [comment]
@sanusoumya17 Great!, You can start working on this. Use [PEP8](https://www.python.org/dev/peps/pep-0008/) for reference.

**Comment by SKAUL05** [comment]
@HarshCasper Would recommend introducing **Linters** also.

**Comment by kritikaparmar-programmer** [comment]
Can I work on this issue? @atarax665
