### ISSUE TITLE
Prefix Sum Array

### ISSUE THREAD

**Issue by pragyajaiswa05l** [HarshCasper/NeoAlgo#547]
## 🚀 Feature

Prefix Sum array is a data structure design which helps us to answer several queries such as sum in a given range in constant time which would otherwise take linear time. It requires a linear time preprocessing and is widely used due to its simplicity and effectiveness.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by pragyajaiswa05l** [comment]
would like to contribute in c++ as a part of HakinCodes2020.
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by PrasadMulherkar** [comment]
I want to solve this issue in Java of HakinCodes 2020

**Comment by gupta-piyush19** [comment]
I would like to work on this issue in JavaScript.

**Comment by Mohitkumar6122** [comment]
would like to contribute in **Python** as a part of HakinCodes2020.
@SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by sahanabalappa** [comment]
I would like solve this using java

**Comment by Ananya88** [comment]
i would like to work on this in C++,please assign c++ to me @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey
