### ISSUE TITLE
Queue using only two stacks in python

### ISSUE THREAD

**Issue by arpit456jain** [HarshCasper/NeoAlgo#5474]
## 🚀 Feature

Only two stacks will be used with operations push and pop for making a queue.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by geekymeeky** [comment]
@HarshCasper I would like to work on this issue. Kindly assign this to me under GSSoC'21.
