### ISSUE TITLE
[Gssoc'21] Reverse first k element of queue

### ISSUE THREAD

**Issue by arpit456jain** [HarshCasper/NeoAlgo#5475]
## 🚀 Feature

user will enter the value of k and a queue is given the code will reverse the first k elements in that queue

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by vermatanu** [comment]
can i be assigned to this as a part of gssoc21 ?

**Comment by Simi06** [comment]
I would like to contribute to the above problem in CPP. am a GSSoC'21 participant. Kindly assign this to me.

**Comment by arpit456jain** [comment]
@Simi06 i am un-assigning my self you can assigned it to you by writing "/assign"

**Comment by Simi06** [comment]
**/assign**

**Comment by arpit456jain** [comment]
> **/assign**

done write in double strings 😅 simply write 
I had written it in double string because I don't want it assign me again.
Hope you understand 😃

**Comment by Simi06** [comment]
thanks, @arpit456jain

**Comment by arpit456jain** [comment]
@Simi06 I am sorry i have to close this issue as you know we can't make more that 2 issues at a time but you can create this same issue of your own i hope you don't mind
