### ISSUE TITLE
(CH20) Implementation of Hill Cipher

### ISSUE THREAD

**Issue by sharanya02** [HarshCasper/NeoAlgo#548]
### Implementation of -

- [Hill cipher](https://en.wikipedia.org/wiki/Hill_cipher#:~:text=In%20classical%20cryptography%2C%20the%20Hill,than%20three%20symbols%20at%20once.)

## Motivation

One of the most common and important cryptographic techniques, which is quite interesting to implement at the same time.

## Pitch
Cryptography is very essential for security and these algorithms might provide some insights on it.

**Languages Supported:**
- C [@SangeetaMishra]
- CPP [@SwagataJ ]
- Python [@sharanya02]
- Java 
- C#
- JavaScript
- GO [@GajjarMiten]

**Comment by sharanya02** [comment]
@Kajol-Kumari  @SKAUL05  @Abhijit2505  @plazzy99 9 @siddharth25pandey 
Can you please add the relevant labels to it and assign the issue to me. I would like to work on it with python.Thank you!

**Comment by SKAUL05** [comment]
@sharanya02 Go Ahead with Hill Cipher in **Python**.

**Comment by SwagataJ** [comment]
Can I work on this in c++?

**Comment by vatsalkesarwani12** [comment]
@SwagataJ go with c++

**Comment by GajjarMiten** [comment]
Hey, @plazzy99 I would like to do it in Golang.

**Comment by vatsalkesarwani12** [comment]
@GajjarMiten go ahead with golang

**Comment by SangeetaMishra** [comment]
@plazzy99 I would like to work in C.

**Comment by vatsalkesarwani12** [comment]
@SangeetaMishra go with C
Happy Coding!!
