### ISSUE TITLE
Reverse of an array

### ISSUE THREAD

**Issue by yogitasaini** [HarshCasper/NeoAlgo#5493]
## 💥 Proposal

Example :-
 1.
 Input :  1 2 3 4 5 
 Output : 5 4 3 2 1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes)

**Comment by ankitaggarwal23** [comment]
Some one already working on this issue #5093
