### ISSUE TITLE
Bit Manipulation C++

### ISSUE THREAD

**Issue by JanhaviSoni** [HarshCasper/NeoAlgo#5503]
## 💥 Proposal

Find the only non repeating element in array where every element repeats twice

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Why two Issue for same problem #5311
