### ISSUE TITLE
Program to find the modulo of nth fibonacci number in an optimised way

### ISSUE THREAD

**Issue by shawavisek35** [HarshCasper/NeoAlgo#559]
## 💥 Proposal

Suggestion on adding a program

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**Program to find the modulo of nth fibonacci number where n is very large in an optimised way.**

**Comment by Mohitkumar6122** [comment]
I found an amazing way to calculate large fibonacci numbers. 
let f(n) be the (n + 1) th fibonacci number, we have two case: n is even and n is odd.

> f(2 * k) = f(k) * f(k) + f(k - 1) * f(k - 1)

> f(2 * k + 1) = f(k) * f(k + 1) + f(k - 1) * f(k)

There are only at most  states.
Let's divide n into groups by depth, you will realize a special property: Each depths only contains at most 4 values of n.

call f(1000):


Depth[0] : 1000 
Depth[1] : 499 500 
Depth[2] : 248 249 250 
Depth[3] : 123 124 125 
Depth[4] : 60 61 62 63 
Depth[5] : 29 30 31 32 
Depth[6] : 13 14 15 16 
Depth[7] : 5 6 7 8 
Depth[8] : 1 2 3 4 
Depth[9] : 0 1 2 
Depth[10] : 0 1 
call f(123123123122):


Depth[0] : 123123123122 
Depth[1] : 61561561560 61561561561 
Depth[2] : 30780780779 30780780780 30780780781 
Depth[3] : 15390390388 15390390389 15390390390 15390390391 
Depth[4] : 7695195193 7695195194 7695195195 7695195196 
Depth[5] : 3847597595 3847597596 3847597597 3847597598 
Depth[6] : 1923798796 1923798797 1923798798 1923798799 
Depth[7] : 961899397 961899398 961899399 961899400 
Depth[8] : 480949697 480949698 480949699 480949700 
Depth[9] : 240474847 240474848 240474849 240474850 
Depth[10] : 120237422 120237423 120237424 120237425 
Depth[11] : 60118710 60118711 60118712 60118713 
Depth[12] : 30059354 30059355 30059356 30059357 
Depth[13] : 15029676 15029677 15029678 15029679 
Depth[14] : 7514837 7514838 7514839 7514840 
Depth[15] : 3757417 3757418 3757419 3757420 
Depth[16] : 1878707 1878708 1878709 1878710 
Depth[17] : 939352 939353 939354 939355 
Depth[18] : 469675 469676 469677 469678 
Depth[19] : 234836 234837 234838 234839 
Depth[20] : 117417 117418 117419 117420 
Depth[21] : 58707 58708 58709 58710 
Depth[22] : 29352 29353 29354 29355 
Depth[23] : 14675 14676 14677 14678 
Depth[24] : 7336 7337 7338 7339 
Depth[25] : 3667 3668 3669 3670 
Depth[26] : 1832 1833 1834 1835 
Depth[27] : 915 916 917 918 
Depth[28] : 456 457 458 459 
Depth[29] : 227 228 229 230 
Depth[30] : 112 113 114 115 
Depth[31] : 55 56 57 58 
Depth[32] : 26 27 28 29 
Depth[33] : 12 13 14 15 
Depth[34] : 5 6 7 8 
Depth[35] : 1 2 3 4 
Depth[36] : 0 1 2 
Depth[37] : 0 1 
According to the amazing property, we can calculate 1018-th fibonacci number by using little code:
My code : https://ideone.com/KM2ACr
