### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by piyushgoell** [HarshCasper/NeoAlgo#563]
### Implementation of 
[Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Motivation
Asked in many Interview.

### Language Supported
 - C [@Yuvraj-kadale]
 - C++ [@piyushgoell]
 - Python [@pradeep98 ]
 - Java [@raksha009]
 - Go [@GajjarMiten]
 - JavaScript [@Nagasuruthika]
 - C# [@Patelkeviin]

**Comment by piyushgoell** [comment]
I would like to work on this in C++. @SKAUL05

**Comment by SKAUL05** [comment]
> I would like to work on this in C++. @SKAUL05

Go Ahead with CPP.

**Comment by pradeep98** [comment]
I would like to do in python. @SKAUL05

**Comment by Yuvraj-kadale** [comment]
I would like to make in C!

**Comment by SKAUL05** [comment]
Python : @pradeep98 
C : @Yuvraj-kadale

**Comment by raksha009** [comment]
Plz assign me this issue in java @SKAUL05

**Comment by PatelKeviin** [comment]
I would like to solve this problem in C# @SKAUL05. Thanks!

**Comment by GajjarMiten** [comment]
@SKAUL05 
I would like to do it in Golang.

**Comment by Nagasuruthika** [comment]
I'd like to take this issue in javascript.

**Comment by atarax665** [comment]
Assigning:
@raksha009 -> Java
@PatelKeviin -> C#
@GajjarMiten -> Golang
@Nagasuruthika -> JavaScript
You all can start working and don't forget to go through contribution guidelines #398 .
Happy Coding!

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
