### ISSUE TITLE
kth Largest / Smallest element in Unsorted array in C

### ISSUE THREAD

**Issue by CSAURABH** [HarshCasper/NeoAlgo#5662]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes

**Comment by samar08** [comment]
Hey I am a GSSOC participant and I want to code for this problem in Java. Pls assign this issue to me. Thank you.

**Comment by CSAURABH** [comment]
@samar08  create a new issue and do it in java

**Comment by samar08** [comment]
thank you
