### ISSUE TITLE
New features in NeoAlgo/Java/ds/linkedList.java 

### ISSUE THREAD

**Issue by nancy0119** [HarshCasper/NeoAlgo#5678]
## 🚀 Feature

I want to add several features such as printLinkedList(), getAt(), removeDuplicates() etc. to this LinkedList for making it more functional.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
 
I'm a GSSOC participant and want to contribute to this project diligently to the best I can.Please assign this issue to me.

## Pitch

These features should be implemented so that the LinkedList can become more functional and it would be easier to use. It will become easier for the user to just call the function and do the desired work.

**Comment by nancy0119** [comment]
**/assign**

**Comment by rohanbabbar04** [comment]
@nancy0119 It's working you can now try

**Comment by nancy0119** [comment]
Yahhh...Thank you

**Comment by ankitaggarwal23** [comment]
No need of such problems
