### ISSUE TITLE
Generate IP Addresses [Backtracking] | GSSOC'21

### ISSUE THREAD

**Issue by amaan-ahmad** [HarshCasper/NeoAlgo#5681]
## 💥 Proposal

Adding Generate IP addresses problem asked in Amazon.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
No need of such problems
