### ISSUE TITLE
GSSOC-Print LinkedList

### ISSUE THREAD

**Issue by nancy0119** [HarshCasper/NeoAlgo#5684]
## 💥 Proposal

Add the problem of printing the LinkedList in NeoAlgo/Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by nancy0119** [comment]
**/assign**

**Comment by ankitaggarwal23** [comment]
No need of such problem and problem also exists
