### ISSUE TITLE
C++ Maximum Width of the Binary tree - medium Level

### ISSUE THREAD

**Issue by shivanshugarg12800** [HarshCasper/NeoAlgo#5701]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes I have read all the contributing guidelines on Pull requests

## Motivation
It is a simple yet medium-level problem of the Binary tree that asks you to find the Maximum width of a binary tree given.

## Pitch
this problem surely will help many to understand how level-order traversal works and the implementation of a binary tree

**Comment by shivanshugarg12800** [comment]
@HarshCasper @ankitaggarwal23 I am assigning this issue to work under GSSOC'21
Please arrange to add the suitable labels to the issue

**Comment by ankitaggarwal23** [comment]
Problem already present #3656
