### ISSUE TITLE
Balanced Array

### ISSUE THREAD

**Issue by anshmishra010** [HarshCasper/NeoAlgo#5706]
## 🚀 Feature

 An array is balanced if the sum of the left half of the array elements is equal to the sum of right half.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I want to add in c++ in cp .

## Pitch

I want to add under GSSoC'21

**Comment by bhav09** [comment]
Merged.
