### ISSUE TITLE
Find 3 numbers whose sum is zero from a given array in O(n^2)[Optimized Way]

### ISSUE THREAD

**Issue by Jkp2072** [HarshCasper/NeoAlgo#578]
## 💥 Proposal

An Array is given as input ,we have to design an algorithm which will find all the possible combinations of 3 numbers whose sum results zero. 

example :
input = [1,-1,2,-2,0]
output = [[1,-1,0],[2,-2,0]]

I would like to do it in c++

@Kajol-Kumari  @HarshCasper  @Abhijit2505 

Assignees
CPP : @Jkp2072
JAVA: @prashansasaxena
Python: @Mohitkumar6122

**Comment by prashansasaxena** [comment]
I would like to do this in java

**Comment by Mohitkumar6122** [comment]
i would like to do this in python @Kajol-Kumari @SKAUL05 @Abhijit2505

**Comment by Huzaib** [comment]
If the implementation in java is open, please assign it to me

**Comment by Jkp2072** [comment]
please assign this issue @routrohan  @plazzy99  @Kajol-Kumari  @Abhijit2505

**Comment by Mohitkumar6122** [comment]
why cant i create a pull request of my commits ?

**Comment by kashika3101** [comment]
Please assign me this issue in C.
@Kajol-Kumari @plazzy99

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
