### ISSUE TITLE
Tree Sort In Java

### ISSUE THREAD

**Issue by Khushi-24** [HarshCasper/NeoAlgo#5784]
## 💥 Proposal

Implementing Tree Sort In Java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
