### ISSUE TITLE
Kth maximum and minimum number in C++

### ISSUE THREAD

**Issue by debjani1413** [HarshCasper/NeoAlgo#5840]
## 💥 Proposal

I would like to contribute to a C++ program that helps to find out the Kth maximum and minimum number in an array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I've read the Contribution Guidelines on Pull Requests

**Comment by NidhiChaurasia** [comment]
@debjani1413 Assign me this issue I would like to contribute in this particular question by using C++ language and some STL libraries.
