### ISSUE TITLE
Four sum

### ISSUE THREAD

**Issue by vedant-jain03** [HarshCasper/NeoAlgo#5846]
## 💥 Proposal

I want to add code in C-Plus-Plus

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes)

**Comment by vedant-jain03** [comment]
> /assign

You should make your own new issue

**Comment by NidhiChaurasia** [comment]
@vedant-jain03 Assign me this issue and I will get it's solution in C++ language using STL libraries and basic C++ functions.

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Assign me this issue and I will get it's solution in C++ language using STL libraries and basic C++ functions.

I am also participant you can maje your own new issue and assign yourself
I am already an assignee in this issue.
