### ISSUE TITLE
TARGET SUM TRIPLETS

### ISSUE THREAD

**Issue by NEEHITGOYAL** [HarshCasper/NeoAlgo#585]
## 💥 Proposal

Take as input N, the size of array. Take N more inputs and store that in an array. Take as input “target”, a number. Write a function which prints all triplets of numbers which sum to target.
For example
input:
9
5 7 9 1 2 4 6 8 3
10
output:
1, 2 and 7
1, 3 and 6
1, 4 and 5
2, 3 and 5
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Assignees
- C : @akanksha-saini
- C++ : @NEEHITGOYAL
- Python : @shubham5351
- Java: @anime19

**Comment by NEEHITGOYAL** [comment]
i would like to do it in c++  as a part of hakin codes
@Kajol-Kumari @SKAUL05 @Abhijit2505 @siddharth25pandey @routrohan @plazzy99

**Comment by shubham5351** [comment]
I would like to do this in python @SKAUL05  @Kajol-Kumari

**Comment by routrohan** [comment]
@NEEHITGOYAL you can proceed with this.

**Comment by routrohan** [comment]
@shubham5351 Please create another issue for the same problem and I'll put you up on that.

**Comment by NEEHITGOYAL** [comment]
@routrohan @SKAUL05 can you please add tags

**Comment by anime19** [comment]
I would like to take this issue in JAVA as partcipant at HakinCodes
Please assign it to me.

**Comment by akanksha-saini** [comment]
I would like to do it in c @SKAUL05 @Kajol-Kumari

**Comment by GajjarMiten** [comment]
Hey @SKAUL05 
I would like to do it in Golang

**Comment by pulkitgovrani** [comment]
I would like to do this in Javascript @SKAUL05

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
