### ISSUE TITLE
Red Black tree (CH20)

### ISSUE THREAD

**Issue by rutujadhanawade** [HarshCasper/NeoAlgo#588]
## 🚀 Feature

Creation and insertion & Deletion in [Red Black tree](https://en.wikipedia.org/wiki/Red%E2%80%93black_tree)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

It is a very useful algorithm. A red-black tree is a kind of self-balancing binary search tree

## Languages 
- C [@SangeetaMishra ]
- CPP [@rutujadhanawade]
- Java [@SangeetaMishra ]
- Python [@Yuvraj-kadale]
- JavaScript
- Go
- C#

**Comment by rutujadhanawade** [comment]
I would like to work on it with C++ .
@Kajol-Kumari @SKAUL05 @plazzy99 
Can you please assign the issue to me. Thank you!

**Comment by vgb-codes** [comment]
@rutujadhanawade go ahead with C++.
Please follow the contribution guidelines when submitting your contribution.

**Comment by rutujadhanawade** [comment]
Sure @VijayaGB98 .

**Comment by Yuvraj-kadale** [comment]
Would like to make in python

**Comment by vgb-codes** [comment]
@Yuvraj-kadale Go ahead with Python.
Please follow the contribution guidelines when submitting your contribution.

**Comment by SangeetaMishra** [comment]
@VijayaGB98 I would like to contribute in Java.

**Comment by vgb-codes** [comment]
@SangeetaMishra go ahead with Java.
Please follow the contribution guidelines when submitting your code.

**Comment by ahampriyanshu** [comment]
@VijayaGB98 Please assign this to me in Golang.

**Comment by SangeetaMishra** [comment]
@atarax665  Why is this issue closed? Only cpp code is submitted.

**Comment by SangeetaMishra** [comment]
@plazzy99  please add difficulty level.

**Comment by SangeetaMishra** [comment]
@siddharth25pandey  Please add CH20 label.

**Comment by vgb-codes** [comment]
@ahampriyanshu Go ahead with Golang.

**Comment by SangeetaMishra** [comment]
@siddharth25pandey  Is this part of CH20 ?

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey Is this part of CH20 ?

@SangeetaMishra Yes, Absolutely

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by SangeetaMishra** [comment]
@iamrajiv Please assign this to me in C.
