### ISSUE TITLE
Four Sum

### ISSUE THREAD

**Issue by Nidhideveloper** [HarshCasper/NeoAlgo#5897]
## 🚀 Feature

Four numbers sum up to a target value.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

This is a hard problem and involves a good and sound concept of algorithm for reducing the complexity form the brute force approach.

## Pitch

This is a hard problem and involves a good and sound concept of algorithm for reducing the complexity form the brute force approach.

**Comment by Nidhideveloper** [comment]
I am gssoc21 participant plz assign this to me in java.

**Comment by ankitaggarwal23** [comment]
Problem already working by other person #5846
