### ISSUE TITLE
Sum of smallest elements in all subarrays. [CH20]

### ISSUE THREAD

**Issue by pradeep98** [HarshCasper/NeoAlgo#590]
## 🚀 Feature

Statement: Given an integer array. Find sum of the smallest values in all possible contiguous subarrays.
ex- [4,1,3] 
&emsp; sub arrays:  [4], [1], [3], [4,1], [1,3], [4,1,3].
 &emsp; &emsp; &emsp; sum = 4 + 1 + 3 + 1 + 1 + 1 = 11

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
This is a classic monotonic stack problem.

## Languages Supported
C [@raksha009]
C++ [@ag278]
Python [@pradeep98 ]
Java [@viveksahu26]
JavaScript
C#

**Comment by pradeep98** [comment]
I would like to implement it in Python.

**Comment by ag278** [comment]
I would like to solve this issue in c++

**Comment by viveksahu26** [comment]
I would like to work with this issue in java..

**Comment by raksha009** [comment]
I would like to work on this issue in C.

**Comment by vinaykumar7686** [comment]
I would like to work on Python for this issue.

**Comment by SKAUL05** [comment]
> I would like to work on Python for this issue.

@pradeep98 requested it before

**Comment by akanksha-saini** [comment]
I would like to do in JavaScript @SKAUL05

**Comment by pulkitgovrani** [comment]
I would like to do this in Javascript @SKAUL05

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
