### ISSUE TITLE
DNF Sort in C-plus-plus

### ISSUE THREAD

**Issue by saumya01-tech** [HarshCasper/NeoAlgo#5915]
## 💥 Proposal

Given an array of 0's,1's, and 2's, the sorting algorithm sorts them in the order where, first all 0's, then 1's, and lastly all 2's.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Problem already present [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp)
