### ISSUE TITLE
Add a C Style Documentation

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#592]
## 📚 Documentation

Create a C Style Guide Documentation in the specific `C`  Directory which serves the following purpose: 

- Acquaint the User about the C Styles Guide and what are the best practices to follow.
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in C Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by NEEHITGOYAL** [comment]
i would like to work on this issue 
if possible can u give any reference or i ll find it myself
@HarshCasper @SKAUL05 @Kajol-Kumari

**Comment by HarshCasper** [comment]
Assigned to you @NEEHITGOYAL
