### ISSUE TITLE
Add a Java Style Documentation

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#593]
## 📚 Documentation

Create a Java Style Guide Documentation in the specific `Java`  Directory which serves the following purpose: 

- Acquaint the User about the Java Styles Guide and what are the best practices to follow.
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in Java Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by nutanaarohi123** [comment]
I would like to work on this.Pls assign

**Comment by ritvij14** [comment]
I would like to contribute to this.

**Comment by GrayFlash** [comment]
I would like to work on it. If available please assign it to me.
