### ISSUE TITLE
Add a Javascript Style Documentation

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/NeoAlgo#594]
## 📚 Documentation

Create a Javascript Style Guide Documentation in the specific `Javascript`  Directory which serves the following purpose: 

- Acquaint the User about the Javascript Styles Guide and what are the best practices to follow.
- Mention about Code Width and Alignment, a proper convention to add Whitespaces and Indentation.
- Mention about Variable Naming Conventions and various best practices followed in Javascript Programming.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AkiraBrand** [comment]
Hey there, 
I'd like to work on the style guide. Is it still needed? 
Thanks,
Akira

**Comment by HarshCasper** [comment]
Hello @AkiraBrand 

This Issue is specific to Contributor's Hack 2020 Participants. If you would like to work on this, we will assign it to you separately.

**Comment by shraddhavp** [comment]
Would like to work on the issue

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
