### ISSUE TITLE
Word Ladder Problem in C++

### ISSUE THREAD

**Issue by Bhawana0001** [HarshCasper/NeoAlgo#5996]
## 💥 Proposal

Code for Word ladder problem in C++
It is graph-based problem.

Problem Statement:
Given two strings as startWord and endWord and,
Given a  list of n words (s1 -> s2 -> s3------>sn)such that:
1. Every adjacent pair of words differ by a single letter.
2. StartWord may note be present in the List 
3. Sn==endWord

Find the number of words in the shortest sequence from startWord to endWord, or 0 if no such sequence exists.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by vi-hna-ja** [comment]
@Bhawana0001 I just tried checking the command because it seems there has been an issue with it. You can close this issue and open a new one.
