### ISSUE TITLE
worst fit algorithm in c || memory allocation || c || arrays

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/NeoAlgo#6005]
## 🚀 Feature

simulation of worst fit algorithm in c

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

simulation of worst fit in c 

## Pitch

simulation of worst fit algorithm in  c

**Comment by ankitaggarwal23** [comment]
Already someone is working on it #5933
