### ISSUE TITLE
Lowest Common Ancestor with Binary Lifting

### ISSUE THREAD

**Issue by SangeetaMishra** [HarshCasper/NeoAlgo#601]
## 🚀 Feature

You are given a tree G and queries of the form (v1,v2). For each query, you need to find the lowest common ancestor, i.e. a vertex v that lies on the path from the root to v1 and the path from the root to v2, and the vertex should be the lowest.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

As it has not been added in any issue in Hakin Codes.

## Pitch

A common algorithm of trees.

**Comment by SangeetaMishra** [comment]
Please assign this issue to me for C++ as a part of Hackin Codes @Kajol-Kumari  @HarshCasper @atarax665 @SKAUL05

**Comment by ritvij14** [comment]
I would like to take this issue in Java for HakinCodes.
