### ISSUE TITLE
Sliding Window Technique

### ISSUE THREAD

**Issue by devanshiv123** [HarshCasper/NeoAlgo#605]
## 🚀 Feature

Addition of some problems related to Sliding Window Technique.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

The technique is used to solve many problems.

**Comment by devanshiv123** [comment]
I would like to work in C++.

**Comment by atarax665** [comment]
Duplicate issue. Refer to #452 .
