### ISSUE TITLE
Implement next greater element using stack in C++

### ISSUE THREAD

**Issue by chandankrsahu** [HarshCasper/NeoAlgo#609]
## 🚀 Feature

Implement next greater element using stack in C++ under stack directory in c++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by chandankrsahu** [comment]
I want to contribute as a part of HackinCodes 2020. @Kajol-Kumari  @Abhijit2505

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java.

**Comment by yashaswibiyahut** [comment]
I want to work on this issue using C++ as a part of HakinCodes, Please assign me with this issue. @Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99

**Comment by yashaswibiyahut** [comment]
kindly see the comments and assign me with this issue. @Kajol-Kumari @SKAUL05 @siddharth25pandey  @iamrajiv
