### ISSUE TITLE
Target Sum Triplets

### ISSUE THREAD

**Issue by shubham5351** [HarshCasper/NeoAlgo#610]
💥 Proposal

Take as input N, the size of array. Take N more inputs and store that in an array. Take as input “target”, a number. Write a function which prints all triplets of numbers which sum to target.
For example
input:
9
5 7 9 1 2 4 6 8 3
10
output:
1, 2 and 7
1, 3 and 6
1, 4 and 5
2, 3 and 5

**Comment by shubham5351** [comment]
I would like to work for this issue in python

**Comment by vgb-codes** [comment]
Issue #585 Duplicate Issue. Therefore, I am going to close this thread.
