### ISSUE TITLE
Design a stack which gets the minimum element in O(1) time

### ISSUE THREAD

**Issue by rahulpathak-github** [HarshCasper/NeoAlgo#615]
## 🚀 Feature

**Design a stack which executes pop(), push(), top(), getMinimum() all in O(1) time.**
(CH20 Participation)

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
YES
(Write your answer here.)

## Motivation

The problem is interesting and based on stack which many people find an easy data structure.

(Please outline the motivation for the proposal.)

## Pitch

This problem is intriguing and a good interview problem as it is based on stack which is usually considered an easy data structure to master. Therefore, it will help people preparing for an interview.

(Please explain why this feature should be implemented and how it would be used.)

**Comment by rahulpathak-github** [comment]
@SKAUL05 @HarshCasper @plazzy99 I wish to work on this issue in C++, therefore, request you to assign me this issue.

**Comment by ag278** [comment]
I would like to work on this issue in C language. Please assign me this issue

**Comment by ritvij14** [comment]
I would like to work on this issue in Java.

**Comment by yogesh-kansal** [comment]
I would like to work on this issue in c++.

**Comment by PatelKeviin** [comment]
I would like to work on this issue in Python. Please assign me, thanks!

**Comment by imPGupta** [comment]
I would like contribute in C or C++. Assign me

**Comment by Sidhant-Gupta** [comment]
I'll like to take this issue in cpp.
