### ISSUE TITLE
Backtracking algorithm

### ISSUE THREAD

**Issue by rgrupesh** [HarshCasper/NeoAlgo#622]
## 🚀 Feature

(Sudoku solver with backtracking.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Yes.)

## Motivation

(Backtracking algorithm can be implemented with just 3 simple functions.)

## Pitch

(Sudoku solving can be cumbersome at times. This algorithm makes it really easy.)

## Assignees 

- Python: @rgrupesh
- C++: @yashaswibiyahut

**Comment by rgrupesh** [comment]
I would like to work in Python @siddharth25pandey

**Comment by yashaswibiyahut** [comment]
I want to work on this issue using C++ as a part of HakinCodes, Please assign me with this issue. @Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99

**Comment by Huzaib** [comment]
I want to do it in Java
Please assign it to me

**Comment by TEJASWI-TEJASWI** [comment]
I want to work on this issue using C++ as a part of HakinCodes, Please assign me with this issue. @Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99

**Comment by yashaswibiyahut** [comment]
kindly see the comments and assign me with this issue. @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv
