### ISSUE TITLE
Max Min Problem

### ISSUE THREAD

**Issue by SalmaZakaria** [HarshCasper/NeoAlgo#6230]
## 💥 Proposal
You will be given a list of integers and a single integer. You must create an array of length N from elements of that array such that its unfairness is minimized, in C++

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

I am GSSOC'21 Participant

**Comment by SalmaZakaria** [comment]
I have made a PR yesterday
What is the meaning of this issue?
@ANUJAGRAWAL2000

**Comment by aman7100** [comment]
i want to solve the issue using c++.kindly assign me
