### ISSUE TITLE
Check String Anagram

### ISSUE THREAD

**Issue by yogitasaini** [HarshCasper/NeoAlgo#6260]
## 💥 Proposal

Example of Anagram words:-
1. listen - silent

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes.)

**Comment by iamvs-2002** [comment]
Respected mentors, Kindly allow me to work on this issue in Java.
