### ISSUE TITLE
Egg Dropping Problem in Cpp

### ISSUE THREAD

**Issue by shubhii0206** [HarshCasper/NeoAlgo#6274]
## 💥 Proposal

I want to add a code for the egg dropping problem in cpp. It is a hard level, Dynamic Programming Problem.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by Bharati2612** [comment]
Could you plz assign this to me

**Comment by anshmishra010** [comment]
it is automatically assigned to you

**Comment by ankitaggarwal23** [comment]
Problem already present #1551

**Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.**
