### ISSUE TITLE
Longest Palindromic Substring 

### ISSUE THREAD

**Issue by devanshiv123** [HarshCasper/NeoAlgo#632]
## 🚀 Feature

Efficient Algorithm for Longest Palindromic Substring problem.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

The question found in many contests and interview series.

## Assignees 

- C++: @devanshiv123 
- Java: @Huzaib 
- C: @kashika3101
- Python: @narayan2111

**Comment by devanshiv123** [comment]
I would like to work in C++.

**Comment by Huzaib** [comment]
I want to do it in Java.
Please assign it to me.

**Comment by TEJASWI-TEJASWI** [comment]
Hi everyone could anyone pls assign this in c++ to me as a part of Hakincodes
@Abhijit2505 @Kajol-Kumari @siddharth25pandey @plazzy99

**Comment by kashika3101** [comment]
I would like to work on this issue in C++/C
Please assign it to me.

**Comment by yashsahay25** [comment]
I would like to do it in C. Kindly assign it to me.

**Comment by narayan2111** [comment]
i would like to work on this issue in python @HarshCasper @plazzy99 @atarax665 @Abhijit2505 @iamrajiv

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
