### ISSUE TITLE
README File of the Python Folder Modification.

### ISSUE THREAD

**Issue by anishsingh42** [HarshCasper/NeoAlgo#6321]
## 💥 Proposal

The README.md file of python folder needs to be updated.
The README file is not containing all the programs that are under the sub-folders, on addition to this few programs are added to the wrong title (example: Data structure programs are added under graphs section) and there are 2 sections for searching, sorting, graphs and competitive programming and programs are added twice because of this reason.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by ankitaggarwal23** [comment]
Actually no need we are already rename and fixing all this issue.

**Comment by anishsingh42** [comment]
@ankitaggarwal23 I have already updated the readme file . If you can check once. Pull request #6322. 
Thank you in anticipation.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 I have already updated the readme file . If you can check once. Pull request #6322.
> Thank you in anticipation.

No you did only for python we already working for all the files almost done just we have to push the changes.
