### ISSUE TITLE
Prefix Sum of Matrix

### ISSUE THREAD

**Issue by U-c0de** [HarshCasper/NeoAlgo#6324]
## 💥 Proposal

A CP algorithm of 2D matrix even used in placement questions, I want to add the algorithm in C++ and Python.
Do assign me this issue  so I can add more to NeoAlgo.

Yes I have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**Comment by iamvs-2002** [comment]
Respected Mentors, kindly assign me this issue in Java.

**Comment by U-c0de** [comment]
https://github.com/TesseractCoding/NeoAlgo/pull/6341#issue-620293235
Pull request Done

**Comment by U-c0de** [comment]
> This issue [has been assigned](https://github.com/TesseractCoding/NeoAlgo/issues/6324#issuecomment-823839927) to @U-c0de!
> It will become unassigned if it isn't closed within 21 days. A maintainer can also add the **pinned** label to prevent it from being unassigned.

**Comment by U-c0de** [comment]
# #6341 Done
