### ISSUE TITLE
Updating the code to take input from user in Java

### ISSUE THREAD

**Issue by ymaheshwari1** [HarshCasper/NeoAlgo#633]
## 🚀 Feature

Currently, we are using hard-coded array values for running the RemoveDuplicateElementWithoutExtraSpace.java and RemoveDuplicateElement.java. We should update the code so that the user is able to define the length of the array and also the values for the array

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by atarax665** [comment]
@ymaheshwari1 Sure, you can refactor the code of above mentioned files.

**Comment by ymaheshwari1** [comment]
@atarax665 Please add appropriate labels on the issue **CH20** and the difficulty label

**Comment by ymaheshwari1** [comment]
@atarax665 Please add the CH20 so that the issue will be counted in the Contributor's Hack and also add the difficulty label.

**Comment by ymaheshwari1** [comment]
@iamrajiv Please label the issue

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
