### ISSUE TITLE
Next prime number

### ISSUE THREAD

**Issue by tanvi355** [HarshCasper/NeoAlgo#6343]
## 💥 Proposal

C++ program to find the next prime number of a given number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by iamvs-2002** [comment]
Respected mentors, may I implement the same in Java?
