### ISSUE TITLE
Merge Sort In Dart

### ISSUE THREAD

**Issue by nitinshukla413** [HarshCasper/NeoAlgo#6347]
## 💥 Proposal

Implementation of Quick Sort in Dart.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Problem already done by someone else #6149
