### ISSUE TITLE
Print count of prime numbers in given range a and b for test cases Q.

### ISSUE THREAD

**Issue by akanksha-saini** [HarshCasper/NeoAlgo#636]
## 🚀 Feature

Count prime numbers between given range using **Prime Sieve**. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

The solution can be implemented using cumulative count of prime numbers up to a large range.
An optimized approach to return prime numbers as it don't call prime sieve function for each test case. Therefore, solution is of complexity O( Q + (n log log n).

## Pitch

This solution works for large test cases (up to 1000) and range up to 10^5.

**Comment by akanksha-saini** [comment]
I would like to contribute in C++ for HakinCodes 2020 @SKAUL05 @Kajol-Kumari

**Comment by siddharth25pandey** [comment]
## This issue is not the part of HakinCodes Contributors' Hack 2020

**Comment by akanksha-saini** [comment]
Code is correct and can be merged as it do not affect other files of master branch, so can't you add CH20 label to it. @SKAUL05 @Kajol-Kumari @siddharth25pandey @Abhijit2505

**Comment by siddharth25pandey** [comment]
> Code is correct and can be merged as it do not affect other files of master branch, so can't you add CH20 label to it. @SKAUL05 @Kajol-Kumari @siddharth25pandey @Abhijit2505

@akanksha-saini **Every issue, which is created here cannot be the part of Contributor's Hack 2020. It should follow some guidelines. it's not like that you just created an issue, send the PR and we will merge it**.
