### ISSUE TITLE
Ackermann function in javascript

### ISSUE THREAD

**Issue by satcasm** [HarshCasper/NeoAlgo#6371]
## 💥 Proposal

Ackermann function in javascript

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by ankitaggarwal23** [comment]
Read the instructions mentioned on Gssoc discord yesterday.
