### ISSUE TITLE
first fit , best fit, worst fit memory allocation algorithms in java , python

### ISSUE THREAD

**Issue by aaadddiii** [HarshCasper/NeoAlgo#6388]
## 🚀 Feature

Program to implement first fit , best fit , worst fit memory allocation algorithms in java and python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

To implement first fit, best fit , worst fit memory allocation algorithms in java and python

## Pitch

To implement first fit, best fit , worst fit memory allocation algorithms in java and python

**Comment by ankitaggarwal23** [comment]
Already 2 issue open closing this issue now
