### ISSUE TITLE
Sum of Root To Leaf Binary Numbers in C++

### ISSUE THREAD

**Issue by kotwani2883** [HarshCasper/NeoAlgo#6439]
## 💥 Proposal
Given the root of a binary tree where each node has a value 0 or 1.  Each root-to-leaf path represents a binary number starting with the most significant bit. For all leaves in the tree, consider the numbers represented by the path from the root to that leaf.
Return the sum of these numbers. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by kotwani2883** [comment]
Kindly Assign this to me as a part of GSSOC'21

**Comment by kotwani2883** [comment]
@ankitaggarwal23 can I do this question .. Will it be come under DS .. Kindly Confirm

**Comment by ankitaggarwal23** [comment]
Yes You can work!
