### ISSUE TITLE
Knapsack Problem

### ISSUE THREAD

**Issue by Mohitkumar6122** [HarshCasper/NeoAlgo#647]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
**YES**

## Motivation

Dynamic programming is used where we have problems, which can be divided into similar sub-problems, so that their results can be re-used. Mostly, these algorithms are used for optimization. Before solving the in-hand sub-problem, dynamic algorithm will try to examine the results of the previously solved sub-problems and knapsack problem is example of DP

**Comment by Mohitkumar6122** [comment]
i would like to do this in python @Kajol-Kumari @SKAUL05 @Abhijit2505

**Comment by ritvij14** [comment]
I would like to contribute to this issue in Java as a part of HakinCodes.

**Comment by atarax665** [comment]
This is a duplicate issue. @ritvij14 @Mohitkumar6122 Please checkout #423
