### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by atarax665** [HarshCasper/NeoAlgo#648]
## 🚀 Feature

**Heap Sort Implementation**
-Heap sort is a comparison based sorting technique based on Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end. We repeat the same process for remaining element.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Heap sort is one of the basic sorting algorithm.  Its time complexity is O(nlogn).

## Pitch

Heap sort algorithm has limited uses because Quicksort and Mergesort are better in practice. Nevertheless, the Heap data structure itself is enormously used. Heap sort can be used in problems like where we need to sort almost sorted array and so on.

## Languages Supported:
- C [@rgrupesh]
- CPP [@bagladivyang03]
- Python [@avinashkranjan]
- Java [@ritvij14 ]
- JavaScript [@nagasuruthika]
- C# 
- GO [@GajjarMiten ]

**Comment by bagladivyang03** [comment]
I would like to do in c++ pls assign @atarax665

**Comment by atarax665** [comment]
@bagladivyang03 You can start working on this in C++.
Happy Coding!

**Comment by rgrupesh** [comment]
I want to work in C. @atarax665

**Comment by avinashkranjan** [comment]
I would like to work on this issue in python @atarax665

**Comment by atarax665** [comment]
@rgrupesh You can start working in C.
@avinashkranjan You can work on this issue in Python.
Go through the contribution guidelines if you haven't yet. #398 
Happy Coding!

**Comment by avinashkranjan** [comment]
@atarax665 you already have a **heap_sort.py** in `NeoAlgo/Python/sort/..` Do you still me to push my verison of code??

**Comment by ritvij14** [comment]
@atarax665 is this included for Contributor's Hack? I would like to do this in Java

Also please put CH20 tag if it is being considered for it.

**Comment by atarax665** [comment]
> @atarax665 you already have a **heap_sort.py** in `NeoAlgo/Python/sort/..` Do you still me to push my verison of code??

@avinashkranjan I want you to modify the existing heap_sort.py file as the existing code doesn't have driver code, proper documentation and functions need to be refactored.

**Comment by avinashkranjan** [comment]
> > @atarax665 you already have a **heap_sort.py** in `NeoAlgo/Python/sort/..` Do you still me to push my verison of code??
> 
> @avinashkranjan I want you to modify the existing heap_sort.py file as the existing code doesn't have driver code, proper documentation and functions need to be refactored.

Okay..I'll make the required changes..

**Comment by avinashkranjan** [comment]
@atarax665 Made the changes, Have a look

**Comment by GajjarMiten** [comment]
Hey @atarax665 
I would like to it in Golang.

**Comment by Nagasuruthika** [comment]
Hey, @atarax665 I'd like this to take this issue in javascript.

**Comment by bagladivyang03** [comment]
Hey , @atarax665 Pls review the pr #666 that i have completed the heap sort in C++

**Comment by siddharth25pandey** [comment]
> @atarax665 is this included for Contributor's Hack? I would like to do this in Java
> 
> Also please put CH20 tag if it is being considered for it.

@ritvij14 Go ahead

**Comment by siddharth25pandey** [comment]
> Hey @atarax665
> I would like to it in Golang.

@GajjarMiten Go ahead

**Comment by siddharth25pandey** [comment]
> Hey, @atarax665 I'd like this to take this issue in javascript.

@Nagasuruthika Go ahead

**Comment by ritvij14** [comment]
@siddharth25pandey could you also put a difficulty tag on this issue? It will help all the assigned contributors to keep track of their progress.

**Comment by prasadvpatil** [comment]
I would like to work on this issue in C @atarax665

**Comment by ritvij14** [comment]
@atarax665 @iamrajiv please add a difficulty label to this issue.
