### ISSUE TITLE
Add Lee's Algorithm in C++ to find shortest path in maze

### ISSUE THREAD

**Issue by ArchishmanSengupta** [HarshCasper/NeoAlgo#6517]
## 💥 Proposal

I propose to add Lee's Algorithm in 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

(Write your answer here.)

I propose to add Lee Algorithm which is use to find the shortest path in a maze.

Real Life Applications:

Maze Game
Solving Rubik's Cube faster
Map Technology
Social Network

I will add proper description, will update the readme in C-plus-plus.

**Comment by Suvraneel** [comment]
@ankitaggarwal23  Can you re open this up? Or do I make another issue?
