### ISSUE TITLE
Replace PI

### ISSUE THREAD

**Issue by tanyagupta0201** [HarshCasper/NeoAlgo#6527]
Explanation:

Given a string. Replace all the occurences of pi with its value (the value of pi is 3.14).

Example:

inputted string = kipipi , output string = ki3.143.14
inputted string = jopirty , output string = jo3.14rty
inputted string = xyz , output string= xyz
I will code this problem in C++ with proper test cases and comments  and contribute to GSSOC. I have read the contributing Guidelines.
Please /assign this problem to me.

**Comment by tanyagupta0201** [comment]
Thank You for assigning me this issue.

**Comment by ankitaggarwal23** [comment]
Problem already present #2901
