### ISSUE TITLE
Lexicographic Rank of a string in C++

### ISSUE THREAD

**Issue by AparnaJuhi** [HarshCasper/NeoAlgo#6539]
I want to work on this issue- which will be used to find the lexicographic rank of a string.  Like the lexicographic rank of string -'aparna' is  78.

**Comment by AparnaJuhi** [comment]
I have generated a PR four days ago. Please review it. @siddharth25pandey

**Comment by siddharth25pandey** [comment]
@AparnaJuhi Link the PR here.

**Comment by AparnaJuhi** [comment]
> @AparnaJuhi Link the PR here.

https://github.com/TesseractCoding/NeoAlgo/pull/6540

**Comment by AparnaJuhi** [comment]
@siddharth25pandey  the link to the pr is https://github.com/TesseractCoding/NeoAlgo/pull/6540
