### ISSUE TITLE
M-coloring Problem

### ISSUE THREAD

**Issue by vanshikachokhani** [HarshCasper/NeoAlgo#6568]
## 🚀 Feature

If we are given an undirected graph and we need to determine if the graph can be colored with at most m no. of different colors such that no two adjacent vertices of the graph are colored with same color. Here coloring of graph means assigning a color to every node of the gaph. Return true if possible else return false.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

I will contribute the code in C++.

**Comment by U-c0de** [comment]
will contribute the code in Python.

**Comment by shubhidua** [comment]
I would like to contribute to the above problem in java as I am a participant of GSSOC'21. Kindly assign this to me.
