### ISSUE TITLE
Implementation of Array Mirror Inverse 

### ISSUE THREAD

**Issue by TEJASWI-TEJASWI** [HarshCasper/NeoAlgo#661]
## 🚀 Feature
Implementation of Array Mirror Inverse
- Inverse of an array means if the array elements are swapped with their corresponding indices and the array is called mirror-inverse if it's inverse is equal to itself .

### Have you read the [Contributing Guidelines on Pull Requests]

- Yes.

## Motivation
- This is a very important concept according to me and I think in first sight many   
of us think this is similar to palindrome concept but it's not.
## Pitch
- This will help to understand the algorithm better and it will reduce the time complexity of it also.

assignees:
c++: @TEJASWI-TEJASWI
java: @Himanshu44626748 
python : @narayan2111 
c: @SangeetaMishra

**Comment by TEJASWI-TEJASWI** [comment]
I want to work on this issue using C++ as a part of HakinCodes, Please assign me with this issue. @Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99

**Comment by narayan2111** [comment]
I would like to work on this issue in python. Please assign this to me.

**Comment by Himanshu44626748** [comment]
@siddharth25pandey @Kajol-Kumari I would like to do this in java. Please assign me.

**Comment by TEJASWI-TEJASWI** [comment]
i would like to work on this issue in c++ as part of hakin codes
@SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you assign this to me in C.

**Comment by SangeetaMishra** [comment]
@iamrajiv Added code for C

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you please add the difficulty level?

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
