### ISSUE TITLE
 Application of euler's Totient function

### ISSUE THREAD

**Issue by ag278** [HarshCasper/NeoAlgo#663]
## 🚀 Feature
Take a input n from the user. My algorithm will find out all the co prime pairs from 1 to n in nlogn time complexity
Example n=6
then the output would be 12 as the co prime pairs will be (1,1),(1,2),(1,3),(1,4),(1,5),(1,6),(2,3),(2,5),(3,4),(3,5),(4,5),(5,6)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

In general this question can be solved in n^2 time complexity but using the concept of euler's totient function this question can be done in nlog(n) time complexity
I would like to solve this issue as a part of CH20

## Assignees 

- @ag278: C++
- @kushagraiitbbs : C
- @kritikaparmar-programmer - Python
- @sahanabalappa - Java

**Comment by ag278** [comment]
@SKAUL05 @atarax665 @iamrajiv  i would like to implement this issue in c++ language. Please assign me this issue

**Comment by kushagraiitbbs** [comment]
@atarax665 Sir, I would like to contribute this issue in C language

**Comment by kritikaparmar-programmer** [comment]
Can I do this in python..? I want to work on it..

**Comment by sahanabalappa** [comment]
I would like to contribute this issue in Java language

**Comment by ag278** [comment]
@iamrajiv @SKAUL05 @siddharth25pandey @plazzy99 please have a look at my issue

**Comment by ag278** [comment]
@HarshCasper @iamrajiv @atarax665 could you please add CH20 and level tag for the issue
