### ISSUE TITLE
Manacher's Algorithm

### ISSUE THREAD

**Issue by SangeetaMishra** [HarshCasper/NeoAlgo#667]
## 🚀 Feature

Given string s with length n. Find all the pairs (i,j) such that substring s[i…j] is a palindrome. This has to be done in O(N).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

As it has not been added in any issue in Hakin Codes.

## Pitch

Important advanced algorithm

Assignees:
C: @SangeetaMishra 
C++: @SangeetaMishra 
Java: @ritvij14 
Python: @sahanabalappa
JavaScript: @ritvij14 
Go:
C#:

**Comment by SangeetaMishra** [comment]
Please assign this issue to me for C++ as a part of Hackin Codes @Kajol-Kumari @HarshCasper @atarax665 @SKAUL05

**Comment by ritvij14** [comment]
I would like to take this up in Java.

**Comment by sahanabalappa** [comment]
I would like to take up in python

**Comment by kritikaparmar-programmer** [comment]
I would like to do in C.. @SKAUL05  Please assign me

**Comment by avinashkranjan** [comment]
I would like work on this issue in JavaScript.. @SKAUL05 Please assign me

**Comment by SangeetaMishra** [comment]
@atarax665  @iamrajiv Solved it in C++
Can you assign it to me for C as well

**Comment by iamrajiv** [comment]
@SangeetaMishra Go ahead with C.

**Comment by SangeetaMishra** [comment]
@iamrajiv Solve it in C. Please review it.

**Comment by ritvij14** [comment]
@iamrajiv I would also like to do this in Javascript for CH20. Can I submit a PR, as I am still assigned? Nobody has taken for Javascript.

**Comment by iamrajiv** [comment]
@ritvij14 Sure.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
