### ISSUE TITLE
Implementation Randomized algorithms for searching

### ISSUE THREAD

**Issue by sparkingdark** [HarshCasper/NeoAlgo#67]
**Algorithm: Random search Algorithm** 
- Monte carlo algorithm
- Las Vegas algorithm

[random search](https://en.wikipedia.org/wiki/Random_search)

**Languages Supported:**
- C
- C++
- C#
- javascript
- java
- python
- go
- dart

**Comment by mar-galho** [comment]
Hi! Will you be doing this for any language?

**Comment by sparkingdark** [comment]
# C and python if possible

**Comment by mar-galho** [comment]
Alright, game on!

**Comment by sparkingdark** [comment]
Yeah let's do it @ricardoprins
