### ISSUE TITLE
Kosaraju's Algorithm(Graphs)

### ISSUE THREAD

**Issue by devanshiv123** [HarshCasper/NeoAlgo#670]
## 🚀 Feature
Kosaraju's Algorithm is used to find Strongly Connected Components in a Directed Graph.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch
We can find Strongly Connected Components of a directed graph in O(V+E) time complexity using this algorithm.

Assignees:
C: @avinashkranjan
C++: @devanshiv123
Java: @sahanabalappa
Python: @kritikaparmar-programmer
JavaScript: @sanskarvijpuria
Go:
C#:

**Comment by devanshiv123** [comment]
Please assign this issue to me in C++ @HarshCasper @SKAUL05  @Kajol-Kumari

**Comment by sahanabalappa** [comment]
Please assign this issue to me in java

**Comment by iamrajiv** [comment]
@devanshiv123 Go ahead with C++ and @sahanabalappa Go ahead with Java.

**Comment by kritikaparmar-programmer** [comment]
Please assign this issue to me, I would like to do in Python..

**Comment by avinashkranjan** [comment]
I'd like to work on this issue using C.. 
@iamrajiv if you could assign me, that'd be great

**Comment by iamrajiv** [comment]
@kritikaparmar-programmer Go ahead with Python.

**Comment by iamrajiv** [comment]
@avinashkranjan Go ahead with C.

**Comment by sanskarvijpuria** [comment]
Please assign me this, I want to work on this in javascript.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
