### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by AparnaJha17** [HarshCasper/NeoAlgo#6709]
## 💥 Proposal

The program will accept a sudoku puzzle from the user and will print its solution if it is solvable in C++ language.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by AparnaJha17** [comment]
In which folder should I add the code for recursion?
@ankitaggarwal23

**Comment by ankitaggarwal23** [comment]
We don't accept such code
