### ISSUE TITLE
LCM in C

### ISSUE THREAD

**Issue by TechSpiritSS** [HarshCasper/NeoAlgo#6711]
## 💥 Proposal

There is no LCM Code in Maths C but HCF is present, so I am writing a code for LCM

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by ankitaggarwal23** [comment]
We don't accept such code. It falls neither as a Data Structure not as an algorithm. and yes the one is present we are removing that as well
