### ISSUE TITLE
Valid Parentheses

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#673]
## 💥 Proposal

An input string is valid if:
1.Open brackets must be closed by the same type of brackets.
2.Open brackets must be closed in the correct order.
3.If string is empty.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

I would like to contribute a code for competitive programming section. 
Plz assign me this issue for Java and C++ @iamrajiv @Kajol-Kumari

**Comment by muddhit** [comment]
An input string is valid if:
1.Open brackets must be closed by the same type of brackets.
2.Open brackets must be closed in the correct order.
3.If string is empty.
I have read the contributing guidelines on pull requests.
I would like to contribute a code for competitive programming section.
Plz assign me this issue for Java and C++

**Comment by Huzaib** [comment]
Can I take this up??

**Comment by shobhu98** [comment]
Can  I complete this in Java?

**Comment by Huzaib** [comment]
I was also asking for java , sorry forgot to mention that.

**Comment by shobhu98** [comment]
No issues you can take in Java

**Comment by raksha009** [comment]
@Kajol-Kumari @SKAUL05 plz assign and look into this issue

**Comment by siddharth25pandey** [comment]
@raksha009 This issue is  already exist [here](https://github.com/TesseractCoding/NeoAlgo/issues/488).
Before creating an issue please check its pre-existence.
Thanks!
