### ISSUE TITLE
💡 New Language: `Nim`

### ISSUE THREAD

**Issue by nandgator** [HarshCasper/NeoAlgo#6741]
## 💥 Proposal

Solve algorithms in [Nim](https://github.com/nim-lang/Nim/).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

- [X] Yes

**Comment by nandgator** [comment]
Hey, @TesseractCoding I've already started my work, here's a glimpse:

![image](https://user-images.githubusercontent.com/38415384/116807384-9b874900-ab50-11eb-9428-e12d6e7715a9.png)

```diff
+ New language
+ New branch 'nim'
+ New folder '/Nim'
+ Sub folders based on category of problems
``` 

---
---

**`~/Nim/README.md (trunc.)`**

# Nilgorithms

Algorithms implemented in [Nim](https://nim-lang.org/) :crown:.

## Prologue

Hey there if you've stumbledcategories on this file blame your inquisitiveness. Just kidding :joy: !

Welcome to `~/NeoAgo/Nim`. It's most likely that you've not heard of Nim (if you have, please [jump in](#contributing)) and that you're interested to learn about this language.

Cool then grab a coffee and...

- If you've very little programming experience go to: https://narimiran.github.io/nim-basics/
- If you know other programming languages hop on to: https://github.com/nim-lang/Nim/wiki#nim-for-x-programmers

## Contributing

- Please follow the Nim Style Guide: https://nim-lang.org/docs/nep1.html
- All folder names in `snake_case`
- All file names in `camelCase`
  - Algorithms with multiple implementation techniques goes as `algorithmName_method`
    ```bash
    # example
        |-- math
            |-- checkPrime_iterative
            |-- checkPrime_recursive
    ```
- Preferred intend size is 2 spaces (not 4 :wink:)
- File docstring
```nim
#[
  Problem: Describe your problem
  Method: Describe prominent approach
  Contributor(s): Name (@github_handle), Name (@github_handle)
  Nim Version: 1.x.y
  Example 1
    Input

    Output
  ...
  Example N
    Input

    Output
]#
``` 
- Finally Make apt changes to this file.


## Nindex

Alphabetical index of nilgorithms

### **A**

| Algorithm Name | Category | Contributor Name |
| --- | --- | --- |
| [Name](#) | [Category](#) |  [Contributor](#) |

### **B**


### ... 

---
---

Shall I proceed, any suggestions?

**Comment by anushkrishnav** [comment]
@ankitaggarwal23

**Comment by nandgator** [comment]
Hi, I had an afterthought, converted it to a different repo https://github.com/joe733/nilgorithms

I wouldn't mind opening PRs _from_ that one.
