### ISSUE TITLE
Add Leet-Code Directory to Miscellaneous Directory

### ISSUE THREAD

**Issue by HarshKhilawala** [HarshCasper/NeoAlgo#678]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Add Leet-Code Directory into Miscellaneous Folder

**Comment by HarshKhilawala** [comment]
I would Like to Work on this . So Kindly Assign this to me.

**Comment by HarshKhilawala** [comment]
I have Created the Pull Request so Kindly Check for it. README file is still incomplete as Needing Help from Project Maintainers for creating README similar like HackerRank  Problems Dash-board. @HarshCasper @iamrajiv

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by HarshKhilawala** [comment]
Issue solved
