### ISSUE TITLE
Find nth Fibonacci number using fast exponentiation - O(logn)

### ISSUE THREAD

**Issue by Aparna-Sakshi** [HarshCasper/NeoAlgo#6831]
## 💥 Proposal

Find nth Fibonacci number using fast exponentiation - O(logn)

I would like to implement this algorithm in python

I am a GSSOC-21 participant, please assign this issue to me.

**Comment by prateek-jpg** [comment]
I would like to implement this algorithm in java

I am a GSSOC-21 participant, please assign this issue to me.
