### ISSUE TITLE
Depth First Traversal

### ISSUE THREAD

**Issue by kshithih** [HarshCasper/NeoAlgo#6855]
## 🚀 Feature

Depth first search (dfs) is processed by starting vertex and then going deeper until required node is found. It uses idea of backtracking.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

This is one of the traversal method in a graph.

**Comment by ankitaggarwal23** [comment]
Code present
