### ISSUE TITLE
Detect Loop in Linked List-JAVA

### ISSUE THREAD

**Issue by muddhit** [HarshCasper/NeoAlgo#686]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Assignees 

- Java: @Mukulbaid63
- C++: @yashaswibiyahut

**Comment by muddhit** [comment]
I want to work on it,so please assign it to me

**Comment by yashaswibiyahut** [comment]
would like to work on this issue . please assign me @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv

**Comment by devanshiv123** [comment]
I want to work on it in C++ , please assign it to me @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv

**Comment by viveksahu26** [comment]
I would like to work with this issue in java.. please assign me..

**Comment by nutanaarohi123** [comment]
I would like to work on this issue in Python .Kindly assign @HarshCasper @Kajol-Kumari
