### ISSUE TITLE
[TAKEN] Add Selection Sort Algorithm 

### ISSUE THREAD

**Issue by RaviAnand111** [HarshCasper/NeoAlgo#69]
**Algorithm: Selection Sort ** 

**DS:** 

**Languages Supported: C, C++, Java, JavaScript, etc.**

**Comment by RaviAnand111** [comment]
@HarshCasper I want to solve this issue in java. Can you assign it to me.?

**Comment by sparkingdark** [comment]
@HarshCasper c and c++

**Comment by Apoorve73** [comment]
@HarshCasper I want to work on this issue in Python. Can you please assign that to me?

**Comment by mar-galho** [comment]
Please, make sure to respond to this issue once you've uploaded your code :)

**Comment by UtkarshChaurasia** [comment]
@HarshCasper Can I work on this in Javascript.

**Comment by mar-galho** [comment]
Great! Please, go ahead @UtkarshChaurasia !

**Comment by parjanyaacoder** [comment]
@ricardoprins This issue has not been solved in Java. Please assign it to me.

**Comment by mar-galho** [comment]
Done - just make sure to pull/rebase the repo prior to working on it!
