### ISSUE TITLE
BFS

### ISSUE THREAD

**Issue by Shatakshijain** [HarshCasper/NeoAlgo#6913]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
I would like to add breadth first search(BFS) for a graph.
## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by ankitaggarwal23** [comment]
Code present
