### ISSUE TITLE
DNF Sort (Dutch National Flag)

### ISSUE THREAD

**Issue by tanyagupta0201** [HarshCasper/NeoAlgo#6985]
DNF sort is used to sort an array of 0, 1, and 2's in linear time that does not consume any extra space.

I would like to contribute its code in C++.
Kindly assign this problem to me.

**Comment by ankitaggarwal23** [comment]
Code already present [here](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/other/SortColors-DutchNationalFlag.cpp)
