### ISSUE TITLE
ping pong game using python  

### ISSUE THREAD

**Issue by walaa5** [HarshCasper/NeoAlgo#6987]
## 💥 Proposal

(A ping pong game using python.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(yes, I read it.)

**Comment by ankitaggarwal23** [comment]
We don't accept such code. It falls neither as a Data Structure nor as an algorithm.
