### ISSUE TITLE
Naive Baye's Classifier Algorithm 

### ISSUE THREAD

**Issue by ainy-123** [HarshCasper/NeoAlgo#7021]
## 💥 Proposal
Code for the Naive Baye's Classifier Algorithm of Machine Learning in Python.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

**Comment by ainy-123** [comment]
> This issue [has been assigned](https://github.com/TesseractCoding/NeoAlgo/issues/7021#issuecomment-848280643) to @amulyavarshney!
> It will become unassigned if it isn't closed within 12 days. A maintainer can also add the **pinned** label to prevent it from being unassigned.

I have created the issue to work on it and commented "/assign". But ,this issue has been assigned to someone else.
Is there any mistake in assignment?
Please check.

**Comment by amulya-0706** [comment]
@ainy-123 your comment to assign you the issue is about 10 days old and I requested to assign me this issue only after I checked that it has not been assigned to anyone earlier.

**Comment by ainy-123** [comment]
> @ainy-123 your comment to assign you the issue is about 10 days old and I requested to assign me this issue only after I checked that it has not been assigned to anyone earlier.

Yes, that's what my confusion is.
Why have I not been assigned?
