### ISSUE TITLE
Karatsuba Algorithm for multiplication

### ISSUE THREAD

**Issue by GajjarMiten** [HarshCasper/NeoAlgo#704]
## 🚀 Feature
For systems that need to multiply numbers in the range of several thousand digits, such as computer algebra systems and bignum libraries, long multiplication is too slow. These systems employ [Karatsuba multiplication](https://en.wikipedia.org/wiki/Karatsuba_algorithm).
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

 Yes.

## Pitch

It is faster than the naive algorithm for multiplying two numbers which require n<sup>2</sup> single-digit products while
it requires only n<sup>1.585</sup>

## Assignees:
- C : [@sanskarvijpuria]
- CPP :  [@devanshiv123]
- Java : [@Huzaib ]
- Python : [@Neel2904]
- JavaScript : [@sanskarvijpuria]
- Go : [@GajjarMiten ]
- C# :

**Comment by Huzaib** [comment]
Can I take it up in java?

**Comment by Neel2904** [comment]
I want to work on this with python

**Comment by devanshiv123** [comment]
I want to work on this issue in C++

**Comment by sanskarvijpuria** [comment]
Can I work on this in C and Javascript?

**Comment by vgb-codes** [comment]
@Huzaib Go ahead with Java.
@Neel2904 Go ahead with Python.
@devanshiv123 Go ahead with C++.
@sanskarvijpuria Go ahead with Javascript and C.
Please follow the contribution guidelines when submitting your PR.

**Comment by GajjarMiten** [comment]
@VijayaGB98 
I would like to do it in Golang.

**Comment by devanshiv123** [comment]
> @Huzaib Go ahead with Java.
> @Neel2904 Go ahead with Python.
> @devanshiv123 Go ahead with C++.
> @sanskarvijpuria Go ahead with Javascript and C.
> Please follow the contribution guidelines when submitting your PR.

 @VijayaGB98 Please add the CH20 label to the issue.

**Comment by vgb-codes** [comment]
@GajjarMiten Go ahead with Golang.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
