### ISSUE TITLE
Implement 3 sum problem in Python

### ISSUE THREAD

**Issue by devRawnie** [HarshCasper/NeoAlgo#7045]
## 🚀 Feature

Implement 3 sum problem in Python

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes
## Motivation

I wasn't able to locate any program which implemented the 2 pointer technique. I would like to do the same for the 3 sum problem.

## Pitch

The 2 pointer technique is an effective technique used in sorted arrays to perform search operations. I would like to demonstrate the same using the 3 sum problem

**Comment by ankitaggarwal23** [comment]
@all-contributors bot please add @devRawnie for his contribution.

**Comment by ankitaggarwal23** [comment]
@all-contributors bot please add @devRawnie for code
