### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by Sapna2001** [HarshCasper/NeoAlgo#705]
## 🚀 Feature

Bucket sort in various languages.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

**Comment by Sapna2001** [comment]
Please assign me python.

**Comment by ashishsahu1** [comment]
I can do it in C

**Comment by yashaswibiyahut** [comment]
I would like to do this in c++ please assign me @Kajol-Kumari @iamrajiv @siddharth25pandey

**Comment by vgb-codes** [comment]
This thread is a duplicate of Issue #426. Please do not create duplicate issue threads. Therefore, I am closing this.
