### ISSUE TITLE
Quick Sort for sorting a linked list

### ISSUE THREAD

**Issue by salonidabgar** [HarshCasper/NeoAlgo#7251]
## 💥 Proposal

Idea is to implement quick sort to sort a linked list using C++.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by purohitmansi** [comment]
Please do assign this to me.
