### ISSUE TITLE
Implementation of deque using linked list

### ISSUE THREAD

**Issue by bindu030** [HarshCasper/NeoAlgo#7376]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

This program is to  implement deqeue using linked list.
I have read the Contributing Guidelines on Pull Requests.

I would like to work on this issue. Please assign it to me. I will solve it in C++ language.

**Comment by bindu030** [comment]
@ankitaggarwal23 can i please know the reason for closing the issue sir?

**Comment by ankitaggarwal23** [comment]
Yesterday was the last date. GSSoc period is now over. So all the issues are auto closed.
