### ISSUE TITLE
Flood Fill Algorithm(Graphs)

### ISSUE THREAD

**Issue by devanshiv123** [HarshCasper/NeoAlgo#740]
## 🚀 Feature

Flood Fill Algorithm is a simple variant of BFS/DFS which is generally used in case of implicit graphs.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is used in some problems of 2-d matrices.

## Assignees 

- C++: @devanshiv123 
- Python: @sanskarvijpuria
- Java: @yashaswibiyahut
- C: @YashThakare

**Comment by devanshiv123** [comment]
Please assign it to me in C++ @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv

**Comment by sanskarvijpuria** [comment]
Please assign me this in python.

**Comment by yashaswibiyahut** [comment]
Please assign it to me in Java @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv

**Comment by Yash-Thakare22** [comment]
I would like to work on this issue in C

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
