### ISSUE TITLE
Car Fueling (Greedy Problem) in C++

### ISSUE THREAD

**Issue by Sri-vishnu-r1431** [HarshCasper/NeoAlgo#7408]
## 💥 Proposal

This is a problem to which out whether the car can reach the distance required or not

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

**Comment by Simi06** [comment]
I would write the code in CPP
