### ISSUE TITLE
Addition of Linked operations to c++ section.

### ISSUE THREAD

**Issue by aniketsingh98571** [HarshCasper/NeoAlgo#75]
This is to inform you regarding the addition of different operations of the linked list using c++. Please suggest if required.

**Comment by mar-galho** [comment]
Would you please elaborate some more? It becomes easier for us to help once we understand the issue better! Thanks!

**Comment by atarax665** [comment]
@aniketsingh98571 Can you please elaborate the issue? Else I think this issue needs to be closed @ricardoprins

**Comment by mar-galho** [comment]
Closing issue.
