### ISSUE TITLE
Adding pending contributors to the contributor's list of NeoAlgo

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#752]
Adding pending contributors to the contributor's list of NeoAlgo.

Please, comment down if your name is not added in contributors list of NeoAlgo i.e. https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by raksha009** [comment]
plz assign me this issue.

**Comment by raksha009** [comment]
@iamrajiv

**Comment by Kritika37** [comment]
I am not added

**Comment by yashsahay25** [comment]
I am not added

**Comment by iamrajiv** [comment]
@yashsahay2014 can you mention the PR which was made by you and got merged.

**Comment by iamrajiv** [comment]
@Kritika37 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by yashsahay25** [comment]
@iamrajiv I have made PR which is yet to be merged by you. Issue #641

**Comment by Kritika37** [comment]
> @Kritika37 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

Thank you

**Comment by raksha009** [comment]
Add me too plz
https://github.com/TesseractCoding/NeoAlgo/pull/645

**Comment by iamrajiv** [comment]
@raksha009 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by raksha009** [comment]
> @raksha009 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

Thanks

**Comment by cherryWood55** [comment]
@iamrajiv my PR is yet to be merged #628 #620

**Comment by iamrajiv** [comment]
@cherryWood55 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by NEEHITGOYAL** [comment]
add me too please i have two pr merged @iamrajiv

**Comment by iamrajiv** [comment]
@NEEHITGOYAL I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by rutujadhanawade** [comment]
@iamrajiv please add me, my 2 PR are merged.

**Comment by iamrajiv** [comment]
@rutujadhanawade I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by Kritika37** [comment]
Please add me for coding as well
My PR got merged #566

**Comment by iamrajiv** [comment]
@Kritika37 Your are already added please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by Kritika37** [comment]
> @Kritika37 Your are already added please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

Yes I know, I'm added but only for documentation thing. Add me for coding as well

**Comment by iamrajiv** [comment]
@Kritika37 I have updated the list please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by Kritika37** [comment]
> @Kritika37 I have updated the list please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

Thank you

**Comment by reethikprasad** [comment]
Hi @iamrajiv my PR has not still merged 
Please check 
https://github.com/TesseractCoding/NeoAlgo/pull/459

**Comment by smv1999** [comment]
I have not been added @iamrajiv

**Comment by iamrajiv** [comment]
@smv1999 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

**Comment by smv1999** [comment]
> @smv1999 I have added you please take a look https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTORS.md

Thank you !
