### ISSUE TITLE
Wrong TestCases in C-Plus-Plus/stack/Check_for_balanced_parenthesis.cpp

### ISSUE THREAD

**Issue by Rishabh7896** [HarshCasper/NeoAlgo#7529]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

The given test cases has not been handled in code. The test cases talk about an expression but in the code it is no where handled thus results in wrong output. Also the given sample I/O is not correct.

**Comment by Ayush0431** [comment]
Hi, I'm interested in fixing this if none else is working on it :)
