### ISSUE TITLE
Wrong algorithm used at C-Plus-Plus/stack/maximum_size_of_balanced_bracket_sequence.cpp

### ISSUE THREAD

**Issue by Rishabh7896** [HarshCasper/NeoAlgo#7530]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

This code doesnot handle the domain of question. It fails in many testcases.

**Comment by Amisha328** [comment]
Hey, @Rishabh7896 
Could you please specify the test cases on which the algorithm fails?

**Comment by Rishabh7896** [comment]
Input: )()()(((()
Expected Output: 4
Output: 6

If we will assume the answer to be the sum of the length of all valid sequences then it is correct, otherwise, it is wrong

**Comment by Amisha328** [comment]
Thank you for the test case.

But I think in this particular question, it is asked to print the maximum length of valid bracket sequence. So, we have to sum the number of brackets that make it valid.

So, the solution according to me is correct.
