### ISSUE TITLE
Need to correct the example test case output written in the down of the NextPermutation problelm.

### ISSUE THREAD

**Issue by KmrAnish04** [HarshCasper/NeoAlgo#7537]
## 💥 Proposal

**Need to correct the example test case output written in the down of the question file named NextPermutation having path "C-Plus-Plus/cp/NextPermutation.cpp"**

(Write your answer here.)
**Currently written test case in the file is:**
/**
Input :
6
5 3 4 9 7 6
Output :
6
5 3 4 9 7 6
Time Complexity : O(nlogn)
Space Complexity : O(n)
**/

**Changes need to be done:**
/**
Input :
6
5 3 4 9 7 6
Output :
5 3 6 4 7 9
Time Complexity : O(nlogn)
Space Complexity : O(n)
**/

**Explanation:**
1. Test case: According to the algorithm written in the file, 
  for the test case: 
  6
  5 3 4 9 7 6
  
    The correct output is:
    5 3 6 4 7 9

2. Here the space complexity is already correct. No need to change space complexity.

**Comment by Ash-KODES** [comment]
is this issue closed?
there are no PR?

**Comment by KmrAnish04** [comment]
here is the PR id = #7539 for this issue. @Ash-KODES
