### ISSUE TITLE
Segment Tree

### ISSUE THREAD

**Issue by sayna3311** [HarshCasper/NeoAlgo#7543]
## 🚀 Feature

There is a lack of material on __segment trees__ and derivatives of segment trees. 

I would like to add the data structure segment tree to this repo since the segment tree is one of the very important advanced data structures. It helps to reduce time complexity by a margin for queries and updates. 

I would like to implement the same in various languages like C++, Python.

**Comment by dhruti29** [comment]
I would like to work on this issue.
