### ISSUE TITLE
Connect n ropes with minimum cost

### ISSUE THREAD

**Issue by CodesbyUnnati** [HarshCasper/NeoAlgo#7546]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

I saw that the problem "Connect n ropes with minimum cost" is not present in the repository, so I have
added it in the "cp" folder.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, I have read.

**Comment by khushbooag4** [comment]
IS this issue open

**Comment by khushbooag4** [comment]
@CodesbyUnnati /assign
