### ISSUE TITLE
KMP Algorithm

### ISSUE THREAD

**Issue by kushagra1212** [HarshCasper/NeoAlgo#7548]
## 💥 Proposal

There is no KMP Algorithm Problem.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

KMP Algorithm for Pattern Searching

**Comment by charlie219** [comment]
@HarshCasper @iamrajiv assign me for Python
