### ISSUE TITLE
Bipartite Graph

### ISSUE THREAD

**Issue by SangeetaMishra** [HarshCasper/NeoAlgo#764]
## 🚀 Feature

A basic algorithm to check whether the given graph is bipartite or not. In simple words, whether it can be coloured in two different colours so that every edge connects two vertices with different colours.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

As it has not been added in any issue in Hakin Codes.

## Pitch

Important standard graph algorithm

## Assignees :
C :
CPP :
Python :
Java :
C# :
JavaScript :
GO :

**Comment by SangeetaMishra** [comment]
Please assign this issue to me for C++ as a part of Hackin Codes @atarax665 @SKAUL05 @iamrajiv

**Comment by yashaswibiyahut** [comment]
Please assign this issue to me for Python as a part of Hackin Codes @atarax665 @SKAUL05 @iamrajiv

**Comment by sahanabalappa** [comment]
assign me for java

**Comment by anubhvshrma18** [comment]
Please assign this issue to me in javascript as a part of HakinCodes
