### ISSUE TITLE
Playfair Cipher

### ISSUE THREAD

**Issue by GajjarMiten** [HarshCasper/NeoAlgo#785]
## 🚀 Feature
* [Playfair Cipher](https://en.wikipedia.org/wiki/Playfair_cipher)
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

To learn different kinds of Cipher algorithms 

## Pitch

Cryptography is an essential way of preventing that from happening. It secures information and communications using a set of rules that allows only those intended—and no one else—to receive the information to access and process it.

## Assignees :
* C : @sahanabalappa
* CPP : @YashThakare 
* Python : 
* Java : @parjanyaacoder 
* C# :
* JavaScript : 
* GO :

**Comment by Yash-Thakare22** [comment]
I would to like work on this issue in C++ and Python

**Comment by ritvij14** [comment]
I would like to take this in Java

**Comment by sahanabalappa** [comment]
would to like work on this issue in C

**Comment by atarax665** [comment]
@parjanyaacoder @sharanya02 I am closing #519 . You can link your PR to this issue.

**Comment by atarax665** [comment]
> I would to like work on this issue in C++ and Python

Sure, you can take this issue in C++.
Don't forget to follow contribution guidelines and make sure that your previous PRs are merged successfully.

**Comment by atarax665** [comment]
> I would like to take this in Java

@ritvij14  Sorry, this issue is already assigned to someone else in Java. You may take up this issue in any other language you're comfortable with.

**Comment by atarax665** [comment]
> would to like work on this issue in C

@sahanabalappa You are assigned this issue in C.
Make sure you go through the contribution guidelines first.
Happy coding

**Comment by ritvij14** [comment]
> Sorry, this issue is already assigned to someone else in Java. You may take up this issue in any other language you're comfortable with.
@atarax665 I would like to take this in Javascript then.

**Comment by atarax665** [comment]
@ritvij14 Go ahead with JavaScript.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ritvij14** [comment]
@GajjarMiten please remove my name from the issue description as I am unable to solve this issue.
