### ISSUE TITLE
Spiral Matrix

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#792]
## 🚀 Feature

Given a matrix of m x n elements (m rows, n columns), return all elements of the matrix in spiral order.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I would like to add an algo for the solution of this problem in competitive problem section.

Plz assign me this issue in Java and C++
@SKAUL05  @Kajol-Kumari

**Comment by kauravankit25** [comment]
I want to take this in python please assign me

**Comment by SangeetaMishra** [comment]
Please assign this to me in C++.

**Comment by GrayFlash** [comment]
Please assign Java part to me

**Comment by narayan2111** [comment]
I would like to work on this issue in C, please assign this to me. @SKAUL05 @Kajol-Kumari @iamrajiv

**Comment by vatsalkesarwani12** [comment]
@raksha009  assigned Java, Cpp
@kauravankit25 assigned python
@narayan2111 assigned C

**Comment by SangeetaMishra** [comment]
@plazzy99   Please assign this to me in Golang.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
