### ISSUE TITLE
Tower of Hanoi Algorithm 

### ISSUE THREAD

**Issue by sanskarvijpuria** [HarshCasper/NeoAlgo#793]
## 🚀 Feature

Tower of Hanoi Algorithm 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is not yet added in this repository and I think it is one of the popular algorithms.

## Pitch

 It uses the divide and conquer method, it reduces the degree of difficulty since it divides the problem into subproblems that are easily solvable, and usually runs faster than other algorithms would. 

Please assign me this issue as a part of Hakincode. I want to implement it in python.

## Assignees
C: @SangeetaMishra
CPP: @kauravankit25
Python: @PinkyWalia
C#: @imPGupta 
Java: @ritvij14
Go: @ahampriyanshu
Javascript: @ShristiJalan

**Comment by kauravankit25** [comment]
I want to take this in c++ please assign me

**Comment by SangeetaMishra** [comment]
Please assign this to me in C.

**Comment by ahampriyanshu** [comment]
Can I implement this algorithm in Golang.

**Comment by PinkyWalia** [comment]
I want to contribute in python. Please assign me

**Comment by ritvij14** [comment]
I would like to take this Java as part of CH20.

**Comment by ShristiJalan** [comment]
I want to contribute in Javascript. Please assign me

**Comment by TEJASWI-TEJASWI** [comment]
Hi everyone could anyone pls assign this in c++ to me as a part of Hakincodes
@Abhijit2505 @Kajol-Kumari @siddharth25pandey @plazzy99

**Comment by vgb-codes** [comment]
@kauravankit25 Go ahead with C++
@SangeetaMishra Go ahead with C
@ahampriyanshu Go ahead with Golang
@PinkyWalia Go ahead with Python
@ritvij14 Go ahead with Java
@ShristiJalan Go ahead with Javascript
@TEJASWI-TEJASWI C++ has been taken, therefore I cannot assign you C++.

**Comment by SangeetaMishra** [comment]
> @kauravankit25 Go ahead with C++
> @SangeetaMishra Go ahead with C
> @ahampriyanshu Go ahead with Golang
> @PinkyWalia Go ahead with Python
> @ritvij14 Go ahead with Java
> @ShristiJalan Go ahead with Javascript
> @TEJASWI-TEJASWI C++ has been taken, therefore I cannot assign you C++.

Added in C. #842

**Comment by kauravankit25** [comment]
> @kauravankit25 Go ahead with C++
> @SangeetaMishra Go ahead with C
> @ahampriyanshu Go ahead with Golang
> @PinkyWalia Go ahead with Python
> @ritvij14 Go ahead with Java
> @ShristiJalan Go ahead with Javascript
> @TEJASWI-TEJASWI C++ has been taken, therefore I cannot assign you C++.

Added in C++

**Comment by imPGupta** [comment]
@VijayaGB98, I want to contribute in C#.

**Comment by vgb-codes** [comment]
@imPGupta Go ahead with C#

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
