### ISSUE TITLE
Minimum Sum Partition Problem

### ISSUE THREAD

**Issue by sharur7** [HarshCasper/NeoAlgo#805]
## 🚀 Feature

__HackinCodes2020 Participant__
#### Minimum Sum Partition Problem:
In this problem given set is partitioned into two subsets such that the difference between the sum of elements of 1st set and the sum of elements of 2nd set is minimized.

Language Supported:

C
CPP
Python
Java
C#
JavaScript
GO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It is a part of Dynamic Programming.
This problem is mainly an extension of the Dynamic Programming (Partition Problem).
It has not yet been added to DP problems in the repository.

## Pitch

As we know that problems having optimal substructure and overlapping can be solved by Dynamic Programming.
This problem has an optimal substructure. This means that the problem can be divided into smaller, simple subproblems which can be further divided until the solution becomes trivial. 

I want to take up this issue in C++ and Python.

@plazzy99 @SKAUL05 @Kajol-Kumari @Abhijit2505 @routrohan

**Comment by ritvij14** [comment]
I would like to take this in Java.

**Comment by GrayFlash** [comment]
I would like to work on C++

**Comment by sahanabalappa** [comment]
I would like to work on C

**Comment by Ajay0511** [comment]
Iwould like to do it in Python.

**Comment by Kajol-Kumari** [comment]
@GrayFlash as c++ is already taken up by @sharur7 can't assign it to you. Feel free to claim any other issues.
@sharur7 : c++
@Ajay0511 : Python
@ritvij14 : Java
@sahanabalappa : C

GO ahead!

**Comment by ritvij14** [comment]
@Kajol-Kumari please also add a tag for its difficulty level.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ritvij14** [comment]
@HarshCasper, @iamrajiv please add a difficulty label to this Issue
