### ISSUE TITLE
smallest Subarray with given sum

### ISSUE THREAD

**Issue by Joshitha18** [HarshCasper/NeoAlgo#814]
## 🚀 Feature

Given an unsorted array of integers(including negative numbers), find the smallest subarray which adds to a given number.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

## Assignees 

- C: @yashsahay2014
- C++: @Joshitha18 
- Java: @sahanabalappa
- Python: @shraddhavp

**Comment by Joshitha18** [comment]
I'd like to work on it in C++ @Kajol-Kumari

**Comment by sahanabalappa** [comment]
I'd like to work on it in java

**Comment by yashsahay25** [comment]
I'd like to work on it in C @Joshitha18

**Comment by Kajol-Kumari** [comment]
@Joshitha18 let's tweak the issue a little bit `find the smallest sub-array that sums to the given number. Please make this modification in the issue description.

**Comment by Joshitha18** [comment]
@Kajol-Kumari done

**Comment by Adityanagraj** [comment]
Can we work on python for this issue @Joshitha18

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by shraddhavp** [comment]
would like to take this issue in python @iamrajiv

**Comment by shraddhavp** [comment]
@plazzy99  sir what is the difficulty level for this issue  to fill in the form?
