### ISSUE TITLE
Count triplets

### ISSUE THREAD

**Issue by Joshitha18** [HarshCasper/NeoAlgo#815]
## 🚀 Feature

Given an array of distinct integers. The task is to count all the triplets such that sum of two elements equals the third element.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

Assignees:
* C++ : @Joshitha18 
* Java : @GrayFlash 
* C : @sahanabalappa
* Python : @Aanchi-glitch2744
* JavaScript : 
* C# : 
* Golang :

**Comment by Joshitha18** [comment]
I'd like to work on it C++

**Comment by GrayFlash** [comment]
I'd like to work on Java

**Comment by sahanabalappa** [comment]
I'd like to work on it C

**Comment by SangeetaMishra** [comment]
@Kajol-Kumari  I would like to work in Python.

**Comment by SangeetaMishra** [comment]
@Kajol-Kumari I would like to work on this in Python

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by Aanchi-glitch2744** [comment]
I'd like to work on this issue in Python.

**Comment by atarax665** [comment]
> I'd like to work on this issue in Python.

@Aanchi-glitch2744 Great! You can start working on this issue in Python.
Happy Coding.
