### ISSUE TITLE
Cutting a Rod (DP Algorithm)

### ISSUE THREAD

**Issue by GrayFlash** [HarshCasper/NeoAlgo#816]
### Problem Statement:
Given a rod of length n inches and an array of prices that contains prices of all pieces of size smaller than n. Determine the maximum value obtainable by cutting up the rod and selling the pieces.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Motivation

Is good to know algorithm for the basics of Dynamic Programming. 

## Pitch

We can make a DP which optimally calculates maximum price using the value of smaller size.

**Comment by GrayFlash** [comment]
I would like to work on C++ and Java.

**Comment by devanshiv123** [comment]
I would like to work in C++

**Comment by sahanabalappa** [comment]
I would like to work in C

**Comment by anubhvshrma18** [comment]
I would like to take this issue in python as a part of HakinCodes

**Comment by salonilakhotia** [comment]
I would like to work on this in java as a part of HakinCodes
