### ISSUE TITLE
Can Add Merge Sort 

### ISSUE THREAD

**Issue by RaviAnand111** [HarshCasper/NeoAlgo#82]
**Algorithm: MergeSort **
   
**DS: Sorting** 

**Languages Supported:  C, C++, Java, JavaScript, Python **

**Comment by RaviAnand111** [comment]
I can solve this issue in Java . Can you assign it to me please

**Comment by HarshCasper** [comment]
This issue is currently being worked here https://github.com/TesseractCoding/NeoAlgo/issues/18

Java is already being worked upon by @MSufiyanAG
