### ISSUE TITLE
Activity selection problem

### ISSUE THREAD

**Issue by NEEHITGOYAL** [HarshCasper/NeoAlgo#826]
## 💥 Proposal

You are given n activities (from 0 to n-1) with their start and finish times. Select the maximum number of activities that can be performed by a single person, assuming that a person can only work on a single activity at a time.
For example:
input
3
10 20
12 15
20 30
output:
2
explanation:
Person can only do first and last activity.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

**Comment by NEEHITGOYAL** [comment]
can i work on this issue in cpp as part of hakin codes
@plazzy99 @Kajol-Kumari @routrohan @SKAUL05 @Abhijit2505

**Comment by GrayFlash** [comment]
@plazzy99 @hushee69 can i work on java

**Comment by shubham5351** [comment]
I would like to work on python
@Kajol-Kumari @plazzy99

**Comment by yashaswibiyahut** [comment]
i want to work on this issue in c as part of hakin code @Kajol-Kumari @routrohan @SKAUL05 @Abhijit2505

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
