### ISSUE TITLE
Matrix Exponentiation

### ISSUE THREAD

**Issue by kushagraiitbbs** [HarshCasper/NeoAlgo#832]
## 🚀 Feature
Matrix exponentiation is a technique to find functions like f(n)=a*f(n-1)+b*f(n-2), in O(logn). (where n,a,b are integers)
Here, we are implementing fibonnaci sequence which is f(n)=f(n-1)+f(n-2). So, we are finding nth fibonacci number in O(logn).

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Motivation
I have used it in competitve programming but for f(n)=a*f(n-1)+b*f(n-2)+c*f(n-3).
Its the fastest way to get result for such recursive functions.

## Pitch
Actually this is very much helpful in contests like google kickstart where n<=10^15. This technique should be known beforehand unless you will loose the time in competition unecessarily.

**Comment by kushagraiitbbs** [comment]
Please assign me this issue in c++ @plazzy99 @SKAUL05 @HarshCasper @atarax665 @iamrajiv

**Comment by GrayFlash** [comment]
Please assign me this issue in Java

**Comment by kushagraiitbbs** [comment]
Please add CH20 label to it @SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari @HarshCasper

**Comment by ag278** [comment]
please assign me this issue in c language

**Comment by TEJASWI-TEJASWI** [comment]
i would like to work on this issue in c++ as part of hakin codes
@SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari
