### ISSUE TITLE
Implementation of Trie Data Structure

### ISSUE THREAD

**Issue by devanshiv123** [HarshCasper/NeoAlgo#849]
## 🚀 Feature

Implement Trie Data structure. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Tries can be efficiently used for some problems in contests.

### Assignees and Languages
* @devanshiv123 - **C++**
* @Himanshu70565- **Java**
* @Ajay0511- **Python**
* @Lakhan-Nad - **C & JavaScript**

**Comment by devanshiv123** [comment]
I would like to work on it in C++.

**Comment by Himanshu70565** [comment]
I would like to implement trie  in java

**Comment by Ajay0511** [comment]
I would like to work in Python .

**Comment by Lakhan-Nad** [comment]
I would like to do this in C and JavaScript.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by atarax665** [comment]
All the assignees should comment on #1278 for any query related to this issue.
