### ISSUE TITLE
First Missing Positive Number

### ISSUE THREAD

**Issue by smv1999** [HarshCasper/NeoAlgo#855]
## 🚀 Feature

Given an array of integers, find the first missing positive integer in linear time and constant space. In other words, 
find the lowest positive integer that does not exist in the array. The array can contain duplicates and negative numbers as well.

For example, the input [3, 4, -1, 1] should give 2. The input [1, 2, 0] should give 3.

You can modify the input array in-place.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This problem helps to understand how to work with arrays "in-place" .
## Pitch

This problem expects solution in Linear time (O(n)) and constant space (O(1)) which poses a challenge to come up with optimal solution. This makes this problem interesting!

Happy Coding!

## Programming Language Assigned
* CPP - @smv1999 
* Python - @devanshi-katyal
* C - @SangeetaMishra 
* Java - @ritvij14

**Comment by smv1999** [comment]
@SKAUL05 @Abhijit2505 @HarshCasper  I want to work on this issue in CPP! Kindly assign me this issue!

**Comment by devanshi-katyal** [comment]
i would like to work on this issue in python

**Comment by SangeetaMishra** [comment]
I would like to work in C.

**Comment by ritvij14** [comment]
I would like to take this in Java. for CH20

**Comment by Abhijit2505** [comment]
@smv1999 , please get started with the solution in CPP

**Comment by Abhijit2505** [comment]
@devanshi-katyal , get started with the solution in Python

**Comment by Abhijit2505** [comment]
@SangeetaMishra , please get started with the solution in C.

**Comment by Abhijit2505** [comment]
@ritvij14 please get started with the solution in Java

**Comment by SangeetaMishra** [comment]
> @SangeetaMishra , please get started with the solution in C.

Solve it in C. #882 @Abhijit2505  @SKAUL05  @siddharth25pandey  @iamrajiv

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
