### ISSUE TITLE
Check if 2 strings are anagrams or not

### ISSUE THREAD

**Issue by sukritidawar** [HarshCasper/NeoAlgo#860]
## 🚀 Feature
Given two strings, check if they are anagrams or not.
An anagram of a string is another string that contains same characters, only the order of characters can be different.
For example: 'word' and 'ordw' are anagrams, 'abcd' and 'abcdb' are not anagrams.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Helps in understanding strings and how to optimize the solution.

## Pitch

This will increase the understanding of string manipulation.

Assignees:
C++: @sukritidawar 
Python: @AdityaJ7 
Java: @salonilakhotia
C:  @AakritiKinra

**Comment by sukritidawar** [comment]
I would like to work on this issue in c++

**Comment by AdityaJ7** [comment]
I would like to work on this issue with python

**Comment by salonilakhotia** [comment]
I would like to work on java if it is in hakincodes

**Comment by AakritiKinra** [comment]
I would like to work on this in C if it is under CH20

**Comment by salonilakhotia** [comment]
@Kajol-Kumari  I  have made the PR in java. Kindly review it 
https://github.com/TesseractCoding/NeoAlgo/pull/892

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by abhay313** [comment]
Please assign me I would like to implement it in C++
