### ISSUE TITLE
The REAMDE file under python directory is messed up.

### ISSUE THREAD

**Issue by AdityaJ7** [HarshCasper/NeoAlgo#864]
## 📚 Documentation

The readme file under the python directory is messed up and contains repetitive block of documentation. It needs to be fixed.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes.

I would like to work on this

**Comment by anubhvshrma18** [comment]
I want to take this issue as a part of HakinCodes.

**Comment by atarax665** [comment]
I have edited the README.md file.
