### ISSUE TITLE
Find leftmost non repeating character in a string

### ISSUE THREAD

**Issue by sukritidawar** [HarshCasper/NeoAlgo#868]
## 🚀 Feature

Given a string, find the index of the leftmost non repeating character in it.
Example: s = "hello", output should be: 0 (index of h)
                s = "aabcdb", output should be: 3 (index of c)
                s = "xxyyzz", output should be -1 (since there is no non repeating character in this string)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Helps in understanding strings.

## Pitch

This will increase the understanding of string manipulation.

Assignees:
C++: @sukritidawar 
Python: @Salonishah01
C: @rajanshoo25
Java: @ritvij14

**Comment by sukritidawar** [comment]
I would like to work on this issue in C++

**Comment by salonishah01** [comment]
I would like to work on this issue in python

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20

**Comment by Anshoo-Rajput** [comment]
I would like to work on this issue in C

**Comment by salonishah01** [comment]
In which folder do I need to add the above solution?

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
