### ISSUE TITLE
Binary Tree traversals have been written in the section of graphs in C++ 

### ISSUE THREAD

**Issue by mannika16161** [HarshCasper/NeoAlgo#872]
## 💥 Proposal

(A clear and concise description of what the proposal is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

**Comment by yashaswibiyahut** [comment]
Can you Please elaborate this issue so that i can work on it as a part of hakin codes.
