### ISSUE TITLE
detect loop in graph (c++) 

### ISSUE THREAD

**Issue by mannika16161** [HarshCasper/NeoAlgo#873]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by mannika16161** [comment]
I can do it.

**Comment by TEJASWI-TEJASWI** [comment]
i would like to work on this issue in c++ as part of hakin codes
@SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari
