### ISSUE TITLE
Add folder for Julia submissions.

### ISSUE THREAD

**Issue by vgb-codes** [HarshCasper/NeoAlgo#874]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes, indeed.

## Motivation

Add folder for Julia submissions.

## Pitch

Julia is a high-level language that is great for scientific computing. I believe that it would be a great addition to have algorithms in Julia as well.

**Comment by Anshoo-Rajput** [comment]
@VijayaGB98 Can I work on this issue?
