### ISSUE TITLE
Container with most Water

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#900]
## 🚀 Feature

Given n non-negative integers a1, a2, ..., an , where each represents a point at coordinate (i, ai). n vertical lines are drawn such that the two endpoints of line i is at (i, ai) and (i, 0). Find two lines, which together with x-axis forms a container, such that the container contains the most water.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Adding new algorithm and hence making the repo more extensive.

I would love to contribute and work on this issue.
Plz assign me this issue in Java and C++ .
@Kajol-Kumari  @Abhijit2505

**Comment by devanshiv123** [comment]
I would like to contribute in C++

**Comment by HarshCasper** [comment]
Assigned this to you @raksha009 in C++

**Comment by raksha009** [comment]
Done. Plz assign me this issue in java too.

**Comment by SangeetaMishra** [comment]
Please assign this to me for C

**Comment by SangeetaMishra** [comment]
@iamrajiv Can you assign this to me for C.

**Comment by nutanaarohi123** [comment]
Plz Assign this task in C . @SKAUL05 @HarshCasper

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by nutanaarohi123** [comment]
pls, assign this task in python @SKAUL05  @HarshCasper

**Comment by nutanaarohi123** [comment]
pls by mistake, I unassigned myself. Can u please assign me again? @SKAUL05
