### ISSUE TITLE
Count the number of binary strings

### ISSUE THREAD

**Issue by Akanksha-Pant** [HarshCasper/NeoAlgo#908]
## 🚀 Feature
I want to add the code for calculating total number of binary strings for a given length which do not have 
consecutive one's in it . I want to add this to dynamic programming. I want to work with java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

It will help  people in understanding the concept of dynamic programming better. Dynamic programming will also help in executing the solution for this problem in less time.

## Pitch
It will help reduce the time complexity and as it is one of the standard problems it will  help people in understanding the concept of dynamic programming better.

**Comment by yashaswibiyahut** [comment]
I would like to work on this issue in cpp.please assign me as a part of Hakin codes @SKAUL05 @siddharth25pandey @Kajol-Kumari @iamrajiv

**Comment by TEJASWI-TEJASWI** [comment]
i would like to work on this issue in c++ as part of hakin codes
@SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari

**Comment by imPGupta** [comment]
I want to contribute to this issue. Assign me in **C** language.
@VijayaGB98
