### ISSUE TITLE
Merge without extra space

### ISSUE THREAD

**Issue by rutujadhanawade** [HarshCasper/NeoAlgo#909]
## 🚀 Feature

Given two sorted arrays arr1[] and arr2[] in non-decreasing order with size n and m. The task is to merge the two sorted arrays in place, i. e., we need to consider all n + m elements in sorted order, then we need to put first n elements of these sorted in the first array and remaining m elements in the second array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

I want to add this as a part of CH20.

## Language

- C++: @rutujadhanawade 
- C: @ag278 
- Go:
- Java: @ritvij14 
- JavaScript:
- Python: @narayan2111

**Comment by rutujadhanawade** [comment]
I want to do this in C++.
@siddharth25pandey  @Kajol-Kumari @iamrajiv 
Please add labels and assign this issue to me in c++.

**Comment by narayan2111** [comment]
> I want to do this in C++.
> @siddharth25pandey @Kajol-Kumari @iamrajiv
> Please add labels and assign this issue to me in c++.

can you explain more about this problem so that i can aslo take this in python?

**Comment by narayan2111** [comment]
i would like to work on this issue in Python. @siddharth25pandey @Kajol-Kumari @iamrajiv

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.

**Comment by ag278** [comment]
I would like to solve this issse in C language as a part of CH20. Please assign me this issue

**Comment by raksha009** [comment]
I would like to work on this issue in java.

**Comment by rutujadhanawade** [comment]
@iamrajiv  will you please lable this issue?

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
