### ISSUE TITLE
Binary Search Tree in JAVA(Data Structure)

### ISSUE THREAD

**Issue by shobhu98** [HarshCasper/NeoAlgo#916]
Code for Binary Search Tree is missing in JAva Data Structure and I would like to contribute the code for it.

**Comment by TEJASWI-TEJASWI** [comment]
I would like to work on this issue in C++ .
 @Harsh Bardhan Mishra (PA) @Kajol(M) @Siddharth Pandey(M)   @Abhijit Tripathy(M) @plazzy99

**Comment by Alifbhanvadiya14** [comment]
I would like to work in Python
