### ISSUE TITLE
Longest Common Prefix [CH20]

### ISSUE THREAD

**Issue by rohangawhade** [HarshCasper/NeoAlgo#917]
## 🚀 Feature

Given array of strings, find the longest common prefix present in all the strings. Print the longest common prefix. If no common prefix is present, then print empty string ("").

example: input: "apple", "appology", "apps"
output: "app"

example: input: "dog", "cat", "lion"
output: ""

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Helps in better understanding of strings

## Pitch

It will help in better understanding of strings, substrings and their operations

## Assignees 

- Java: @rohangawhade 
- C++: @devanshiv123 
- Python: @narayan2111 
- C: @bagladivyang03

**Comment by rohangawhade** [comment]
I would like to work on this in Java for CH20.

**Comment by devanshiv123** [comment]
I would like to work in C++ for the issue.

**Comment by narayan2111** [comment]
i would like to work on this issue in Python

**Comment by bagladivyang03** [comment]
i would like to work in C for this issue.

**Comment by TEJASWI-TEJASWI** [comment]
i would like to work on this issue in c++ as part of hakin codes
@SKAUL05 @Abhijit2505 @plazzy99 @Kajol-Kumari

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
