### ISSUE TITLE
Finding the Numbers

### ISSUE THREAD

**Issue by smv1999** [HarshCasper/NeoAlgo#922]
## 🚀 Feature

You are given an array arr containing 2*N+2 positive numbers, out of which 2*N numbers exist in pairs whereas the other two number occurs exactly **once** and are **distinct**. You need to find the other two numbers and print them in **ascending** order.
Input:
2 (N)
1 2 3 2 1 4  (Array Elements)

Output:
3 4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

This helps in better understanding of arrays

## Pitch

This problem helps in brainstorming for various methods of solving it which makes it really interesting!
Happy Coding!

## Assignees 

- C++: @smv1999
- C: @narayan2111
- Java: @ritvij14
- Python: @SangeetaMishra

**Comment by smv1999** [comment]
@SKAUL05 @Abhijit2505 @siddharth25pandey  @HarshCasper  I would like to work on this issue in CPP. Please assign me this issue!

**Comment by narayan2111** [comment]
I also would like to work on this issue in C

**Comment by ritvij14** [comment]
I would like to work on this in Java

**Comment by Mohitkumar6122** [comment]
@SKAUL05 @Abhijit2505 @siddharth25pandey, I would like to do this in python

**Comment by ritvij14** [comment]
@HarshCasper please also add the CH20 label and difficulty level label.

**Comment by narayan2111** [comment]
Kindly label the difficulty level of this issue @iamrajiv

**Comment by SangeetaMishra** [comment]
@iamrajiv I would like to take this in Python

**Comment by SangeetaMishra** [comment]
@iamrajiv @atarax665 @plazzy99 I have added the Python Code
