### ISSUE TITLE
Addition of Polynomial and evaluation using circular linked lists

### ISSUE THREAD

**Issue by bagladivyang03** [HarshCasper/NeoAlgo#923]
## 💥 Proposal
A program for calculating the sum of two polynomials and also for evaluation of polynomial by accepting the variable values.
This issue is good for building concepts in linked lists .

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Comment by devanshiv123** [comment]
I would like to work on the issue in C++.

**Comment by ritvij14** [comment]
I would like to take this in Java for HakinCodes CH20.
