### ISSUE TITLE
Sorting Algorithm:Cocktail Sort

### ISSUE THREAD

**Issue by sahanabalappa** [HarshCasper/NeoAlgo#925]
Bubble sort algorithm can be further optimized with the help of **Cocktail Sort**. Here instead of moving in one direction from left to right we move in the opposite direction right to left. Hence, once we move the largest element towards the right, while returning back to the initial position, we take the smallest element to the left.
**Cocktail sort** will be faster then **bubble sort**, but it will not change the complexity. The complexity will be still **O(n^2).**
EX:
Initial Un-Sorted array: {2, 7, 6, 4, 1, 8, 5, 3}
Pass 1:
Left to right:
{2, 6, 7, 4, 1, 8, 5, 3} 2 > 6? False
{2, 6, 4, 7, 1, 8, 5, 3} 6 > 4? True, swap
{2, 4, 6, 1, 7, 8, 5, 3} 6 > 1? True, swap
{2, 4, 1, 6, 7, 8, 5, 3} 6 > 7? False
{2, 4, 1, 6, 7, 5, 8, 3} 7 > 5? True, swap
{2, 4, 1, 6, 5, 7, 8, 3} 7 > 8? False
{2, 4, 1, 6, 5, 7, 8, 3} 8 > 3? True, swap
{2, 4, 1, 6, 5, 7, 3, 8} 

Now from right to left:
{2, 4, 1, 6, 5, 7, 3, 8}  3 < 7? True, swap
{2, 4, 1, 6, 5, 3, 7, 8}  3 < 5? True, swap
{2, 4, 1, 6, 3, 5, 7, 8}  3 < 6? True, swap
{2, 4, 1, 3, 6, 5, 7, 8}  3 < 1? False
{2, 1, 4, 3, 6, 5, 7, 8}  1 < 2? True, swap
{1, 2, 4, 3, 6, 5, 7, 8}  
 
Hence in the first pass, lowest element is at the left and highest element is at the right.

Pass 2:

Left to Right
{1, 2, 4, 3, 6, 5, 7, 8} 1 > 2? False 
{1, 2, 4, 3, 6, 5, 7, 8} 2 > 4? False 
{1, 2, 4, 3, 6, 5, 7, 8} 4 > 3? True, swap 
{1, 2, 3, 4, 6, 5, 7, 8} 4 > 6? False
{1, 2, 3, 4, 6, 5, 7, 8} 6 > 5? True, swap
{1, 2, 3, 4, 5, 6, 7, 8} 6 > 7? False

Right to Left
{1, 2, 3, 4, 5, 6, 7, 8} 6 < 5? False 
{1, 2, 3, 4, 5, 6, 7, 8} 5 < 4? False 
{1, 2, 3, 4, 5, 6, 7, 8} 4 < 3? False 
{1, 2, 3, 4, 5, 6, 7, 8} 3 < 2? False 
{1, 2, 3, 4, 5, 6, 7, 8} 2 < 1? False 
 

Now the array is sorted.

**Comment by sahanabalappa** [comment]
I would like to work on this issue in C

**Comment by ritvij14** [comment]
I would like to take this in Java for HakinCodes CH20.

**Comment by tejaswi55511** [comment]
I would like to work on this issue in C++ . 
Please assign this task to me @plazzy99 @SKAUL05 @Abhijit2505 @atarax665

**Comment by TEJASWI-TEJASWI** [comment]
I would like to work on this issue in C++ .
Please assign this task to me @plazzy99 @SKAUL05 @Abhijit2505 @atarax665

**Comment by rutujadhanawade** [comment]
I would like to take this issue in Python.

**Comment by Kajol-Kumari** [comment]
Please go ahead with this issue.
C: @sahanabalappa 
Java: @ritvij14 
C++ : @TEJASWI-TEJASWI 
Python: @rutujadhanawade

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by rutujadhanawade** [comment]
@iamrajiv @Kajol-Kumari @siddharth25pandey 
@HarshCasper  please add difficulty label to this issue.
