### ISSUE TITLE
String to int (atoi)

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#929]
## 🚀 Feature

Implement atoi which converts a string to an integer.

The function first discards as many whitespace characters as necessary until the first non-whitespace character is found. Then, starting from this character, takes an optional initial plus or minus sign followed by as many numerical digits as possible, and interprets them as a numerical value.

The string can contain additional characters after those that form the integral number, which are ignored and have no effect on the behavior of this function.

If the first sequence of non-whitespace characters in str is not a valid integral number, or if no such sequence exists because either str is empty or it contains only whitespace characters, no conversion is performed.

If no valid conversion could be performed, a zero value is returned.

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Adding new algorithm and hence making the repo more extensive.

I would love to contribute and work on this issue.
Plz assign me this issue in Java and C++ .
@Kajol-Kumari @iamrajiv @SKAUL05

**Comment by raksha009** [comment]
@iamrajiv Plz assign me this issue too in java.
Thanks

**Comment by HarshCasper** [comment]
Assigned to you in C++ @raksha009 

Complete your previous Issues before I assign you in Java as well

**Comment by raksha009** [comment]
Sorry for the confusion, i'll work on c++ 😅

**Comment by AdityaJ7** [comment]
Can i work on this with python?

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by nutanaarohi123** [comment]
I want to work on this issue in C. pls assign @HarshCasper  @SKAUL05 .
