### ISSUE TITLE
Double factorial

### ISSUE THREAD

**Issue by ag278** [HarshCasper/NeoAlgo#930]
## 🚀 Feature

Double factorial of a non-negative integer n is defined as the product of all the integers from 1 to n that have the same parity (odd or even) as n.  It is also called as semifactorial of a number and is denoted by n!!

### Have you read the [Contributing Guidelines on Pull Requests]
(https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
Using recursion this issue can be solved in O(n) time complexity and in lesser time than an iterative approach
I want to solve this issue as a part of CH20

## Language

- C++: @ag278 
- C: @bagladivyang03 
- Go:
- Java: @ritvij14 
- JavaScript: @gupta-piyush19 
- Python: @rutujadhanawade

**Comment by ag278** [comment]
@SKAUL05 @atarax665 @Abhijit2505 @iamrajiv I want to solve this issue in c++ language as a part of CH20. Please assign me this issue

**Comment by iamrajiv** [comment]
@ag278 Ok, make sure you add both iterative and recursive method.

**Comment by ag278** [comment]
@iamrajiv could you please add CH20 and level tag as well

**Comment by ag278** [comment]
@iamrajiv  could you please add the level tag for this problem

**Comment by rutujadhanawade** [comment]
I would like to do this in java or python

**Comment by bagladivyang03** [comment]
i want to do in c pls assign me

**Comment by ritvij14** [comment]
I would like to take this in Java @iamrajiv

**Comment by ag278** [comment]
> @ag278 Ok, make sure you add both iterative and recursive method.

@iamrajiv do I need to make seperate files for both or I can add the iterative and recursive approach in the same file itself

**Comment by gupta-piyush19** [comment]
@iamrajiv I would like to work on this issue in JavaScript.

**Comment by iamrajiv** [comment]
@ag278 Add both the ways in the same file.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
