### ISSUE TITLE
Maximum Square Matrix With All 1s

### ISSUE THREAD

**Issue by sukritishah15** [HarshCasper/NeoAlgo#939]
## 🚀 Feature
Given an n*m matrix which contains only 0s and 1s, find out the size of maximum square sub-matrix with all 1s. You need to return the size of the side of maximum/largest square with all 1s.

Sample Input :
3 3
0 0 1
0 0 0
0 0 0

Sample Output :
1

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this issue as a part of CH20

## Assignees 

- @sukritishah15 : C++ 
- @ritvij14 : Java
- @nutanaarohi123 : C
- @rutujadhanawade : Python

It is a good DP problem.

**Comment by sukritishah15** [comment]
I would like to implement this in C++ as a part of CH20.
@SKAUL05 @atarax665 @Abhijit2505 @iamrajiv Please assign me this issue. Thank you!

**Comment by ritvij14** [comment]
I would like to take this in Java as a part of CH20.

**Comment by nutanaarohi123** [comment]
I would like to take this issue in C.

**Comment by rutujadhanawade** [comment]
I would like to take this in python

**Comment by ritvij14** [comment]
@sukritishah15 could you please make a small change? I have been assigned this in Java, but it's written C in the issue description, could you please change that to avoid confusion?

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ritvij14** [comment]
@HarshCasper please add difficulty level label to this issue.

**Comment by sukritishah15** [comment]
@HarshCasper Please add C-Plus-Plus and difficulty label for this issue.

**Comment by rutujadhanawade** [comment]
@HarshCasper  @iamrajiv please add difficulty label to this issue.

**Comment by nutanaarohi123** [comment]
pls add the difficulty label to this issue  @HarshCasper
