### ISSUE TITLE
Add Code Inspector GitHub Action

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#941]

**Comment by ymaheshwari1** [comment]
I am interested in working on this.

**Comment by iamrajiv** [comment]
@ymaheshwari1 Any updates

**Comment by ymaheshwari1** [comment]
> @ymaheshwari1 Any updates

Working on it

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ymaheshwari1** [comment]
@iamrajiv Is this solved or still open?

**Comment by iamrajiv** [comment]
@ymaheshwari1 It is open.
