### ISSUE TITLE
Connect links of pending programs in README.md

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#945]
## 📚 Documentation

Many of programs in `C-Plus-Plus`, `C-Sharp`, `C`, `Go`, `Java`, `JavaScript`, `Python` and `Q-Sharp` are not linked to there respective README files. Go through the files and check which program have not linked and link that program to the README. It would be nice if the programs are organised in alphabetical order. Also, make sure the markdowns are formatted using Prettier you can take help of this https://prettier.io/playground/.

I will be assigning one person per language section so that work gets distributed properly.

## Assignees

- C-Plus-Plus: @narayan2111
- C-Sharp: @rutujadhanawade
- C: @AdityaJ7
- Go: @SangeetaMishra
- Java: @ymaheshwari1
- JavaScript: @ritvij14
- Python: @AdityaJ7

**Comment by AdityaJ7** [comment]
I would like to solve the python part

**Comment by ymaheshwari1** [comment]
I like to work on the Java section

**Comment by SangeetaMishra** [comment]
I would like to take this for Go.

**Comment by AdityaJ7** [comment]
Can I work on the C language part of the issue?

**Comment by iamrajiv** [comment]
@AdityaJ7 Go ahead.

**Comment by SangeetaMishra** [comment]
I want to work in Go.

**Comment by narayan2111** [comment]
I want to work in C++

**Comment by ritvij14** [comment]
I would like to take the Javascript section.

**Comment by rutujadhanawade** [comment]
I want to take the C-sharp section

**Comment by raksha009** [comment]
I would like to work for Qsharp

**Comment by raksha009** [comment]
@iamrajiv  What do I change in readme of q-sharp. There isn't even a single code added there.

**Comment by iamrajiv** [comment]
@raksha009 Ok than leave that.

**Comment by ritvij14** [comment]
@iamrajiv there is a problem, all Java links for Sorting have been moved from the `Sorting` heading to the `Competitive programming` heading. Is that fine or should I change it??

It turned out this way due to #948

**Comment by ymaheshwari1** [comment]
@ritvij14 Let me check

**Comment by ymaheshwari1** [comment]
@ritvij14 Please look at this commit https://github.com/TesseractCoding/NeoAlgo/pull/948/commits/65aa2b1d4871ac60a8f0ba891167ffdafa7e739b
The problem is not due to #948 . I think it is due to something else.

**Comment by ritvij14** [comment]
@ymaheshwari1 oh yes you are right, it does seem to be from something else.
@iamrajiv sir, how should we proceed? I just made a PR #973, should I resolve it in that only?

**Comment by ymaheshwari1** [comment]
@ritvij14 @iamrajiv It is due to this commit https://github.com/TesseractCoding/NeoAlgo/commit/a6eaa72a36eaaa3df32666972d7d82a3f640b1f8#diff-057b6dba29349d96ba09dd23a6a146ba

**Comment by SangeetaMishra** [comment]
@iamrajiv Updated README.md for Go
