### ISSUE TITLE
Remove Outermost Parantheses

### ISSUE THREAD

**Issue by raksha009** [HarshCasper/NeoAlgo#955]
## 🚀 Feature

A valid parentheses string is either empty (""), "(" + A + ")", or A + B, where A and B are valid parentheses strings, and + represents string concatenation.  For example, "", "()", "(())()", and "(()(()))" are all valid parentheses strings.
A valid parentheses string S is primitive if it is nonempty, and there does not exist a way to split it into S = A+B, with A and B nonempty valid parentheses strings.
Given a valid parentheses string S, consider its primitive decomposition: S = P_1 + P_2 + ... + P_k, where P_i are primitive valid parentheses strings.
Return S after removing the outermost parentheses of every primitive string in the primitive decomposition of S.

Have you read the Contributing Guidelines on Pull Requests?
Yes

Motivation
Adding a new algorithm and hence making the repo more extensive.

## Language

- C-Plus-Plus: @yashaswibiyahut 
- C: @ag278 
- Go:
- Java: @raksha009
- JavaScript: @ritvij14
- Python: @salonishah01

**Comment by iamrajiv** [comment]
@raksha009 Choose any one language C++ or Java.

**Comment by raksha009** [comment]
Java😅

**Comment by iamrajiv** [comment]
@raksha009 Go ahead with Java.

**Comment by salonishah01** [comment]
Can I take up this problem in python?

**Comment by yashaswibiyahut** [comment]
I would like to do in cpp please assign me this issue. @iamrajiv

**Comment by iamrajiv** [comment]
> Can I take up this problem in python?

@salonishah01 Go ahead with C++.

**Comment by iamrajiv** [comment]
> Can I take up this problem in python?

@salonishah01 Go ahead with Python.

**Comment by iamrajiv** [comment]
> I would like to do in cpp please assign me this issue. @iamrajiv

@yashaswibiyahut Go ahead with C++.

**Comment by ritvij14** [comment]
I would like to take this in Javascript for CH20.

**Comment by ag278** [comment]
I would like to take this in issue in C for CH20.

**Comment by shraddhavp** [comment]
would like to take this issue in python if it is not assigned @iamrajiv

**Comment by iamrajiv** [comment]
@salonishah01 Are you still working on this since your last PR #962 was closed by you

**Comment by iamrajiv** [comment]
@salonishah01 Are you still working on this with Python since you last PR #962 was closed by you?

**Comment by salonishah01** [comment]
@iamrajiv I closed the previous PR mistakenly. I am making a new one.

**Comment by iamrajiv** [comment]
@salonishah01 Sure.
