### ISSUE TITLE
Encryption Algorithm using Tree or Graph

### ISSUE THREAD

**Issue by Mohitkumar6122** [HarshCasper/NeoAlgo#972]
## Feature
Most Algorithm uses key to encrypt the data.But by using tree or graph and by any suitable method (using xor, ascii , position of characters) we can encrypt and decrypt data without using explicit keys. Further it will a fun project . 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

**YES**

**Comment by Mohitkumar6122** [comment]
I would like to do this in C++ for CH20 @siddharth25pandey @Kajol-Kumari @iamrajiv @HarshCasper

**Comment by ritvij14** [comment]
I would like to do this in Java for CH20

**Comment by AdityaJ7** [comment]
I would like to do this in Python
