### ISSUE TITLE
Vigenere Cipher Algorithm

### ISSUE THREAD

**Issue by parjanyaacoder** [HarshCasper/NeoAlgo#974]
Vigenere Cipher Algorithm is a famous cryptographic algorithm.  Vigenère cipher is a method of encrypting alphabetic text by using a series of interwoven Caesar ciphers
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Pitch

The repository currently lacks this algorithm. It should be added to e added to the repo in all languages. 

## Assignees 

- @parjanyaacoder : Java
- @rutujadhanawade : Python 
- @SangeetaMishra : C++
- @SangeetaMishra : C
- @ankitaggarwal23 :C#

**Comment by parjanyaacoder** [comment]
@atarax665 @iamrajiv @siddharth25pandey 
I would like to implement it in Java. Please assign.

**Comment by rutujadhanawade** [comment]
I would like to do this in python.

**Comment by Halix267** [comment]
I would also like to work on this issue in python

**Comment by SangeetaMishra** [comment]
I would like to work in C++

**Comment by SangeetaMishra** [comment]
@HarshCasper Added code for C++

**Comment by SangeetaMishra** [comment]
@HarshCasper @iamrajiv I would like to work on this in C.

**Comment by iamrajiv** [comment]
@SangeetaMishra Sure.

**Comment by SangeetaMishra** [comment]
@iamrajiv  Added code for C

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by ankitaggarwal23** [comment]
I would like to work in c#

**Comment by ankitaggarwal23** [comment]
@iamrajiv @HarshCasper I would like to work in c#

**Comment by ankitaggarwal23** [comment]
@iamrajiv @HarshCasper Kindly review my PR #1233 .
