### ISSUE TITLE
Sudoku Solver

### ISSUE THREAD

**Issue by ishi0301** [HarshCasper/NeoAlgo#976]
## 🚀 Feature

Given a partially filled 9×9 2D array ‘grid[9][9]’, the goal is to assign digits (from 1 to 9) to the empty cells so that every row, column, and subgrid of size 3×3 contains exactly one instance of the digits from 1 to 9.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

## Pitch

It's a backtracking algorithm used to solve a sudoku.

## Assignees 

- Java: @ritvij14 
- C++: @ishi0301
- Python: @raksha009 
- C: @mahimagoyalx

**Comment by ritvij14** [comment]
I would like to take this in Java as a part of CH20

**Comment by narayan2111** [comment]
I would like to take this issue in C++

**Comment by ishi0301** [comment]
@HarshCasper @Abhijit2505  @iamrajiv @atarax665 @SKAUL05 I would like to implement this in C++ as a part of CH20. Please assign me this issue.

**Comment by raksha009** [comment]
I would like to take this issue in python.

**Comment by mahimagoyalx** [comment]
I would like to take this issue in C.

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)

**Comment by narayan2111** [comment]
Kindly assign this issue to me @iamrajiv
