### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by ishi0301** [HarshCasper/NeoAlgo#977]
## 🚀 Feature

Bucket Sort is a sorting technique that sorts the elements by first dividing the elements into several groups called buckets. The elements inside each bucket are sorted using any of the suitable sorting algorithms or recursively calling the same algorithm.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
yes

## Pitch

It should be implemented because it is quicker than bubble sort.Putting data into small buckets that can be sorted individually reduces the number of comparisons that need to be carried out

**Comment by ritvij14** [comment]
I think this is the same as #426
