### ISSUE TITLE
Russian Peasant algorithm

### ISSUE THREAD

**Issue by mahimagoyalx** [HarshCasper/NeoAlgo#978]
## 🚀 Feature

Russian Peasant algorithm to multiply two long numbers. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this issue as a part of CH20.

## Pitch

It is a quick way to convert two numbers to binary form, multiply them together, and convert back to our number system.

## Assignees

- C-Plus-Plus: @mahimagoyalx
- C: @SangeetaMishra
- Go:
- Java: @ritvij14
- JavaScript: @ritvij14 
- Python: @narayan2111

**Comment by mahimagoyalx** [comment]
I would like to implement this in C++ as a part of CH20.
@SKAUL05 @atarax665 @Abhijit2505 @iamrajiv Please assign me this issue. Thank you!

**Comment by ritvij14** [comment]
I would like to take this in java and javascript as part of CH20.

**Comment by narayan2111** [comment]
I would like to work on this issue in python

**Comment by SangeetaMishra** [comment]
I would like to work in C.

**Comment by SangeetaMishra** [comment]
@iamrajiv I have added the C++ code

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
