### ISSUE TITLE
Swap Two Nibbles

### ISSUE THREAD

**Issue by mahimagoyalx** [HarshCasper/NeoAlgo#980]
## 🚀 Feature

Given a byte, swap the two nibbles in it. 

For example 100 is be represented as 01100100 in a byte (or 8 bits). The two nibbles are (0110) and (0100). If we swap the two nibbles, we get 01000110 which is 70 in decimal.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this issue as a part of CH20.

## Pitch

It is a good bit manipulation problem.

## Assignees 

- C++: @mahimagoyalx
- Java: @ritvij14
- Python: @narayan2111
- C: @ag278

**Comment by mahimagoyalx** [comment]
I would like to implement this in C++ as a part of CH20.
@HarshCasper @SKAUL05 @atarax665 @Abhijit2505 @iamrajiv Please assign me this issue. Thank you!

**Comment by mahimagoyalx** [comment]
@HarshCasper @SKAUL05 @atarax665 @Abhijit2505 @iamrajiv Please assign me this issue. Thank you!

**Comment by mahimagoyalx** [comment]
I would like to implement this in C++ as a part of CH20.
@HarshCasper @SKAUL05 @atarax665 @Abhijit2505 @iamrajiv Please assign me this issue. Thank you!

**Comment by ritvij14** [comment]
I would like to take this in Java for CH20.

**Comment by narayan2111** [comment]
I would like to work on this issue in python

**Comment by ag278** [comment]
I would like to solve this issue in C for CH20

**Comment by rutujadhanawade** [comment]
I would like to do this in C#

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
