### ISSUE TITLE
Format all Python programs according to PEP 8 rules which are not formatted

### ISSUE THREAD

**Issue by iamrajiv** [HarshCasper/NeoAlgo#985]
## 🐛 Bug Report

Many of the Python programs are not formatted according to PEP 8 rules. It would be nice if all the programs get formatted according to PEP 8 rules which are not formatted. I would recommend using Sublime Package Control or Visual Studio Code Extensions so that the programs get formatted easily. You can also use https://pypi.org/project/autopep8/ and https://github.com/google/yapf.

After formatting, all the codes do check that all the programs are running fine.

**Comment by SangeetaMishra** [comment]
I would like to take this issue

**Comment by iamrajiv** [comment]
@SangeetaMishra Sure.

**Comment by SangeetaMishra** [comment]
@iamrajiv I have changed the python programs according to PEP 8 rules.
