### ISSUE TITLE
Unique Number-II

### ISSUE THREAD

**Issue by mahimagoyalx** [HarshCasper/NeoAlgo#987]
## 🚀 Feature

Given an array A containing 2*N+2 positive, out of which 2*N numbers exist in pairs whereas the other two number occur exactly once and are distinct. Find the other two numbers  (in ascending order).

Sample Input:
1 2 4 2 1 3

Sample Output:
3 4

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

I want to solve this issue as a part of CH20.

## Pitch

It is a quick way to find the two non-repeating elements in an array of repeating elements using bit manipulation other than sorting.

**Comment by mahimagoyalx** [comment]
I would like to implement this in C++ as a part of CH20.
@SKAUL05 @atarax665 @Abhijit2505 @iamrajiv @HarshCasper  Please assign me this issue. Thank you!

**Comment by ishi0301** [comment]
I would like to implement this in C. @HarshCasper @Abhijit2505 @atarax665 @SKAUL05.

**Comment by ritvij14** [comment]
I would like to try this in java for CH20.

**Comment by narayan2111** [comment]
This is duplicate issue, it already exists. #922
