### ISSUE TITLE
Check for Subsequence

### ISSUE THREAD

**Issue by samyukta20** [HarshCasper/NeoAlgo#993]
## 🚀 Feature

(A clear and concise description of what the feature is.)

There are two strings. Find if first string is a subsequence of second string or not.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation
Time complexity should be linear.

## Assignees 

- @samyukta20 : C++
- @yashaswibiyahut : Python 
- @rohangawhade : Java
- @ag278 : C

**Comment by samyukta20** [comment]
I want to work on this in Cpp as part of CH20. Please assign me this.
@SKAUL05 @iamrajiv @HarshCasper @Kajol-Kumari

**Comment by yashaswibiyahut** [comment]
I want to work on this in python as part of CH20. Please assign me this.
@SKAUL05 @iamrajiv @HarshCasper @Kajol-Kumari

**Comment by rohangawhade** [comment]
I would like to work on this in Java as a part of CH20. Kindly assign me this issue in Java
@SKAUL05 @iamrajiv @HarshCasper @Kajol-Kumari @Abhijit2505

**Comment by ag278** [comment]
I would like to work on this issue in C as part of CH20. Please assign me this issue @iamrajiv @HarshCasper @Kajol-Kumari

**Comment by ag278** [comment]
@iamrajiv @atarax665 @SKAUL05 please add CH20 and level tag for this issue

**Comment by HarshCasper** [comment]
We are logging the scores for the <b>Contributor's Hack 2020</b>. If you have one or more than one PR merged during the program, make sure to fill this [form](https://forms.gle/jG7kDteT5EAz23hk7)
